var searchData=
[
  ['sam_20parts_0',['SAM parts',['../group__sam__part__macros__group.html',1,'']]],
  ['same70j19_20definitions_1',['SAME70J19 definitions',['../group___s_a_m_e70_j19__definitions.html',1,'']]],
  ['same70j19b_20definitions_2',['SAME70J19B definitions',['../group___s_a_m_e70_j19_b__definitions.html',1,'']]],
  ['same70j20_20definitions_3',['SAME70J20 definitions',['../group___s_a_m_e70_j20__definitions.html',1,'']]],
  ['same70j20b_20definitions_4',['SAME70J20B definitions',['../group___s_a_m_e70_j20_b__definitions.html',1,'']]],
  ['same70j21_20definitions_5',['SAME70J21 definitions',['../group___s_a_m_e70_j21__definitions.html',1,'']]],
  ['same70j21b_20definitions_6',['SAME70J21B definitions',['../group___s_a_m_e70_j21_b__definitions.html',1,'']]],
  ['same70n19_20definitions_7',['SAME70N19 definitions',['../group___s_a_m_e70_n19__definitions.html',1,'']]],
  ['same70n19b_20definitions_8',['SAME70N19B definitions',['../group___s_a_m_e70_n19_b__definitions.html',1,'']]],
  ['same70n20_20definitions_9',['SAME70N20 definitions',['../group___s_a_m_e70_n20__definitions.html',1,'']]],
  ['same70n20b_20definitions_10',['SAME70N20B definitions',['../group___s_a_m_e70_n20_b__definitions.html',1,'']]],
  ['same70n21_20definitions_11',['SAME70N21 definitions',['../group___s_a_m_e70_n21__definitions.html',1,'']]],
  ['same70n21b_20definitions_12',['SAME70N21B definitions',['../group___s_a_m_e70_n21_b__definitions.html',1,'']]],
  ['same70q19_20definitions_13',['SAME70Q19 definitions',['../group___s_a_m_e70_q19__definitions.html',1,'']]],
  ['same70q19b_20definitions_14',['SAME70Q19B definitions',['../group___s_a_m_e70_q19_b__definitions.html',1,'']]],
  ['same70q20_20definitions_15',['SAME70Q20 definitions',['../group___s_a_m_e70_q20__definitions.html',1,'']]],
  ['same70q20b_20definitions_16',['SAME70Q20B definitions',['../group___s_a_m_e70_q20_b__definitions.html',1,'']]],
  ['same70q21_20definitions_17',['SAME70Q21 definitions',['../group___s_a_m_e70_q21__definitions.html',1,'']]],
  ['same70q21b_20definitions_18',['SAME70Q21B definitions',['../group___s_a_m_e70_q21_b__definitions.html',1,'']]],
  ['scanning_19',['Scanning',['../group___w_l_a_n_s_c_a_n.html',1,'']]],
  ['sdram_20controller_20',['SDRAM Controller',['../group___s_a_m_e70___s_d_r_a_m_c.html',1,'']]],
  ['secure_21',['secure',['../group___secure_fn.html',1,'']]],
  ['send_22',['send',['../group___send_fn.html',1,'']]],
  ['sendto_23',['sendto',['../group___send_to_socket_fn.html',1,'']]],
  ['serial_20interface_20_28serial_29_24',['Serial Interface (Serial)',['../group__serial__group.html',1,'']]],
  ['serial_20peripheral_20interface_25',['Serial Peripheral Interface',['../group___s_a_m_e70___s_p_i.html',1,'']]],
  ['serial_20peripheral_20interface_20_28spi_29_26',['Serial Peripheral Interface (SPI)',['../group__sam__drivers__spi__group.html',1,'(Global Namespace)'],['../group__spi__group.html',1,'(Global Namespace)']]],
  ['setsockopt_27',['setsockopt',['../group___set_socket_option_fn.html',1,'']]],
  ['socket_28',['socket',['../group___socket_fn.html',1,'']]],
  ['socket_29',['Socket',['../group___socket_header.html',1,'']]],
  ['socketdeinit_30',['socketDeInit',['../group___socket_de_initialization_fn.html',1,'']]],
  ['socketinit_31',['socketInit',['../group___socket_initialization_fn.html',1,'']]],
  ['socketstate_32',['socketState',['../group___socket_state_fn.html',1,'']]],
  ['spi_20flash_33',['Spi Flash',['../group___s_p_i_f_l_a_s_h.html',1,'']]],
  ['spi_5fflash_5ferase_34',['spi_flash_erase',['../group___s_pi_flash_erase.html',1,'']]],
  ['spi_5fflash_5fget_5fsize_35',['spi_flash_get_size',['../group___s_pi_flash_get_fn.html',1,'']]],
  ['spi_5fflash_5fwrite_36',['spi_flash_write',['../group___s_pi_flash_write.html',1,'']]],
  ['spi_5fflexible_5fflash_5ffind_5fsection_37',['spi_flexible_flash_find_section',['../group___s_pi_flash_read.html',1,'']]],
  ['ssl_38',['SSL',['../group___s_s_l_a_p_i.html',1,'']]],
  ['sslenablecertexpirationcheck_39',['sslEnableCertExpirationCheck',['../group__ssl_enable_cert_expiration_check_fn.html',1,'']]],
  ['standard_20i_2fo_20_28stdio_29_40',['Standard I/O (stdio)',['../group__group__common__utils__stdio.html',1,'']]],
  ['standard_20serial_20i_2fo_20_28stdio_29_41',['Standard serial I/O (stdio)',['../group__group__common__utils__stdio__stdio__serial.html',1,'']]],
  ['static_20memory_20controller_42',['Static Memory Controller',['../group___s_a_m_e70___s_m_c.html',1,'']]],
  ['supply_20controller_43',['Supply Controller',['../group___s_a_m_e70___s_u_p_c.html',1,'']]],
  ['synchronous_20serial_20controller_44',['Synchronous Serial Controller',['../group___s_a_m_e70___s_s_c.html',1,'']]],
  ['system_20clock_20management_45',['System Clock Management',['../group__sysclk__group.html',1,'']]],
  ['system_20time_46',['System Time',['../group___w_l_a_n_t_i_m_e.html',1,'']]]
];
