var searchData=
[
  ['parallel_20input_2foutput_20controller_0',['Parallel Input/Output Controller',['../group___s_a_m_e70___p_i_o.html',1,'']]],
  ['peripheral_20base_20address_20definitions_1',['Peripheral Base Address Definitions',['../group___s_a_m_e70_j19__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j19_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j20__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j20_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j21__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j21_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n19__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n19_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n20__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n20_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n21__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n21_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q19__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q19_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q20__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q20_b__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q21__base.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q21_b__base.html',1,'(Global Namespace)']]],
  ['peripheral_20ids_20definitions_2',['Peripheral Ids Definitions',['../group___s_a_m_e70_j19__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j19_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j20__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j20_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j21__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j21_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n19__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n19_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n20__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n20_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n21__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n21_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q19__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q19_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q20__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q20_b__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q21__id.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q21_b__id.html',1,'(Global Namespace)']]],
  ['peripheral_20parallel_20input_2foutput_20_28pio_29_20controller_3',['Peripheral Parallel Input/Output (PIO) Controller',['../group__sam__drivers__pio__group.html',1,'']]],
  ['peripheral_20pio_20definitions_4',['Peripheral Pio Definitions',['../group___s_a_m_e70_j19__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j19_b__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j20__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j20_b__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j21__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j21_b__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n19__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n19_b__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n20__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n20_b__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n21__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n21_b__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q19__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q19_b__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q20__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q20_b__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q21__pio.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q21_b__pio.html',1,'(Global Namespace)']]],
  ['peripheral_20software_20api_5',['Peripheral Software API',['../group___s_a_m_e70_j19__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j19_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j20__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j20_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j21__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_j21_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n19__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n19_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n20__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n20_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n21__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_n21_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q19__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q19_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q20__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q20_b__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q21__api.html',1,'(Global Namespace)'],['../group___s_a_m_e70_q21_b__api.html',1,'(Global Namespace)']]],
  ['pll_20management_6',['PLL Management',['../group__pll__group.html',1,'']]],
  ['power_20management_20controller_7',['Power Management Controller',['../group___s_a_m_e70___p_m_c.html',1,'']]],
  ['power_20management_20controller_20_28pmc_29_8',['Power Management Controller (PMC)',['../group__sam__drivers__pmc__group.html',1,'']]],
  ['power_20manager_20_28pm_29_9',['Power Manager (PM)',['../group__sleep__group.html',1,'']]],
  ['power_20save_10',['Power Save',['../group___w_l_a_n_p_s.html',1,'']]],
  ['preprocessor_20_2d_20macro_20repeat_11',['Preprocessor - Macro Repeat',['../group__group__sam__utils__mrepeat.html',1,'']]],
  ['preprocessor_20_2d_20stringize_12',['Preprocessor - Stringize',['../group__group__sam__utils__stringz.html',1,'']]],
  ['preprocessor_20_2d_20token_20paste_13',['Preprocessor - Token Paste',['../group__group__sam__utils__tpaste.html',1,'']]],
  ['provisioning_14',['Provisioning',['../group___w_l_a_n_p_r_o_v_i_s_i_o_n.html',1,'']]],
  ['pulse_20width_20modulation_20controller_15',['Pulse Width Modulation Controller',['../group___s_a_m_e70___p_w_m.html',1,'']]]
];
