WINC1500 Weather Client Demo for SAME70 Xplained: spi.h File Reference
drivers/spi/spi.h File Reference
Serial Peripheral Interface (SPI) driver for SAM.
#include "compiler.h"
Macros
#define spi_get_pcs(chip_sel_id) ((~(1u<<(chip_sel_id)))&0xF)
Generate Peripheral Chip Select Value from Chip Select ID.
#define SPI_TIMEOUT 15000
Time-out value (number of attempts).
Typedefs
typedef enum spi_cs_behavior spi_cs_behavior_t
SPI Chip Select behavior modes while transferring.
Enumerations
enum spi_cs_behavior {
SPI_CS_KEEP_LOW = SPI_CSR_CSAAT ,
SPI_CS_RISE_NO_TX = 0 ,
SPI_CS_RISE_FORCED = SPI_CSR_CSNAAT
}
SPI Chip Select behavior modes while transferring.
enum spi_status_t {
SPI_ERROR = -1 ,
SPI_OK = 0 ,
SPI_ERROR_TIMEOUT = 1 ,
SPI_ERROR_ARGUMENT ,
SPI_ERROR_OVERRUN ,
SPI_ERROR_MODE_FAULT ,
SPI_ERROR_OVERRUN_AND_MODE_FAULT
}
Status codes used by the SPI driver.
Functions
int16_t spi_calc_baudrate_div (const uint32_t baudrate, uint32_t mck)
Calculate the baudrate divider.
void spi_configure_cs_behavior (Spi *p_spi, uint32_t ul_pcs_ch, uint32_t ul_cs_behavior)
Configure CS behavior for SPI transfer (spi_cs_behavior_t).
static void spi_disable (Spi *p_spi)
Disable SPI.
void spi_disable_clock (Spi *p_spi)
Disable SPI clock.
static void spi_disable_interrupt (Spi *p_spi, uint32_t ul_sources)
Disable SPI interrupts.
static void spi_disable_loopback (Spi *p_spi)
Disable loopback mode.
static void spi_disable_mode_fault_detect (Spi *p_spi)
Disable Mode Fault Detection.
static void spi_disable_peripheral_select_decode (Spi *p_spi)
Disable Peripheral Select Decode.
static void spi_disable_tx_on_rx_empty (Spi *p_spi)
Disable waiting RX_EMPTY before transfer starts.
static void spi_enable (Spi *p_spi)
Enable SPI.
void spi_enable_clock (Spi *p_spi)
Enable SPI clock.
static void spi_enable_interrupt (Spi *p_spi, uint32_t ul_sources)
Enable SPI interrupts.
static void spi_enable_loopback (Spi *p_spi)
Enable loopback mode.
static void spi_enable_mode_fault_detect (Spi *p_spi)
Enable Mode Fault Detection.
static void spi_enable_peripheral_select_decode (Spi *p_spi)
Enable Peripheral Select Decode.
static void spi_enable_tx_on_rx_empty (Spi *p_spi)
Enable waiting RX_EMPTY before transfer starts.
static uint16_t spi_get (Spi *p_spi)
Get one data to a SPI peripheral.
static uint32_t spi_get_mode (Spi *p_spi)
Get SPI work mode.
static uint32_t spi_get_mode_fault_detect_setting (Spi *p_spi)
Check if mode fault detection is enabled.
static uint32_t spi_get_peripheral_select_decode_setting (Spi *p_spi)
Get Peripheral Select Decode mode.
static uint32_t spi_get_peripheral_select_mode (Spi *p_spi)
Get Peripheral Select mode.
static uint32_t spi_get_tx_on_rx_empty_setting (Spi *p_spi)
Check if SPI waits RX_EMPTY before transfer starts.
uint32_t spi_get_writeprotect_status (Spi *p_spi)
Indicate write protect status.
static uint32_t spi_is_enabled (Spi *p_spi)
Test if the SPI is enabled.
static uint32_t spi_is_rx_full (Spi *p_spi)
Check if the SPI contains a received character.
static uint32_t spi_is_rx_ready (Spi *p_spi)
Check if all receptions are ready.
static uint32_t spi_is_tx_empty (Spi *p_spi)
Check if all transmissions are complete.
static uint32_t spi_is_tx_ready (Spi *p_spi)
Check if all transmissions are ready.
static void spi_put (Spi *p_spi, uint16_t data)
Put one data to a SPI peripheral.
spi_status_t spi_read (Spi *p_spi, uint16_t *us_data, uint8_t *p_pcs)
Read the received data and it's peripheral chip select value.
static uint32_t spi_read_interrupt_mask (Spi *p_spi)
Read SPI interrupt mask.
static uint32_t spi_read_status (Spi *p_spi)
Read status register.
static void spi_reset (Spi *p_spi)
Reset SPI and set it to Slave mode.
int16_t spi_set_baudrate_div (Spi *p_spi, uint32_t ul_pcs_ch, uint8_t uc_baudrate_divider)
Set Serial Clock Baud Rate divider value (SCBR).
void spi_set_bits_per_transfer (Spi *p_spi, uint32_t ul_pcs_ch, uint32_t ul_bits)
Set number of bits per transfer.
void spi_set_clock_phase (Spi *p_spi, uint32_t ul_pcs_ch, uint32_t ul_phase)
Set Data Capture Phase.
void spi_set_clock_polarity (Spi *p_spi, uint32_t ul_pcs_ch, uint32_t ul_polarity)
Set clock default state.
void spi_set_delay_between_chip_select (Spi *p_spi, uint32_t ul_delay)
Set delay between chip selects (in number of MCK clocks).
static void spi_set_fixed_peripheral_select (Spi *p_spi)
Set Fixed Peripheral Select.
static void spi_set_lastxfer (Spi *p_spi)
Issue a LASTXFER command.
static void spi_set_master_mode (Spi *p_spi)
Set SPI to Master mode.
void spi_set_peripheral_chip_select_value (Spi *p_spi, uint32_t ul_value)
Set Peripheral Chip Select (PCS) value.
static void spi_set_slave_mode (Spi *p_spi)
Set SPI to Slave mode.
void spi_set_transfer_delay (Spi *p_spi, uint32_t ul_pcs_ch, uint8_t uc_dlybs, uint8_t uc_dlybct)
Configure timing for SPI transfer.
static void spi_set_variable_peripheral_select (Spi *p_spi)
Set Variable Peripheral Select.
void spi_set_writeprotect (Spi *p_spi, uint32_t ul_enable)
Enable or disable write protection of SPI registers.
spi_status_t spi_write (Spi *p_spi, uint16_t us_data, uint8_t uc_pcs, uint8_t uc_last)
Write the transmitted data with specified peripheral chip select value.
Detailed Description
Serial Peripheral Interface (SPI) driver for SAM.
Copyright (c) 2011-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file drivers/spi/spi.h.
Macro Definition Documentation
spi_get_pcs
#define spi_get_pcs (chip_sel_id) ((~(1u<<(chip_sel_id)))&0xF)
Generate Peripheral Chip Select Value from Chip Select ID.
Note
When chip select n is working, PCS bit n is set to low level.
Parameters
chip_sel_id The chip select number used
Definition at line 81 of file drivers/spi/spi.h.
SPI_TIMEOUT
#define SPI_TIMEOUT 15000
Time-out value (number of attempts).
Definition at line 51 of file drivers/spi/spi.h.
Typedef Documentation
spi_cs_behavior_t
typedef enum spi_cs_behavior spi_cs_behavior_t
SPI Chip Select behavior modes while transferring.
Enumeration Type Documentation
spi_cs_behavior
enum spi_cs_behavior
SPI Chip Select behavior modes while transferring.
Enumerator
SPI_CS_KEEP_LOW
CS does not rise until a new transfer is requested on different chip select.
SPI_CS_RISE_NO_TX
CS rises if there is no more data to transfer.
SPI_CS_RISE_FORCED
CS is de-asserted systematically during a time DLYBCS.
Definition at line 66 of file drivers/spi/spi.h.
{
    SPI_CS_KEEP_LOW = SPI_CSR_CSAAT,
    SPI_CS_RISE_NO_TX = 0,
    SPI_CS_RISE_FORCED = SPI_CSR_CSNAAT
} spi_cs_behavior_t;
spi_status_t
enum spi_status_t
Status codes used by the SPI driver.
Enumerator
SPI_ERROR
SPI_OK
SPI_ERROR_TIMEOUT
SPI_ERROR_ARGUMENT
SPI_ERROR_OVERRUN
SPI_ERROR_MODE_FAULT
SPI_ERROR_OVERRUN_AND_MODE_FAULT
Definition at line 54 of file drivers/spi/spi.h.
{
    SPI_ERROR = -1,
    SPI_OK = 0,
    SPI_ERROR_TIMEOUT = 1,
    SPI_ERROR_ARGUMENT,
    SPI_ERROR_OVERRUN,
    SPI_ERROR_MODE_FAULT,
    SPI_ERROR_OVERRUN_AND_MODE_FAULT
} spi_status_t;
Function Documentation
spi_disable()
static void spi_disable (Spi * p_spi) inline static
Disable SPI.
Note
CS is de-asserted, which indicates that the last data is done, and user should check TX_EMPTY before disabling SPI.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 111 of file drivers/spi/spi.h.
{
    p_spi->SPI_CR = SPI_CR_SPIDIS;
}
References Spi::SPI_CR, and SPI_CR_SPIDIS.
Referenced by nm_bus_deinit(), and nm_bus_init().
spi_disable_interrupt()
static void spi_disable_interrupt (Spi * p_spi, uint32_t ul_sources) inline static
Disable SPI interrupts.
Parameters
p_spi Pointer to an SPI instance.
ul_sources Interrupts to be disabled.
Definition at line 472 of file drivers/spi/spi.h.
{
    p_spi->SPI_IDR = ul_sources;
}
References Spi::SPI_IDR.
spi_disable_loopback()
static void spi_disable_loopback (Spi * p_spi) inline static
Disable loopback mode.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 324 of file drivers/spi/spi.h.
{
    p_spi->SPI_MR &= (~SPI_MR_LLB);
}
References Spi::SPI_MR.
Referenced by spi_master_init().
spi_disable_mode_fault_detect()
static void spi_disable_mode_fault_detect (Spi * p_spi) inline static
Disable Mode Fault Detection.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 252 of file drivers/spi/spi.h.
{
    p_spi->SPI_MR |= SPI_MR_MODFDIS;
}
References Spi::SPI_MR, and SPI_MR_MODFDIS.
Referenced by nm_bus_init(), and spi_master_init().
spi_disable_peripheral_select_decode()
static void spi_disable_peripheral_select_decode (Spi * p_spi) inline static
Disable Peripheral Select Decode.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 216 of file drivers/spi/spi.h.
{
    p_spi->SPI_MR &= (~SPI_MR_PCSDEC);
}
References Spi::SPI_MR.
Referenced by spi_master_init().
spi_disable_tx_on_rx_empty()
static void spi_disable_tx_on_rx_empty (Spi * p_spi) inline static
Disable waiting RX_EMPTY before transfer starts.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 288 of file drivers/spi/spi.h.
{
    p_spi->SPI_MR &= (~SPI_MR_WDRBT);
}
References Spi::SPI_MR.
spi_enable()
static void spi_enable (Spi * p_spi) inline static
Enable SPI.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 98 of file drivers/spi/spi.h.
{
    p_spi->SPI_CR = SPI_CR_SPIEN;
}
References Spi::SPI_CR, and SPI_CR_SPIEN.
Referenced by ili9488_init(), and nm_bus_init().
spi_enable_interrupt()
static void spi_enable_interrupt (Spi * p_spi, uint32_t ul_sources) inline static
Enable SPI interrupts.
Parameters
p_spi Pointer to an SPI instance.
ul_sources Interrupts to be enabled.
Definition at line 461 of file drivers/spi/spi.h.
{
    p_spi->SPI_IER = ul_sources;
}
References Spi::SPI_IER.
Referenced by ili9488_init().
spi_enable_loopback()
static void spi_enable_loopback (Spi * p_spi) inline static
Enable loopback mode.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 314 of file drivers/spi/spi.h.
{
    p_spi->SPI_MR |= SPI_MR_LLB;
}
References Spi::SPI_MR, and SPI_MR_LLB.
spi_enable_mode_fault_detect()
static void spi_enable_mode_fault_detect (Spi * p_spi) inline static
Enable Mode Fault Detection.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 242 of file drivers/spi/spi.h.
{
    p_spi->SPI_MR &= (~SPI_MR_MODFDIS);
}
References Spi::SPI_MR.
spi_enable_peripheral_select_decode()
static void spi_enable_peripheral_select_decode (Spi * p_spi) inline static
Enable Peripheral Select Decode.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 206 of file drivers/spi/spi.h.
{
    p_spi->SPI_MR |= SPI_MR_PCSDEC;
}
References Spi::SPI_MR, and SPI_MR_PCSDEC.
spi_enable_tx_on_rx_empty()
static void spi_enable_tx_on_rx_empty (Spi * p_spi) inline static
Enable waiting RX_EMPTY before transfer starts.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 278 of file drivers/spi/spi.h.
{
    p_spi->SPI_MR |= SPI_MR_WDRBT;
}
References Spi::SPI_MR, and SPI_MR_WDRBT.
spi_get()
static uint16_t spi_get (Spi * p_spi) inline static
Get one data to a SPI peripheral.
Parameters
p_spi Base address of the SPI instance.
Returns
The data byte
Definition at line 383 of file drivers/spi/spi.h.
{
    return (p_spi->SPI_RDR & SPI_RDR_RD_Msk);
}
References Spi::SPI_RDR, and SPI_RDR_RD_Msk.
Referenced by spi_read_single().
spi_get_mode()
static uint32_t spi_get_mode (Spi * p_spi) inline static
Get SPI work mode.
Parameters
p_spi Pointer to an SPI instance.
Returns
1 for master mode, 0 for slave mode.
Definition at line 154 of file drivers/spi/spi.h.
{
    if (p_spi->SPI_MR & SPI_MR_MSTR) {
        return 1;
    } else {
        return 0;
    }
}
References Spi::SPI_MR, and SPI_MR_MSTR.
spi_get_mode_fault_detect_setting()
static uint32_t spi_get_mode_fault_detect_setting (Spi * p_spi) inline static
Check if mode fault detection is enabled.
Parameters
p_spi Pointer to an SPI instance.
Returns
1 for disabled, 0 for enabled.
Definition at line 264 of file drivers/spi/spi.h.
{
    if (p_spi->SPI_MR & SPI_MR_MODFDIS) {
        return 1;
    } else {
        return 0;
    }
}
References Spi::SPI_MR, and SPI_MR_MODFDIS.
spi_get_peripheral_select_decode_setting()
static uint32_t spi_get_peripheral_select_decode_setting (Spi * p_spi) inline static
Get Peripheral Select Decode mode.
Parameters
p_spi Pointer to an SPI instance.
Returns
1 for decode mode, 0 for direct mode.
Definition at line 228 of file drivers/spi/spi.h.
{
    if (p_spi->SPI_MR & SPI_MR_PCSDEC) {
        return 1;
    } else {
        return 0;
    }
}
References Spi::SPI_MR, and SPI_MR_PCSDEC.
Referenced by spi_select_device().
spi_get_peripheral_select_mode()
static uint32_t spi_get_peripheral_select_mode (Spi * p_spi) inline static
Get Peripheral Select mode.
Parameters
p_spi Pointer to an SPI instance.
Returns
1 for Variable mode, 0 for fixed mode.
Definition at line 192 of file drivers/spi/spi.h.
{
    if (p_spi->SPI_MR & SPI_MR_PS) {
        return 1;
    } else {
        return 0;
    }
}
References Spi::SPI_MR, and SPI_MR_PS.
Referenced by spi_read(), and spi_write().
spi_get_tx_on_rx_empty_setting()
static uint32_t spi_get_tx_on_rx_empty_setting (Spi * p_spi) inline static
Check if SPI waits RX_EMPTY before transfer starts.
Parameters
p_spi Pointer to an SPI instance.
Returns
1 for SPI waits, 0 for no wait.
Definition at line 300 of file drivers/spi/spi.h.
{
    if (p_spi->SPI_MR & SPI_MR_WDRBT) {
        return 1;
    } else {
        return 0;
    }
}
References Spi::SPI_MR, and SPI_MR_WDRBT.
spi_is_enabled()
static uint32_t spi_is_enabled (Spi * p_spi) inline static
Test if the SPI is enabled.
Parameters
p_spi Pointer to an SPI instance.
Returns
1 if the SPI is enabled, otherwise 0.
Definition at line 356 of file drivers/spi/spi.h.
{
    if (p_spi->SPI_SR & SPI_SR_SPIENS) {
        return 1;
    } else {
        return 0;
    }
}
References Spi::SPI_SR, and SPI_SR_SPIENS.
spi_is_rx_full()
static uint32_t spi_is_rx_full (Spi * p_spi) inline static
Check if the SPI contains a received character.
Parameters
p_spi Pointer to an SPI instance.
Returns
1 if the SPI Receive Holding Register is full, otherwise 0.
Definition at line 429 of file drivers/spi/spi.h.
{
    if (p_spi->SPI_SR & SPI_SR_RDRF) {
        return 1;
    } else {
        return 0;
    }
}
References Spi::SPI_SR, and SPI_SR_RDRF.
spi_is_rx_ready()
static uint32_t spi_is_rx_ready (Spi * p_spi) inline static
Check if all receptions are ready.
Parameters
p_spi Pointer to an SPI instance.
Returns
1 if the SPI Receiver is ready, otherwise 0.
Definition at line 445 of file drivers/spi/spi.h.
{
    if ((p_spi->SPI_SR & (SPI_SR_RDRF | SPI_SR_TXEMPTY))
            == (SPI_SR_RDRF | SPI_SR_TXEMPTY)) {
        return 1;
    } else {
        return 0;
    }
}
References Spi::SPI_SR, SPI_SR_RDRF, and SPI_SR_TXEMPTY.
Referenced by spi_read_packet(), and spi_transceive_packet().
spi_is_tx_empty()
static uint32_t spi_is_tx_empty (Spi * p_spi) inline static
Check if all transmissions are complete.
Parameters
p_spi Pointer to an SPI instance.
Return values
1 if transmissions are complete.
0 if transmissions are not complete.
Definition at line 396 of file drivers/spi/spi.h.
{
    if (p_spi->SPI_SR & SPI_SR_TXEMPTY) {
        return 1;
    } else {
        return 0;
    }
}
References Spi::SPI_SR, and SPI_SR_TXEMPTY.
Referenced by spi_deselect_device().
spi_is_tx_ready()
static uint32_t spi_is_tx_ready (Spi * p_spi) inline static
Check if all transmissions are ready.
Parameters
p_spi Pointer to an SPI instance.
Return values
1 if transmissions are complete.
0 if transmissions are not complete.
Definition at line 413 of file drivers/spi/spi.h.
{
    if (p_spi->SPI_SR & SPI_SR_TDRE) {
        return 1;
    } else {
        return 0;
    }
}
References Spi::SPI_SR, and SPI_SR_TDRE.
Referenced by spi_read_packet(), spi_transceive_packet(), and spi_write_packet().
spi_put()
static void spi_put (Spi * p_spi, uint16_t data) inline static
Put one data to a SPI peripheral.
Parameters
p_spi Base address of the SPI instance.
data The data byte to be loaded
Definition at line 372 of file drivers/spi/spi.h.
{
    p_spi->SPI_TDR = SPI_TDR_TD(data);
}
References Spi::SPI_TDR, and SPI_TDR_TD.
Referenced by spi_write_single().
spi_read_interrupt_mask()
static uint32_t spi_read_interrupt_mask (Spi * p_spi) inline static
Read SPI interrupt mask.
Parameters
p_spi Pointer to an SPI instance.
Returns
The interrupt mask value.
Definition at line 484 of file drivers/spi/spi.h.
{
    return p_spi->SPI_IMR;
}
References Spi::SPI_IMR.
spi_read_status()
static uint32_t spi_read_status (Spi * p_spi) inline static
Read status register.
Parameters
p_spi Pointer to an SPI instance.
Returns
SPI status register value.
Definition at line 344 of file drivers/spi/spi.h.
{
    return p_spi->SPI_SR;
}
References Spi::SPI_SR.
spi_reset()
static void spi_reset (Spi * p_spi) inline static
Reset SPI and set it to Slave mode.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 88 of file drivers/spi/spi.h.
{
    p_spi->SPI_CR = SPI_CR_SWRST;
}
References Spi::SPI_CR, and SPI_CR_SWRST.
Referenced by nm_bus_init(), and spi_master_init().
spi_set_fixed_peripheral_select()
static void spi_set_fixed_peripheral_select (Spi * p_spi) inline static
Set Fixed Peripheral Select.
Peripheral Chip Select is controlled by SPI_MR.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 180 of file drivers/spi/spi.h.
{
    p_spi->SPI_MR &= (~SPI_MR_PS);
}
References Spi::SPI_MR.
Referenced by spi_master_init().
spi_set_lastxfer()
static void spi_set_lastxfer (Spi * p_spi) inline static
Issue a LASTXFER command.
The next transfer is the last transfer and after that CS is de-asserted.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 122 of file drivers/spi/spi.h.
{
    p_spi->SPI_CR = SPI_CR_LASTXFER;
}
References Spi::SPI_CR, and SPI_CR_LASTXFER.
Referenced by spi_deselect_device().
spi_set_master_mode()
static void spi_set_master_mode (Spi * p_spi) inline static
Set SPI to Master mode.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 132 of file drivers/spi/spi.h.
{
    p_spi->SPI_MR |= SPI_MR_MSTR;
}
References Spi::SPI_MR, and SPI_MR_MSTR.
Referenced by nm_bus_init(), and spi_master_init().
spi_set_slave_mode()
static void spi_set_slave_mode (Spi * p_spi) inline static
Set SPI to Slave mode.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 142 of file drivers/spi/spi.h.
{
    p_spi->SPI_MR &= (~SPI_MR_MSTR);
}
References Spi::SPI_MR.
spi_set_variable_peripheral_select()
static void spi_set_variable_peripheral_select (Spi * p_spi) inline static
Set Variable Peripheral Select.
Peripheral Chip Select can be controlled by SPI_TDR.
Parameters
p_spi Pointer to an SPI instance.
Definition at line 169 of file drivers/spi/spi.h.
{
    p_spi->SPI_MR |= SPI_MR_PS;
}
References Spi::SPI_MR, and SPI_MR_PS.