WINC1500 Weather Client Demo for SAME70 Xplained: fpu.h File Reference
fpu.h File Reference
FPU support for SAM.
#include <compiler.h>
Macros
#define ADDR_CPACR 0xE000ED88
Address for ARM CPACR.
#define REG_CPACR (*((volatile uint32_t *)ADDR_CPACR))
CPACR Register.
Functions
static __always_inline void fpu_disable (void)
Disable FPU.
static __always_inline void fpu_enable (void)
Enable FPU.
static __always_inline bool fpu_is_enabled (void)
Check if FPU is enabled.
Detailed Description
FPU support for SAM.
Copyright (c) 2014-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file fpu.h.
Macro Definition Documentation
ADDR_CPACR
#define ADDR_CPACR 0xE000ED88
Address for ARM CPACR.
Definition at line 43 of file fpu.h.
REG_CPACR
#define REG_CPACR (*((volatile uint32_t *)ADDR_CPACR))
CPACR Register.
Definition at line 46 of file fpu.h.
Function Documentation
fpu_disable()
static __always_inline void fpu_disable (void) static
Disable FPU.
Definition at line 64 of file fpu.h.
{
    irqflags_t flags;
    flags = cpu_irq_save();
    REG_CPACR &= ~(0xFu << 20);
    __DSB();
    __ISB();
    cpu_irq_restore(flags);
}
References cpu_irq_restore(), cpu_irq_save(), and REG_CPACR.
fpu_enable()
static __always_inline void fpu_enable (void) static
Enable FPU.
Definition at line 51 of file fpu.h.
{
    irqflags_t flags;
    flags = cpu_irq_save();
    REG_CPACR |=  (0xFu << 20);
    __DSB();
    __ISB();
    cpu_irq_restore(flags);
}
References cpu_irq_restore(), cpu_irq_save(), and REG_CPACR.
fpu_is_enabled()
static __always_inline bool fpu_is_enabled (void) static
Check if FPU is enabled.
Returns
Return ture if FPU is enabled, otherwise return false.
Definition at line 79 of file fpu.h.
{
    return (REG_CPACR & (0xFu << 20));
}
References REG_CPACR.