WINC1500 Weather Client Demo for SAME70 Xplained: Functions
Functions
WLAN » Version
Lists the APIs for reading the version information of the WINC firmware.
Functions
NMI_API sint8 m2m_ota_get_firmware_version (tstrM2mRev *pstrRev)
Get the OTA Firmware version.
sint8 m2m_wifi_get_firmware_version (tstrM2mRev *pstrRev)
Get Firmware version info.
Detailed Description
Lists the APIs for reading the version information of the WINC firmware.
Function Documentation
m2m_ota_get_firmware_version()
sint8 m2m_ota_get_firmware_version (tstrM2mRev * pstrRev)
Get the OTA Firmware version.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
Get OTA Firmware version info from the inactive partition, as defined in the structure tstrM2mRev.
Parameters
[out] pstrRev Pointer to the structure tstrM2mRev that contains the firmware version parameters.
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 295 of file m2m_ota.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = hif_chip_wake();
    if(ret == M2M_SUCCESS)
    {
        ret = nm_get_ota_firmware_info(pstrRev);
        hif_chip_sleep();
    }
    return ret;
}
References hif_chip_sleep(), hif_chip_wake(), M2M_SUCCESS, and nm_get_ota_firmware_info().
m2m_wifi_get_firmware_version()
NMI_API m2m_wifi_get_firmware_version (tstrM2mRev * pstrRev)
Get Firmware version info.
Get the Firmware version info from the active partition, as defined in the structure tstrM2mRev.
Parameters
[out] pstrRev Pointer to the structure tstrM2mRev that contains the firmware version parameters.
Precondition
Must be called after initialization through the following function m2m_wifi_init.
See also
m2m_wifi_init
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 1711 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = hif_chip_wake();
    if(ret == M2M_SUCCESS)
    {
        ret = nm_get_firmware_full_info(pstrRev);
        hif_chip_sleep();
    }
    return ret;
}
References hif_chip_sleep(), hif_chip_wake(), M2M_SUCCESS, and nm_get_firmware_full_info().