WINC1500 Weather Client Demo for SAME70 Xplained: Display - ILI9488 Controller
Display - ILI9488 Controller
Low-level driver for the ILI9488 LCD controller.
Macros
#define LCD_DATA_CACHE_SIZE ILI9488_LCD_WIDTH
Functions
static void ili9488_check_box_coordinates (uint32_t *p_ul_x1, uint32_t *p_ul_y1, uint32_t *p_ul_x2, uint32_t *p_ul_y2)
Check box coordinates.
void ili9488_copy_pixels_from_screen (uint16_t *pixels, uint32_t count)
Copy pixels from the screen to a pixel buffer.
void ili9488_copy_pixels_to_screen (const uint16_t *pixels, uint32_t count)
Copy pixels from SRAM to the screen.
void ili9488_delay (uint32_t ul_ms)
Delay function.
void ili9488_display_off (void)
Turn off the LCD.
void ili9488_display_on (void)
Turn on the LCD.
static void ili9488_draw_char (uint32_t ul_x, uint32_t ul_y, uint8_t uc_c)
Draw an ASCII character on LCD.
uint32_t ili9488_draw_circle (uint32_t ul_x, uint32_t ul_y, uint32_t ul_r)
Draw a circle on LCD.
uint32_t ili9488_draw_filled_circle (uint32_t ul_x, uint32_t ul_y, uint32_t ul_r)
Draw a filled circle on LCD.
void ili9488_draw_filled_rectangle (uint32_t ul_x1, uint32_t ul_y1, uint32_t ul_x2, uint32_t ul_y2)
Draw a filled rectangle on LCD.
void ili9488_draw_line (uint32_t ul_x1, uint32_t ul_y1, uint32_t ul_x2, uint32_t ul_y2)
Draw a line on LCD.
static void ili9488_draw_line_bresenham (uint32_t ul_x1, uint32_t ul_y1, uint32_t ul_x2, uint32_t ul_y2)
Draw a line on LCD, which is not horizontal or vertical.
uint32_t ili9488_draw_pixel (uint32_t ul_x, uint32_t ul_y)
Draw a pixel on LCD.
void ili9488_draw_pixmap (uint32_t ul_x, uint32_t ul_y, uint32_t ul_width, uint32_t ul_height, const ili9488_color_t *p_ul_pixmap)
Draw a pixmap on LCD.
void ili9488_draw_prepare (uint32_t ul_x, uint32_t ul_y, uint32_t ul_width, uint32_t ul_height)
Prepare LCD to draw.
void ili9488_draw_rectangle (uint32_t ul_x1, uint32_t ul_y1, uint32_t ul_x2, uint32_t ul_y2)
Draw a rectangle on LCD.
void ili9488_draw_string (uint32_t ul_x, uint32_t ul_y, const uint8_t *p_str)
Draw a string on LCD.
void ili9488_duplicate_pixel (const uint16_t color, uint32_t count)
Set a given number of pixels to the same color.
void ili9488_fill (ili9488_color_t ul_color)
Fill the LCD buffer with the specified color.
ili9488_color_t ili9488_get_pixel (uint32_t ul_x, uint32_t ul_y)
Get a pixel from LCD.
uint32_t ili9488_init (struct ili9488_opt_t *p_opt)
Initialize the ILI9488 lcd driver.
static uint32_t ili9488_read_chipid (void)
Read chipid.
uint16_t ili9488_read_gram (void)
Read a single color from the graphical memory.
static uint32_t ili9488_read_ram (void)
Read data to LCD GRAM.
void ili9488_scroll (uint16_t ul_tfa, uint16_t ul_vsa, uint16_t ul_bfa)
Scroll up/down for the number of specified lines.
void ili9488_set_bottom_right_limit (ili9488_coord_t x, ili9488_coord_t y)
Set the display bottom right drawing limit.
void ili9488_set_cursor_position (uint16_t x, uint16_t y)
Set cursor of LCD screen.
void ili9488_set_display_direction (enum ili9488_display_direction direction)
ILI9488 configure landscape.
void ili9488_set_foreground_color (uint32_t ul_color)
Set foreground color.
void ili9488_set_limits (ili9488_coord_t start_x, ili9488_coord_t start_y, ili9488_coord_t end_x, ili9488_coord_t end_y)
Set the full display drawing limits.
void ili9488_set_orientation (uint8_t flags)
Sets the orientation of the display data.
void ili9488_set_scroll_address (uint16_t ul_vsp)
Enable the scrolling feature.
void ili9488_set_top_left_limit (ili9488_coord_t x, ili9488_coord_t y)
Set the display top left drawing limit.
void ili9488_set_window (uint16_t x, uint16_t y, uint16_t width, uint16_t height)
ILI9488 configure window.
void ili9488_write_brightness (uint16_t us_value)
Set display brightness.
void ili9488_write_gram (uint16_t color)
Write the graphical memory with a single color pixel.
static void ili9488_write_ram (ili9488_color_t ul_color)
Write data to LCD GRAM.
static void ili9488_write_ram_buffer (const ili9488_color_t *p_ul_buf, uint32_t ul_size)
Write multiple data in buffer to LCD controller.
static void ili9488_write_ram_prepare (void)
Prepare to write GRAM data.
static void ili9488_write_register (uint8_t uc_reg, const ili9488_color_t *us_data, uint32_t size)
Write data to LCD Register.
Variables
static ili9488_color_t g_ul_pixel_cache [LCD_DATA_CACHE_SIZE *LCD_DATA_COLOR_UNIT]
const struct ili9488_font gfont = {10, 14}
static ili9488_coord_t limit_end_x
static ili9488_coord_t limit_end_y
static ili9488_coord_t limit_start_x
static ili9488_coord_t limit_start_y
const uint8_t p_uc_charset10x14 []
Character set table for font 10x14 Coding format: Char height is 14 bits, which is coded using 2 bytes per column (2 unused bits).
Detailed Description
Low-level driver for the ILI9488 LCD controller.
This driver provides access to the main features of the ILI9488 controller.
Macro Definition Documentation
LCD_DATA_CACHE_SIZE
#define LCD_DATA_CACHE_SIZE ILI9488_LCD_WIDTH
Definition at line 69 of file ili9488.c.
Function Documentation
ili9488_check_box_coordinates()
static void ili9488_check_box_coordinates (uint32_t * p_ul_x1, uint32_t * p_ul_y1, uint32_t * p_ul_x2, uint32_t * p_ul_y2) static
Check box coordinates.
Parameters
p_ul_x1 X coordinate of upper-left corner on LCD.
p_ul_y1 Y coordinate of upper-left corner on LCD.
p_ul_x2 X coordinate of lower-right corner on LCD.
p_ul_y2 Y coordinate of lower-right corner on LCD.
Definition at line 522 of file ili9488.c.
{
    uint32_t dw;
    if (*p_ul_x1 >= ILI9488_LCD_WIDTH) {
        *p_ul_x1 = ILI9488_LCD_WIDTH - 1;
    }
    if (*p_ul_x2 >= ILI9488_LCD_WIDTH) {
        *p_ul_x2 = ILI9488_LCD_WIDTH - 1;
    }
    if (*p_ul_y1 >= ILI9488_LCD_HEIGHT) {
        *p_ul_y1 = ILI9488_LCD_HEIGHT - 1;
    }
    if (*p_ul_y2 >= ILI9488_LCD_HEIGHT) {
        *p_ul_y2 = ILI9488_LCD_HEIGHT - 1;
    }
    if (*p_ul_x1 > *p_ul_x2) {
        dw = *p_ul_x1;
        *p_ul_x1 = *p_ul_x2;
        *p_ul_x2 = dw;
    }
    if (*p_ul_y1 > *p_ul_y2) {
        dw = *p_ul_y1;
        *p_ul_y1 = *p_ul_y2;
        *p_ul_y2 = dw;
    }
}
References ILI9488_LCD_HEIGHT, and ILI9488_LCD_WIDTH.
Referenced by ili9488_draw_filled_rectangle(), ili9488_draw_pixmap(), and ili9488_draw_rectangle().
ili9488_copy_pixels_from_screen()
void ili9488_copy_pixels_from_screen (uint16_t * pixels, uint32_t count)
Copy pixels from the screen to a pixel buffer.
Use this function to copy pixels from the display to an internal SRAM buffer.
Limits have to be set prior to calling this function, e.g.:
ili9488_set_top_left_limit(0, 0);
ili9488_set_bottom_right_limit(320, 240);
...
Parameters
pixels Pointer to the pixel buffer to read to
count Number of pixels to read
Definition at line 1460 of file ili9488.c.
{
    ili9488_set_window(limit_start_x, limit_start_y, (limit_end_x - limit_start_x) + 1, (limit_end_y - limit_start_y) + 1);
    ili9488_write_register(ILI9488_CMD_MEMORY_READ, 0x0000, 0);
#ifdef ILI9488_EBIMODE
    pio_set(PIN_EBI_CDS_PIO, PIN_EBI_CDS_MASK);
    LCD_MULTI_RD(pixels, count);
#endif
#ifdef ILI9488_SPIMODE
    ili9488_color_t grambuf[3];
    pio_set_pin_high(LCD_SPI_CDS_PIO);
    spi_read_packet(BOARD_ILI9488_SPI, grambuf, 1);
    while (count--) {
        spi_read_packet(BOARD_ILI9488_SPI, grambuf, 3);
        *pixels = ILI9488_COLOR(grambuf[0], grambuf[1], grambuf[2]);
        pixels++;
    }
#endif
}
References BOARD_ILI9488_SPI, ILI9488_CMD_MEMORY_READ, ILI9488_COLOR, ili9488_set_window(), ili9488_write_register(), LCD_SPI_CDS_PIO, limit_end_x, limit_end_y, limit_start_x, limit_start_y, PIN_EBI_CDS_MASK, PIN_EBI_CDS_PIO, pio_set(), pio_set_pin_high(), and spi_read_packet().
ili9488_copy_pixels_to_screen()
void ili9488_copy_pixels_to_screen (const uint16_t * pixels, uint32_t count)
Copy pixels from SRAM to the screen.
Used to copy a large quantitative of data to the screen in one go.
Limits have to be set prior to calling this function, e.g.:
ili9488_set_top_left_limit(0, 0);
ili9488_set_bottom_right_limit(320, 240);
...
Parameters
pixels Pointer to the pixel data
count Number of pixels to copy to the screen
Definition at line 1389 of file ili9488.c.
{
    ili9488_set_window(limit_start_x, limit_start_y, (limit_end_x - limit_start_x) + 1, (limit_end_y - limit_start_y) + 1);
#ifdef ILI9488_EBIMODE
    ili9488_write_register(ILI9488_CMD_MEMORY_WRITE, pixels, count * LCD_DATA_COLOR_UNIT);
#endif
#ifdef ILI9488_SPIMODE
    uint32_t color_666;
    ili9488_write_ram_prepare();
    while (count--) {
        color_666 = RGB_16_TO_18BIT(*pixels);
        ili9488_write_ram(color_666 >> 16);
        ili9488_write_ram(color_666 >> 8);
        ili9488_write_ram(color_666 & 0xFF);
        pixels++;
    }
#endif
}
References ILI9488_CMD_MEMORY_WRITE, ili9488_set_window(), ili9488_write_ram(), ili9488_write_ram_prepare(), ili9488_write_register(), LCD_DATA_COLOR_UNIT, limit_end_x, limit_end_y, limit_start_x, limit_start_y, and RGB_16_TO_18BIT.
ili9488_delay()
void ili9488_delay (uint32_t ul_ms)
Delay function.
Definition at line 504 of file ili9488.c.
{
    uint32_t i;
    for(i = 0; i < ul_ms; i++) {
        for(i = 0; i < 100000; i++) {
        }
    }
}
Referenced by ili9488_init().
ili9488_display_off()
void ili9488_display_off (void)
Turn off the LCD.
Definition at line 724 of file ili9488.c.
{
    ili9488_write_register(ILI9488_CMD_DISPLAY_OFF, 0x00, 0);
}
References ILI9488_CMD_DISPLAY_OFF, and ili9488_write_register().
ili9488_display_on()
void ili9488_display_on (void)
Turn on the LCD.
Definition at line 716 of file ili9488.c.
{
    ili9488_write_register(ILI9488_CMD_DISPLAY_ON, 0, 0);
}
References ILI9488_CMD_DISPLAY_ON, and ili9488_write_register().
Referenced by ili9488_init().
ili9488_draw_char()
static void ili9488_draw_char (uint32_t ul_x, uint32_t ul_y, uint8_t uc_c) static
Draw an ASCII character on LCD.
Parameters
ul_x X coordinate of character upper-left corner.
ul_y Y coordinate of character upper-left corner.
uc_c character to print.
Definition at line 1145 of file ili9488.c.
{
    uint32_t row, col;
    uint32_t offset, offset0, offset1;
    /* Compute offset according of the specified ASCII character */
    /* Note: the first 32 characters of the ASCII table are not handled */
    offset = ((uint32_t)uc_c - 0x20) * 20;
    for (col = 0; col < 10; col++) {
        /* Compute the first and second byte offset of a column */
        offset0 = offset + col * 2;
        offset1 = offset0 + 1;
        /* Draw pixel on screen depending on the corresponding bit value from the charset */
        for (row = 0; row < 8; row++) {
            if ((p_uc_charset10x14[offset0] >> (7 - row)) & 0x1) {
                ili9488_draw_pixel(ul_x + col, ul_y + row);
            }
        }
        for (row = 0; row < 6; row++) {
            if ((p_uc_charset10x14[offset1] >> (7 - row)) & 0x1) {
                ili9488_draw_pixel(ul_x + col, ul_y + row + 8);
            }
        }
    }
}
References ili9488_draw_pixel(), and p_uc_charset10x14.
Referenced by ili9488_draw_string().
ili9488_draw_circle()
uint32_t ili9488_draw_circle (uint32_t ul_x, uint32_t ul_y, uint32_t ul_r)
Draw a circle on LCD.
Parameters
ul_x X coordinate of circle center.
ul_y Y coordinate of circle center.
ul_r circle radius.
Returns
0 if succeeds, otherwise fails.
Definition at line 1034 of file ili9488.c.
{
    int32_t   d;    /* Decision Variable */
    uint32_t  curX; /* Current X Value */
    uint32_t  curY; /* Current Y Value */
    if (ul_r == 0) {
        return 1;
    }
    d = 3 - (ul_r << 1);
    curX = 0;
    curY = ul_r;
    while (curX <= curY) {
        ili9488_draw_pixel(ul_x + curX, ul_y + curY);
        ili9488_draw_pixel(ul_x + curX, ul_y - curY);
        ili9488_draw_pixel(ul_x - curX, ul_y + curY);
        ili9488_draw_pixel(ul_x - curX, ul_y - curY);
        ili9488_draw_pixel(ul_x + curY, ul_y + curX);
        ili9488_draw_pixel(ul_x + curY, ul_y - curX);
        ili9488_draw_pixel(ul_x - curY, ul_y + curX);
        ili9488_draw_pixel(ul_x - curY, ul_y - curX);
        if (d < 0) {
            d += (curX << 2) + 6;
        } else {
            d += ((curX - curY) << 2) + 10;
            curY--;
        }
        curX++;
    }
    return 0;
}
References ili9488_draw_pixel().
ili9488_draw_filled_circle()
uint32_t ili9488_draw_filled_circle (uint32_t ul_x, uint32_t ul_y, uint32_t ul_r)
Draw a filled circle on LCD.
Parameters
ul_x X coordinate of circle center.
ul_y Y coordinate of circle center.
ul_r circle radius.
Returns
0 if succeeds, otherwise fails.
Definition at line 1079 of file ili9488.c.
{
    signed int d;       /* Decision Variable */
    uint32_t dwCurX;    /* Current X Value */
    uint32_t dwCurY;    /* Current Y Value */
    uint32_t dwXmin, dwYmin;
    if (ul_r == 0) {
        return 1;
    }
    d = 3 - (ul_r << 1);
    dwCurX = 0;
    dwCurY = ul_r;
    while (dwCurX <= dwCurY) {
        dwXmin = (dwCurX > ul_x) ? 0 : ul_x - dwCurX;
        dwYmin = (dwCurY > ul_y) ? 0 : ul_y - dwCurY;
        ili9488_draw_filled_rectangle(dwXmin, dwYmin, ul_x + dwCurX, dwYmin);
        ili9488_draw_filled_rectangle(dwXmin, ul_y + dwCurY, ul_x + dwCurX, ul_y + dwCurY);
        dwXmin = (dwCurY > ul_x) ? 0 : ul_x - dwCurY;
        dwYmin = (dwCurX > ul_y) ? 0 : ul_y - dwCurX;
        ili9488_draw_filled_rectangle(dwXmin, dwYmin, ul_x + dwCurY, dwYmin);
        ili9488_draw_filled_rectangle(dwXmin, ul_y + dwCurX, ul_x + dwCurY, ul_y + dwCurX);
        if (d < 0) {
            d += (dwCurX << 2) + 6;
        } else {
            d += ((dwCurX - dwCurY) << 2) + 10;
            dwCurY--;
        }
        dwCurX++;
    }
    return 0;
}
References ili9488_draw_filled_rectangle().
ili9488_draw_filled_rectangle()
void ili9488_draw_filled_rectangle (uint32_t ul_x1, uint32_t ul_y1, uint32_t ul_x2, uint32_t ul_y2)
Draw a filled rectangle on LCD.
Parameters
ul_x1 X coordinate of upper-left corner on LCD.
ul_y1 Y coordinate of upper-left corner on LCD.
ul_x2 X coordinate of lower-right corner on LCD.
ul_y2 Y coordinate of lower-right corner on LCD.
Definition at line 996 of file ili9488.c.
{
    uint32_t size, blocks;
    /* Swap coordinates if necessary */
    ili9488_check_box_coordinates(&ul_x1, &ul_y1, &ul_x2, &ul_y2);
    /* Determine the refresh window area */
    ili9488_set_window(ul_x1, ul_y1, (ul_x2 - ul_x1) + 1, (ul_y2 - ul_y1) + 1);
    /* Prepare to write in GRAM */
    ili9488_write_ram_prepare();
    size = (ul_x2 - ul_x1 + 1) * (ul_y2 - ul_y1 + 1);
    /* Send pixels blocks => one SPI IT / block */
    blocks = size / LCD_DATA_CACHE_SIZE;
    while (blocks--) {
        ili9488_write_ram_buffer(g_ul_pixel_cache, LCD_DATA_CACHE_SIZE * LCD_DATA_COLOR_UNIT);
    }
    /* Send remaining pixels */
    ili9488_write_ram_buffer(g_ul_pixel_cache, (size % LCD_DATA_CACHE_SIZE) * LCD_DATA_COLOR_UNIT);
    /* Reset the refresh window area */
    ili9488_set_window(0, 0, ILI9488_LCD_WIDTH, ILI9488_LCD_HEIGHT);
}
References g_ul_pixel_cache, ili9488_check_box_coordinates(), ILI9488_LCD_HEIGHT, ILI9488_LCD_WIDTH, ili9488_set_window(), ili9488_write_ram_buffer(), ili9488_write_ram_prepare(), LCD_DATA_CACHE_SIZE, and LCD_DATA_COLOR_UNIT.
Referenced by ili9488_draw_filled_circle(), ili9488_draw_line(), ili9488_draw_rectangle(), main(), and refresh_display().
ili9488_draw_line()
void ili9488_draw_line (uint32_t ul_x1, uint32_t ul_y1, uint32_t ul_x2, uint32_t ul_y2)
Draw a line on LCD.
Parameters
ul_x1 X coordinate of line start.
ul_y1 Y coordinate of line start.
ul_x2 X coordinate of line end.
ul_y2 Y coordinate of line end.
Definition at line 958 of file ili9488.c.
{
    if ((ul_y1 == ul_y2) || (ul_x1 == ul_x2)) {
        ili9488_draw_filled_rectangle(ul_x1, ul_y1, ul_x2, ul_y2);
    } else {
        ili9488_draw_line_bresenham(ul_x1, ul_y1, ul_x2, ul_y2);
    }
}
References ili9488_draw_filled_rectangle(), and ili9488_draw_line_bresenham().
ili9488_draw_line_bresenham()
static void ili9488_draw_line_bresenham (uint32_t ul_x1, uint32_t ul_y1, uint32_t ul_x2, uint32_t ul_y2) static
Draw a line on LCD, which is not horizontal or vertical.
Parameters
ul_x1 X coordinate of line start.
ul_y1 Y coordinate of line start.
ul_x2 X coordinate of line end.
ul_y2 Y coordinate of line endl.
Definition at line 900 of file ili9488.c.
{
    int dx, dy;
    int i;
    int xinc, yinc, cumul;
    int x, y;
    x = ul_x1;
    y = ul_y1;
    dx = ul_x2 - ul_x1;
    dy = ul_y2 - ul_y1;
    xinc = (dx > 0) ? 1 : -1;
    yinc = (dy > 0) ? 1 : -1;
    dx = abs(ul_x2 - ul_x1);
    dy = abs(ul_y2 - ul_y1);
    ili9488_draw_pixel(x, y);
    if (dx > dy) {
        cumul = dx >> 1;
        for (i = 1; i <= dx; i++) {
            x += xinc;
            cumul += dy;
            if (cumul >= dx) {
                cumul -= dx;
                y += yinc;
            }
            ili9488_draw_pixel(x, y);
        }
    } else {
        cumul = dy >> 1;
        for (i = 1; i <= dy; i++) {
            y += yinc;
            cumul += dx;
            if (cumul >= dy) {
                cumul -= dy;
                x += xinc;
            }
            ili9488_draw_pixel(x, y);
        }
    }
}
References ili9488_draw_pixel().
Referenced by ili9488_draw_line().
ili9488_draw_pixel()
uint32_t ili9488_draw_pixel (uint32_t ul_x, uint32_t ul_y)
Draw a pixel on LCD.
Parameters
ul_x X coordinate of pixel.
ul_y Y coordinate of pixel.
Returns
0 if succeeds, otherwise fails.
Definition at line 851 of file ili9488.c.
{
    if ((ul_x >= ILI9488_LCD_WIDTH) || (ul_y >= ILI9488_LCD_HEIGHT)) {
        return 1;
    }
    /* Set cursor */
    ili9488_set_cursor_position(ul_x, ul_y);
    /* Prepare to write in GRAM */
    ili9488_write_ram_prepare();
    ili9488_write_ram_buffer(g_ul_pixel_cache, LCD_DATA_COLOR_UNIT);
    return 0;
}
References g_ul_pixel_cache, ILI9488_LCD_HEIGHT, ILI9488_LCD_WIDTH, ili9488_set_cursor_position(), ili9488_write_ram_buffer(), ili9488_write_ram_prepare(), and LCD_DATA_COLOR_UNIT.
Referenced by ili9488_draw_char(), ili9488_draw_circle(), ili9488_draw_line_bresenham(), and ili9488_draw_number().
ili9488_draw_pixmap()
void ili9488_draw_pixmap (uint32_t ul_x, uint32_t ul_y, uint32_t ul_width, uint32_t ul_height, const ili9488_color_t * p_ul_pixmap)
Draw a pixmap on LCD.
Parameters
ul_x X coordinate of upper-left corner on LCD.
ul_y Y coordinate of upper-left corner on LCD.
ul_width width of the picture.
ul_height height of the picture.
p_ul_pixmap pixmap of the image.
Definition at line 1208 of file ili9488.c.
{
    uint32_t size;
    uint32_t dwX1, dwY1, dwX2, dwY2;
    dwX1 = ul_x;
    dwY1 = ul_y;
    dwX2 = ul_x + ul_width - 1;
    dwY2 = ul_y + ul_height - 1;
    /* Swap coordinates if necessary */
    ili9488_check_box_coordinates(&dwX1, &dwY1, &dwX2, &dwY2);
    /* Determine the refresh window area */
    ili9488_set_window(dwX1, dwY1, (dwX2 - dwX1 + 1), (dwY2 - dwY1 + 1));
    size = (dwX2 - dwX1) * (dwY2 - dwY1);
    ili9488_write_register(ILI9488_CMD_MEMORY_WRITE, p_ul_pixmap, size * LCD_DATA_COLOR_UNIT);
    /* Reset the refresh window area */
    ili9488_set_window(0, 0, ILI9488_LCD_WIDTH, ILI9488_LCD_HEIGHT);
}
References ili9488_check_box_coordinates(), ILI9488_CMD_MEMORY_WRITE, ILI9488_LCD_HEIGHT, ILI9488_LCD_WIDTH, ili9488_set_window(), ili9488_write_register(), and LCD_DATA_COLOR_UNIT.
Referenced by main(), and refresh_display().
ili9488_draw_prepare()
void ili9488_draw_prepare (uint32_t ul_x, uint32_t ul_y, uint32_t ul_width, uint32_t ul_height)
Prepare LCD to draw.
Parameters
ul_x Horizontal address start position
ul_y Vertical address start position
ul_width The width of the window.
ul_height The height of the window.
Definition at line 1125 of file ili9488.c.
{
    /* Determine the refresh window area */
    ili9488_set_window(ul_x, ul_y, ul_width, ul_height);
    /* Set cursor */
    ili9488_set_cursor_position(ul_x, ul_y);
    /* Prepare to write in GRAM */
    ili9488_write_ram_prepare();
}
References ili9488_set_cursor_position(), ili9488_set_window(), and ili9488_write_ram_prepare().
ili9488_draw_rectangle()
void ili9488_draw_rectangle (uint32_t ul_x1, uint32_t ul_y1, uint32_t ul_x2, uint32_t ul_y2)
Draw a rectangle on LCD.
Parameters
ul_x1 X coordinate of upper-left corner on LCD.
ul_y1 Y coordinate of upper-left corner on LCD.
ul_x2 X coordinate of lower-right corner on LCD.
ul_y2 Y coordinate of lower-right corner on LCD.
Definition at line 976 of file ili9488.c.
{
    ili9488_check_box_coordinates(&ul_x1, &ul_y1, &ul_x2, &ul_y2);
    ili9488_draw_filled_rectangle(ul_x1, ul_y1, ul_x2, ul_y1);
    ili9488_draw_filled_rectangle(ul_x1, ul_y2, ul_x2, ul_y2);
    ili9488_draw_filled_rectangle(ul_x1, ul_y1, ul_x1, ul_y2);
    ili9488_draw_filled_rectangle(ul_x2, ul_y1, ul_x2, ul_y2);
}
References ili9488_check_box_coordinates(), and ili9488_draw_filled_rectangle().
ili9488_draw_string()
void ili9488_draw_string (uint32_t ul_x, uint32_t ul_y, const uint8_t * p_str)
Draw a string on LCD.
Parameters
ul_x X coordinate of string top-left corner.
ul_y Y coordinate of string top-left corner.
p_str String to display.
Definition at line 1181 of file ili9488.c.
{
    uint32_t xorg = ul_x;
    while (*p_str != 0) {
        /* If newline, jump to the next line (font height + 2) */
        if (*p_str == '\n') {
            ul_y += gfont.height + 2;
            ul_x = xorg;
        } else {
            /* Draw the character and place cursor right after (font width + 2) */
            ili9488_draw_char(ul_x, ul_y, *p_str);
            ul_x += gfont.width + 2;
        }
        p_str++;
    }
}
References gfont, ili9488_font::height, ili9488_draw_char(), and ili9488_font::width.
Referenced by main(), refresh_display(), and wifi_connect().
ili9488_duplicate_pixel()
void ili9488_duplicate_pixel (const uint16_t color, uint32_t count)
Set a given number of pixels to the same color.
Use this function to write a certain number of pixels to the same color within a set limit.
Limits have to be set prior to calling this function, e.g.:
ili9488_set_top_left_limit(0, 0);
ili9488_set_bottom_right_limit(320, 240);
...
Parameters
color The color to write to the display
count The number of pixels to write with this color
Definition at line 1425 of file ili9488.c.
{
    ili9488_set_window(limit_start_x, limit_start_y, (limit_end_x - limit_start_x) + 1, (limit_end_y - limit_start_y) + 1);
    ili9488_write_ram_prepare();
#ifdef ILI9488_EBIMODE
    while (count--) {
        ili9488_write_ram(color);
    }
#endif
#ifdef ILI9488_SPIMODE
    uint32_t color_666 = RGB_16_TO_18BIT(color);
    while (count--) {
        ili9488_write_ram(color_666 >> 16);
        ili9488_write_ram(color_666 >> 8);
        ili9488_write_ram(color_666 & 0xFF);
    }
#endif
}
References ili9488_set_window(), ili9488_write_ram(), ili9488_write_ram_prepare(), limit_end_x, limit_end_y, limit_start_x, limit_start_y, and RGB_16_TO_18BIT.
ili9488_fill()
void ili9488_fill (ili9488_color_t ul_color)
Fill the LCD buffer with the specified color.
Parameters
ul_color fill color.
Definition at line 757 of file ili9488.c.
{
    uint32_t dw;
    ili9488_set_cursor_position(0, 0);
    ili9488_write_ram_prepare();
    for (dw = ILI9488_LCD_WIDTH * ILI9488_LCD_HEIGHT; dw > 0; dw--) {
        ili9488_write_ram(ul_color);
    }
}
References ILI9488_LCD_HEIGHT, ILI9488_LCD_WIDTH, ili9488_set_cursor_position(), ili9488_write_ram(), and ili9488_write_ram_prepare().
ili9488_get_pixel()
ili9488_color_t ili9488_get_pixel (uint32_t ul_x, uint32_t ul_y)
Get a pixel from LCD.
Parameters
ul_x X coordinate of pixel.
ul_y Y coordinate of pixel.
Returns
the pixel color.
Definition at line 874 of file ili9488.c.
{
#ifdef ILI9488_EBIMODE
    Assert(ul_x <= ILI9488_LCD_WIDTH);
    Assert(ul_y <= ILI9488_LCD_HEIGHT);
    /* Set cursor */
    ili9488_set_cursor_position(ul_x, ul_y);
    /* Prepare to write in GRAM */
    return ili9488_read_ram();
#endif
#ifdef ILI9488_SPIMODE
    Assert(0);
    return 0;
#endif
}
References Assert, ILI9488_LCD_HEIGHT, ILI9488_LCD_WIDTH, ili9488_read_ram(), and ili9488_set_cursor_position().
ili9488_init()
uint32_t ili9488_init (struct ili9488_opt_t * p_opt)
Initialize the ILI9488 lcd driver.
Note
Make sure below works have been done before calling ili9488_init()
ILI9488 related Pins have been initialized correctly.
SMC has been configured correctly for access ILI9488 (16-bit system interface for now).
Parameters
p_opt pointer to ILI9488 option structure.
Returns
0 if initialization succeeds, otherwise fails.
read chipid
make it tRGB and reverse the column order
Definition at line 620 of file ili9488.c.
{
    ili9488_color_t param;
    uint32_t chipid;
#ifdef ILI9488_EBIMODE
    /* Enable peripheral clock */
    pmc_enable_periph_clk(ID_SMC);
    /* Configure SMC, NCS3 is assigned to LCD */
    smc_set_setup_timing(SMC, BOARD_ILI9488_EBI_NPCS, SMC_SETUP_NWE_SETUP(0)
            | SMC_SETUP_NCS_WR_SETUP(0)
            | SMC_SETUP_NRD_SETUP(0)
            | SMC_SETUP_NCS_RD_SETUP(0));
    smc_set_pulse_timing(SMC, BOARD_ILI9488_EBI_NPCS , SMC_PULSE_NWE_PULSE(3)
            | SMC_PULSE_NCS_WR_PULSE(0x4)
            | SMC_PULSE_NRD_PULSE(0xA)
            | SMC_PULSE_NCS_RD_PULSE(0xA));
    smc_set_cycle_timing(SMC, BOARD_ILI9488_EBI_NPCS, SMC_CYCLE_NWE_CYCLE(0x4)
            | SMC_CYCLE_NRD_CYCLE(0xA));
    smc_set_mode(SMC, BOARD_ILI9488_EBI_NPCS, SMC_MODE_READ_MODE
            | SMC_MODE_WRITE_MODE
            | SMC_MODE_DBW_16_BIT
            | SMC_MODE_EXNW_MODE_DISABLED
            | SMC_MODE_TDF_CYCLES(0xF));
#endif
#ifdef ILI9488_SPIMODE
    struct spi_device ILI9488_SPI_DEVICE = {
        // Board specific chip select configuration
        .id = BOARD_ILI9488_SPI_NPCS
    };
    /* Init, select and configure the chip */
    spi_master_init(BOARD_ILI9488_SPI);
    spi_master_setup_device(BOARD_ILI9488_SPI, &ILI9488_SPI_DEVICE, SPI_MODE_3, ILI9488_SPI_BAUDRATE, 0);
    spi_configure_cs_behavior(BOARD_ILI9488_SPI, BOARD_ILI9488_SPI_NPCS, SPI_CS_RISE_NO_TX);
    spi_select_device(BOARD_ILI9488_SPI, &ILI9488_SPI_DEVICE);
    /* Enable the SPI peripheral */
    spi_enable(BOARD_ILI9488_SPI);
    spi_enable_interrupt(BOARD_ILI9488_SPI, SPI_IER_RDRF);
#endif
    ili9488_write_register(ILI9488_CMD_SOFTWARE_RESET, 0x0000, 0);
    ili9488_delay(200);
    ili9488_write_register(ILI9488_CMD_SLEEP_OUT, 0x0000, 0);
    ili9488_delay(200);
    chipid = ili9488_read_chipid();
    if (chipid != ILI9488_DEVICE_CODE) {
        return 1;
    }
    param = 0x48;
    ili9488_write_register(ILI9488_CMD_MEMORY_ACCESS_CONTROL, &param, 1);
    ili9488_delay(100);
    param = 0x04;
    ili9488_write_register(ILI9488_CMD_CABC_CONTROL_9, &param, 1);
    ili9488_delay(100);
#ifdef ILI9488_EBIMODE
    param = 0x05;
    ili9488_write_register(ILI9488_CMD_COLMOD_PIXEL_FORMAT_SET, &param, 1);
    ili9488_delay(100);
    ili9488_write_register(ILI9488_CMD_PARTIAL_MODE_ON, 0, 0);
    ili9488_delay(100);
#endif
#ifdef ILI9488_SPIMODE
    param = 0x06;
    ili9488_write_register(ILI9488_CMD_COLMOD_PIXEL_FORMAT_SET, &param, 1);
    ili9488_delay(100);
    ili9488_write_register(ILI9488_CMD_NORMAL_DISP_MODE_ON, 0, 0);
    ili9488_delay(100);
#endif
    ili9488_display_on();
    ili9488_delay(100);
    ili9488_set_display_direction(LANDSCAPE);
    ili9488_delay(100);
    ili9488_set_window(0, 0,p_opt->ul_width,p_opt->ul_height);
    ili9488_set_foreground_color(p_opt->foreground_color);
    ili9488_set_cursor_position(0, 0);
    return 0;
}
References BOARD_ILI9488_SPI, BOARD_ILI9488_SPI_NPCS, ili9488_opt_t::foreground_color, spi_device::id, ID_SMC, ILI9488_CMD_CABC_CONTROL_9, ILI9488_CMD_COLMOD_PIXEL_FORMAT_SET, ILI9488_CMD_MEMORY_ACCESS_CONTROL, ILI9488_CMD_NORMAL_DISP_MODE_ON, ILI9488_CMD_PARTIAL_MODE_ON, ILI9488_CMD_SLEEP_OUT, ILI9488_CMD_SOFTWARE_RESET, ili9488_delay(), ILI9488_DEVICE_CODE, ili9488_display_on(), ili9488_read_chipid(), ili9488_set_cursor_position(), ili9488_set_display_direction(), ili9488_set_foreground_color(), ili9488_set_window(), ILI9488_SPI_BAUDRATE, ili9488_write_register(), LANDSCAPE, pmc_enable_periph_clk(), SMC, SMC_CYCLE_NRD_CYCLE, SMC_CYCLE_NWE_CYCLE, SMC_MODE_DBW_16_BIT, SMC_MODE_EXNW_MODE_DISABLED, SMC_MODE_READ_MODE, SMC_MODE_TDF_CYCLES, SMC_MODE_WRITE_MODE, SMC_PULSE_NCS_RD_PULSE, SMC_PULSE_NCS_WR_PULSE, SMC_PULSE_NRD_PULSE, SMC_PULSE_NWE_PULSE, SMC_SETUP_NCS_RD_SETUP, SMC_SETUP_NCS_WR_SETUP, SMC_SETUP_NRD_SETUP, SMC_SETUP_NWE_SETUP, spi_configure_cs_behavior(), SPI_CS_RISE_NO_TX, spi_enable(), spi_enable_interrupt(), SPI_IER_RDRF, spi_master_init(), spi_master_setup_device(), SPI_MODE_3, spi_select_device(), ili9488_opt_t::ul_height, and ili9488_opt_t::ul_width.
Referenced by main().
ili9488_read_chipid()
static uint32_t ili9488_read_chipid (void) static
Read chipid.
Returns
chipid value.
Definition at line 475 of file ili9488.c.
{
    uint32_t i, chipid = 0;
    volatile uint32_t j;
    ili9488_color_t chipidBuf, reg, param;
    reg = 0x81;
    param = 0x0;
    for (i = 3; i > 0; i--) {
        ili9488_write_register(ILI9488_CMD_SPI_READ_SETTINGS, &reg, 1);
        reg++;
        for(j = 0; j < 0xFF; j++);
        ili9488_write_register(ILI9488_CMD_READ_ID4, 0, 0);
        {
            pio_set_pin_high(LCD_SPI_CDS_PIO);
            spi_read_packet(BOARD_ILI9488_SPI, &chipidBuf, 1);
            for(j = 0; j < 0xFF; j++);
        }
        chipid |= (chipidBuf & 0xFF) << ((i - 1) << 3);
        ili9488_write_register(ILI9488_CMD_SPI_READ_SETTINGS, &param, 1);
        for(j = 0; j < 0xFFF; j++);
    }
    return chipid;
}
References BOARD_ILI9488_SPI, ILI9488_CMD_READ_ID4, ILI9488_CMD_SPI_READ_SETTINGS, ili9488_write_register(), LCD_SPI_CDS_PIO, pio_set_pin_high(), and spi_read_packet().
Referenced by ili9488_init().
ili9488_read_gram()
uint16_t ili9488_read_gram (void)
Read a single color from the graphical memory.
Use this function to read a color from the graphical memory of the controller.
Limits have to be set prior to calling this function, e.g.:
ili9488_set_top_left_limit(0, 0);
ili9488_set_bottom_right_limit(320, 240);
...
Return values
ili9488_color_t The read color pixel
Definition at line 1339 of file ili9488.c.
{
    ili9488_set_cursor_position(limit_start_x, limit_start_y);
    return ili9488_read_ram();
}
References ili9488_read_ram(), ili9488_set_cursor_position(), limit_start_x, and limit_start_y.
ili9488_read_ram()
static uint32_t ili9488_read_ram (void) static
Read data to LCD GRAM.
Note
Because pixel data LCD GRAM is 18-bits, so convertion to RGB565 16-bits will cause low color bit lose.
Returns
color 16-bits RGB color.
Definition at line 459 of file ili9488.c.
{
    uint8_t grambuf[4];
    ili9488_write_register(ILI9488_CMD_MEMORY_READ, 0x0000, 0);
    pio_set_pin_high(LCD_SPI_CDS_PIO);
    spi_read_packet(BOARD_ILI9488_SPI, grambuf, 4);
    /* The first data is dummy*/
    return ILI9488_COLOR(grambuf[1], grambuf[2], grambuf[3]);
}
References BOARD_ILI9488_SPI, ILI9488_CMD_MEMORY_READ, ILI9488_COLOR, ili9488_write_register(), LCD_SPI_CDS_PIO, pio_set_pin_high(), and spi_read_packet().
Referenced by ili9488_get_pixel(), and ili9488_read_gram().
ili9488_scroll()
void ili9488_scroll (uint16_t ul_tfa, uint16_t ul_vsa, uint16_t ul_bfa)
Scroll up/down for the number of specified lines.
Parameters
ul_tfa Top Fixed Area in number of lines from the top of the frame memory.
ul_lines number of lines to scroll.
ul_bfa bottom Fixed Area in number of lines from the bottom of the frame memory.
Definition at line 807 of file ili9488.c.
{
    uint32_t cnt = 0;
    ili9488_color_t buf[6];
    cnt = sizeof(buf)/sizeof(ili9488_color_t);
    buf[0] = get_8b_to_16b(ul_tfa);
    buf[1] = get_0b_to_8b(ul_tfa);
    buf[2] = get_8b_to_16b(ul_vsa);
    buf[3] = get_0b_to_8b(ul_vsa);
    buf[4] = get_8b_to_16b(ul_bfa);
    buf[5] = get_0b_to_8b(ul_bfa);
    ili9488_write_register(ILI9488_CMD_VERT_SCROLL_DEFINITION, buf, cnt);
}
References get_0b_to_8b, get_8b_to_16b, ILI9488_CMD_VERT_SCROLL_DEFINITION, and ili9488_write_register().
ili9488_set_bottom_right_limit()
void ili9488_set_bottom_right_limit (ili9488_coord_t x, ili9488_coord_t y)
Set the display bottom right drawing limit.
Use this function to set the bottom right corner of the drawing limit box.
Parameters
x The x coordinate of the bottom right corner
y The y coordinate of the bottom right corner
Definition at line 1270 of file ili9488.c.
{
    limit_end_x = x;
    limit_end_y = y;
}
References limit_end_x, and limit_end_y.
ili9488_set_cursor_position()
void ili9488_set_cursor_position (uint16_t x, uint16_t y)
Set cursor of LCD screen.
Parameters
x X coordinate of upper-left corner on LCD.
y Y coordinate of upper-left corner on LCD.
Definition at line 775 of file ili9488.c.
{
    /* Set Horizontal Address Start Position */
    uint32_t cnt = 0;
    ili9488_color_t buf[4];
    cnt = sizeof(buf)/sizeof(ili9488_color_t);
    buf[0] = get_8b_to_16b(x);
    buf[1] = get_0b_to_8b(x);
    buf[2] = get_8b_to_16b(x);
    buf[3] = get_0b_to_8b(x);
    ili9488_write_register(ILI9488_CMD_COLUMN_ADDRESS_SET, buf, cnt);
    ili9488_write_register(ILI9488_CMD_NOP, 0, 0);
    /* Set Horizontal Address End Position */
    buf[0] = get_8b_to_16b(y);
    buf[1] = get_0b_to_8b(y);
    buf[2] = get_8b_to_16b(y);
    buf[3] = get_0b_to_8b(y);
    ili9488_write_register(ILI9488_CMD_PAGE_ADDRESS_SET, buf, cnt);
    ili9488_write_register(ILI9488_CMD_NOP, 0, 0);
}
References get_0b_to_8b, get_8b_to_16b, ILI9488_CMD_COLUMN_ADDRESS_SET, ILI9488_CMD_NOP, ILI9488_CMD_PAGE_ADDRESS_SET, and ili9488_write_register().
Referenced by ili9488_draw_pixel(), ili9488_draw_prepare(), ili9488_fill(), ili9488_get_pixel(), ili9488_init(), ili9488_read_gram(), and ili9488_write_gram().
ili9488_set_display_direction()
void ili9488_set_display_direction (enum ili9488_display_direction direction)
ILI9488 configure landscape.
\Param LandscaprMode Landscape Mode.
Definition at line 560 of file ili9488.c.
{
    ili9488_color_t value;
    if(direction) {
        value = 0xE8;
    } else {
        value = 0x48;
    }
    ili9488_write_register(ILI9488_CMD_MEMORY_ACCESS_CONTROL, &value, 1);
}
References ILI9488_CMD_MEMORY_ACCESS_CONTROL, and ili9488_write_register().
Referenced by ili9488_init().
ili9488_set_foreground_color()
void ili9488_set_foreground_color (uint32_t ul_color)
Set foreground color.
Parameters
ul_color foreground color.
Definition at line 734 of file ili9488.c.
{
    uint32_t i;
#ifdef ILI9488_EBIMODE
    /* Fill the cache with selected color */
    for (i = 0; i < LCD_DATA_CACHE_SIZE; ++i) {
        g_ul_pixel_cache[i] = ul_color;
    }
#endif
#ifdef ILI9488_SPIMODE
    for (i = 0; i < LCD_DATA_CACHE_SIZE * LCD_DATA_COLOR_UNIT; ) {
        g_ul_pixel_cache[i++] = ul_color>>16;
        g_ul_pixel_cache[i++] = ul_color>>8;
        g_ul_pixel_cache[i++] = ul_color&0xFF;
    }
#endif
}
References g_ul_pixel_cache, LCD_DATA_CACHE_SIZE, and LCD_DATA_COLOR_UNIT.
Referenced by ili9488_init(), main(), refresh_display(), and wifi_connect().
ili9488_set_limits()
void ili9488_set_limits (ili9488_coord_t start_x, ili9488_coord_t start_y, ili9488_coord_t end_x, ili9488_coord_t end_y)
Set the full display drawing limits.
Use this function to set the full drawing limit box.
Parameters
start_x The x coordinate of the top left corner
start_y The y coordinate of the top left corner
end_x The x coordinate of the bottom right corner
end_y The y coordinate of the bottom right corner
Definition at line 1286 of file ili9488.c.
{
    limit_start_x = start_x;
    limit_start_y = start_y;
    limit_end_x = end_x;
    limit_end_y = end_y;
}
References limit_end_x, limit_end_y, limit_start_x, and limit_start_y.
ili9488_set_orientation()
void ili9488_set_orientation (uint8_t flags)
Sets the orientation of the display data.
Configures the display for a given orientation, including mirroring and/or screen rotation.
Parameters
flags Orientation flags to use, see ILI9488_FLIP_X, ILI9488_FLIP_Y and ILI9488_SWITCH_XY.
Definition at line 1304 of file ili9488.c.
{
    /* Flip X/Y and reverse X orientation and set BGR mode*/
    ili9488_color_t madctl = 0x68;
    if (flags & ILI9488_FLIP_X) {
        madctl &= ~(1 << 6);
    }
    if (flags & ILI9488_FLIP_Y) {
        madctl |= 1 << 7;
    }
    if (flags & ILI9488_SWITCH_XY) {
        madctl &= ~(1 << 5);
    }
    ili9488_write_register(ILI9488_CMD_MEMORY_ACCESS_CONTROL, &madctl, 1);
}
References ILI9488_CMD_MEMORY_ACCESS_CONTROL, ILI9488_FLIP_X, ILI9488_FLIP_Y, ILI9488_SWITCH_XY, and ili9488_write_register().
ili9488_set_scroll_address()
void ili9488_set_scroll_address (uint16_t ul_vsp)
Enable the scrolling feature.
Parameters
ul_vsp Vertical Scrolling Start Address
Definition at line 831 of file ili9488.c.
{
    uint32_t cnt = 0;
    ili9488_color_t buf[2];
    cnt = sizeof(buf)/sizeof(ili9488_color_t);
    buf[0] = get_8b_to_16b(ul_vsp);
    buf[1] = get_0b_to_8b(ul_vsp);
    ili9488_write_register(ILI9488_CMD_VERT_SCROLL_START_ADDRESS, buf, cnt);
}
References get_0b_to_8b, get_8b_to_16b, ILI9488_CMD_VERT_SCROLL_START_ADDRESS, and ili9488_write_register().
ili9488_set_top_left_limit()
void ili9488_set_top_left_limit (ili9488_coord_t x, ili9488_coord_t y)
Set the display top left drawing limit.
Use this function to set the top left limit of the drawing limit box.
Parameters
x The x coordinate of the top left corner
y The y coordinate of the top left corner
Definition at line 1256 of file ili9488.c.
{
    limit_start_x = x;
    limit_start_y = y;
}
References limit_start_x, and limit_start_y.
ili9488_set_window()
void ili9488_set_window (uint16_t x, uint16_t y, uint16_t width, uint16_t height)
ILI9488 configure window.
\Param x start position. \Param y start position. \Param width Width of window. \Param height Height of window.
Definition at line 579 of file ili9488.c.
{
    uint16_t col_start, col_end, row_start, row_end;
    uint32_t cnt = 0;
    ili9488_color_t buf[4];
    cnt = sizeof(buf)/sizeof(ili9488_color_t);
    col_start  =  x ;
    col_end    =  width + x - 1;
    row_start = y ;
    row_end   = height + y - 1;
    buf[0] = get_8b_to_16b(col_start);
    buf[1] = get_0b_to_8b(col_start);
    buf[2] = get_8b_to_16b(col_end);
    buf[3] = get_0b_to_8b(col_end);
    ili9488_write_register(ILI9488_CMD_COLUMN_ADDRESS_SET, buf, cnt);
    ili9488_write_register(ILI9488_CMD_NOP, 0, 0);
    /* Set Horizontal Address End Position */
    buf[0] = get_8b_to_16b(row_start);
    buf[1] = get_0b_to_8b(row_start);
    buf[2] = get_8b_to_16b(row_end);
    buf[3] = get_0b_to_8b(row_end);
    ili9488_write_register(ILI9488_CMD_PAGE_ADDRESS_SET, buf, cnt);
    ili9488_write_register(ILI9488_CMD_NOP, 0, 0);
}
References get_0b_to_8b, get_8b_to_16b, ili9488_font::height, ILI9488_CMD_COLUMN_ADDRESS_SET, ILI9488_CMD_NOP, ILI9488_CMD_PAGE_ADDRESS_SET, ili9488_write_register(), and ili9488_font::width.
Referenced by ili9488_copy_pixels_from_screen(), ili9488_copy_pixels_to_screen(), ili9488_draw_filled_rectangle(), ili9488_draw_pixmap(), ili9488_draw_prepare(), ili9488_duplicate_pixel(), and ili9488_init().
ili9488_write_brightness()
void ili9488_write_brightness (uint16_t us_value)
Set display brightness.
Configures the display for a given brightness value
Parameters
us_value brightness value need to written.
Definition at line 1239 of file ili9488.c.
{
    ili9488_write_register(ILI9488_CMD_WRITE_DISPLAY_BRIGHTNESS, (ili9488_color_t *)&us_value, 1);
}
References ILI9488_CMD_WRITE_DISPLAY_BRIGHTNESS, and ili9488_write_register().
ili9488_write_gram()
void ili9488_write_gram (uint16_t color)
Write the graphical memory with a single color pixel.
Use this function to write a single color pixel to the controller memory.
Limits have to be set prior to calling this function, e.g.:
ili9488_set_top_left_limit(0, 0);
ili9488_set_bottom_right_limit(320, 240);
...
Parameters
color The color pixel to write to the screen
Definition at line 1359 of file ili9488.c.
{
    ili9488_set_cursor_position(limit_start_x, limit_start_y);
    ili9488_write_ram_prepare();
#ifdef ILI9488_EBIMODE
    ili9488_write_ram(color);
#endif
#ifdef ILI9488_SPIMODE
    uint32_t color_666 = RGB_16_TO_18BIT(color);
    ili9488_write_ram(color_666 >> 16);
    ili9488_write_ram(color_666 >> 8);
    ili9488_write_ram(color_666 & 0xFF);
#endif
}
References ili9488_set_cursor_position(), ili9488_write_ram(), ili9488_write_ram_prepare(), limit_start_x, limit_start_y, and RGB_16_TO_18BIT.
ili9488_write_ram()
static void ili9488_write_ram (ili9488_color_t ul_color) static
Write data to LCD GRAM.
Parameters
ul_color 16-bits RGB color.
Definition at line 407 of file ili9488.c.
{
    pio_set_pin_high(LCD_SPI_CDS_PIO);
    spi_write(BOARD_ILI9488_SPI, ul_color, BOARD_ILI9488_SPI_NPCS, 0);
}
References BOARD_ILI9488_SPI, BOARD_ILI9488_SPI_NPCS, LCD_SPI_CDS_PIO, pio_set_pin_high(), and spi_write().
Referenced by ili9488_copy_pixels_to_screen(), ili9488_duplicate_pixel(), ili9488_fill(), and ili9488_write_gram().
ili9488_write_ram_buffer()
static void ili9488_write_ram_buffer (const ili9488_color_t * p_ul_buf, uint32_t ul_size) static
Write multiple data in buffer to LCD controller.
Parameters
p_ul_buf data buffer.
ul_size size in pixels.
Definition at line 419 of file ili9488.c.
{
    volatile uint32_t i;
    pio_set_pin_high(LCD_SPI_CDS_PIO);
    spi_write_packet(BOARD_ILI9488_SPI, p_ul_buf, ul_size);
    for(i = 0; i < 0xFF; i++);
}
References BOARD_ILI9488_SPI, LCD_SPI_CDS_PIO, pio_set_pin_high(), and spi_write_packet().
Referenced by ili9488_draw_filled_rectangle(), and ili9488_draw_pixel().
ili9488_write_ram_prepare()
static void ili9488_write_ram_prepare (void) static
Prepare to write GRAM data.
Definition at line 394 of file ili9488.c.
{
    volatile uint32_t i;
    pio_set_pin_low(LCD_SPI_CDS_PIO);
    spi_write(BOARD_ILI9488_SPI, ILI9488_CMD_MEMORY_WRITE, BOARD_ILI9488_SPI_NPCS, 0);
    for(i = 0; i < 0xFF; i++);
}
References BOARD_ILI9488_SPI, BOARD_ILI9488_SPI_NPCS, ILI9488_CMD_MEMORY_WRITE, LCD_SPI_CDS_PIO, pio_set_pin_low(), and spi_write().
Referenced by ili9488_copy_pixels_to_screen(), ili9488_draw_filled_rectangle(), ili9488_draw_pixel(), ili9488_draw_prepare(), ili9488_duplicate_pixel(), ili9488_fill(), and ili9488_write_gram().
ili9488_write_register()
static void ili9488_write_register (uint8_t uc_reg, const ili9488_color_t * us_data, uint32_t size) static
Write data to LCD Register.
Parameters
uc_reg register address.
us_data data to be written.
size the number of parameters.
Definition at line 434 of file ili9488.c.
{
    volatile uint32_t i;
    /* Transfer cmd */
    pio_set_pin_low(LCD_SPI_CDS_PIO);
    spi_write(BOARD_ILI9488_SPI, uc_reg, BOARD_ILI9488_SPI_NPCS, 0);
    for(i = 0; i < 0xFF; i++);
    if(size > 0) {
        /* Transfer data */
        pio_set_pin_high(LCD_SPI_CDS_PIO);
        spi_write_packet(BOARD_ILI9488_SPI, us_data, size);
        for(i = 0; i < 0x5F; i++);
    }
}
References BOARD_ILI9488_SPI, BOARD_ILI9488_SPI_NPCS, LCD_SPI_CDS_PIO, pio_set_pin_high(), pio_set_pin_low(), spi_write(), and spi_write_packet().
Referenced by ili9488_copy_pixels_from_screen(), ili9488_copy_pixels_to_screen(), ili9488_display_off(), ili9488_display_on(), ili9488_draw_pixmap(), ili9488_init(), ili9488_read_chipid(), ili9488_read_ram(), ili9488_scroll(), ili9488_set_cursor_position(), ili9488_set_display_direction(), ili9488_set_orientation(), ili9488_set_scroll_address(), ili9488_set_window(), and ili9488_write_brightness().
Variable Documentation
g_ul_pixel_cache
ili9488_color_t g_ul_pixel_cache[LCD_DATA_CACHE_SIZE *LCD_DATA_COLOR_UNIT] static
Definition at line 70 of file ili9488.c.
Referenced by ili9488_draw_filled_rectangle(), ili9488_draw_pixel(), and ili9488_set_foreground_color().
gfont
const struct ili9488_font gfont = {10, 14}
Definition at line 73 of file ili9488.c.
Referenced by ili9488_draw_string().
limit_end_x
ili9488_coord_t limit_end_x static
Definition at line 1246 of file ili9488.c.
Referenced by ili9488_copy_pixels_from_screen(), ili9488_copy_pixels_to_screen(), ili9488_duplicate_pixel(), ili9488_set_bottom_right_limit(), and ili9488_set_limits().
limit_end_y
ili9488_coord_t limit_end_y static
Definition at line 1246 of file ili9488.c.
Referenced by ili9488_copy_pixels_from_screen(), ili9488_copy_pixels_to_screen(), ili9488_duplicate_pixel(), ili9488_set_bottom_right_limit(), and ili9488_set_limits().
limit_start_x
ili9488_coord_t limit_start_x static
Definition at line 1245 of file ili9488.c.
Referenced by ili9488_copy_pixels_from_screen(), ili9488_copy_pixels_to_screen(), ili9488_duplicate_pixel(), ili9488_read_gram(), ili9488_set_limits(), ili9488_set_top_left_limit(), and ili9488_write_gram().
limit_start_y
ili9488_coord_t limit_start_y static
Definition at line 1245 of file ili9488.c.
Referenced by ili9488_copy_pixels_from_screen(), ili9488_copy_pixels_to_screen(), ili9488_duplicate_pixel(), ili9488_read_gram(), ili9488_set_limits(), ili9488_set_top_left_limit(), and ili9488_write_gram().
p_uc_charset10x14
const uint8_t p_uc_charset10x14[]
Character set table for font 10x14 Coding format: Char height is 14 bits, which is coded using 2 bytes per column (2 unused bits).
Char width is 10 bits.
Definition at line 80 of file ili9488.c.
Referenced by ili9488_draw_char().