WINC1500 Weather Client Demo for SAME70 Xplained: MPU - Memory Protect Unit
MPU - Memory Protect Unit
Modules
MMU Initialization
Files
file mpu.c
SAMV70/SAMV71/SAME70/SAMS70-XULTRA board mpu config.
Functions
uint32_t mpu_cal_mpu_region_size (uint32_t dw_actual_size_in_bytes)
Calculate region size for the RASR.
void mpu_disable_region (void)
Disable the current active region.
void mpu_enable (uint32_t dw_mpu_enable)
Enables the MPU module.
void mpu_set_region (uint32_t dw_region_base_addr, uint32_t dw_region_attr)
Setup a memory region.
void mpu_set_region_num (uint32_t dw_region_num)
Set active memory region.
void mpu_update_regions (uint32_t dw_region_num, uint32_t dw_region_base_addr, uint32_t dw_region_attr)
Update MPU regions.
Detailed Description
Function Documentation
mpu_cal_mpu_region_size()
uint32_t mpu_cal_mpu_region_size (uint32_t dw_actual_size_in_bytes)
Calculate region size for the RASR.
Definition at line 126 of file mpu.c.
{
    uint32_t dwRegionSize = 32;
    uint32_t dwReturnValue = 4;
    while( dwReturnValue < 31 ) {
        if( dw_actual_size_in_bytes <= dwRegionSize ) {
            break;
        } else {
            dwReturnValue++;
        }
        dwRegionSize <<= 1;
    }
    return ( dwReturnValue << 1 );
}
mpu_disable_region()
void mpu_disable_region (void)
Disable the current active region.
Definition at line 105 of file mpu.c.
{
    MPU->RASR &= 0xfffffffe;
}
Referenced by mpu_update_regions().
mpu_enable()
void mpu_enable (uint32_t dw_mpu_enable)
Enables the MPU module.
Parameters
dwMPUEnable Enable/Disable the memory region.
Definition at line 87 of file mpu.c.
{
    MPU->CTRL = dw_mpu_enable ;
}
mpu_set_region()
void mpu_set_region (uint32_t dw_region_base_addr, uint32_t dw_region_attr)
Setup a memory region.
Parameters
dwRegionBaseAddr Memory region base address.
dwRegionAttr Memory region attributes.
Definition at line 116 of file mpu.c.
{
    MPU->RBAR = dw_region_base_addr;
    MPU->RASR = dw_region_attr;
}
Referenced by mpu_update_regions().
mpu_set_region_num()
void mpu_set_region_num (uint32_t dw_region_num)
Set active memory region.
Parameters
dwRegionNum The memory region to be active.
Definition at line 97 of file mpu.c.
{
    MPU->RNR = dw_region_num;
}
Referenced by mpu_update_regions().
mpu_update_regions()
void mpu_update_regions (uint32_t dw_region_num, uint32_t dw_region_base_addr, uint32_t dw_region_attr)
Update MPU regions.
Returns
Unused (ANSI-C compatibility).
Definition at line 149 of file mpu.c.
{
    volatile irqflags_t flags;
    /* Get and clear the global interrupt flags */
    flags = cpu_irq_save();
    /* Clean up data and instruction buffer */
    __DSB();
    __ISB();
    /* Set active region */
    mpu_set_region_num(dw_region_num);
    /* Disable region */
    mpu_disable_region();
    /* Update region attribute */
    mpu_set_region( dw_region_base_addr, dw_region_attr);
    /* Clean up data and instruction buffer to make the new region taking
       effect at once */
    __DSB();
    __ISB();
    /* Restore global interrupt flags */
    cpu_irq_restore(flags);
}
References cpu_irq_restore(), cpu_irq_save(), mpu_disable_region(), mpu_set_region(), and mpu_set_region_num().