WINC1500 Weather Client Demo for SAME70 Xplained: WLAN
WLAN
Modules
Callbacks
Provides detail on the available callbacks for the Wlan APIs.
Defines
Specifies the macros and defines used by the Wlan APIs.
Enumerations and Typedefs
Specifies the enums and Data Structures used by the Wlan APIs.
Functions
Here are listed all the functions that implement the Wlan APIs.
Version
Describes the APIs for reading the version information of the WINC firmware.
Functions
sint8 m2m_wifi_1x_get_option (tenu1xOption enuOptionName, void *pOptionValue, size_t *pOptionLen)
API to get (read) options relating to Wi-Fi connection using WPA(2) Enterprise authentication.
sint8 m2m_wifi_1x_set_option (tenu1xOption enuOptionName, const void *pOptionValue, size_t OptionLen)
API to set (write) options relating to Wi-Fi connection using WPA(2) Enterprise authentication.
NMI_API sint8 m2m_wifi_conf_auto_rate (tstrConfAutoRate *pstrConfAutoRate)
Allow the host MCU app to configure auto TX rate selection algorithm. The application can use this API to tweak the algorithm performance. Moreover, it allows the application to force a specific WLAN PHY rate for transmitted data packets to favor range vs. throughput needs.
NMI_API sint8 m2m_wifi_configure_sntp (uint8 *pu8NTPServerName, uint8 u8NTPServerNameLength, tenuSNTPUseDHCP useDHCP)
Configures what NTP server the SNTP client should use.
NMI_API sint8 m2m_wifi_connect (char *pcSsid, uint8 u8SsidLen, uint8 u8SecType, void *pvAuthInfo, uint16 u16Ch)
DEPRECATED in v19.6.1 - Kept only for legacy purposes.
Legacy asynchronous API to request connection to a specified access point.
sint8 m2m_wifi_connect_1x_mschap2 (tenuCredStoreOption enuCredStoreOption, tstrNetworkId *pstrNetworkId, tstrAuth1xMschap2 *pstrAuth1xMschap2)
Asynchronous API to connect to an access point using WPA(2) Enterprise authentication with MS-CHAP-V2 credentials.
sint8 m2m_wifi_connect_1x_tls (tenuCredStoreOption enuCredStoreOption, tstrNetworkId *pstrNetworkId, tstrAuth1xTls *pstrAuth1xTls)
Asynchronous API to connect to an access point using WPA(2) Enterprise authentication with MS-CHAP-V2 credentials.
sint8 m2m_wifi_connect_open (tenuCredStoreOption enuCredStoreOption, tstrNetworkId *pstrNetworkId)
Asynchronous API to connect to an access point using open authentication.
sint8 m2m_wifi_connect_psk (tenuCredStoreOption enuCredStoreOption, tstrNetworkId *pstrNetworkId, tstrAuthPsk *pstrAuthPsk)
Asynchronous API to connect to an access point using WPA(2) PSK authentication.
NMI_API sint8 m2m_wifi_connect_sc (char *pcSsid, uint8 u8SsidLen, uint8 u8SecType, void *pvAuthInfo, uint16 u16Ch, uint8 u8NoSaveCred)
DEPRECATED in v19.6.1 - Kept only for legacy purposes.
Legacy asynchronous API to request connection to a specific AP with the option to save credentials in Flash.
sint8 m2m_wifi_connect_wep (tenuCredStoreOption enuCredStoreOption, tstrNetworkId *pstrNetworkId, tstrAuthWep *pstrAuthWep)
Asynchronous API to connect to an access point using WEP authentication.
NMI_API sint8 m2m_wifi_default_connect (void)
Asynchronous API that attempts to reconnect to the last-associated access point.
NMI_API sint8 m2m_wifi_deinit (void *arg)
De-initialize the WINC driver and host interface.
sint8 m2m_wifi_delete_sc (char *pcSsid, uint8 u8SsidLen)
Asynchronous API that deletes connection credentials (PSK, WEP key, 802.1X password) from WINC flash. Either deletes all credentials, or for a specific SSID.
NMI_API sint8 m2m_wifi_disable_ap (void)
Synchronous API to disable access point mode on the WINC IC.
sint8 m2m_wifi_disable_roaming (void)
Disable WiFi STA roaming.
NMI_API sint8 m2m_wifi_disconnect (void)
Synchronous API to request disconnection from a network.
NMI_API sint8 m2m_wifi_download_mode (void)
Prepares the WINC board before downloading any data (Firmware, Certificates, etc).
NMI_API sint8 m2m_wifi_enable_ap (CONST tstrM2MAPConfig *pstrM2MAPConfig)
Asynchronous API to enable access point (AKA "hot-spot") mode on the WINC IC.
NMI_API sint8 m2m_wifi_enable_ap_ext (CONST tstrM2MAPModeConfig *pstrM2MAPModeConfig)
Asynchronous API to enable access point (AKA "hot-spot") mode on the WINC IC with extended options.
NMI_API sint8 m2m_wifi_enable_dhcp (uint8 u8DhcpEn)
Enable/Disable the DHCP client after connection.
sint8 m2m_wifi_enable_firmware_logs (uint8 u8Enable)
Enable or Disable logs in run time (Disable Firmware logs will enhance the firmware start-up time and performance)
sint8 m2m_wifi_enable_roaming (uint8 bEnableDhcp)
Enable WiFi STA roaming.
NMI_API sint8 m2m_wifi_enable_sntp (uint8 bEnable)
Synchronous function to enable/disable the native Simple Network Time Protocol(SNTP) client in the WINC15x0 firmware.
sint8 m2m_wifi_enable_XO_during_sleep (uint8 bXOSleepEnable)
Specifies whether the crystal oscillator is left on or off during deep sleep (defaults to off).
NMI_API sint8 m2m_wifi_get_connection_info (void)
Asynchronous API for retrieving the WINC IC's connection status.
NMI_API sint8 m2m_wifi_get_firmware_version (tstrM2mRev *pstrRev)
Get Firmware version info.
NMI_API sint8 m2m_wifi_get_mac_address (uint8 *pu8MacAddr)
Request the current MAC address of the device (the working mac address). (the function is Blocking until response received)
NMI_API uint8 m2m_wifi_get_num_ap_found (void)
Reads the number of AP's found in the last Scan Request, The function read the number of AP's from global variable which updated in the wifi_cb in M2M_WIFI_RESP_SCAN_DONE.
NMI_API sint8 m2m_wifi_get_otp_mac_address (uint8 *pu8MacAddr, uint8 *pu8IsValid)
Request the MAC address stored on the OTP (one time programmable) memory of the device. (the function is Blocking until response received)
NMI_API uint8 m2m_wifi_get_sleep_mode (void)
Get the current Power save mode.
NMI_API uint8 m2m_wifi_get_state (void)
Get the wifi state.
NMI_API sint8 m2m_wifi_get_system_time (void)
Asynchronous API to obtain the system time in use by the WINC IC.
NMI_API sint8 m2m_wifi_handle_events (void *arg)
Synchronous M2M event handler function.
NMI_API sint8 m2m_wifi_init (tstrWifiInitParam *pWifiInitParam)
Synchronous API to initialize the WINC driver.
NMI_API sint8 m2m_wifi_init_hold (void)
First part of m2m_wifi_init, up to the point of initializing SPI for flash access.
NMI_API sint8 m2m_wifi_init_start (tstrWifiInitParam *pWifiInitParam)
Second part of m2m_wifi_init, continuing from where m2m_wifi_init_hold left off.
sint8 m2m_wifi_prng_get_random_bytes (uint8 *pu8PrngBuff, uint16 u16PrngSize)
Get random bytes using the PRNG bytes.
NMI_API sint8 m2m_wifi_reinit (tstrWifiInitParam *pWifiInitParam)
De-initialize and then initialize wifi. Resets the WINC.
NMI_API sint8 m2m_wifi_reinit_hold (void)
First part of m2m_wifi_reinit, up to the point of initializing SPI for flash access.
NMI_API sint8 m2m_wifi_reinit_start (tstrWifiInitParam *pWifiInitParam)
Second part of m2m_wifi_reinit, continuing from where m2m_wifi_reinit_hold left off.
NMI_API sint8 m2m_wifi_req_client_ctrl (uint8 cmd)
Send a command to the PS Client (An WINC board running the ps_firmware), if the PS client send any commands it will be received in wifi_cb M2M_WIFI_RESP_CLIENT_INFO.
NMI_API sint8 m2m_wifi_req_curr_rssi (void)
Request the current RSSI for the current connected AP, the response received in wifi_cb M2M_WIFI_RESP_CURRENT_RSSI
NMI_API sint8 m2m_wifi_req_scan_result (uint8 index)
Reads the AP information from the Scan Result list with the given index, the response received in wifi_cb M2M_WIFI_RESP_SCAN_RESULT, the response pointer should be casted with tstrM2mWifiscanResult structure
NMI_API sint8 m2m_wifi_req_server_init (uint8 ch)
Initialize the PS Server, The WINC support non secure communication with another WINC, (SERVER/CLIENT) through one byte command (probe request and probe response) without any connection setup.
NMI_API sint8 m2m_wifi_request_dhcp_client (void)
Legacy (deprecated) Asynchronous API for starting a DHCP client on the WINC IC.
NMI_API sint8 m2m_wifi_request_dhcp_server (uint8 *addr)
Dhcp requested by the firmware automatically in STA/AP mode).
NMI_API sint8 m2m_wifi_request_scan (uint8 ch)
Asynchronous API to request the WINC IC to scan for networks.
NMI_API sint8 m2m_wifi_request_scan_passive (uint8 ch, uint16 scan_time)
Similar to m2m_wifi_request_scan but performs passive scanning instead of active scanning.
NMI_API sint8 m2m_wifi_request_scan_ssid_list (uint8 ch, uint8 *u8Ssidlist)
Asynchronous wi-fi scan request on the given channel and the hidden scan list.
NMI_API sint8 m2m_wifi_request_sleep (uint32 u32SlpReqTime)
API to place the WINC IC into sleep mode for a specified period of time.
sint8 m2m_wifi_send_crl (tstrTlsCrlInfo *pCRL)
Asynchronous API that notifies the WINC with the Certificate Revocation List.
NMI_API sint8 m2m_wifi_send_ethernet_pkt (uint8 *pu8Packet, uint16 u16PacketSize)
Synchronous function to transmit an Ethernet packet.
sint8 m2m_wifi_set_battery_voltage (uint16 u16BattVoltx100)
Enable or Disable logs in run time (Disable Firmware logs will enhance the firmware start-up time and performance)
NMI_API sint8 m2m_wifi_set_cust_InfoElement (uint8 *pau8M2mCustInfoElement)
API to add or remove a user-defined Information Element.
NMI_API sint8 m2m_wifi_set_device_name (uint8 *pu8DeviceName, uint8 u8DeviceNameLength)
Sets the WINC device name. The name string is used as a device name in DHCP hostname (option 12).
sint8 m2m_wifi_set_gain_table_idx (uint8 u8GainTableIdx)
set the gain table index corresponding to a specific WiFi region
sint8 m2m_wifi_set_gains (tstrM2mWifiGainsParams *pstrM2mGain)
Set the chip PPA gain for 11b/11gn.
NMI_API sint8 m2m_wifi_set_lsn_int (tstrM2mLsnInt *pstrM2mLsnInt)
Set the Wi-Fi listen interval for power save operation. It is represented in units of AP Beacon periods.
NMI_API sint8 m2m_wifi_set_mac_address (uint8 au8MacAddress[6])
Synchronous API for assigning a MAC address to the WINC IC.
sint8 m2m_wifi_set_power_profile (uint8 u8PwrMode)
Change the power profile mode.
NMI_API sint8 m2m_wifi_set_scan_options (tstrM2MScanOption *ptstrM2MScanOption)
Synchronous API for configuring the behaviour of the WINC IC's network scanning functions.
NMI_API sint8 m2m_wifi_set_scan_region (uint16 ScanRegion)
Synchronous API for configuring the regulatory restrictions that may affect the WINC ICs scanning behaviour.
NMI_API sint8 m2m_wifi_set_sleep_mode (uint8 PsTyp, uint8 BcastEn)
Set the power saving mode for the WINC1500.
NMI_API sint8 m2m_wifi_set_static_ip (tstrM2MIPConfig *pstrStaticIPConf)
Synchronous API to manually assign a (static) IP address to the WINC IC.
NMI_API sint8 m2m_wifi_set_stop_scan_on_first (uint8 u8StopScanOption)
Synchronous API for enabling/disabling the stop scan on first result of the WINC IC's network scanning functions.
NMI_API sint8 m2m_wifi_set_system_time (uint32 u32UTCSeconds)
Function for setting the system time within the WINC IC.
sint8 m2m_wifi_set_tx_power (uint8 u8TxPwrLevel)
set the TX power tenuM2mTxPwrLevel
NMI_API sint8 m2m_wifi_start_provision_mode (tstrM2MAPConfig *pstrAPConfig, char *pcHttpServerDomainName, uint8 bEnableHttpRedirect)
Asynchronous API for control of Wi-Fi provisioning functionality.
NMI_API sint8 m2m_wifi_start_provision_mode_ext (tstrM2MAPModeConfig *pstrAPModeConfig, char *pcHttpServerDomainName, uint8 bEnableHttpRedirect)
Asynchronous API for control of Wi-Fi provisioning functionality with extended options.
NMI_API sint8 m2m_wifi_stop_provision_mode (void)
Synchronous API for terminating provisioning mode on the WINC IC.
NMI_API sint8 m2m_wifi_wps (uint8 u8TriggerType, const char *pcPinNumber)
Asynchronous API to engage the WINC IC's Wi-Fi Protected Setup (enrollee) function.
NMI_API sint8 m2m_wifi_wps_disable (void)
Stops the ongoing WPS session.
NMI_API void m2m_wifi_yield (void)
Yield from processing more synchronous M2M events.
Variables
uint8 tstrM2mWifiWepParams::__PAD24__ [3]
uint8 tstrEthInitParam::__PAD8__
uint8 * tstrEthInitParam::au8ethRcvBuf
uint8 tstr1xAuthCredentials::au8Passwd [41]
uint8 tstr1xAuthCredentials::au8UserName [21]
uint8 tstrM2mWifiWepParams::au8WepKey [WEP_104_KEY_STRING_SIZE+1]
bool tstrAuth1xMschap2::bPrependDomain
bool tstrAuth1xTls::bPrependDomain
bool tstrAuth1xMschap2::bUnencryptedUserName
bool tstrAuth1xTls::bUnencryptedUserName
tenuM2mScanCh tstrNetworkId::enuChannel
tpfAppEthCb tstrEthInitParam::pfAppEthCb
tpfAppMonCb tstrWifiInitParam::pfAppMonCb
tpfAppWifiCb tstrEthInitParam::pfAppWifiCb
tpfAppWifiCb tstrWifiInitParam::pfAppWifiCb
uint8 * tstrNetworkId::pu8Bssid
uint8 * tstrAuth1xTls::pu8Certificate
uint8 * tstrAuth1xMschap2::pu8Domain
uint8 * tstrAuth1xTls::pu8Domain
uint8 * tstrAuthPsk::pu8Passphrase
uint8 * tstrAuth1xMschap2::pu8Password
uint8 * tstrAuth1xTls::pu8PrivateKey_Exp
uint8 * tstrAuth1xTls::pu8PrivateKey_Mod
uint8 * tstrAuthPsk::pu8Psk
uint8 * tstrNetworkId::pu8Ssid
uint8 * tstrAuth1xMschap2::pu8UserName
uint8 * tstrAuth1xTls::pu8UserName
uint8 * tstrAuthWep::pu8WepKey
tstrEthInitParam tstrWifiInitParam::strEthInitParam
uint16 tstrAuth1xTls::u16CertificateLen
uint16 tstrM2mIpCtrlBuf::u16DataSize
uint16 tstrAuth1xMschap2::u16DomainLen
uint16 tstrAuth1xTls::u16DomainLen
uint16 tstrEthInitParam::u16ethRcvBufSize
uint16 tstrAuth1xMschap2::u16PasswordLen
uint16 tstrAuth1xTls::u16PrivateKeyLen
uint16 tstrM2mIpCtrlBuf::u16RemainingDataSize
uint16 tstrAuth1xMschap2::u16UserNameLen
uint16 tstrAuth1xTls::u16UserNameLen
uint8 tstrEthInitParam::u8EthernetEnable
uint8 tstrM2mWifiWepParams::u8KeyIndx
uint8 tstrAuthWep::u8KeyIndx
uint8 tstrM2mWifiWepParams::u8KeySz
uint8 tstrAuthWep::u8KeySz
uint8 tstrAuthPsk::u8PassphraseLen
uint8 tstrNetworkId::u8SsidLen
Detailed Description
Function Documentation
m2m_wifi_1x_get_option()
sint8 m2m_wifi_1x_get_option (tenu1xOption enuOptionName, void * pOptionValue, size_t * pOptionLen)
API to get (read) options relating to Wi-Fi connection using WPA(2) Enterprise authentication.
The following options can be read:
WIFI_1X_BYPASS_SERVER_AUTH
WIFI_1X_SESSION_CACHING
WIFI_1X_SPECIFIC_ROOTCERT
WIFI_1X_TIME_VERIF_MODE
Parameters
[in] enuOptionName The option to get.
[out] pOptionValue Pointer to a buffer containing the value to set. The buffer must be at least as long as OptionLen. If OptionLen is 0, then pOptionValue may be NULL.
[in,out] pOptionLen Pointer to a length. When calling the function, this length must be the length of the buffer available for reading the option value. When the function returns, this length is the length of the data that has been populated by the function.
Returns
The function returns M2M_SUCCESS if the parameters are valid and M2M_ERR_INVALID_ARG otherwise.
Definition at line 843 of file m2m_wifi.c.
{
    if(pOptionValue == NULL)
        return M2M_ERR_INVALID_ARG;
    switch(enuOptionName)
    {
    case WIFI_1X_BYPASS_SERVER_AUTH:
        if(*pOptionLen < sizeof(int))
            return M2M_ERR_INVALID_ARG;
        *pOptionLen = sizeof(int);
        *(int*)pOptionValue = (gu321xTlsHsFlags & WIFI_1X_TLS_HS_FLAGS_PEER_AUTH) ? 0 : 1;
        break;
    case WIFI_1X_TIME_VERIF_MODE:
        if(*pOptionLen < sizeof(tenuSslCertExpSettings))
            return M2M_ERR_INVALID_ARG;
        *pOptionLen = sizeof(tenuSslCertExpSettings);
        if(!(gu321xTlsHsFlags & WIFI_1X_TLS_HS_FLAGS_PEER_CERTTIMECHECK))
            *(tenuSslCertExpSettings*)pOptionValue = SSL_CERT_EXP_CHECK_DISABLE;
        else if(gu321xTlsHsFlags & WIFI_1X_TLS_HS_FLAGS_REQUIRE_TIME)
            *(tenuSslCertExpSettings*)pOptionValue = SSL_CERT_EXP_CHECK_ENABLE;
        else
            *(tenuSslCertExpSettings*)pOptionValue = SSL_CERT_EXP_CHECK_EN_IF_SYS_TIME;
        break;
    case WIFI_1X_SESSION_CACHING:
        if(*pOptionLen < sizeof(int))
            return M2M_ERR_INVALID_ARG;
        *pOptionLen = sizeof(int);
        *(int*)pOptionValue = (gu321xTlsHsFlags & WIFI_1X_TLS_HS_FLAGS_SESSION_CACHING) ? 1 : 0;
        break;
    case WIFI_1X_SPECIFIC_ROOTCERT:
        if(gu321xTlsHsFlags & WIFI_1X_TLS_HS_FLAGS_SPECIFY_ROOTCERT)
        {
            if(*pOptionLen < sizeof(gau81xRootSha1))
                return M2M_ERR_INVALID_ARG;
            *pOptionLen = sizeof(gau81xRootSha1);
            m2m_memcpy((uint8*)pOptionValue, gau81xRootSha1, sizeof(gau81xRootSha1));
        }
        else
            *pOptionLen = 0;
        break;
    default:
        return M2M_ERR_INVALID_ARG;
    }
    return M2M_SUCCESS;
}
References gau81xRootSha1, gu321xTlsHsFlags, M2M_ERR_INVALID_ARG, m2m_memcpy(), M2M_SUCCESS, NULL, SSL_CERT_EXP_CHECK_DISABLE, SSL_CERT_EXP_CHECK_EN_IF_SYS_TIME, SSL_CERT_EXP_CHECK_ENABLE, WIFI_1X_BYPASS_SERVER_AUTH, WIFI_1X_SESSION_CACHING, WIFI_1X_SPECIFIC_ROOTCERT, WIFI_1X_TIME_VERIF_MODE, WIFI_1X_TLS_HS_FLAGS_PEER_AUTH, WIFI_1X_TLS_HS_FLAGS_PEER_CERTTIMECHECK, WIFI_1X_TLS_HS_FLAGS_REQUIRE_TIME, WIFI_1X_TLS_HS_FLAGS_SESSION_CACHING, and WIFI_1X_TLS_HS_FLAGS_SPECIFY_ROOTCERT.
m2m_wifi_1x_set_option()
sint8 m2m_wifi_1x_set_option (tenu1xOption enuOptionName, const void * pOptionValue, size_t OptionLen)
API to set (write) options relating to Wi-Fi connection using WPA(2) Enterprise authentication.
The following options can be set:
WIFI_1X_BYPASS_SERVER_AUTH
WIFI_1X_SESSION_CACHING
WIFI_1X_SPECIFIC_ROOTCERT
WIFI_1X_TIME_VERIF_MODE
The setting applies to all subsequent connection attempts via m2m_wifi_connect_1x_mschap2 or m2m_wifi_connect_1x_tls.
Connection attempts via m2m_wifi_default_connect use the settings which were in place at the time of the original connection.
Parameters
[in] enuOptionName The option to set.
[in] pOptionValue Pointer to a buffer containing the value to set. The buffer must be at least as long as OptionLen. If OptionLen is 0, then pOptionValue may be NULL.
[in] OptionLen The length of the option value being set.
Returns
The function returns M2M_SUCCESS if the parameters are valid and M2M_ERR_INVALID_ARG otherwise.
Definition at line 766 of file m2m_wifi.c.
{
    if((pOptionValue == NULL) && (OptionLen > 0))
        return M2M_ERR_INVALID_ARG;
    switch(enuOptionName)
    {
    case WIFI_1X_BYPASS_SERVER_AUTH:
        if(OptionLen != sizeof(int))
            return M2M_ERR_INVALID_ARG;
        switch(*(int*)pOptionValue)
        {
        case 1:
            gu321xTlsHsFlags &= ~WIFI_1X_TLS_HS_FLAGS_PEER_AUTH;
            break;
        case 0:
            gu321xTlsHsFlags |= WIFI_1X_TLS_HS_FLAGS_PEER_AUTH;
            break;
        default:
            return M2M_ERR_INVALID_ARG;
        }
        break;
    case WIFI_1X_TIME_VERIF_MODE:
        if(OptionLen != sizeof(tenuSslCertExpSettings))
            return M2M_ERR_INVALID_ARG;
        switch(*(tenuSslCertExpSettings*)pOptionValue)
        {
        case SSL_CERT_EXP_CHECK_DISABLE:
            gu321xTlsHsFlags &= ~WIFI_1X_TLS_HS_FLAGS_PEER_CERTTIMECHECK;
            gu321xTlsHsFlags &= ~WIFI_1X_TLS_HS_FLAGS_REQUIRE_TIME;
            break;
        case SSL_CERT_EXP_CHECK_ENABLE:
            gu321xTlsHsFlags |= WIFI_1X_TLS_HS_FLAGS_PEER_CERTTIMECHECK;
            gu321xTlsHsFlags |= WIFI_1X_TLS_HS_FLAGS_REQUIRE_TIME;
            break;
        case SSL_CERT_EXP_CHECK_EN_IF_SYS_TIME:
            gu321xTlsHsFlags |= WIFI_1X_TLS_HS_FLAGS_PEER_CERTTIMECHECK;
            gu321xTlsHsFlags &= ~WIFI_1X_TLS_HS_FLAGS_REQUIRE_TIME;
            break;
        default:
            return M2M_ERR_INVALID_ARG;
        }
        break;
    case WIFI_1X_SESSION_CACHING:
        if(OptionLen != sizeof(int))
            return M2M_ERR_INVALID_ARG;
        switch(*(int*)pOptionValue)
        {
        case 1:
            gu321xTlsHsFlags |= WIFI_1X_TLS_HS_FLAGS_SESSION_CACHING;
            break;
        case 0:
            gu321xTlsHsFlags &= ~WIFI_1X_TLS_HS_FLAGS_SESSION_CACHING;
            break;
        default:
            return M2M_ERR_INVALID_ARG;
        }
        break;
    case WIFI_1X_SPECIFIC_ROOTCERT:
        switch(OptionLen)
        {
        case 20:
            gu321xTlsHsFlags |= WIFI_1X_TLS_HS_FLAGS_SPECIFY_ROOTCERT;
            m2m_memcpy(gau81xRootSha1, (uint8*)pOptionValue, sizeof(gau81xRootSha1));
            break;
        case 0:
            gu321xTlsHsFlags &= ~WIFI_1X_TLS_HS_FLAGS_SPECIFY_ROOTCERT;
            m2m_memset(gau81xRootSha1, 0, sizeof(gau81xRootSha1));
        default:
            return M2M_ERR_INVALID_ARG;
        }
        break;
    default:
        return M2M_ERR_INVALID_ARG;
    }
    return M2M_SUCCESS;
}
References gau81xRootSha1, gu321xTlsHsFlags, M2M_ERR_INVALID_ARG, m2m_memcpy(), m2m_memset(), M2M_SUCCESS, NULL, SSL_CERT_EXP_CHECK_DISABLE, SSL_CERT_EXP_CHECK_EN_IF_SYS_TIME, SSL_CERT_EXP_CHECK_ENABLE, WIFI_1X_BYPASS_SERVER_AUTH, WIFI_1X_SESSION_CACHING, WIFI_1X_SPECIFIC_ROOTCERT, WIFI_1X_TIME_VERIF_MODE, WIFI_1X_TLS_HS_FLAGS_PEER_AUTH, WIFI_1X_TLS_HS_FLAGS_PEER_CERTTIMECHECK, WIFI_1X_TLS_HS_FLAGS_REQUIRE_TIME, WIFI_1X_TLS_HS_FLAGS_SESSION_CACHING, and WIFI_1X_TLS_HS_FLAGS_SPECIFY_ROOTCERT.
m2m_wifi_conf_auto_rate()
NMI_API sint8 m2m_wifi_conf_auto_rate (tstrConfAutoRate * pstrConfAutoRate)
Allow the host MCU app to configure auto TX rate selection algorithm. The application can use this API to tweak the algorithm performance. Moreover, it allows the application to force a specific WLAN PHY rate for transmitted data packets to favor range vs. throughput needs.
Configures WLAN automatic TX rate adaptation algorithm.
Parameters
[in] pstrConfAutoRate The Auto rate configuration parameters as listed in tstrConfAutoRate.
See also
tstrConfAutoRate
Returns
The function SHALL return 0 for success and a negative value otherwise.
Allow the host MCU app to configure auto TX rate selection algorithm. The application can use this API to tweak the algorithm performance. Moreover, it allows the application to force a specific WLAN PHY rate for transmitted data packets to favor range vs. throughput needs.
Parameters
[in] pstrConfAutoRate The Auto rate configuration parameters as listed in tstrConfAutoRate.
Returns
The function SHALL return M2M_SUCCESS for success and a negative value otherwise.
See also
tstrConfAutoRate
Definition at line 1949 of file m2m_wifi.c.
{
    sint8 s8ret = M2M_ERR_FAIL;
    s8ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CONG_AUTO_RATE, (uint8 *)pstrConfAutoRate,sizeof(tstrConfAutoRate),NULL,0,0);
    return s8ret;
}
References hif_send(), M2M_ERR_FAIL, M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CONG_AUTO_RATE, and NULL.
m2m_wifi_configure_sntp()
NMI_API sint8 m2m_wifi_configure_sntp (uint8 * pu8NTPServerName, uint8 u8NTPServerNameLength, tenuSNTPUseDHCP useDHCP)
Configures what NTP server the SNTP client should use.
Parameters
[in] pu8NTPServerName Buffer holding the NTP server name. If the first character is an asterisk (*) then it will be treated as a server pool, where the asterisk will be replaced with an incrementing value from 0 to 3 each time a server fails (example: *.pool.ntp.org).
[in] u8NTPServerNameLength Length of the NTP server name. Should not exceed the maximum NTP server name length of M2M_NTP_MAX_SERVER_NAME_LENGTH
[in] useDHCP Should the NTP server provided by the DHCP server be used.
Returns
The function SHALL return M2M_SUCCESS for success and a negative value otherwise.
Configures what NTP server the SNTP client should use. Only 1 server name can be provided, if the configured server name begins with an asterisk then it will be treated as a server pool. The SNTP client can also use the NTP server provided by the DHCP server through option 42. By default the NTP server provided by DHCP will be tried first, then the built-in default NTP server (time.nist.gov) will be used.
Parameters
[in] pu8NTPServerName Buffer holding the NTP server name. If the first character is an asterisk (*) then it will be treated as a server pool, where the asterisk will be replaced with an incrementing value from 0 to 3 each time a server fails (example: *.pool.ntp.org).
[in] u8NTPServerNameLength Length of the NTP server name. Should not exceed the maximum NTP server name length of M2M_NTP_MAX_SERVER_NAME_LENGTH.
[in] useDHCP Explicity tell the WINC if it should use the NTP server provided by the DHCP server or not.
Warning
SNTP should be configured before the connection takes place. If SNTP is configured after the device connects to a network, the new configuration can take a minimum of 24h to be applied. However, it can take even longer since it is triggered by DHCP renewal. Currently there is also a known issue in which if the WINC obtains the NTP server from DHCP and then connects to a different network, it will still use the NTP from the previous network. Configuring a server name will overwrite the built-in default server until next reboot.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
Definition at line 1696 of file m2m_wifi.c.
{
    tstrM2MSNTPConfig strSNTPConfig;
    if(u8NTPServerNameLength > M2M_NTP_MAX_SERVER_NAME_LENGTH)
        return M2M_ERR_FAIL;
    m2m_memcpy((uint8*)strSNTPConfig.acNTPServer, pu8NTPServerName, u8NTPServerNameLength);
    strSNTPConfig.acNTPServer[u8NTPServerNameLength] = '\0';
    strSNTPConfig.enuUseDHCP = useDHCP;
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CONFIG_SNTP,
        (uint8*)&strSNTPConfig, sizeof(tstrM2MSNTPConfig), NULL, 0,0);
}
References tstrM2MSNTPConfig::acNTPServer, tstrM2MSNTPConfig::enuUseDHCP, hif_send(), M2M_ERR_FAIL, m2m_memcpy(), M2M_NTP_MAX_SERVER_NAME_LENGTH, M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CONFIG_SNTP, and NULL.
m2m_wifi_connect()
NMI_API sint8 m2m_wifi_connect (char * pcSsid, uint8 u8SsidLen, uint8 u8SecType, void * pvAuthInfo, uint16 u16Ch)
DEPRECATED in v19.6.1 - Kept only for legacy purposes.
Legacy asynchronous API to request connection to a specified access point.
Prior to a successful connection, the application must define the SSID of the AP, the security type, the authentication information parameters and the channel number to which the connection will be established.
The connection status is known when a response of M2M_WIFI_RESP_CON_STATE_CHANGED is received based on the states defined in tenuM2mConnState, successful connection is defined by M2M_WIFI_CONNECTED
The only difference between this function and m2m_wifi_default_connect, is the set of connection parameters. Connection using this function is expected to be made to a specific AP and to a specified channel.
Parameters
[in] pcSsid A buffer holding the SSID corresponding to the requested AP. SSID must not contain '\0'.
[in] u8SsidLen Length of the given SSID (not including the NULL termination). A length greater than the maximum defined SSID M2M_MAX_SSID_LEN will result in a negative error M2M_ERR_FAIL.
[in] u8SecType Wi-Fi security type security for the network. It can be one of the following types: -M2M_WIFI_SEC_OPEN -M2M_WIFI_SEC_WEP -M2M_WIFI_SEC_WPA_PSK -M2M_WIFI_SEC_802_1X A value outside these possible values will result in a negative return error M2M_ERR_FAIL.
[in] pvAuthInfo Authentication parameters required for completing the connection. Its type is based on the security type. If the authentication parameters are NULL or are greater than the maximum length of the authentication parameters length as defined by M2M_MAX_PSK_LEN a negative error will return M2M_ERR_FAIL(-12) indicating connection failure.
[in] u16Ch Wi-Fi channel number as defined in tenuM2mScanCh enumeration. Specifying a channel number greater than M2M_WIFI_CH_14 returns a negative error M2M_ERR_FAIL(-12), unless the value is M2M_WIFI_CH_ALL, since this indicates that the firmware should scan all channels to find the SSID specified in parameter pcSsid.
Failure to find the connection match will return a negative error M2M_DEFAULT_CONN_SCAN_MISMATCH.
Precondition
Prior to a successful connection request, the wi-fi driver must have been successfully initialized through the call of the m2m_wifi_init function
Warning
If there is a '\0' character within the first u8SsidLen characters, then this function will assume that the input u8SsidLen was incorrect, set length to strlen(pcSsid) and continue.
This function has been deprecated since v19.6.1 and will no longer be supported afterwards. The following should be used instead: m2m_wifi_connect_open m2m_wifi_connect_wep m2m_wifi_connect_psk m2m_wifi_connect_1x_mschap2 m2m_wifi_connect_1x_tls
Additionally:
This function must be called in station mode only.
Successful completion of this function does not guarantee success of the WIFI connection, and a negative return value indicates only locally-detected errors.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
tstr1xAuthCredentials tstrM2mWifiWepParams
Definition at line 1069 of file m2m_wifi.c.
{
    return m2m_wifi_connect_sc(pcSsid, u8SsidLen, u8SecType, pvAuthInfo,  u16Ch, 0);
}
References m2m_wifi_connect_sc().
Referenced by wifi_connect().
m2m_wifi_connect_1x_mschap2()
sint8 m2m_wifi_connect_1x_mschap2 (tenuCredStoreOption enuCredStoreOption, tstrNetworkId * pstrNetworkId, tstrAuth1xMschap2 * pstrAuth1xMschap2)
Asynchronous API to connect to an access point using WPA(2) Enterprise authentication with MS-CHAP-V2 credentials.
Asynchronous Wi-Fi connection function. An application calling this function will cause the firmware to attempt to connect to an access point matching the details in pstrNetworkId, with the Enterprise MS-CHAP-V2 credentials provided in pstrAuth1xMschap2. On successful connection, the connection details may be saved in WINC's flash, according to the option selected in enuCredStoreOption. Once connection has been attempted (whether successful or otherwise), a response event M2M_WIFI_RESP_CON_STATE_CHANGED will be sent to the callback function tpfAppWifiCb provided during initialization m2m_wifi_init.
Possible results indicated by the response event are:
M2M_WIFI_DISCONNECTED if the connection attempt failed.
M2M_WIFI_CONNECTED if the connection attempt succeeded.
Precondition
Prior to attempting connection, the WINC driver must have been initialized by calling the m2m_wifi_init function.
Warning
This function is handled in station mode only.
Parameters
[in] enuCredStoreOption Option to specify whether connection details (i.e. the contents of pstrNetworkId and pstrAuth1xMschap2) are stored in WINC's flash and, if so, whether they are encrypted before storing.
[in] pstrNetworkId Structure specifying SSID/BSSID and Wi-Fi channel.
[in] pstrAuth1xMschap2 Structure specifying the MS-CHAP-V2 credentials.
Returns
The function returns M2M_SUCCESS if the connect request has been successfully passed to the firmware and a negative value otherwise.
Definition at line 889 of file m2m_wifi.c.
{
    sint8 ret = M2M_ERR_INVALID_ARG;
    if (pstrAuth1xMschap2 != NULL)
    {
        if (pstrAuth1xMschap2->pu8Domain == NULL)
            pstrAuth1xMschap2->u16DomainLen = 0;
        if (
                (pstrAuth1xMschap2->pu8UserName != NULL)
            &&  (pstrAuth1xMschap2->pu8Password != NULL)
            &&  ((uint32)(pstrAuth1xMschap2->u16DomainLen) + pstrAuth1xMschap2->u16UserNameLen <= M2M_AUTH_1X_USER_LEN_MAX)
            &&  (pstrAuth1xMschap2->u16PasswordLen <= M2M_AUTH_1X_PASSWORD_LEN_MAX)
        )
        {
            tstrM2mWifiConnHdr  strConnHdr;
            uint16              u16AuthSize =   sizeof(tstrM2mWifi1xHdr) +
                                                pstrAuth1xMschap2->u16DomainLen +
                                                pstrAuth1xMschap2->u16UserNameLen +
                                                pstrAuth1xMschap2->u16PasswordLen;
            ret = m2m_wifi_connect_prepare_msg( enuCredStoreOption,
                                                M2M_WIFI_SEC_802_1X,
                                                u16AuthSize,
                                                pstrNetworkId,
                                                &strConnHdr);
            if (ret == M2M_SUCCESS)
            {
                tstrM2mWifi1xHdr    *pstr1xHdr = (tstrM2mWifi1xHdr*)malloc(u16AuthSize);
                if (pstr1xHdr != NULL)
                {
                    uint8   *pu8AuthPtr = pstr1xHdr->au81xAuthDetails;
                    m2m_memset((uint8*)pstr1xHdr, 0, u16AuthSize);
                    pstr1xHdr->u8Flags = M2M_802_1X_MSCHAP2_FLAG;
                    if (pstrAuth1xMschap2->bUnencryptedUserName == true)
                        pstr1xHdr->u8Flags |= M2M_802_1X_UNENCRYPTED_USERNAME_FLAG;
                    if (pstrAuth1xMschap2->bPrependDomain == true)
                        pstr1xHdr->u8Flags |= M2M_802_1X_PREPEND_DOMAIN_FLAG;
                    pstr1xHdr->u8HdrLength = sizeof(tstrM2mWifi1xHdr);
                    pstr1xHdr->u32TlsHsFlags = gu321xTlsHsFlags;
                    m2m_memcpy(pstr1xHdr->au8TlsSpecificRootNameSha1, gau81xRootSha1, sizeof(gau81xRootSha1));
                    pstr1xHdr->u8DomainLength = 0;
                    if(pstrAuth1xMschap2->pu8Domain != NULL)
                    {
                        pstr1xHdr->u8DomainLength = (uint8)(pstrAuth1xMschap2->u16DomainLen);
                        m2m_memcpy(pu8AuthPtr, pstrAuth1xMschap2->pu8Domain, pstr1xHdr->u8DomainLength);
                        pu8AuthPtr += pstr1xHdr->u8DomainLength;
                    }
                    pstr1xHdr->u8UserNameLength = (pstrAuth1xMschap2->u16UserNameLen);
                    m2m_memcpy(pu8AuthPtr, pstrAuth1xMschap2->pu8UserName, pstr1xHdr->u8UserNameLength);
                    pu8AuthPtr += pstr1xHdr->u8UserNameLength;
                    pstr1xHdr->u16PrivateKeyOffset = pu8AuthPtr - pstr1xHdr->au81xAuthDetails;
                    pstr1xHdr->u16PrivateKeyLength = pstrAuth1xMschap2->u16PasswordLen;
                    m2m_memcpy(pu8AuthPtr, pstrAuth1xMschap2->pu8Password, pstr1xHdr->u16PrivateKeyLength);
                    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CONN | M2M_REQ_DATA_PKT,
                                   (uint8 *)&strConnHdr, sizeof(tstrM2mWifiConnHdr),
                                   (uint8 *)pstr1xHdr, u16AuthSize,
                                   sizeof(tstrM2mWifiConnHdr));
                    free(pstr1xHdr);
                }
                else
                    ret = M2M_ERR_MEM_ALLOC;
            }
        }
    }
    return ret;
}
References tstrM2mWifi1xHdr::au81xAuthDetails, tstrAuth1xMschap2::bPrependDomain, tstrAuth1xMschap2::bUnencryptedUserName, gau81xRootSha1, gu321xTlsHsFlags, hif_send(), M2M_802_1X_MSCHAP2_FLAG, M2M_802_1X_PREPEND_DOMAIN_FLAG, M2M_802_1X_UNENCRYPTED_USERNAME_FLAG, M2M_AUTH_1X_PASSWORD_LEN_MAX, M2M_AUTH_1X_USER_LEN_MAX, M2M_ERR_INVALID_ARG, M2M_ERR_MEM_ALLOC, m2m_memcpy(), m2m_memset(), M2M_REQ_DATA_PKT, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, m2m_wifi_connect_prepare_msg(), M2M_WIFI_REQ_CONN, M2M_WIFI_SEC_802_1X, NULL, tstrAuth1xMschap2::pu8Domain, tstrAuth1xMschap2::pu8Password, tstrAuth1xMschap2::pu8UserName, tstrAuth1xMschap2::u16DomainLen, tstrAuth1xMschap2::u16PasswordLen, and tstrAuth1xMschap2::u16UserNameLen.
Referenced by m2m_wifi_connect_sc().
m2m_wifi_connect_1x_tls()
sint8 m2m_wifi_connect_1x_tls (tenuCredStoreOption enuCredStoreOption, tstrNetworkId * pstrNetworkId, tstrAuth1xTls * pstrAuth1xTls)
Asynchronous API to connect to an access point using WPA(2) Enterprise authentication with MS-CHAP-V2 credentials.
Asynchronous Wi-Fi connection function. An application calling this function will cause the firmware to attempt to connect to an access point matching the details in pstrNetworkId, with the Enterprise TLS credentials provided in pstrAuth1xTls. On successful connection, the connection details may be saved in WINC's flash, according to the option selected in enuCredStoreOption. Once connection has been attempted (whether successful or otherwise), a response event M2M_WIFI_RESP_CON_STATE_CHANGED will be sent to the callback function tpfAppWifiCb provided during initialization m2m_wifi_init.
Possible results indicated by the response event are:
M2M_WIFI_DISCONNECTED if the connection attempt failed.
M2M_WIFI_CONNECTED if the connection attempt succeeded.
Precondition
Prior to attempting connection, the WINC driver must have been initialized by calling the m2m_wifi_init function.
Warning
This function is handled in station mode only.
Parameters
[in] enuCredStoreOption Option to specify whether connection details (i.e. the contents of pstrNetworkId and pstrAuth1xTls) are stored in WINC's flash and, if so, whether they are encrypted before storing.
[in] pstrNetworkId Structure specifying SSID/BSSID and Wi-Fi channel.
[in] pstrAuth1xTls Structure specifying the EAP-TLS credentials.
Returns
The function returns M2M_SUCCESS if the connect request has been successfully passed to the firmware and a negative value otherwise.
Definition at line 967 of file m2m_wifi.c.
{
    sint8 ret = M2M_ERR_INVALID_ARG;
    if (pstrAuth1xTls != NULL)
    {
        if (pstrAuth1xTls->pu8Domain == NULL)
            pstrAuth1xTls->u16DomainLen = 0;
        if (
                (pstrAuth1xTls->pu8UserName != NULL)
            &&  (pstrAuth1xTls->pu8PrivateKey_Mod != NULL)
            &&  (pstrAuth1xTls->pu8PrivateKey_Exp != NULL)
            &&  (pstrAuth1xTls->pu8Certificate != NULL)
            &&  ((uint32)(pstrAuth1xTls->u16DomainLen) + pstrAuth1xTls->u16UserNameLen <= M2M_AUTH_1X_USER_LEN_MAX)
            &&  (pstrAuth1xTls->u16PrivateKeyLen <= M2M_AUTH_1X_PRIVATEKEY_LEN_MAX)
            &&  (pstrAuth1xTls->u16CertificateLen <= M2M_AUTH_1X_CERT_LEN_MAX)
        )
        {
            tstrM2mWifiConnHdr  strConnHdr;
            uint16              u16AuthSize =   sizeof(tstrM2mWifi1xHdr) +
                                                pstrAuth1xTls->u16DomainLen +
                                                pstrAuth1xTls->u16UserNameLen +
                                                (2 * pstrAuth1xTls->u16PrivateKeyLen) +
                                                pstrAuth1xTls->u16CertificateLen;
            ret = m2m_wifi_connect_prepare_msg( enuCredStoreOption,
                                                M2M_WIFI_SEC_802_1X,
                                                u16AuthSize,
                                                pstrNetworkId,
                                                &strConnHdr);
            if (ret == M2M_SUCCESS)
            {
                uint16              u16Payload1Size = u16AuthSize - pstrAuth1xTls->u16CertificateLen;
                tstrM2mWifi1xHdr    *pstr1xHdr = (tstrM2mWifi1xHdr*)malloc(u16Payload1Size);
                if (pstr1xHdr != NULL)
                {
                    tstrM2mWifiAuthInfoHdr strInfoHdr = {0};
                    uint8   *pu8AuthPtr = pstr1xHdr->au81xAuthDetails;
                    m2m_memset((uint8*)pstr1xHdr, 0, u16Payload1Size);
                    pstr1xHdr->u8Flags = M2M_802_1X_TLS_FLAG;
                    if (pstrAuth1xTls->bUnencryptedUserName == true)
                        pstr1xHdr->u8Flags |= M2M_802_1X_UNENCRYPTED_USERNAME_FLAG;
                    if (pstrAuth1xTls->bPrependDomain == true)
                        pstr1xHdr->u8Flags |= M2M_802_1X_PREPEND_DOMAIN_FLAG;
                    pstr1xHdr->u8HdrLength = sizeof(tstrM2mWifi1xHdr);
                    pstr1xHdr->u32TlsHsFlags = gu321xTlsHsFlags;
                    m2m_memcpy(pstr1xHdr->au8TlsSpecificRootNameSha1, gau81xRootSha1, sizeof(gau81xRootSha1));
                    pstr1xHdr->u8DomainLength = 0;
                    if(pstrAuth1xTls->pu8Domain != NULL)
                    {
                        pstr1xHdr->u8DomainLength = (uint8)(pstrAuth1xTls->u16DomainLen);
                        m2m_memcpy(pu8AuthPtr, pstrAuth1xTls->pu8Domain, pstr1xHdr->u8DomainLength);
                        pu8AuthPtr += pstr1xHdr->u8DomainLength;
                    }
                    pstr1xHdr->u8UserNameLength = (pstrAuth1xTls->u16UserNameLen);
                    m2m_memcpy(pu8AuthPtr, pstrAuth1xTls->pu8UserName, pstr1xHdr->u8UserNameLength);
                    pu8AuthPtr += pstr1xHdr->u8UserNameLength;
                    pstr1xHdr->u16PrivateKeyOffset = pu8AuthPtr - pstr1xHdr->au81xAuthDetails;
                    pstr1xHdr->u16PrivateKeyLength = pstrAuth1xTls->u16PrivateKeyLen;
                    m2m_memcpy(pu8AuthPtr, pstrAuth1xTls->pu8PrivateKey_Mod, pstr1xHdr->u16PrivateKeyLength);
                    pu8AuthPtr += pstr1xHdr->u16PrivateKeyLength;
                    m2m_memcpy(pu8AuthPtr, pstrAuth1xTls->pu8PrivateKey_Exp, pstr1xHdr->u16PrivateKeyLength);
                    pu8AuthPtr += pstr1xHdr->u16PrivateKeyLength;
                    pstr1xHdr->u16CertificateOffset = pu8AuthPtr - pstr1xHdr->au81xAuthDetails;
                    pstr1xHdr->u16CertificateLength = pstrAuth1xTls->u16CertificateLen;
                    strInfoHdr.u8Type = M2M_802_1X_TLS_CLIENT_CERTIFICATE;
                    strInfoHdr.u16InfoPos = pstr1xHdr->u16CertificateOffset;
                    strInfoHdr.u16InfoLen = pstr1xHdr->u16CertificateLength;
                    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_IND_CONN_PARAM | M2M_REQ_DATA_PKT,
                                   (uint8 *)&strInfoHdr, sizeof(tstrM2mWifiAuthInfoHdr),
                                   pstrAuth1xTls->pu8Certificate, pstrAuth1xTls->u16CertificateLen,
                                   sizeof(tstrM2mWifiAuthInfoHdr));
                    if(ret == M2M_SUCCESS)
                    {
                        ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CONN | M2M_REQ_DATA_PKT,
                                       (uint8 *)&strConnHdr, sizeof(tstrM2mWifiConnHdr),
                                       (uint8 *)pstr1xHdr, u16Payload1Size,
                                       sizeof(tstrM2mWifiConnHdr));
                    }
                    free(pstr1xHdr);
                }
                else
                    ret = M2M_ERR_MEM_ALLOC;
            }
        }
    }
    return ret;
}
References tstrM2mWifi1xHdr::au81xAuthDetails, tstrAuth1xTls::bPrependDomain, tstrAuth1xTls::bUnencryptedUserName, gau81xRootSha1, gu321xTlsHsFlags, hif_send(), M2M_802_1X_PREPEND_DOMAIN_FLAG, M2M_802_1X_TLS_CLIENT_CERTIFICATE, M2M_802_1X_TLS_FLAG, M2M_802_1X_UNENCRYPTED_USERNAME_FLAG, M2M_AUTH_1X_CERT_LEN_MAX, M2M_AUTH_1X_PRIVATEKEY_LEN_MAX, M2M_AUTH_1X_USER_LEN_MAX, M2M_ERR_INVALID_ARG, M2M_ERR_MEM_ALLOC, m2m_memcpy(), m2m_memset(), M2M_REQ_DATA_PKT, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, m2m_wifi_connect_prepare_msg(), M2M_WIFI_IND_CONN_PARAM, M2M_WIFI_REQ_CONN, M2M_WIFI_SEC_802_1X, NULL, tstrAuth1xTls::pu8Certificate, tstrAuth1xTls::pu8Domain, tstrAuth1xTls::pu8PrivateKey_Exp, tstrAuth1xTls::pu8PrivateKey_Mod, tstrAuth1xTls::pu8UserName, tstrAuth1xTls::u16CertificateLen, tstrAuth1xTls::u16DomainLen, tstrM2mWifiAuthInfoHdr::u16InfoLen, tstrM2mWifiAuthInfoHdr::u16InfoPos, tstrAuth1xTls::u16PrivateKeyLen, tstrAuth1xTls::u16UserNameLen, and tstrM2mWifiAuthInfoHdr::u8Type.
m2m_wifi_connect_open()
sint8 m2m_wifi_connect_open (tenuCredStoreOption enuCredStoreOption, tstrNetworkId * pstrNetworkId)
Asynchronous API to connect to an access point using open authentication.
Asynchronous Wi-Fi connection function. An application calling this function will cause the firmware to attempt to connect to an access point matching the details in pstrNetworkId, with open authentication. On successful connection, the connection details may be saved in WINC's flash, according to the option selected in enuCredStoreOption. Once connection has been attempted (whether successful or otherwise), a response event M2M_WIFI_RESP_CON_STATE_CHANGED will be sent to the callback function tpfAppWifiCb provided during initialization m2m_wifi_init.
Possible results indicated by the response event are:
M2M_WIFI_DISCONNECTED if the connection attempt failed.
M2M_WIFI_CONNECTED if the connection attempt succeeded.
Precondition
Prior to attempting connection, the WINC driver must have been initialized by calling the m2m_wifi_init function.
Warning
This function is handled in station mode only.
Parameters
[in] enuCredStoreOption Option to specify whether connection details (i.e. the contents of pstrNetworkId) are stored in WINC's flash and, if so, whether they are encrypted before storing.
[in] pstrNetworkId Structure specifying SSID/BSSID and Wi-Fi channel.
Returns
The function returns M2M_SUCCESS if the connect request has been successfully passed to the firmware and a negative value otherwise.
Definition at line 641 of file m2m_wifi.c.
    {
    sint8               ret = M2M_ERR_INVALID_ARG;
    tstrM2mWifiConnHdr  strConnHdr;
    ret = m2m_wifi_connect_prepare_msg(enuCredStoreOption, M2M_WIFI_SEC_OPEN, 0, pstrNetworkId, &strConnHdr);
    if (ret == M2M_SUCCESS)
        {
        ret = hif_send( M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CONN,
                        (uint8*)&strConnHdr, sizeof(strConnHdr),
                        NULL, 0, 0);
        }
    return ret;
    }
References hif_send(), M2M_ERR_INVALID_ARG, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, m2m_wifi_connect_prepare_msg(), M2M_WIFI_REQ_CONN, M2M_WIFI_SEC_OPEN, and NULL.
Referenced by m2m_wifi_connect_sc().
m2m_wifi_connect_psk()
sint8 m2m_wifi_connect_psk (tenuCredStoreOption enuCredStoreOption, tstrNetworkId * pstrNetworkId, tstrAuthPsk * pstrAuthPsk)
Asynchronous API to connect to an access point using WPA(2) PSK authentication.
Asynchronous Wi-Fi connection function. An application calling this function will cause the firmware to attempt to connect to an access point matching the details in pstrNetworkId, with the PSK passphrase provided in pstrAuthPsk. On successful connection, the connection details may be saved in WINC's flash, according to the option selected in enuCredStoreOption. Once connection has been attempted (whether successful or otherwise), a response event M2M_WIFI_RESP_CON_STATE_CHANGED will be sent to the callback function tpfAppWifiCb provided during initialization m2m_wifi_init.
Possible results indicated by the response event are:
M2M_WIFI_DISCONNECTED if the connection attempt failed.
M2M_WIFI_CONNECTED if the connection attempt succeeded.
Precondition
Prior to attempting connection, the WINC driver must have been initialized by calling the m2m_wifi_init function.
Warning
This function is handled in station mode only.
Parameters
[in] enuCredStoreOption Option to specify whether connection details (i.e. the contents of pstrNetworkId and pstrAuthPsk) are stored in WINC's flash and, if so, whether they are encrypted before storing.
[in] pstrNetworkId Structure specifying SSID/BSSID and Wi-Fi channel.
[in] pstrAuthPsk Structure specifying the Passphrase/PSK.
Returns
The function returns M2M_SUCCESS if the connect request has been successfully passed to the firmware and a negative value otherwise.
Definition at line 702 of file m2m_wifi.c.
{
    sint8   ret = M2M_ERR_INVALID_ARG;
    if (pstrAuthPsk != NULL)
    {
        tstrM2mWifiConnHdr  strConnHdr;
        ret = m2m_wifi_connect_prepare_msg( enuCredStoreOption,
                                            M2M_WIFI_SEC_WPA_PSK,
                                            sizeof(tstrM2mWifiPsk),
                                            pstrNetworkId,
                                            &strConnHdr);
        if(ret == M2M_SUCCESS)
        {
            tstrM2mWifiPsk  *pstrPsk = (tstrM2mWifiPsk *)malloc(sizeof(tstrM2mWifiPsk));
            if(pstrPsk != NULL)
            {
                m2m_memset((uint8 *)pstrPsk, 0, sizeof(tstrM2mWifiPsk));
                if(pstrAuthPsk->pu8Psk != NULL)
                {
                    if(pstrAuthPsk->pu8Passphrase != NULL)
                        ret = M2M_ERR_INVALID_ARG;
                    else
                    {
                        pstrPsk->u8PassphraseLen = M2M_MAX_PSK_LEN-1;
                        /* Use hexstr_2_bytes to verify pu8Psk input. */
                        if(M2M_SUCCESS != hexstr_2_bytes(pstrPsk->au8Passphrase, pstrAuthPsk->pu8Psk, pstrPsk->u8PassphraseLen/2))
                            ret = M2M_ERR_INVALID_ARG;
                        m2m_memcpy(pstrPsk->au8Passphrase, pstrAuthPsk->pu8Psk, pstrPsk->u8PassphraseLen);
                    }
                }
                else if(pstrAuthPsk->pu8Passphrase != NULL)
                {
                    if(pstrAuthPsk->u8PassphraseLen > M2M_MAX_PSK_LEN-1)
                        ret = M2M_ERR_INVALID_ARG;
                    else
                    {
                        pstrPsk->u8PassphraseLen = pstrAuthPsk->u8PassphraseLen;
                        m2m_memcpy(pstrPsk->au8Passphrase, pstrAuthPsk->pu8Passphrase, pstrPsk->u8PassphraseLen);
                    }
                }
                else
                    ret = M2M_ERR_INVALID_ARG;
                if(ret == M2M_SUCCESS)
                {
                    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CONN | M2M_REQ_DATA_PKT,
                                   (uint8 *)&strConnHdr, sizeof(tstrM2mWifiConnHdr),
                                   (uint8 *)pstrPsk, sizeof(tstrM2mWifiPsk), sizeof(tstrM2mWifiConnHdr));
                }
                free(pstrPsk);
            }
            else
                ret = M2M_ERR_MEM_ALLOC;
        }
    }
    return ret;
}
References hexstr_2_bytes(), hif_send(), M2M_ERR_INVALID_ARG, M2M_ERR_MEM_ALLOC, M2M_MAX_PSK_LEN, m2m_memcpy(), m2m_memset(), M2M_REQ_DATA_PKT, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, m2m_wifi_connect_prepare_msg(), M2M_WIFI_REQ_CONN, M2M_WIFI_SEC_WPA_PSK, NULL, tstrAuthPsk::pu8Passphrase, tstrAuthPsk::pu8Psk, and tstrAuthPsk::u8PassphraseLen.
Referenced by m2m_wifi_connect_sc().
m2m_wifi_connect_sc()
NMI_API sint8 m2m_wifi_connect_sc (char * pcSsid, uint8 u8SsidLen, uint8 u8SecType, void * pvAuthInfo, uint16 u16Ch, uint8 u8NoSaveCred)
DEPRECATED in v19.6.1 - Kept only for legacy purposes.
Legacy asynchronous API to request connection to a specific AP with the option to save credentials in Flash.
Prior to a successful connection, the application developers must know the SSID of the AP, the security type, the authentication information parameters and the channel number to which the connection will be established.
The connection status is known when a response of M2M_WIFI_RESP_CON_STATE_CHANGED is received based on the states defined in tenuM2mConnState, successful connection is defined by M2M_WIFI_CONNECTED The only difference between this function and m2m_wifi_connect, is the option to save the access point info (SSID, password...etc) or not. Connection using this function is expected to be made to a specific AP and to a specified channel.
Parameters
[in] pcSsid A buffer holding the SSID corresponding to the requested AP. SSID must not contain '\0'.
[in] u8SsidLen Length of the given SSID (not including the NULL termination). A length greater than the maximum defined SSID M2M_MAX_SSID_LEN will result in a negative error M2M_ERR_FAIL.
[in] u8SecType Wi-Fi security type security for the network see tenuM2mSecType. It can be one of the following types: -M2M_WIFI_SEC_OPEN -M2M_WIFI_SEC_WEP -M2M_WIFI_SEC_WPA_PSK -M2M_WIFI_SEC_802_1X A value outside these possible values will result in a negative return error M2M_ERR_FAIL.
[in] pvAuthInfo Authentication parameters required for completing the connection. Its type is based on the security type. If the authentication parameters are NULL or are greater than the maximum length of the authentication parameters length as defined by M2M_MAX_PSK_LEN a negative error will return M2M_ERR_FAIL(-12) indicating connection failure.
[in] u16Ch Wi-Fi channel number as defined in tenuM2mScanCh enumeration. Specification of a channel number greater than M2M_WIFI_CH_14 returns a negative error M2M_ERR_FAIL(-12) unless the value is M2M_WIFI_CH_ALL. A channel number of M2M_WIFI_CH_ALL indicates that the firmware should scan all channels to find the SSID specified in parameter pcSsid.
Failure to find the connection match will return a negative error M2M_DEFAULT_CONN_SCAN_MISMATCH.
Parameters
[in] u8NoSaveCred Option to store the access point SSID and password into the WINC flash memory or not.
Precondition
Prior to a successful connection request, the wi-fi driver must have been successfully initialized through the call of the m2m_wifi_init function.
Warning
If there is a '\0' character within the first u8SsidLen characters, then this function will assume that the input u8SsidLen was incorrect, set length to strlen(pcSsid) and continue.
This function has been deprecated since v19.6.1 and will no longer be supported afterwards. The following should be used instead: m2m_wifi_connect_open m2m_wifi_connect_wep m2m_wifi_connect_psk m2m_wifi_connect_1x_mschap2 m2m_wifi_connect_1x_tls
Additionally:
This function must be called in station mode only.
Successful completion of this function does not guarantee success of the WIFI connection, and a negative return value indicates only locally-detected errors.
See also
tenuM2mSecType tstr1xAuthCredentials tstrM2mWifiWepParams
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
Definition at line 1074 of file m2m_wifi.c.
{
    sint8               s8Ret              = M2M_ERR_INVALID_ARG;
    tstrNetworkId       strNetworkId       = {NULL, (uint8*)pcSsid, u8SsidLen, (tenuM2mScanCh)u16Ch};
    tenuCredStoreOption enuCredStoreOption = u8NoSaveCred ? WIFI_CRED_DONTSAVE : WIFI_CRED_SAVE_ENCRYPTED;
    /* This API does not support SSIDs which contain '\0'. If there is a '\0' character within the
     * first u8SsidLen characters, then assume that the input u8SsidLen was incorrect - set length
     * to strlen(pcSsid) and continue. This is to avoid a change from the behaviour of previously
     * released drivers. */
    if (u8SsidLen < M2M_MAX_SSID_LEN)
    {
        while (u8SsidLen--)
            if (strNetworkId.pu8Ssid[u8SsidLen] == 0){
                strNetworkId.u8SsidLen = u8SsidLen;}
    }
    switch ((tenuM2mSecType)u8SecType)
    {
        case M2M_WIFI_SEC_OPEN:
        s8Ret = m2m_wifi_connect_open(enuCredStoreOption, &strNetworkId);
        break;
        case M2M_WIFI_SEC_WPA_PSK:
        if (pvAuthInfo != NULL)
        {
            tstrAuthPsk strAuthPsk = {NULL, NULL, 0};
            uint16      len        = m2m_strlen((uint8*)pvAuthInfo);
            if (len == M2M_MAX_PSK_LEN-1)
            {
                strAuthPsk.pu8Psk = (uint8*)pvAuthInfo;
            }
            else
            {
                strAuthPsk.pu8Passphrase = (uint8*)pvAuthInfo;
                strAuthPsk.u8PassphraseLen = len;
            }
            s8Ret = m2m_wifi_connect_psk(enuCredStoreOption, &strNetworkId, &strAuthPsk);
        }
        break;
        case M2M_WIFI_SEC_WEP:
        if (pvAuthInfo != NULL)
        {
            tstrM2mWifiWepParams    *pstrWepParams = (tstrM2mWifiWepParams*)pvAuthInfo;
            tstrAuthWep             strAuthWep = {pstrWepParams->au8WepKey, pstrWepParams->u8KeySz-1, pstrWepParams->u8KeyIndx};
            s8Ret = m2m_wifi_connect_wep(enuCredStoreOption, &strNetworkId, &strAuthWep);
        }
        break;
        case M2M_WIFI_SEC_802_1X:
        if (pvAuthInfo != NULL)
        {
            tstr1xAuthCredentials   *pstr1xParams = (tstr1xAuthCredentials*)pvAuthInfo;
            tstrAuth1xMschap2       strAuth1xMschap2 = {NULL,
                pstr1xParams->au8UserName,
                pstr1xParams->au8Passwd,
                0,
                                                        m2m_strlen(pstr1xParams->au8UserName),
                                                        m2m_strlen(pstr1xParams->au8Passwd),
                                                        false};
            s8Ret = m2m_wifi_connect_1x_mschap2(enuCredStoreOption, &strNetworkId, &strAuth1xMschap2);
        }
        break;
        default:
        break;
    }
    return s8Ret;
}
References tstr1xAuthCredentials::au8Passwd, tstr1xAuthCredentials::au8UserName, tstrM2mWifiWepParams::au8WepKey, M2M_ERR_INVALID_ARG, M2M_MAX_PSK_LEN, M2M_MAX_SSID_LEN, m2m_strlen(), m2m_wifi_connect_1x_mschap2(), m2m_wifi_connect_open(), m2m_wifi_connect_psk(), m2m_wifi_connect_wep(), M2M_WIFI_SEC_802_1X, M2M_WIFI_SEC_OPEN, M2M_WIFI_SEC_WEP, M2M_WIFI_SEC_WPA_PSK, NULL, tstrAuthPsk::pu8Passphrase, tstrAuthPsk::pu8Psk, tstrNetworkId::pu8Ssid, tstrM2mWifiWepParams::u8KeyIndx, tstrM2mWifiWepParams::u8KeySz, tstrAuthPsk::u8PassphraseLen, tstrNetworkId::u8SsidLen, WIFI_CRED_DONTSAVE, and WIFI_CRED_SAVE_ENCRYPTED.
Referenced by m2m_wifi_connect().
m2m_wifi_connect_wep()
sint8 m2m_wifi_connect_wep (tenuCredStoreOption enuCredStoreOption, tstrNetworkId * pstrNetworkId, tstrAuthWep * pstrAuthWep)
Asynchronous API to connect to an access point using WEP authentication.
Asynchronous Wi-Fi connection function. An application calling this function will cause the firmware to attempt to connect to an access point matching the details in pstrNetworkId, with the WEP key provided in pstrAuthWep. On successful connection, the connection details may be saved in WINC's flash, according to the option selected in enuCredStoreOption. Once connection has been attempted (whether successful or otherwise), a response event M2M_WIFI_RESP_CON_STATE_CHANGED will be sent to the callback function tpfAppWifiCb provided during initialization m2m_wifi_init.
Possible results indicated by the response event are:
M2M_WIFI_DISCONNECTED if the connection attempt failed.
M2M_WIFI_CONNECTED if the connection attempt succeeded.
Precondition
Prior to attempting connection, the WINC driver must have been initialized by calling the m2m_wifi_init function.
Warning
This function is handled in station mode only.
Parameters
[in] enuCredStoreOption Option to specify whether connection details (i.e. the contents of pstrNetworkId and pstrAuthWep) are stored in WINC's flash and, if so, whether they are encrypted before storing.
[in] pstrNetworkId Structure specifying SSID/BSSID and Wi-Fi channel.
[in] pstrAuthWep Structure specifying the WEP key.
Returns
The function returns M2M_SUCCESS if the connect request has been successfully passed to the firmware and a negative value otherwise.
Definition at line 659 of file m2m_wifi.c.
{
    sint8   ret = M2M_ERR_INVALID_ARG;
    if (
            (pstrAuthWep != NULL) && (pstrAuthWep->pu8WepKey != NULL)
        &&  (pstrAuthWep->u8KeyIndx > 0) && (pstrAuthWep->u8KeyIndx <= WEP_KEY_MAX_INDEX)
        &&  ((pstrAuthWep->u8KeySz == WEP_104_KEY_STRING_SIZE) || (pstrAuthWep->u8KeySz == WEP_40_KEY_STRING_SIZE))
    )
    {
        tstrM2mWifiConnHdr  strConnHdr;
        ret = m2m_wifi_connect_prepare_msg( enuCredStoreOption,
                                            M2M_WIFI_SEC_WEP,
                                            sizeof(tstrM2mWifiWep),
                                            pstrNetworkId,
                                            &strConnHdr);
        if (ret == M2M_SUCCESS)
        {
            tstrM2mWifiWep  *pstrWep = (tstrM2mWifiWep*)malloc(sizeof(tstrM2mWifiWep));
            if (pstrWep != NULL)
        {
                pstrWep->u8KeyIndex = pstrAuthWep->u8KeyIndx - 1;
                pstrWep->u8KeyLen = pstrAuthWep->u8KeySz/2;
                hexstr_2_bytes(pstrWep->au8WepKey, (pstrAuthWep->pu8WepKey), pstrWep->u8KeyLen);
                ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CONN | M2M_REQ_DATA_PKT,
                               (uint8 *)&strConnHdr, sizeof(tstrM2mWifiConnHdr),
                               (uint8 *)pstrWep, sizeof(tstrM2mWifiWep), sizeof(tstrM2mWifiConnHdr));
                free(pstrWep);
            }
            else
                ret = M2M_ERR_MEM_ALLOC;
        }
    }
    return ret;
}
References tstrM2mWifiWep::au8WepKey, hexstr_2_bytes(), hif_send(), M2M_ERR_INVALID_ARG, M2M_ERR_MEM_ALLOC, M2M_REQ_DATA_PKT, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, m2m_wifi_connect_prepare_msg(), M2M_WIFI_REQ_CONN, M2M_WIFI_SEC_WEP, NULL, tstrAuthWep::pu8WepKey, tstrM2mWifiWep::u8KeyIndex, tstrAuthWep::u8KeyIndx, tstrM2mWifiWep::u8KeyLen, tstrAuthWep::u8KeySz, WEP_104_KEY_STRING_SIZE, WEP_40_KEY_STRING_SIZE, and WEP_KEY_MAX_INDEX.
Referenced by m2m_wifi_connect_sc().
m2m_wifi_default_connect()
NMI_API sint8 m2m_wifi_default_connect (void)
Asynchronous API that attempts to reconnect to the last-associated access point.
Asynchronous Wi-Fi connection function. An application calling this function will cause the firmware to correspondingly connect to the last successfully connected AP from the cached connections.
A failure to connect will result in a response of M2M_WIFI_RESP_DEFAULT_CONNECT indicating the connection error as defined in the structure tstrM2MDefaultConnResp.
Possible errors are: The connection list is empty M2M_DEFAULT_CONN_EMPTY_LIST or a mismatch for the saved AP name M2M_DEFAULT_CONN_SCAN_MISMATCH.
Precondition
Prior to connecting, the WINC driver should have been successfully initialized by calling the m2m_wifi_init function.
Warning
This function must be called in station mode only. It is important to note that successful completion of a call to m2m_wifi_default_connect() does not guarantee success of the WIFI connection; a negative return value indicates only locally-detected errors.
See also
m2m_wifi_connect
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
Definition at line 563 of file m2m_wifi.c.
{
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_DEFAULT_CONNECT, NULL, 0,NULL, 0,0);
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_DEFAULT_CONNECT, and NULL.
m2m_wifi_deinit()
NMI_API sint8 m2m_wifi_deinit (void * arg)
De-initialize the WINC driver and host interface.
Synchronous de-initialization function for the WINC driver. De-initializes the host interface and frees any resources used by the M2M_WIFI layer. This function must be called in the application closing phase to ensure that all resources have been correctly released. No arguments are expected to be passed in.
Parameters
[in] arg Opaque argument, not used in current implementation. Application should use null.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC, and a negative value otherwise.
Note
This function must be called at the de-initialization stage of the application. Generally this function should be the last function before switching off the chip and it should be followed only by nm_bsp_deinit function call. Every function call of m2m_wifi_init should be matched with a call to m2m_wifi_deinit.
See also
nm_bsp_deinit m2m_wifi_init m2m_wifi_init_hold m2m_wifi_download_mode
Definition at line 525 of file m2m_wifi.c.
{
    gu8WifiState = WIFI_STATE_DEINIT;
    hif_deinit(NULL);
    nm_drv_deinit(NULL);
    return M2M_SUCCESS;
}
References gu8WifiState, hif_deinit(), M2M_SUCCESS, nm_drv_deinit(), NULL, and WIFI_STATE_DEINIT.
Referenced by m2m_wifi_reinit_hold().
m2m_wifi_delete_sc()
sint8 m2m_wifi_delete_sc (char * pcSsid, uint8 u8SsidLen)
Asynchronous API that deletes connection credentials (PSK, WEP key, 802.1X password) from WINC flash. Either deletes all credentials, or for a specific SSID.
Causes WINC to delete connection credentials. If the parameter is NULL, then WINC will delete all credentials from flash. Otherwise WINC will only delete credentials for matching SSID. Callback will report the status of the operation (success or not).
Parameters
[in] pcSsid SSID to match on when deleting credentials. SSID must not contain '\0'. NULL is a valid argument here, in which case all credentials are deleted.
[in] u8SsidLen Length of SSID provided in pcSsid. Must be less than M2M_MAX_SSID_LEN. This parameter is ignored if pcSsid is NULL.
Precondition
Prior to deleting credentials, the WINC driver should have been successfully initialized by calling the m2m_wifi_init function.
Warning
The option to delete for a specific SSID is currently not supported; all credentials are deleted regardless of the input parameters.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
Definition at line 545 of file m2m_wifi.c.
{
    tstrM2mWifiApId strApId;
    m2m_memset((uint8*)&strApId, 0, sizeof(strApId));
#if 0
    if (pcSsid != NULL)
    {
        if (u8SsidLen >= M2M_MAX_SSID_LEN)
            return M2M_ERR_INVALID_ARG;
        strApId.au8SSID[0] = u8SsidLen;
        m2m_memcpy(&strApId.au8SSID[1], (uint8*)pcSsid, u8SsidLen);
    }
    else
#endif
        strApId.au8SSID[0] = 0xFF;  // Special value used to cause fw to delete all entries.
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQRSP_DELETE_APID, (uint8*)&strApId, sizeof(tstrM2mWifiApId), NULL, 0, 0);
}
References tstrM2mWifiApId::au8SSID, hif_send(), M2M_ERR_INVALID_ARG, M2M_MAX_SSID_LEN, m2m_memcpy(), m2m_memset(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQRSP_DELETE_APID, and NULL.
m2m_wifi_disable_ap()
NMI_API sint8 m2m_wifi_disable_ap (void)
Synchronous API to disable access point mode on the WINC IC.
Must be called only when the AP is enabled through the m2m_wifi_enable_ap function. Otherwise the call to this function will not be useful.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
m2m_wifi_enable_ap
Definition at line 1477 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_DISABLE_AP, NULL, 0, NULL, 0, 0);
    return ret;
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_DISABLE_AP, and NULL.
m2m_wifi_disable_roaming()
sint8 m2m_wifi_disable_roaming (void)
Disable WiFi STA roaming.
Precondition
Must be called after the initialization.
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
See also
m2m_wifi_init
Definition at line 2062 of file m2m_wifi.c.
{
    tstrM2mWiFiRoaming  strWiFiRoaming;
    strWiFiRoaming.u8EnableRoaming = 0;
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_ROAMING, (uint8 *) &strWiFiRoaming, sizeof(tstrM2mWiFiRoaming), NULL, 0,0);
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_ROAMING, NULL, and tstrM2mWiFiRoaming::u8EnableRoaming.
m2m_wifi_disconnect()
NMI_API sint8 m2m_wifi_disconnect (void)
Synchronous API to request disconnection from a network.
Request a Wi-Fi disconnect from the currently connected AP. After the disconnect is complete the driver should receive a response of M2M_WIFI_RESP_CON_STATE_CHANGED based on the states defined in tenuM2mConnState, successful disconnection is defined by M2M_WIFI_DISCONNECTED .
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
Precondition
Disconnection request must be made to a successfully connected AP. If the WINC is not in the connected state, a call to this function will hold insignificant.
Warning
This function must be called in station mode only.
See also
m2m_wifi_connect_open m2m_wifi_connect_wep m2m_wifi_connect_psk m2m_wifi_connect_1x_mschap2 m2m_wifi_connect_1x_tls m2m_wifi_default_connect
Definition at line 1144 of file m2m_wifi.c.
{
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_DISCONNECT, NULL, 0, NULL, 0,0);
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_DISCONNECT, and NULL.
m2m_wifi_download_mode()
NMI_API sint8 m2m_wifi_download_mode (void)
Prepares the WINC board before downloading any data (Firmware, Certificates, etc).
This function should be called before attempting to download any data to the WINC board. Performs the appropriate WINC driver initialization, this includes bus initialization, interrupt enabling and it halts the chip to allow for the firmware downloads. Firmware can be downloaded through a number of interfaces, UART, I2C and SPI.
Precondition
Prior to call m2m_wifi_download_mode, the Application should ensure that the wifi is not initialized. This can be done by calling m2m_wifi_get_state and in case the wifi state differs from WIFI_STATE_DEINIT, a m2m_wifi_deinit needs to be issued.
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 295 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    /* Apply device specific initialization. */
    ret = nm_drv_init_download_mode();
    if(ret != M2M_SUCCESS)  goto _EXIT0;
    enable_interrupts();
    gu8WifiState = WIFI_STATE_INIT;
_EXIT0:
    return ret;
}
References enable_interrupts(), gu8WifiState, M2M_SUCCESS, nm_drv_init_download_mode(), and WIFI_STATE_INIT.
m2m_wifi_enable_ap()
NMI_API sint8 m2m_wifi_enable_ap (CONST tstrM2MAPConfig * pstrM2MAPConfig)
Asynchronous API to enable access point (AKA "hot-spot") mode on the WINC IC.
The WINC IC supports the ability to operate as an access point with the following limitations:
Only 1 station may be associated at any given time.
Open system and WEP are the only security suites supported.
Parameters
[in] pstrM2MAPConfig A structure holding the AP configurations.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
Precondition
A Wi-Fi notification callback of type tpfAppWifiCb MUST be implemented and registered at initialization. Registering the callback is done through passing it to the m2m_wifi_init.
The event M2M_WIFI_REQ_DHCP_CONF must be handled in the callback.
The m2m_wifi_handle_events MUST be called to receive the responses in the callback.
Warning
This function is not allowed in STA mode.
See also
tpfAppWifiCb tenuM2mSecType m2m_wifi_init M2M_WIFI_REQ_DHCP_CONF tstrM2mWifiStateChanged tstrM2MAPConfig
Example
The code snippet demonstrates how the AP mode is enabled after the driver is initialized in the application's main function and the handling of the event M2M_WIFI_REQ_DHCP_CONF, to indicate successful connection.
#include "m2m_wifi.h"
#include "m2m_types.h"
void wifi_event_cb(uint8 u8WiFiEvent, void * pvMsg)
{
    switch(u8WiFiEvent)
    {
    case M2M_WIFI_REQ_DHCP_CONF:
        {
            uint8   *pu8IPAddress = (uint8*)pvMsg;
            printf("Associated STA has IP Address \"%u.%u.%u.%u\"\n",pu8IPAddress[0],pu8IPAddress[1],pu8IPAddress[2],pu8IPAddress[3]);
        }
        break;
    default:
        break;
    }
}
int main()
{
    tstrWifiInitParam   param;
    param.pfAppWifiCb   = wifi_event_cb;
    if(!m2m_wifi_init(&param))
    {
        tstrM2MAPConfig     apConfig;
        strcpy(apConfig.au8SSID, "WINC_SSID");
        apConfig.u8ListenChannel    = 1;
        apConfig.u8SecType          = M2M_WIFI_SEC_OPEN;
        apConfig.u8SsidHide         = 0;
        // IP Address
        apConfig.au8DHCPServerIP[0] = 192;
        apConfig.au8DHCPServerIP[1] = 168;
        apConfig.au8DHCPServerIP[2] = 1;
        apConfig.au8DHCPServerIP[3] = 1;
        // Trigger AP
        m2m_wifi_enable_ap(&apConfig);
        while(1)
        {
            m2m_wifi_handle_events(NULL);
        }
    }
}
Definition at line 1445 of file m2m_wifi.c.
{
    tstrM2MAPModeConfig strM2MAPModeConfig;
    m2m_memcpy((uint8 *)&strM2MAPModeConfig.strApConfig, (uint8 *)pstrM2MAPConfig, sizeof(tstrM2MAPConfig));
    m2m_memcpy(strM2MAPModeConfig.strApConfigExt.au8DefRouterIP, (uint8 *)pstrM2MAPConfig->au8DHCPServerIP, 4);
    m2m_memcpy(strM2MAPModeConfig.strApConfigExt.au8DNSServerIP, (uint8 *)pstrM2MAPConfig->au8DHCPServerIP, 4);
    strM2MAPModeConfig.strApConfigExt.au8SubnetMask[0] = 0;
    return m2m_wifi_enable_ap_ext(&strM2MAPModeConfig);
}
References tstrM2MAPConfigExt::au8DefRouterIP, tstrM2MAPConfigExt::au8DNSServerIP, tstrM2MAPConfigExt::au8SubnetMask, m2m_memcpy(), m2m_wifi_enable_ap_ext(), tstrM2MAPModeConfig::strApConfig, and tstrM2MAPModeConfig::strApConfigExt.
m2m_wifi_enable_ap_ext()
NMI_API sint8 m2m_wifi_enable_ap_ext (CONST tstrM2MAPModeConfig * pstrM2MAPModeConfig)
Asynchronous API to enable access point (AKA "hot-spot") mode on the WINC IC with extended options.
The WINC IC supports the ability to operate as an access point with the following limitations:
Only 1 station may be associated at any given time.
Open system and WEP are the only security suites supported.
Parameters
[in] pstrM2MAPModeConfig A structure holding the AP configurations.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
Precondition
A Wi-Fi notification callback of type tpfAppWifiCb MUST be implemented and registered at initialization. Registering the callback is done through passing it to the m2m_wifi_init.
The event M2M_WIFI_REQ_DHCP_CONF must be handled in the callback.
The m2m_wifi_handle_events MUST be called to receive the responses in the callback.
Warning
This function is not allowed in STA mode.
See also
tpfAppWifiCb tenuM2mSecType m2m_wifi_init M2M_WIFI_REQ_DHCP_CONF tstrM2mWifiStateChanged tstrM2MAPModeConfig tstrM2MAPConfigExt
Example
The code snippet demonstrates how the AP mode is enabled after the driver is initialized in the application's main function and the handling of the event M2M_WIFI_REQ_DHCP_CONF, to indicate successful connection.
#include "m2m_wifi.h"
#include "m2m_types.h"
void wifi_event_cb(uint8 u8WiFiEvent, void * pvMsg)
{
    switch(u8WiFiEvent)
    {
    case M2M_WIFI_REQ_DHCP_CONF:
        {
            uint8   *pu8IPAddress = (uint8*)pvMsg;
            printf("Associated STA has IP Address \"%u.%u.%u.%u\"\n",pu8IPAddress[0],pu8IPAddress[1],pu8IPAddress[2],pu8IPAddress[3]);
        }
        break;
    default:
        break;
    }
}
int main()
{
    tstrWifiInitParam   param;
    param.pfAppWifiCb   = wifi_event_cb;
    if(!m2m_wifi_init(&param))
    {
        tstrM2MAPModeConfig     apModeConfig;
        strcpy(apConfig.strApConfig.au8SSID, "WINC_SSID");
        apModeConfig.strApConfig.u8ListenChannel    = 1;
        apModeConfig.strApConfig.u8SecType          = M2M_WIFI_SEC_OPEN;
        apModeConfig.strApConfig.u8SsidHide         = 0;
        // IP Address
        apModeConfig.strApConfig.au8DHCPServerIP[0] = 192;
        apModeConfig.strApConfig.au8DHCPServerIP[1] = 168;
        apModeConfig.strApConfig.au8DHCPServerIP[2] = 1;
        apModeConfig.strApConfig.au8DHCPServerIP[3] = 1;
        // Default router IP
        m2m_memcpy(apModeConfig.strApConfigExt.au8DefRouterIP, apModeConfig.strApConfig.au8DHCPServerIP, 4);
        // DNS Server IP
        m2m_memcpy(apModeConfig.strApConfigExt.au8DNSServerIP, apModeConfig.strApConfig.au8DHCPServerIP, 4);
        // Subnet mask
        apModeConfig.strApConfigExt.au8SubnetMask[0]    = 255;
        apModeConfig.strApConfigExt.au8SubnetMask[1]    = 255;
        apModeConfig.strApConfigExt.au8SubnetMask[2]    = 255;
        apModeConfig.strApConfigExt.au8SubnetMask[3]    = 0;
        // Trigger AP
        m2m_wifi_enable_ap_ext(&apModeConfig);
        while(1)
        {
            m2m_wifi_handle_events(NULL);
        }
    }
}
Definition at line 1458 of file m2m_wifi.c.
{
    sint8 ret = M2M_ERR_FAIL;
    if(M2M_SUCCESS == m2m_validate_ap_parameters(pstrM2MAPModeConfig))
    {
        ret = hif_send(M2M_REQ_GROUP_WIFI, (M2M_REQ_DATA_PKT|M2M_WIFI_REQ_ENABLE_AP), NULL, 0, (uint8 *)pstrM2MAPModeConfig, sizeof(tstrM2MAPModeConfig), 0);
    }
    return ret;
}
References hif_send(), M2M_ERR_FAIL, M2M_REQ_DATA_PKT, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, m2m_validate_ap_parameters(), M2M_WIFI_REQ_ENABLE_AP, and NULL.
Referenced by m2m_wifi_enable_ap().
m2m_wifi_enable_dhcp()
NMI_API sint8 m2m_wifi_enable_dhcp (uint8 u8DhcpEn)
Enable/Disable the DHCP client after connection.
Synchronous Wi-Fi DHCP enable function. This function will Enable/Disable the DHCP protocol.
Parameters
[in] u8DhcpEn The state of the DHCP client feature after successful association with an access point:
1: Enables DHCP client after connection.
0: Disables DHCP client after connection.
Returns
The function SHALL return M2M_SUCCESS for successful operation and a negative value otherwise.
Warning
DHCP client is enabled by default. This Function should be called before using m2m_wifi_set_static_ip
See also
m2m_wifi_set_static_ip
Definition at line 1191 of file m2m_wifi.c.
{
    uint8   u8Req;
    u8Req = u8DhcpEn ? M2M_IP_REQ_ENABLE_DHCP : M2M_IP_REQ_DISABLE_DHCP;
    return hif_send(M2M_REQ_GROUP_IP, u8Req, NULL, 0, NULL, 0, 0);
}
References hif_send(), M2M_IP_REQ_DISABLE_DHCP, M2M_IP_REQ_ENABLE_DHCP, M2M_REQ_GROUP_IP, and NULL.
m2m_wifi_enable_firmware_logs()
sint8 m2m_wifi_enable_firmware_logs (uint8 u8Enable)
Enable or Disable logs in run time (Disable Firmware logs will enhance the firmware start-up time and performance)
Enable or Disable logs in run time.
Parameters
[in] u8Enable Set 1 to enable the logs 0 for disable
Returns
The function SHALL return M2M_SUCCESS for success and a negative value otherwise.
See also
DISABLE_FIRMWARE_LOGS (build option to disable logs from initializations)
Precondition
m2m_wifi_init
Warning
Enable or Disable logs in run time (Disable Firmware logs will enhance the firmware start-up time and performance).
Parameters
[in] u8Enable Set 1 to enable the logs, 0 for disable.
Precondition
Must be called after initialization through the following function m2m_wifi_init().
Returns
The function SHALL return M2M_SUCCESS for success and a negative value otherwise.
See also
DISABLE_FIRMWARE_LOGS (build option to disable logs from initializations) m2m_wifi_init
Definition at line 1875 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    tstrM2mEnableLogs strM2mEnableLogs;
    strM2mEnableLogs.u8Enable = u8Enable;
    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_ENABLE_LOGS, (uint8*)&strM2mEnableLogs,sizeof(tstrM2mEnableLogs), NULL, 0, 0);
    return ret;
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_SET_ENABLE_LOGS, NULL, and tstrM2mEnableLogs::u8Enable.
m2m_wifi_enable_roaming()
sint8 m2m_wifi_enable_roaming (uint8 bEnableDhcp)
Enable WiFi STA roaming.
m2m_wifi_enable_roaming enables the firmware to trigger the roaming algorithm/steps on link loss with the current AP. If roaming is successful, the M2M_WIFI_RESP_CON_STATE_CHANGED message with state as M2M_WIFI_ROAMED is sent to host. Additionally a M2M_WIFI_REQ_DHCP_CONF message with new DHCP lease details is sent to host (only if bEnableDhcp=1). If roaming is unsuccessful, M2M_WIFI_RESP_CON_STATE_CHANGED message with state as M2M_WIFI_DISCONNECTED is sent to host.
Parameters
[in] bEnableDhcp 0 : Disables DHCP client execution after roaming to new AP 1 : Enables DHCP client execution after roaming to new AP
Precondition
Must be called after the initialization. The roaming algorithm/procedure is internal to the firmware.
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
See also
m2m_wifi_init
Definition at line 2047 of file m2m_wifi.c.
{
    tstrM2mWiFiRoaming  strWiFiRoaming;
    strWiFiRoaming.u8EnableRoaming = 1;
    if(0 == bEnableDhcp || 1 == bEnableDhcp)
    {
        strWiFiRoaming.u8EnableDhcp = bEnableDhcp;
        return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_ROAMING,
            (uint8 *) &strWiFiRoaming, sizeof(tstrM2mWiFiRoaming), NULL, 0, 0);
    }
    else
    {
        return M2M_ERR_INVALID_ARG;
    }
}
References hif_send(), M2M_ERR_INVALID_ARG, M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_ROAMING, NULL, tstrM2mWiFiRoaming::u8EnableDhcp, and tstrM2mWiFiRoaming::u8EnableRoaming.
m2m_wifi_enable_sntp()
NMI_API sint8 m2m_wifi_enable_sntp (uint8 bEnable)
Synchronous function to enable/disable the native Simple Network Time Protocol(SNTP) client in the WINC15x0 firmware.
The SNTP is enabled by default at start-up.The SNTP client at firmware is used to synchronize the system clock to the UTC time from the well known time servers (e.g. "time-c.nist.gov"). The SNTP client uses a default update cycle of 1 day.
The UTC is important for checking the expiration date of X509 certificates used while establishing TLS (Transport Layer Security) connections.
It is highly recommended to use it if there is no other means to get the UTC time. If there is a RTC on the host MCU, the SNTP could be disabled and the host should set the system time to the firmware using the m2m_wifi_set_system_time function.
Parameters
[in] bEnable Enables or disables the SNTP service '0' :disable SNTP '1' :enable SNTP
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
m2m_wifi_set_system_time
Definition at line 1800 of file m2m_wifi.c.
{
    uint8   u8Req;
    u8Req = bEnable ? M2M_WIFI_REQ_ENABLE_SNTP_CLIENT : M2M_WIFI_REQ_DISABLE_SNTP_CLIENT;
    return hif_send(M2M_REQ_GROUP_WIFI, u8Req, NULL, 0, NULL, 0, 0);
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_DISABLE_SNTP_CLIENT, M2M_WIFI_REQ_ENABLE_SNTP_CLIENT, and NULL.
m2m_wifi_enable_XO_during_sleep()
sint8 m2m_wifi_enable_XO_during_sleep (uint8 bXOSleepEnable)
Specifies whether the crystal oscillator is left on or off during deep sleep (defaults to off).
m2m_wifi_enable_XO_during_sleep controls the state of the crystal oscillator during deep sleep.
Parameters
[in] bXOSleepEnable 0 : The XO will be switched off during deep sleep 1 : The XO will be kept on during deep sleep
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 2069 of file m2m_wifi.c.
{
    tstrM2mWiFiXOSleepEnable  strM2mWiFiXOSleepEnable;
    if(0 == bXOSleepEnable || 1 == bXOSleepEnable)
    {
        strM2mWiFiXOSleepEnable.u8EnableXODuringSleep = bXOSleepEnable;
        return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_XO_SLEEP_ENABLE,
                        (uint8 *) &strM2mWiFiXOSleepEnable, sizeof(strM2mWiFiXOSleepEnable), NULL, 0, 0);
    }
    else
    {
        return M2M_ERR_INVALID_ARG;
    }
}
References hif_send(), M2M_ERR_INVALID_ARG, M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_XO_SLEEP_ENABLE, NULL, and tstrM2mWiFiXOSleepEnable::u8EnableXODuringSleep.
m2m_wifi_get_connection_info()
NMI_API sint8 m2m_wifi_get_connection_info (void)
Asynchronous API for retrieving the WINC IC's connection status.
Asynchronous connection status retrieval function, retrieves the status information of the currently connected AP. The result is passed to the Wi-Fi notification callback through the event M2M_WIFI_RESP_CONN_INFO. Connection information is retrieved from the structure tstrM2MConnInfo.
Connection Information retrieved: -Connection Security -Connection RSSI -Remote MAC address -Remote IP address
In case the WINC is operating in station mode, the SSID of the AP is also retrieved.
Precondition
A Wi-Fi notification callback of type tpfAppWifiCb MUST be implemented and registered at startup. Registering the callback is done through passing it to the initialization m2m_wifi_init function.
The event M2M_WIFI_RESP_CONN_INFO must be handled in the callback to receive the requested connection info.
Warning
In case the WINC is operating in AP mode, the SSID field will be returned as a NULL string.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
M2M_WIFI_RESP_CONN_INFO, tstrM2MConnInfo
Example
The code snippet shows an example of how wi-fi connection information is retrieved .
#include "m2m_wifi.h"
#include "m2m_types.h"
void wifi_event_cb(uint8 u8WiFiEvent, void * pvMsg)
{
    switch(u8WiFiEvent)
    {
    case M2M_WIFI_RESP_CONN_INFO:
        {
            tstrM2MConnInfo     *pstrConnInfo = (tstrM2MConnInfo*)pvMsg;
            printf("CONNECTED AP INFO\n");
            printf("SSID                : %s\n",pstrConnInfo->acSSID);
            printf("SEC TYPE            : %d\n",pstrConnInfo->u8SecType);
            printf("Signal Strength     : %d\n", pstrConnInfo->s8RSSI);
            printf("Local IP Address    : %d.%d.%d.%d\n",
                pstrConnInfo->au8IPAddr[0] , pstrConnInfo->au8IPAddr[1], pstrConnInfo->au8IPAddr[2], pstrConnInfo->au8IPAddr[3]);
        }
        break;
    case M2M_WIFI_REQ_DHCP_CONF:
        {
            // Get the current AP information.
            m2m_wifi_get_connection_info();
        }
        break;
    default:
        break;
    }
}
int main()
{
    tstrWifiInitParam   param;
    param.pfAppWifiCb   = wifi_event_cb;
    if(!m2m_wifi_init(&param))
    {
        // connect to the default AP
        m2m_wifi_default_connect();
        while(1)
        {
            m2m_wifi_handle_events(NULL);
        }
    }
}
Definition at line 1775 of file m2m_wifi.c.
{
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_GET_CONN_INFO, NULL, 0, NULL, 0, 0);
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_GET_CONN_INFO, and NULL.
m2m_wifi_get_firmware_version()
NMI_API sint8 m2m_wifi_get_firmware_version (tstrM2mRev * pstrRev)
Get Firmware version info.
Get the Firmware version info from the active partition, as defined in the structure tstrM2mRev.
Parameters
[out] pstrRev Pointer to the structure tstrM2mRev that contains the firmware version parameters.
Precondition
Must be called after initialization through the following function m2m_wifi_init.
See also
m2m_wifi_init
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 1711 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = hif_chip_wake();
    if(ret == M2M_SUCCESS)
    {
        ret = nm_get_firmware_full_info(pstrRev);
        hif_chip_sleep();
    }
    return ret;
}
References hif_chip_sleep(), hif_chip_wake(), M2M_SUCCESS, and nm_get_firmware_full_info().
m2m_wifi_get_mac_address()
NMI_API sint8 m2m_wifi_get_mac_address (uint8 * pu8MacAddr)
Request the current MAC address of the device (the working mac address). (the function is Blocking until response received)
Synchronous API to retrieve the MAC address currently in use by the device.
Parameters
[out] pu8MacAddr Output MAC address buffer of 6 bytes size.
Returns
The function shall return M2M_SUCCESS for success and a negative value otherwise.
See also
m2m_wifi_get_otp_mac_address
Precondition
m2m_wifi_init required to call any WIFI/socket function
Function to retrieve the current MAC address. The function is blocking until the response is received.
Precondition
Prior call to m2m_wifi_init is required before any WIFI/socket function.
Parameters
[out] pu8MacAddr Pointer to a buffer in memory containing a 6-byte MAC address (provided function returns M2M_SUCCESS).
Returns
The function returns M2M_SUCCESS for successful operation and a negative value otherwise.
See also
m2m_wifi_get_otp_mac_address
Definition at line 1547 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = hif_chip_wake();
    if(ret == M2M_SUCCESS)
    {
        ret = nmi_get_mac_address(pu8MacAddr);
        if(ret == M2M_SUCCESS)
        {
            ret = hif_chip_sleep();
        }
    }
    return ret;
}
References hif_chip_sleep(), hif_chip_wake(), M2M_SUCCESS, and nmi_get_mac_address().
m2m_wifi_get_num_ap_found()
NMI_API uint8 m2m_wifi_get_num_ap_found (void)
Reads the number of AP's found in the last Scan Request, The function read the number of AP's from global variable which updated in the wifi_cb in M2M_WIFI_RESP_SCAN_DONE.
Synchronous function to retrieve the number of AP's found during the last scan operation.
See also
m2m_wifi_request_scan
Returns
Return the number of AP's found in the last Scan Request.
Precondition
m2m_wifi_request_scan need to be called first
Warning
That function need to be called in the wifi_cb in M2M_WIFI_RESP_SCAN_DONE, calling that function in any other place will return undefined/undated numbers. Function used only in STA mode only.
The function reads the number of APs from global variable which was updated in the Wi-Fi callback function through the M2M_WIFI_RESP_SCAN_DONE event. Function used only in STA mode only.
See also
m2m_wifi_request_scan M2M_WIFI_RESP_SCAN_DONE M2M_WIFI_RESP_SCAN_RESULT
Precondition
m2m_wifi_request_scan must be called first to ensure up to date results are available.
A Wi-Fi notification callback of type tpfAppWifiCb MUST be implemented and registered at initialization. Registering the callback is done through passing it to the m2m_wifi_init.
The event M2M_WIFI_RESP_SCAN_DONE must be handled in the callback to receive the requested scan information.
Warning
This function must be called only in the wi-fi callback function when the events M2M_WIFI_RESP_SCAN_DONE or M2M_WIFI_RESP_SCAN_RESULT are received. Calling this function in any other place will result in undefined/outdated numbers.
Returns
Return the number of AP's found in the last Scan Request.
Example
The code snippet demonstrates an example of how the scan request is called from the application's main function and the handling of the events received in response.
#include "m2m_wifi.h"
#include "m2m_types.h"
void wifi_event_cb(uint8 u8WiFiEvent, void * pvMsg)
{
    static uint8    u8ScanResultIdx = 0;
    switch(u8WiFiEvent)
    {
    case M2M_WIFI_RESP_SCAN_DONE:
        {
            tstrM2mScanDone *pstrInfo = (tstrM2mScanDone*)pvMsg;
            printf("Num of AP found %d\n",pstrInfo->u8NumofCh);
            if(pstrInfo->s8ScanState == M2M_SUCCESS)
            {
                u8ScanResultIdx = 0;
                if(pstrInfo->u8NumofCh >= 1)
                {
                    m2m_wifi_req_scan_result(u8ScanResultIdx);
                    u8ScanResultIdx ++;
                }
                else
                {
                    printf("No AP Found Rescan\n");
                    m2m_wifi_request_scan(M2M_WIFI_CH_ALL);
                }
            }
            else
            {
                printf("(ERR) Scan fail with error <%d>\n",pstrInfo->s8ScanState);
            }
        }
        break;
    case M2M_WIFI_RESP_SCAN_RESULT:
        {
            tstrM2mWifiscanResult       *pstrScanResult =(tstrM2mWifiscanResult*)pvMsg;
            uint8                       u8NumFoundAPs = m2m_wifi_get_num_ap_found();
            printf(">>%02d RI %d SEC %s CH %02d BSSID %02X:%02X:%02X:%02X:%02X:%02X SSID %s\n",
                pstrScanResult->u8index,pstrScanResult->s8rssi,
                pstrScanResult->u8AuthType,
                pstrScanResult->u8ch,
                pstrScanResult->au8BSSID[0], pstrScanResult->au8BSSID[1], pstrScanResult->au8BSSID[2],
                pstrScanResult->au8BSSID[3], pstrScanResult->au8BSSID[4], pstrScanResult->au8BSSID[5],
                pstrScanResult->au8SSID);
            if(u8ScanResultIdx < u8NumFoundAPs)
            {
                // Read the next scan result
                m2m_wifi_req_scan_result(index);
                u8ScanResultIdx ++;
            }
        }
        break;
    default:
        break;
    }
}
int main()
{
    tstrWifiInitParam   param;
    param.pfAppWifiCb   = wifi_event_cb;
    if(!m2m_wifi_init(&param))
    {
        // Scan all channels
        m2m_wifi_request_scan(M2M_WIFI_CH_ALL);
        while(1)
        {
            m2m_wifi_handle_events(NULL);
        }
    }
}
Definition at line 1599 of file m2m_wifi.c.
{
    return gu8ChNum;
}
References gu8ChNum.
m2m_wifi_get_otp_mac_address()
NMI_API sint8 m2m_wifi_get_otp_mac_address (uint8 * pu8MacAddr, uint8 * pu8IsValid)
Request the MAC address stored on the OTP (one time programmable) memory of the device. (the function is Blocking until response received)
Synchronous API to query the MAC address programmed into the WINC ICs OTP memory.
Parameters
[out] pu8MacAddr Output MAC address buffer of 6 bytes size. Valid only if *pu8Valid=1.
[out] pu8IsValid A output boolean value to indicate the validity of pu8MacAddr in OTP. Output zero if the OTP memory is not programmed, non-zero otherwise.
Returns
The function shall return M2M_SUCCESS for success and a negative value otherwise.
See also
m2m_wifi_get_mac_address
Precondition
m2m_wifi_init required to call any WIFI/socket function
This function attempts to read the device's MAC address from the One Time Programmable (OTP) memory on the IC. The presence (yes or no) of a MAC address in the OTP memory and, in the case of it being present, its value is returned via RAM pointed to by the input arguments.
Request the MAC address stored on the One Time Programmable(OTP) memory of the device. The function is blocking until the response is received.
Precondition
Prior call to m2m_wifi_init is required before any WIFI/socket function.
Parameters
[out] pu8MacAddr Output MAC address buffer 6 bytes in size. Valid only if *pu8Valid=1.
[out] pu8IsValid A boolean value set by the callee to indicate the validity of pu8MacAddr in OTP. If no MAC has been programmed in the OTP the value of this parameter will be zero; otherwise it will be non-zero.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
See also
m2m_wifi_get_mac_address
Definition at line 1523 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = hif_chip_wake();
    if(ret == M2M_SUCCESS)
    {
        ret = nmi_get_otp_mac_address(pu8MacAddr, pu8IsValid);
        if(ret == M2M_SUCCESS)
        {
            ret = hif_chip_sleep();
        }
    }
    return ret;
}
References hif_chip_sleep(), hif_chip_wake(), M2M_SUCCESS, and nmi_get_otp_mac_address().
m2m_wifi_get_sleep_mode()
NMI_API uint8 m2m_wifi_get_sleep_mode (void)
Get the current Power save mode.
Synchronous power save mode retrieval function.
Returns
The current operating power saving mode.
See also
tenuPowerSaveModes , m2m_wifi_set_sleep_mode
Returns
The current operating power saving mode based on the enumerated sleep modes tenuPowerSaveModes.
See also
tenuPowerSaveModes m2m_wifi_set_sleep_mode
Definition at line 1609 of file m2m_wifi.c.
{
    return hif_get_sleep_mode();
}
References hif_get_sleep_mode().
m2m_wifi_get_state()
NMI_API uint8 m2m_wifi_get_state (void)
Get the wifi state.
Returns
The function returns the current wifi state (see tenuWifiState for the possible states).
Note
Check the WINC state. See tenuWifiState for possible states.
WIFI_STATE_INIT state represents WINC initialized but not started, this is a suitable state for safe flash access.
See also
m2m_wifi_init m2m_wifi_download_mode
Definition at line 2042 of file m2m_wifi.c.
{
    return gu8WifiState;
}
References gu8WifiState.
Referenced by m2m_ota_host_file_read_spi().
m2m_wifi_get_system_time()
NMI_API sint8 m2m_wifi_get_system_time (void)
Asynchronous API to obtain the system time in use by the WINC IC.
See also
m2m_wifi_enable_sntp tstrSystemTime
Note
get the system time from the sntp client using the API m2m_wifi_get_system_time.
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Asynchronous function used to retrieve the system time through the use of the response M2M_WIFI_RESP_GET_SYS_TIME. Response time retrieved is parsed into the members defined in the structure tstrSystemTime.
Note
Get the system time from the SNTP client using the API m2m_wifi_get_system_time.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
m2m_wifi_enable_sntp tstrSystemTime
Definition at line 1795 of file m2m_wifi.c.
{
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_GET_SYS_TIME, NULL,0, NULL, 0, 0);
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_GET_SYS_TIME, and NULL.
m2m_wifi_handle_events()
NMI_API sint8 m2m_wifi_handle_events (void * arg)
Synchronous M2M event handler function.
This function is responsible for handling interrupts received from the WINC firmware. Applications should call this function periodically in-order to receive the events that are to be handled by the callback functions implemented by the application.
Handle the various events received from the WINC board. Whenever an event happens in the WINC board (e.g. Connection, Disconnection, DHCP, etc), the WINC will interrupt the host to let it know that a new event has occurred. The host driver will attempt to handle these events whenever the application decides to do so by calling the m2m_wifi_handle_events function. It is mandatory to call this function periodically and independently of any other condition. It is ideal to include this function in the main and the most frequent loop of the host application.
Precondition
Prior to receiving events, the WINC driver should have been successfully initialized by calling the m2m_wifi_init function.
Warning
Failure to successfully complete this function indicates bus errors and hence a fatal error that will prevent the application from proceeding.
Returns
The function returns M2M_SUCCESS for successful interrupt handling and a negative value otherwise.
Definition at line 540 of file m2m_wifi.c.
{
    return hif_handle_isr();
}
References hif_handle_isr().
Referenced by wifi_handle_events().
m2m_wifi_init()
NMI_API sint8 m2m_wifi_init (tstrWifiInitParam * pWifiInitParam)
Synchronous API to initialize the WINC driver.
This function initializes the WINC driver by registering the callback function for the M2M_WIFI layer (also the callback function for bypass mode/monitoring mode if defined), initializing the host interface layer and the bus interfaces. Wi-Fi callback registering is essential to allow the handling of the events received, in response to the asynchronous Wi-Fi operations.
The possible Wi-Fi events that are expected to be received through the callback function (provided by the application) to the M2M_WIFI layer are listed below:
M2M_WIFI_RESP_CON_STATE_CHANGED
M2M_WIFI_RESP_CONN_INFO
M2M_WIFI_REQ_DHCP_CONF
M2M_WIFI_REQ_WPS
M2M_WIFI_RESP_IP_CONFLICT
M2M_WIFI_RESP_SCAN_DONE
M2M_WIFI_RESP_SCAN_RESULT
M2M_WIFI_RESP_CURRENT_RSSI
M2M_WIFI_RESP_CLIENT_INFO
M2M_WIFI_RESP_PROVISION_INFO
M2M_WIFI_RESP_DEFAULT_CONNECT
M2M_WIFI_RESP_ETHERNET_RX_PACKET (if bypass mode is enabled)
M2M_WIFI_RESP_WIFI_RX_PACKET (if monitoring mode is enabled)
Any application using the WINC driver must call this function at the start of its main function.
Parameters
[in] pWifiInitParam This is a pointer to a structure of type tstrWifiInitParam which contains pointers to the application WIFI layer callback function, monitoring mode callback and tstrEthInitParam structure (which contains initialization settings for bypass mode).
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Precondition
Prior to this function call, The application should initialize the BSP using nm_bsp_init. Also, application users must provide a call back function responsible for receiving all the wi-fi events that are received on the M2M_WIFI layer.
Warning
Failure to successfully complete indicates that the driver could not be initialized and a fatal error will prevent the application from proceeding, proper error handling should be implemented by the application.
See also
m2m_wifi_deinit m2m_wifi_init_hold m2m_wifi_init_start tstrWifiInitParam tenuM2mStaCmd tenuM2mStaCmd
Definition at line 513 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = m2m_wifi_init_hold();
    if (ret == M2M_SUCCESS)
{
        ret = m2m_wifi_init_start(pWifiInitParam);
    }
    return ret;
}
References M2M_SUCCESS, m2m_wifi_init_hold(), and m2m_wifi_init_start().
Referenced by wifi_init().
m2m_wifi_init_hold()
NMI_API sint8 m2m_wifi_init_hold (void)
First part of m2m_wifi_init, up to the point of initializing SPI for flash access.
See also
m2m_wifi_init m2m_wifi_init_start
Definition at line 443 of file m2m_wifi.c.
{
    sint8 ret = M2M_ERR_FAIL;
    /* Apply device specific initialization. */
    ret = nm_drv_init_hold();
    if(M2M_SUCCESS == ret) {
        gu8WifiState = WIFI_STATE_INIT;
    }
    return ret;
}
References gu8WifiState, M2M_ERR_FAIL, M2M_SUCCESS, nm_drv_init_hold(), and WIFI_STATE_INIT.
Referenced by m2m_wifi_init(), and m2m_wifi_reinit_hold().
m2m_wifi_init_start()
NMI_API sint8 m2m_wifi_init_start (tstrWifiInitParam * pWifiInitParam)
Second part of m2m_wifi_init, continuing from where m2m_wifi_init_hold left off.
Parameters
[in] pWifiInitParam This is a pointer to a variable of type tstrWifiInitParam which contains pointers to the application WIFI layer callback function (see tpfAppWifiCb), monitoring mode callback (see tpfAppEthCb) and tstrEthInitParam structure (which contains initialization settings for bypass mode).
See also
m2m_wifi_init tstrWifiInitParam
Definition at line 457 of file m2m_wifi.c.
{
    tstrM2mRev strtmp;
    sint8 ret = M2M_SUCCESS;
    uint8 u8WifiMode = M2M_WIFI_MODE_NORMAL;
    if(pWifiInitParam == NULL) {
        ret = M2M_ERR_FAIL;
        goto _EXIT0;
    }
    gpfAppWifiCb = pWifiInitParam->pfAppWifiCb;
#ifdef ETH_MODE
    gpfAppEthCb       = pWifiInitParam->strEthInitParam.pfAppEthCb;
    gau8ethRcvBuf     = pWifiInitParam->strEthInitParam.au8ethRcvBuf;
    gu16ethRcvBufSize = pWifiInitParam->strEthInitParam.u16ethRcvBufSize;
    if (pWifiInitParam->strEthInitParam.u8EthernetEnable)
        u8WifiMode = M2M_WIFI_MODE_ETHERNET;
#endif /* ETH_MODE */
    gu8scanInProgress = 0;
    /* Apply device specific initialization. */
    ret = nm_drv_init_start(&u8WifiMode);
    if(ret != M2M_SUCCESS)  goto _EXIT0;
    gu8WifiState = WIFI_STATE_START;
    /* Initialize host interface module */
    ret = hif_init(NULL);
    if(ret != M2M_SUCCESS)  goto _EXIT1;
    hif_register_cb(M2M_REQ_GROUP_WIFI,m2m_wifi_cb);
    ret = nm_get_firmware_full_info(&strtmp);
    M2M_INFO("Firmware ver   : %u.%u.%u Svnrev %u\n", strtmp.u8FirmwareMajor, strtmp.u8FirmwareMinor, strtmp.u8FirmwarePatch,strtmp.u16FirmwareSvnNum);
    M2M_INFO("Firmware Build %s Time %s\n",strtmp.BuildDate,strtmp.BuildTime);
    M2M_INFO("Firmware Min driver ver : %u.%u.%u\n", strtmp.u8DriverMajor, strtmp.u8DriverMinor, strtmp.u8DriverPatch);
    M2M_INFO("Driver ver: %u.%u.%u \n", M2M_RELEASE_VERSION_MAJOR_NO, M2M_RELEASE_VERSION_MINOR_NO, M2M_RELEASE_VERSION_PATCH_NO);
    M2M_INFO("Driver built at %s\t%s\n",__DATE__,__TIME__);
    if(M2M_ERR_FW_VER_MISMATCH == ret)
    {
        M2M_ERR("Mismatch Firmware Version\n");
    }
    goto _EXIT0;
_EXIT1:
    gu8WifiState = WIFI_STATE_DEINIT;
    nm_drv_deinit(NULL);
_EXIT0:
    return ret;
}
References tstrEthInitParam::au8ethRcvBuf, tstrM2mRev::BuildDate, tstrM2mRev::BuildTime, gpfAppWifiCb, gu8scanInProgress, gu8WifiState, hif_init(), hif_register_cb(), M2M_ERR, M2M_ERR_FAIL, M2M_ERR_FW_VER_MISMATCH, M2M_INFO, M2M_RELEASE_VERSION_MAJOR_NO, M2M_RELEASE_VERSION_MINOR_NO, M2M_RELEASE_VERSION_PATCH_NO, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, m2m_wifi_cb(), M2M_WIFI_MODE_ETHERNET, M2M_WIFI_MODE_NORMAL, nm_drv_deinit(), nm_drv_init_start(), nm_get_firmware_full_info(), NULL, tstrEthInitParam::pfAppEthCb, tstrWifiInitParam::pfAppWifiCb, tstrWifiInitParam::strEthInitParam, tstrEthInitParam::u16ethRcvBufSize, tstrM2mRev::u16FirmwareSvnNum, tstrM2mRev::u8DriverMajor, tstrM2mRev::u8DriverMinor, tstrM2mRev::u8DriverPatch, tstrEthInitParam::u8EthernetEnable, tstrM2mRev::u8FirmwareMajor, tstrM2mRev::u8FirmwareMinor, tstrM2mRev::u8FirmwarePatch, WIFI_STATE_DEINIT, and WIFI_STATE_START.
Referenced by m2m_wifi_init(), and m2m_wifi_reinit_start().
m2m_wifi_prng_get_random_bytes()
sint8 m2m_wifi_prng_get_random_bytes (uint8 * pu8PrngBuff, uint16 u16PrngSize)
Get random bytes using the PRNG bytes.
Asynchronous function for retrieving from the firmware a pseudo-random set of bytes.
Parameters
[in] u16PrngSize Size of the required random bytes to be generated.
[in] pu8PrngBuff Pointer to user allocated buffer.
Returns
The function SHALL return M2M_SUCCESS for success and a negative value otherwise.
Asynchronous function for retrieving from the firmware a pseudo-random set of bytes as specified in the size passed in as a parameter. The registered wifi-cb function retrieves the random bytes through the response M2M_WIFI_RESP_GET_PRNG
Parameters
[in] pu8PrngBuff Pointer to a buffer to receive data.
[in] u16PrngSize Requested size in bytes. Maximum 1580.
Warning
Size greater than the maximum specified (1580) causes a negative error M2M_ERR_FAIL.
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 1912 of file m2m_wifi.c.
{
    sint8 ret = M2M_ERR_FAIL;
    tstrPrng   strRng = {0};
    if(
            (u16PrngSize <= (M2M_HIF_MAX_PACKET_SIZE - (M2M_HIF_HDR_OFFSET + sizeof(tstrPrng))))
        &&  (pu8PrngBuff != NULL)
    )
    {
        strRng.u16PrngSize = u16PrngSize;
        strRng.pu8RngBuff  = pu8PrngBuff;
        ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_GET_PRNG|M2M_REQ_DATA_PKT, (uint8 *)&strRng, sizeof(tstrPrng), NULL, 0, 0);
    }
    else
    {
        M2M_ERR("PRNG Buffer exceeded maximum size %d or NULL Buffer\n", u16PrngSize);
    }
    return ret;
}
References hif_send(), M2M_ERR, M2M_ERR_FAIL, M2M_HIF_HDR_OFFSET, M2M_HIF_MAX_PACKET_SIZE, M2M_REQ_DATA_PKT, M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_GET_PRNG, NULL, tstrPrng::pu8RngBuff, and tstrPrng::u16PrngSize.
m2m_wifi_reinit()
NMI_API sint8 m2m_wifi_reinit (tstrWifiInitParam * pWifiInitParam)
De-initialize and then initialize wifi. Resets the WINC.
Parameters
[in] pWifiInitParam This is a pointer to a variable of type tstrWifiInitParam which contains pointers to the application WIFI layer callback function (see tpfAppWifiCb), monitoring mode callback (see tpfAppEthCb) and tstrEthInitParam structure (which contains initialization settings for bypass mode).
Note
m2m_wifi_reinit wraps a call to m2m_wifi_deinit and to m2m_wifi_init.
See also
m2m_wifi_deinit m2m_wifi_init tstrWifiInitParam
Definition at line 2022 of file m2m_wifi.c.
{
    sint8 ret = m2m_wifi_reinit_hold();
    if(M2M_SUCCESS == ret)
        ret = m2m_wifi_reinit_start(pWifiInitParam);
    return ret;
}
References M2M_SUCCESS, m2m_wifi_reinit_hold(), and m2m_wifi_reinit_start().
m2m_wifi_reinit_hold()
NMI_API sint8 m2m_wifi_reinit_hold (void)
First part of m2m_wifi_reinit, up to the point of initializing SPI for flash access.
Note
m2m_wifi_reinit_hold wraps a call to m2m_wifi_deinit and to m2m_wifi_init_hold.
See also
m2m_wifi_deinit m2m_wifi_reinit m2m_wifi_init_hold
Definition at line 2031 of file m2m_wifi.c.
{
    m2m_wifi_deinit(NULL);
    return m2m_wifi_init_hold();
}
References m2m_wifi_deinit(), m2m_wifi_init_hold(), and NULL.
Referenced by m2m_wifi_reinit().
m2m_wifi_reinit_start()
NMI_API sint8 m2m_wifi_reinit_start (tstrWifiInitParam * pWifiInitParam)
Second part of m2m_wifi_reinit, continuing from where m2m_wifi_reinit_hold left off.
Parameters
[in] pWifiInitParam This is a pointer to the tstrWifiInitParam structure which contains pointers to the application WIFI layer callback function (see tpfAppWifiCb), monitoring mode callback (see tpfAppEthCb) and tstrEthInitParam structure (which contains initialization settings for bypass mode).
See also
m2m_wifi_reinit m2m_wifi_init_start tstrWifiInitParam
Definition at line 2037 of file m2m_wifi.c.
{
    return m2m_wifi_init_start(pWifiInitParam);
}
References m2m_wifi_init_start().
Referenced by m2m_wifi_reinit().
m2m_wifi_req_client_ctrl()
NMI_API sint8 m2m_wifi_req_client_ctrl (uint8 u8Cmd)
Send a command to the PS Client (An WINC board running the ps_firmware), if the PS client send any commands it will be received in wifi_cb M2M_WIFI_RESP_CLIENT_INFO.
Asynchronous command sending function to the PS Client.
Parameters
[in] cmd Control command sent from PS Server to PS Client (command values defined by the application).
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
See also
m2m_wifi_req_server_init, M2M_WIFI_RESP_CLIENT_INFO
Precondition
m2m_wifi_req_server_init should be called first
Asynchronous command sending function to the PS Client (a WINC board running the ps_firmware) if the PS client sends any command, it will be received through the M2M_WIFI_RESP_CLIENT_INFO event.
Parameters
[in] cmd Control command sent from PS Server to PS Client (command values defined by the application)
Precondition
m2m_wifi_req_server_init should be called first.
Warning
This mode is not supported in the current release.
See also
m2m_wifi_req_server_init M2M_WIFI_RESP_CLIENT_INFO
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 1387 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
#ifdef _PS_SERVER_
    tstrM2Mservercmd    strCmd;
    strCmd.u8cmd = u8Cmd;
    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CLIENT_CTRL, (uint8*)&strCmd, sizeof(tstrM2Mservercmd), NULL, 0, 0);
#else
    M2M_ERR("_PS_SERVER_ is not defined\n");
#endif
    return ret;
}
References hif_send(), M2M_ERR, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_CLIENT_CTRL, NULL, and tstrM2Mservercmd::u8cmd.
m2m_wifi_req_curr_rssi()
NMI_API sint8 m2m_wifi_req_curr_rssi (void)
Request the current RSSI for the current connected AP, the response received in wifi_cb M2M_WIFI_RESP_CURRENT_RSSI
Asynchronous API to request the current Receive Signal Strength (RSSI) of the current connection.
See also
M2M_WIFI_RESP_CURRENT_RSSI
Returns
The function shall return M2M_SUCCESS for success and a negative value otherwise.
This function will result in the application receiving the RSSI via a M2M_WIFI_RESP_CURRENT_RSSI event.
Precondition
A Wi-Fi notification callback of type tpfAppWifiCb MUST be implemented and registered during initialization. Registration of the callback is done through passing it to m2m_wifi_init via the tstrWifiInitParam initialization structure.
The event M2M_WIFI_RESP_CURRENT_RSSI must be handled in the callback to receive the requested Rssi information.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
Example
The code snippet demonstrates how the RSSI request is called in the application's main function and the handling of the event received in the callback.
#include "m2m_wifi.h"
#include "m2m_types.h"
void wifi_event_cb(uint8 u8WiFiEvent, void * pvMsg)
{
    static uint8    u8ScanResultIdx = 0;
    switch(u8WiFiEvent)
    {
    case M2M_WIFI_RESP_CURRENT_RSSI:
        {
            sint8   *rssi = (sint8*)pvMsg;
            M2M_INFO("ch rssi %d\n",*rssi);
        }
        break;
    default:
        break;
    }
}
int main()
{
    tstrWifiInitParam   param;
    param.pfAppWifiCb   = wifi_event_cb;
    if(!m2m_wifi_init(&param))
    {
        // Scan all channels
        m2m_wifi_req_curr_rssi();
        while(1)
        {
            m2m_wifi_handle_events(NULL);
        }
    }
}
Definition at line 1490 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CURRENT_RSSI, NULL, 0, NULL,0, 0);
    return ret;
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_CURRENT_RSSI, and NULL.
m2m_wifi_req_scan_result()
NMI_API sint8 m2m_wifi_req_scan_result (uint8 index)
Reads the AP information from the Scan Result list with the given index, the response received in wifi_cb M2M_WIFI_RESP_SCAN_RESULT, the response pointer should be casted with tstrM2mWifiscanResult structure
Synchronous call to read the AP information from the SCAN Result list.
Parameters
[in] index Index for the requested result, the index range start from 0 till number of AP's found
See also
tstrM2mWifiscanResult,m2m_wifi_get_num_ap_found,m2m_wifi_request_scan
Returns
The function shall return M2M_SUCCESS for success and a negative value otherwise
Precondition
m2m_wifi_request_scan need to be called first, then m2m_wifi_get_num_ap_found to get the number of AP's found
Warning
Function used only in STA mode only. the scan result updated only if scan request called, else it will be cashed in firmware for the host scan request result, which mean if large delay occur between the scan request and the scan result request, the result will not be up-to-date
Synchronous call to read the AP information from the SCAN Result list with the given index. This function is expected to be called when the response events M2M_WIFI_RESP_SCAN_RESULT or M2M_WIFI_RESP_SCAN_DONE are received in the wi-fi callback function. The response information received can be obtained through the casting to the tstrM2mWifiscanResult structure.
Parameters
[in] index Index for the requested result, the index range start from 0 till number of AP's found.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
tstrM2mWifiscanResult m2m_wifi_get_num_ap_found m2m_wifi_request_scan
Precondition
m2m_wifi_request_scan needs to be called first, then m2m_wifi_get_num_ap_found to get the number of AP's found.
A Wi-Fi notification callback of type tpfAppWifiCb MUST be implemented and registered at startup. Registering the callback is done through passing it to the m2m_wifi_init function.
The event M2M_WIFI_RESP_SCAN_RESULT must be handled in the callback to receive the requested scan information.
Warning
Function used in STA mode only. the scan results are updated only if the scan request is called.
Calling this function only without a scan request will lead to firmware errors.
Application code should refrain from introducing a large delay between the scan request and the scan result request, to prevent errors occurring.
Example
The code snippet demonstrates an example of how the scan request is called from the application's main function and the handling of the events received in response.
#include "m2m_wifi.h"
#include "m2m_types.h"
void wifi_event_cb(uint8 u8WiFiEvent, void * pvMsg)
{
    static uint8    u8ScanResultIdx = 0;
    switch(u8WiFiEvent)
    {
    case M2M_WIFI_RESP_SCAN_DONE:
        {
            tstrM2mScanDone *pstrInfo = (tstrM2mScanDone*)pvMsg;
            printf("Num of AP found %d\n",pstrInfo->u8NumofCh);
            if(pstrInfo->s8ScanState == M2M_SUCCESS)
            {
                u8ScanResultIdx = 0;
                if(pstrInfo->u8NumofCh >= 1)
                {
                    m2m_wifi_req_scan_result(u8ScanResultIdx);
                    u8ScanResultIdx ++;
                }
                else
                {
                    printf("No AP Found Rescan\n");
                    m2m_wifi_request_scan(M2M_WIFI_CH_ALL);
                }
            }
            else
            {
                printf("(ERR) Scan fail with error <%d>\n",pstrInfo->s8ScanState);
            }
        }
        break;
    case M2M_WIFI_RESP_SCAN_RESULT:
        {
            tstrM2mWifiscanResult       *pstrScanResult =(tstrM2mWifiscanResult*)pvMsg;
            uint8                       u8NumFoundAPs = m2m_wifi_get_num_ap_found();
            printf(">>%02d RI %d SEC %s CH %02d BSSID %02X:%02X:%02X:%02X:%02X:%02X SSID %s\n",
                pstrScanResult->u8index,pstrScanResult->s8rssi,
                pstrScanResult->u8AuthType,
                pstrScanResult->u8ch,
                pstrScanResult->au8BSSID[0], pstrScanResult->au8BSSID[1], pstrScanResult->au8BSSID[2],
                pstrScanResult->au8BSSID[3], pstrScanResult->au8BSSID[4], pstrScanResult->au8BSSID[5],
                pstrScanResult->au8SSID);
            if(u8ScanResultIdx < u8NumFoundAPs)
            {
                // Read the next scan result
                m2m_wifi_req_scan_result(index);
                u8ScanResultIdx ++;
            }
        }
        break;
    default:
        break;
    }
}
int main()
{
    tstrWifiInitParam   param;
    param.pfAppWifiCb   = wifi_event_cb;
    if(!m2m_wifi_init(&param))
    {
        // Scan all channels
        m2m_wifi_request_scan(M2M_WIFI_CH_ALL);
        while(1)
        {
            m2m_wifi_handle_events(NULL);
        }
    }
}
Definition at line 1579 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    tstrM2mReqScanResult strReqScanRlt;
    strReqScanRlt.u8Index = index;
    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SCAN_RESULT, (uint8*) &strReqScanRlt, sizeof(tstrM2mReqScanResult), NULL, 0, 0);
    return ret;
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_SCAN_RESULT, NULL, and tstrM2mReqScanResult::u8Index.
m2m_wifi_req_server_init()
NMI_API sint8 m2m_wifi_req_server_init (uint8 ch)
Initialize the PS Server, The WINC support non secure communication with another WINC, (SERVER/CLIENT) through one byte command (probe request and probe response) without any connection setup.
Synchronous function to initialize the PS Server.
Parameters
[in] ch Server listening channel
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
See also
m2m_wifi_req_client_ctrl
Warning
The server mode can't be used with any other modes (STA/AP).
The WINC supports non secure communication with another WINC, (SERVER/CLIENT) through one byte command (probe request and probe response) without any connection setup. The server mode can't be used with any other modes (STA/AP)
Parameters
[in] ch Server listening channel
See also
m2m_wifi_req_client_ctrl
Warning
This mode is not supported in the current release.
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 1410 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
#ifdef _PS_SERVER_
    tstrM2mServerInit strServer;
    strServer.u8Channel = ch;
    ret = hif_send(M2M_REQ_GROUP_WIFI,M2M_WIFI_REQ_SERVER_INIT, (uint8*)&strServer, sizeof(tstrM2mServerInit), NULL, 0, 0);
#else
    M2M_ERR("_PS_SERVER_ is not defined\n");
#endif
    return ret;
}
References hif_send(), M2M_ERR, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_SERVER_INIT, NULL, and tstrM2mServerInit::u8Channel.
m2m_wifi_request_dhcp_client()
NMI_API sint8 m2m_wifi_request_dhcp_client (void)
Legacy (deprecated) Asynchronous API for starting a DHCP client on the WINC IC.
This is a legacy API and is no longer supported. Calls to this API will not result in any changes being made to the state of the WINC IC.
Warning
This function has been deprecated. DHCP is used automatically when the WINC IC connects.
Returns
This function always returns M2M_SUCCESS.
Definition at line 1169 of file m2m_wifi.c.
{
    /*legacy API should be removed */
    return 0;
}
Referenced by wifi_cb().
m2m_wifi_request_dhcp_server()
NMI_API sint8 m2m_wifi_request_dhcp_server (uint8 * addr)
Dhcp requested by the firmware automatically in STA/AP mode).
Warning
This function is legacy and exists only for compatibility with older applications. DHCP server is started automatically when enabling the AP mode.
Returns
This function always returns M2M_SUCCESS.
Definition at line 1175 of file m2m_wifi.c.
{
    /*legacy API should be removed */
    return 0;
}
m2m_wifi_request_scan()
NMI_API sint8 m2m_wifi_request_scan (uint8 ch)
Asynchronous API to request the WINC IC to scan for networks.
Scan statuses are delivered to the application via the Wi-Fi event callback (tpfAppWifiCb) in three stages. The first step involves the event M2M_WIFI_RESP_SCAN_DONE which, if successful, provides the number of detected networks (access points). The application must then read the list of access points via multiple calls to the asynchronous m2m_wifi_req_scan_result API. For each call to this function, the application will receive (step three) the event M2M_WIFI_RESP_SCAN_RESULT.
Parameters
[in] ch RF Channel ID for SCAN operation. It should be set according to tenuM2mScanCh, with a value of M2M_WIFI_CH_ALL to scan all channels.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
Precondition
A Wi-Fi notification callback of type tpfAppWifiCb MUST be implemented and registered at initialization. Registration of the callback is done via m2m_wifi_init.
The events M2M_WIFI_RESP_SCAN_DONE and M2M_WIFI_RESP_SCAN_RESULT must be handled in the (tpfAppWifiCb) callback.
The m2m_wifi_handle_events function MUST be called to receive the responses in the callback.
Warning
This API is valid only for STA mode, it may be called regardless of connection state (connected or disconnected states).
See also
M2M_WIFI_RESP_SCAN_DONE M2M_WIFI_RESP_SCAN_RESULT tpfAppWifiCb tstrM2mWifiscanResult tenuM2mScanCh m2m_wifi_init m2m_wifi_handle_events m2m_wifi_req_scan_result
Example
The code snippet demonstrates an example of how the scan request is called from the application's main function and the handling of the events received in response.
#include "m2m_wifi.h"
#include "m2m_types.h"
void wifi_event_cb(uint8 u8WiFiEvent, void * pvMsg)
{
    static uint8    u8ScanResultIdx = 0;
    switch(u8WiFiEvent)
    {
    case M2M_WIFI_RESP_SCAN_DONE:
        {
            tstrM2mScanDone *pstrInfo = (tstrM2mScanDone*)pvMsg;
            printf("Num of AP found %d\n",pstrInfo->u8NumofCh);
            if(pstrInfo->s8ScanState == M2M_SUCCESS)
            {
                u8ScanResultIdx = 0;
                if(pstrInfo->u8NumofCh >= 1)
                {
                    m2m_wifi_req_scan_result(u8ScanResultIdx);
                    u8ScanResultIdx ++;
                }
                else
                {
                    printf("No AP Found Rescan\n");
                    m2m_wifi_request_scan(M2M_WIFI_CH_ALL);
                }
            }
            else
            {
                printf("(ERR) Scan fail with error <%d>\n",pstrInfo->s8ScanState);
            }
        }
        break;
    case M2M_WIFI_RESP_SCAN_RESULT:
        {
            tstrM2mWifiscanResult       *pstrScanResult =(tstrM2mWifiscanResult*)pvMsg;
            uint8                       u8NumFoundAPs = m2m_wifi_get_num_ap_found();
            printf(">>%02d RI %d SEC %s CH %02d BSSID %02X:%02X:%02X:%02X:%02X:%02X SSID %s\n",
                pstrScanResult->u8index,pstrScanResult->s8rssi,
                pstrScanResult->u8AuthType,
                pstrScanResult->u8ch,
                pstrScanResult->au8BSSID[0], pstrScanResult->au8BSSID[1], pstrScanResult->au8BSSID[2],
                pstrScanResult->au8BSSID[3], pstrScanResult->au8BSSID[4], pstrScanResult->au8BSSID[5],
                pstrScanResult->au8SSID);
            if(u8ScanResultIdx < u8NumFoundAPs)
            {
                // Read the next scan result
                m2m_wifi_req_scan_result(index);
                u8ScanResultIdx ++;
            }
        }
        break;
    default:
        break;
    }
}
int main()
{
    tstrWifiInitParam   param;
    param.pfAppWifiCb   = wifi_event_cb;
    if(!m2m_wifi_init(&param))
    {
        // Scan all channels
        m2m_wifi_request_scan(M2M_WIFI_CH_ALL);
        while(1)
        {
            m2m_wifi_handle_events(NULL);
        }
    }
}
Definition at line 1260 of file m2m_wifi.c.
{
    sint8   s8Ret = M2M_SUCCESS;
    if(!gu8scanInProgress)
    {
        if(((ch >= M2M_WIFI_CH_1) && (ch <= M2M_WIFI_CH_14)) || (ch == M2M_WIFI_CH_ALL))
        {
            tstrM2MScan strtmp;
            strtmp.u8ChNum = ch;
            s8Ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SCAN, (uint8*)&strtmp, sizeof(tstrM2MScan),NULL, 0,0);
            if(s8Ret == M2M_SUCCESS)
            {
                gu8scanInProgress = 1;
            }
        }
        else
        {
            s8Ret = M2M_ERR_INVALID_ARG;
        }
    }
    else
    {
        s8Ret = M2M_ERR_SCAN_IN_PROGRESS;
    }
    return s8Ret;
}
References gu8scanInProgress, hif_send(), M2M_ERR_INVALID_ARG, M2M_ERR_SCAN_IN_PROGRESS, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_CH_1, M2M_WIFI_CH_14, M2M_WIFI_CH_ALL, M2M_WIFI_REQ_SCAN, NULL, and tstrM2MScan::u8ChNum.
m2m_wifi_request_scan_passive()
NMI_API sint8 m2m_wifi_request_scan_passive (uint8 ch, uint16 scan_time)
Similar to m2m_wifi_request_scan but performs passive scanning instead of active scanning.
Parameters
[in] ch RF Channel ID for SCAN operation. It should be set according to tenuM2mScanCh. With a value of M2M_WIFI_CH_ALL, means to scan all channels.
[in] scan_time The time in ms that passive scan is listening for beacons on each channel per one slot, enter 0 for default setting.
Warning
This function is not allowed in AP mode. It works only for STA mode (both connected or disconnected states).
Precondition
A Wi-Fi notification callback of type tpfAppWifiCb MUST be implemented and registered at initialization. Registering the callback is done through passing it to the m2m_wifi_init.
The events M2M_WIFI_RESP_SCAN_DONE and M2M_WIFI_RESP_SCAN_RESULT. must be handled in the callback.
The m2m_wifi_handle_events function MUST be called to receive the responses in the callback.
See also
M2M_WIFI_RESP_SCAN_DONE M2M_WIFI_RESP_SCAN_RESULT tpfAppWifiCb tstrM2mWifiscanResult tenuM2mScanCh m2m_wifi_init m2m_wifi_request_scan m2m_wifi_handle_events m2m_wifi_req_scan_result
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 1288 of file m2m_wifi.c.
{
    sint8   s8Ret = M2M_SUCCESS;
    if(!gu8scanInProgress)
    {
        if(((ch >= M2M_WIFI_CH_1) && (ch <= M2M_WIFI_CH_14)) || (ch == M2M_WIFI_CH_ALL))
        {
            tstrM2MScan strtmp;
            strtmp.u8ChNum = ch;
            strtmp.u16PassiveScanTime = scan_time;
            s8Ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_PASSIVE_SCAN, (uint8*)&strtmp, sizeof(tstrM2MScan),NULL, 0,0);
            if(s8Ret == M2M_SUCCESS)
            {
                gu8scanInProgress = 1;
            }
        }
        else
        {
            s8Ret = M2M_ERR_INVALID_ARG;
        }
    }
    else
    {
        s8Ret = M2M_ERR_SCAN_IN_PROGRESS;
    }
    return s8Ret;
}
References gu8scanInProgress, hif_send(), M2M_ERR_INVALID_ARG, M2M_ERR_SCAN_IN_PROGRESS, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_CH_1, M2M_WIFI_CH_14, M2M_WIFI_CH_ALL, M2M_WIFI_REQ_PASSIVE_SCAN, NULL, tstrM2MScan::u16PassiveScanTime, and tstrM2MScan::u8ChNum.
m2m_wifi_request_scan_ssid_list()
NMI_API sint8 m2m_wifi_request_scan_ssid_list (uint8 ch, uint8 * u8Ssidlist)
Asynchronous wi-fi scan request on the given channel and the hidden scan list.
The scan status is delivered in the wi-fi event callback and then the application is to read the scan results sequentially. The number of APs found (N) is returned in event M2M_WIFI_RESP_SCAN_DONE with the number of found APs. The application could read the list of APs by calling the function m2m_wifi_req_scan_result N times.
Parameters
[in] ch RF Channel ID for SCAN operation. It should be set according to tenuM2mScanCh. With a value of M2M_WIFI_CH_ALL, means to scan all channels.
[in] u8SsidList u8SsidList is a buffer containing a list of hidden SSIDs to include during the scan. The first byte in the buffer, u8SsidList[0], is the number of SSIDs encoded in the string. The number of hidden SSIDs cannot exceed MAX_HIDDEN_SITES. All SSIDs are concatenated in the following bytes and each SSID is prefixed with a one-byte header containing its length.
The total number of bytes in u8SsidList buffer, including length byte, cannot exceed 133 bytes (MAX_HIDDEN_SITES SSIDs x 32 bytes each, which is max SSID length). For instance, encoding the two hidden SSIDs "DEMO_AP" and "TEST" results in the following buffer content:
uint8 u8SsidList[14];
u8SsidList[0] = 2; // Number of SSIDs is 2
u8SsidList[1] = 7; // Length of the string "DEMO_AP" without NULL termination
memcpy(&u8SsidList[2], "DEMO_AP", 7);  // Bytes index 2-9 containing the string DEMO_AP
u8SsidList[9] = 4; // Length of the string "TEST" without NULL termination
memcpy(&u8SsidList[10], "TEST", 4);  // Bytes index 10-13 containing the string TEST
Note
It works with STA/AP mode (connected or disconnected).
Precondition
A Wi-Fi notification callback of type tpfAppWifiCb MUST be implemented and registered at initialization. Registering the callback is done through passing it to the m2m_wifi_init.
The events M2M_WIFI_RESP_SCAN_DONE and M2M_WIFI_RESP_SCAN_RESULT. must be handled in the callback.
The m2m_wifi_handle_events function MUST be called to receive the responses in the callback.
See also
M2M_WIFI_RESP_SCAN_DONE M2M_WIFI_RESP_SCAN_RESULT tpfAppWifiCb tstrM2mWifiscanResult tenuM2mScanCh m2m_wifi_init m2m_wifi_handle_events m2m_wifi_req_scan_result
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Example
The code snippet demonstrates an example of how the scan request is called from the application's main function and the handling of the events received in response.
#include "m2m_wifi.h"
#include "m2m_types.h"
static void request_scan_hidden_demo_ap(void);
void wifi_event_cb(uint8 u8WiFiEvent, void * pvMsg)
{
    static uint8    u8ScanResultIdx = 0;
    switch(u8WiFiEvent)
    {
    case M2M_WIFI_RESP_SCAN_DONE:
        {
            tstrM2mScanDone *pstrInfo = (tstrM2mScanDone*)pvMsg;
            printf("Num of AP found %d\n",pstrInfo->u8NumofCh);
            if(pstrInfo->s8ScanState == M2M_SUCCESS)
            {
                u8ScanResultIdx = 0;
                if(pstrInfo->u8NumofCh >= 1)
                {
                    m2m_wifi_req_scan_result(u8ScanResultIdx);
                    u8ScanResultIdx ++;
                }
                else
                {
                    printf("No AP Found Rescan\n");
                    request_scan_hidden_demo_ap();
                }
            }
            else
            {
                printf("(ERR) Scan fail with error <%d>\n",pstrInfo->s8ScanState);
            }
        }
        break;
    case M2M_WIFI_RESP_SCAN_RESULT:
        {
            tstrM2mWifiscanResult       *pstrScanResult =(tstrM2mWifiscanResult*)pvMsg;
            uint8                       u8NumFoundAPs = m2m_wifi_get_num_ap_found();
            printf(">>%02d RI %d SEC %s CH %02d BSSID %02X:%02X:%02X:%02X:%02X:%02X SSID %s\n",
                pstrScanResult->u8index,pstrScanResult->s8rssi,
                pstrScanResult->u8AuthType,
                pstrScanResult->u8ch,
                pstrScanResult->au8BSSID[0], pstrScanResult->au8BSSID[1], pstrScanResult->au8BSSID[2],
                pstrScanResult->au8BSSID[3], pstrScanResult->au8BSSID[4], pstrScanResult->au8BSSID[5],
                pstrScanResult->au8SSID);
            if(u8ScanResultIdx < u8NumFoundAPs)
            {
                // Read the next scan result
                m2m_wifi_req_scan_result(index);
                u8ScanResultIdx ++;
            }
        }
        break;
    default:
        break;
    }
}
static void request_scan_hidden_demo_ap(void)
{
    uint8 list[9];
    char ssid[] = "DEMO_AP";
    uint8 len = (uint8)(sizeof(ssid)-1);
    list[0] = 1;
    list[1] = len;
    memcpy(&list[2], ssid, len); // copy 7 bytes
    // Scan all channels
    m2m_wifi_request_scan_ssid_list(M2M_WIFI_CH_ALL, list);
}
int main()
{
    tstrWifiInitParam   param;
    param.pfAppWifiCb   = wifi_event_cb;
    if(!m2m_wifi_init(&param))
    {
        request_scan_hidden_demo_ap();
        while(1)
        {
            m2m_wifi_handle_events(NULL);
        }
    }
}
Definition at line 1319 of file m2m_wifi.c.
{
    sint8   s8Ret = M2M_ERR_INVALID_ARG;
    if(!gu8scanInProgress)
    {
        if((((ch >= M2M_WIFI_CH_1) && (ch <= M2M_WIFI_CH_14)) || (ch == M2M_WIFI_CH_ALL))&&(u8Ssidlist != NULL))
        {
            tstrM2MScan strtmp;
            uint16 u16Lsize = 0;
            uint8 u8Apnum = u8Ssidlist[u16Lsize];
            if(u8Apnum <= MAX_HIDDEN_SITES)
            {
                u16Lsize++;
                while(u8Apnum)
                {
                    if(u8Ssidlist[u16Lsize] >= M2M_MAX_SSID_LEN){
                        goto EXIT;
                    }else {
                        u16Lsize += u8Ssidlist[u16Lsize] + 1;
                        u8Apnum--;
                    }
                }
                strtmp.u8ChNum = ch;
                s8Ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SCAN_SSID_LIST|M2M_REQ_DATA_PKT, (uint8*)&strtmp, sizeof(tstrM2MScan),u8Ssidlist, u16Lsize,sizeof(tstrM2MScan));
                if(s8Ret == M2M_SUCCESS)
                {
                    gu8scanInProgress = 1;
                }
            }
        }
    }
    else
    {
        s8Ret = M2M_ERR_SCAN_IN_PROGRESS;
    }
EXIT:
    return s8Ret;
}
References gu8scanInProgress, hif_send(), M2M_ERR_INVALID_ARG, M2M_ERR_SCAN_IN_PROGRESS, M2M_MAX_SSID_LEN, M2M_REQ_DATA_PKT, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_CH_1, M2M_WIFI_CH_14, M2M_WIFI_CH_ALL, M2M_WIFI_REQ_SCAN_SSID_LIST, MAX_HIDDEN_SITES, NULL, and tstrM2MScan::u8ChNum.
m2m_wifi_request_sleep()
NMI_API sint8 m2m_wifi_request_sleep (uint32 u32SlpReqTime)
API to place the WINC IC into sleep mode for a specified period of time.
Synchronous power-save sleep request function, which requests the WINC device to sleep in the currently configured power save mode, as set using m2m_wifi_set_sleep_mode, for a specific time as defined by the passed in parameter. This function should be used in the M2M_PS_MANUAL power save mode only. A wake up request is automatically performed by the WINC device when any host driver API function, e.g. Wi-Fi or socket operation is called.
Parameters
[in] u32SlpReqTime Request sleep time in ms.
The best recommended sleep duration is left to be determined by the application. Taking into account that if the application sends notifications very rarely, sleeping for a long time can be a power-efficient decision. In contrast, applications that are sensitive for long periods of absence can experience performance degradation in the connection if long sleeping times are used.
Returns
The function returns M2M_SUCCESS for successful operation and a negative value otherwise.
Warning
The function should be called in M2M_PS_MANUAL power save mode only. As enumerated in tenuPowerSaveModes. It's also important to note that during the sleeping time while in the M2M_PS_MANUAL mode, AP beacon monitoring is bypassed and the wifi-connection may drop if the sleep period is elongated.
See also
tenuPowerSaveModes m2m_wifi_set_sleep_mode
Definition at line 1647 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    uint8 psType;
    psType = hif_get_sleep_mode();
    if(psType == M2M_PS_MANUAL)
    {
        tstrM2mSlpReqTime strPs;
        strPs.u32SleepTime = u32SlpReqTime;
        ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_DOZE, (uint8*) &strPs,sizeof(tstrM2mSlpReqTime), NULL, 0, 0);
    }
    return ret;
}
References hif_get_sleep_mode(), hif_send(), M2M_PS_MANUAL, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_DOZE, NULL, and tstrM2mSlpReqTime::u32SleepTime.
m2m_wifi_send_crl()
sint8 m2m_wifi_send_crl (tstrTlsCrlInfo * pCRL)
Asynchronous API that notifies the WINC with the Certificate Revocation List.
Parameters
[in] pCRL Pointer to the structure containing certificate revocation list details.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
Definition at line 436 of file m2m_wifi.c.
{
    sint8 s8Ret = M2M_ERR_FAIL;
    s8Ret = hif_send(M2M_REQ_GROUP_SSL, M2M_SSL_IND_CRL|M2M_REQ_DATA_PKT, NULL, 0, (uint8*)pCRL, sizeof(tstrTlsCrlInfo), 0);
    return s8Ret;
}
References hif_send(), M2M_ERR_FAIL, M2M_REQ_DATA_PKT, M2M_REQ_GROUP_SSL, M2M_SSL_IND_CRL, and NULL.
m2m_wifi_send_ethernet_pkt()
NMI_API sint8 m2m_wifi_send_ethernet_pkt (uint8 * pu8Packet, uint16 u16PacketSize)
Synchronous function to transmit an Ethernet packet.
Transmit a packet directly in ETHERNET/bypass mode where the TCP/IP stack is disabled and the implementation of this packet is left to the application developer. The Ethernet packet composition is left to the application developer.
Note
Packets are the user's responsibility.
Warning
This function available in ETHERNET/Bypass mode ONLY. Make sure that application defines ETH_MODE.
Parameters
[in] pu8Packet Pointer to a buffer holding the whole Ethernet frame.
[in] u16PacketSize The size of the whole packet in bytes.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
m2m_wifi_enable_mac_mcast m2m_wifi_set_receive_buffer
Definition at line 1496 of file m2m_wifi.c.
{
    sint8   s8Ret = -1;
    if((pu8Packet != NULL)&&(u16PacketSize>0))
    {
        tstrM2MWifiTxPacketInfo     strTxPkt;
        strTxPkt.u16PacketSize      = u16PacketSize;
        strTxPkt.u16HeaderLength    = M2M_ETHERNET_HDR_LEN;
        s8Ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SEND_ETHERNET_PACKET | M2M_REQ_DATA_PKT,
        (uint8*)&strTxPkt, sizeof(tstrM2MWifiTxPacketInfo), pu8Packet, u16PacketSize,  M2M_ETHERNET_HDR_OFFSET - M2M_HIF_HDR_OFFSET);
    }
    return s8Ret;
}
References hif_send(), M2M_ETHERNET_HDR_LEN, M2M_ETHERNET_HDR_OFFSET, M2M_HIF_HDR_OFFSET, M2M_REQ_DATA_PKT, M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SEND_ETHERNET_PACKET, NULL, tstrM2MWifiTxPacketInfo::u16HeaderLength, and tstrM2MWifiTxPacketInfo::u16PacketSize.
m2m_wifi_set_battery_voltage()
sint8 m2m_wifi_set_battery_voltage (uint16 u16BattVoltx100)
Enable or Disable logs in run time (Disable Firmware logs will enhance the firmware start-up time and performance)
Parameters
[in] u16BattVoltx100 battery voltage multiplied by 100
Returns
The function SHALL return M2M_SUCCESS for success and a negative value otherwise.
See also
DISABLE_FIRMWARE_LOGS (build option to disable logs from initializations)
Precondition
m2m_wifi_init
Warning
Definition at line 1895 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    tstrM2mBatteryVoltage strM2mBattVol = {0};
    strM2mBattVol.u16BattVolt = u16BattVoltx100;
    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_BATTERY_VOLTAGE, (uint8*)&strM2mBattVol,sizeof(tstrM2mBatteryVoltage), NULL, 0, 0);
    return ret;
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_SET_BATTERY_VOLTAGE, NULL, and tstrM2mBatteryVoltage::u16BattVolt.
m2m_wifi_set_cust_InfoElement()
NMI_API sint8 m2m_wifi_set_cust_InfoElement (uint8 * pau8M2mCustInfoElement)
API to add or remove a user-defined Information Element.
Synchronous function to Add/Remove user-defined Information Element to the WIFIBeacon and Probe Response frames while chip mode is Access Point Mode.
According to the information element layout shown bellow, if it is required to set new data for the information elements, pass in the buffer with the information according to the sizes and ordering defined bellow. However, if it's required to delete these IEs, fill the buffer with zeros.
Parameters
[in] pau8M2mCustInfoElement Pointer to Buffer containing the IE to be sent. It is the application developer's responsibility to ensure on the correctness of the information element's ordering passed in.
Warning
Size of All elements combined must not exceed 255 byte. Used in Access Point Mode.
Note
IEs Format will be follow the following layout:
    --------------- ---------- ---------- ------------------- -------- -------- ----------- -----------------------
              | Byte[0]       | Byte[1]  | Byte[2]  | Byte[3:length1+2] | ..... | Byte[n] | Byte[n+1] | Byte[n+2:lengthx+2]  |
    |---------------|----------|----------|-------------------|-------- --------|-----------|---------------------|
              | #of all Bytes | IE1 ID   | Length1  | Data1(Hex Coded)  | ..... | IEx ID  | Lengthx   | Datax(Hex Coded)     |
    --------------- ---------- ---------- ------------------- -------- -------- ----------- -----------------------
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
m2m_wifi_enable_sntp
Example
The example demonstrates how the information elements are set using this function.
char elementData[21];
static char state = 0; // To Add, Append, and Delete
if(0 == state) {    //Add 3 IEs
    state = 1;
    //Total Number of Bytes
    elementData[0]=12;
    //First IE
    elementData[1]=200; elementData[2]=1; elementData[3]='A';
    //Second IE
    elementData[4]=201; elementData[5]=2; elementData[6]='B'; elementData[7]='C';
    //Third IE
    elementData[8]=202; elementData[9]=3; elementData[10]='D'; elementData[11]=0; elementData[12]='F';
} else if(1 == state) {
    //Append 2 IEs to others, Notice that we keep old data in array starting with\n
    //element 13 and total number of bytes increased to 20
    state = 2;
    //Total Number of Bytes
    elementData[0]=20;
    //Fourth IE
    elementData[13]=203; elementData[14]=1; elementData[15]='G';
    //Fifth IE
    elementData[16]=204; elementData[17]=3; elementData[18]='X'; elementData[19]=5; elementData[20]='Z';
} else if(2 == state) { //Delete All IEs
    state = 0;
    //Total Number of Bytes
    elementData[0]=0;
}
m2m_wifi_set_cust_InfoElement(elementData);
Definition at line 1206 of file m2m_wifi.c.
{
    sint8  ret = M2M_ERR_FAIL;
    if(pau8M2mCustInfoElement != NULL)
    {
        if((pau8M2mCustInfoElement[0] + 1) < M2M_CUST_IE_LEN_MAX)
        {
            ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CUST_INFO_ELEMENT|M2M_REQ_DATA_PKT, (uint8*)pau8M2mCustInfoElement, pau8M2mCustInfoElement[0]+1, NULL, 0, 0);
        }
    }
    return ret;
}
References hif_send(), M2M_CUST_IE_LEN_MAX, M2M_ERR_FAIL, M2M_REQ_DATA_PKT, M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CUST_INFO_ELEMENT, and NULL.
m2m_wifi_set_device_name()
NMI_API sint8 m2m_wifi_set_device_name (uint8 * pu8DeviceName, uint8 u8DeviceNameLength)
Sets the WINC device name. The name string is used as a device name in DHCP hostname (option 12).
Asynchronous API to set the "Device Name" of the WINC IC.
Parameters
[in] pu8DeviceName Buffer holding the device name.
[in] u8DeviceNameLength Length of the device name.
Returns
The function SHALL return M2M_SUCCESS for success and a negative value otherwise.
Warning
The Function called once after initialization.
Sets the WINC device name. The name string is used as a device name in DHCP hostname (option 12). If a device is not set through this function a default name is assigned. The default name is WINC-XX-YY, where XX and YY are the last 2 octets of the OTP MAC address. If OTP (eFuse) is programmed, then the default name is WINC-00-00.
Warning
The function called once after initialization.
Used for DHCP client hostname option (12).
Device name shall contain only characters allowed in valid internet host name as defined in RFC 952 and 1123.
Parameters
[in] pu8DeviceName Buffer holding the device name. Device name is a null terminated C string.
[in] u8DeviceNameLength Length of the device name. Should not exceed the maximum device name's length M2M_DEVICE_NAME_MAX (including null character).
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
Definition at line 1670 of file m2m_wifi.c.
{
    tstrM2MDeviceNameConfig strDeviceName;
    if(u8DeviceNameLength >= M2M_DEVICE_NAME_MAX)
    {
        u8DeviceNameLength = M2M_DEVICE_NAME_MAX;
    }
    //pu8DeviceName[u8DeviceNameLength] = '\0';
    u8DeviceNameLength ++;
    m2m_memcpy(strDeviceName.au8DeviceName, pu8DeviceName, u8DeviceNameLength);
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_DEVICE_NAME,
        (uint8*)&strDeviceName, sizeof(tstrM2MDeviceNameConfig), NULL, 0,0);
}
References tstrM2MDeviceNameConfig::au8DeviceName, hif_send(), M2M_DEVICE_NAME_MAX, m2m_memcpy(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_DEVICE_NAME, and NULL.
m2m_wifi_set_gain_table_idx()
sint8 m2m_wifi_set_gain_table_idx (uint8 u8GainTableIdx)
set the gain table index corresponding to a specific WiFi region
Set the Gain table index corresponding to specific WiFi region.
Parameters
[in] u8GainTableIdx change the gain table index
Returns
The function SHALL return M2M_SUCCESS for success and a negative value otherwise.
Precondition
The gain tables must be written to the flash through gain builder tool. m2m_wifi_init
Warning
Parameters
[in] u8GainTableIdx change the gain table index based on the WiFi region it is suppose to be used.
Precondition
Must be called after the initialization and before any connection request. The corresponding gain tables must be present in the flash.
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
See also
m2m_wifi_init
Definition at line 1855 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    tstrM2mWiFiGainIdx strM2mGainTableIdx;
    strM2mGainTableIdx.u8GainTableIdx = u8GainTableIdx;
    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_GAIN_TABLE_IDX, (uint8*)&strM2mGainTableIdx,sizeof(tstrM2mWiFiGainIdx), NULL, 0, 0);
    return ret;
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_SET_GAIN_TABLE_IDX, NULL, and tstrM2mWiFiGainIdx::u8GainTableIdx.
m2m_wifi_set_gains()
sint8 m2m_wifi_set_gains (tstrM2mWifiGainsParams * pstrM2mGain)
Set the chip PPA gain for 11b/11gn.
Parameters
[in] pstrM2mGain tstrM2mWifiGainsParams contain gain parameters as implemented in rf document.
Precondition
Must be called after initialization through the following function m2m_wifi_init.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
m2m_wifi_init
Definition at line 1468 of file m2m_wifi.c.
{
    sint8 ret = M2M_ERR_FAIL;
    if(pstrM2mGain != NULL)
    {
        ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_GAINS, (uint8 *)pstrM2mGain, sizeof(tstrM2mWifiGainsParams), NULL, 0, 0);
    }
    return ret;
}
References hif_send(), M2M_ERR_FAIL, M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_GAINS, and NULL.
m2m_wifi_set_lsn_int()
NMI_API sint8 m2m_wifi_set_lsn_int (tstrM2mLsnInt * pstrM2mLsnInt)
Set the Wi-Fi listen interval for power save operation. It is represented in units of AP Beacon periods.
API to set Wi-Fi listen interval for power save operation.
Parameters
[in] pstrM2mLsnInt Structure holding the listen interval configurations.
Returns
The function SHALL return 0 for success and a negative value otherwise.
See also
tstrM2mLsnInt , m2m_wifi_set_sleep_mode
Precondition
m2m_wifi_set_sleep_mode shall be called first
Warning
The Function called once after initialization.
This is one of the two synchronous power-save setting functions that allow the host MCU application to tweak the system power consumption. Such tweaking can be done by modifying the Wi-Fi listen interval. The listen interval is how many beacon periods the station can sleep before it wakes up to receive data buffered in the AP. It is represented in units of AP beacon periods(100ms).
Warning
The function should be called once after initialization.
Parameters
[in] pstrM2mLsnInt Structure holding the listen interval configuration.
Precondition
The function m2m_wifi_set_sleep_mode shall be called first, to set the power saving mode required.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
tstrM2mLsnInt m2m_wifi_set_sleep_mode
Definition at line 1201 of file m2m_wifi.c.
{
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_LSN_INT, (uint8*)pstrM2mLsnInt, sizeof(tstrM2mLsnInt), NULL, 0, 0);
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_LSN_INT, and NULL.
m2m_wifi_set_mac_address()
NMI_API sint8 m2m_wifi_set_mac_address (uint8 au8MacAddress[6])
Synchronous API for assigning a MAC address to the WINC IC.
This function override the already assigned MAC address of the WINC board with a user provided one. This is for experimental use only and should never be used in the production SW.
Parameters
[in] au8MacAddress MAC Address to be provisioned to the WINC.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
Definition at line 1149 of file m2m_wifi.c.
{
    tstrM2mSetMacAddress strTmp;
    m2m_memcpy((uint8*) strTmp.au8Mac, (uint8*) au8MacAddress, 6);
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_MAC_ADDRESS,
        (uint8*) &strTmp, sizeof(tstrM2mSetMacAddress), NULL, 0,0);
}
References tstrM2mSetMacAddress::au8Mac, hif_send(), m2m_memcpy(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_MAC_ADDRESS, and NULL.
m2m_wifi_set_power_profile()
sint8 m2m_wifi_set_power_profile (uint8 u8PwrMode)
Change the power profile mode.
Parameters
[in] u8PwrMode Change the WINC power profile to different mode PWR_LOW1/PWR_LOW2/PWR_HIGH/PWR_AUTO (tenuM2mPwrMode)
Returns
The function SHALL return M2M_SUCCESS for success and a negative value otherwise.
See also
tenuM2mPwrMode
Precondition
m2m_wifi_init
Warning
must be called after the initializations and before any connection request and can't be changed in run time,
Parameters
[in] u8PwrMode Change the WINC power profile to different mode based on the enumeration tenuM2mPwrMode.
Warning
May only be called after initialization, before any connection request, and may not be used to change the power mode thereafter.
Returns
The function SHALL return M2M_SUCCESS for success and a negative value otherwise.
See also
tenuM2mPwrMode m2m_wifi_init
Definition at line 1818 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    tstrM2mPwrMode strM2mPwrMode;
    strM2mPwrMode.u8PwrMode = u8PwrMode;
    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_POWER_PROFILE, (uint8*)&strM2mPwrMode,sizeof(tstrM2mPwrMode), NULL, 0, 0);
    return ret;
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_SET_POWER_PROFILE, NULL, and tstrM2mPwrMode::u8PwrMode.
m2m_wifi_set_scan_options()
NMI_API sint8 m2m_wifi_set_scan_options (tstrM2MScanOption * ptstrM2MScanOption)
Synchronous API for configuring the behaviour of the WINC IC's network scanning functions.
This function sets the configuration parameters for the scan operation.
Parameters
[in] ptstrM2MScanOption; Pointer to the structure holding the Scan Parameters.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
tenuM2mScanCh m2m_wifi_request_scan tstrM2MScanOption
Definition at line 1220 of file m2m_wifi.c.
{
    sint8   s8Ret = M2M_ERR_FAIL;
    if(m2m_validate_scan_options (ptstrM2MScanOption) == M2M_SUCCESS)
    {
        s8Ret =  hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_SCAN_OPTION, (uint8*)ptstrM2MScanOption, sizeof(tstrM2MScanOption),NULL, 0,0);
    }
    return s8Ret;
}
References hif_send(), M2M_ERR_FAIL, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, m2m_validate_scan_options(), M2M_WIFI_REQ_SET_SCAN_OPTION, and NULL.
m2m_wifi_set_scan_region()
NMI_API sint8 m2m_wifi_set_scan_region (uint16 ScanRegion)
Synchronous API for configuring the regulatory restrictions that may affect the WINC ICs scanning behaviour.
This function sets a property called the scan region, a parameter that affects the range of channels that the WINC IC may legally scan given a geographic region.
For 2.4GHz, supported in the current release, the requested scan region can't exceed the maximum number of channels (14).
Parameters
[in] ScanRegion ASIA NORTH_AMERICA
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
tenuM2mScanCh m2m_wifi_request_scan
Definition at line 1252 of file m2m_wifi.c.
{
    sint8   s8Ret = M2M_ERR_FAIL;
    tstrM2MScanRegion strScanRegion;
    strScanRegion.u16ScanRegion = ScanRegion;
    s8Ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_SCAN_REGION, (uint8*)&strScanRegion, sizeof(tstrM2MScanRegion),NULL, 0,0);
    return s8Ret;
}
References hif_send(), M2M_ERR_FAIL, M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_SCAN_REGION, NULL, and tstrM2MScanRegion::u16ScanRegion.
m2m_wifi_set_sleep_mode()
NMI_API sint8 m2m_wifi_set_sleep_mode (uint8 PsTyp, uint8 BcastEn)
Set the power saving mode for the WINC1500.
Synchronous API to set the power-save mode of the WINC IC.
Parameters
[in] PsTyp Desired power saving mode. Supported types are defined in tenuPowerSaveModes.
[in] BcastEn Broadcast reception enable flag. If it is 1, the WINC1500 must be awake each DTIM Beacon for receiving Broadcast traffic. If it is 0, the WINC1500 will not wakeup at the DTIM Beacon, but its wakeup depends only on the the configured Listen Interval.
Returns
The function SHALL return 0 for success and a negative value otherwise.
See also
tenuPowerSaveModes
Warning
The function called once after initialization.
This is one of the two synchronous power-save setting functions that allow the host MCU application to tweak the system power consumption. Such tweaking can be done through one of two ways:
1) Changing the power save mode, to one of the allowed power save modes (see tenuPowerSaveModes). This is done by setting the first parameter.
2) Configuring DTIM monitoring: Configuring beacon monitoring parameters by enabling or disabling the reception of broadcast/multicast data. This is done by setting the second parameter.
Parameters
[in] PsTyp Desired power saving mode. Supported types are enumerated in tenuPowerSaveModes.
[in] BcastEn Broadcast reception enable flag. If it is 1, the WINC will be awake for each DTIM beacon in order to check for and receive broadcast traffic. If it is 0, the WINC will ignore broadcast traffic. Through this flag the WINC will not wakeup at the DTIM beacon, but instead it will wakeup only based on the configured Listen Interval.
Warning
The function called once after initialization.
Returns
The function returns M2M_SUCCESS for successful operation and a negative value otherwise.
See also
tenuPowerSaveModes m2m_wifi_get_sleep_mode m2m_wifi_set_lsn_int
Definition at line 1627 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    tstrM2mPsType strPs;
    strPs.u8PsType = PsTyp;
    strPs.u8BcastEn = BcastEn;
    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SLEEP, (uint8*) &strPs,sizeof(tstrM2mPsType), NULL, 0, 0);
    M2M_INFO("POWER SAVE %d\n",PsTyp);
    hif_set_sleep_mode(PsTyp);
    return ret;
}
References hif_send(), hif_set_sleep_mode(), M2M_INFO, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_SLEEP, NULL, tstrM2mPsType::u8BcastEn, and tstrM2mPsType::u8PsType.
m2m_wifi_set_static_ip()
NMI_API sint8 m2m_wifi_set_static_ip (tstrM2MIPConfig * pstrStaticIPConf)
Synchronous API to manually assign a (static) IP address to the WINC IC.
Assign a static IP address to the WINC board. This function assigns a static IP address in case the AP doesn't have a DHCP server or in case the application wants to assign a predefined known IP address. The user must keep in mind that assigning a static IP address might result in an IP address conflict. In case of an IP address conflict observed by the WINC board the user will get a response of M2M_WIFI_RESP_IP_CONFLICT in the wifi callback. The application is then responsible to either solve the conflict or assign another IP address.
Precondition
The application must disable auto DHCP using m2m_wifi_enable_dhcp before assigning a static IP address.
Warning
Normally this function should not be used. DHCP configuration is requested automatically after successful Wi-Fi connection is established.
Parameters
[in] pstrStaticIPConf Pointer to a structure holding the static IP configuration (IP, Gateway, subnet mask and DNS address).
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
tstrM2MIPConfig
Definition at line 1157 of file m2m_wifi.c.
{
    pstrStaticIPConf->u32DNS = NM_BSP_B_L_32(pstrStaticIPConf->u32DNS);
    pstrStaticIPConf->u32Gateway = NM_BSP_B_L_32(pstrStaticIPConf->u32Gateway);
    pstrStaticIPConf->u32StaticIP = NM_BSP_B_L_32(
        pstrStaticIPConf->u32StaticIP);
    pstrStaticIPConf->u32SubnetMask = NM_BSP_B_L_32(
        pstrStaticIPConf->u32SubnetMask);
    return hif_send(M2M_REQ_GROUP_IP, M2M_IP_REQ_STATIC_IP_CONF,
        (uint8*) pstrStaticIPConf, sizeof(tstrM2MIPConfig), NULL, 0,0);
}
References hif_send(), M2M_IP_REQ_STATIC_IP_CONF, M2M_REQ_GROUP_IP, NM_BSP_B_L_32, NULL, tstrM2MIPConfig::u32DNS, tstrM2MIPConfig::u32Gateway, tstrM2MIPConfig::u32StaticIP, and tstrM2MIPConfig::u32SubnetMask.
m2m_wifi_set_stop_scan_on_first()
NMI_API sint8 m2m_wifi_set_stop_scan_on_first (uint8 u8StopScanOption)
Synchronous API for enabling/disabling the stop scan on first result of the WINC IC's network scanning functions.
Allows for enabling/disabling of stop scan on first result. When enabled, the WINC will stop the scan as soon as it detects a network and return the results to the host. Setting is persistent and will need to be explicitly reverted back by the application if it no longer wishes for it to be enabled.
Parameters
[in] u8StopScanOption; Setting for enabling or disabling Stopping Scan on first result. 1 = Enabled, 0 = Disabled (Default)
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
tenuM2mScanCh tstrM2MScanOption tstrM2MStopScanOption m2m_wifi_request_scan m2m_wifi_set_scan_options
Definition at line 1230 of file m2m_wifi.c.
{
    sint8   s8Ret = M2M_ERR_FAIL;
    tstrM2MStopScanOption StopScanOption = { 0 };
    if(1 >= u8StopScanOption)
    {
        StopScanOption.u8StopOnFirstResult = u8StopScanOption;
        s8Ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_STOP_SCAN_OPTION, (uint8 *)&StopScanOption, sizeof(tstrM2MStopScanOption), NULL, 0, 0);
        M2M_INFO("Scan will %s stop on first result.\n", StopScanOption.u8StopOnFirstResult ? "" : "NOT");
    }
    else
    {
        s8Ret = M2M_ERR_INVALID_ARG;
    }
    return s8Ret;
}
References hif_send(), M2M_ERR_FAIL, M2M_ERR_INVALID_ARG, M2M_INFO, M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_STOP_SCAN_OPTION, NULL, and tstrM2MStopScanOption::u8StopOnFirstResult.
m2m_wifi_set_system_time()
NMI_API sint8 m2m_wifi_set_system_time (uint32 u32UTCSeconds)
Function for setting the system time within the WINC IC.
Synchronous function for setting the system time in time/date format (uint32). The tstrSystemTime structure can be used as a reference to the time values that should be set and pass its value as uint32.
Parameters
[in] u32UTCSeconds Seconds elapsed since January 1, 1900 (NTP Timestamp).
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
m2m_wifi_enable_sntp tstrSystemTime
Note
If there is an RTC on the host MCU, the SNTP may be disabled and the host may set the system time within the firmware using the API m2m_wifi_set_system_time.
Definition at line 1780 of file m2m_wifi.c.
{
    /*
        The firmware accepts timestamps relative to 1900 like NTP Timestamp.
    */
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_SYS_TIME, (uint8*)&u32UTCSeconds, sizeof(tstrSystemTime), NULL, 0, 0);
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_SYS_TIME, and NULL.
m2m_wifi_set_tx_power()
sint8 m2m_wifi_set_tx_power (uint8 u8TxPwrLevel)
set the TX power tenuM2mTxPwrLevel
Set the TX power tenuM2mTxPwrLevel.
Parameters
[in] u8TxPwrLevel change the TX power tenuM2mTxPwrLevel
Returns
The function SHALL return M2M_SUCCESS for success and a negative value otherwise.
See also
tenuM2mTxPwrLevel
Precondition
m2m_wifi_init
Warning
Parameters
[in] u8TxPwrLevel Change the TX power based on the enumeration tenuM2mTxPwrLevel.
Precondition
Must be called after the initialization and before any connection request and can't be changed in runtime.
Returns
The function SHALL return M2M_SUCCESS for success and a negative value otherwise.
See also
tenuM2mTxPwrLevel m2m_wifi_init
Definition at line 1836 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    tstrM2mTxPwrLevel strM2mTxPwrLevel;
    strM2mTxPwrLevel.u8TxPwrLevel = u8TxPwrLevel;
    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_TX_POWER, (uint8*)&strM2mTxPwrLevel,sizeof(tstrM2mTxPwrLevel), NULL, 0, 0);
    return ret;
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_SET_TX_POWER, NULL, and tstrM2mTxPwrLevel::u8TxPwrLevel.
m2m_wifi_start_provision_mode()
NMI_API sint8 m2m_wifi_start_provision_mode (tstrM2MAPConfig * pstrM2MAPConfig, char * pcHttpServerDomainName, uint8 bEnableHttpRedirect)
Asynchronous API for control of Wi-Fi provisioning functionality.
Asynchronous Wi-Fi provisioning function, which starts the WINC HTTP PROVISIONING mode. The function triggers the WINC to activate the Wi-Fi AP (HOTSPOT) mode with the passed configuration parameters and then starts the HTTP Provision WEB Server.
Provisioning status is returned in an event M2M_WIFI_RESP_PROVISION_INFO.
Parameters
[in] pstrAPConfig AP configuration parameters as defined in tstrM2MAPConfig configuration structure. If a NULL value is passed in, the call will result in a negative error M2M_ERR_FAIL.
[in] pcHttpServerDomainName Domain name of the HTTP Provision WEB server which others will use to load the provisioning Home page. The domain name can have one of the following 3 forms:
1. "wincprov.com"
2. "http://wincprov.com"
3. "https://wincprov.com"
Forms 1 and 2 are equivalent, they will both start a plain http server, while form 3 will start a secure HTTP provisioning Session (HTTP over SSL connection).
Parameters
[in] bEnableHttpRedirect A flag to enable/disable the HTTP redirect feature. If Secure provisioning is enabled (i.e. the server domain name uses "https" prefix) this flag is ignored (no meaning for redirect in HTTPS). Possible values are:
ZERO value, which means DO NOT use HTTP Redirect. In this case, the associated device could open the provisioning page ONLY when the HTTP Provision URL of the WINC HTTP Server is correctly written on the browser.
Non-Zero value, means use HTTP Redirect. In this case, all http traffic (http://URL) from the associated device (Phone, PC, etc) will be redirected to the WINC HTTP Provisioning Home page.
Precondition
A Wi-Fi notification callback of type tpfAppWifiCb MUST be implemented and registered at startup. Registering the callback is done through passing it to the initialization m2m_wifi_init function.
The event M2M_WIFI_RESP_CONN_INFO must be handled in the callback to receive the requested connection info.
Warning
DO NOT use ".local" in the pcHttpServerDomainName.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
tpfAppWifiCb m2m_wifi_init M2M_WIFI_RESP_PROVISION_INFO m2m_wifi_stop_provision_mode tstrM2MAPConfig
Example
The example demonstrates a code snippet for how provisioning is triggered and the response event received accordingly.
#include "m2m_wifi.h"
#include "m2m_types.h"
void wifi_event_cb(uint8 u8WiFiEvent, void * pvMsg)
{
    switch(u8WiFiEvent)
    {
    case M2M_WIFI_RESP_PROVISION_INFO:
        {
            tstrM2MProvisionInfo    *pstrProvInfo = (tstrM2MProvisionInfo*)pvMsg;
            if(pstrProvInfo->u8Status == M2M_SUCCESS)
            {
                tstrNetworkId   strNetworkId = {NULL, pstrProvInfo->au8SSID, (uint8)strlen((char*)(pstrProvInfo->au8SSID)), M2M_WIFI_CH_ALL};
                tstrAuthPsk     strAuthPsk = {NULL, pstrProvInfo->au8Password, (uint8)strlen((char*)(pstrProvInfo->au8Password))};
                m2m_wifi_connect_psk(WIFI_CRED_SAVE_ENCRYPTED, &strNetworkId, &strAuthPsk);
                printf("PROV SSID : %s\n",pstrProvInfo->au8SSID);
                printf("PROV PSK  : %s\n",pstrProvInfo->au8Password);
            }
            else
            {
                printf("(ERR) Provisioning Failed\n");
            }
        }
        break;
        default:
        break;
    }
}
int main()
{
    tstrWifiInitParam   param;
    param.pfAppWifiCb   = wifi_event_cb;
    if(!m2m_wifi_init(&param))
    {
        tstrM2MAPConfig     apConfig;
        uint8               bEnableRedirect = 1;
        strcpy(apConfig.au8SSID, "WINC_SSID");
        apConfig.u8ListenChannel    = 1;
        apConfig.u8SecType          = M2M_WIFI_SEC_OPEN;
        apConfig.u8SsidHide         = 0;
        // IP Address
        apConfig.au8DHCPServerIP[0] = 192;
        apConfig.au8DHCPServerIP[1] = 168;
        apConfig.au8DHCPServerIP[2] = 1;
        apConfig.au8DHCPServerIP[3] = 1;
        m2m_wifi_start_provision_mode(&apConfig, "atmelwincconf.com", bEnableRedirect);
        while(1)
        {
            m2m_wifi_handle_events(NULL);
        }
    }
}
Definition at line 1723 of file m2m_wifi.c.
{
    tstrM2MAPModeConfig strM2MAPModeConfig;
    m2m_memcpy((uint8 *)&strM2MAPModeConfig.strApConfig, (uint8 *)pstrM2MAPConfig, sizeof(tstrM2MAPConfig));
    m2m_memcpy(strM2MAPModeConfig.strApConfigExt.au8DefRouterIP, pstrM2MAPConfig->au8DHCPServerIP, 4);
    m2m_memcpy(strM2MAPModeConfig.strApConfigExt.au8DNSServerIP, pstrM2MAPConfig->au8DHCPServerIP, 4);
    strM2MAPModeConfig.strApConfigExt.au8SubnetMask[0] = 0;
    return m2m_wifi_start_provision_mode_ext(&strM2MAPModeConfig, pcHttpServerDomainName, bEnableHttpRedirect);
}
References tstrM2MAPConfigExt::au8DefRouterIP, tstrM2MAPConfig::au8DHCPServerIP, tstrM2MAPConfigExt::au8DNSServerIP, tstrM2MAPConfigExt::au8SubnetMask, m2m_memcpy(), m2m_wifi_start_provision_mode_ext(), tstrM2MAPModeConfig::strApConfig, and tstrM2MAPModeConfig::strApConfigExt.
m2m_wifi_start_provision_mode_ext()
NMI_API sint8 m2m_wifi_start_provision_mode_ext (tstrM2MAPModeConfig * pstrAPModeConfig, char * pcHttpServerDomainName, uint8 bEnableHttpRedirect)
Asynchronous API for control of Wi-Fi provisioning functionality with extended options.
Asynchronous Wi-Fi provisioning function, which starts the WINC HTTP PROVISIONING mode. The function triggers the WINC to activate the Wi-Fi AP (HOTSPOT) mode with the passed configuration parameters and then starts the HTTP Provision WEB Server.
Provisioning status is returned in an event M2M_WIFI_RESP_PROVISION_INFO.
Parameters
[in] pstrAPModeConfig AP configuration parameters as defined in tstrM2MAPModeConfig configuration structure. A NULL value passed in, will result in a negative error M2M_ERR_FAIL.
[in] pcHttpServerDomainName Domain name of the HTTP Provision WEB server which others will use to load the provisioning Home page. The domain name can have one of the following 3 forms:
1. "wincprov.com"
2. "http://wincprov.com"
3. "https://wincprov.com"
The forms 1 and 2 are equivalent, they both will start a plain http server, while form 3 will start a secure HTTP provisioning Session (HTTP over SSL connection).
Parameters
[in] bEnableHttpRedirect A flag to enable/disable the HTTP redirect feature. If Secure provisioning is enabled (i.e. the server domain name uses "https" prefix) this flag is ignored (no meaning for redirect in HTTPS). Possible values are:
ZERO value, which means DO NOT use HTTP Redirect. In this case, the associated device could open the provisioning page ONLY when the HTTP Provision URL of the WINC HTTP Server is correctly written on the browser.
Non-Zero value, means use HTTP Redirect. In this case, all http traffic (http://URL) from the associated device (Phone, PC, etc) will be redirected to the WINC HTTP Provisioning Home page.
Precondition
A Wi-Fi notification callback of type tpfAppWifiCb MUST be implemented and registered at startup. Registering the callback is done through passing it to the initialization m2m_wifi_init function.
The event M2M_WIFI_RESP_CONN_INFO must be handled in the callback to receive the requested connection info.
Warning
DO Not use ".local" in the pcHttpServerDomainName.
See also
tpfAppWifiCb m2m_wifi_init M2M_WIFI_RESP_PROVISION_INFO m2m_wifi_stop_provision_mode tstrM2MAPModeConfig
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
Example
The example demonstrates a code snippet for how provisioning is triggered and the response event received accordingly.
#include "m2m_wifi.h"
#include "m2m_types.h"
void wifi_event_cb(uint8 u8WiFiEvent, void * pvMsg)
{
    switch(u8WiFiEvent)
    {
    case M2M_WIFI_RESP_PROVISION_INFO:
        {
            tstrM2MProvisionInfo    *pstrProvInfo = (tstrM2MProvisionInfo*)pvMsg;
            if(pstrProvInfo->u8Status == M2M_SUCCESS)
            {
                tstrNetworkId   strNetworkId = {NULL, pstrProvInfo->au8SSID, (uint8)strlen((char*)(pstrProvInfo->au8SSID)), M2M_WIFI_CH_ALL};
                tstrAuthPsk     strAuthPsk = {NULL, pstrProvInfo->au8Password, (uint8)strlen((char*)(pstrProvInfo->au8Password))};
                m2m_wifi_connect_psk(WIFI_CRED_SAVE_ENCRYPTED, &strNetworkId, &strAuthPsk);
                printf("PROV SSID : %s\n",pstrProvInfo->au8SSID);
                printf("PROV PSK  : %s\n",pstrProvInfo->au8Password);
            }
            else
            {
                printf("(ERR) Provisioning Failed\n");
            }
        }
        break;
        default:
        break;
    }
}
int main()
{
    tstrWifiInitParam   param;
    param.pfAppWifiCb   = wifi_event_cb;
    if(!m2m_wifi_init(&param))
    {
        tstrM2MAPModeConfig apModeConfig;
        uint8               bEnableRedirect = 1;
        strcpy(apModeConfig.strApConfig.au8SSID, "WINC_SSID");
        apModeConfig.strApConfig.u8ListenChannel    = 1;
        apModeConfig.strApConfig.u8SecType          = M2M_WIFI_SEC_OPEN;
        apModeConfig.strApConfig.u8SsidHide         = 0;
        // IP Address
        apModeConfig.strApConfig.au8DHCPServerIP[0] = 192;
        apModeConfig.strApConfig.au8DHCPServerIP[1] = 168;
        apModeConfig.strApConfig.au8DHCPServerIP[2] = 1;
        apModeConfig.strApConfig.au8DHCPServerIP[3] = 1;
        // Default router IP
        m2m_memcpy(apModeConfig.strApConfigExt.au8DefRouterIP, apModeConfig.strApConfig.au8DHCPServerIP, 4);
        // DNS Server IP
        m2m_memcpy(apModeConfig.strApConfigExt.au8DNSServerIP, apModeConfig.strApConfig.au8DHCPServerIP, 4);
        // Subnet mask
        apModeConfig.strApConfigExt.au8SubnetMask[0]    = 255;
        apModeConfig.strApConfigExt.au8SubnetMask[1]    = 255;
        apModeConfig.strApConfigExt.au8SubnetMask[2]    = 255;
        apModeConfig.strApConfigExt.au8SubnetMask[3]    = 0;
        m2m_wifi_start_provision_mode_ext(&apModeConfig, "atmelwincconf.com", bEnableRedirect);
        while(1)
        {
            m2m_wifi_handle_events(NULL);
        }
    }
}
Definition at line 1736 of file m2m_wifi.c.
{
    sint8   s8Ret = M2M_ERR_FAIL;
    if(pstrAPModeConfig != NULL)
    {
        tstrM2MProvisionModeConfig  strProvConfig;
        if(M2M_SUCCESS == m2m_validate_ap_parameters(pstrAPModeConfig))
        {
            m2m_memcpy((uint8*)&strProvConfig.strApConfig, (uint8*)&pstrAPModeConfig->strApConfig, sizeof(tstrM2MAPConfig));
            m2m_memcpy((uint8*)&strProvConfig.strApConfigExt, (uint8*)&pstrAPModeConfig->strApConfigExt, sizeof(tstrM2MAPConfigExt));
            if((m2m_strlen((uint8 *)pcHttpServerDomainName) <= 0) || (NULL == pcHttpServerDomainName))
            {
                M2M_ERR("INVALID DOMAIN NAME\n");
                goto ERR1;
            }
            m2m_memcpy((uint8*)strProvConfig.acHttpServerDomainName, (uint8*)pcHttpServerDomainName, 64);
            strProvConfig.u8EnableRedirect = bEnableHttpRedirect;
            /* Stop Scan if it is ongoing.
            */
            gu8scanInProgress = 0;
            s8Ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_START_PROVISION_MODE | M2M_REQ_DATA_PKT,
                        (uint8*)&strProvConfig, sizeof(tstrM2MProvisionModeConfig), NULL, 0, 0);
        }
        else
        {
            /*goto ERR1;*/
        }
    }
ERR1:
    return s8Ret;
}
References tstrM2MProvisionModeConfig::acHttpServerDomainName, gu8scanInProgress, hif_send(), M2M_ERR, M2M_ERR_FAIL, m2m_memcpy(), M2M_REQ_DATA_PKT, M2M_REQ_GROUP_WIFI, m2m_strlen(), M2M_SUCCESS, m2m_validate_ap_parameters(), M2M_WIFI_REQ_START_PROVISION_MODE, NULL, tstrM2MAPModeConfig::strApConfig, tstrM2MProvisionModeConfig::strApConfig, tstrM2MAPModeConfig::strApConfigExt, tstrM2MProvisionModeConfig::strApConfigExt, and tstrM2MProvisionModeConfig::u8EnableRedirect.
Referenced by m2m_wifi_start_provision_mode().
m2m_wifi_stop_provision_mode()
NMI_API sint8 m2m_wifi_stop_provision_mode (void)
Synchronous API for terminating provisioning mode on the WINC IC.
This function will terminate any currently active provisioning mode on the WINC IC, returning the IC to idle.
Precondition
An active provisioning session must be active before it is terminated through this function.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
See also
m2m_wifi_start_provision_mode
Definition at line 1770 of file m2m_wifi.c.
{
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_STOP_PROVISION_MODE, NULL, 0, NULL, 0, 0);
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_STOP_PROVISION_MODE, and NULL.
m2m_wifi_wps()
NMI_API sint8 m2m_wifi_wps (uint8 u8TriggerType, const char * pcPinNumber)
Asynchronous API to engage the WINC IC's Wi-Fi Protected Setup (enrollee) function.
This function is called for the WINC to enter the WPS (Wi-Fi Protected Setup) mode. The result is passed to the Wi-Fi notification callback with the event M2M_WIFI_REQ_WPS.
Parameters
[in] u8TriggerType WPS Trigger method. This may be:
WPS_PIN_TRIGGER Push button method
WPS_PBC_TRIGGER Pin method
[in] pcPinNumber PIN number for WPS PIN method. It is not used if the trigger type is WPS_PBC_TRIGGER. It must follow the rules stated by the WPS standard.
Precondition
A Wi-Fi notification callback of type (tpfAppWifiCb MUST be implemented and registered at startup. Registering the callback is done through passing it to m2m_wifi_init.
The event M2M_WIFI_REQ_WPS must be handled in the callback to receive the WPS status.
The WINC device MUST be in IDLE or STA mode. If AP mode is active, the WPS will not be performed.
The m2m_wifi_handle_events MUST be called periodically to receive the responses in the callback.
Warning
This function is not allowed in AP mode.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
tpfAppWifiCb m2m_wifi_init M2M_WIFI_REQ_WPS tenuWPSTrigger tstrM2MWPSInfo
Example
The code snippet shows an example of how wi-fi WPS is triggered .
#include "m2m_wifi.h"
#include "m2m_types.h"
void wifi_event_cb(uint8 u8WiFiEvent, void * pvMsg)
{
    switch(u8WiFiEvent)
    {
    case M2M_WIFI_REQ_WPS:
        {
            tstrM2MWPSInfo  *pstrWPS = (tstrM2MWPSInfo*)pvMsg;
            if(pstrWPS->u8AuthType != 0)
            {
                // establish Wi-Fi connection
                tstrNetworkId   strNetworkId = {NULL, pstrWPS->au8SSID, (uint8)strlen((char*)(pstrWPS->au8SSID)), pstrWPS->u8Ch};
                if(pstrWPS->u8AuthType == M2M_WIFI_SEC_OPEN)
                {
                    m2m_wifi_connect_open(WIFI_CRED_SAVE_ENCRYPTED, &strNetworkId);
                }
                else
                {
                    tstrAuthPsk     strAuthPsk = {NULL, pstrWPS->au8PSK, (uint8)strlen((char*)(pstrWPS->au8PSK))};
                    m2m_wifi_connect_psk(WIFI_CRED_SAVE_ENCRYPTED, &strNetworkId, &strAuthPsk);
                }
                printf("WPS SSID           : %s\n",pstrWPS->au8SSID);
                printf("WPS PSK            : %s\n",pstrWPS->au8PSK);
                printf("WPS SSID Auth Type : %s\n",pstrWPS->u8AuthType == M2M_WIFI_SEC_OPEN ? "OPEN" : "WPA/WPA2");
                printf("WPS Channel        : %d\n",pstrWPS->u8Ch);
            }
            else
            {
                printf("(ERR) WPS Is not enabled OR Timed out\n");
            }
        }
        break;
    default:
        break;
    }
}
int main()
{
    tstrWifiInitParam   param;
    param.pfAppWifiCb   = wifi_event_cb;
    if(!m2m_wifi_init(&param))
    {
        // Trigger WPS in Push button mode.
        m2m_wifi_wps(WPS_PBC_TRIGGER, NULL);
        while(1)
        {
            m2m_wifi_handle_events(NULL);
        }
    }
}
Definition at line 1358 of file m2m_wifi.c.
{
    tstrM2MWPSConnect strtmp;
    /* Stop Scan if it is ongoing.
    */
    gu8scanInProgress = 0;
    strtmp.u8TriggerType = u8TriggerType;
    /*If WPS is using PIN METHOD*/
    if (u8TriggerType == WPS_PIN_TRIGGER)
        m2m_memcpy ((uint8*)strtmp.acPinNumber,(uint8*) pcPinNumber,8);
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_WPS, (uint8*)&strtmp,sizeof(tstrM2MWPSConnect), NULL, 0,0);
}
References tstrM2MWPSConnect::acPinNumber, gu8scanInProgress, hif_send(), m2m_memcpy(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_WPS, NULL, tstrM2MWPSConnect::u8TriggerType, and WPS_PIN_TRIGGER.
m2m_wifi_wps_disable()
NMI_API sint8 m2m_wifi_wps_disable (void)
Stops the ongoing WPS session.
Precondition
WINC should be already in WPS mode using m2m_wifi_wps.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
m2m_wifi_wps
Definition at line 1371 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_DISABLE_WPS, NULL,0, NULL, 0, 0);
    return ret;
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_DISABLE_WPS, and NULL.
m2m_wifi_yield()
NMI_API void m2m_wifi_yield (void)
Yield from processing more synchronous M2M events.
This function causes the synchronous M2M event handler function to yield from processing further events and return control to the caller.
Precondition
Prior to receiving Wi-Fi interrupts, the WINC driver should have been successfully initialized by calling the m2m_wifi_init function.
Warning
Failure to successfully complete this function indicates bus errors and hence a fatal error that will prevent the application from proceeding.
Definition at line 535 of file m2m_wifi.c.
{
    hif_yield();
}
References hif_yield().
Variable Documentation
__PAD24__
uint8 tstrM2mWifiWepParams::__PAD24__[3]
Definition at line 404 of file m2m_wifi.h.
__PAD8__
uint8 tstrEthInitParam::__PAD8__
Padding
Definition at line 331 of file m2m_wifi.h.
au8ethRcvBuf
uint8* tstrEthInitParam::au8ethRcvBuf
Pointer to Receive Buffer of Ethernet Packet
Definition at line 328 of file m2m_wifi.h.
Referenced by m2m_wifi_init_start().
au8Passwd
uint8 tstr1xAuthCredentials::au8Passwd[41]
Definition at line 410 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_sc().
au8UserName
uint8 tstr1xAuthCredentials::au8UserName[21]
Definition at line 409 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_sc().
au8WepKey
uint8 tstrM2mWifiWepParams::au8WepKey[WEP_104_KEY_STRING_SIZE+1]
Definition at line 403 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_sc().
bPrependDomain [1/2]
bool tstrAuth1xMschap2::bPrependDomain
Determines whether Domain is prepended or appended to UserName in EAP identity responses. true: Domain is prepended to UserName - [Domain][UserName]. false: Domain is appended to UserName - [UserName][Domain].
Definition at line 472 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_mschap2().
bPrependDomain [2/2]
bool tstrAuth1xTls::bPrependDomain
Determines whether Domain is prepended or appended to UserName in EAP identity responses. true: Domain is prepended to UserName - [Domain][UserName]. false: Domain is appended to UserName - [UserName][Domain].
Definition at line 524 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_tls().
bUnencryptedUserName [1/2]
bool tstrAuth1xMschap2::bUnencryptedUserName
Determines whether UserName or "anonymous" is sent (unencrypted) in the initial EAP identity response. Domain is sent in both cases.
true: UserName is sent in the initial EAP identity response (not recommended). false: "anonymous" is sent in the initial EAP identity response. This setting is recommended for tunneled methods. MSCHAPv2 is always a tunneled method.
Definition at line 466 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_mschap2().
bUnencryptedUserName [2/2]
bool tstrAuth1xTls::bUnencryptedUserName
Determines whether UserName or "anonymous" is sent (unencrypted) in the initial EAP identity response. Domain is sent in both cases.
true: UserName is sent in the initial EAP identity response (required for EAP-TLS). false: "anonymous" is sent in the initial EAP identity response. This setting is recommended for tunneled methods such as EAP-PEAP/TLS.
Definition at line 518 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_tls().
enuChannel
tenuM2mScanCh tstrNetworkId::enuChannel
Wi-Fi channel to connect on. If an appropriate AP cannot be found on this channel then connection fails. M2M_WIFI_CH_ALL may be used to allow scanning of all channels.
Definition at line 393 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_prepare_msg().
pfAppEthCb
tpfAppEthCb tstrEthInitParam::pfAppEthCb
Callback for Ethernet interface.
Definition at line 327 of file m2m_wifi.h.
Referenced by m2m_wifi_init_start().
pfAppMonCb
tpfAppMonCb tstrWifiInitParam::pfAppMonCb
Callback for monitoring interface.
Definition at line 381 of file m2m_wifi.h.
pfAppWifiCb [1/2]
tpfAppWifiCb tstrEthInitParam::pfAppWifiCb
Callback for wifi notifications.
Definition at line 326 of file m2m_wifi.h.
pfAppWifiCb [2/2]
tpfAppWifiCb tstrWifiInitParam::pfAppWifiCb
Callback for Wi-Fi notifications.
Definition at line 380 of file m2m_wifi.h.
Referenced by m2m_wifi_init_start(), and wifi_init().
pu8Bssid
uint8* tstrNetworkId::pu8Bssid
Pointer to BSSID (6 bytes). Optional (may be NULL). If present, this restricts the connection attempt to APs that have a matching BSSID.
Definition at line 386 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_prepare_msg().
pu8Certificate
uint8* tstrAuth1xTls::pu8Certificate
Pointer to TLS client certificate corresponding to PrivateKey. This will be used during TLS client authentication.
Definition at line 499 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_tls().
pu8Domain [1/2]
uint8* tstrAuth1xMschap2::pu8Domain
Pointer to Domain of authentication server (printable ASCII), including '@' or '\' separator character as appropriate. Use NULL if there is no domain information. The Domain will be either prepended or appended to the UserName, depending on the setting of field bPrependDomain.
Example 1: if [Domain]is "@my_domain" and bPrependDomain is false, then the EAP identity response is "[UserName]@my_domain".
Example 2: if [Domain]is "my_domain\" and bPrependDomain is true, then the EAP identity response is "my_domain\[UserName]".
Definition at line 437 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_mschap2().
pu8Domain [2/2]
uint8* tstrAuth1xTls::pu8Domain
Pointer to Domain of authentication server (printable ASCII), including '@' or '\' separator character as appropriate. Use NULL if there is no domain information. The Domain will be either prepended or appended to the UserName, depending on the setting of field bPrependDomain.
Example 1: if [Domain]is "@my_domain" and bPrependDomain is false, then the EAP identity response is "[UserName]@my_domain".
Example 2: if [Domain]is "my_domain\" and bPrependDomain is true, then the EAP identity response is "my_domain\[UserName]".
Definition at line 479 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_tls().
pu8Passphrase
uint8* tstrAuthPsk::pu8Passphrase
Pointer to Passphrase (Printable ASCII). Must be NULL if PSK is provided instead.
Definition at line 417 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_psk(), and m2m_wifi_connect_sc().
pu8Password
uint8* tstrAuth1xMschap2::pu8Password
Pointer to MSCHAPv2 Password (ASCII). This will be used during MSCHAPv2 authentication.
Definition at line 451 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_mschap2().
pu8PrivateKey_Exp
uint8* tstrAuth1xTls::pu8PrivateKey_Exp
Pointer to PrivateKey exponent (raw data). This will be used during TLS client authentication.
Definition at line 496 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_tls().
pu8PrivateKey_Mod
uint8* tstrAuth1xTls::pu8PrivateKey_Mod
Pointer to PrivateKey modulus (raw data). This will be used during TLS client authentication.
Definition at line 493 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_tls().
pu8Psk
uint8* tstrAuthPsk::pu8Psk
Pointer to PSK, represented as an ASCII string (64 characters, representing 32 bytes). Must be NULL if Passphrase is provided instead.
Definition at line 414 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_psk(), and m2m_wifi_connect_sc().
pu8Ssid
uint8* tstrNetworkId::pu8Ssid
Pointer to SSID. Required.
Definition at line 389 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_prepare_msg(), and m2m_wifi_connect_sc().
pu8UserName [1/2]
uint8* tstrAuth1xMschap2::pu8UserName
Pointer to UserName (ASCII). This will be sent (encrypted) in the tunneled EAP identity response (if applicable) and used during MSCHAPv2 authentication. If bUnencryptedUserName is true then it will also be sent (unencrypted) in the initial EAP identity response.
Definition at line 446 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_mschap2().
pu8UserName [2/2]
uint8* tstrAuth1xTls::pu8UserName
Pointer to UserName (ASCII). This will be sent (encrypted) in the tunneled EAP identity response. If bUnencryptedUserName is true then it will also be sent (unencrypted) in the initial EAP identity response.
Definition at line 488 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_tls().
pu8WepKey
uint8* tstrAuthWep::pu8WepKey
Pointer to WEP Key, represented as an ASCII string. (10 or 26 characters, representing 5 or 13 bytes.)
Definition at line 426 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_wep().
strEthInitParam
tstrEthInitParam tstrWifiInitParam::strEthInitParam
Structure to hold Ethernet interface parameters.
Definition at line 382 of file m2m_wifi.h.
Referenced by m2m_wifi_init_start().
u16CertificateLen
uint16 tstrAuth1xTls::u16CertificateLen
Length of Certificate (in bytes). Permitted values are between 0 and M2M_AUTH_1X_CERT_LEN_MAX.
Definition at line 515 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_tls().
u16DataSize
uint16 tstrM2mIpCtrlBuf::u16DataSize
Size of the received data in bytes.
Definition at line 358 of file m2m_wifi.h.
Referenced by m2m_wifi_cb().
u16DomainLen [1/2]
uint16 tstrAuth1xMschap2::u16DomainLen
Length of Domain (in ASCII characters), including '@' or '\' separator character as appropriate. Permitted values are such that u16DomainLen + u16UserNameLen is between 0 and M2M_AUTH_1X_USER_LEN_MAX.
Definition at line 454 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_mschap2().
u16DomainLen [2/2]
uint16 tstrAuth1xTls::u16DomainLen
Length of Domain (in ASCII characters), including '@' or '\' separator character as appropriate. Permitted values are such that u16DomainLen + u16UserNameLen is between 0 and M2M_AUTH_1X_USER_LEN_MAX.
Definition at line 502 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_tls().
u16ethRcvBufSize
uint16 tstrEthInitParam::u16ethRcvBufSize
Size of Receive Buffer for Ethernet Packet
Definition at line 329 of file m2m_wifi.h.
Referenced by m2m_wifi_init_start().
u16PasswordLen
uint16 tstrAuth1xMschap2::u16PasswordLen
Length of Password (in ASCII characters). Permitted values are between 0 and M2M_AUTH_1X_PASSWORD_LEN_MAX.
Definition at line 463 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_mschap2().
u16PrivateKeyLen
uint16 tstrAuth1xTls::u16PrivateKeyLen
Length of PrivateKey_Mod (in bytes). Permitted values are between 0 and M2M_AUTH_1X_PRIVATEKEY_LEN_MAX, typically 128 or 256. PrivateKey_Exp must be the same length as modulus, pre-padded with 0s if necessary.
Definition at line 511 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_tls().
u16RemainingDataSize
uint16 tstrM2mIpCtrlBuf::u16RemainingDataSize
Size of the remaining data bytes to be delivered to host.
Definition at line 359 of file m2m_wifi.h.
Referenced by m2m_wifi_cb().
u16UserNameLen [1/2]
uint16 tstrAuth1xMschap2::u16UserNameLen
Length of UserName (in ASCII characters). Permitted values are such that u16DomainLen + u16UserNameLen is between 0 and M2M_AUTH_1X_USER_LEN_MAX.
Definition at line 459 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_mschap2().
u16UserNameLen [2/2]
uint16 tstrAuth1xTls::u16UserNameLen
Length of UserName (in ASCII characters). Permitted values are such that u16DomainLen + u16UserNameLen is between 0 and M2M_AUTH_1X_USER_LEN_MAX.
Definition at line 507 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_1x_tls().
u8EthernetEnable
uint8 tstrEthInitParam::u8EthernetEnable
Enable Ethernet mode flag
Definition at line 330 of file m2m_wifi.h.
Referenced by m2m_wifi_init_start().
u8KeyIndx [1/2]
uint8 tstrM2mWifiWepParams::u8KeyIndx
Definition at line 401 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_sc().
u8KeyIndx [2/2]
uint8 tstrAuthWep::u8KeyIndx
WEP Key Index in the range 1 to 4.
Definition at line 432 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_wep().
u8KeySz [1/2]
uint8 tstrM2mWifiWepParams::u8KeySz
Definition at line 402 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_sc().
u8KeySz [2/2]
uint8 tstrAuthWep::u8KeySz
Size of WEP Key string. Permitted values are WEP_40_KEY_STRING_SIZE or WEP_104_KEY_STRING_SIZE.
Definition at line 429 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_wep().
u8PassphraseLen
uint8 tstrAuthPsk::u8PassphraseLen
Length of Passphrase. Permitted values are between 8 and 63. This field is ignored if pu8Passphrase == NULL.
Definition at line 420 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_psk(), and m2m_wifi_connect_sc().
u8SsidLen
uint8 tstrNetworkId::u8SsidLen
Length of SSID in bytes. Permitted values are between 0 and 32.
Definition at line 391 of file m2m_wifi.h.
Referenced by m2m_wifi_connect_prepare_msg(), and m2m_wifi_connect_sc().