WINC1500 Weather Client Demo for SAME70 Xplained: Standard serial I/O (stdio)
Standard serial I/O (stdio)
Standard I/O (stdio)
Common standard serial I/O management driver that implements a stdio serial interface on AVR and SAM devices.
Functions
static void stdio_serial_init (volatile void *usart, const usart_serial_options_t *opt)
Initializes the stdio in Serial Mode.
Variables
void(* ptr_get)(void volatile *, char *)
Pointer to the external low level read function.
int(* ptr_put)(void volatile *, char)
Pointer to the external low level write function.
volatile void *volatile stdio_base
Pointer to the base of the USART module instance to use for stdio.
Detailed Description
Common standard serial I/O management driver that implements a stdio serial interface on AVR and SAM devices.
Function Documentation
stdio_serial_init()
static void stdio_serial_init (volatile void * usart, const usart_serial_options_t * opt) inline static
Initializes the stdio in Serial Mode.
Parameters
usart Base address of the USART instance.
opt Options needed to set up RS232 communication (see usart_options_t).
Definition at line 82 of file stdio_serial.h.
{
    stdio_base = (void *)usart;
    ptr_put = (int (*)(void volatile*,char))&usart_serial_putchar;
    ptr_get = (void (*)(void volatile*,char*))&usart_serial_getchar;
# if (XMEGA || MEGA_RF)
    usart_serial_init((USART_t *)usart,opt);
# elif UC3
    usart_serial_init(usart,(usart_serial_options_t *)opt);
# elif SAM
    usart_serial_init((Usart *)usart,(usart_serial_options_t *)opt);
# else
#  error Unsupported chip type
# endif
# if defined(__GNUC__)
#  if (XMEGA || MEGA_RF)
    // For AVR GCC libc print redirection uses fdevopen.
    fdevopen((int (*)(char, FILE*))(_write),(int (*)(FILE*))(_read));
#  endif
#  if UC3 || SAM
    // For AVR32 and SAM GCC
    // Specify that stdout and stdin should not be buffered.
    setbuf(stdout, NULL);
    setbuf(stdin, NULL);
    // Note: Already the case in IAR's Normal DLIB default configuration
    // and AVR GCC library:
    // - printf() emits one character at a time.
    // - getchar() requests only 1 byte to exit.
#  endif
# endif
}
References _read(), _write(), NULL, ptr_get, ptr_put, stdio_base, usart_serial_getchar(), usart_serial_init(), and usart_serial_putchar().
Referenced by configure_console().
Variable Documentation
ptr_get
void(* ptr_get) (void volatile *, char *) (void volatile * , char *) extern
Pointer to the external low level read function.
Definition at line 50 of file read.c.
Referenced by _read(), and stdio_serial_init().
ptr_put
int(* ptr_put) (void volatile *, char) (void volatile * , char) extern
Pointer to the external low level write function.
Definition at line 47 of file write.c.
Referenced by _write(), and stdio_serial_init().
stdio_base
volatile void* volatile stdio_base extern
Pointer to the base of the USART module instance to use for stdio.
Definition at line 46 of file write.c.
Referenced by _write(), and stdio_serial_init().