WINC1500 Weather Client Demo for SAME70 Xplained: spi_flexible_flash_find_section
spi_flexible_flash_find_section
Spi Flash » Function
Functions
sint8 spi_flash_read (uint8 *pu8Buf, uint32 u32Addr, uint32 u32Sz)
Read a specified portion of data from SPI Flash.
.
sint8 spi_flexible_flash_find_section (uint16 u16EntryIDToLookFor, uint32 *pu32StartOffset, uint32 *pu32Size)
Read the Flash Map to extract the host file starting offset.
.
Detailed Description
Function Documentation
spi_flash_read()
sint8 spi_flash_read (uint8 * pu8Buf, uint32 u32offset, uint32 u32Sz)
Read a specified portion of data from SPI Flash.
.
Parameters
[out] pu8Buf Pointer to data buffer which will fill in with data in case of successful operation.
[in] u32Addr Address (Offset) to read from at the SPI flash.
[in] u32Sz Total size of data to be read in bytes
Warning
Address (offset) plus size of data must not exceed flash size.
No firmware is required for reading from SPI flash.
In case of there is a running firmware, it is required to pause your firmware first before any trial to access SPI flash to avoid any racing between host and running firmware on bus using m2m_wifi_download_mode
Note
It is blocking function
See also
m2m_wifi_download_mode, spi_flash_get_size
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 570 of file spi_flash.c.
{
    sint8 ret = M2M_SUCCESS;
    if(u32Sz > FLASH_BLOCK_SIZE)
    {
        do
        {
            ret = spi_flash_read_internal(pu8Buf, u32offset, FLASH_BLOCK_SIZE);
            if(M2M_SUCCESS != ret) goto ERR;
            u32Sz -= FLASH_BLOCK_SIZE;
            u32offset += FLASH_BLOCK_SIZE;
            pu8Buf += FLASH_BLOCK_SIZE;
        } while(u32Sz > FLASH_BLOCK_SIZE);
    }
    ret = spi_flash_read_internal(pu8Buf, u32offset, u32Sz);
ERR:
    return ret;
}
References FLASH_BLOCK_SIZE, M2M_SUCCESS, and spi_flash_read_internal().
Referenced by m2m_ota_host_file_read_spi(), and spi_flexible_flash_find_section().
spi_flexible_flash_find_section()
sint8 spi_flexible_flash_find_section (uint16 u16EntryIDToLookFor, uint32 * pu32StartOffset, uint32 * pu32Size)
Read the Flash Map to extract the host file starting offset.
.
Parameters
[in] u16EntryIDToLookFor The ID of the location in Flash we are looking for. See tenuFlashLUTEntryID.
[in] pu32StartOffset Pointer to the variable where the Flash section start address should be stored.
[in] pu32Size Pointer to the variable where the Flash section size should be stored.
Warning
In case there is a running WINC firmware, it is required to pause the firmware first before any trial to access SPI flash to avoid any racing between host and running firmware on bus. m2m_wifi_download_mode can be used to pause the firmware.
See also
m2m_wifi_download_mode m2m_wifi_init_hold
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 42 of file flexible_flash.c.
{
    sint8 s8Ret = M2M_ERR_INVALID_ARG;
    if((NULL == pu32StartOffset) || (NULL == pu32Size)) goto EXIT;
    uint8 au8buff[8];
    uint8 u8CurrEntry = 0;
    s8Ret = spi_flash_read(&au8buff[0], FLASH_MAP_TABLE_ADDR, 4);
    if(M2M_SUCCESS != s8Ret) goto EXIT;
    uint8 u8nEntries = au8buff[0];     // Max number is 32, reading one byte will suffice
    if(u8nEntries > N_ENTRIES_MAX)
    {
        s8Ret = M2M_ERR_FAIL;
        goto EXIT;
    }
    while(u8nEntries > u8CurrEntry)
    {
        s8Ret = spi_flash_read(&au8buff[0], FLASH_MAP_TABLE_ADDR + 4 + (u8CurrEntry*8), 8);
        u8CurrEntry++;
        if(M2M_SUCCESS != s8Ret) break;
        uint16 u16EntryID = (au8buff[1] << 8) | au8buff[0];
        if(u16EntryID != u16EntryIDToLookFor) continue;
        *pu32StartOffset = au8buff[2] * FLASH_SECTOR_SZ;
        *pu32Size        = au8buff[3] * FLASH_SECTOR_SZ;
        break;
    }
EXIT:
    return s8Ret;
}
References FLASH_MAP_TABLE_ADDR, FLASH_SECTOR_SZ, M2M_ERR_FAIL, M2M_ERR_INVALID_ARG, M2M_SUCCESS, N_ENTRIES_MAX, NULL, and spi_flash_read().
Referenced by m2m_ota_host_file_read_spi().