WINC1500 Weather Client Demo for SAME70 Xplained: Common IOPORT API
Common IOPORT API
See Quick start guide for the common IOPORT service.
Macros
#define IOPORT_CREATE_PIN(port, pin) ((IOPORT_ ## port) * 32 + (pin))
Create IOPORT pin number.
Enumerations
enum ioport_direction {
IOPORT_DIR_INPUT ,
IOPORT_DIR_OUTPUT
}
IOPORT pin directions.
enum ioport_sense {
IOPORT_SENSE_BOTHEDGES ,
IOPORT_SENSE_RISING ,
IOPORT_SENSE_FALLING
}
enum ioport_value {
IOPORT_PIN_LEVEL_LOW ,
IOPORT_PIN_LEVEL_HIGH
}
IOPORT levels.
Functions
static void ioport_disable_pin (ioport_pin_t pin)
Disable IOPORT pin, based on a pin created with IOPORT_CREATE_PIN().
static void ioport_disable_port (ioport_port_t port, ioport_port_mask_t mask)
Disable multiple pins in a single IOPORT port.
static void ioport_enable_pin (ioport_pin_t pin)
Enable an IOPORT pin, based on a pin created with IOPORT_CREATE_PIN().
static void ioport_enable_port (ioport_port_t port, ioport_port_mask_t mask)
Enable multiple pins in a single IOPORT port.
static bool ioport_get_pin_level (ioport_pin_t pin)
Get current value of an IOPORT pin, which has been configured as an input.
static ioport_port_mask_t ioport_get_port_level (ioport_pin_t port, ioport_port_mask_t mask)
Get current value of several IOPORT pins in a single port, which have been configured as an inputs.
static void ioport_init (void)
Initializes the IOPORT service, ready for use.
static ioport_port_mask_t ioport_pin_to_mask (ioport_pin_t pin)
Convert a pin ID into a bitmask mask for the given pin on its port.
static ioport_port_t ioport_pin_to_port_id (ioport_pin_t pin)
Convert a pin ID into a its port ID.
static void ioport_reset_pin_mode (ioport_pin_t pin)
Reset pin mode configuration for a single IOPORT pin.
static void ioport_reset_port_mode (ioport_port_t port, ioport_port_mask_t mask)
Reset multiple pin modes in a specified IOPORT port to defaults.
static void ioport_set_pin_dir (ioport_pin_t pin, enum ioport_direction dir)
Set direction for a single IOPORT pin.
static void ioport_set_pin_level (ioport_pin_t pin, bool level)
Set an IOPORT pin to a specified logical value.
static void ioport_set_pin_mode (ioport_pin_t pin, ioport_mode_t mode)
Set pin mode for one single IOPORT pin.
static void ioport_set_pin_sense_mode (ioport_pin_t pin, enum ioport_sense pin_sense)
Set the pin sense mode of a single IOPORT pin.
static void ioport_set_port_dir (ioport_port_t port, ioport_port_mask_t mask, enum ioport_direction dir)
Set I/O direction for a group of pins in a single IOPORT.
static void ioport_set_port_level (ioport_port_t port, ioport_port_mask_t mask, enum ioport_value level)
Set a group of IOPORT pins in a single port to a specified logical value.
static void ioport_set_port_mode (ioport_port_t port, ioport_port_mask_t mask, ioport_mode_t mode)
Set multiple pin modes in a single IOPORT port, such as pull-up, pull-down, etc.
static void ioport_set_port_sense_mode (ioport_port_t port, ioport_port_mask_t mask, enum ioport_sense pin_sense)
Set the pin sense mode of a multiple IOPORT pins on a single port.
static void ioport_toggle_pin_level (ioport_pin_t pin)
Toggle the value of an IOPORT pin, which has previously configured as an output.
static void ioport_toggle_port_level (ioport_port_t port, ioport_port_mask_t mask)
Toggle the values of several IOPORT pins located in a single port.
IOPORT Mode bit definitions
#define IOPORT_MODE_MUX_MASK (0x7 << 0)
#define IOPORT_MODE_MUX_BIT0 (1 << 0)
#define IOPORT_MODE_MUX_A (0 << 0)
#define IOPORT_MODE_MUX_B (1 << 0)
#define IOPORT_MODE_PULLUP (1 << 3)
#define IOPORT_MODE_OPEN_DRAIN (1 << 5)
#define IOPORT_MODE_GLITCH_FILTER (1 << 6)
#define IOPORT_MODE_DEBOUNCE (1 << 7)
Detailed Description
See Quick start guide for the common IOPORT service.
This is common IOPORT service for GPIO pin configuration and control in a standardized manner across the MEGA, MEGA_RF, XMEGA, UC3 and ARM devices.
Port pin control code is optimized for each platform, and should produce both compact and fast execution times when used with constant values.
Dependencies
This driver depends on the following modules:
System Clock Management for clock speed and functions.
IOPORT Modes
For details on these please see the SAM Manual.
Macro Definition Documentation
IOPORT_CREATE_PIN
#define IOPORT_CREATE_PIN (port, pin) ((IOPORT_ ## port) * 32 + (pin))
Create IOPORT pin number.
Create a IOPORT pin number for use with the IOPORT functions.
Parameters
port IOPORT port (e.g. PORTA, PA or PIOA depending on chosen architecture)
pin IOPORT zero-based index of the I/O pin
Definition at line 41 of file ioport_pio.h.
IOPORT_MODE_DEBOUNCE
#define IOPORT_MODE_DEBOUNCE (1 << 7)
Input debounce
Definition at line 87 of file ioport_pio.h.
IOPORT_MODE_GLITCH_FILTER
#define IOPORT_MODE_GLITCH_FILTER (1 << 6)
Glitch filter
Definition at line 86 of file ioport_pio.h.
IOPORT_MODE_MUX_A
#define IOPORT_MODE_MUX_A (0 << 0)
MUX function A
Definition at line 70 of file ioport_pio.h.
IOPORT_MODE_MUX_B
#define IOPORT_MODE_MUX_B (1 << 0)
MUX function B
Definition at line 71 of file ioport_pio.h.
IOPORT_MODE_MUX_BIT0
#define IOPORT_MODE_MUX_BIT0 (1 << 0)
MUX BIT0 mask
Definition at line 64 of file ioport_pio.h.
IOPORT_MODE_MUX_MASK
#define IOPORT_MODE_MUX_MASK (0x7 << 0)
MUX bits mask
Definition at line 63 of file ioport_pio.h.
IOPORT_MODE_OPEN_DRAIN
#define IOPORT_MODE_OPEN_DRAIN (1 << 5)
Open drain
Definition at line 84 of file ioport_pio.h.
IOPORT_MODE_PULLUP
#define IOPORT_MODE_PULLUP (1 << 3)
Pull-up
Definition at line 78 of file ioport_pio.h.
Enumeration Type Documentation
ioport_direction
enum ioport_direction
IOPORT pin directions.
Enumerator
IOPORT_DIR_INPUT
IOPORT input direction
IOPORT_DIR_OUTPUT
IOPORT output direction
Definition at line 76 of file ioport.h.
                      {
    IOPORT_DIR_INPUT,
    IOPORT_DIR_OUTPUT,
};
ioport_sense
enum ioport_sense
Enumerator
IOPORT_SENSE_BOTHEDGES
IOPORT sense both rising and falling edges
IOPORT_SENSE_RISING
IOPORT sense rising edges
IOPORT_SENSE_FALLING
IOPORT sense falling edges
Definition at line 112 of file ioport.h.
                  {
    IOPORT_SENSE_BOTHEDGES,
    IOPORT_SENSE_RISING,
    IOPORT_SENSE_FALLING,
};
ioport_value
enum ioport_value
IOPORT levels.
Enumerator
IOPORT_PIN_LEVEL_LOW
IOPORT pin value low
IOPORT_PIN_LEVEL_HIGH
IOPORT pin value high
Definition at line 82 of file ioport.h.
                  {
    IOPORT_PIN_LEVEL_LOW,
    IOPORT_PIN_LEVEL_HIGH,
};
Function Documentation
ioport_disable_pin()
static void ioport_disable_pin (ioport_pin_t pin) inline static
Disable IOPORT pin, based on a pin created with IOPORT_CREATE_PIN().
Parameters
pin IOPORT pin to disable
Definition at line 179 of file ioport.h.
{
    arch_ioport_disable_pin(pin);
}
References arch_ioport_disable_pin().
Referenced by nm_bus_init().
ioport_disable_port()
static void ioport_disable_port (ioport_port_t port, ioport_port_mask_t mask) inline static
Disable multiple pins in a single IOPORT port.
Parameters
port IOPORT port to disable
mask Pin mask of pins to disable
Definition at line 190 of file ioport.h.
{
    arch_ioport_disable_port(port, mask);
}
References arch_ioport_disable_port().
ioport_enable_pin()
static void ioport_enable_pin (ioport_pin_t pin) inline static
Enable an IOPORT pin, based on a pin created with IOPORT_CREATE_PIN().
Parameters
pin IOPORT pin to enable
Definition at line 156 of file ioport.h.
{
    arch_ioport_enable_pin(pin);
}
References arch_ioport_enable_pin().
Referenced by nm_bus_init().
ioport_enable_port()
static void ioport_enable_port (ioport_port_t port, ioport_port_mask_t mask) inline static
Enable multiple pins in a single IOPORT port.
Parameters
port IOPORT port to enable
mask Mask of pins within the port to enable
Definition at line 167 of file ioport.h.
{
    arch_ioport_enable_port(port, mask);
}
References arch_ioport_enable_port().
ioport_get_pin_level()
static bool ioport_get_pin_level (ioport_pin_t pin) inline static
Get current value of an IOPORT pin, which has been configured as an input.
Parameters
pin IOPORT pin to read
Returns
Current logical value of the specified pin
Definition at line 301 of file ioport.h.
{
    return arch_ioport_get_pin_level(pin);
}
References arch_ioport_get_pin_level().
Referenced by wifi_connect().
ioport_get_port_level()
static ioport_port_mask_t ioport_get_port_level (ioport_pin_t port, ioport_port_mask_t mask) inline static
Get current value of several IOPORT pins in a single port, which have been configured as an inputs.
Parameters
port IOPORT port to read
mask Pin mask of pins to read
Returns
Logical levels of the specified pins from the read port, returned as a mask.
Definition at line 315 of file ioport.h.
{
    return arch_ioport_get_port_level(port, mask);
}
References arch_ioport_get_port_level().
ioport_init()
static void ioport_init (void) inline static
Initializes the IOPORT service, ready for use.
This function must be called before using any other functions in the IOPORT service.
Definition at line 145 of file ioport.h.
{
    arch_ioport_init();
}
References arch_ioport_init().
Referenced by board_init(), init_chip_pins(), and main().
ioport_pin_to_mask()
static ioport_port_mask_t ioport_pin_to_mask (ioport_pin_t pin) inline static
Convert a pin ID into a bitmask mask for the given pin on its port.
Parameters
pin IOPORT pin ID to convert
Return values
Bitmask with a bit set that corresponds to the given pin ID in its port
Definition at line 387 of file ioport.h.
{
    return arch_ioport_pin_to_mask(pin);
}
References arch_ioport_pin_to_mask().
ioport_pin_to_port_id()
static ioport_port_t ioport_pin_to_port_id (ioport_pin_t pin) inline static
Convert a pin ID into a its port ID.
Parameters
pin IOPORT pin ID to convert
Return values
Port ID for the given pin ID
Definition at line 376 of file ioport.h.
{
    return arch_ioport_pin_to_port_id(pin);
}
References arch_ioport_pin_to_port_id().
ioport_reset_pin_mode()
static void ioport_reset_pin_mode (ioport_pin_t pin) inline static
Reset pin mode configuration for a single IOPORT pin.
Parameters
pin IOPORT pin to configure
Definition at line 239 of file ioport.h.
{
    arch_ioport_set_pin_mode(pin, 0);
}
References arch_ioport_set_pin_mode().
ioport_reset_port_mode()
static void ioport_reset_port_mode (ioport_port_t port, ioport_port_mask_t mask) inline static
Reset multiple pin modes in a specified IOPORT port to defaults.
Parameters
port IOPORT port to configure
mask Mask of pins whose mode configuration is to be reset
Definition at line 228 of file ioport.h.
{
    arch_ioport_set_port_mode(port, mask, 0);
}
References arch_ioport_set_port_mode().
ioport_set_pin_dir()
static void ioport_set_pin_dir (ioport_pin_t pin, enum ioport_direction dir) inline static
Set direction for a single IOPORT pin.
Parameters
pin IOPORT pin to configure
dir Direction to set for the specified pin (ioport_direction)
Definition at line 263 of file ioport.h.
{
    arch_ioport_set_pin_dir(pin, dir);
}
References arch_ioport_set_pin_dir().
Referenced by board_init(), init_chip_pins(), main(), nm_bus_deinit(), and nm_bus_init().
ioport_set_pin_level()
static void ioport_set_pin_level (ioport_pin_t pin, bool level) inline static
Set an IOPORT pin to a specified logical value.
Parameters
pin IOPORT pin to configure
level Logical value of the pin
Definition at line 275 of file ioport.h.
{
    arch_ioport_set_pin_level(pin, level);
}
References arch_ioport_set_pin_level().
Referenced by board_init(), init_chip_pins(), nm_bsp_deinit(), and nm_bsp_reset().
ioport_set_pin_mode()
static void ioport_set_pin_mode (ioport_pin_t pin, ioport_mode_t mode) inline static
Set pin mode for one single IOPORT pin.
Parameters
pin IOPORT pin to configure
mode Mode masks to configure for the specified pin (IOPORT Modes)
Definition at line 217 of file ioport.h.
{
    arch_ioport_set_pin_mode(pin, mode);
}
References arch_ioport_set_pin_mode().
Referenced by board_init(), main(), and nm_bus_init().
ioport_set_pin_sense_mode()
static void ioport_set_pin_sense_mode (ioport_pin_t pin, enum ioport_sense pin_sense) inline static
Set the pin sense mode of a single IOPORT pin.
Parameters
pin IOPORT pin to configure
pin_sense Edge to sense for the pin (ioport_sense)
Definition at line 350 of file ioport.h.
{
    arch_ioport_set_pin_sense_mode(pin, pin_sense);
}
References arch_ioport_set_pin_sense_mode().
ioport_set_port_dir()
static void ioport_set_port_dir (ioport_port_t port, ioport_port_mask_t mask, enum ioport_direction dir) inline static
Set I/O direction for a group of pins in a single IOPORT.
Parameters
port IOPORT port to configure
mask Pin mask of pins to configure
dir Direction to set for the specified pins (ioport_direction)
Definition at line 251 of file ioport.h.
{
    arch_ioport_set_port_dir(port, mask, dir);
}
References arch_ioport_set_port_dir().
ioport_set_port_level()
static void ioport_set_port_level (ioport_port_t port, ioport_port_mask_t mask, enum ioport_value level) inline static
Set a group of IOPORT pins in a single port to a specified logical value.
Parameters
port IOPORT port to write to
mask Pin mask of pins to modify
level Level of the pins to be modified
Definition at line 288 of file ioport.h.
{
    arch_ioport_set_port_level(port, mask, level);
}
References arch_ioport_set_port_level().
ioport_set_port_mode()
static void ioport_set_port_mode (ioport_port_t port, ioport_port_mask_t mask, ioport_mode_t mode) inline static
Set multiple pin modes in a single IOPORT port, such as pull-up, pull-down, etc.
configuration.
Parameters
port IOPORT port to configure
mask Pin mask of pins to configure
mode Mode masks to configure for the specified pins (IOPORT Modes)
Definition at line 205 of file ioport.h.
{
    arch_ioport_set_port_mode(port, mask, mode);
}
References arch_ioport_set_port_mode().
ioport_set_port_sense_mode()
static void ioport_set_port_sense_mode (ioport_port_t port, ioport_port_mask_t mask, enum ioport_sense pin_sense) inline static
Set the pin sense mode of a multiple IOPORT pins on a single port.
Parameters
port IOPORT port to configure
mask Bitmask if pins whose edge sense is to be configured
pin_sense Edge to sense for the pins (ioport_sense)
Definition at line 363 of file ioport.h.
{
    arch_ioport_set_port_sense_mode(port, mask, pin_sense);
}
References arch_ioport_set_port_sense_mode().
ioport_toggle_pin_level()
static void ioport_toggle_pin_level (ioport_pin_t pin) inline static
Toggle the value of an IOPORT pin, which has previously configured as an output.
Parameters
pin IOPORT pin to toggle
Definition at line 327 of file ioport.h.
{
    arch_ioport_toggle_pin_level(pin);
}
References arch_ioport_toggle_pin_level().
ioport_toggle_port_level()
static void ioport_toggle_port_level (ioport_port_t port, ioport_port_mask_t mask) inline static
Toggle the values of several IOPORT pins located in a single port.
Parameters
port IOPORT port to modify
mask Pin mask of pins to toggle
Definition at line 338 of file ioport.h.
{
    arch_ioport_toggle_port_level(port, mask);
}
References arch_ioport_toggle_port_level().