WINC1500 Weather Client Demo for SAME70 Xplained: System Time
System Time
WLAN » Functions
Here are listed all the functions that implement the System Time APIs.
Functions
sint8 m2m_wifi_configure_sntp (uint8 *pu8NTPServerName, uint8 u8NTPServerNameLength, tenuSNTPUseDHCP useDHCP)
Configures what NTP server the SNTP client should use.
sint8 m2m_wifi_enable_sntp (uint8 bEnable)
Synchronous function to enable/disable the native Simple Network Time Protocol(SNTP) client in the WINC15x0 firmware.
sint8 m2m_wifi_get_system_time (void)
Asynchronous API to obtain the system time in use by the WINC IC.
sint8 m2m_wifi_set_system_time (uint32 u32UTCSeconds)
Function for setting the system time within the WINC IC.
Detailed Description
Here are listed all the functions that implement the System Time APIs.
Function Documentation
m2m_wifi_configure_sntp()
NMI_API sint8 m2m_wifi_configure_sntp (uint8 * pu8NTPServerName, uint8 u8NTPServerNameLength, tenuSNTPUseDHCP useDHCP)
Configures what NTP server the SNTP client should use.
Parameters
[in] pu8NTPServerName Buffer holding the NTP server name. If the first character is an asterisk (*) then it will be treated as a server pool, where the asterisk will be replaced with an incrementing value from 0 to 3 each time a server fails (example: *.pool.ntp.org).
[in] u8NTPServerNameLength Length of the NTP server name. Should not exceed the maximum NTP server name length of M2M_NTP_MAX_SERVER_NAME_LENGTH
[in] useDHCP Should the NTP server provided by the DHCP server be used.
Returns
The function SHALL return M2M_SUCCESS for success and a negative value otherwise.
Configures what NTP server the SNTP client should use. Only 1 server name can be provided, if the configured server name begins with an asterisk then it will be treated as a server pool. The SNTP client can also use the NTP server provided by the DHCP server through option 42. By default the NTP server provided by DHCP will be tried first, then the built-in default NTP server (time.nist.gov) will be used.
Parameters
[in] pu8NTPServerName Buffer holding the NTP server name. If the first character is an asterisk (*) then it will be treated as a server pool, where the asterisk will be replaced with an incrementing value from 0 to 3 each time a server fails (example: *.pool.ntp.org).
[in] u8NTPServerNameLength Length of the NTP server name. Should not exceed the maximum NTP server name length of M2M_NTP_MAX_SERVER_NAME_LENGTH.
[in] useDHCP Explicity tell the WINC if it should use the NTP server provided by the DHCP server or not.
Warning
SNTP should be configured before the connection takes place. If SNTP is configured after the device connects to a network, the new configuration can take a minimum of 24h to be applied. However, it can take even longer since it is triggered by DHCP renewal. Currently there is also a known issue in which if the WINC obtains the NTP server from DHCP and then connects to a different network, it will still use the NTP from the previous network. Configuring a server name will overwrite the built-in default server until next reboot.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
Definition at line 1696 of file m2m_wifi.c.
{
    tstrM2MSNTPConfig strSNTPConfig;
    if(u8NTPServerNameLength > M2M_NTP_MAX_SERVER_NAME_LENGTH)
        return M2M_ERR_FAIL;
    m2m_memcpy((uint8*)strSNTPConfig.acNTPServer, pu8NTPServerName, u8NTPServerNameLength);
    strSNTPConfig.acNTPServer[u8NTPServerNameLength] = '\0';
    strSNTPConfig.enuUseDHCP = useDHCP;
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CONFIG_SNTP,
        (uint8*)&strSNTPConfig, sizeof(tstrM2MSNTPConfig), NULL, 0,0);
}
References tstrM2MSNTPConfig::acNTPServer, tstrM2MSNTPConfig::enuUseDHCP, hif_send(), M2M_ERR_FAIL, m2m_memcpy(), M2M_NTP_MAX_SERVER_NAME_LENGTH, M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_CONFIG_SNTP, and NULL.
m2m_wifi_enable_sntp()
NMI_API sint8 m2m_wifi_enable_sntp (uint8 bEnable)
Synchronous function to enable/disable the native Simple Network Time Protocol(SNTP) client in the WINC15x0 firmware.
The SNTP is enabled by default at start-up.The SNTP client at firmware is used to synchronize the system clock to the UTC time from the well known time servers (e.g. "time-c.nist.gov"). The SNTP client uses a default update cycle of 1 day.
The UTC is important for checking the expiration date of X509 certificates used while establishing TLS (Transport Layer Security) connections.
It is highly recommended to use it if there is no other means to get the UTC time. If there is a RTC on the host MCU, the SNTP could be disabled and the host should set the system time to the firmware using the m2m_wifi_set_system_time function.
Parameters
[in] bEnable Enables or disables the SNTP service '0' :disable SNTP '1' :enable SNTP
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
m2m_wifi_set_system_time
Definition at line 1800 of file m2m_wifi.c.
{
    uint8   u8Req;
    u8Req = bEnable ? M2M_WIFI_REQ_ENABLE_SNTP_CLIENT : M2M_WIFI_REQ_DISABLE_SNTP_CLIENT;
    return hif_send(M2M_REQ_GROUP_WIFI, u8Req, NULL, 0, NULL, 0, 0);
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_DISABLE_SNTP_CLIENT, M2M_WIFI_REQ_ENABLE_SNTP_CLIENT, and NULL.
m2m_wifi_get_system_time()
NMI_API sint8 m2m_wifi_get_system_time (void)
Asynchronous API to obtain the system time in use by the WINC IC.
See also
m2m_wifi_enable_sntp tstrSystemTime
Note
get the system time from the sntp client using the API m2m_wifi_get_system_time.
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Asynchronous function used to retrieve the system time through the use of the response M2M_WIFI_RESP_GET_SYS_TIME. Response time retrieved is parsed into the members defined in the structure tstrSystemTime.
Note
Get the system time from the SNTP client using the API m2m_wifi_get_system_time.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
m2m_wifi_enable_sntp tstrSystemTime
Definition at line 1795 of file m2m_wifi.c.
{
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_GET_SYS_TIME, NULL,0, NULL, 0, 0);
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_GET_SYS_TIME, and NULL.
m2m_wifi_set_system_time()
NMI_API sint8 m2m_wifi_set_system_time (uint32 u32UTCSeconds)
Function for setting the system time within the WINC IC.
Synchronous function for setting the system time in time/date format (uint32). The tstrSystemTime structure can be used as a reference to the time values that should be set and pass its value as uint32.
Parameters
[in] u32UTCSeconds Seconds elapsed since January 1, 1900 (NTP Timestamp).
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
m2m_wifi_enable_sntp tstrSystemTime
Note
If there is an RTC on the host MCU, the SNTP may be disabled and the host may set the system time within the firmware using the API m2m_wifi_set_system_time.
Definition at line 1780 of file m2m_wifi.c.
{
    /*
        The firmware accepts timestamps relative to 1900 like NTP Timestamp.
    */
    return hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_SYS_TIME, (uint8*)&u32UTCSeconds, sizeof(tstrSystemTime), NULL, 0, 0);
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_SYS_TIME, and NULL.