WINC1500 Weather Client Demo for SAME70 Xplained: Embedded Flash Service
Embedded Flash Service
The Embedded Flash service provides functions for internal flash operations.
Macros
#define GPNVM_NUM_MAX 2
Functions
static void compute_address (Efc *p_efc, uint16_t us_page, uint16_t us_offset, uint32_t *pul_addr)
Compute the address of a flash by the given page and offset.
static void compute_lock_range (uint32_t ul_start, uint32_t ul_end, uint32_t *pul_actual_start, uint32_t *pul_actual_end)
Compute the lock range associated with the given address range.
uint32_t flash_clear_gpnvm (uint32_t ul_gpnvm)
Clear the given GPNVM bit.
uint32_t flash_enable_security_bit (void)
Set security bit.
uint32_t flash_erase_all (uint32_t ul_address)
Erase the entire flash.
uint32_t flash_get_descriptor (uint32_t ul_address, uint32_t *pul_flash_descriptor, uint32_t ul_size)
Get flash descriptor.
uint32_t flash_get_page_count (const uint32_t *pul_flash_descriptor)
Get flash total page count for the specified bank.
uint32_t flash_get_page_count_per_region (const uint32_t *pul_flash_descriptor)
Get flash page count per region (plane) for the specified bank.
uint32_t flash_get_region_count (const uint32_t *pul_flash_descriptor)
Get flash region (plane) count for the specified bank.
uint32_t flash_get_wait_state (uint32_t ul_address)
Get flash wait state.
uint32_t flash_init (uint32_t ul_mode, uint32_t ul_fws)
Initialize the flash service.
uint32_t flash_is_gpnvm_set (uint32_t ul_gpnvm)
Check if the given GPNVM bit is set or not.
uint32_t flash_is_locked (uint32_t ul_start, uint32_t ul_end)
Get the number of locked regions inside the given address range.
uint32_t flash_is_security_bit_enabled (void)
Check if the security bit is set or not.
uint32_t flash_lock (uint32_t ul_start, uint32_t ul_end, uint32_t *pul_actual_start, uint32_t *pul_actual_end)
Lock all the regions in the given address range.
uint32_t flash_read_unique_id (uint32_t *pul_data, uint32_t ul_size)
Read the flash unique ID.
uint32_t flash_set_gpnvm (uint32_t ul_gpnvm)
Set the given GPNVM bit.
uint32_t flash_set_wait_state (uint32_t ul_address, uint32_t ul_fws)
Set flash wait state.
uint32_t flash_set_wait_state_adaptively (uint32_t ul_address)
Set flash wait state.
uint32_t flash_unlock (uint32_t ul_start, uint32_t ul_end, uint32_t *pul_actual_start, uint32_t *pul_actual_end)
Unlock all the regions in the given address range.
uint32_t flash_write (uint32_t ul_address, const void *p_buffer, uint32_t ul_size, uint32_t ul_erase_flag)
Write a data buffer on flash.
static void translate_address (Efc **pp_efc, uint32_t ul_addr, uint16_t *pus_page, uint16_t *pus_offset)
Translate the given flash address to page and offset values.
Variables
static uint32_t gs_ul_page_buffer [IFLASH_PAGE_SIZE/sizeof(uint32_t)]
Detailed Description
The Embedded Flash service provides functions for internal flash operations.
Macro Definition Documentation
GPNVM_NUM_MAX
#define GPNVM_NUM_MAX 2
Definition at line 122 of file flash_efc.c.
Function Documentation
compute_address()
static void compute_address (Efc * p_efc, uint16_t us_page, uint16_t us_offset, uint32_t * pul_addr) static
Compute the address of a flash by the given page and offset.
Parameters
p_efc Pointer to an EFC instance.
us_page Page number.
us_offset Byte offset inside page.
pul_addr Computed address (optional).
Definition at line 226 of file flash_efc.c.
{
    uint32_t ul_addr;
/* Dual bank flash */
#ifdef EFC1
    /* Compute address */
#if (SAM4SD16 || SAM4SD32 || SAM4C32 || SAM4CMP32 || SAM4CMS32)
    uint32_t uc_gpnvm2;
    uc_gpnvm2 = flash_is_gpnvm_set(2);
    if (p_efc == EFC0) {
        if(uc_gpnvm2 == FLASH_RC_YES) {
            ul_addr = IFLASH1_ADDR + us_page * IFLASH_PAGE_SIZE + us_offset;
        } else {
            ul_addr = IFLASH0_ADDR + us_page * IFLASH_PAGE_SIZE + us_offset;
        }
    } else {
        if(uc_gpnvm2 == FLASH_RC_YES) {
            ul_addr = IFLASH0_ADDR + us_page * IFLASH_PAGE_SIZE + us_offset;
        } else {
            ul_addr = IFLASH1_ADDR + us_page * IFLASH_PAGE_SIZE + us_offset;
        }
    }
#else
    ul_addr = (p_efc == EFC0) ?
            IFLASH0_ADDR + us_page * IFLASH_PAGE_SIZE + us_offset :
            IFLASH1_ADDR + us_page * IFLASH_PAGE_SIZE + us_offset;
#endif
/* One bank flash */
#else
    /* avoid Cppcheck Warning */
    UNUSED(p_efc);
    /* Compute address */
    ul_addr = IFLASH_ADDR + us_page * IFLASH_PAGE_SIZE + us_offset;
#endif
    /* Store result */
    if (pul_addr != NULL) {
        *pul_addr = ul_addr;
    }
}
References flash_is_gpnvm_set(), FLASH_RC_YES, IFLASH_ADDR, IFLASH_PAGE_SIZE, NULL, and UNUSED.
Referenced by flash_write().
compute_lock_range()
static void compute_lock_range (uint32_t ul_start, uint32_t ul_end, uint32_t * pul_actual_start, uint32_t * pul_actual_end) static
Compute the lock range associated with the given address range.
Parameters
ul_start Start address of lock range.
ul_end End address of lock range.
pul_actual_start Actual start address of lock range.
pul_actual_end Actual end address of lock range.
Definition at line 277 of file flash_efc.c.
{
    uint32_t ul_actual_start, ul_actual_end;
    ul_actual_start = ul_start - (ul_start % IFLASH_LOCK_REGION_SIZE);
    ul_actual_end = ul_end - (ul_end % IFLASH_LOCK_REGION_SIZE) +
            IFLASH_LOCK_REGION_SIZE - 1;
    if (pul_actual_start) {
        *pul_actual_start = ul_actual_start;
    }
    if (pul_actual_end) {
        *pul_actual_end = ul_actual_end;
    }
}
References IFLASH_LOCK_REGION_SIZE.
Referenced by flash_lock(), and flash_unlock().
flash_clear_gpnvm()
uint32_t flash_clear_gpnvm (uint32_t ul_gpnvm)
Clear the given GPNVM bit.
Parameters
ul_gpnvm GPNVM bit index.
Returns
0 if successful; otherwise returns an error code.
Definition at line 884 of file flash_efc.c.
{
    if (ul_gpnvm >= GPNVM_NUM_MAX) {
        return FLASH_RC_INVALID;
    }
    if (FLASH_RC_NO == flash_is_gpnvm_set(ul_gpnvm)) {
        return FLASH_RC_OK;
    }
    if (EFC_RC_OK == efc_perform_command(EFC, EFC_FCMD_CGPB, ul_gpnvm)) {
        return FLASH_RC_OK;
    }
    return FLASH_RC_ERROR;
}
References EFC, EFC_FCMD_CGPB, efc_perform_command(), EFC_RC_OK, flash_is_gpnvm_set(), FLASH_RC_ERROR, FLASH_RC_INVALID, FLASH_RC_NO, FLASH_RC_OK, and GPNVM_NUM_MAX.
flash_enable_security_bit()
uint32_t flash_enable_security_bit (void)
Set security bit.
Returns
0 if successful; otherwise returns an error code.
Definition at line 935 of file flash_efc.c.
{
    return flash_set_gpnvm(0);
}
References flash_set_gpnvm().
flash_erase_all()
uint32_t flash_erase_all (uint32_t ul_address)
Erase the entire flash.
Note
Only the flash bank including ul_address will be erased. If there are two flash banks, we need to call this function twice with each bank start address.
Parameters
ul_address Flash bank start address.
Returns
0 if successful; otherwise returns an error code.
Definition at line 485 of file flash_efc.c.
{
    Efc *p_efc;
    translate_address(&p_efc, ul_address, NULL, NULL);
    if (EFC_RC_OK != efc_perform_command(p_efc, EFC_FCMD_EA, 0)) {
        return FLASH_RC_ERROR;
    }
    return FLASH_RC_OK;
}
References EFC_FCMD_EA, efc_perform_command(), EFC_RC_OK, FLASH_RC_ERROR, FLASH_RC_OK, NULL, and translate_address().
flash_get_descriptor()
uint32_t flash_get_descriptor (uint32_t ul_address, uint32_t * pul_flash_descriptor, uint32_t ul_size)
Get flash descriptor.
Parameters
ul_address Flash bank start address.
pul_flash_descriptor Pointer to a data buffer to store flash descriptor.
ul_size Data buffer size in DWORD.
Returns
The actual descriptor length.
Definition at line 402 of file flash_efc.c.
{
    Efc *p_efc;
    uint32_t ul_tmp;
    uint32_t ul_cnt;
    translate_address(&p_efc, ul_address, NULL, NULL);
    /* Command fails */
    if (FLASH_RC_OK != efc_perform_command(p_efc, EFC_FCMD_GETD, 0)) {
        return 0;
    } else {
        /* Read until no result */
        for (ul_cnt = 0;; ul_cnt++) {
            ul_tmp = efc_get_result(p_efc);
            if ((ul_size > ul_cnt) && (ul_tmp != 0)) {
                *pul_flash_descriptor++ = ul_tmp;
            } else {
                break;
            }
        }
    }
    return ul_cnt;
}
References EFC_FCMD_GETD, efc_get_result(), efc_perform_command(), FLASH_RC_OK, NULL, and translate_address().
flash_get_page_count()
uint32_t flash_get_page_count (const uint32_t * pul_flash_descriptor)
Get flash total page count for the specified bank.
Note
The flash descriptor must be fetched from flash_get_descriptor function first.
Parameters
pul_flash_descriptor Pointer to a flash descriptor.
Returns
The flash total page count.
Definition at line 439 of file flash_efc.c.
{
    return (pul_flash_descriptor[1] / pul_flash_descriptor[2]);
}
flash_get_page_count_per_region()
uint32_t flash_get_page_count_per_region (const uint32_t * pul_flash_descriptor)
Get flash page count per region (plane) for the specified bank.
Note
The flash descriptor must be fetched from flash_get_descriptor function first.
Parameters
pul_flash_descriptor Pointer to a flash descriptor.
Returns
The flash page count per region (plane).
Definition at line 454 of file flash_efc.c.
{
    return (pul_flash_descriptor[4] / pul_flash_descriptor[2]);
}
flash_get_region_count()
uint32_t flash_get_region_count (const uint32_t * pul_flash_descriptor)
Get flash region (plane) count for the specified bank.
Note
The flash descriptor must be fetched from flash_get_descriptor function first.
Parameters
pul_flash_descriptor Pointer to a flash descriptor.
Returns
The flash region (plane) count.
Definition at line 469 of file flash_efc.c.
{
    return (pul_flash_descriptor[3]);
}
flash_get_wait_state()
uint32_t flash_get_wait_state (uint32_t ul_address)
Get flash wait state.
Parameters
ul_address Flash bank start address.
Returns
The number of wait states in cycle (no shift).
Definition at line 385 of file flash_efc.c.
{
    Efc *p_efc;
    translate_address(&p_efc, ul_address, NULL, NULL);
    return efc_get_wait_state(p_efc);
}
References efc_get_wait_state(), NULL, and translate_address().
flash_init()
uint32_t flash_init (uint32_t ul_mode, uint32_t ul_fws)
Initialize the flash service.
Parameters
ul_mode FLASH_ACCESS_MODE_128 or FLASH_ACCESS_MODE_64.
ul_fws The number of wait states in cycle (no shift).
Returns
0 if successful; otherwise returns an error code.
Definition at line 303 of file flash_efc.c.
{
    efc_init(EFC, ul_mode, ul_fws);
#ifdef EFC1
    efc_init(EFC1, ul_mode, ul_fws);
#endif
    return FLASH_RC_OK;
}
References EFC, efc_init(), and FLASH_RC_OK.
Referenced by wifi_connect().
flash_is_gpnvm_set()
uint32_t flash_is_gpnvm_set (uint32_t ul_gpnvm)
Check if the given GPNVM bit is set or not.
Parameters
ul_gpnvm GPNVM bit index.
Return values
1 If the given GPNVM bit is currently set.
0 If the given GPNVM bit is currently cleared. otherwise returns an error code.
Definition at line 910 of file flash_efc.c.
{
    uint32_t ul_gpnvm_bits;
    if (ul_gpnvm >= GPNVM_NUM_MAX) {
        return FLASH_RC_INVALID;
    }
    if (EFC_RC_OK != efc_perform_command(EFC, EFC_FCMD_GGPB, 0)) {
        return FLASH_RC_ERROR;
    }
    ul_gpnvm_bits = efc_get_result(EFC);
    if (ul_gpnvm_bits & (1 << ul_gpnvm)) {
        return FLASH_RC_YES;
    }
    return FLASH_RC_NO;
}
References EFC, EFC_FCMD_GGPB, efc_get_result(), efc_perform_command(), EFC_RC_OK, FLASH_RC_ERROR, FLASH_RC_INVALID, FLASH_RC_NO, FLASH_RC_YES, and GPNVM_NUM_MAX.
Referenced by compute_address(), flash_clear_gpnvm(), flash_is_security_bit_enabled(), flash_set_gpnvm(), and translate_address().
flash_is_locked()
uint32_t flash_is_locked (uint32_t ul_start, uint32_t ul_end)
Get the number of locked regions inside the given address range.
Parameters
ul_start Start address of range
ul_end End address of range.
Returns
The number of locked regions inside the given address range.
Definition at line 783 of file flash_efc.c.
{
    Efc *p_efc;
    uint16_t us_start_page, us_end_page;
    uint8_t uc_start_region, uc_end_region;
    uint16_t us_num_pages_in_region;
    uint32_t ul_status;
    uint32_t ul_error;
    uint32_t ul_num_locked_regions = 0;
    uint32_t ul_count = 0;
    uint32_t ul_bit = 0;
    Assert(ul_end >= ul_start);
#ifdef EFC1
    Assert(((ul_start >= IFLASH0_ADDR)
                && (ul_end <= IFLASH0_ADDR + IFLASH0_SIZE))
                || ((ul_start >= IFLASH1_ADDR)
                    && (ul_end <= IFLASH1_ADDR + IFLASH1_SIZE)));
#else
    Assert((ul_start >= IFLASH_ADDR)
                && (ul_end <= IFLASH_ADDR + IFLASH_SIZE));
#endif
    /* Compute page numbers */
    translate_address(&p_efc, ul_start, &us_start_page, 0);
    translate_address(0, ul_end, &us_end_page, 0);
    /* Compute region numbers */
    us_num_pages_in_region = IFLASH_LOCK_REGION_SIZE / IFLASH_PAGE_SIZE;
    uc_start_region = us_start_page / us_num_pages_in_region;
    uc_end_region = us_end_page / us_num_pages_in_region;
    /* Retrieve lock status */
    ul_error = efc_perform_command(p_efc, EFC_FCMD_GLB, 0);
    if (ul_error) {
        return ul_error;
    }
    UNUSED(ul_error);
    /* Skip unrequested regions (if necessary) */
    ul_status = efc_get_result(p_efc);
    while (!(ul_count <= uc_start_region &&
            uc_start_region < (ul_count + 32))) {
        ul_status = efc_get_result(p_efc);
        ul_count += 32;
    }
    /* Check status of each involved region */
    ul_bit = uc_start_region - ul_count;
    /* Number of region to check (must be > 0) */
    ul_count = uc_end_region - uc_start_region + 1;
    while (ul_count > 0) {
        if (ul_status & (1 << (ul_bit))) {
            ul_num_locked_regions++;
        }
        ul_count -= 1;
        ul_bit += 1;
        if (ul_bit == 32) {
            ul_status = efc_get_result(p_efc);
            ul_bit = 0;
        }
    }
    return ul_num_locked_regions;
}
References Assert, EFC_FCMD_GLB, efc_get_result(), efc_perform_command(), IFLASH_ADDR, IFLASH_LOCK_REGION_SIZE, IFLASH_PAGE_SIZE, IFLASH_SIZE, translate_address(), and UNUSED.
flash_is_security_bit_enabled()
uint32_t flash_is_security_bit_enabled (void)
Check if the security bit is set or not.
Return values
1 If the security bit is currently set.
0 If the security bit is currently cleared. otherwise returns an error code.
Definition at line 947 of file flash_efc.c.
{
    return flash_is_gpnvm_set(0);
}
References flash_is_gpnvm_set().
flash_lock()
uint32_t flash_lock (uint32_t ul_start, uint32_t ul_end, uint32_t * pul_actual_start, uint32_t * pul_actual_end)
Lock all the regions in the given address range.
The actual lock range is reported through two output parameters.
Parameters
ul_start Start address of lock range.
ul_end End address of lock range.
pul_actual_start Start address of the actual lock range (optional).
pul_actual_end End address of the actual lock range (optional).
Returns
0 if successful, otherwise returns an error code.
Definition at line 690 of file flash_efc.c.
{
    Efc *p_efc;
    uint32_t ul_actual_start, ul_actual_end;
    uint16_t us_start_page, us_end_page;
    uint32_t ul_error;
    uint16_t us_num_pages_in_region =
            IFLASH_LOCK_REGION_SIZE / IFLASH_PAGE_SIZE;
    /* Compute actual lock range and store it */
    compute_lock_range(ul_start, ul_end, &ul_actual_start, &ul_actual_end);
    if (pul_actual_start != NULL) {
        *pul_actual_start = ul_actual_start;
    }
    if (pul_actual_end != NULL) {
        *pul_actual_end = ul_actual_end;
    }
    /* Compute page numbers */
    translate_address(&p_efc, ul_actual_start, &us_start_page, 0);
    translate_address(0, ul_actual_end, &us_end_page, 0);
    /* Lock all pages */
    while (us_start_page < us_end_page) {
        ul_error = efc_perform_command(p_efc, EFC_FCMD_SLB, us_start_page);
        if (ul_error) {
            return ul_error;
        }
        us_start_page += us_num_pages_in_region;
    }
    return FLASH_RC_OK;
}
References compute_lock_range(), EFC_FCMD_SLB, efc_perform_command(), FLASH_RC_OK, IFLASH_LOCK_REGION_SIZE, IFLASH_PAGE_SIZE, NULL, and translate_address().
flash_read_unique_id()
uint32_t flash_read_unique_id (uint32_t * pul_data, uint32_t ul_size)
Read the flash unique ID.
Parameters
pul_data Pointer to a data buffer to store 128-bit unique ID.
ul_size Data buffer size in DWORD.
Returns
0 if successful; otherwise returns an error code.
Definition at line 960 of file flash_efc.c.
{
    uint32_t uid_buf[4];
    uint32_t ul_idx;
    if (FLASH_RC_OK != efc_perform_read_sequence(EFC, EFC_FCMD_STUI,
            EFC_FCMD_SPUI, uid_buf, 4)) {
        return FLASH_RC_ERROR;
    }
    if (ul_size > 4) {
        /* Only 4 dword to store unique ID */
        ul_size = 4;
    }
    for (ul_idx = 0; ul_idx < ul_size; ul_idx++) {
        pul_data[ul_idx] = uid_buf[ul_idx];
    }
    return FLASH_RC_OK;
}
References EFC, EFC_FCMD_SPUI, EFC_FCMD_STUI, efc_perform_read_sequence(), FLASH_RC_ERROR, and FLASH_RC_OK.
flash_set_gpnvm()
uint32_t flash_set_gpnvm (uint32_t ul_gpnvm)
Set the given GPNVM bit.
Parameters
ul_gpnvm GPNVM bit index.
Returns
0 if successful; otherwise returns an error code.
Definition at line 860 of file flash_efc.c.
{
    if (ul_gpnvm >= GPNVM_NUM_MAX) {
        return FLASH_RC_INVALID;
    }
    if (FLASH_RC_YES == flash_is_gpnvm_set(ul_gpnvm)) {
        return FLASH_RC_OK;
    }
    if (EFC_RC_OK == efc_perform_command(EFC, EFC_FCMD_SGPB, ul_gpnvm)) {
        return FLASH_RC_OK;
    }
    return FLASH_RC_ERROR;
}
References EFC, EFC_FCMD_SGPB, efc_perform_command(), EFC_RC_OK, flash_is_gpnvm_set(), FLASH_RC_ERROR, FLASH_RC_INVALID, FLASH_RC_OK, FLASH_RC_YES, and GPNVM_NUM_MAX.
Referenced by flash_enable_security_bit().
flash_set_wait_state()
uint32_t flash_set_wait_state (uint32_t ul_address, uint32_t ul_fws)
Set flash wait state.
Parameters
ul_address Flash bank start address.
ul_fws The number of wait states in cycle (no shift).
Returns
0 if successful; otherwise returns an error code.
Definition at line 322 of file flash_efc.c.
{
    Efc *p_efc;
    translate_address(&p_efc, ul_address, NULL, NULL);
    efc_set_wait_state(p_efc, ul_fws);
    return FLASH_RC_OK;
}
References efc_set_wait_state(), FLASH_RC_OK, NULL, and translate_address().
flash_set_wait_state_adaptively()
uint32_t flash_set_wait_state_adaptively (uint32_t ul_address)
Set flash wait state.
Parameters
ul_address Flash bank start address.
ul_fws The number of wait states in cycle (no shift).
Returns
0 if successful; otherwise returns an error code.
Definition at line 340 of file flash_efc.c.
{
    Efc *p_efc;
    uint32_t clock = sysclk_get_cpu_hz();
    translate_address(&p_efc, ul_address, NULL, NULL);
    /* Set FWS for embedded Flash access according to operating frequency */
    if (clock < CHIP_FREQ_FWS_0) {
        efc_set_wait_state(p_efc, 0);
    } else if (clock < CHIP_FREQ_FWS_1) {
        efc_set_wait_state(p_efc, 1);
    } else if (clock < CHIP_FREQ_FWS_2) {
        efc_set_wait_state(p_efc, 2);
#if (SAM3XA || SAM3U)
    } else if (clock < CHIP_FREQ_FWS_3) {
        efc_set_wait_state(p_efc, 3);
    } else {
        efc_set_wait_state(p_efc, 4);
    }
#elif (SAM4S || SAM4E || SAM4N || SAM4C || SAM4CP || SAM4CM || \
     SAMV71 || SAMV70 || SAMS70 || SAME70)
    } else if (clock < CHIP_FREQ_FWS_3) {
        efc_set_wait_state(p_efc, 3);
    } else if (clock < CHIP_FREQ_FWS_4) {
        efc_set_wait_state(p_efc, 4);
    } else {
        efc_set_wait_state(p_efc, 5);
    }
#else
    } else {
        efc_set_wait_state(p_efc, 3);
    }
#endif
    return FLASH_RC_OK;
}
References CHIP_FREQ_FWS_0, CHIP_FREQ_FWS_1, CHIP_FREQ_FWS_2, CHIP_FREQ_FWS_3, efc_set_wait_state(), NULL, sysclk_get_cpu_hz(), and translate_address().
flash_unlock()
uint32_t flash_unlock (uint32_t ul_start, uint32_t ul_end, uint32_t * pul_actual_start, uint32_t * pul_actual_end)
Unlock all the regions in the given address range.
The actual unlock range is reported through two output parameters.
Parameters
ul_start Start address of unlock range.
ul_end End address of unlock range.
pul_actual_start Start address of the actual unlock range (optional).
pul_actual_end End address of the actual unlock range (optional).
Returns
0 if successful, otherwise returns an error code.
Definition at line 739 of file flash_efc.c.
{
    Efc *p_efc;
    uint32_t ul_actual_start, ul_actual_end;
    uint16_t us_start_page, us_end_page;
    uint32_t ul_error;
    uint16_t us_num_pages_in_region =
            IFLASH_LOCK_REGION_SIZE / IFLASH_PAGE_SIZE;
    /* Compute actual unlock range and store it */
    compute_lock_range(ul_start, ul_end, &ul_actual_start, &ul_actual_end);
    if (pul_actual_start != NULL) {
        *pul_actual_start = ul_actual_start;
    }
    if (pul_actual_end != NULL) {
        *pul_actual_end = ul_actual_end;
    }
    /* Compute page numbers */
    translate_address(&p_efc, ul_actual_start, &us_start_page, 0);
    translate_address(0, ul_actual_end, &us_end_page, 0);
    /* Unlock all pages */
    while (us_start_page < us_end_page) {
        ul_error = efc_perform_command(p_efc, EFC_FCMD_CLB,
                us_start_page);
        if (ul_error) {
            return ul_error;
        }
        us_start_page += us_num_pages_in_region;
    }
    return FLASH_RC_OK;
}
References compute_lock_range(), EFC_FCMD_CLB, efc_perform_command(), FLASH_RC_OK, IFLASH_LOCK_REGION_SIZE, IFLASH_PAGE_SIZE, NULL, and translate_address().
Referenced by wifi_connect().
flash_write()
uint32_t flash_write (uint32_t ul_address, const void * p_buffer, uint32_t ul_size, uint32_t ul_erase_flag)
Write a data buffer on flash.
Note
This function works in polling mode, and thus only returns when the data has been effectively written.
For dual bank flash, this function doesn't support cross write from bank 0 to bank 1. In this case, flash_write must be called twice (ie for each bank).
Parameters
ul_address Write address.
p_buffer Data buffer.
ul_size Size of data buffer in bytes.
ul_erase_flag Flag to set if erase first.
Returns
0 if successful, otherwise returns an error code.
Definition at line 597 of file flash_efc.c.
{
    Efc *p_efc;
    uint32_t ul_fws_temp;
    uint16_t us_page;
    uint16_t us_offset;
    uint32_t writeSize;
    uint32_t ul_page_addr;
    uint16_t us_padding;
    uint32_t ul_error;
    uint32_t ul_idx;
    uint32_t *p_aligned_dest;
    uint8_t *puc_page_buffer = (uint8_t *) gs_ul_page_buffer;
    translate_address(&p_efc, ul_address, &us_page, &us_offset);
#if SAM3S || SAM3N || SAM3XA || SAM3U
    /* According to the errata, set the wait state value to 6. */
    ul_fws_temp = efc_get_wait_state(p_efc);
    efc_set_wait_state(p_efc, 6);
#else
    UNUSED(ul_fws_temp);
#endif
    /* Write all pages */
    while (ul_size > 0) {
        /* Copy data in temporary buffer to avoid alignment problems. */
        writeSize = Min((uint32_t) IFLASH_PAGE_SIZE - us_offset,
                ul_size);
        compute_address(p_efc, us_page, 0, &ul_page_addr);
        us_padding = IFLASH_PAGE_SIZE - us_offset - writeSize;
        /* Pre-buffer data */
        memcpy(puc_page_buffer, (void *)ul_page_addr, us_offset);
        /* Buffer data */
        memcpy(puc_page_buffer + us_offset, p_buffer, writeSize);
        /* Post-buffer data */
        memcpy(puc_page_buffer + us_offset + writeSize,
                (void *)(ul_page_addr + us_offset + writeSize),
                us_padding);
        /* Write page.
         * Writing 8-bit and 16-bit data is not allowed and may lead to
         * unpredictable data corruption.
         */
        p_aligned_dest = (uint32_t *) ul_page_addr;
        for (ul_idx = 0; ul_idx < (IFLASH_PAGE_SIZE / sizeof(uint32_t));
                ++ul_idx) {
            *p_aligned_dest++ = gs_ul_page_buffer[ul_idx];
        }
        if (ul_erase_flag) {
            ul_error = efc_perform_command(p_efc, EFC_FCMD_EWP,
                    us_page);
        } else {
            ul_error = efc_perform_command(p_efc, EFC_FCMD_WP,
                    us_page);
        }
        if (ul_error) {
            return ul_error;
        }
        /* Progression */
        p_buffer = (void *)((uint32_t) p_buffer + writeSize);
        ul_size -= writeSize;
        us_page++;
        us_offset = 0;
    }
#if SAM3S || SAM3N || SAM3XA || SAM3U
    /* According to the errata, restore the wait state value. */
    efc_set_wait_state(p_efc, ul_fws_temp);
#endif
    return FLASH_RC_OK;
}
References compute_address(), EFC_FCMD_EWP, EFC_FCMD_WP, efc_get_wait_state(), efc_perform_command(), efc_set_wait_state(), FLASH_RC_OK, gs_ul_page_buffer, IFLASH_PAGE_SIZE, Min, translate_address(), and UNUSED.
Referenced by wifi_connect().
translate_address()
static void translate_address (Efc ** pp_efc, uint32_t ul_addr, uint16_t * pus_page, uint16_t * pus_offset) static
Translate the given flash address to page and offset values.
Note
pus_page and pus_offset must not be null in order to store the corresponding values.
Parameters
pp_efc Pointer to an EFC pointer.
ul_addr Address to translate.
pus_page The first page accessed.
pus_offset Byte offset in the first page.
Definition at line 154 of file flash_efc.c.
{
    Efc *p_efc;
    uint16_t us_page;
    uint16_t us_offset;
#if (SAM3XA || SAM3U4)
    if (ul_addr >= IFLASH1_ADDR) {
        p_efc = EFC1;
        us_page = (ul_addr - IFLASH1_ADDR) / IFLASH1_PAGE_SIZE;
        us_offset = (ul_addr - IFLASH1_ADDR) % IFLASH1_PAGE_SIZE;
    } else {
        p_efc = EFC0;
        us_page = (ul_addr - IFLASH0_ADDR) / IFLASH0_PAGE_SIZE;
        us_offset = (ul_addr - IFLASH0_ADDR) % IFLASH0_PAGE_SIZE;
    }
#elif (SAM4SD16 || SAM4SD32 || SAM4C32 || SAM4CMP32 || SAM4CMS32)
    uint32_t uc_gpnvm2;
    uc_gpnvm2 = flash_is_gpnvm_set(2);
    if (ul_addr >= IFLASH1_ADDR) {
        if(uc_gpnvm2 == FLASH_RC_YES) {
            p_efc = EFC0;
        } else {
            p_efc = EFC1;
        }
        us_page = (ul_addr - IFLASH1_ADDR) / IFLASH1_PAGE_SIZE;
        us_offset = (ul_addr - IFLASH1_ADDR) % IFLASH1_PAGE_SIZE;
    } else {
        if(uc_gpnvm2 == FLASH_RC_YES) {
            p_efc = EFC1;
        } else {
            p_efc = EFC0;
        }
        us_page = (ul_addr - IFLASH0_ADDR) / IFLASH0_PAGE_SIZE;
        us_offset = (ul_addr - IFLASH0_ADDR) % IFLASH0_PAGE_SIZE;
    }
#elif (SAM3S8 || SAM3SD8)
    p_efc = EFC;
    us_page = (ul_addr - IFLASH0_ADDR) / IFLASH0_PAGE_SIZE;
    us_offset = (ul_addr - IFLASH0_ADDR) % IFLASH0_PAGE_SIZE;
#else
    Assert(ul_addr >= IFLASH_ADDR);
    Assert(ul_addr <= (IFLASH_ADDR + IFLASH_SIZE));
    p_efc = EFC;
    us_page = (ul_addr - IFLASH_ADDR) / IFLASH_PAGE_SIZE;
    us_offset = (ul_addr - IFLASH_ADDR) % IFLASH_PAGE_SIZE;
#endif
    /* Store values */
    if (pp_efc) {
        *pp_efc = p_efc;
    }
    if (pus_page) {
        *pus_page = us_page;
    }
    if (pus_offset) {
        *pus_offset = us_offset;
    }
}
References Assert, EFC, flash_is_gpnvm_set(), FLASH_RC_YES, IFLASH_ADDR, IFLASH_PAGE_SIZE, and IFLASH_SIZE.
Referenced by flash_erase_all(), flash_get_descriptor(), flash_get_wait_state(), flash_is_locked(), flash_lock(), flash_set_wait_state(), flash_set_wait_state_adaptively(), flash_unlock(), and flash_write().
Variable Documentation
gs_ul_page_buffer
uint32_t gs_ul_page_buffer[IFLASH_PAGE_SIZE/sizeof(uint32_t)] static
Definition at line 142 of file flash_efc.c.
Referenced by flash_write().