WINC1500 Weather Client Demo for SAME70 Xplained: Enhanced Embedded Flash Controller (EEFC)
Enhanced Embedded Flash Controller (EEFC)
The Enhanced Embedded Flash Controller ensures the interface of the Flash block with the 32-bit internal bus.
Macros
#define EEFC_ERROR_FLAGS (EEFC_FSR_FLOCKE | EEFC_FSR_FCMDE)
#define EEFC_FCR_FKEY_PASSWD EEFC_FCR_FKEY(FWP_KEY)
#define FWP_KEY 0x5Au
Functions
void efc_disable_frdy_interrupt (Efc *p_efc)
Disable the flash ready interrupt.
void efc_enable_frdy_interrupt (Efc *p_efc)
Enable the flash ready interrupt.
uint32_t efc_get_flash_access_mode (Efc *p_efc)
Get flash access mode.
uint32_t efc_get_result (Efc *p_efc)
Get the result of the last executed command.
uint32_t efc_get_status (Efc *p_efc)
Get the current status of the EEFC.
uint32_t efc_get_wait_state (Efc *p_efc)
Get flash wait state.
uint32_t efc_init (Efc *p_efc, uint32_t ul_access_mode, uint32_t ul_fws)
Initialize the EFC controller.
uint32_t efc_perform_command (Efc *p_efc, uint32_t ul_command, uint32_t ul_argument)
Perform the given command and wait until its completion (or an error).
uint32_t efc_perform_fcr (Efc *p_efc, uint32_t ul_fcr)
Perform command.
__no_inline RAMFUNC uint32_t efc_perform_read_sequence (Efc *p_efc, uint32_t ul_cmd_st, uint32_t ul_cmd_sp, uint32_t *p_ul_buf, uint32_t ul_size)
Perform read sequence.
void efc_set_flash_access_mode (Efc *p_efc, uint32_t ul_mode)
Set flash access mode.
void efc_set_wait_state (Efc *p_efc, uint32_t ul_fws)
Set flash wait state.
void efc_write_fmr (Efc *p_efc, uint32_t ul_fmr)
Set mode register.
Detailed Description
The Enhanced Embedded Flash Controller ensures the interface of the Flash block with the 32-bit internal bus.
Macro Definition Documentation
EEFC_ERROR_FLAGS
#define EEFC_ERROR_FLAGS (EEFC_FSR_FLOCKE | EEFC_FSR_FCMDE)
Definition at line 86 of file efc.c.
EEFC_FCR_FKEY_PASSWD
#define EEFC_FCR_FKEY_PASSWD EEFC_FCR_FKEY(FWP_KEY)
Definition at line 90 of file efc.c.
FWP_KEY
#define FWP_KEY 0x5Au
Definition at line 76 of file efc.c.
Function Documentation
efc_disable_frdy_interrupt()
void efc_disable_frdy_interrupt (Efc * p_efc)
Disable the flash ready interrupt.
Parameters
p_efc Pointer to an EFC instance.
Definition at line 164 of file efc.c.
{
    uint32_t ul_fmr = p_efc->EEFC_FMR;
    efc_write_fmr(p_efc, ul_fmr & (~EEFC_FMR_FRDY));
}
References Efc::EEFC_FMR, EEFC_FMR_FRDY, and efc_write_fmr().
efc_enable_frdy_interrupt()
void efc_enable_frdy_interrupt (Efc * p_efc)
Enable the flash ready interrupt.
Parameters
p_efc Pointer to an EFC instance.
Definition at line 152 of file efc.c.
{
    uint32_t ul_fmr = p_efc->EEFC_FMR;
    efc_write_fmr(p_efc, ul_fmr | EEFC_FMR_FRDY);
}
References Efc::EEFC_FMR, EEFC_FMR_FRDY, and efc_write_fmr().
efc_get_flash_access_mode()
uint32_t efc_get_flash_access_mode (Efc * p_efc)
Get flash access mode.
Parameters
p_efc Pointer to an EFC instance.
Returns
0 for 128-bit or EEFC_FMR_FAM for 64-bit.
Definition at line 212 of file efc.c.
{
    return (p_efc->EEFC_FMR & EEFC_FMR_FAM);
}
References Efc::EEFC_FMR.
efc_get_result()
uint32_t efc_get_result (Efc * p_efc)
Get the result of the last executed command.
Parameters
p_efc Pointer to an EFC instance.
Returns
The result of the last executed command.
Definition at line 297 of file efc.c.
{
    return p_efc->EEFC_FRR;
}
References Efc::EEFC_FRR.
Referenced by flash_get_descriptor(), flash_is_gpnvm_set(), and flash_is_locked().
efc_get_status()
uint32_t efc_get_status (Efc * p_efc)
Get the current status of the EEFC.
Note
This function clears the value of some status bits (FLOCKE, FCMDE).
Parameters
p_efc Pointer to an EFC instance.
Returns
The current status.
Definition at line 285 of file efc.c.
{
    return p_efc->EEFC_FSR;
}
References Efc::EEFC_FSR.
efc_get_wait_state()
uint32_t efc_get_wait_state (Efc * p_efc)
Get flash wait state.
Parameters
p_efc Pointer to an EFC instance.
Returns
The number of wait states in cycle (no shift).
Definition at line 238 of file efc.c.
{
    return ((p_efc->EEFC_FMR & EEFC_FMR_FWS_Msk) >> EEFC_FMR_FWS_Pos);
}
References Efc::EEFC_FMR, EEFC_FMR_FWS_Msk, and EEFC_FMR_FWS_Pos.
Referenced by flash_get_wait_state(), and flash_write().
efc_init()
uint32_t efc_init (Efc * p_efc, uint32_t ul_access_mode, uint32_t ul_fws)
Initialize the EFC controller.
Parameters
ul_access_mode 0 for 128-bit, EEFC_FMR_FAM for 64-bit.
ul_fws The number of wait states in cycle (no shift).
Returns
0 if successful.
Definition at line 109 of file efc.c.
{
#if (SAM4S || SAM4E || SAM4N || SAM4C || SAMG || SAM4CP || SAM4CM || \
     SAMV71 || SAMV70 || SAMS70 || SAME70)
    efc_write_fmr(p_efc, ul_access_mode | EEFC_FMR_FWS(ul_fws) | EEFC_FMR_CLOE);
#else
    efc_write_fmr(p_efc, ul_access_mode | EEFC_FMR_FWS(ul_fws));
#endif
    return EFC_RC_OK;
}
References EEFC_FMR_CLOE, EEFC_FMR_FWS, EFC_RC_OK, and efc_write_fmr().
Referenced by flash_init().
efc_perform_command()
uint32_t efc_perform_command (Efc * p_efc, uint32_t ul_command, uint32_t ul_argument)
Perform the given command and wait until its completion (or an error).
Note
Unique ID commands are not supported, use efc_perform_read_sequence.
Parameters
p_efc Pointer to an EFC instance.
ul_command Command to perform.
ul_argument Optional command argument.
Note
This function will automatically choose to use IAP function.
Returns
0 if successful, otherwise returns an error code.
Definition at line 256 of file efc.c.
{
    uint32_t result;
    irqflags_t flags;
    /* Unique ID commands are not supported. */
    if (ul_command == EFC_FCMD_STUI || ul_command == EFC_FCMD_SPUI) {
        return EFC_RC_NOT_SUPPORT;
    }
    flags = cpu_irq_save();
    /* Use RAM Function. */
    result = efc_perform_fcr(p_efc,
            EEFC_FCR_FKEY_PASSWD | EEFC_FCR_FARG(ul_argument) |
            EEFC_FCR_FCMD(ul_command));
    cpu_irq_restore(flags);
    return result;
}
References cpu_irq_restore(), cpu_irq_save(), EEFC_FCR_FARG, EEFC_FCR_FCMD, EEFC_FCR_FKEY_PASSWD, EFC_FCMD_SPUI, EFC_FCMD_STUI, efc_perform_fcr(), and EFC_RC_NOT_SUPPORT.
Referenced by flash_clear_gpnvm(), flash_erase_all(), flash_get_descriptor(), flash_is_gpnvm_set(), flash_is_locked(), flash_lock(), flash_set_gpnvm(), flash_unlock(), and flash_write().
efc_perform_fcr()
__no_inline RAMFUNC uint32_t efc_perform_fcr (Efc * p_efc, uint32_t ul_fcr)
Perform command.
Parameters
p_efc Pointer to an EFC instance.
ul_fcr Flash command.
Returns
The current status.
Definition at line 408 of file efc.c.
{
    volatile uint32_t ul_status;
    p_efc->EEFC_FCR = ul_fcr;
    do {
        ul_status = p_efc->EEFC_FSR;
    } while ((ul_status & EEFC_FSR_FRDY) != EEFC_FSR_FRDY);
    return (ul_status & EEFC_ERROR_FLAGS);
}
References EEFC_ERROR_FLAGS, Efc::EEFC_FCR, Efc::EEFC_FSR, and EEFC_FSR_FRDY.
Referenced by efc_perform_command().
efc_perform_read_sequence()
__no_inline RAMFUNC uint32_t efc_perform_read_sequence (Efc * p_efc, uint32_t ul_cmd_st, uint32_t ul_cmd_sp, uint32_t * p_ul_buf, uint32_t ul_size)
Perform read sequence.
Supported sequences are read Unique ID and read User Signature
Parameters
p_efc Pointer to an EFC instance.
ul_cmd_st Start command to perform.
ul_cmd_sp Stop command to perform.
p_ul_buf Pointer to an data buffer.
ul_size Buffer size.
Returns
0 if successful, otherwise returns an error code.
Definition at line 316 of file efc.c.
{
    volatile uint32_t ul_status;
    uint32_t ul_cnt;
#if (SAM3U4 || SAM3XA || SAM4SD16 || SAM4SD32 || SAM4C32 || SAM4CMS32|| SAM4CMP32)
    uint32_t *p_ul_data =
            (uint32_t *) ((p_efc == EFC0) ?
            READ_BUFF_ADDR0 : READ_BUFF_ADDR1);
#elif (SAM3S || SAM4S || SAM3N || SAM3U || SAM4E || SAM4N || SAM4C || SAMG || \
       SAM4CP || SAM4CM || SAMV71 || SAMV70 || SAMS70 || SAME70)
    uint32_t *p_ul_data = (uint32_t *) READ_BUFF_ADDR;
#else
    return EFC_RC_NOT_SUPPORT;
#endif
    if (p_ul_buf == NULL) {
        return EFC_RC_INVALID;
    }
    p_efc->EEFC_FMR |= (0x1u << 16);
    /* Send the Start Read command */
#if (SAM4S || SAM4E || SAM4N || SAM4C || SAMG || SAM4CP || SAM4CM || \
     SAMV71 || SAMV70 || SAMS70 || SAME70)
    p_efc->EEFC_FCR = EEFC_FCR_FKEY_PASSWD | EEFC_FCR_FARG(0)
            | EEFC_FCR_FCMD(ul_cmd_st);
#else
    p_efc->EEFC_FCR = EEFC_FCR_FKEY(FWP_KEY) | EEFC_FCR_FARG(0)
            | EEFC_FCR_FCMD(ul_cmd_st);
#endif
    /* Wait for the FRDY bit in the Flash Programming Status Register
     * (EEFC_FSR) falls.
     */
    do {
        ul_status = p_efc->EEFC_FSR;
    } while ((ul_status & EEFC_FSR_FRDY) == EEFC_FSR_FRDY);
    /* The data is located in the first address of the Flash
     * memory mapping.
     */
    for (ul_cnt = 0; ul_cnt < ul_size; ul_cnt++) {
        p_ul_buf[ul_cnt] = p_ul_data[ul_cnt];
    }
    /* To stop the read mode */
    p_efc->EEFC_FCR =
#if (SAM4S || SAM4E || SAM4N || SAM4C || SAMG || SAM4CP || SAM4CM || \
     SAMV71 || SAMV70 || SAMS70 || SAME70)
            EEFC_FCR_FKEY_PASSWD | EEFC_FCR_FARG(0) |
            EEFC_FCR_FCMD(ul_cmd_sp);
#else
            EEFC_FCR_FKEY(FWP_KEY) | EEFC_FCR_FARG(0) |
            EEFC_FCR_FCMD(ul_cmd_sp);
#endif
    /* Wait for the FRDY bit in the Flash Programming Status Register (EEFC_FSR)
     * rises.
     */
    do {
        ul_status = p_efc->EEFC_FSR;
    } while ((ul_status & EEFC_FSR_FRDY) != EEFC_FSR_FRDY);
    p_efc->EEFC_FMR &= ~(0x1u << 16);
    return EFC_RC_OK;
}
References Efc::EEFC_FCR, EEFC_FCR_FARG, EEFC_FCR_FCMD, EEFC_FCR_FKEY, EEFC_FCR_FKEY_PASSWD, Efc::EEFC_FMR, Efc::EEFC_FSR, EEFC_FSR_FRDY, EFC_RC_INVALID, EFC_RC_NOT_SUPPORT, EFC_RC_OK, FWP_KEY, and NULL.
Referenced by flash_read_unique_id().
efc_set_flash_access_mode()
void efc_set_flash_access_mode (Efc * p_efc, uint32_t ul_mode)
Set flash access mode.
Parameters
p_efc Pointer to an EFC instance.
ul_mode 0 for 128-bit, EEFC_FMR_FAM for 64-bit.
Definition at line 198 of file efc.c.
{
    uint32_t ul_fmr = p_efc->EEFC_FMR & (~EEFC_FMR_FAM);
    efc_write_fmr(p_efc, ul_fmr | ul_mode);
}
References Efc::EEFC_FMR, and efc_write_fmr().
efc_set_wait_state()
void efc_set_wait_state (Efc * p_efc, uint32_t ul_fws)
Set flash wait state.
Parameters
p_efc Pointer to an EFC instance.
ul_fws The number of wait states in cycle (no shift).
Definition at line 224 of file efc.c.
{
    uint32_t ul_fmr = p_efc->EEFC_FMR & (~EEFC_FMR_FWS_Msk);
    efc_write_fmr(p_efc, ul_fmr | EEFC_FMR_FWS(ul_fws));
}
References Efc::EEFC_FMR, EEFC_FMR_FWS, and efc_write_fmr().
Referenced by flash_set_wait_state(), flash_set_wait_state_adaptively(), and flash_write().
efc_write_fmr()
__no_inline RAMFUNC void efc_write_fmr (Efc * p_efc, uint32_t ul_fmr)
Set mode register.
Parameters
p_efc Pointer to an EFC instance.
ul_fmr Value of mode register
Definition at line 393 of file efc.c.
{
    p_efc->EEFC_FMR = ul_fmr;
}
References Efc::EEFC_FMR.
Referenced by efc_disable_frdy_interrupt(), efc_enable_frdy_interrupt(), efc_init(), efc_set_flash_access_mode(), and efc_set_wait_state().