WINC1500 Weather Client Demo for SAME70 Xplained: nm_bsp_register_isr
nm_bsp_register_isr
BSP » Functions
Register ISR (Interrupt Service Routine) in the initialization of the HIF (Host Interface) Layer.
Functions
void nm_bsp_register_isr (tpfNmBspIsr pfIsr)
Register the host interface interrupt service routine.
Detailed Description
Register ISR (Interrupt Service Routine) in the initialization of the HIF (Host Interface) Layer.
When the interrupt is triggered, the BSP layer should call the pfisr function from the interrupt handler.
Function Documentation
nm_bsp_register_isr()
void nm_bsp_register_isr (tpfNmBspIsr pfIsr)
Register the host interface interrupt service routine.
The WINC board uses the SPI interface to communicate with the host. This function registers the SPI interrupt to notify the host whenever there is an outstanding message from the WINC board. This function should be called during the initialization of the host interface. It is an internal driver function and shouldn't be called by the Application.
Parameters
[in] pfIsr Pointer to ISR handler in the HIF layer.
Note
Implementation of this function is host dependent and called by HIF layer.
Warning
Make sure that ISR for IRQ pin for WINC is disabled by default in your implementation.
See also
tpfNmBspIsr
Returns
None
Definition at line 135 of file nm_bsp_same70.c.
{
    gpfIsr = pfIsr;
    /* Configure PGIO pin for interrupt from SPI slave, used when slave has data to send. */
    pmc_enable_periph_clk(CONF_WINC_SPI_INT_PIO_ID);
    pio_configure_pin(CONF_WINC_SPI_INT_PIN, PIO_TYPE_PIO_INPUT);
    pio_pull_up(CONF_WINC_SPI_INT_PIO, CONF_WINC_SPI_INT_MASK, PIO_PULLUP);
    /*Interrupt on falling edge*/
    pio_handler_set(CONF_WINC_SPI_INT_PIO, CONF_WINC_SPI_INT_PIO_ID,
    CONF_WINC_SPI_INT_MASK, PIO_PULLUP | PIO_IT_FALL_EDGE, chip_isr);
    pio_get_interrupt_status(CONF_WINC_SPI_INT_PIO);
    pio_enable_interrupt(CONF_WINC_SPI_INT_PIO, CONF_WINC_SPI_INT_MASK);
    NVIC_EnableIRQ((IRQn_Type) CONF_WINC_SPI_INT_PIO_ID);
    pio_handler_set_priority(CONF_WINC_SPI_INT_PIO, (IRQn_Type)CONF_WINC_SPI_INT_PIO_ID,
            CONF_WINC_SPI_INT_PRIORITY);
}
References chip_isr(), CONF_WINC_SPI_INT_MASK, CONF_WINC_SPI_INT_PIN, CONF_WINC_SPI_INT_PIO, CONF_WINC_SPI_INT_PIO_ID, CONF_WINC_SPI_INT_PRIORITY, gpfIsr, pio_configure_pin(), pio_enable_interrupt(), pio_get_interrupt_status(), pio_handler_set(), pio_handler_set_priority(), PIO_IT_FALL_EDGE, pio_pull_up(), PIO_PULLUP, PIO_TYPE_PIO_INPUT, and pmc_enable_periph_clk().
Referenced by hif_init().