WINC1500 Weather Client Demo for SAME70 Xplained: Power Management Controller (PMC)
Power Management Controller (PMC)
Functions
void pmc_clr_fast_startup_input (uint32_t ul_inputs)
Clear the wake-up inputs for fast startup mode registers (remove event generation).
void pmc_disable_all_pck (void)
Disable all programmable clocks.
void pmc_disable_all_periph_clk (void)
Disable all peripheral clocks.
void pmc_disable_clock_failure_detector (void)
Disable Clock Failure Detector.
void pmc_disable_interrupt (uint32_t ul_sources)
Disable PMC interrupts.
void pmc_disable_pck (uint32_t ul_id)
Disable the specified programmable clock.
uint32_t pmc_disable_periph_clk (uint32_t ul_id)
Disable the specified peripheral clock.
void pmc_disable_pllack (void)
Disable PLLA clock.
void pmc_enable_all_pck (void)
Enable all programmable clocks.
void pmc_enable_all_periph_clk (void)
Enable all peripheral clocks.
void pmc_enable_backupmode (void)
Enable Backup Mode.
void pmc_enable_clock_failure_detector (void)
Enable Clock Failure Detector.
void pmc_enable_interrupt (uint32_t ul_sources)
Enable PMC interrupts.
void pmc_enable_pck (uint32_t ul_id)
Enable the specified programmable clock.
uint32_t pmc_enable_periph_clk (uint32_t ul_id)
Enable the specified peripheral clock.
void pmc_enable_pllack (uint32_t mula, uint32_t pllacount, uint32_t diva)
Enable PLLA clock.
void pmc_enable_sleepmode (uint8_t uc_type)
Enable Sleep Mode.
void pmc_enable_waitmode (void)
Enable Wait Mode.
uint32_t pmc_get_interrupt_mask (void)
Get PMC interrupt mask.
uint32_t pmc_get_status (void)
Get current status.
uint32_t pmc_get_writeprotect_status (void)
Return write protect status.
uint32_t pmc_is_locked_pllack (void)
Is PLLA locked?
uint32_t pmc_is_pck_enabled (uint32_t ul_id)
Check if the specified programmable clock is enabled.
uint32_t pmc_is_periph_clk_enabled (uint32_t ul_id)
Check if the specified peripheral clock is enabled.
void pmc_mainck_osc_select (uint32_t ul_xtal_rc)
Select Main Crystal or internal RC as main clock source.
void pmc_mck_set_prescaler (uint32_t ul_pres)
Set the prescaler of the MCK.
void pmc_mck_set_source (uint32_t ul_source)
Set the source of the MCK.
void pmc_osc_bypass_main_xtal (void)
Bypass main XTAL.
void pmc_osc_disable_fastrc (void)
Disable the internal fast RC.
void pmc_osc_disable_main_xtal (void)
Disable the main Xtal.
void pmc_osc_disable_xtal (uint32_t ul_bypass)
Disable the external Xtal.
void pmc_osc_enable_fastrc (uint32_t ul_rc)
Enable fast RC oscillator.
void pmc_osc_enable_main_xtal (uint32_t ul_xtal_startup_time)
Enable main XTAL oscillator.
uint32_t pmc_osc_is_bypassed_main_xtal (void)
Check if the main crystal is bypassed.
uint32_t pmc_osc_is_ready_32kxtal (void)
Check if the external 32k Xtal is ready.
uint32_t pmc_osc_is_ready_fastrc (void)
Check if the main fastrc is ready.
uint32_t pmc_osc_is_ready_main_xtal (void)
Check if the main crystal is ready.
uint32_t pmc_osc_is_ready_mainck (void)
Check if the MAINCK is ready.
void pmc_pck_set_prescaler (uint32_t ul_id, uint32_t ul_pres)
Set the prescaler for the specified programmable clock.
void pmc_pck_set_source (uint32_t ul_id, uint32_t ul_source)
Set the source oscillator for the specified programmable clock.
void pmc_set_fast_startup_input (uint32_t ul_inputs)
Set the wake-up inputs for fast startup mode registers (event generation).
void pmc_set_writeprotect (uint32_t ul_enable)
Enable or disable write protect of PMC registers.
void pmc_switch_mainck_to_fastrc (uint32_t ul_moscrcf)
Switch main clock source selection to internal fast RC.
void pmc_switch_mainck_to_xtal (uint32_t ul_bypass, uint32_t ul_xtal_startup_time)
Switch main clock source selection to external Xtal/Bypass.
uint32_t pmc_switch_mck_to_mainck (uint32_t ul_pres)
Switch master clock source selection to main clock.
uint32_t pmc_switch_mck_to_pllack (uint32_t ul_pres)
Switch master clock source selection to PLLA clock.
uint32_t pmc_switch_mck_to_sclk (uint32_t ul_pres)
Switch master clock source selection to slow clock.
uint32_t pmc_switch_pck_to_mainck (uint32_t ul_id, uint32_t ul_pres)
Switch programmable clock source selection to main clock.
uint32_t pmc_switch_pck_to_mck (uint32_t ul_id, uint32_t ul_pres)
Switch programmable clock source selection to mck.
uint32_t pmc_switch_pck_to_pllack (uint32_t ul_id, uint32_t ul_pres)
Switch programmable clock source selection to PLLA clock.
uint32_t pmc_switch_pck_to_sclk (uint32_t ul_id, uint32_t ul_pres)
Switch programmable clock source selection to slow clock.
void pmc_switch_sclk_to_32kxtal (uint32_t ul_bypass)
Switch slow clock source selection to external 32k (Xtal or Bypass).
Detailed Description
Purpose
The Power Management Controller (PMC) optimizes power consumption by controlling all system and user peripheral clocks. The PMC enables/disables the clock inputs to many of the peripherals and the Cortex-M Processor.
Function Documentation
pmc_clr_fast_startup_input()
void pmc_clr_fast_startup_input (uint32_t ul_inputs)
Clear the wake-up inputs for fast startup mode registers (remove event generation).
Parameters
ul_inputs Wake up inputs to disable.
Definition at line 1350 of file pmc.c.
{
    ul_inputs &= PMC_FAST_STARTUP_Msk;
    PMC->PMC_FSMR &= ~ul_inputs;
}
References PMC, and PMC_FAST_STARTUP_Msk.
pmc_disable_all_pck()
void pmc_disable_all_pck (void)
Disable all programmable clocks.
Definition at line 1088 of file pmc.c.
{
    PMC->PMC_SCDR = PMC_SCDR_PCK0 | PMC_SCDR_PCK1 | PMC_SCDR_PCK2;
}
References PMC, PMC_SCDR_PCK0, PMC_SCDR_PCK1, and PMC_SCDR_PCK2.
pmc_disable_all_periph_clk()
void pmc_disable_all_periph_clk (void)
Disable all peripheral clocks.
Definition at line 776 of file pmc.c.
{
    PMC->PMC_PCDR0 = PMC_MASK_STATUS0;
    while ((PMC->PMC_PCSR0 & PMC_MASK_STATUS0) != 0);
#if (SAM3S || SAM3XA || SAM4S || SAM4E || SAM4C || SAM4CM || SAM4CP || SAMV71 \
        || SAMV70 || SAME70 || SAMS70)
    PMC->PMC_PCDR1 = PMC_MASK_STATUS1;
    while ((PMC->PMC_PCSR1 & PMC_MASK_STATUS1) != 0);
#endif
#if defined(REG_PMC_PCR) && !SAMG55
    for (uint32_t id = 64; id <= 0x7F; id ++) {
        pmc_disable_periph_clk(id);
    }
#endif
}
References PMC, pmc_disable_periph_clk(), PMC_MASK_STATUS0, and PMC_MASK_STATUS1.
pmc_disable_clock_failure_detector()
void pmc_disable_clock_failure_detector (void)
Disable Clock Failure Detector.
Definition at line 1536 of file pmc.c.
{
    uint32_t ul_reg = PMC->CKGR_MOR & (~CKGR_MOR_CFDEN);
    PMC->CKGR_MOR = CKGR_MOR_KEY_PASSWD | ul_reg;
}
References CKGR_MOR_KEY_PASSWD, and PMC.
pmc_disable_interrupt()
void pmc_disable_interrupt (uint32_t ul_sources)
Disable PMC interrupts.
Parameters
ul_sources Interrupt sources bit map.
Definition at line 1307 of file pmc.c.
{
    PMC->PMC_IDR = ul_sources;
}
References PMC.
pmc_disable_pck()
void pmc_disable_pck (uint32_t ul_id)
Disable the specified programmable clock.
Parameters
ul_id Id of the programmable clock.
Definition at line 1072 of file pmc.c.
{
    PMC->PMC_SCDR = PMC_SCER_PCK0 << ul_id;
}
References PMC, and PMC_SCER_PCK0.
Referenced by genclk_disable().
pmc_disable_periph_clk()
uint32_t pmc_disable_periph_clk (uint32_t ul_id)
Disable the specified peripheral clock.
Note
The ID must NOT be shifted (i.e., 1 << ID_xxx).
Parameters
ul_id Peripheral ID (ID_xxx).
Return values
0 Success.
1 Invalid parameter.
Definition at line 722 of file pmc.c.
{
#if defined(REG_PMC_PCR) && !SAMG55
    uint32_t pcr;
    PMC->PMC_PCR = ul_id & 0x7F;
    pcr = PMC->PMC_PCR | PMC_PCR_CMD;
    PMC->PMC_PCR = pcr;
    return 0;
#else
    if (ul_id > MAX_PERIPH_ID) {
        return 1;
    }
    if (ul_id < 32) {
        if ((PMC->PMC_PCSR0 & (1u << ul_id)) == (1u << ul_id)) {
            PMC->PMC_PCDR0 = 1 << ul_id;
        }
#if (SAM3S || SAM3XA || SAM4S || SAM4E || SAM4C || SAM4CM || SAM4CP || SAMG55 || SAMV71 \
        || SAMV70 || SAME70 || SAMS70)
    } else {
        ul_id -= 32;
        if ((PMC->PMC_PCSR1 & (1u << ul_id)) == (1u << ul_id)) {
            PMC->PMC_PCDR1 = 1 << ul_id;
        }
#endif
    }
    return 0;
#endif /* defined(REG_PMC_PCR) && !SAMG55 */
}
References PMC, and PMC_PCR_CMD.
Referenced by pmc_disable_all_periph_clk(), and sysclk_disable_peripheral_clock().
pmc_disable_pllack()
void pmc_disable_pllack (void)
Disable PLLA clock.
Definition at line 576 of file pmc.c.
{
#if (SAM4C || SAM4CM || SAM4CP || SAMG)
    PMC->CKGR_PLLAR = CKGR_PLLAR_MULA(0);
#else
    PMC->CKGR_PLLAR = CKGR_PLLAR_ONE | CKGR_PLLAR_MULA(0);
#endif
}
References CKGR_PLLAR_MULA, CKGR_PLLAR_ONE, and PMC.
Referenced by pll_config_write(), pll_disable(), pll_enable(), and pmc_enable_pllack().
pmc_enable_all_pck()
void pmc_enable_all_pck (void)
Enable all programmable clocks.
Definition at line 1080 of file pmc.c.
{
    PMC->PMC_SCER = PMC_SCER_PCK0 | PMC_SCER_PCK1 | PMC_SCER_PCK2;
}
References PMC, PMC_SCER_PCK0, PMC_SCER_PCK1, and PMC_SCER_PCK2.
pmc_enable_all_periph_clk()
void pmc_enable_all_periph_clk (void)
Enable all peripheral clocks.
Definition at line 755 of file pmc.c.
{
    PMC->PMC_PCER0 = PMC_MASK_STATUS0;
    while ((PMC->PMC_PCSR0 & PMC_MASK_STATUS0) != PMC_MASK_STATUS0);
#if (SAM3S || SAM3XA || SAM4S || SAM4E || SAM4C || SAM4CM || SAM4CP || SAMV71  \
        || SAMV70 || SAME70 || SAMS70)
    PMC->PMC_PCER1 = PMC_MASK_STATUS1;
    while ((PMC->PMC_PCSR1 & PMC_MASK_STATUS1) != PMC_MASK_STATUS1);
#endif
#if defined(REG_PMC_PCR) && !SAMG55
    for (uint32_t id = 64; id <= 0x7F; id ++) {
        pmc_enable_periph_clk(id);
    }
#endif
}
References PMC, pmc_enable_periph_clk(), PMC_MASK_STATUS0, and PMC_MASK_STATUS1.
pmc_enable_backupmode()
void pmc_enable_backupmode (void)
Enable Backup Mode.
Enter condition: WFE/(VROFF bit = 1) + (SLEEPDEEP bit = 1)
Definition at line 1501 of file pmc.c.
{
#if (SAM4C || SAM4CM || SAM4CP)
    uint32_t tmp = SUPC->SUPC_MR & ~(SUPC_MR_BUPPOREN | SUPC_MR_KEY_Msk);
    SUPC->SUPC_MR = tmp | SUPC_MR_KEY_PASSWD;
    while (SUPC->SUPC_SR & SUPC_SR_BUPPORS);
#endif
    SCB->SCR |= SCB_SCR_SLEEPDEEP_Msk;
#if (SAM4S || SAM4E || SAM4N || SAM4C || SAM4CM || SAM4CP || SAMG55 || SAMV71 || SAMV70 || SAME70 || SAMS70)
    SUPC->SUPC_CR = SUPC_CR_KEY_PASSWD | SUPC_CR_VROFF_STOP_VREG;
    uint32_t ul_dummy = SUPC->SUPC_MR;
    UNUSED(ul_dummy);
    __DSB();
    __WFE();
    __WFI();
#else
    __DSB();
    __WFE();
#endif
}
References SUPC, SUPC_CR_KEY_PASSWD, SUPC_CR_VROFF_STOP_VREG, SUPC_MR_KEY_Msk, SUPC_MR_KEY_PASSWD, and UNUSED.
pmc_enable_clock_failure_detector()
void pmc_enable_clock_failure_detector (void)
Enable Clock Failure Detector.
Definition at line 1526 of file pmc.c.
{
    uint32_t ul_reg = PMC->CKGR_MOR;
    PMC->CKGR_MOR = CKGR_MOR_KEY_PASSWD | CKGR_MOR_CFDEN | ul_reg;
}
References CKGR_MOR_CFDEN, CKGR_MOR_KEY_PASSWD, and PMC.
pmc_enable_interrupt()
void pmc_enable_interrupt (uint32_t ul_sources)
Enable PMC interrupts.
Parameters
ul_sources Interrupt sources bit map.
Definition at line 1297 of file pmc.c.
{
    PMC->PMC_IER = ul_sources;
}
References PMC.
pmc_enable_pck()
void pmc_enable_pck (uint32_t ul_id)
Enable the specified programmable clock.
Parameters
ul_id Id of the programmable clock.
Definition at line 1062 of file pmc.c.
{
    PMC->PMC_SCER = PMC_SCER_PCK0 << ul_id;
}
References PMC, and PMC_SCER_PCK0.
Referenced by genclk_enable().
pmc_enable_periph_clk()
uint32_t pmc_enable_periph_clk (uint32_t ul_id)
Enable the specified peripheral clock.
Note
The ID must NOT be shifted (i.e., 1 << ID_xxx).
Parameters
ul_id Peripheral ID (ID_xxx).
Return values
0 Success.
1 Invalid parameter.
Definition at line 682 of file pmc.c.
{
#if defined(REG_PMC_PCR) && !SAMG55
    uint32_t pcr;
    PMC->PMC_PCR = ul_id & 0x7F;
    pcr = PMC->PMC_PCR | PMC_PCR_EN | PMC_PCR_CMD;
    PMC->PMC_PCR = pcr;
    return 0;
#else
    if (ul_id > MAX_PERIPH_ID) {
        return 1;
    }
    if (ul_id < 32) {
        if ((PMC->PMC_PCSR0 & (1u << ul_id)) != (1u << ul_id)) {
            PMC->PMC_PCER0 = 1 << ul_id;
        }
#if (SAM3S || SAM3XA || SAM4S || SAM4E || SAM4C || SAM4CM || SAM4CP || SAMG55 || SAMV71 || SAMV70 || SAME70 || SAMS70)
    } else {
        ul_id -= 32;
        if ((PMC->PMC_PCSR1 & (1u << ul_id)) != (1u << ul_id)) {
            PMC->PMC_PCER1 = 1 << ul_id;
        }
#endif
    }
    return 0;
#endif /* defined(REG_PMC_PCR) && !SAMG55 */
}
References PMC, PMC_PCR_CMD, and PMC_PCR_EN.
Referenced by ili9488_init(), nm_bsp_register_isr(), nm_bus_init(), pmc_enable_all_periph_clk(), and sysclk_enable_peripheral_clock().
pmc_enable_pllack()
void pmc_enable_pllack (uint32_t mula, uint32_t pllacount, uint32_t diva)
Enable PLLA clock.
Parameters
mula PLLA multiplier.
pllacount PLLA counter.
diva Divider.
Definition at line 558 of file pmc.c.
{
    /* first disable the PLL to unlock the lock */
    pmc_disable_pllack();
#if (SAM4C || SAM4CM || SAM4CP || SAMG)
    PMC->CKGR_PLLAR = CKGR_PLLAR_PLLAEN(diva) |
            CKGR_PLLAR_PLLACOUNT(pllacount) | CKGR_PLLAR_MULA(mula);
#else
    PMC->CKGR_PLLAR = CKGR_PLLAR_ONE | CKGR_PLLAR_DIVA(diva) |
            CKGR_PLLAR_PLLACOUNT(pllacount) | CKGR_PLLAR_MULA(mula);
#endif
    while ((PMC->PMC_SR & PMC_SR_LOCKA) == 0);
}
References CKGR_PLLAR_DIVA, CKGR_PLLAR_MULA, CKGR_PLLAR_ONE, CKGR_PLLAR_PLLACOUNT, PMC, pmc_disable_pllack(), and PMC_SR_LOCKA.
pmc_enable_sleepmode()
void pmc_enable_sleepmode (uint8_t uc_type)
Enable Sleep Mode.
Enter condition: (WFE or WFI) + (SLEEPDEEP bit = 0) + (LPM bit = 0)
Parameters
uc_type 0 for wait for interrupt, 1 for wait for event.
Note
For SAM4S, SAM4C, SAM4CM, SAM4CP, SAMV71 and SAM4E series, since only WFI is effective, uc_type = 1 will be treated as uc_type = 0.
Definition at line 1390 of file pmc.c.
{
#if !(SAM4S || SAM4E || SAM4N || SAM4C || SAM4CM || SAM4CP || SAMV71 || SAMV70 || SAME70 || SAMS70)
    PMC->PMC_FSMR &= (uint32_t) ~ PMC_FSMR_LPM; // Enter Sleep mode
#endif
    SCB->SCR &= (uint32_t) ~ SCB_SCR_SLEEPDEEP_Msk; // Deep sleep
#if (SAM4S || SAM4E || SAM4N || SAM4C || SAM4CM || SAM4CP || SAMV71 || SAMV70 || SAME70 || SAMS70)
    UNUSED(uc_type);
    __DSB();
    __WFI();
#else
    if (uc_type == 0) {
        __DSB();
        __WFI();
    } else {
        __DSB();
        __WFE();
    }
#endif
}
References PMC, PMC_FSMR_LPM, and UNUSED.
pmc_enable_waitmode()
void pmc_enable_waitmode (void)
Enable Wait Mode.
Enter condition: WFE + (SLEEPDEEP bit = 0) + (LPM bit = 1)
Definition at line 1475 of file pmc.c.
{
    uint32_t i;
    PMC->PMC_FSMR |= PMC_FSMR_LPM; /* Enter Wait mode */
    SCB->SCR &= (uint32_t) ~ SCB_SCR_SLEEPDEEP_Msk; /* Deep sleep */
    __DSB();
    __WFE();
    /* Waiting for MOSCRCEN bit cleared is strongly recommended
     * to ensure that the core will not execute undesired instructions
     */
    for (i = 0; i < 500; i++) {
        __NOP();
    }
    while (!(PMC->CKGR_MOR & CKGR_MOR_MOSCRCEN));
}
References CKGR_MOR_MOSCRCEN, PMC, and PMC_FSMR_LPM.
pmc_get_interrupt_mask()
uint32_t pmc_get_interrupt_mask (void)
Get PMC interrupt mask.
Returns
The interrupt mask value.
Definition at line 1317 of file pmc.c.
{
    return PMC->PMC_IMR;
}
References PMC.
pmc_get_status()
uint32_t pmc_get_status (void)
Get current status.
Returns
The current PMC status.
Definition at line 1327 of file pmc.c.
{
    return PMC->PMC_SR;
}
References PMC.
pmc_get_writeprotect_status()
uint32_t pmc_get_writeprotect_status (void)
Return write protect status.
Returns
Return write protect status.
Definition at line 1584 of file pmc.c.
{
    return PMC->PMC_WPSR;
}
References PMC.
pmc_is_locked_pllack()
uint32_t pmc_is_locked_pllack (void)
Is PLLA locked?
Return values
0 Not locked.
1 Locked.
Definition at line 591 of file pmc.c.
{
    return (PMC->PMC_SR & PMC_SR_LOCKA);
}
References PMC, and PMC_SR_LOCKA.
Referenced by pll_is_locked().
pmc_is_pck_enabled()
uint32_t pmc_is_pck_enabled (uint32_t ul_id)
Check if the specified programmable clock is enabled.
Parameters
ul_id Id of the programmable clock.
Return values
0 Programmable clock is disabled or unknown.
1 Programmable clock is enabled.
Definition at line 1101 of file pmc.c.
{
    if (ul_id > 2) {
        return 0;
    }
    return (PMC->PMC_SCSR & (PMC_SCSR_PCK0 << ul_id));
}
References PMC, and PMC_SCSR_PCK0.
pmc_is_periph_clk_enabled()
uint32_t pmc_is_periph_clk_enabled (uint32_t ul_id)
Check if the specified peripheral clock is enabled.
Note
The ID must NOT be shifted (i.e., 1 << ID_xxx).
Parameters
ul_id Peripheral ID (ID_xxx).
Return values
0 Peripheral clock is disabled or unknown.
1 Peripheral clock is enabled.
Definition at line 804 of file pmc.c.
{
#if defined(REG_PMC_PCR) && !SAMG55
    PMC->PMC_PCR = ul_id & 0x7F;
    return (PMC->PMC_PCR & PMC_PCR_EN) ? 1 : 0;
#else
    if (ul_id > MAX_PERIPH_ID) {
        return 0;
    }
#if (SAM3S || SAM3XA || SAM4S || SAM4E || SAM4C || SAM4CM || SAM4CP || SAMV71 \
        || SAMV70 || SAME70 || SAMS70)
    if (ul_id < 32) {
#endif
        if ((PMC->PMC_PCSR0 & (1u << ul_id))) {
            return 1;
        } else {
            return 0;
        }
#if (SAM3S || SAM3XA || SAM4S || SAM4E || SAM4C || SAM4CM || SAM4CP || SAMV71 \
        || SAMV70 || SAME70 || SAMS70)
    } else {
        ul_id -= 32;
        if ((PMC->PMC_PCSR1 & (1u << ul_id))) {
            return 1;
        } else {
            return 0;
        }
    }
#endif
#endif /* defined(REG_PMC_PCR) && !SAMG55 */
}
References PMC, and PMC_PCR_EN.
pmc_mainck_osc_select()
void pmc_mainck_osc_select (uint32_t ul_xtal_rc)
Select Main Crystal or internal RC as main clock source.
Note
This function will not enable/disable RC or Main Crystal.
Parameters
ul_xtal_rc 0 internal RC is selected, otherwise Main Crystal.
Definition at line 540 of file pmc.c.
{
    uint32_t mor = PMC->CKGR_MOR;
    if (ul_xtal_rc) {
        mor |=  CKGR_MOR_MOSCSEL;
    } else {
        mor &= ~CKGR_MOR_MOSCSEL;
    }
    PMC->CKGR_MOR = CKGR_MOR_KEY_PASSWD | mor;
}
References CKGR_MOR_KEY_PASSWD, CKGR_MOR_MOSCSEL, and PMC.
pmc_mck_set_prescaler()
void pmc_mck_set_prescaler (uint32_t ul_pres)
Set the prescaler of the MCK.
Parameters
ul_pres Prescaler value.
Definition at line 96 of file pmc.c.
{
    PMC->PMC_MCKR =
            (PMC->PMC_MCKR & (~PMC_MCKR_PRES_Msk)) | ul_pres;
    while (!(PMC->PMC_SR & PMC_SR_MCKRDY));
}
References PMC, and PMC_SR_MCKRDY.
Referenced by sysclk_set_prescalers().
pmc_mck_set_source()
void pmc_mck_set_source (uint32_t ul_source)
Set the source of the MCK.
Parameters
ul_source Source selection value.
Definition at line 139 of file pmc.c.
{
    PMC->PMC_MCKR =
            (PMC->PMC_MCKR & (~PMC_MCKR_CSS_Msk)) | ul_source;
    while (!(PMC->PMC_SR & PMC_SR_MCKRDY));
}
References PMC, and PMC_SR_MCKRDY.
Referenced by sysclk_set_source().
pmc_osc_bypass_main_xtal()
void pmc_osc_bypass_main_xtal (void)
Bypass main XTAL.
Definition at line 430 of file pmc.c.
{
    uint32_t mor = PMC->CKGR_MOR;
    mor &= ~(CKGR_MOR_MOSCXTBY|CKGR_MOR_MOSCXTEN);
    mor |= CKGR_MOR_KEY_PASSWD | CKGR_MOR_MOSCXTBY;
    /* Enable Crystal oscillator but DO NOT switch now. Keep MOSCSEL to 0 */
    PMC->CKGR_MOR = mor;
    /* The MOSCXTS in PMC_SR is automatically set */
}
References CKGR_MOR_KEY_PASSWD, CKGR_MOR_MOSCXTBY, CKGR_MOR_MOSCXTEN, and PMC.
pmc_osc_disable_fastrc()
void pmc_osc_disable_fastrc (void)
Disable the internal fast RC.
Definition at line 393 of file pmc.c.
{
    /* Disable Fast RC oscillator */
    PMC->CKGR_MOR = (PMC->CKGR_MOR & ~CKGR_MOR_MOSCRCEN &
                    ~CKGR_MOR_MOSCRCF_Msk)
                | CKGR_MOR_KEY_PASSWD;
}
References CKGR_MOR_KEY_PASSWD, and PMC.
Referenced by osc_disable().
pmc_osc_disable_main_xtal()
void pmc_osc_disable_main_xtal (void)
Disable the main Xtal.
Definition at line 443 of file pmc.c.
{
    uint32_t mor = PMC->CKGR_MOR;
    mor &= ~(CKGR_MOR_MOSCXTBY|CKGR_MOR_MOSCXTEN);
    PMC->CKGR_MOR = CKGR_MOR_KEY_PASSWD | mor;
}
References CKGR_MOR_KEY_PASSWD, CKGR_MOR_MOSCXTBY, CKGR_MOR_MOSCXTEN, and PMC.
pmc_osc_disable_xtal()
void pmc_osc_disable_xtal (uint32_t ul_bypass)
Disable the external Xtal.
Parameters
ul_bypass 0 for Xtal, 1 for bypass.
Definition at line 509 of file pmc.c.
{
    /* Disable xtal oscillator */
    if (ul_bypass) {
        PMC->CKGR_MOR = (PMC->CKGR_MOR & ~CKGR_MOR_MOSCXTBY) |
                CKGR_MOR_KEY_PASSWD;
    } else {
        PMC->CKGR_MOR = (PMC->CKGR_MOR & ~CKGR_MOR_MOSCXTEN) |
                CKGR_MOR_KEY_PASSWD;
    }
}
References CKGR_MOR_KEY_PASSWD, and PMC.
Referenced by osc_disable().
pmc_osc_enable_fastrc()
void pmc_osc_enable_fastrc (uint32_t ul_rc)
Enable fast RC oscillator.
Parameters
ul_rc Fast RC oscillator(4/8/12Mhz).
Definition at line 376 of file pmc.c.
{
    /* Enable Fast RC oscillator but DO NOT switch to RC */
    PMC->CKGR_MOR |= (CKGR_MOR_KEY_PASSWD | CKGR_MOR_MOSCRCEN);
    /* Wait the Fast RC to stabilize */
    while (!(PMC->PMC_SR & PMC_SR_MOSCRCS));
    /* Change Fast RC oscillator frequency */
    PMC->CKGR_MOR = (PMC->CKGR_MOR & ~CKGR_MOR_MOSCRCF_Msk) |
            CKGR_MOR_KEY_PASSWD | ul_rc;
    /* Wait the Fast RC to stabilize */
    while (!(PMC->PMC_SR & PMC_SR_MOSCRCS));
}
References CKGR_MOR_KEY_PASSWD, CKGR_MOR_MOSCRCEN, PMC, and PMC_SR_MOSCRCS.
pmc_osc_enable_main_xtal()
void pmc_osc_enable_main_xtal (uint32_t ul_xtal_startup_time)
Enable main XTAL oscillator.
Parameters
ul_xtal_startup_time Xtal start-up time, in number of slow clocks.
Definition at line 416 of file pmc.c.
{
    uint32_t mor = PMC->CKGR_MOR;
    mor &= ~(CKGR_MOR_MOSCXTBY|CKGR_MOR_MOSCXTEN);
    mor |= CKGR_MOR_KEY_PASSWD | CKGR_MOR_MOSCXTEN |
            CKGR_MOR_MOSCXTST(ul_xtal_startup_time);
    PMC->CKGR_MOR = mor;
    /* Wait the main Xtal to stabilize */
    while (!(PMC->PMC_SR & PMC_SR_MOSCXTS));
}
References CKGR_MOR_KEY_PASSWD, CKGR_MOR_MOSCXTBY, CKGR_MOR_MOSCXTEN, CKGR_MOR_MOSCXTST, PMC, and PMC_SR_MOSCXTS.
pmc_osc_is_bypassed_main_xtal()
uint32_t pmc_osc_is_bypassed_main_xtal (void)
Check if the main crystal is bypassed.
Return values
0 Xtal is bypassed, otherwise not.
Definition at line 455 of file pmc.c.
{
    return (PMC->CKGR_MOR & CKGR_MOR_MOSCXTBY);
}
References CKGR_MOR_MOSCXTBY, and PMC.
pmc_osc_is_ready_32kxtal()
uint32_t pmc_osc_is_ready_32kxtal (void)
Check if the external 32k Xtal is ready.
Return values
1 External 32k Xtal is ready.
0 External 32k Xtal is not ready.
Definition at line 336 of file pmc.c.
{
    return ((SUPC->SUPC_SR & SUPC_SR_OSCSEL)
            && (PMC->PMC_SR & PMC_SR_OSCSELS));
}
References PMC, PMC_SR_OSCSELS, SUPC, and SUPC_SR_OSCSEL.
Referenced by osc_is_ready().
pmc_osc_is_ready_fastrc()
uint32_t pmc_osc_is_ready_fastrc (void)
Check if the main fastrc is ready.
Return values
0 Xtal is not ready, otherwise ready.
Definition at line 406 of file pmc.c.
{
    return (PMC->PMC_SR & PMC_SR_MOSCRCS);
}
References PMC, and PMC_SR_MOSCRCS.
pmc_osc_is_ready_main_xtal()
uint32_t pmc_osc_is_ready_main_xtal (void)
Check if the main crystal is ready.
Note
If main crystal is bypassed, it's always ready.
Return values
0 main crystal is not ready, otherwise ready.
Definition at line 467 of file pmc.c.
{
    return (PMC->PMC_SR & PMC_SR_MOSCXTS);
}
References PMC, and PMC_SR_MOSCXTS.
pmc_osc_is_ready_mainck()
uint32_t pmc_osc_is_ready_mainck (void)
Check if the MAINCK is ready.
Depending on MOSCEL, MAINCK can be one of Xtal, bypass or internal RC.
Return values
1 Xtal is ready.
0 Xtal is not ready.
Definition at line 528 of file pmc.c.
{
    return PMC->PMC_SR & PMC_SR_MOSCSELS;
}
References PMC, and PMC_SR_MOSCSELS.
Referenced by osc_is_ready().
pmc_pck_set_prescaler()
void pmc_pck_set_prescaler (uint32_t ul_id, uint32_t ul_pres)
Set the prescaler for the specified programmable clock.
Parameters
ul_id Peripheral ID.
ul_pres Prescaler value.
Definition at line 843 of file pmc.c.
{
    PMC->PMC_PCK[ul_id] =
            (PMC->PMC_PCK[ul_id] & ~PMC_PCK_PRES_Msk) | ul_pres;
    while ((PMC->PMC_SCER & (PMC_SCER_PCK0 << ul_id))
            && !(PMC->PMC_SR & (PMC_SR_PCKRDY0 << ul_id)));
}
References PMC, PMC_SCER_PCK0, and PMC_SR_PCKRDY0.
pmc_pck_set_source()
void pmc_pck_set_source (uint32_t ul_id, uint32_t ul_source)
Set the source oscillator for the specified programmable clock.
Parameters
ul_id Peripheral ID.
ul_source Source selection value.
Definition at line 857 of file pmc.c.
{
    PMC->PMC_PCK[ul_id] =
            (PMC->PMC_PCK[ul_id] & ~PMC_PCK_CSS_Msk) | ul_source;
    while ((PMC->PMC_SCER & (PMC_SCER_PCK0 << ul_id))
            && !(PMC->PMC_SR & (PMC_SR_PCKRDY0 << ul_id)));
}
References PMC, PMC_SCER_PCK0, and PMC_SR_PCKRDY0.
pmc_set_fast_startup_input()
void pmc_set_fast_startup_input (uint32_t ul_inputs)
Set the wake-up inputs for fast startup mode registers (event generation).
Parameters
ul_inputs Wake up inputs to enable.
Definition at line 1338 of file pmc.c.
{
    ul_inputs &= PMC_FAST_STARTUP_Msk;
    PMC->PMC_FSMR |= ul_inputs;
}
References PMC, and PMC_FAST_STARTUP_Msk.
pmc_set_writeprotect()
void pmc_set_writeprotect (uint32_t ul_enable)
Enable or disable write protect of PMC registers.
Parameters
ul_enable 1 to enable, 0 to disable.
Definition at line 1570 of file pmc.c.
{
    if (ul_enable) {
        PMC->PMC_WPMR = PMC_WPMR_WPKEY_PASSWD | PMC_WPMR_WPEN;
    } else {
        PMC->PMC_WPMR = PMC_WPMR_WPKEY_PASSWD;
    }
}
References PMC, PMC_WPMR_WPEN, and PMC_WPMR_WPKEY_PASSWD.
pmc_switch_mainck_to_fastrc()
void pmc_switch_mainck_to_fastrc (uint32_t ul_moscrcf)
Switch main clock source selection to internal fast RC.
Parameters
ul_moscrcf Fast RC oscillator(4/8/12Mhz).
Return values
0 Success.
1 Timeout error.
2 Invalid frequency.
Definition at line 351 of file pmc.c.
{
    /* Enable Fast RC oscillator but DO NOT switch to RC now */
    PMC->CKGR_MOR |= (CKGR_MOR_KEY_PASSWD | CKGR_MOR_MOSCRCEN);
    /* Wait the Fast RC to stabilize */
    while (!(PMC->PMC_SR & PMC_SR_MOSCRCS));
    /* Change Fast RC oscillator frequency */
    PMC->CKGR_MOR = (PMC->CKGR_MOR & ~CKGR_MOR_MOSCRCF_Msk) |
            CKGR_MOR_KEY_PASSWD | ul_moscrcf;
    /* Wait the Fast RC to stabilize */
    while (!(PMC->PMC_SR & PMC_SR_MOSCRCS));
    /* Switch to Fast RC */
    PMC->CKGR_MOR = (PMC->CKGR_MOR & ~CKGR_MOR_MOSCSEL) |
            CKGR_MOR_KEY_PASSWD;
}
References CKGR_MOR_KEY_PASSWD, CKGR_MOR_MOSCRCEN, PMC, and PMC_SR_MOSCRCS.
Referenced by osc_enable().
pmc_switch_mainck_to_xtal()
void pmc_switch_mainck_to_xtal (uint32_t ul_bypass, uint32_t ul_xtal_startup_time)
Switch main clock source selection to external Xtal/Bypass.
Note
The function may switch MCK to SCLK if MCK source is MAINCK to avoid any system crash.
If used in Xtal mode, the Xtal is automatically enabled.
Parameters
ul_bypass 0 for Xtal, 1 for bypass.
Return values
0 Success.
1 Timeout error.
Definition at line 485 of file pmc.c.
{
    /* Enable Main Xtal oscillator */
    if (ul_bypass) {
        PMC->CKGR_MOR = (PMC->CKGR_MOR & ~CKGR_MOR_MOSCXTEN) |
                CKGR_MOR_KEY_PASSWD | CKGR_MOR_MOSCXTBY |
                CKGR_MOR_MOSCSEL;
    } else {
        PMC->CKGR_MOR = (PMC->CKGR_MOR & ~CKGR_MOR_MOSCXTBY) |
                CKGR_MOR_KEY_PASSWD | CKGR_MOR_MOSCXTEN |
                CKGR_MOR_MOSCXTST(ul_xtal_startup_time);
        /* Wait the Xtal to stabilize */
        while (!(PMC->PMC_SR & PMC_SR_MOSCXTS));
        PMC->CKGR_MOR |= CKGR_MOR_KEY_PASSWD | CKGR_MOR_MOSCSEL;
    }
}
References CKGR_MOR_KEY_PASSWD, CKGR_MOR_MOSCSEL, CKGR_MOR_MOSCXTBY, CKGR_MOR_MOSCXTEN, CKGR_MOR_MOSCXTST, PMC, and PMC_SR_MOSCXTS.
Referenced by osc_enable().
pmc_switch_mck_to_mainck()
uint32_t pmc_switch_mck_to_mainck (uint32_t ul_pres)
Switch master clock source selection to main clock.
Parameters
ul_pres Processor clock prescaler.
Return values
0 Success.
1 Timeout error.
Definition at line 186 of file pmc.c.
{
    uint32_t ul_timeout;
    PMC->PMC_MCKR = (PMC->PMC_MCKR & (~PMC_MCKR_CSS_Msk)) |
            PMC_MCKR_CSS_MAIN_CLK;
    for (ul_timeout = PMC_TIMEOUT; !(PMC->PMC_SR & PMC_SR_MCKRDY);
            --ul_timeout) {
        if (ul_timeout == 0) {
            return 1;
        }
    }
    PMC->PMC_MCKR = (PMC->PMC_MCKR & (~PMC_MCKR_PRES_Msk)) | ul_pres;
    for (ul_timeout = PMC_TIMEOUT; !(PMC->PMC_SR & PMC_SR_MCKRDY);
            --ul_timeout) {
        if (ul_timeout == 0) {
            return 1;
        }
    }
    return 0;
}
References PMC, PMC_MCKR_CSS_MAIN_CLK, PMC_SR_MCKRDY, and PMC_TIMEOUT.
Referenced by sysclk_init().
pmc_switch_mck_to_pllack()
uint32_t pmc_switch_mck_to_pllack (uint32_t ul_pres)
Switch master clock source selection to PLLA clock.
Parameters
ul_pres Processor clock prescaler.
Return values
0 Success.
1 Timeout error.
Definition at line 218 of file pmc.c.
{
    uint32_t ul_timeout;
    PMC->PMC_MCKR = (PMC->PMC_MCKR & (~PMC_MCKR_PRES_Msk)) | ul_pres;
    for (ul_timeout = PMC_TIMEOUT; !(PMC->PMC_SR & PMC_SR_MCKRDY);
            --ul_timeout) {
        if (ul_timeout == 0) {
            return 1;
        }
    }
    PMC->PMC_MCKR = (PMC->PMC_MCKR & (~PMC_MCKR_CSS_Msk)) |
            PMC_MCKR_CSS_PLLA_CLK;
    for (ul_timeout = PMC_TIMEOUT; !(PMC->PMC_SR & PMC_SR_MCKRDY);
            --ul_timeout) {
        if (ul_timeout == 0) {
            return 1;
        }
    }
    return 0;
}
References PMC, PMC_MCKR_CSS_PLLA_CLK, PMC_SR_MCKRDY, and PMC_TIMEOUT.
Referenced by sysclk_init().
pmc_switch_mck_to_sclk()
uint32_t pmc_switch_mck_to_sclk (uint32_t ul_pres)
Switch master clock source selection to slow clock.
Parameters
ul_pres Processor clock prescaler.
Return values
0 Success.
1 Timeout error.
Definition at line 154 of file pmc.c.
{
    uint32_t ul_timeout;
    PMC->PMC_MCKR = (PMC->PMC_MCKR & (~PMC_MCKR_CSS_Msk)) |
            PMC_MCKR_CSS_SLOW_CLK;
    for (ul_timeout = PMC_TIMEOUT; !(PMC->PMC_SR & PMC_SR_MCKRDY);
            --ul_timeout) {
        if (ul_timeout == 0) {
            return 1;
        }
    }
    PMC->PMC_MCKR = (PMC->PMC_MCKR & (~PMC_MCKR_PRES_Msk)) | ul_pres;
    for (ul_timeout = PMC_TIMEOUT; !(PMC->PMC_SR & PMC_SR_MCKRDY);
            --ul_timeout) {
        if (ul_timeout == 0) {
            return 1;
        }
    }
    return 0;
}
References PMC, PMC_MCKR_CSS_SLOW_CLK, PMC_SR_MCKRDY, and PMC_TIMEOUT.
Referenced by sysclk_init().
pmc_switch_pck_to_mainck()
uint32_t pmc_switch_pck_to_mainck (uint32_t ul_id, uint32_t ul_pres)
Switch programmable clock source selection to main clock.
Parameters
ul_id Id of the programmable clock.
ul_pres Programmable clock prescaler.
Return values
0 Success.
1 Timeout error.
Definition at line 898 of file pmc.c.
{
    uint32_t ul_timeout;
    PMC->PMC_PCK[ul_id] = PMC_PCK_CSS_MAIN_CLK | ul_pres;
    for (ul_timeout = PMC_TIMEOUT;
    !(PMC->PMC_SR & (PMC_SR_PCKRDY0 << ul_id)); --ul_timeout) {
        if (ul_timeout == 0) {
            return 1;
        }
    }
    return 0;
}
References PMC, PMC_PCK_CSS_MAIN_CLK, PMC_SR_PCKRDY0, and PMC_TIMEOUT.
pmc_switch_pck_to_mck()
uint32_t pmc_switch_pck_to_mck (uint32_t ul_id, uint32_t ul_pres)
Switch programmable clock source selection to mck.
Parameters
ul_id Id of the programmable clock.
ul_pres Programmable clock prescaler.
Return values
0 Success.
1 Timeout error.
Definition at line 1042 of file pmc.c.
{
    uint32_t ul_timeout;
    PMC->PMC_PCK[ul_id] = PMC_PCK_CSS_MCK | ul_pres;
    for (ul_timeout = PMC_TIMEOUT;
    !(PMC->PMC_SR & (PMC_SR_PCKRDY0 << ul_id)); --ul_timeout) {
        if (ul_timeout == 0) {
            return 1;
        }
    }
    return 0;
}
References PMC, PMC_PCK_CSS_MCK, PMC_SR_PCKRDY0, and PMC_TIMEOUT.
pmc_switch_pck_to_pllack()
uint32_t pmc_switch_pck_to_pllack (uint32_t ul_id, uint32_t ul_pres)
Switch programmable clock source selection to PLLA clock.
Parameters
ul_id Id of the programmable clock.
ul_pres Programmable clock prescaler.
Return values
0 Success.
1 Timeout error.
Definition at line 922 of file pmc.c.
{
    uint32_t ul_timeout;
    PMC->PMC_PCK[ul_id] = PMC_PCK_CSS_PLLA_CLK | ul_pres;
    for (ul_timeout = PMC_TIMEOUT;
    !(PMC->PMC_SR & (PMC_SR_PCKRDY0 << ul_id)); --ul_timeout) {
        if (ul_timeout == 0) {
            return 1;
        }
    }
    return 0;
}
References PMC, PMC_PCK_CSS_PLLA_CLK, PMC_SR_PCKRDY0, and PMC_TIMEOUT.
pmc_switch_pck_to_sclk()
uint32_t pmc_switch_pck_to_sclk (uint32_t ul_id, uint32_t ul_pres)
Switch programmable clock source selection to slow clock.
Parameters
ul_id Id of the programmable clock.
ul_pres Programmable clock prescaler.
Return values
0 Success.
1 Timeout error.
Definition at line 874 of file pmc.c.
{
    uint32_t ul_timeout;
    PMC->PMC_PCK[ul_id] = PMC_PCK_CSS_SLOW_CLK | ul_pres;
    for (ul_timeout = PMC_TIMEOUT;
    !(PMC->PMC_SR & (PMC_SR_PCKRDY0 << ul_id)); --ul_timeout) {
        if (ul_timeout == 0) {
            return 1;
        }
    }
    return 0;
}
References PMC, PMC_PCK_CSS_SLOW_CLK, PMC_SR_PCKRDY0, and PMC_TIMEOUT.
pmc_switch_sclk_to_32kxtal()
void pmc_switch_sclk_to_32kxtal (uint32_t ul_bypass)
Switch slow clock source selection to external 32k (Xtal or Bypass).
Note
Switching SCLK back to 32krc is only possible by shutting down the VDDIO power supply.
Parameters
ul_bypass 0 for Xtal, 1 for bypass.
Definition at line 319 of file pmc.c.
{
    /* Set Bypass mode if required */
    if (ul_bypass == 1) {
        SUPC->SUPC_MR |= SUPC_MR_KEY_PASSWD |
            SUPC_MR_OSCBYPASS;
    }
    SUPC->SUPC_CR = SUPC_CR_KEY_PASSWD | SUPC_CR_XTALSEL;
}
References SUPC, SUPC_CR_KEY_PASSWD, SUPC_CR_XTALSEL, SUPC_MR_KEY_PASSWD, and SUPC_MR_OSCBYPASS.
Referenced by osc_enable().