WINC1500 Weather Client Demo for SAME70 Xplained: Hot-Spot (Access-Point)
Hot-Spot (Access-Point)
WLAN » Functions
Here are listed all the functions that implement the Wifi Hot-Spot (Access-Point) APIs.
Functions
sint8 m2m_wifi_disable_ap (void)
Synchronous API to disable access point mode on the WINC IC.
sint8 m2m_wifi_enable_ap (CONST tstrM2MAPConfig *pstrM2MAPConfig)
Asynchronous API to enable access point (AKA "hot-spot") mode on the WINC IC.
sint8 m2m_wifi_enable_ap_ext (CONST tstrM2MAPModeConfig *pstrM2MAPModeConfig)
Asynchronous API to enable access point (AKA "hot-spot") mode on the WINC IC with extended options.
Detailed Description
Here are listed all the functions that implement the Wifi Hot-Spot (Access-Point) APIs.
Function Documentation
m2m_wifi_disable_ap()
NMI_API sint8 m2m_wifi_disable_ap (void)
Synchronous API to disable access point mode on the WINC IC.
Must be called only when the AP is enabled through the m2m_wifi_enable_ap function. Otherwise the call to this function will not be useful.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
See also
m2m_wifi_enable_ap
Definition at line 1477 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_DISABLE_AP, NULL, 0, NULL, 0, 0);
    return ret;
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_DISABLE_AP, and NULL.
m2m_wifi_enable_ap()
NMI_API sint8 m2m_wifi_enable_ap (CONST tstrM2MAPConfig * pstrM2MAPConfig)
Asynchronous API to enable access point (AKA "hot-spot") mode on the WINC IC.
The WINC IC supports the ability to operate as an access point with the following limitations:
Only 1 station may be associated at any given time.
Open system and WEP are the only security suites supported.
Parameters
[in] pstrM2MAPConfig A structure holding the AP configurations.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
Precondition
A Wi-Fi notification callback of type tpfAppWifiCb MUST be implemented and registered at initialization. Registering the callback is done through passing it to the m2m_wifi_init.
The event M2M_WIFI_REQ_DHCP_CONF must be handled in the callback.
The m2m_wifi_handle_events MUST be called to receive the responses in the callback.
Warning
This function is not allowed in STA mode.
See also
tpfAppWifiCb tenuM2mSecType m2m_wifi_init M2M_WIFI_REQ_DHCP_CONF tstrM2mWifiStateChanged tstrM2MAPConfig
Example
The code snippet demonstrates how the AP mode is enabled after the driver is initialized in the application's main function and the handling of the event M2M_WIFI_REQ_DHCP_CONF, to indicate successful connection.
#include "m2m_wifi.h"
#include "m2m_types.h"
void wifi_event_cb(uint8 u8WiFiEvent, void * pvMsg)
{
    switch(u8WiFiEvent)
    {
    case M2M_WIFI_REQ_DHCP_CONF:
        {
            uint8   *pu8IPAddress = (uint8*)pvMsg;
            printf("Associated STA has IP Address \"%u.%u.%u.%u\"\n",pu8IPAddress[0],pu8IPAddress[1],pu8IPAddress[2],pu8IPAddress[3]);
        }
        break;
    default:
        break;
    }
}
int main()
{
    tstrWifiInitParam   param;
    param.pfAppWifiCb   = wifi_event_cb;
    if(!m2m_wifi_init(&param))
    {
        tstrM2MAPConfig     apConfig;
        strcpy(apConfig.au8SSID, "WINC_SSID");
        apConfig.u8ListenChannel    = 1;
        apConfig.u8SecType          = M2M_WIFI_SEC_OPEN;
        apConfig.u8SsidHide         = 0;
        // IP Address
        apConfig.au8DHCPServerIP[0] = 192;
        apConfig.au8DHCPServerIP[1] = 168;
        apConfig.au8DHCPServerIP[2] = 1;
        apConfig.au8DHCPServerIP[3] = 1;
        // Trigger AP
        m2m_wifi_enable_ap(&apConfig);
        while(1)
        {
            m2m_wifi_handle_events(NULL);
        }
    }
}
Definition at line 1445 of file m2m_wifi.c.
{
    tstrM2MAPModeConfig strM2MAPModeConfig;
    m2m_memcpy((uint8 *)&strM2MAPModeConfig.strApConfig, (uint8 *)pstrM2MAPConfig, sizeof(tstrM2MAPConfig));
    m2m_memcpy(strM2MAPModeConfig.strApConfigExt.au8DefRouterIP, (uint8 *)pstrM2MAPConfig->au8DHCPServerIP, 4);
    m2m_memcpy(strM2MAPModeConfig.strApConfigExt.au8DNSServerIP, (uint8 *)pstrM2MAPConfig->au8DHCPServerIP, 4);
    strM2MAPModeConfig.strApConfigExt.au8SubnetMask[0] = 0;
    return m2m_wifi_enable_ap_ext(&strM2MAPModeConfig);
}
References tstrM2MAPConfigExt::au8DefRouterIP, tstrM2MAPConfigExt::au8DNSServerIP, tstrM2MAPConfigExt::au8SubnetMask, m2m_memcpy(), m2m_wifi_enable_ap_ext(), tstrM2MAPModeConfig::strApConfig, and tstrM2MAPModeConfig::strApConfigExt.
m2m_wifi_enable_ap_ext()
NMI_API sint8 m2m_wifi_enable_ap_ext (CONST tstrM2MAPModeConfig * pstrM2MAPModeConfig)
Asynchronous API to enable access point (AKA "hot-spot") mode on the WINC IC with extended options.
The WINC IC supports the ability to operate as an access point with the following limitations:
Only 1 station may be associated at any given time.
Open system and WEP are the only security suites supported.
Parameters
[in] pstrM2MAPModeConfig A structure holding the AP configurations.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC and a negative value otherwise.
Precondition
A Wi-Fi notification callback of type tpfAppWifiCb MUST be implemented and registered at initialization. Registering the callback is done through passing it to the m2m_wifi_init.
The event M2M_WIFI_REQ_DHCP_CONF must be handled in the callback.
The m2m_wifi_handle_events MUST be called to receive the responses in the callback.
Warning
This function is not allowed in STA mode.
See also
tpfAppWifiCb tenuM2mSecType m2m_wifi_init M2M_WIFI_REQ_DHCP_CONF tstrM2mWifiStateChanged tstrM2MAPModeConfig tstrM2MAPConfigExt
Example
The code snippet demonstrates how the AP mode is enabled after the driver is initialized in the application's main function and the handling of the event M2M_WIFI_REQ_DHCP_CONF, to indicate successful connection.
#include "m2m_wifi.h"
#include "m2m_types.h"
void wifi_event_cb(uint8 u8WiFiEvent, void * pvMsg)
{
    switch(u8WiFiEvent)
    {
    case M2M_WIFI_REQ_DHCP_CONF:
        {
            uint8   *pu8IPAddress = (uint8*)pvMsg;
            printf("Associated STA has IP Address \"%u.%u.%u.%u\"\n",pu8IPAddress[0],pu8IPAddress[1],pu8IPAddress[2],pu8IPAddress[3]);
        }
        break;
    default:
        break;
    }
}
int main()
{
    tstrWifiInitParam   param;
    param.pfAppWifiCb   = wifi_event_cb;
    if(!m2m_wifi_init(&param))
    {
        tstrM2MAPModeConfig     apModeConfig;
        strcpy(apConfig.strApConfig.au8SSID, "WINC_SSID");
        apModeConfig.strApConfig.u8ListenChannel    = 1;
        apModeConfig.strApConfig.u8SecType          = M2M_WIFI_SEC_OPEN;
        apModeConfig.strApConfig.u8SsidHide         = 0;
        // IP Address
        apModeConfig.strApConfig.au8DHCPServerIP[0] = 192;
        apModeConfig.strApConfig.au8DHCPServerIP[1] = 168;
        apModeConfig.strApConfig.au8DHCPServerIP[2] = 1;
        apModeConfig.strApConfig.au8DHCPServerIP[3] = 1;
        // Default router IP
        m2m_memcpy(apModeConfig.strApConfigExt.au8DefRouterIP, apModeConfig.strApConfig.au8DHCPServerIP, 4);
        // DNS Server IP
        m2m_memcpy(apModeConfig.strApConfigExt.au8DNSServerIP, apModeConfig.strApConfig.au8DHCPServerIP, 4);
        // Subnet mask
        apModeConfig.strApConfigExt.au8SubnetMask[0]    = 255;
        apModeConfig.strApConfigExt.au8SubnetMask[1]    = 255;
        apModeConfig.strApConfigExt.au8SubnetMask[2]    = 255;
        apModeConfig.strApConfigExt.au8SubnetMask[3]    = 0;
        // Trigger AP
        m2m_wifi_enable_ap_ext(&apModeConfig);
        while(1)
        {
            m2m_wifi_handle_events(NULL);
        }
    }
}
Definition at line 1458 of file m2m_wifi.c.
{
    sint8 ret = M2M_ERR_FAIL;
    if(M2M_SUCCESS == m2m_validate_ap_parameters(pstrM2MAPModeConfig))
    {
        ret = hif_send(M2M_REQ_GROUP_WIFI, (M2M_REQ_DATA_PKT|M2M_WIFI_REQ_ENABLE_AP), NULL, 0, (uint8 *)pstrM2MAPModeConfig, sizeof(tstrM2MAPModeConfig), 0);
    }
    return ret;
}
References hif_send(), M2M_ERR_FAIL, M2M_REQ_DATA_PKT, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, m2m_validate_ap_parameters(), M2M_WIFI_REQ_ENABLE_AP, and NULL.
Referenced by m2m_wifi_enable_ap().