WINC1500 Weather Client Demo for SAME70 Xplained: Generic Clock Management
Generic Clock Management
Clock Management
Generic clocks are configurable clocks which run outside the system clock domain.
Data Structures
struct genclk_config
Hardware representation of a set of generic clock parameters.
Programmable Clock Sources (PCK)
enum genclk_source {
GENCLK_PCK_SRC_SLCK_RC = 0 ,
GENCLK_PCK_SRC_SLCK_XTAL = 1 ,
GENCLK_PCK_SRC_SLCK_BYPASS = 2 ,
GENCLK_PCK_SRC_MAINCK_4M_RC = 3 ,
GENCLK_PCK_SRC_MAINCK_8M_RC = 4 ,
GENCLK_PCK_SRC_MAINCK_12M_RC = 5 ,
GENCLK_PCK_SRC_MAINCK_XTAL = 6 ,
GENCLK_PCK_SRC_MAINCK_BYPASS = 7 ,
GENCLK_PCK_SRC_PLLACK = 8 ,
GENCLK_PCK_SRC_MCK = 9
}
Programmable Clock Prescalers (PCK)
enum genclk_divider {
GENCLK_PCK_PRES_1 = PMC_PCK_PRES(0) ,
GENCLK_PCK_PRES_2 = PMC_PCK_PRES(1) ,
GENCLK_PCK_PRES_4 = PMC_PCK_PRES(2) ,
GENCLK_PCK_PRES_8 = PMC_PCK_PRES(3) ,
GENCLK_PCK_PRES_16 = PMC_PCK_PRES(4) ,
GENCLK_PCK_PRES_32 = PMC_PCK_PRES(5) ,
GENCLK_PCK_PRES_64 = PMC_PCK_PRES(6)
}
static void genclk_config_defaults (struct genclk_config *p_cfg, uint32_t ul_id)
static void genclk_config_read (struct genclk_config *p_cfg, uint32_t ul_id)
static void genclk_config_write (const struct genclk_config *p_cfg, uint32_t ul_id)
Enabling and disabling Generic Clocks
static void genclk_enable_config (unsigned int id, enum genclk_source src, unsigned int divider)
Enable the configuration defined by src and divider for the generic clock identified by id.
Programmable Clock Source and Prescaler configuration
static void genclk_config_set_source (struct genclk_config *p_cfg, enum genclk_source e_src)
Select a new source clock src in configuration cfg.
static void genclk_config_set_divider (struct genclk_config *p_cfg, uint32_t e_divider)
static void genclk_enable (const struct genclk_config *p_cfg, uint32_t ul_id)
static void genclk_disable (uint32_t ul_id)
static void genclk_enable_source (enum genclk_source e_src)
Enable the source clock src used by a generic clock.
Retrieves the current rate in Hz of the Programmable Clock Source
static uint32_t genclk_get_frequency_hz (uint32_t ul_id)
Programmable Clock Identifiers (PCK)
#define GENCLK_PCK_0 0
PCK0 ID.
#define GENCLK_PCK_1 1
PCK1 ID.
#define GENCLK_PCK_2 2
PCK2 ID.
Detailed Description
Generic clocks are configurable clocks which run outside the system clock domain.
They are often connected to peripherals which have an asynchronous component running independently of the bus clock, e.g. USB controllers, low-power timers and RTCs, etc.
Note that not all platforms have support for generic clocks; on such platforms, this API will not be available.
Macro Definition Documentation
GENCLK_PCK_0
#define GENCLK_PCK_0 0
PCK0 ID.
Definition at line 59 of file same70/genclk.h.
GENCLK_PCK_1
#define GENCLK_PCK_1 1
PCK1 ID.
Definition at line 60 of file same70/genclk.h.
GENCLK_PCK_2
#define GENCLK_PCK_2 2
PCK2 ID.
Definition at line 61 of file same70/genclk.h.
Enumeration Type Documentation
genclk_divider
enum genclk_divider
Enumerator
GENCLK_PCK_PRES_1
Set PCK clock prescaler to 1.
GENCLK_PCK_PRES_2
Set PCK clock prescaler to 2.
GENCLK_PCK_PRES_4
Set PCK clock prescaler to 4.
GENCLK_PCK_PRES_8
Set PCK clock prescaler to 8.
GENCLK_PCK_PRES_16
Set PCK clock prescaler to 16.
GENCLK_PCK_PRES_32
Set PCK clock prescaler to 32.
GENCLK_PCK_PRES_64
Set PCK clock prescaler to 64.
Definition at line 85 of file same70/genclk.h.
                    {
    GENCLK_PCK_PRES_1  = PMC_PCK_PRES(0),
    GENCLK_PCK_PRES_2  = PMC_PCK_PRES(1),
    GENCLK_PCK_PRES_4  = PMC_PCK_PRES(2),
    GENCLK_PCK_PRES_8  = PMC_PCK_PRES(3),
    GENCLK_PCK_PRES_16 = PMC_PCK_PRES(4),
    GENCLK_PCK_PRES_32 = PMC_PCK_PRES(5),
    GENCLK_PCK_PRES_64 = PMC_PCK_PRES(6),
};
genclk_source
enum genclk_source
Enumerator
GENCLK_PCK_SRC_SLCK_RC
Internal 32kHz RC oscillator as PCK source clock.
GENCLK_PCK_SRC_SLCK_XTAL
External 32kHz crystal oscillator as PCK source clock.
GENCLK_PCK_SRC_SLCK_BYPASS
External 32kHz bypass oscillator as PCK source clock.
GENCLK_PCK_SRC_MAINCK_4M_RC
Internal 4MHz RC oscillator as PCK source clock.
GENCLK_PCK_SRC_MAINCK_8M_RC
Internal 8MHz RC oscillator as PCK source clock.
GENCLK_PCK_SRC_MAINCK_12M_RC
Internal 12MHz RC oscillator as PCK source clock.
GENCLK_PCK_SRC_MAINCK_XTAL
External crystal oscillator as PCK source clock.
GENCLK_PCK_SRC_MAINCK_BYPASS
External bypass oscillator as PCK source clock.
GENCLK_PCK_SRC_PLLACK
Use PLLACK as PCK source clock.
GENCLK_PCK_SRC_MCK
Use Master Clk as PCK source clock.
Definition at line 67 of file same70/genclk.h.
                   {
    GENCLK_PCK_SRC_SLCK_RC       = 0,
    GENCLK_PCK_SRC_SLCK_XTAL     = 1,
    GENCLK_PCK_SRC_SLCK_BYPASS   = 2,
    GENCLK_PCK_SRC_MAINCK_4M_RC  = 3,
    GENCLK_PCK_SRC_MAINCK_8M_RC  = 4,
    GENCLK_PCK_SRC_MAINCK_12M_RC = 5,
    GENCLK_PCK_SRC_MAINCK_XTAL   = 6,
    GENCLK_PCK_SRC_MAINCK_BYPASS = 7,
    GENCLK_PCK_SRC_PLLACK        = 8,
    GENCLK_PCK_SRC_MCK           = 9,
};
Function Documentation
genclk_config_defaults()
static void genclk_config_defaults (struct genclk_config * p_cfg, uint32_t ul_id) inline static
Definition at line 101 of file same70/genclk.h.
{
    ul_id = ul_id;
    p_cfg->ctrl = 0;
}
References genclk_config::ctrl.
Referenced by genclk_enable_config().
genclk_config_read()
static void genclk_config_read (struct genclk_config * p_cfg, uint32_t ul_id) inline static
Definition at line 108 of file same70/genclk.h.
{
    p_cfg->ctrl = PMC->PMC_PCK[ul_id];
}
References genclk_config::ctrl, and PMC.
genclk_config_set_divider()
static void genclk_config_set_divider (struct genclk_config * p_cfg, uint32_t e_divider) inline static
Definition at line 156 of file same70/genclk.h.
{
    p_cfg->ctrl &= ~PMC_PCK_PRES_Msk;
    p_cfg->ctrl |= e_divider;
}
References genclk_config::ctrl.
Referenced by genclk_enable_config().
genclk_config_set_source()
void genclk_config_set_source (struct genclk_config * p_cfg, enum genclk_source e_src) inline static
Select a new source clock src in configuration cfg.
Definition at line 123 of file same70/genclk.h.
{
    p_cfg->ctrl &= (~PMC_PCK_CSS_Msk);
    switch (e_src) {
    case GENCLK_PCK_SRC_SLCK_RC:
    case GENCLK_PCK_SRC_SLCK_XTAL:
    case GENCLK_PCK_SRC_SLCK_BYPASS:
        p_cfg->ctrl |= (PMC_PCK_CSS_SLOW_CLK);
        break;
    case GENCLK_PCK_SRC_MAINCK_4M_RC:
    case GENCLK_PCK_SRC_MAINCK_8M_RC:
    case GENCLK_PCK_SRC_MAINCK_12M_RC:
    case GENCLK_PCK_SRC_MAINCK_XTAL:
    case GENCLK_PCK_SRC_MAINCK_BYPASS:
        p_cfg->ctrl |= (PMC_PCK_CSS_MAIN_CLK);
        break;
    case GENCLK_PCK_SRC_PLLACK:
        p_cfg->ctrl |= (PMC_PCK_CSS_PLLA_CLK);
        break;
    case GENCLK_PCK_SRC_MCK:
        p_cfg->ctrl |= (PMC_PCK_CSS_MCK);
        break;
    default:
        break;
    }
}
References genclk_config::ctrl, GENCLK_PCK_SRC_MAINCK_12M_RC, GENCLK_PCK_SRC_MAINCK_4M_RC, GENCLK_PCK_SRC_MAINCK_8M_RC, GENCLK_PCK_SRC_MAINCK_BYPASS, GENCLK_PCK_SRC_MAINCK_XTAL, GENCLK_PCK_SRC_MCK, GENCLK_PCK_SRC_PLLACK, GENCLK_PCK_SRC_SLCK_BYPASS, GENCLK_PCK_SRC_SLCK_RC, GENCLK_PCK_SRC_SLCK_XTAL, PMC_PCK_CSS_MAIN_CLK, PMC_PCK_CSS_MCK, PMC_PCK_CSS_PLLA_CLK, and PMC_PCK_CSS_SLOW_CLK.
Referenced by genclk_enable_config().
genclk_config_write()
static void genclk_config_write (const struct genclk_config * p_cfg, uint32_t ul_id) inline static
Definition at line 114 of file same70/genclk.h.
{
    PMC->PMC_PCK[ul_id] = p_cfg->ctrl;
}
References genclk_config::ctrl, and PMC.
genclk_disable()
static void genclk_disable (uint32_t ul_id) inline static
Definition at line 171 of file same70/genclk.h.
{
    pmc_disable_pck(ul_id);
}
References pmc_disable_pck().
genclk_enable()
static void genclk_enable (const struct genclk_config * p_cfg, uint32_t ul_id) inline static
Definition at line 165 of file same70/genclk.h.
{
    PMC->PMC_PCK[ul_id] = p_cfg->ctrl;
    pmc_enable_pck(ul_id);
}
References genclk_config::ctrl, PMC, and pmc_enable_pck().
Referenced by genclk_enable_config().
genclk_enable_config()
static void genclk_enable_config (unsigned int id, enum genclk_source src, unsigned int divider) inline static
Enable the configuration defined by src and divider for the generic clock identified by id.
Parameters
id The ID of the generic clock.
src The source clock of the generic clock.
divider The divider used to generate the generic clock.
Definition at line 176 of file genclk.h.
{
    struct genclk_config gcfg;
    genclk_config_defaults(&gcfg, id);
    genclk_enable_source(src);
    genclk_config_set_source(&gcfg, src);
    genclk_config_set_divider(&gcfg, divider);
    genclk_enable(&gcfg, id);
}
References genclk_config_defaults(), genclk_config_set_divider(), genclk_config_set_source(), genclk_enable(), and genclk_enable_source().
genclk_enable_source()
void genclk_enable_source (enum genclk_source e_src) inline static
Enable the source clock src used by a generic clock.
Definition at line 176 of file same70/genclk.h.
{
    switch (e_src) {
    case GENCLK_PCK_SRC_SLCK_RC:
        if (!osc_is_ready(OSC_SLCK_32K_RC)) {
            osc_enable(OSC_SLCK_32K_RC);
            osc_wait_ready(OSC_SLCK_32K_RC);
        }
        break;
    case GENCLK_PCK_SRC_SLCK_XTAL:
        if (!osc_is_ready(OSC_SLCK_32K_XTAL)) {
            osc_enable(OSC_SLCK_32K_XTAL);
            osc_wait_ready(OSC_SLCK_32K_XTAL);
        }
        break;
    case GENCLK_PCK_SRC_SLCK_BYPASS:
        if (!osc_is_ready(OSC_SLCK_32K_BYPASS)) {
            osc_enable(OSC_SLCK_32K_BYPASS);
            osc_wait_ready(OSC_SLCK_32K_BYPASS);
        }
        break;
    case GENCLK_PCK_SRC_MAINCK_4M_RC:
        if (!osc_is_ready(OSC_MAINCK_4M_RC)) {
            osc_enable(OSC_MAINCK_4M_RC);
            osc_wait_ready(OSC_MAINCK_4M_RC);
        }
        break;
    case GENCLK_PCK_SRC_MAINCK_8M_RC:
        if (!osc_is_ready(OSC_MAINCK_8M_RC)) {
            osc_enable(OSC_MAINCK_8M_RC);
            osc_wait_ready(OSC_MAINCK_8M_RC);
        }
        break;
    case GENCLK_PCK_SRC_MAINCK_12M_RC:
        if (!osc_is_ready(OSC_MAINCK_12M_RC)) {
            osc_enable(OSC_MAINCK_12M_RC);
            osc_wait_ready(OSC_MAINCK_12M_RC);
        }
        break;
    case GENCLK_PCK_SRC_MAINCK_XTAL:
        if (!osc_is_ready(OSC_MAINCK_XTAL)) {
            osc_enable(OSC_MAINCK_XTAL);
            osc_wait_ready(OSC_MAINCK_XTAL);
        }
        break;
    case GENCLK_PCK_SRC_MAINCK_BYPASS:
        if (!osc_is_ready(OSC_MAINCK_BYPASS)) {
            osc_enable(OSC_MAINCK_BYPASS);
            osc_wait_ready(OSC_MAINCK_BYPASS);
        }
        break;
#ifdef CONFIG_PLL0_SOURCE
    case GENCLK_PCK_SRC_PLLACK:
        pll_enable_config_defaults(0);
        break;
#endif
    case GENCLK_PCK_SRC_MCK:
        break;
    default:
        Assert(false);
        break;
    }
}
References Assert, GENCLK_PCK_SRC_MAINCK_12M_RC, GENCLK_PCK_SRC_MAINCK_4M_RC, GENCLK_PCK_SRC_MAINCK_8M_RC, GENCLK_PCK_SRC_MAINCK_BYPASS, GENCLK_PCK_SRC_MAINCK_XTAL, GENCLK_PCK_SRC_MCK, GENCLK_PCK_SRC_PLLACK, GENCLK_PCK_SRC_SLCK_BYPASS, GENCLK_PCK_SRC_SLCK_RC, GENCLK_PCK_SRC_SLCK_XTAL, osc_enable(), osc_is_ready(), OSC_MAINCK_12M_RC, OSC_MAINCK_4M_RC, OSC_MAINCK_8M_RC, OSC_MAINCK_BYPASS, OSC_MAINCK_XTAL, OSC_SLCK_32K_BYPASS, OSC_SLCK_32K_RC, OSC_SLCK_32K_XTAL, osc_wait_ready(), and pll_enable_config_defaults().
Referenced by genclk_enable_config().
genclk_get_frequency_hz()
static uint32_t genclk_get_frequency_hz (uint32_t ul_id) inline static
Definition at line 252 of file same70/genclk.h.
{
    uint32_t pck_source,clock_config;
    uint32_t pck_freq = 0;
    pck_source = (PMC->PMC_PCK[ul_id] & PMC_PCK_CSS_Msk) >> PMC_PCK_CSS_Pos;
    switch(pck_source)
    {
        case PMC_PCK_CSS_SLOW_CLK:
            if (pmc_get_slck_config())
                pck_freq = OSC_SLCK_32K_RC_HZ;
            else
                pck_freq = OSC_SLCK_32K_XTAL_HZ;
            break;
        case PMC_PCK_CSS_MAIN_CLK:
        case PMC_PCK_CSS_PLLA_CLK:
            clock_config = pmc_get_mainck_config();
            if (clock_config & CKGR_MOR_MOSCSEL)
            {
                switch(clock_config & CKGR_MOR_MOSCRCF_Msk)
                {
                    case CKGR_MOR_MOSCRCF_4_MHz:
                        pck_freq = OSC_MAINCK_4M_RC_HZ;
                        break;
                    case CKGR_MOR_MOSCRCF_8_MHz:
                        pck_freq = OSC_MAINCK_8M_RC_HZ;
                        break;
                    case CKGR_MOR_MOSCRCF_12_MHz:
                        pck_freq = OSC_MAINCK_12M_RC_HZ;
                        break;
                }
            }
            else
            {
                pck_freq = OSC_MAINCK_XTAL_HZ;
            }
            if (pck_source == PMC_PCK_CSS_PLLA_CLK)
            {
                clock_config = pmc_get_pllack_config();
                if ((clock_config & CKGR_PLLAR_DIVA_Msk) == 0)
                    return 0;
                pck_freq *= ((((clock_config & CKGR_PLLAR_MULA_Msk)>>CKGR_PLLAR_MULA_Pos) + 1)/(clock_config & CKGR_PLLAR_DIVA_Msk));
            }
            break;
        case PMC_PCK_CSS_UPLL_CLK:
            pck_freq = pmc_get_upllckdiv_config() ? PLL_UPLL_HZ/2: PLL_UPLL_HZ;
            break;
        case PMC_PCK_CSS_MCK:
            pck_freq = sysclk_get_main_hz();
            break;
        default:
            break;
    }
    pck_freq /= ((PMC->PMC_PCK[ul_id] & PMC_PCK_PRES_Msk) >> PMC_PCK_PRES_Pos)+1;
    return pck_freq;
}
References CKGR_MOR_MOSCRCF_12_MHz, CKGR_MOR_MOSCRCF_4_MHz, CKGR_MOR_MOSCRCF_8_MHz, CKGR_MOR_MOSCRCF_Msk, CKGR_MOR_MOSCSEL, CKGR_PLLAR_DIVA_Msk, CKGR_PLLAR_MULA_Msk, CKGR_PLLAR_MULA_Pos, OSC_MAINCK_12M_RC_HZ, OSC_MAINCK_4M_RC_HZ, OSC_MAINCK_8M_RC_HZ, OSC_MAINCK_XTAL_HZ, OSC_SLCK_32K_RC_HZ, OSC_SLCK_32K_XTAL_HZ, PLL_UPLL_HZ, PMC, PMC_PCK_CSS_MAIN_CLK, PMC_PCK_CSS_MCK, PMC_PCK_CSS_Msk, PMC_PCK_CSS_PLLA_CLK, PMC_PCK_CSS_Pos, PMC_PCK_CSS_SLOW_CLK, PMC_PCK_CSS_UPLL_CLK, PMC_PCK_PRES_Msk, PMC_PCK_PRES_Pos, and sysclk_get_main_hz().