WINC1500 Weather Client Demo for SAME70 Xplained: spi_flash_erase
spi_flash_erase
Spi Flash » Function
Functions
sint8 spi_flash_erase (uint32 u32Offset, uint32 u32Sz)
Erase a specified portion of SPI Flash.
.
Detailed Description
Function Documentation
spi_flash_erase()
sint8 spi_flash_erase (uint32 u32Offset, uint32 u32Sz)
Erase a specified portion of SPI Flash.
.
Parameters
[in] u32Offset Address (Offset) to erase from the SPI flash.
[in] u32Sz Size of SPI flash required to be erased.
Note
It is blocking function
Warning
Address (offset) plus size of data must not exceed flash size.
No firmware is required for writing to SPI flash.
In case of there is a running firmware, it is required to pause your firmware first before any trial to access SPI flash to avoid any racing between host and running firmware on bus using m2m_wifi_download_mode
It is blocking function
See also
m2m_wifi_download_mode, spi_flash_get_size
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 681 of file spi_flash.c.
{
    uint32 i = 0;
    sint8 ret = M2M_SUCCESS;
    uint8  tmp = 0;
#ifdef PROFILING
    uint32 t;
    t = GetTickCount();
#endif
    M2M_PRINT("\r\n>Start erasing...\r\n");
    for(i = u32Offset; i < (u32Sz +u32Offset); i += (16*FLASH_PAGE_SZ))
    {
        ret += spi_flash_write_enable();
        ret += spi_flash_read_status_reg(&tmp);
        ret += spi_flash_sector_erase(i + 10);
        ret += spi_flash_read_status_reg(&tmp);
        do
        {
            if(ret != M2M_SUCCESS) goto ERR;
            ret += spi_flash_read_status_reg(&tmp);
        }while(tmp & 0x01);
    }
    M2M_PRINT("Done\r\n");
#ifdef PROFILING
    M2M_PRINT("#Erase time = %f sec\n", (GetTickCount()-t)/1000.0);
#endif
ERR:
    return ret;
}
References FLASH_PAGE_SZ, M2M_PRINT, M2M_SUCCESS, spi_flash_read_status_reg(), spi_flash_sector_erase(), and spi_flash_write_enable().