WINC1500 Weather Client Demo for SAME70 Xplained: nm_bsp_interrupt_ctrl
nm_bsp_interrupt_ctrl
BSP » Functions
Synchronous enable/disable of WINC to host interrupts.
Functions
void nm_bsp_interrupt_ctrl (uint8 u8Enable)
Enable/Disable interrupts from the WINC.
Detailed Description
Synchronous enable/disable of WINC to host interrupts.
Function Documentation
nm_bsp_interrupt_ctrl()
void nm_bsp_interrupt_ctrl (uint8 u8Enable)
Enable/Disable interrupts from the WINC.
This function can be used to enable/disable the WINC to host interrupts, depending on how the driver is implemented. It is an internal driver function and shouldn't be called by the application.
Parameters
[in] u8Enable
'0' disable interrupts.
'1' enable interrupts.
Precondition
The interrupt must be registered using nm_bsp_register_isr first.
Note
Implementation of this function is host dependent and called by HIF layer.
See also
tpfNmBspIsr, nm_bsp_register_isr
Returns
None
Definition at line 159 of file nm_bsp_same70.c.
{
    if (u8Enable) {
        pio_get_interrupt_status(CONF_WINC_SPI_INT_PIO);
        pio_enable_interrupt(CONF_WINC_SPI_INT_PIO, CONF_WINC_SPI_INT_MASK);
    }
    else {
        pio_disable_interrupt(CONF_WINC_SPI_INT_PIO, CONF_WINC_SPI_INT_MASK);
    }
}
References CONF_WINC_SPI_INT_MASK, CONF_WINC_SPI_INT_PIO, pio_disable_interrupt(), pio_enable_interrupt(), and pio_get_interrupt_status().
Referenced by hif_handle_isr(), hif_set_rx_done(), and isr().