WINC1500 Weather Client Demo for SAME70 Xplained: nm_bsp_init
nm_bsp_init
BSP » Functions
Initialization for BSP (Board Support Package) such as Reset and Chip Enable Pins for WINC, delays, register ISR, enable/disable IRQ for WINC, etc.
Functions
sint8 nm_bsp_init (void)
This function is used to initialize the Board Support Package (BSP) in order to prepare the WINC before any WINC API calls.
Detailed Description
Initialization for BSP (Board Support Package) such as Reset and Chip Enable Pins for WINC, delays, register ISR, enable/disable IRQ for WINC, etc.
You must use this function at the head of your application to enable WINC and Host Driver to communicate with each other.
Function Documentation
nm_bsp_init()
sint8 nm_bsp_init (void)
This function is used to initialize the Board Support Package (BSP) in order to prepare the WINC before any WINC API calls.
The nm_bsp_init function is the first function that should be called at the beginning of every application to initialize the BSP and the WINC board. Otherwise, the rest of the BSP function calls will return with failure. This function should also be called after the WINC has been switched off with a successful call to nm_bsp_deinit in order to reinitialize the BSP before the Application can use any of the WINC APIs again. After the function initializes the WINC, a hard reset must be applied to start the WINC board by calling nm_bsp_reset.
Note
Implementation of this function is host dependent.
Warning
Omitting this function will lead to unavailability of host-chip communication.
See also
nm_bsp_deinit, nm_bsp_reset
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 71 of file nm_bsp_same70.c.
{
    gpfIsr = NULL;
    /* Initialize chip IOs. */
    init_chip_pins();
    /* Make sure a 1ms Systick is configured. */
    if (!(SysTick->CTRL & SysTick_CTRL_ENABLE_Msk && SysTick->CTRL & SysTick_CTRL_TICKINT_Msk)) {
        delay_init();
    }
    /* Perform chip reset. */
    nm_bsp_reset();
    return 0;
}
References delay_init, gpfIsr, init_chip_pins(), nm_bsp_reset(), and NULL.
Referenced by wifi_init().