WINC1500 Weather Client Demo for SAME70 Xplained: nm_bsp_sleep
nm_bsp_sleep
BSP » Functions
Sleep in units of milliseconds.
Functions
void nm_bsp_sleep (uint32 u32TimeMsec)
Used to put the host to sleep for the specified duration (in milliseconds). Forcing the host to sleep for extended period may lead to host not being able to respond to WINC board events. It is important to be considerate while choosing the sleep period.
Detailed Description
Sleep in units of milliseconds.
This function used by the HIF Layer on several different scenarios.
Function Documentation
nm_bsp_sleep()
void nm_bsp_sleep (uint32 u32TimeMsec)
Used to put the host to sleep for the specified duration (in milliseconds). Forcing the host to sleep for extended period may lead to host not being able to respond to WINC board events. It is important to be considerate while choosing the sleep period.
Parameters
[in] u32TimeMsec Time unit in milliseconds.
Precondition
Initialize nm_bsp_init first.
Note
Implementation of this function is host dependent.
Warning
Maximum value must nor exceed 4294967295 milliseconds which is equal to 4294967.295 seconds.
See also
nm_bsp_init
Returns
None
Definition at line 122 of file nm_bsp_same70.c.
{
    while(u32TimeMsec--) {
        delay_ms(4);
    }
}
References delay_ms.
Referenced by chip_reset(), chip_wake(), cpu_start(), hif_send(), nm_bsp_reset(), nm_bus_init(), wait_for_bootrom(), and wait_for_firmware_start().