WINC1500 Weather Client Demo for SAME70 Xplained: WINC1500 (Wi-Fi)
WINC1500 (Wi-Fi)
Macros
#define WIFI_1X_TLS_HS_FLAGS_DEFAULT
#define WIFI_1X_TLS_HS_FLAGS_PEER_AUTH NBIT1
#define WIFI_1X_TLS_HS_FLAGS_PEER_CERTTIMECHECK NBIT2
#define WIFI_1X_TLS_HS_FLAGS_REQUIRE_TIME NBIT3
#define WIFI_1X_TLS_HS_FLAGS_RSV5 NBIT5
#define WIFI_1X_TLS_HS_FLAGS_RSV7 NBIT7
#define WIFI_1X_TLS_HS_FLAGS_SESSION_CACHING NBIT4
#define WIFI_1X_TLS_HS_FLAGS_SPECIFY_ROOTCERT NBIT6
Functions
static sint8 m2m_validate_ap_parameters (CONST tstrM2MAPModeConfig *pstrM2MAPModeConfig)
static sint8 m2m_validate_scan_options (tstrM2MScanOption *ptstrM2MScanOption)
static void m2m_wifi_cb (uint8 u8OpCode, uint16 u16DataSize, uint32 u32Addr)
static sint8 m2m_wifi_connect_prepare_msg (tenuCredStoreOption enuCredStoreOption, tenuM2mSecType enuAuthType, uint16 u16AuthSize, tstrNetworkId *pstrNetworkId, tstrM2mWifiConnHdr *pstrWifiConn)
sint8 m2m_wifi_p2p (uint8 u8Channel)
sint8 m2m_wifi_p2p_disconnect (void)
sint8 m2m_wifi_set_battery_voltage (uint16 u16BattVoltx100)
Enable or Disable logs in run time (Disable Firmware logs will enhance the firmware start-up time and performance)
Variables
static uint8 gau81xRootSha1 [20] = {0}
static tpfAppWifiCb gpfAppWifiCb = NULL
static uint32 gu321xTlsHsFlags = WIFI_1X_TLS_HS_FLAGS_DEFAULT
static volatile uint8 gu8ChNum
static volatile uint8 gu8scanInProgress = 0
static volatile uint8 gu8WifiState = WIFI_STATE_DEINIT
Detailed Description
Macro Definition Documentation
WIFI_1X_TLS_HS_FLAGS_DEFAULT
#define WIFI_1X_TLS_HS_FLAGS_DEFAULT
Value:
            (           \
            WIFI_1X_TLS_HS_FLAGS_PEER_AUTH          \
        |   WIFI_1X_TLS_HS_FLAGS_PEER_CERTTIMECHECK \
        |   WIFI_1X_TLS_HS_FLAGS_SESSION_CACHING    \
)
Definition at line 61 of file m2m_wifi.c.
WIFI_1X_TLS_HS_FLAGS_PEER_AUTH
#define WIFI_1X_TLS_HS_FLAGS_PEER_AUTH NBIT1
Definition at line 47 of file m2m_wifi.c.
WIFI_1X_TLS_HS_FLAGS_PEER_CERTTIMECHECK
#define WIFI_1X_TLS_HS_FLAGS_PEER_CERTTIMECHECK NBIT2
Definition at line 49 of file m2m_wifi.c.
WIFI_1X_TLS_HS_FLAGS_REQUIRE_TIME
#define WIFI_1X_TLS_HS_FLAGS_REQUIRE_TIME NBIT3
Definition at line 51 of file m2m_wifi.c.
WIFI_1X_TLS_HS_FLAGS_RSV5
#define WIFI_1X_TLS_HS_FLAGS_RSV5 NBIT5
Definition at line 55 of file m2m_wifi.c.
WIFI_1X_TLS_HS_FLAGS_RSV7
#define WIFI_1X_TLS_HS_FLAGS_RSV7 NBIT7
Definition at line 59 of file m2m_wifi.c.
WIFI_1X_TLS_HS_FLAGS_SESSION_CACHING
#define WIFI_1X_TLS_HS_FLAGS_SESSION_CACHING NBIT4
Definition at line 53 of file m2m_wifi.c.
WIFI_1X_TLS_HS_FLAGS_SPECIFY_ROOTCERT
#define WIFI_1X_TLS_HS_FLAGS_SPECIFY_ROOTCERT NBIT6
Definition at line 57 of file m2m_wifi.c.
Function Documentation
m2m_validate_ap_parameters()
static sint8 m2m_validate_ap_parameters (CONST tstrM2MAPModeConfig * pstrM2MAPModeConfig) static
Definition at line 309 of file m2m_wifi.c.
{
    sint8 s8Ret = M2M_SUCCESS;
    /* Check for incoming pointer */
    if(pstrM2MAPModeConfig == NULL)
    {
        M2M_ERR("INVALID POINTER\n");
        s8Ret = M2M_ERR_FAIL;
        goto ERR1;
    }
    /* Check for SSID */
    if((m2m_strlen((uint8 *)pstrM2MAPModeConfig->strApConfig.au8SSID) <= 0) || (m2m_strlen((uint8 *)pstrM2MAPModeConfig->strApConfig.au8SSID) >= M2M_MAX_SSID_LEN))
    {
        M2M_ERR("INVALID SSID\n");
        s8Ret = M2M_ERR_FAIL;
        goto ERR1;
    }
    /* Check for Channel */
    if(pstrM2MAPModeConfig->strApConfig.u8ListenChannel > M2M_WIFI_CH_14 || pstrM2MAPModeConfig->strApConfig.u8ListenChannel < M2M_WIFI_CH_1)
    {
        M2M_ERR("INVALID CH\n");
        s8Ret = M2M_ERR_FAIL;
        goto ERR1;
    }
    /* Check for DHCP Server IP address */
    if(!(pstrM2MAPModeConfig->strApConfig.au8DHCPServerIP[0] || pstrM2MAPModeConfig->strApConfig.au8DHCPServerIP[1]))
    {
        if(!(pstrM2MAPModeConfig->strApConfig.au8DHCPServerIP[2]))
        {
            M2M_ERR("INVALID DHCP SERVER IP\n");
            s8Ret = M2M_ERR_FAIL;
            goto ERR1;
        }
    }
    /* Check for Security */
    if(pstrM2MAPModeConfig->strApConfig.u8SecType == M2M_WIFI_SEC_OPEN)
    {
        goto ERR1;
    }
    else if(pstrM2MAPModeConfig->strApConfig.u8SecType == M2M_WIFI_SEC_WEP)
    {
        /* Check for WEP Key index */
        if((pstrM2MAPModeConfig->strApConfig.u8KeyIndx == 0) || (pstrM2MAPModeConfig->strApConfig.u8KeyIndx > WEP_KEY_MAX_INDEX))
        {
            M2M_ERR("INVALID KEY INDEX\n");
            s8Ret = M2M_ERR_FAIL;
            goto ERR1;
        }
        /* Check for WEP Key size */
        if( (pstrM2MAPModeConfig->strApConfig.u8KeySz != WEP_40_KEY_STRING_SIZE) &&
            (pstrM2MAPModeConfig->strApConfig.u8KeySz != WEP_104_KEY_STRING_SIZE)
        )
        {
            M2M_ERR("INVALID KEY STRING SIZE\n");
            s8Ret = M2M_ERR_FAIL;
            goto ERR1;
        }
        if((m2m_strlen((uint8 *)pstrM2MAPModeConfig->strApConfig.au8WepKey) <= 0) || (m2m_strlen((uint8 *)pstrM2MAPModeConfig->strApConfig.au8WepKey) > WEP_104_KEY_STRING_SIZE))
        {
            M2M_ERR("INVALID KEY SIZE\n");
            s8Ret = M2M_ERR_FAIL;
            goto ERR1;
        }
    }
    else if(pstrM2MAPModeConfig->strApConfig.u8SecType == M2M_WIFI_SEC_WPA_PSK)
    {
        /* Check for WPA Key size */
        if( ((pstrM2MAPModeConfig->strApConfig.u8KeySz + 1) < M2M_MIN_PSK_LEN) || ((pstrM2MAPModeConfig->strApConfig.u8KeySz + 1) > M2M_MAX_PSK_LEN))
        {
            M2M_ERR("INVALID WPA KEY SIZE\n");
            s8Ret = M2M_ERR_FAIL;
            goto ERR1;
        }
    }
    else
    {
        M2M_ERR("INVALID AUTHENTICATION MODE\n");
        s8Ret = M2M_ERR_FAIL;
        goto ERR1;
    }
ERR1:
    return s8Ret;
}
References M2M_ERR, M2M_ERR_FAIL, M2M_MAX_PSK_LEN, M2M_MAX_SSID_LEN, M2M_MIN_PSK_LEN, m2m_strlen(), M2M_SUCCESS, M2M_WIFI_CH_1, M2M_WIFI_CH_14, M2M_WIFI_SEC_OPEN, M2M_WIFI_SEC_WEP, M2M_WIFI_SEC_WPA_PSK, NULL, WEP_104_KEY_STRING_SIZE, WEP_40_KEY_STRING_SIZE, and WEP_KEY_MAX_INDEX.
Referenced by m2m_wifi_enable_ap_ext(), and m2m_wifi_start_provision_mode_ext().
m2m_validate_scan_options()
static sint8 m2m_validate_scan_options (tstrM2MScanOption * ptstrM2MScanOption) static
Definition at line 394 of file m2m_wifi.c.
{
    sint8 s8Ret = M2M_SUCCESS;
    /* Check for incoming pointer */
    if(ptstrM2MScanOption == NULL)
    {
        M2M_ERR("INVALID POINTER\n");
        s8Ret = M2M_ERR_FAIL;
        goto ERR;
    }
    /* Check for valid No of slots */
    if(ptstrM2MScanOption->u8NumOfSlot == 0)
    {
        M2M_ERR("INVALID No of scan slots! %d\n",ptstrM2MScanOption->u8NumOfSlot);
        s8Ret = M2M_ERR_FAIL;
        goto ERR;
    }
    /* Check for valid time of slots */
    if(ptstrM2MScanOption->u8SlotTime < 10 || ptstrM2MScanOption->u8SlotTime > 250)
    {
        M2M_ERR("INVALID scan slot time! %d\n",ptstrM2MScanOption->u8SlotTime);
        s8Ret = M2M_ERR_FAIL;
        goto ERR;
    }
    /* Check for valid No of probe requests per slot */
    if((ptstrM2MScanOption->u8ProbesPerSlot == 0)||(ptstrM2MScanOption->u8ProbesPerSlot > M2M_SCAN_DEFAULT_NUM_PROBE))
    {
        M2M_ERR("INVALID No of probe requests per scan slot %d\n",ptstrM2MScanOption->u8ProbesPerSlot);
        s8Ret = M2M_ERR_FAIL;
        goto ERR;
    }
    /* Check for valid RSSI threshold */
    if(ptstrM2MScanOption->s8RssiThresh >= 0)
    {
        M2M_ERR("INVALID RSSI threshold %d \n",ptstrM2MScanOption->s8RssiThresh);
        s8Ret = M2M_ERR_FAIL;
    }
ERR:
    return s8Ret;
}
References M2M_ERR, M2M_ERR_FAIL, M2M_SCAN_DEFAULT_NUM_PROBE, M2M_SUCCESS, NULL, tstrM2MScanOption::s8RssiThresh, tstrM2MScanOption::u8NumOfSlot, tstrM2MScanOption::u8ProbesPerSlot, and tstrM2MScanOption::u8SlotTime.
Referenced by m2m_wifi_set_scan_options().
m2m_wifi_cb()
static void m2m_wifi_cb (uint8 u8OpCode, uint16 u16DataSize, uint32 u32Addr) static
Definition at line 93 of file m2m_wifi.c.
{
    uint8 rx_buf[8];
    if (u8OpCode == M2M_WIFI_RESP_CON_STATE_CHANGED)
    {
        tstrM2mWifiStateChanged strState;
        if (hif_receive(u32Addr, (uint8*) &strState,sizeof(tstrM2mWifiStateChanged), 0) == M2M_SUCCESS)
        {
            if (gpfAppWifiCb)
                gpfAppWifiCb(M2M_WIFI_RESP_CON_STATE_CHANGED, &strState);
        }
    }
    else if (u8OpCode == M2M_WIFI_RESP_GET_SYS_TIME)
    {
        tstrSystemTime strSysTime;
        if (hif_receive(u32Addr, (uint8*) &strSysTime,sizeof(tstrSystemTime), 0) == M2M_SUCCESS)
        {
            if (gpfAppWifiCb)
                gpfAppWifiCb(M2M_WIFI_RESP_GET_SYS_TIME, &strSysTime);
        }
    }
    else if(u8OpCode == M2M_WIFI_RESP_CONN_INFO)
    {
        tstrM2MConnInfo     strConnInfo;
        if(hif_receive(u32Addr, (uint8*)&strConnInfo, sizeof(tstrM2MConnInfo), 1) == M2M_SUCCESS)
        {
            if(gpfAppWifiCb)
                gpfAppWifiCb(M2M_WIFI_RESP_CONN_INFO, &strConnInfo);
        }
    }
    else if (u8OpCode == M2M_WIFI_RESP_MEMORY_RECOVER)
    {
#if 0
        if (hif_receive(u32Addr, rx_buf, 4, 1) == M2M_SUCCESS)
        {
            tstrM2mWifiStateChanged strState;
            m2m_memcpy((uint8*) &strState, rx_buf,sizeof(tstrM2mWifiStateChanged));
            if (app_wifi_recover_cb)
                app_wifi_recover_cb(strState.u8CurrState);
        }
#endif
    }
    else if (u8OpCode == M2M_WIFI_REQ_DHCP_CONF)
    {
        tstrM2MIPConfig strIpConfig;
        if (hif_receive(u32Addr, (uint8 *)&strIpConfig, sizeof(tstrM2MIPConfig), 0) == M2M_SUCCESS)
        {
            if (gpfAppWifiCb)
                gpfAppWifiCb(M2M_WIFI_REQ_DHCP_CONF, (uint8 *)&strIpConfig);
        }
    }
    else if (u8OpCode == M2M_WIFI_REQ_DHCP_FAILURE)
    {
        if (hif_receive(u32Addr, NULL, 0, 1) == M2M_SUCCESS)
        {
            if (gpfAppWifiCb)
                gpfAppWifiCb(M2M_WIFI_REQ_DHCP_FAILURE, NULL);
        }
    }
    else if (u8OpCode == M2M_WIFI_REQ_WPS)
    {
        tstrM2MWPSInfo strWps;
        m2m_memset((uint8*)&strWps,0,sizeof(tstrM2MWPSInfo));
        if(hif_receive(u32Addr, (uint8*)&strWps, sizeof(tstrM2MWPSInfo), 0) == M2M_SUCCESS)
        {
            if (gpfAppWifiCb)
                gpfAppWifiCb(M2M_WIFI_REQ_WPS, &strWps);
        }
    }
    else if (u8OpCode == M2M_WIFI_RESP_IP_CONFLICT)
    {
        uint32  u32ConflictedIP;
        if(hif_receive(u32Addr, (uint8 *)&u32ConflictedIP, sizeof(u32ConflictedIP), 0) == M2M_SUCCESS)
        {
            M2M_INFO("Conflicted IP \" %u.%u.%u.%u \" \n",
                BYTE_0(u32ConflictedIP),BYTE_1(u32ConflictedIP),BYTE_2(u32ConflictedIP),BYTE_3(u32ConflictedIP));
            if (gpfAppWifiCb)
                gpfAppWifiCb(M2M_WIFI_RESP_IP_CONFLICT, NULL);
        }
    }
    else if (u8OpCode == M2M_WIFI_RESP_SCAN_DONE)
    {
        tstrM2mScanDone strState;
        gu8scanInProgress = 0;
        if(hif_receive(u32Addr, (uint8*)&strState, sizeof(tstrM2mScanDone), 0) == M2M_SUCCESS)
        {
            gu8ChNum = strState.u8NumofCh;
            if (gpfAppWifiCb)
                gpfAppWifiCb(M2M_WIFI_RESP_SCAN_DONE, &strState);
        }
    }
    else if (u8OpCode == M2M_WIFI_RESP_SCAN_RESULT)
    {
        tstrM2mWifiscanResult strScanResult;
        if(hif_receive(u32Addr, (uint8*)&strScanResult, sizeof(tstrM2mWifiscanResult), 0) == M2M_SUCCESS)
        {
            if (gpfAppWifiCb)
                gpfAppWifiCb(M2M_WIFI_RESP_SCAN_RESULT, &strScanResult);
        }
    }
    else if (u8OpCode == M2M_WIFI_RESP_CURRENT_RSSI)
    {
        if (hif_receive(u32Addr, rx_buf, 4, 0) == M2M_SUCCESS)
        {
            if (gpfAppWifiCb)
                gpfAppWifiCb(M2M_WIFI_RESP_CURRENT_RSSI, rx_buf);
        }
    }
    else if (u8OpCode == M2M_WIFI_RESP_CLIENT_INFO)
    {
        if (hif_receive(u32Addr, rx_buf, 4, 0) == M2M_SUCCESS)
        {
            if (gpfAppWifiCb)
                gpfAppWifiCb(M2M_WIFI_RESP_CLIENT_INFO, rx_buf);
        }
    }
    else if(u8OpCode == M2M_WIFI_RESP_PROVISION_INFO)
    {
        tstrM2MProvisionInfo    strProvInfo;
        if(hif_receive(u32Addr, (uint8*)&strProvInfo, sizeof(tstrM2MProvisionInfo), 1) == M2M_SUCCESS)
        {
            if(gpfAppWifiCb)
                gpfAppWifiCb(M2M_WIFI_RESP_PROVISION_INFO, &strProvInfo);
        }
    }
    else if(u8OpCode == M2M_WIFI_RESP_DEFAULT_CONNECT)
    {
        tstrM2MDefaultConnResp  strResp;
        if(hif_receive(u32Addr, (uint8*)&strResp, sizeof(tstrM2MDefaultConnResp), 1) == M2M_SUCCESS)
        {
            if(gpfAppWifiCb)
                gpfAppWifiCb(M2M_WIFI_RESP_DEFAULT_CONNECT, &strResp);
        }
    }
    else if (u8OpCode == M2M_WIFI_REQRSP_DELETE_APID)
    {
        tstrM2MGenericResp strResp;
        if (hif_receive(u32Addr, (uint8*)&strResp, sizeof(tstrM2MGenericResp), 0) == M2M_SUCCESS)
        {
            if (gpfAppWifiCb)
                gpfAppWifiCb(M2M_WIFI_REQRSP_DELETE_APID, &strResp);
        }
    }
    else if(u8OpCode == M2M_WIFI_RESP_GET_PRNG)
    {
        tstrPrng strPrng;
        if(hif_receive(u32Addr, (uint8*)&strPrng,sizeof(tstrPrng), 0) == M2M_SUCCESS)
        {
            if(hif_receive(u32Addr + sizeof(tstrPrng),strPrng.pu8RngBuff,strPrng.u16PrngSize, 1) == M2M_SUCCESS)
            {
                if(gpfAppWifiCb)
                    gpfAppWifiCb(M2M_WIFI_RESP_GET_PRNG,&strPrng);
            }
        }
    }
#ifdef ETH_MODE
    else if(u8OpCode == M2M_WIFI_RESP_ETHERNET_RX_PACKET)
        {
            uint8 u8SetRxDone;
            tstrM2mIpRsvdPkt strM2mRsvd;
            if(hif_receive(u32Addr, (uint8 *)&strM2mRsvd ,sizeof(tstrM2mIpRsvdPkt), 0) == M2M_SUCCESS)
            {
                tstrM2mIpCtrlBuf  strM2mIpCtrlBuf;
                uint16 u16Offset = strM2mRsvd.u16PktOffset;
                strM2mIpCtrlBuf.u16RemainingDataSize = strM2mRsvd.u16PktSz;
                if((gpfAppEthCb) && (gau8ethRcvBuf) && (gu16ethRcvBufSize > 0))
                {
                    do
                    {
                        u8SetRxDone = 1;
                        if(strM2mIpCtrlBuf.u16RemainingDataSize > gu16ethRcvBufSize)
{
                            u8SetRxDone = 0;
                            strM2mIpCtrlBuf.u16DataSize = gu16ethRcvBufSize;
                        }
                        else
{
                            strM2mIpCtrlBuf.u16DataSize = strM2mIpCtrlBuf.u16RemainingDataSize;
                        }
                        if(hif_receive(u32Addr + u16Offset, gau8ethRcvBuf, strM2mIpCtrlBuf.u16DataSize, u8SetRxDone) == M2M_SUCCESS)
{
                            strM2mIpCtrlBuf.u16RemainingDataSize -= strM2mIpCtrlBuf.u16DataSize;
                            u16Offset += strM2mIpCtrlBuf.u16DataSize;
                            gpfAppEthCb(M2M_WIFI_RESP_ETHERNET_RX_PACKET, gau8ethRcvBuf, &(strM2mIpCtrlBuf));
                        }
                        else
{
                            break;
                        }
                    }while (strM2mIpCtrlBuf.u16RemainingDataSize > 0);
                }
            }
        }
#endif  /* ETH_MODE */
    else
    {
        M2M_ERR("REQ Not defined %d\n",u8OpCode);
    }
}
References BYTE_0, BYTE_1, BYTE_2, BYTE_3, gpfAppWifiCb, gu8ChNum, gu8scanInProgress, hif_receive(), M2M_ERR, M2M_INFO, m2m_memcpy(), m2m_memset(), M2M_SUCCESS, M2M_WIFI_REQ_DHCP_CONF, M2M_WIFI_REQ_DHCP_FAILURE, M2M_WIFI_REQ_WPS, M2M_WIFI_REQRSP_DELETE_APID, M2M_WIFI_RESP_CLIENT_INFO, M2M_WIFI_RESP_CON_STATE_CHANGED, M2M_WIFI_RESP_CONN_INFO, M2M_WIFI_RESP_CURRENT_RSSI, M2M_WIFI_RESP_DEFAULT_CONNECT, M2M_WIFI_RESP_ETHERNET_RX_PACKET, M2M_WIFI_RESP_GET_PRNG, M2M_WIFI_RESP_GET_SYS_TIME, M2M_WIFI_RESP_IP_CONFLICT, M2M_WIFI_RESP_MEMORY_RECOVER, M2M_WIFI_RESP_PROVISION_INFO, M2M_WIFI_RESP_SCAN_DONE, M2M_WIFI_RESP_SCAN_RESULT, NULL, tstrPrng::pu8RngBuff, tstrM2mIpCtrlBuf::u16DataSize, tstrM2mIpRsvdPkt::u16PktOffset, tstrM2mIpRsvdPkt::u16PktSz, tstrPrng::u16PrngSize, tstrM2mIpCtrlBuf::u16RemainingDataSize, tstrM2mWifiStateChanged::u8CurrState, and tstrM2mScanDone::u8NumofCh.
Referenced by m2m_wifi_init_start().
m2m_wifi_connect_prepare_msg()
static sint8 m2m_wifi_connect_prepare_msg (tenuCredStoreOption enuCredStoreOption, tenuM2mSecType enuAuthType, uint16 u16AuthSize, tstrNetworkId * pstrNetworkId, tstrM2mWifiConnHdr * pstrWifiConn) static
Definition at line 571 of file m2m_wifi.c.
{
    sint8   ret = M2M_ERR_FAIL;
    uint16  u16CredSize = sizeof(tstrM2mConnCredCmn) + u16AuthSize;
    /* Check application params. */
    if (
            (pstrNetworkId == NULL)
        ||  (pstrNetworkId->pu8Ssid == NULL)
        ||  (pstrNetworkId->u8SsidLen >= M2M_MAX_SSID_LEN)
    )
        goto INVALID_ARG;
    if (pstrWifiConn != NULL)
    {
        tstrM2mConnCredHdr  *pstrHdr = &pstrWifiConn->strConnCredHdr;
        tstrM2mConnCredCmn  *pstrCmn = &pstrWifiConn->strConnCredCmn;
        m2m_memset((uint8*)pstrWifiConn, 0, sizeof(tstrM2mWifiConnHdr));
        pstrHdr->u16CredSize = u16CredSize;
        switch (enuCredStoreOption)
        {
            case WIFI_CRED_SAVE_ENCRYPTED:
                pstrHdr->u8CredStoreFlags |= M2M_CRED_ENCRYPT_FLAG;
            // intentional fall through...
            case WIFI_CRED_SAVE_UNENCRYPTED:
                pstrHdr->u8CredStoreFlags |= M2M_CRED_STORE_FLAG;
            // intentional fall through...
            case WIFI_CRED_DONTSAVE:
                break;
            default:
                goto INVALID_ARG;
        }
        if (pstrNetworkId->enuChannel == M2M_WIFI_CH_ALL)
            pstrHdr->u8Channel = (uint8)(pstrNetworkId->enuChannel);
        else if ((pstrNetworkId->enuChannel <= M2M_WIFI_CH_14) && (pstrNetworkId->enuChannel >= M2M_WIFI_CH_1))
            pstrHdr->u8Channel = (uint8)(pstrNetworkId->enuChannel) - 1;
        else
            goto INVALID_ARG;
        if ((enuAuthType == M2M_WIFI_SEC_INVALID) || (enuAuthType >= M2M_WIFI_NUM_AUTH_TYPES))
            goto INVALID_ARG;
        pstrCmn->u8AuthType = (uint8)enuAuthType;
        pstrCmn->u8SsidLen = pstrNetworkId->u8SsidLen;
        m2m_memcpy(pstrCmn->au8Ssid, pstrNetworkId->pu8Ssid, pstrNetworkId->u8SsidLen);
        if (pstrNetworkId->pu8Bssid != NULL)
        {
            pstrCmn->u8Options = M2M_WIFI_CONN_BSSID_FLAG;
            m2m_memcpy(pstrCmn->au8Bssid, pstrNetworkId->pu8Bssid, M2M_MAC_ADDRES_LEN);
        }
        /* Everything is ok, set return value. */
        ret = M2M_SUCCESS;
    }
    return ret;
INVALID_ARG:
    return M2M_ERR_INVALID_ARG;
}
References tstrM2mConnCredCmn::au8Bssid, tstrM2mConnCredCmn::au8Ssid, tstrNetworkId::enuChannel, M2M_CRED_ENCRYPT_FLAG, M2M_CRED_STORE_FLAG, M2M_ERR_FAIL, M2M_ERR_INVALID_ARG, M2M_MAC_ADDRES_LEN, M2M_MAX_SSID_LEN, m2m_memcpy(), m2m_memset(), M2M_SUCCESS, M2M_WIFI_CH_1, M2M_WIFI_CH_14, M2M_WIFI_CH_ALL, M2M_WIFI_CONN_BSSID_FLAG, M2M_WIFI_NUM_AUTH_TYPES, M2M_WIFI_SEC_INVALID, NULL, tstrNetworkId::pu8Bssid, tstrNetworkId::pu8Ssid, tstrM2mWifiConnHdr::strConnCredCmn, tstrM2mWifiConnHdr::strConnCredHdr, tstrM2mConnCredHdr::u16CredSize, tstrM2mConnCredCmn::u8AuthType, tstrM2mConnCredHdr::u8Channel, tstrM2mConnCredHdr::u8CredStoreFlags, tstrM2mConnCredCmn::u8Options, tstrM2mConnCredCmn::u8SsidLen, tstrNetworkId::u8SsidLen, WIFI_CRED_DONTSAVE, WIFI_CRED_SAVE_ENCRYPTED, and WIFI_CRED_SAVE_UNENCRYPTED.
Referenced by m2m_wifi_connect_1x_mschap2(), m2m_wifi_connect_1x_tls(), m2m_wifi_connect_open(), m2m_wifi_connect_psk(), and m2m_wifi_connect_wep().
m2m_wifi_p2p()
sint8 m2m_wifi_p2p (uint8 u8Channel)
Definition at line 1422 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    if((u8Channel == M2M_WIFI_CH_1) || (u8Channel == M2M_WIFI_CH_6) || (u8Channel == M2M_WIFI_CH_11))
    {
        tstrM2MP2PConnect strtmp;
        strtmp.u8ListenChannel = u8Channel;
        ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_ENABLE_P2P, (uint8*)&strtmp, sizeof(tstrM2MP2PConnect), NULL, 0,0);
    }
    else
    {
        M2M_ERR("Listen channel should only be M2M_WIFI_CH_1/6/11 \n");
        ret = M2M_ERR_FAIL;
    }
    return ret;
}
References hif_send(), M2M_ERR, M2M_ERR_FAIL, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_CH_1, M2M_WIFI_CH_11, M2M_WIFI_CH_6, and NULL.
m2m_wifi_p2p_disconnect()
sint8 m2m_wifi_p2p_disconnect (void)
Definition at line 1438 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_DISABLE_P2P, NULL, 0, NULL, 0, 0);
    return ret;
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_SUCCESS, and NULL.
m2m_wifi_set_battery_voltage()
NMI_API sint8 m2m_wifi_set_battery_voltage (uint16 u16BattVoltx100)
Enable or Disable logs in run time (Disable Firmware logs will enhance the firmware start-up time and performance)
Parameters
[in] u16BattVoltx100 battery voltage multiplied by 100
Returns
The function SHALL return M2M_SUCCESS for success and a negative value otherwise.
See also
DISABLE_FIRMWARE_LOGS (build option to disable logs from initializations)
Precondition
m2m_wifi_init
Warning
Definition at line 1895 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    tstrM2mBatteryVoltage strM2mBattVol = {0};
    strM2mBattVol.u16BattVolt = u16BattVoltx100;
    ret = hif_send(M2M_REQ_GROUP_WIFI, M2M_WIFI_REQ_SET_BATTERY_VOLTAGE, (uint8*)&strM2mBattVol,sizeof(tstrM2mBatteryVoltage), NULL, 0, 0);
    return ret;
}
References hif_send(), M2M_REQ_GROUP_WIFI, M2M_SUCCESS, M2M_WIFI_REQ_SET_BATTERY_VOLTAGE, NULL, and tstrM2mBatteryVoltage::u16BattVolt.
Variable Documentation
gau81xRootSha1
uint8 gau81xRootSha1[20] = {0} static
Definition at line 73 of file m2m_wifi.c.
Referenced by m2m_wifi_1x_get_option(), m2m_wifi_1x_set_option(), m2m_wifi_connect_1x_mschap2(), and m2m_wifi_connect_1x_tls().
gpfAppWifiCb
tpfAppWifiCb gpfAppWifiCb = NULL static
Definition at line 69 of file m2m_wifi.c.
Referenced by m2m_wifi_cb(), and m2m_wifi_init_start().
gu321xTlsHsFlags
uint32 gu321xTlsHsFlags = WIFI_1X_TLS_HS_FLAGS_DEFAULT static
Definition at line 72 of file m2m_wifi.c.
Referenced by m2m_wifi_1x_get_option(), m2m_wifi_1x_set_option(), m2m_wifi_connect_1x_mschap2(), and m2m_wifi_connect_1x_tls().
gu8ChNum
volatile uint8 gu8ChNum static
Definition at line 67 of file m2m_wifi.c.
Referenced by m2m_wifi_cb(), and m2m_wifi_get_num_ap_found().
gu8scanInProgress
volatile uint8 gu8scanInProgress = 0 static
Definition at line 70 of file m2m_wifi.c.
Referenced by m2m_wifi_cb(), m2m_wifi_init_start(), m2m_wifi_request_scan(), m2m_wifi_request_scan_passive(), m2m_wifi_request_scan_ssid_list(), m2m_wifi_start_provision_mode_ext(), and m2m_wifi_wps().
gu8WifiState
volatile uint8 gu8WifiState = WIFI_STATE_DEINIT static
Definition at line 68 of file m2m_wifi.c.
Referenced by m2m_wifi_deinit(), m2m_wifi_download_mode(), m2m_wifi_get_state(), m2m_wifi_init_hold(), and m2m_wifi_init_start().