WINC1500 Weather Client Demo for SAME70 Xplained: Generic board support
Generic board support
The generic board support module includes board-specific definitions and function prototypes, such as the board initialization function.
Functions
void board_init (void)
This function initializes the board target resources.
Base Boards
#define EVK1100 1
AT32UC3A EVK1100 board.
#define EVK1101 2
AT32UC3B EVK1101 board.
#define UC3C_EK 3
AT32UC3C UC3C-EK board.
#define EVK1104 4
AT32UC3A3 EVK1104 board.
#define EVK1105 5
AT32UC3A EVK1105 board.
#define STK600_RCUC3L0 6
STK600 RCUC3L0 board.
#define UC3L_EK 7
AT32UC3L-EK board.
#define XPLAIN 8
ATxmega128A1 Xplain board.
#define STK600_RC064X 10
ATxmega256A3 STK600 board.
#define STK600_RC100X 11
ATxmega128A1 STK600 board.
#define UC3_A3_XPLAINED 13
ATUC3A3 UC3-A3 Xplained board.
#define UC3_L0_XPLAINED 15
ATUC3L0 UC3-L0 Xplained board.
#define STK600_RCUC3D 16
STK600 RCUC3D board.
#define STK600_RCUC3C0 17
STK600 RCUC3C board.
#define XMEGA_B1_XPLAINED 18
ATxmega128B1 Xplained board.
#define XMEGA_A1_XPLAINED 19
ATxmega128A1 Xplain-A1 board.
#define XMEGA_A1U_XPLAINED_PRO 20
ATxmega128A1U XMEGA-A1U Xplained Pro board.
#define STK600_RCUC3L4 21
ATUCL4 STK600 board.
#define UC3_L0_XPLAINED_BC 22
ATUC3L0 UC3-L0 Xplained board controller board.
#define MEGA1284P_XPLAINED_BC 23
ATmega1284P-Xplained board controller board.
#define STK600_RC044X 24
STK600 with RC044X routing card board.
#define STK600_RCUC3B0 25
STK600 RCUC3B0 board.
#define UC3_L0_QT600 26
QT600 UC3L0 MCU board.
#define XMEGA_A3BU_XPLAINED 27
ATxmega256A3BU Xplained board.
#define STK600_RC064X_LCDX 28
XMEGAB3 STK600 RC064X LCDX board.
#define STK600_RC100X_LCDX 29
XMEGAB1 STK600 RC100X LCDX board.
#define UC3B_BOARD_CONTROLLER 30
AT32UC3B1 board controller for Atmel boards.
#define RZ600 31
AT32UC3A RZ600 MCU board.
#define SAM3S_EK 32
SAM3S-EK board.
#define SAM3U_EK 33
SAM3U-EK board.
#define SAM3X_EK 34
SAM3X-EK board.
#define SAM3N_EK 35
SAM3N-EK board.
#define SAM3S_EK2 36
SAM3S-EK2 board.
#define SAM4S_EK 37
SAM4S-EK board.
#define STK600_RCUC3A0 38
STK600 RCUC3A0 board.
#define STK600_MEGA 39
STK600 MEGA board.
#define MEGA_1284P_XPLAINED 40
ATmega1284P Xplained board.
#define SAM4S_XPLAINED 41
SAM4S Xplained board.
#define ATXMEGA128A1_QT600 42
QT600 ATXMEGA128A1 MCU board.
#define ARDUINO_DUE_X 43
Arduino Due/X board.
#define STK600_RCUC3L3 44
ATUCL3 STK600 board.
#define SAM4L_EK 45
SAM4L-EK board.
#define STK600_MEGA_RF 46
STK600 MEGA RF EVK board.
#define XMEGA_C3_XPLAINED 47
ATxmega384C3 Xplained board.
#define STK600_RC032X 48
STK600 with RC032X routing card board.
#define SAM4S_EK2 49
SAM4S-EK2 board.
#define XMEGA_E5_XPLAINED 50
ATxmega32E5 Xplained board.
#define SAM4E_EK 51
SAM4E-EK board.
#define ATMEGA256RFR2_XPLAINED_PRO 52
ATmega256RFR2 Xplained Pro board.
#define SAM4S_XPLAINED_PRO 53
SAM4S Xplained Pro board.
#define SAM4L_XPLAINED_PRO 54
SAM4L Xplained Pro board.
#define ATMEGA256RFR2_ZIGBIT 55
ATmega256RFR2 zigbit.
#define XMEGA_RF233_ZIGBIT 56
ATxmega256A3U with AT86RF233 Zigbit.
#define XMEGA_RF212B_ZIGBIT 57
ATxmega256A3U with AT86RF212B Zigbit.
#define SAM4S_WPIR_RD 58
SAM4S-WPIR-RD board.
#define SAMD20_XPLAINED_PRO 59
SAM D20 Xplained Pro board.
#define SAM4L8_XPLAINED_PRO 60
SAM4L8 Xplained Pro board.
#define SAM4N_XPLAINED_PRO 61
SAM4N Xplained Pro board.
#define XMEGA_A3_REB_CBB 62
XMEGA REB Controller Base board.
#define ATMEGARFX_RCB 63
RFR2 & RFA1 RCB.
#define SAM4C_EK 64
SAM4C-EK board.
#define RCB256RFR2_XPRO 65
RFR2 RCB Xplained Pro board.
#define SAMG53_XPLAINED_PRO 66
SAMG53 Xplained Pro board.
#define SAM4CP16BMB 67
SAM4CP16BMB board.
#define SAM4E_XPLAINED_PRO 68
SAM4E Xplained Pro board.
#define SAMD21_XPLAINED_PRO 69
SAM D21 Xplained Pro board.
#define SAMR21_XPLAINED_PRO 70
SAM R21 Xplained Pro board.
#define SAM4CMP_DB 71
SAM4CMP demo board.
#define SAM4CMS_DB 72
SAM4CMS demo board.
#define ATPL230AMB 73
ATPL230AMB board.
#define SAMD11_XPLAINED_PRO 74
SAM D11 Xplained Pro board.
#define SAMG55_XPLAINED_PRO 75
SAMG55 Xplained Pro board.
#define SAML21_XPLAINED_PRO 76
SAM L21 Xplained Pro board.
#define SAMD10_XPLAINED_MINI 77
SAM D10 Xplained Mini board.
#define SAMDA1_XPLAINED_PRO 78
SAM DA1 Xplained Pro board.
#define SAMW25_XPLAINED_PRO 79
SAMW25 Xplained Pro board.
#define SAMC21_XPLAINED_PRO 80
SAM C21 Xplained Pro board.
#define SAMV71_XPLAINED_ULTRA 81
SAMV71 Xplained Ultra board.
#define ATMEGA328P_XPLAINED_MINI 82
ATMEGA328P Xplained MINI board.
#define ATMEGA328PB_XPLAINED_MINI 83
ATMEGA328PB Xplained MINI board.
#define SAMB11_XPLAINED_PRO 84
SAM B11 Xplained Pro board.
#define SAME70_XPLAINED 85
SAME70 Xplained board.
#define SAML22_XPLAINED_PRO 86
SAM L22 Xplained Pro board.
#define SAML22_XPLAINED_PRO_B 87
SAM L22 Xplained Pro board.
#define SAMR21ZLL_EK 88
SAMR21ZLL-EK board.
#define ATMEGA168PB_XPLAINED_MINI 89
ATMEGA168PB Xplained MINI board.
#define ATMEGA324PB_XPLAINED_PRO 90
ATMEGA324PB Xplained Pro board.
#define SAMB11ZR_XPLAINED_PRO 92
SAM B11 ZR Xplained Pro board.
#define SAMR30_XPLAINED_PRO 93
SAM R30 Xplained Pro board.
#define SAMHA1G16A_XPLAINED_PRO 94
SAM HA1G16A Xplained Pro board.
#define SAMR34_XPLAINED_PRO 95
SAM R34 Xplained Pro board.
#define SIMULATOR_XMEGA_A1 97
Simulator for XMEGA A1 devices.
#define AVR_SIMULATOR_UC3 98
Simulator for the AVR UC3 device family.
#define USER_BOARD 99
User-reserved board (if any).
#define DUMMY_BOARD 100
Dummy board to support board-independent applications (e.g. bootloader).
#define SAMB11ZR_SENSOR_TAG 101
SAMB11ZR sensor tag board.
#define SAMR30_MODULE_XPLAINED_PRO 102
SAM R30 Module Xplained Pro board.
#define SAMR21G18_MODULE 103
SAMR21G18-MR210UA Module.
#define SAMR21B18_MODULE 104
SAMR21B18-MZ210PA Module.
#define WLR089_XPLAINED_PRO 105
WLR089_XPLAINED_PRO board.
Extension Boards
#define EXT1102 1
AT32UC3B EXT1102 board.
#define MC300 2
AT32UC3 MC300 board.
#define SENSORS_XPLAINED_INERTIAL_1 3
Xplained inertial sensor board 1.
#define SENSORS_XPLAINED_INERTIAL_2 4
Xplained inertial sensor board 2.
#define SENSORS_XPLAINED_PRESSURE_1 5
Xplained pressure sensor board.
#define SENSORS_XPLAINED_LIGHTPROX_1 6
Xplained light & proximity sensor board.
#define SENSORS_XPLAINED_INERTIAL_A1 7
Xplained inertial sensor board "A".
#define RZ600_AT86RF231 8
AT86RF231 RF board in RZ600.
#define RZ600_AT86RF230B 9
AT86RF230B RF board in RZ600.
#define RZ600_AT86RF212 10
AT86RF212 RF board in RZ600.
#define SENSORS_XPLAINED_BREADBOARD 11
Xplained sensor development breadboard.
#define SECURITY_XPLAINED 12
Xplained ATSHA204 board.
#define USER_EXT_BOARD 99
User-reserved extension board (if any).
Detailed Description
The generic board support module includes board-specific definitions and function prototypes, such as the board initialization function.
Macro Definition Documentation
ARDUINO_DUE_X
#define ARDUINO_DUE_X 43
Arduino Due/X board.
Definition at line 101 of file board.h.
ATMEGA168PB_XPLAINED_MINI
#define ATMEGA168PB_XPLAINED_MINI 89
ATMEGA168PB Xplained MINI board.
Definition at line 147 of file board.h.
ATMEGA256RFR2_XPLAINED_PRO
#define ATMEGA256RFR2_XPLAINED_PRO 52
ATmega256RFR2 Xplained Pro board.
Definition at line 110 of file board.h.
ATMEGA256RFR2_ZIGBIT
#define ATMEGA256RFR2_ZIGBIT 55
ATmega256RFR2 zigbit.
Definition at line 113 of file board.h.
ATMEGA324PB_XPLAINED_PRO
#define ATMEGA324PB_XPLAINED_PRO 90
ATMEGA324PB Xplained Pro board.
Definition at line 148 of file board.h.
ATMEGA328P_XPLAINED_MINI
#define ATMEGA328P_XPLAINED_MINI 82
ATMEGA328P Xplained MINI board.
Definition at line 140 of file board.h.
ATMEGA328PB_XPLAINED_MINI
#define ATMEGA328PB_XPLAINED_MINI 83
ATMEGA328PB Xplained MINI board.
Definition at line 141 of file board.h.
ATMEGARFX_RCB
#define ATMEGARFX_RCB 63
RFR2 & RFA1 RCB.
Definition at line 121 of file board.h.
ATPL230AMB
#define ATPL230AMB 73
ATPL230AMB board.
Definition at line 131 of file board.h.
ATXMEGA128A1_QT600
#define ATXMEGA128A1_QT600 42
QT600 ATXMEGA128A1 MCU board.
Definition at line 100 of file board.h.
AVR_SIMULATOR_UC3
#define AVR_SIMULATOR_UC3 98
Simulator for the AVR UC3 device family.
Definition at line 154 of file board.h.
DUMMY_BOARD
#define DUMMY_BOARD 100
Dummy board to support board-independent applications (e.g. bootloader).
Definition at line 156 of file board.h.
EVK1100
#define EVK1100 1
AT32UC3A EVK1100 board.
Definition at line 62 of file board.h.
EVK1101
#define EVK1101 2
AT32UC3B EVK1101 board.
Definition at line 63 of file board.h.
EVK1104
#define EVK1104 4
AT32UC3A3 EVK1104 board.
Definition at line 65 of file board.h.
EVK1105
#define EVK1105 5
AT32UC3A EVK1105 board.
Definition at line 66 of file board.h.
EXT1102
#define EXT1102 1
AT32UC3B EXT1102 board.
Definition at line 167 of file board.h.
MC300
#define MC300 2
AT32UC3 MC300 board.
Definition at line 168 of file board.h.
MEGA1284P_XPLAINED_BC
#define MEGA1284P_XPLAINED_BC 23
ATmega1284P-Xplained board controller board.
Definition at line 81 of file board.h.
MEGA_1284P_XPLAINED
#define MEGA_1284P_XPLAINED 40
ATmega1284P Xplained board.
Definition at line 98 of file board.h.
RCB256RFR2_XPRO
#define RCB256RFR2_XPRO 65
RFR2 RCB Xplained Pro board.
Definition at line 123 of file board.h.
RZ600
#define RZ600 31
AT32UC3A RZ600 MCU board.
Definition at line 89 of file board.h.
RZ600_AT86RF212
#define RZ600_AT86RF212 10
AT86RF212 RF board in RZ600.
Definition at line 176 of file board.h.
RZ600_AT86RF230B
#define RZ600_AT86RF230B 9
AT86RF230B RF board in RZ600.
Definition at line 175 of file board.h.
RZ600_AT86RF231
#define RZ600_AT86RF231 8
AT86RF231 RF board in RZ600.
Definition at line 174 of file board.h.
SAM3N_EK
#define SAM3N_EK 35
SAM3N-EK board.
Definition at line 93 of file board.h.
SAM3S_EK
#define SAM3S_EK 32
SAM3S-EK board.
Definition at line 90 of file board.h.
SAM3S_EK2
#define SAM3S_EK2 36
SAM3S-EK2 board.
Definition at line 94 of file board.h.
SAM3U_EK
#define SAM3U_EK 33
SAM3U-EK board.
Definition at line 91 of file board.h.
SAM3X_EK
#define SAM3X_EK 34
SAM3X-EK board.
Definition at line 92 of file board.h.
SAM4C_EK
#define SAM4C_EK 64
SAM4C-EK board.
Definition at line 122 of file board.h.
SAM4CMP_DB
#define SAM4CMP_DB 71
SAM4CMP demo board.
Definition at line 129 of file board.h.
SAM4CMS_DB
#define SAM4CMS_DB 72
SAM4CMS demo board.
Definition at line 130 of file board.h.
SAM4CP16BMB
#define SAM4CP16BMB 67
SAM4CP16BMB board.
Definition at line 125 of file board.h.
SAM4E_EK
#define SAM4E_EK 51
SAM4E-EK board.
Definition at line 109 of file board.h.
SAM4E_XPLAINED_PRO
#define SAM4E_XPLAINED_PRO 68
SAM4E Xplained Pro board.
Definition at line 126 of file board.h.
SAM4L8_XPLAINED_PRO
#define SAM4L8_XPLAINED_PRO 60
SAM4L8 Xplained Pro board.
Definition at line 118 of file board.h.
SAM4L_EK
#define SAM4L_EK 45
SAM4L-EK board.
Definition at line 103 of file board.h.
SAM4L_XPLAINED_PRO
#define SAM4L_XPLAINED_PRO 54
SAM4L Xplained Pro board.
Definition at line 112 of file board.h.
SAM4N_XPLAINED_PRO
#define SAM4N_XPLAINED_PRO 61
SAM4N Xplained Pro board.
Definition at line 119 of file board.h.
SAM4S_EK
#define SAM4S_EK 37
SAM4S-EK board.
Definition at line 95 of file board.h.
SAM4S_EK2
#define SAM4S_EK2 49
SAM4S-EK2 board.
Definition at line 107 of file board.h.
SAM4S_WPIR_RD
#define SAM4S_WPIR_RD 58
SAM4S-WPIR-RD board.
Definition at line 116 of file board.h.
SAM4S_XPLAINED
#define SAM4S_XPLAINED 41
SAM4S Xplained board.
Definition at line 99 of file board.h.
SAM4S_XPLAINED_PRO
#define SAM4S_XPLAINED_PRO 53
SAM4S Xplained Pro board.
Definition at line 111 of file board.h.
SAMB11_XPLAINED_PRO
#define SAMB11_XPLAINED_PRO 84
SAM B11 Xplained Pro board.
Definition at line 142 of file board.h.
SAMB11ZR_SENSOR_TAG
#define SAMB11ZR_SENSOR_TAG 101
SAMB11ZR sensor tag board.
Definition at line 157 of file board.h.
SAMB11ZR_XPLAINED_PRO
#define SAMB11ZR_XPLAINED_PRO 92
SAM B11 ZR Xplained Pro board.
Definition at line 149 of file board.h.
SAMC21_XPLAINED_PRO
#define SAMC21_XPLAINED_PRO 80
SAM C21 Xplained Pro board.
Definition at line 138 of file board.h.
SAMD10_XPLAINED_MINI
#define SAMD10_XPLAINED_MINI 77
SAM D10 Xplained Mini board.
Definition at line 135 of file board.h.
SAMD11_XPLAINED_PRO
#define SAMD11_XPLAINED_PRO 74
SAM D11 Xplained Pro board.
Definition at line 132 of file board.h.
SAMD20_XPLAINED_PRO
#define SAMD20_XPLAINED_PRO 59
SAM D20 Xplained Pro board.
Definition at line 117 of file board.h.
SAMD21_XPLAINED_PRO
#define SAMD21_XPLAINED_PRO 69
SAM D21 Xplained Pro board.
Definition at line 127 of file board.h.
SAMDA1_XPLAINED_PRO
#define SAMDA1_XPLAINED_PRO 78
SAM DA1 Xplained Pro board.
Definition at line 136 of file board.h.
SAME70_XPLAINED
#define SAME70_XPLAINED 85
SAME70 Xplained board.
Definition at line 143 of file board.h.
SAMG53_XPLAINED_PRO
#define SAMG53_XPLAINED_PRO 66
SAMG53 Xplained Pro board.
Definition at line 124 of file board.h.
SAMG55_XPLAINED_PRO
#define SAMG55_XPLAINED_PRO 75
SAMG55 Xplained Pro board.
Definition at line 133 of file board.h.
SAMHA1G16A_XPLAINED_PRO
#define SAMHA1G16A_XPLAINED_PRO 94
SAM HA1G16A Xplained Pro board.
Definition at line 151 of file board.h.
SAML21_XPLAINED_PRO
#define SAML21_XPLAINED_PRO 76
SAM L21 Xplained Pro board.
Definition at line 134 of file board.h.
SAML22_XPLAINED_PRO
#define SAML22_XPLAINED_PRO 86
SAM L22 Xplained Pro board.
Definition at line 144 of file board.h.
SAML22_XPLAINED_PRO_B
#define SAML22_XPLAINED_PRO_B 87
SAM L22 Xplained Pro board.
Definition at line 145 of file board.h.
SAMR21_XPLAINED_PRO
#define SAMR21_XPLAINED_PRO 70
SAM R21 Xplained Pro board.
Definition at line 128 of file board.h.
SAMR21B18_MODULE
#define SAMR21B18_MODULE 104
SAMR21B18-MZ210PA Module.
Definition at line 160 of file board.h.
SAMR21G18_MODULE
#define SAMR21G18_MODULE 103
SAMR21G18-MR210UA Module.
Definition at line 159 of file board.h.
SAMR21ZLL_EK
#define SAMR21ZLL_EK 88
SAMR21ZLL-EK board.
Definition at line 146 of file board.h.
SAMR30_MODULE_XPLAINED_PRO
#define SAMR30_MODULE_XPLAINED_PRO 102
SAM R30 Module Xplained Pro board.
Definition at line 158 of file board.h.
SAMR30_XPLAINED_PRO
#define SAMR30_XPLAINED_PRO 93
SAM R30 Xplained Pro board.
Definition at line 150 of file board.h.
SAMR34_XPLAINED_PRO
#define SAMR34_XPLAINED_PRO 95
SAM R34 Xplained Pro board.
Definition at line 152 of file board.h.
SAMV71_XPLAINED_ULTRA
#define SAMV71_XPLAINED_ULTRA 81
SAMV71 Xplained Ultra board.
Definition at line 139 of file board.h.
SAMW25_XPLAINED_PRO
#define SAMW25_XPLAINED_PRO 79
SAMW25 Xplained Pro board.
Definition at line 137 of file board.h.
SECURITY_XPLAINED
#define SECURITY_XPLAINED 12
Xplained ATSHA204 board.
Definition at line 178 of file board.h.
SENSORS_XPLAINED_BREADBOARD
#define SENSORS_XPLAINED_BREADBOARD 11
Xplained sensor development breadboard.
Definition at line 177 of file board.h.
SENSORS_XPLAINED_INERTIAL_1
#define SENSORS_XPLAINED_INERTIAL_1 3
Xplained inertial sensor board 1.
Definition at line 169 of file board.h.
SENSORS_XPLAINED_INERTIAL_2
#define SENSORS_XPLAINED_INERTIAL_2 4
Xplained inertial sensor board 2.
Definition at line 170 of file board.h.
SENSORS_XPLAINED_INERTIAL_A1
#define SENSORS_XPLAINED_INERTIAL_A1 7
Xplained inertial sensor board "A".
Definition at line 173 of file board.h.
SENSORS_XPLAINED_LIGHTPROX_1
#define SENSORS_XPLAINED_LIGHTPROX_1 6
Xplained light & proximity sensor board.
Definition at line 172 of file board.h.
SENSORS_XPLAINED_PRESSURE_1
#define SENSORS_XPLAINED_PRESSURE_1 5
Xplained pressure sensor board.
Definition at line 171 of file board.h.
SIMULATOR_XMEGA_A1
#define SIMULATOR_XMEGA_A1 97
Simulator for XMEGA A1 devices.
Definition at line 153 of file board.h.
STK600_MEGA
#define STK600_MEGA 39
STK600 MEGA board.
Definition at line 97 of file board.h.
STK600_MEGA_RF
#define STK600_MEGA_RF 46
STK600 MEGA RF EVK board.
Definition at line 104 of file board.h.
STK600_RC032X
#define STK600_RC032X 48
STK600 with RC032X routing card board.
Definition at line 106 of file board.h.
STK600_RC044X
#define STK600_RC044X 24
STK600 with RC044X routing card board.
Definition at line 82 of file board.h.
STK600_RC064X
#define STK600_RC064X 10
ATxmega256A3 STK600 board.
Definition at line 70 of file board.h.
STK600_RC064X_LCDX
#define STK600_RC064X_LCDX 28
XMEGAB3 STK600 RC064X LCDX board.
Definition at line 86 of file board.h.
STK600_RC100X
#define STK600_RC100X 11
ATxmega128A1 STK600 board.
Definition at line 71 of file board.h.
STK600_RC100X_LCDX
#define STK600_RC100X_LCDX 29
XMEGAB1 STK600 RC100X LCDX board.
Definition at line 87 of file board.h.
STK600_RCUC3A0
#define STK600_RCUC3A0 38
STK600 RCUC3A0 board.
Definition at line 96 of file board.h.
STK600_RCUC3B0
#define STK600_RCUC3B0 25
STK600 RCUC3B0 board.
Definition at line 83 of file board.h.
STK600_RCUC3C0
#define STK600_RCUC3C0 17
STK600 RCUC3C board.
Definition at line 75 of file board.h.
STK600_RCUC3D
#define STK600_RCUC3D 16
STK600 RCUC3D board.
Definition at line 74 of file board.h.
STK600_RCUC3L0
#define STK600_RCUC3L0 6
STK600 RCUC3L0 board.
Definition at line 67 of file board.h.
STK600_RCUC3L3
#define STK600_RCUC3L3 44
ATUCL3 STK600 board.
Definition at line 102 of file board.h.
STK600_RCUC3L4
#define STK600_RCUC3L4 21
ATUCL4 STK600 board.
Definition at line 79 of file board.h.
UC3_A3_XPLAINED
#define UC3_A3_XPLAINED 13
ATUC3A3 UC3-A3 Xplained board.
Definition at line 72 of file board.h.
UC3_L0_QT600
#define UC3_L0_QT600 26
QT600 UC3L0 MCU board.
Definition at line 84 of file board.h.
UC3_L0_XPLAINED
#define UC3_L0_XPLAINED 15
ATUC3L0 UC3-L0 Xplained board.
Definition at line 73 of file board.h.
UC3_L0_XPLAINED_BC
#define UC3_L0_XPLAINED_BC 22
ATUC3L0 UC3-L0 Xplained board controller board.
Definition at line 80 of file board.h.
UC3B_BOARD_CONTROLLER
#define UC3B_BOARD_CONTROLLER 30
AT32UC3B1 board controller for Atmel boards.
Definition at line 88 of file board.h.
UC3C_EK
#define UC3C_EK 3
AT32UC3C UC3C-EK board.
Definition at line 64 of file board.h.
UC3L_EK
#define UC3L_EK 7
AT32UC3L-EK board.
Definition at line 68 of file board.h.
USER_BOARD
#define USER_BOARD 99
User-reserved board (if any).
Definition at line 155 of file board.h.
USER_EXT_BOARD
#define USER_EXT_BOARD 99
User-reserved extension board (if any).
Definition at line 179 of file board.h.
WLR089_XPLAINED_PRO
#define WLR089_XPLAINED_PRO 105
WLR089_XPLAINED_PRO board.
Definition at line 161 of file board.h.
XMEGA_A1_XPLAINED
#define XMEGA_A1_XPLAINED 19
ATxmega128A1 Xplain-A1 board.
Definition at line 77 of file board.h.
XMEGA_A1U_XPLAINED_PRO
#define XMEGA_A1U_XPLAINED_PRO 20
ATxmega128A1U XMEGA-A1U Xplained Pro board.
Definition at line 78 of file board.h.
XMEGA_A3_REB_CBB
#define XMEGA_A3_REB_CBB 62
XMEGA REB Controller Base board.
Definition at line 120 of file board.h.
XMEGA_A3BU_XPLAINED
#define XMEGA_A3BU_XPLAINED 27
ATxmega256A3BU Xplained board.
Definition at line 85 of file board.h.
XMEGA_B1_XPLAINED
#define XMEGA_B1_XPLAINED 18
ATxmega128B1 Xplained board.
Definition at line 76 of file board.h.
XMEGA_C3_XPLAINED
#define XMEGA_C3_XPLAINED 47
ATxmega384C3 Xplained board.
Definition at line 105 of file board.h.
XMEGA_E5_XPLAINED
#define XMEGA_E5_XPLAINED 50
ATxmega32E5 Xplained board.
Definition at line 108 of file board.h.
XMEGA_RF212B_ZIGBIT
#define XMEGA_RF212B_ZIGBIT 57
ATxmega256A3U with AT86RF212B Zigbit.
Definition at line 115 of file board.h.
XMEGA_RF233_ZIGBIT
#define XMEGA_RF233_ZIGBIT 56
ATxmega256A3U with AT86RF233 Zigbit.
Definition at line 114 of file board.h.
XPLAIN
#define XPLAIN 8
ATxmega128A1 Xplain board.
Definition at line 69 of file board.h.
Function Documentation
board_init()
void board_init (void)
This function initializes the board target resources.
This function should be called to ensure proper initialization of the target board hardware connected to the part.
LCD pin configure on EBI
LCD pin configure on SPI
Definition at line 366 of file init.c.
{
#ifndef CONF_BOARD_KEEP_WATCHDOG_AT_INIT
    /* Disable the watchdog */
    WDT->WDT_MR = WDT_MR_WDDIS;
#endif
#ifdef CONF_BOARD_CONFIG_MPU_AT_INIT
    _setup_memory_region();
#endif
#ifdef CONF_BOARD_ENABLE_CACHE
    /* Enabling the Cache */
    SCB_EnableICache();
    SCB_EnableDCache();
#endif
#ifdef CONF_BOARD_ENABLE_TCM_AT_INIT
    /* TCM Configuration */
    EFC->EEFC_FCR = (EEFC_FCR_FKEY_PASSWD | EEFC_FCR_FCMD_CGPB
                    | EEFC_FCR_FARG(8));
    EFC->EEFC_FCR = (EEFC_FCR_FKEY_PASSWD | EEFC_FCR_FCMD_SGPB
                    | EEFC_FCR_FARG(7));
    tcm_enable();
#if defined(__GNUC__)
    volatile char *dst = &_sitcm;
    volatile char *src = &_itcm_lma;
    /* copy code_TCM from flash to ITCM */
    while(dst < &_eitcm){
        *dst++ = *src++;
    }
#endif
#else
    /* TCM Configuration */
    EFC->EEFC_FCR = (EEFC_FCR_FKEY_PASSWD | EEFC_FCR_FCMD_CGPB
                    | EEFC_FCR_FARG(8));
    EFC->EEFC_FCR = (EEFC_FCR_FKEY_PASSWD | EEFC_FCR_FCMD_CGPB
                    | EEFC_FCR_FARG(7));
    tcm_disable();
#endif
    /* Initialize IOPORTs */
    ioport_init();
    /* Configure the pins connected to LED as output and set their
     * default initial state to high (LED off).
     */
    ioport_set_pin_dir(LED0_GPIO, IOPORT_DIR_OUTPUT);
    ioport_set_pin_level(LED0_GPIO, LED0_INACTIVE_LEVEL);
    /* Configure Push Button pins */
    ioport_set_pin_input_mode(GPIO_PUSH_BUTTON_1, GPIO_PUSH_BUTTON_1_FLAGS,
            GPIO_PUSH_BUTTON_1_SENSE);
#ifdef CONF_BOARD_UART_CONSOLE
    /* Configure UART pins */
    ioport_set_pin_peripheral_mode(USART1_RXD_GPIO, USART1_RXD_FLAGS);
    MATRIX->CCFG_SYSIO |= CCFG_SYSIO_SYSIO4;
    ioport_set_pin_peripheral_mode(USART1_TXD_GPIO, USART1_TXD_FLAGS);
#endif
#ifdef CONF_BOARD_TWIHS0
    ioport_set_pin_peripheral_mode(TWIHS0_DATA_GPIO, TWIHS0_DATA_FLAGS);
    ioport_set_pin_peripheral_mode(TWIHS0_CLK_GPIO, TWIHS0_CLK_FLAGS);
#endif
#ifdef CONF_BOARD_CAN0
    /* Configure the CAN0 TX and RX pins. */
    ioport_set_pin_peripheral_mode(PIN_CAN0_RX_IDX, PIN_CAN0_RX_FLAGS);
    ioport_set_pin_peripheral_mode(PIN_CAN0_TX_IDX, PIN_CAN0_TX_FLAGS);
    /* Configure the transiver0 RS & EN pins. */
    ioport_set_pin_dir(PIN_CAN0_TR_RS_IDX, IOPORT_DIR_OUTPUT);
    ioport_set_pin_dir(PIN_CAN0_TR_EN_IDX, IOPORT_DIR_OUTPUT);
#endif
#ifdef CONF_BOARD_CAN1
    /* Configure the CAN1 TX and RX pin. */
    ioport_set_pin_peripheral_mode(PIN_CAN1_RX_IDX, PIN_CAN1_RX_FLAGS);
    ioport_set_pin_peripheral_mode(PIN_CAN1_TX_IDX, PIN_CAN1_TX_FLAGS);
#endif
#ifdef CONF_BOARD_SPI
    ioport_set_pin_peripheral_mode(SPI0_MISO_GPIO, SPI0_MISO_FLAGS);
    ioport_set_pin_peripheral_mode(SPI0_MOSI_GPIO, SPI0_MOSI_FLAGS);
    ioport_set_pin_peripheral_mode(SPI0_SPCK_GPIO, SPI0_SPCK_FLAGS);
#ifdef CONF_BOARD_SPI_NPCS0
    ioport_set_pin_peripheral_mode(SPI0_NPCS0_GPIO, SPI0_NPCS0_FLAGS);
#endif
#ifdef CONF_BOARD_SPI_NPCS1
    ioport_set_pin_peripheral_mode(SPI0_NPCS1_GPIO, SPI0_NPCS1_FLAGS);
#endif
#endif
#ifdef CONF_BOARD_QSPI
    ioport_set_pin_peripheral_mode(QSPI_QSCK_GPIO, QSPI_QSCK_FLAGS);
    ioport_set_pin_peripheral_mode(QSPI_QCS_GPIO, QSPI_QCS_FLAGS);
    ioport_set_pin_peripheral_mode(QSPI_QIO0_GPIO, QSPI_QIO0_FLAGS);
    ioport_set_pin_peripheral_mode(QSPI_QIO1_GPIO, QSPI_QIO1_FLAGS);
    ioport_set_pin_peripheral_mode(QSPI_QIO2_GPIO, QSPI_QIO2_FLAGS);
    ioport_set_pin_peripheral_mode(QSPI_QIO3_GPIO, QSPI_QIO3_FLAGS);
#endif
#ifdef CONF_BOARD_PWM_LED0
    /* Configure PWM LED0 pin */
    ioport_set_pin_peripheral_mode(PIN_PWM_LED0_GPIO, PIN_PWM_LED0_FLAGS);
#endif
#ifdef CONF_BOARD_PWM_LED1
    /* Configure PWM LED1 pin */
    ioport_set_pin_peripheral_mode(PIN_PWM_LED1_GPIO, PIN_PWM_LED1_FLAGS);
#endif
#ifdef CONF_BOARD_UART_RXD
    ioport_set_pin_peripheral_mode(UART3_RXD_GPIO, UART3_RXD_FLAGS);
    ioport_set_pin_peripheral_mode(UART4_RXD_GPIO, UART4_RXD_FLAGS);
#endif
#ifdef CONF_BOARD_UART_TXD
    ioport_set_pin_peripheral_mode(UART3_TXD_GPIO, UART3_TXD_FLAGS);
    ioport_set_pin_peripheral_mode(UART4_TXD_GPIO, UART4_TXD_FLAGS);
#endif
#ifdef CONF_BOARD_USART_RXD
    /* Configure USART RXD pin */
    ioport_set_pin_peripheral_mode(USART0_RXD_GPIO, USART0_RXD_FLAGS);
    ioport_set_pin_peripheral_mode(USART2_RXD_GPIO, USART2_RXD_FLAGS);
#endif
#ifdef CONF_BOARD_USART_TXD
    /* Configure USART TXD pin */
    ioport_set_pin_peripheral_mode(USART0_TXD_GPIO, USART0_TXD_FLAGS);
    ioport_set_pin_peripheral_mode(USART2_TXD_GPIO, USART2_TXD_FLAGS);
#endif
#ifdef CONF_BOARD_USART_SCK
    /* Configure USART synchronous communication SCK pin */
    ioport_set_pin_peripheral_mode(PIN_USART0_SCK_IDX,PIN_USART0_SCK_FLAGS);
#endif
#ifdef CONF_BOARD_USART_CTS
    /* Configure USART synchronous communication CTS pin */
    ioport_set_pin_peripheral_mode(PIN_USART0_CTS_IDX,PIN_USART0_CTS_FLAGS);
#endif
#ifdef CONF_BOARD_USART_RTS
    /* Configure USART RTS pin */
    ioport_set_pin_peripheral_mode(PIN_USART0_RTS_IDX, PIN_USART0_RTS_FLAGS);
#endif
#ifdef CONF_BOARD_SD_MMC_HSMCI
    /* Configure HSMCI pins */
    ioport_set_pin_peripheral_mode(PIN_HSMCI_MCCDA_GPIO, PIN_HSMCI_MCCDA_FLAGS);
    ioport_set_pin_peripheral_mode(PIN_HSMCI_MCCK_GPIO, PIN_HSMCI_MCCK_FLAGS);
    ioport_set_pin_peripheral_mode(PIN_HSMCI_MCDA0_GPIO, PIN_HSMCI_MCDA0_FLAGS);
    ioport_set_pin_peripheral_mode(PIN_HSMCI_MCDA1_GPIO, PIN_HSMCI_MCDA1_FLAGS);
    ioport_set_pin_peripheral_mode(PIN_HSMCI_MCDA2_GPIO, PIN_HSMCI_MCDA2_FLAGS);
    ioport_set_pin_peripheral_mode(PIN_HSMCI_MCDA3_GPIO, PIN_HSMCI_MCDA3_FLAGS);
    /* Configure SD/MMC card detect pin */
    ioport_set_pin_dir(SD_MMC_0_CD_GPIO, IOPORT_DIR_INPUT);
    ioport_set_pin_mode(SD_MMC_0_CD_GPIO, SD_MMC_0_CD_FLAGS);
#endif
#ifdef CONF_BOARD_ILI9488
    pio_configure(PIN_EBI_RESET_PIO, PIN_EBI_RESET_TYPE, PIN_EBI_RESET_MASK, PIN_EBI_RESET_ATTRI);
    pio_configure(PIN_EBI_CDS_PIO, PIN_EBI_CDS_TYPE, PIN_EBI_CDS_MASK, PIN_EBI_CDS_ATTRI);
    pio_configure(PIN_EBI_DATAL_PIO, PIN_EBI_DATAL_TYPE, PIN_EBI_DATAL_MASK, PIN_EBI_DATAL_ATTRI);
    pio_configure(PIN_EBI_DATAH_0_PIO, PIN_EBI_DATAH_0_TYPE, PIN_EBI_DATAH_0_MASK, PIN_EBI_DATAH_0_ATTRI);
    pio_configure(PIN_EBI_DATAH_1_PIO, PIN_EBI_DATAH_1_TYPE, PIN_EBI_DATAH_1_MASK, PIN_EBI_DATAH_1_ATTRI);
    pio_configure(PIN_EBI_NWE_PIO, PIN_EBI_NWE_TYPE, PIN_EBI_NWE_MASK, PIN_EBI_NWE_ATTRI);
    pio_configure(PIN_EBI_NRD_PIO, PIN_EBI_NRD_TYPE, PIN_EBI_NRD_MASK, PIN_EBI_NRD_ATTRI);
    pio_configure(PIN_EBI_CS_PIO, PIN_EBI_CS_TYPE, PIN_EBI_CS_MASK, PIN_EBI_CS_ATTRI);
    pio_configure(PIN_EBI_BACKLIGHT_PIO, PIN_EBI_BACKLIGHT_TYPE, PIN_EBI_BACKLIGHT_MASK, PIN_EBI_BACKLIGHT_ATTRI);
    pio_set(PIN_EBI_BACKLIGHT_PIO, PIN_EBI_BACKLIGHT_MASK);
#endif
#if (defined CONF_BOARD_USB_PORT)
# if defined(CONF_BOARD_USB_VBUS_DETECT)
    ioport_set_pin_dir(USB_VBUS_PIN, IOPORT_DIR_INPUT);
# endif
# if defined(CONF_BOARD_USB_ID_DETECT)
    ioport_set_pin_dir(USB_ID_PIN, IOPORT_DIR_INPUT);
# endif
#endif
#ifdef CONF_BOARD_SDRAMC
    pio_configure_pin(SDRAM_BA0_PIO, SDRAM_BA0_FLAGS);
    pio_configure_pin(SDRAM_SDCK_PIO, SDRAM_SDCK_FLAGS);
    pio_configure_pin(SDRAM_SDCKE_PIO, SDRAM_SDCKE_FLAGS);
    pio_configure_pin(SDRAM_SDCS_PIO, SDRAM_SDCS_FLAGS);
    pio_configure_pin(SDRAM_RAS_PIO, SDRAM_RAS_FLAGS);
    pio_configure_pin(SDRAM_CAS_PIO, SDRAM_CAS_FLAGS);
    pio_configure_pin(SDRAM_SDWE_PIO, SDRAM_SDWE_FLAGS);
    pio_configure_pin(SDRAM_NBS0_PIO, SDRAM_NBS0_FLAGS);
    pio_configure_pin(SDRAM_NBS1_PIO, SDRAM_NBS1_FLAGS);
    pio_configure_pin(SDRAM_A2_PIO, SDRAM_A_FLAGS);
    pio_configure_pin(SDRAM_A3_PIO, SDRAM_A_FLAGS);
    pio_configure_pin(SDRAM_A4_PIO, SDRAM_A_FLAGS);
    pio_configure_pin(SDRAM_A5_PIO, SDRAM_A_FLAGS);
    pio_configure_pin(SDRAM_A6_PIO, SDRAM_A_FLAGS);
    pio_configure_pin(SDRAM_A7_PIO, SDRAM_A_FLAGS);
    pio_configure_pin(SDRAM_A8_PIO, SDRAM_A_FLAGS);
    pio_configure_pin(SDRAM_A9_PIO, SDRAM_A_FLAGS);
    pio_configure_pin(SDRAM_A10_PIO, SDRAM_A_FLAGS);
    pio_configure_pin(SDRAM_A11_PIO, SDRAM_A_FLAGS);
    pio_configure_pin(SDRAM_SDA10_PIO, SDRAM_SDA10_FLAGS);
    pio_configure_pin(SDRAM_D0_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D1_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D2_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D3_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D4_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D5_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D6_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D7_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D8_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D9_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D10_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D11_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D12_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D13_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D14_PIO, SDRAM_D_FLAGS);
    pio_configure_pin(SDRAM_D15_PIO, SDRAM_D_FLAGS);
    MATRIX->CCFG_SMCNFCS = CCFG_SMCNFCS_SDRAMEN;
#endif
#ifdef CONF_BOARD_ILI9488
    pio_configure_pin(LCD_SPI_MISO_PIO, LCD_SPI_MISO_FLAGS);
    pio_configure_pin(LCD_SPI_MOSI_PIO, LCD_SPI_MOSI_FLAGS);
    pio_configure_pin(LCD_SPI_SPCK_PIO, LCD_SPI_SPCK_FLAGS);
    pio_configure_pin(LCD_SPI_NPCS_PIO, LCD_SPI_NPCS_FLAGS);
    pio_configure_pin(LCD_SPI_RESET_PIO, LCD_SPI_RESET_FLAGS);
    pio_configure_pin(LCD_SPI_CDS_PIO, LCD_SPI_CDS_FLAGS);
    pio_configure_pin(LCD_SPI_BACKLIGHT_PIO, LCD_SPI_BACKLIGHT_FLAGS);
    pio_set_pin_high(LCD_SPI_BACKLIGHT_PIO);
#endif
}
References CCFG_SMCNFCS_SDRAMEN, CCFG_SYSIO_SYSIO4, EEFC_FCR_FARG, EEFC_FCR_FCMD_CGPB, EEFC_FCR_FCMD_SGPB, EEFC_FCR_FKEY_PASSWD, EFC, GPIO_PUSH_BUTTON_1, GPIO_PUSH_BUTTON_1_FLAGS, GPIO_PUSH_BUTTON_1_SENSE, IOPORT_DIR_INPUT, IOPORT_DIR_OUTPUT, ioport_init(), ioport_set_pin_dir(), ioport_set_pin_input_mode, ioport_set_pin_level(), ioport_set_pin_mode(), ioport_set_pin_peripheral_mode, LCD_SPI_BACKLIGHT_FLAGS, LCD_SPI_BACKLIGHT_PIO, LCD_SPI_CDS_FLAGS, LCD_SPI_CDS_PIO, LCD_SPI_MISO_FLAGS, LCD_SPI_MISO_PIO, LCD_SPI_MOSI_FLAGS, LCD_SPI_MOSI_PIO, LCD_SPI_NPCS_FLAGS, LCD_SPI_NPCS_PIO, LCD_SPI_RESET_FLAGS, LCD_SPI_RESET_PIO, LCD_SPI_SPCK_FLAGS, LCD_SPI_SPCK_PIO, LED0_GPIO, LED0_INACTIVE_LEVEL, MATRIX, PIN_CAN0_RX_FLAGS, PIN_CAN0_RX_IDX, PIN_CAN0_TR_EN_IDX, PIN_CAN0_TR_RS_IDX, PIN_CAN0_TX_FLAGS, PIN_CAN0_TX_IDX, PIN_CAN1_RX_FLAGS, PIN_CAN1_RX_IDX, PIN_CAN1_TX_FLAGS, PIN_CAN1_TX_IDX, PIN_EBI_BACKLIGHT_ATTRI, PIN_EBI_BACKLIGHT_MASK, PIN_EBI_BACKLIGHT_PIO, PIN_EBI_BACKLIGHT_TYPE, PIN_EBI_CDS_ATTRI, PIN_EBI_CDS_MASK, PIN_EBI_CDS_PIO, PIN_EBI_CDS_TYPE, PIN_EBI_CS_ATTRI, PIN_EBI_CS_MASK, PIN_EBI_CS_PIO, PIN_EBI_CS_TYPE, PIN_EBI_DATAH_0_ATTRI, PIN_EBI_DATAH_0_MASK, PIN_EBI_DATAH_0_PIO, PIN_EBI_DATAH_0_TYPE, PIN_EBI_DATAH_1_ATTRI, PIN_EBI_DATAH_1_MASK, PIN_EBI_DATAH_1_PIO, PIN_EBI_DATAH_1_TYPE, PIN_EBI_DATAL_ATTRI, PIN_EBI_DATAL_MASK, PIN_EBI_DATAL_PIO, PIN_EBI_DATAL_TYPE, PIN_EBI_NRD_ATTRI, PIN_EBI_NRD_MASK, PIN_EBI_NRD_PIO, PIN_EBI_NRD_TYPE, PIN_EBI_NWE_ATTRI, PIN_EBI_NWE_MASK, PIN_EBI_NWE_PIO, PIN_EBI_NWE_TYPE, PIN_EBI_RESET_ATTRI, PIN_EBI_RESET_MASK, PIN_EBI_RESET_PIO, PIN_EBI_RESET_TYPE, PIN_HSMCI_MCCDA_FLAGS, PIN_HSMCI_MCCDA_GPIO, PIN_HSMCI_MCCK_FLAGS, PIN_HSMCI_MCCK_GPIO, PIN_HSMCI_MCDA0_FLAGS, PIN_HSMCI_MCDA0_GPIO, PIN_HSMCI_MCDA1_FLAGS, PIN_HSMCI_MCDA1_GPIO, PIN_HSMCI_MCDA2_FLAGS, PIN_HSMCI_MCDA2_GPIO, PIN_HSMCI_MCDA3_FLAGS, PIN_HSMCI_MCDA3_GPIO, PIN_PWM_LED0_FLAGS, PIN_PWM_LED0_GPIO, PIN_PWM_LED1_FLAGS, PIN_PWM_LED1_GPIO, PIN_USART0_CTS_FLAGS, PIN_USART0_CTS_IDX, PIN_USART0_RTS_FLAGS, PIN_USART0_RTS_IDX, PIN_USART0_SCK_FLAGS, PIN_USART0_SCK_IDX, pio_configure(), pio_configure_pin(), pio_set(), pio_set_pin_high(), QSPI_QCS_FLAGS, QSPI_QCS_GPIO, QSPI_QIO0_FLAGS, QSPI_QIO0_GPIO, QSPI_QIO1_FLAGS, QSPI_QIO1_GPIO, QSPI_QIO2_FLAGS, QSPI_QIO2_GPIO, QSPI_QIO3_FLAGS, QSPI_QIO3_GPIO, QSPI_QSCK_FLAGS, QSPI_QSCK_GPIO, SD_MMC_0_CD_FLAGS, SD_MMC_0_CD_GPIO, SDRAM_A10_PIO, SDRAM_A11_PIO, SDRAM_A2_PIO, SDRAM_A3_PIO, SDRAM_A4_PIO, SDRAM_A5_PIO, SDRAM_A6_PIO, SDRAM_A7_PIO, SDRAM_A8_PIO, SDRAM_A9_PIO, SDRAM_A_FLAGS, SDRAM_BA0_FLAGS, SDRAM_BA0_PIO, SDRAM_CAS_FLAGS, SDRAM_CAS_PIO, SDRAM_D0_PIO, SDRAM_D10_PIO, SDRAM_D11_PIO, SDRAM_D12_PIO, SDRAM_D13_PIO, SDRAM_D14_PIO, SDRAM_D15_PIO, SDRAM_D1_PIO, SDRAM_D2_PIO, SDRAM_D3_PIO, SDRAM_D4_PIO, SDRAM_D5_PIO, SDRAM_D6_PIO, SDRAM_D7_PIO, SDRAM_D8_PIO, SDRAM_D9_PIO, SDRAM_D_FLAGS, SDRAM_NBS0_FLAGS, SDRAM_NBS0_PIO, SDRAM_NBS1_FLAGS, SDRAM_NBS1_PIO, SDRAM_RAS_FLAGS, SDRAM_RAS_PIO, SDRAM_SDA10_FLAGS, SDRAM_SDA10_PIO, SDRAM_SDCK_FLAGS, SDRAM_SDCK_PIO, SDRAM_SDCKE_FLAGS, SDRAM_SDCKE_PIO, SDRAM_SDCS_FLAGS, SDRAM_SDCS_PIO, SDRAM_SDWE_FLAGS, SDRAM_SDWE_PIO, SPI0_MISO_FLAGS, SPI0_MISO_GPIO, SPI0_MOSI_FLAGS, SPI0_MOSI_GPIO, SPI0_NPCS0_FLAGS, SPI0_NPCS0_GPIO, SPI0_NPCS1_FLAGS, SPI0_NPCS1_GPIO, SPI0_SPCK_FLAGS, SPI0_SPCK_GPIO, tcm_disable(), TWIHS0_CLK_FLAGS, TWIHS0_CLK_GPIO, TWIHS0_DATA_FLAGS, TWIHS0_DATA_GPIO, UART3_RXD_FLAGS, UART3_RXD_GPIO, UART3_TXD_FLAGS, UART3_TXD_GPIO, UART4_RXD_FLAGS, UART4_RXD_GPIO, UART4_TXD_FLAGS, UART4_TXD_GPIO, USART0_RXD_FLAGS, USART0_RXD_GPIO, USART0_TXD_FLAGS, USART0_TXD_GPIO, USART1_RXD_FLAGS, USART1_RXD_GPIO, USART1_TXD_FLAGS, USART1_TXD_GPIO, USART2_RXD_FLAGS, USART2_RXD_GPIO, USART2_TXD_FLAGS, USART2_TXD_GPIO, USB_ID_PIN, USB_VBUS_PIN, WDT, and WDT_MR_WDDIS.
Referenced by main().