WINC1500 Weather Client Demo for SAME70 Xplained: Peripheral Parallel Input/Output (PIO) Controller
Peripheral Parallel Input/Output (PIO) Controller
Macros
#define FREQ_SLOW_CLOCK_EXT 32768
Functions
void pio_clear (Pio *p_pio, const uint32_t ul_mask)
Set a low output level on all the PIOs defined in ul_mask.
uint32_t pio_configure (Pio *p_pio, const pio_type_t ul_type, const uint32_t ul_mask, const uint32_t ul_attribute)
Perform complete pin(s) configuration; general attributes and PIO init if necessary.
void pio_configure_interrupt (Pio *p_pio, const uint32_t ul_mask, const uint32_t ul_attr)
Configure the given interrupt source.
uint32_t pio_configure_pin (uint32_t ul_pin, const uint32_t ul_flags)
Perform complete pin(s) configuration; general attributes and PIO init if necessary.
uint32_t pio_configure_pin_group (Pio *p_pio, uint32_t ul_mask, const uint32_t ul_flags)
Perform complete pin(s) configuration; general attributes and PIO init if necessary.
void pio_disable_interrupt (Pio *p_pio, const uint32_t ul_mask)
Disable a given interrupt source, with no added side effects.
void pio_disable_output_write (Pio *p_pio, const uint32_t ul_mask)
Disable PIO output write.
void pio_disable_pin_interrupt (uint32_t ul_pin)
Disable interrupt for a GPIO pin.
void pio_enable_interrupt (Pio *p_pio, const uint32_t ul_mask)
Enable the given interrupt source.
void pio_enable_output_write (Pio *p_pio, const uint32_t ul_mask)
Enable PIO output write for synchronous data output.
void pio_enable_pin_interrupt (uint32_t ul_pin)
Enable interrupt for a GPIO pin.
uint32_t pio_get (Pio *p_pio, const pio_type_t ul_type, const uint32_t ul_mask)
Return 1 if one or more PIOs of the given Pin instance currently have a high level; otherwise returns 0.
uint32_t pio_get_interrupt_mask (const Pio *p_pio)
Read PIO interrupt mask.
uint32_t pio_get_interrupt_status (const Pio *p_pio)
Read and clear PIO interrupt status.
uint32_t pio_get_multi_driver_status (const Pio *p_pio)
Get multi-driver status.
uint32_t pio_get_output_data_status (const Pio *p_pio, const uint32_t ul_mask)
Return 1 if one or more PIOs of the given Pin are configured to output a high level (even if they are not output).
uint32_t pio_get_output_write_status (const Pio *p_pio)
Read PIO output write status.
Pio * pio_get_pin_group (uint32_t ul_pin)
Return GPIO port for a GPIO pin.
uint32_t pio_get_pin_group_id (uint32_t ul_pin)
Return GPIO port peripheral ID for a GPIO pin.
uint32_t pio_get_pin_group_mask (uint32_t ul_pin)
Return GPIO port pin mask for a GPIO pin.
uint32_t pio_get_pin_value (uint32_t ul_pin)
Return the value of a pin.
uint32_t pio_get_writeprotect_status (const Pio *p_pio)
Read write protect status.
void pio_pull_up (Pio *p_pio, const uint32_t ul_mask, const uint32_t ul_pull_up_enable)
Configure PIO internal pull-up.
void pio_set (Pio *p_pio, const uint32_t ul_mask)
Set a high output level on all the PIOs defined in ul_mask.
void pio_set_additional_interrupt_mode (Pio *p_pio, const uint32_t ul_mask, const uint32_t ul_attribute)
Set additional interrupt mode.
void pio_set_debounce_filter (Pio *p_pio, const uint32_t ul_mask, const uint32_t ul_cut_off)
Configure Glitch or Debouncing filter for the specified input(s).
void pio_set_input (Pio *p_pio, const uint32_t ul_mask, const uint32_t ul_attribute)
Configure one or more pin(s) or a PIO controller as inputs.
void pio_set_multi_driver (Pio *p_pio, const uint32_t ul_mask, const uint32_t ul_multi_driver_enable)
Configure PIO pin multi-driver.
void pio_set_output (Pio *p_pio, const uint32_t ul_mask, const uint32_t ul_default_level, const uint32_t ul_multidrive_enable, const uint32_t ul_pull_up_enable)
Configure one or more pin(s) of a PIO controller as outputs, with the given default value.
void pio_set_peripheral (Pio *p_pio, const pio_type_t ul_type, const uint32_t ul_mask)
Configure IO of a PIO controller as being controlled by a specific peripheral.
void pio_set_pin_group_high (Pio *p_pio, uint32_t ul_mask)
Drive a GPIO port to 1.
void pio_set_pin_group_low (Pio *p_pio, uint32_t ul_mask)
Drive a GPIO port to 0.
void pio_set_pin_high (uint32_t ul_pin)
Drive a GPIO pin to 1.
void pio_set_pin_low (uint32_t ul_pin)
Drive a GPIO pin to 0.
void pio_set_writeprotect (Pio *p_pio, const uint32_t ul_enable)
Enable or disable write protect of PIO registers.
void pio_sync_output_write (Pio *p_pio, const uint32_t ul_mask)
Synchronously write on output pins.
void pio_toggle_pin (uint32_t ul_pin)
Toggle a GPIO pin.
void pio_toggle_pin_group (Pio *p_pio, uint32_t ul_mask)
Toggle a GPIO group.
Detailed Description
Purpose
The Parallel Input/Output Controller (PIO) manages up to 32 fully programmable input/output lines. Each I/O line may be dedicated as a general-purpose I/O or be assigned to a function of an embedded peripheral. This assures effective optimization of the pins of a product.
Macro Definition Documentation
FREQ_SLOW_CLOCK_EXT
#define FREQ_SLOW_CLOCK_EXT 32768
Definition at line 58 of file pio.c.
Function Documentation
pio_clear()
void pio_clear (Pio * p_pio, const uint32_t ul_mask)
Set a low output level on all the PIOs defined in ul_mask.
This has no immediate effects on PIOs that are not output, but the PIO controller will save the value if they are changed to outputs.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Bitmask of one or more pin(s) to configure.
Definition at line 130 of file pio.c.
{
    p_pio->PIO_CODR = ul_mask;
}
References Pio::PIO_CODR.
pio_configure()
uint32_t pio_configure (Pio * p_pio, const pio_type_t ul_type, const uint32_t ul_mask, const uint32_t ul_attribute)
Perform complete pin(s) configuration; general attributes and PIO init if necessary.
Parameters
p_pio Pointer to a PIO instance.
ul_type PIO type.
ul_mask Bitmask of one or more pin(s) to configure.
ul_attribute Pins attributes.
Returns
Whether the pin(s) have been configured properly.
Definition at line 348 of file pio.c.
{
    /* Configure pins */
    switch (ul_type) {
    case PIO_PERIPH_A:
    case PIO_PERIPH_B:
#if (SAM3S || SAM3N || SAM4S || SAM4E || SAM4N || SAM4C || SAM4CP || SAM4CM || SAMV71 || SAMV70 || SAME70 || SAMS70)
    case PIO_PERIPH_C:
    case PIO_PERIPH_D:
#endif
        pio_set_peripheral(p_pio, ul_type, ul_mask);
        pio_pull_up(p_pio, ul_mask, (ul_attribute & PIO_PULLUP));
        break;
    case PIO_INPUT:
        pio_set_input(p_pio, ul_mask, ul_attribute);
        break;
    case PIO_OUTPUT_0:
    case PIO_OUTPUT_1:
        pio_set_output(p_pio, ul_mask, (ul_type == PIO_OUTPUT_1),
                (ul_attribute & PIO_OPENDRAIN) ? 1 : 0,
                (ul_attribute & PIO_PULLUP) ? 1 : 0);
        break;
    default:
        return 0;
    }
    return 1;
}
References PIO_INPUT, PIO_OPENDRAIN, PIO_OUTPUT_0, PIO_OUTPUT_1, PIO_PERIPH_A, PIO_PERIPH_B, pio_pull_up(), PIO_PULLUP, pio_set_input(), pio_set_output(), and pio_set_peripheral().
Referenced by board_init().
pio_configure_interrupt()
void pio_configure_interrupt (Pio * p_pio, const uint32_t ul_mask, const uint32_t ul_attr)
Configure the given interrupt source.
Interrupt can be configured to trigger on rising edge, falling edge, high level, low level or simply on level change.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Interrupt source bit map.
ul_attr Interrupt source attributes.
Definition at line 538 of file pio.c.
{
    /* Configure additional interrupt mode registers. */
    if (ul_attr & PIO_IT_AIME) {
        /* Enable additional interrupt mode. */
        p_pio->PIO_AIMER = ul_mask;
        /* If bit field of the selected pin is 1, set as
           Rising Edge/High level detection event. */
        if (ul_attr & PIO_IT_RE_OR_HL) {
            /* Rising Edge or High Level */
            p_pio->PIO_REHLSR = ul_mask;
        } else {
            /* Falling Edge or Low Level */
            p_pio->PIO_FELLSR = ul_mask;
        }
        /* If bit field of the selected pin is 1, set as
           edge detection source. */
        if (ul_attr & PIO_IT_EDGE) {
            /* Edge select */
            p_pio->PIO_ESR = ul_mask;
        } else {
            /* Level select */
            p_pio->PIO_LSR = ul_mask;
        }
    } else {
        /* Disable additional interrupt mode. */
        p_pio->PIO_AIMDR = ul_mask;
    }
}
References Pio::PIO_AIMDR, Pio::PIO_AIMER, Pio::PIO_ESR, Pio::PIO_FELLSR, PIO_IT_AIME, PIO_IT_EDGE, PIO_IT_RE_OR_HL, Pio::PIO_LSR, and Pio::PIO_REHLSR.
Referenced by pio_handler_set().
pio_configure_pin()
uint32_t pio_configure_pin (uint32_t ul_pin, const uint32_t ul_flags)
Perform complete pin(s) configuration; general attributes and PIO init if necessary.
Parameters
ul_pin The pin index.
ul_flags Pins attributes.
Returns
Whether the pin(s) have been configured properly.
Definition at line 763 of file pio.c.
{
    Pio *p_pio = pio_get_pin_group(ul_pin);
    /* Configure pins */
    switch (ul_flags & PIO_TYPE_Msk) {
    case PIO_TYPE_PIO_PERIPH_A:
        pio_set_peripheral(p_pio, PIO_PERIPH_A, (1 << (ul_pin & 0x1F)));
        pio_pull_up(p_pio, (1 << (ul_pin & 0x1F)),
                (ul_flags & PIO_PULLUP));
        break;
    case PIO_TYPE_PIO_PERIPH_B:
        pio_set_peripheral(p_pio, PIO_PERIPH_B, (1 << (ul_pin & 0x1F)));
        pio_pull_up(p_pio, (1 << (ul_pin & 0x1F)),
                (ul_flags & PIO_PULLUP));
        break;
#if (SAM3S || SAM3N || SAM4S || SAM4E || SAM4N || SAM4C || SAM4CP || SAM4CM || SAMV71 || SAMV70 || SAME70 || SAMS70)
    case PIO_TYPE_PIO_PERIPH_C:
        pio_set_peripheral(p_pio, PIO_PERIPH_C, (1 << (ul_pin & 0x1F)));
        pio_pull_up(p_pio, (1 << (ul_pin & 0x1F)),
                (ul_flags & PIO_PULLUP));
        break;
    case PIO_TYPE_PIO_PERIPH_D:
        pio_set_peripheral(p_pio, PIO_PERIPH_D, (1 << (ul_pin & 0x1F)));
        pio_pull_up(p_pio, (1 << (ul_pin & 0x1F)),
                (ul_flags & PIO_PULLUP));
        break;
#endif
    case PIO_TYPE_PIO_INPUT:
        pio_set_input(p_pio, (1 << (ul_pin & 0x1F)), ul_flags);
        break;
    case PIO_TYPE_PIO_OUTPUT_0:
    case PIO_TYPE_PIO_OUTPUT_1:
        pio_set_output(p_pio, (1 << (ul_pin & 0x1F)),
                ((ul_flags & PIO_TYPE_PIO_OUTPUT_1)
                == PIO_TYPE_PIO_OUTPUT_1) ? 1 : 0,
                (ul_flags & PIO_OPENDRAIN) ? 1 : 0,
                (ul_flags & PIO_PULLUP) ? 1 : 0);
        break;
    default:
        return 0;
    }
    return 1;
}
References pio_get_pin_group(), PIO_OPENDRAIN, PIO_PERIPH_A, PIO_PERIPH_B, pio_pull_up(), PIO_PULLUP, pio_set_input(), pio_set_output(), pio_set_peripheral(), PIO_TYPE_Msk, PIO_TYPE_PIO_INPUT, PIO_TYPE_PIO_OUTPUT_0, PIO_TYPE_PIO_OUTPUT_1, PIO_TYPE_PIO_PERIPH_A, PIO_TYPE_PIO_PERIPH_B, PIO_TYPE_PIO_PERIPH_C, and PIO_TYPE_PIO_PERIPH_D.
Referenced by board_init(), and nm_bsp_register_isr().
pio_configure_pin_group()
uint32_t pio_configure_pin_group (Pio * p_pio, uint32_t ul_mask, const uint32_t ul_flags)
Perform complete pin(s) configuration; general attributes and PIO init if necessary.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Bitmask of one or more pin(s) to configure.
ul_flags Pin(s) attributes.
Returns
Whether the pin(s) have been configured properly.
Definition at line 863 of file pio.c.
{
    /* Configure pins */
    switch (ul_flags & PIO_TYPE_Msk) {
    case PIO_TYPE_PIO_PERIPH_A:
        pio_set_peripheral(p_pio, PIO_PERIPH_A, ul_mask);
        pio_pull_up(p_pio, ul_mask, (ul_flags & PIO_PULLUP));
        break;
    case PIO_TYPE_PIO_PERIPH_B:
        pio_set_peripheral(p_pio, PIO_PERIPH_B, ul_mask);
        pio_pull_up(p_pio, ul_mask, (ul_flags & PIO_PULLUP));
        break;
#if (SAM3S || SAM3N || SAM4S || SAM4E || SAM4N || SAM4C || SAM4CP || SAM4CM || SAMV71 || SAMV70 || SAME70 || SAMS70)
    case PIO_TYPE_PIO_PERIPH_C:
        pio_set_peripheral(p_pio, PIO_PERIPH_C, ul_mask);
        pio_pull_up(p_pio, ul_mask, (ul_flags & PIO_PULLUP));
        break;
    case PIO_TYPE_PIO_PERIPH_D:
        pio_set_peripheral(p_pio, PIO_PERIPH_D, ul_mask);
        pio_pull_up(p_pio, ul_mask, (ul_flags & PIO_PULLUP));
        break;
#endif
    case PIO_TYPE_PIO_INPUT:
        pio_set_input(p_pio, ul_mask, ul_flags);
        break;
    case PIO_TYPE_PIO_OUTPUT_0:
    case PIO_TYPE_PIO_OUTPUT_1:
        pio_set_output(p_pio, ul_mask,
                ((ul_flags & PIO_TYPE_PIO_OUTPUT_1)
                == PIO_TYPE_PIO_OUTPUT_1) ? 1 : 0,
                (ul_flags & PIO_OPENDRAIN) ? 1 : 0,
                (ul_flags & PIO_PULLUP) ? 1 : 0);
        break;
    default:
        return 0;
    }
    return 1;
}
References PIO_OPENDRAIN, PIO_PERIPH_A, PIO_PERIPH_B, pio_pull_up(), PIO_PULLUP, pio_set_input(), pio_set_output(), pio_set_peripheral(), PIO_TYPE_Msk, PIO_TYPE_PIO_INPUT, PIO_TYPE_PIO_OUTPUT_0, PIO_TYPE_PIO_OUTPUT_1, PIO_TYPE_PIO_PERIPH_A, PIO_TYPE_PIO_PERIPH_B, PIO_TYPE_PIO_PERIPH_C, and PIO_TYPE_PIO_PERIPH_D.
pio_disable_interrupt()
void pio_disable_interrupt (Pio * p_pio, const uint32_t ul_mask)
Disable a given interrupt source, with no added side effects.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Interrupt sources bit map.
Definition at line 589 of file pio.c.
{
    p_pio->PIO_IDR = ul_mask;
}
References Pio::PIO_IDR.
Referenced by nm_bsp_interrupt_ctrl(), pio_handler_set_priority(), pio_set_input(), and pio_set_output().
pio_disable_output_write()
void pio_disable_output_write (Pio * p_pio, const uint32_t ul_mask)
Disable PIO output write.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Bitmask of one or more pin(s) to configure.
Definition at line 472 of file pio.c.
{
    p_pio->PIO_OWDR = ul_mask;
}
References Pio::PIO_OWDR.
pio_disable_pin_interrupt()
void pio_disable_pin_interrupt (uint32_t ul_pin)
Disable interrupt for a GPIO pin.
Parameters
ul_pin The pin index.
Note
The function gpio_configure_pin must be called before.
Definition at line 929 of file pio.c.
{
    Pio *p_pio = pio_get_pin_group(ul_pin);
    p_pio->PIO_IDR = 1 << (ul_pin & 0x1F);
}
References pio_get_pin_group(), and Pio::PIO_IDR.
pio_enable_interrupt()
void pio_enable_interrupt (Pio * p_pio, const uint32_t ul_mask)
Enable the given interrupt source.
The PIO must be configured as an NVIC interrupt source as well.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Interrupt sources bit map.
Definition at line 578 of file pio.c.
{
    p_pio->PIO_IER = ul_mask;
}
References Pio::PIO_IER.
Referenced by nm_bsp_interrupt_ctrl(), nm_bsp_register_isr(), and pio_handler_set_priority().
pio_enable_output_write()
void pio_enable_output_write (Pio * p_pio, const uint32_t ul_mask)
Enable PIO output write for synchronous data output.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Bitmask of one or more pin(s) to configure.
Definition at line 461 of file pio.c.
{
    p_pio->PIO_OWER = ul_mask;
}
References Pio::PIO_OWER.
pio_enable_pin_interrupt()
void pio_enable_pin_interrupt (uint32_t ul_pin)
Enable interrupt for a GPIO pin.
Parameters
ul_pin The pin index.
Note
The function gpio_configure_pin must be called before.
Definition at line 914 of file pio.c.
{
    Pio *p_pio = pio_get_pin_group(ul_pin);
    p_pio->PIO_IER = 1 << (ul_pin & 0x1F);
}
References pio_get_pin_group(), and Pio::PIO_IER.
pio_get()
uint32_t pio_get (Pio * p_pio, const pio_type_t ul_type, const uint32_t ul_mask)
Return 1 if one or more PIOs of the given Pin instance currently have a high level; otherwise returns 0.
This method returns the actual value that is being read on the pin. To return the supposed output value of a pin, use pio_get_output_data_status() instead.
Parameters
p_pio Pointer to a PIO instance.
ul_type PIO type.
ul_mask Bitmask of one or more pin(s) to configure.
Return values
1 at least one PIO currently has a high level.
0 all PIOs have a low level.
Definition at line 148 of file pio.c.
{
    uint32_t ul_reg;
    if ((ul_type == PIO_OUTPUT_0) || (ul_type == PIO_OUTPUT_1)) {
        ul_reg = p_pio->PIO_ODSR;
    } else {
        ul_reg = p_pio->PIO_PDSR;
    }
    if ((ul_reg & ul_mask) == 0) {
        return 0;
    } else {
        return 1;
    }
}
References Pio::PIO_ODSR, PIO_OUTPUT_0, PIO_OUTPUT_1, and Pio::PIO_PDSR.
pio_get_interrupt_mask()
uint32_t pio_get_interrupt_mask (const Pio * p_pio)
Read PIO interrupt mask.
Parameters
p_pio Pointer to a PIO instance.
Returns
The interrupt mask value.
Definition at line 613 of file pio.c.
{
    return p_pio->PIO_IMR;
}
References Pio::PIO_IMR.
Referenced by pio_handler_process(), and pio_handler_set_priority().
pio_get_interrupt_status()
uint32_t pio_get_interrupt_status (const Pio * p_pio)
Read and clear PIO interrupt status.
Parameters
p_pio Pointer to a PIO instance.
Returns
The interrupt status value.
Definition at line 601 of file pio.c.
{
    return p_pio->PIO_ISR;
}
References Pio::PIO_ISR.
Referenced by nm_bsp_interrupt_ctrl(), nm_bsp_register_isr(), pio_handler_process(), and pio_handler_set_priority().
pio_get_multi_driver_status()
uint32_t pio_get_multi_driver_status (const Pio * p_pio)
Get multi-driver status.
Parameters
p_pio Pointer to a PIO instance.
Returns
The multi-driver mask value.
Definition at line 428 of file pio.c.
{
    return p_pio->PIO_MDSR;
}
References Pio::PIO_MDSR.
pio_get_output_data_status()
uint32_t pio_get_output_data_status (const Pio * p_pio, const uint32_t ul_mask)
Return 1 if one or more PIOs of the given Pin are configured to output a high level (even if they are not output).
To get the actual value of the pin, use PIO_Get() instead.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Bitmask of one or more pin(s).
Return values
1 At least one PIO is configured to output a high level.
0 All PIOs are configured to output a low level.
Definition at line 392 of file pio.c.
{
    if ((p_pio->PIO_ODSR & ul_mask) == 0) {
        return 0;
    } else {
        return 1;
    }
}
References Pio::PIO_ODSR.
pio_get_output_write_status()
uint32_t pio_get_output_write_status (const Pio * p_pio)
Read PIO output write status.
Parameters
p_pio Pointer to a PIO instance.
Returns
The output write mask value.
Definition at line 484 of file pio.c.
{
    return p_pio->PIO_OWSR;
}
References Pio::PIO_OWSR.
pio_get_pin_group()
Pio * pio_get_pin_group (uint32_t ul_pin)
Return GPIO port for a GPIO pin.
Parameters
ul_pin The pin index.
Returns
Pointer to Pio struct for GPIO port.
Definition at line 944 of file pio.c.
{
    Pio *p_pio;
#if (SAM4C || SAM4CP)
#  ifdef ID_PIOD
    if (ul_pin > PIO_PC9_IDX) {
        p_pio = PIOD;
    } else if (ul_pin > PIO_PB31_IDX) {
#  else
    if  (ul_pin > PIO_PB31_IDX) {
#  endif
        p_pio = PIOC;
    } else {
        p_pio = (Pio *)((uint32_t)PIOA + (PIO_DELTA * (ul_pin >> 5)));
    }
#elif (SAM4CM)
    if (ul_pin > PIO_PB21_IDX) {
        p_pio = PIOC;
    } else {
        p_pio = (Pio *)((uint32_t)PIOA + (PIO_DELTA * (ul_pin >> 5)));
    }
#else
    p_pio = (Pio *)((uint32_t)PIOA + (PIO_DELTA * (ul_pin >> 5)));
#endif
    return p_pio;
}
References PIO_DELTA, PIO_PC9_IDX, PIOA, PIOC, and PIOD.
Referenced by pio_configure_pin(), pio_disable_pin_interrupt(), pio_enable_pin_interrupt(), pio_get_pin_value(), pio_set_pin_high(), pio_set_pin_low(), and pio_toggle_pin().
pio_get_pin_group_id()
uint32_t pio_get_pin_group_id (uint32_t ul_pin)
Return GPIO port peripheral ID for a GPIO pin.
Parameters
ul_pin The pin index.
Returns
GPIO port peripheral ID.
Definition at line 979 of file pio.c.
{
    uint32_t ul_id;
#if (SAM4C || SAM4CP)
#  ifdef ID_PIOD
    if (ul_pin > PIO_PC9_IDX) {
        ul_id = ID_PIOD;
    } else if (ul_pin > PIO_PB31_IDX) {
#  else
    if (ul_pin > PIO_PB31_IDX) {
#  endif
        ul_id = ID_PIOC;
    } else {
        ul_id = ID_PIOA + (ul_pin >> 5);
    }
#elif (SAM4CM)
    if (ul_pin > PIO_PB21_IDX) {
        ul_id = ID_PIOC;
    } else {
        ul_id = ID_PIOA + (ul_pin >> 5);
    }
#elif (SAMV70 || SAMV71 || SAME70 || SAMS70)
    ul_id = ID_PIOA + (ul_pin >> 5);
    #ifdef ID_PIOD
    if (ul_pin >= PIO_PD0_IDX) ul_id = ID_PIOD;
    #endif
    #ifdef ID_PIOE
    if (ul_pin >= PIO_PE0_IDX) ul_id = ID_PIOE;
    #endif
#else
    ul_id = ID_PIOA + (ul_pin >> 5);
#endif
    return ul_id;
}
References ID_PIOA, ID_PIOC, ID_PIOD, ID_PIOE, PIO_PC9_IDX, PIO_PD0_IDX, and PIO_PE0_IDX.
pio_get_pin_group_mask()
uint32_t pio_get_pin_group_mask (uint32_t ul_pin)
Return GPIO port pin mask for a GPIO pin.
Parameters
ul_pin The pin index.
Returns
GPIO port pin mask.
Definition at line 1025 of file pio.c.
{
    uint32_t ul_mask = 1 << (ul_pin & 0x1F);
    return ul_mask;
}
pio_get_pin_value()
uint32_t pio_get_pin_value (uint32_t ul_pin)
Return the value of a pin.
Parameters
ul_pin The pin number.
Returns
The pin value.
Note
If pin is output: a pull-up or pull-down could hide the actual value. The function pio_get can be called to get the actual pin output level.
If pin is input: PIOx must be clocked to sample the signal. See PMC driver.
Definition at line 697 of file pio.c.
{
    Pio *p_pio = pio_get_pin_group(ul_pin);
    return (p_pio->PIO_PDSR >> (ul_pin & 0x1F)) & 1;
}
References pio_get_pin_group(), and Pio::PIO_PDSR.
pio_get_writeprotect_status()
uint32_t pio_get_writeprotect_status (const Pio * p_pio)
Read write protect status.
Parameters
p_pio Pointer to a PIO instance.
Returns
Return write protect status.
Definition at line 679 of file pio.c.
{
    return p_pio->PIO_WPSR;
}
References Pio::PIO_WPSR.
pio_pull_up()
void pio_pull_up (Pio * p_pio, const uint32_t ul_mask, const uint32_t ul_pull_up_enable)
Configure PIO internal pull-up.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Bitmask of one or more pin(s) to configure.
ul_pull_up_enable Indicates if the pin(s) internal pull-up shall be configured.
Definition at line 69 of file pio.c.
{
    /* Enable the pull-up(s) if necessary */
    if (ul_pull_up_enable) {
        p_pio->PIO_PUER = ul_mask;
    } else {
        p_pio->PIO_PUDR = ul_mask;
    }
}
References Pio::PIO_PUDR, and Pio::PIO_PUER.
Referenced by nm_bsp_register_isr(), pio_configure(), pio_configure_pin(), pio_configure_pin_group(), pio_set_input(), and pio_set_output().
pio_set()
void pio_set (Pio * p_pio, const uint32_t ul_mask)
Set a high output level on all the PIOs defined in ul_mask.
This has no immediate effects on PIOs that are not output, but the PIO controller will save the value if they are changed to outputs.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Bitmask of one or more pin(s) to configure.
Definition at line 117 of file pio.c.
{
    p_pio->PIO_SODR = ul_mask;
}
References Pio::PIO_SODR.
Referenced by board_init(), and ili9488_copy_pixels_from_screen().
pio_set_additional_interrupt_mode()
void pio_set_additional_interrupt_mode (Pio * p_pio, const uint32_t ul_mask, const uint32_t ul_attribute)
Set additional interrupt mode.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Interrupt sources bit map.
ul_attribute Pin(s) attributes.
Definition at line 625 of file pio.c.
{
    /* Enables additional interrupt mode if needed */
    if (ul_attribute & PIO_IT_AIME) {
        /* Enables additional interrupt mode */
        p_pio->PIO_AIMER = ul_mask;
        /* Configures the Polarity of the event detection */
        /* (Rising/Falling Edge or High/Low Level) */
        if (ul_attribute & PIO_IT_RE_OR_HL) {
            /* Rising Edge or High Level */
            p_pio->PIO_REHLSR = ul_mask;
        } else {
            /* Falling Edge or Low Level */
            p_pio->PIO_FELLSR = ul_mask;
        }
        /* Configures the type of event detection (Edge or Level) */
        if (ul_attribute & PIO_IT_EDGE) {
            /* Edge select */
            p_pio->PIO_ESR = ul_mask;
        } else {
            /* Level select */
            p_pio->PIO_LSR = ul_mask;
        }
    } else {
        /* Disable additional interrupt mode */
        p_pio->PIO_AIMDR = ul_mask;
    }
}
References Pio::PIO_AIMDR, Pio::PIO_AIMER, Pio::PIO_ESR, Pio::PIO_FELLSR, PIO_IT_AIME, PIO_IT_EDGE, PIO_IT_RE_OR_HL, Pio::PIO_LSR, and Pio::PIO_REHLSR.
pio_set_debounce_filter()
void pio_set_debounce_filter (Pio * p_pio, const uint32_t ul_mask, const uint32_t ul_cut_off)
Configure Glitch or Debouncing filter for the specified input(s).
Parameters
p_pio Pointer to a PIO instance.
ul_mask Bitmask of one or more pin(s) to configure.
ul_cut_off Cuts off frequency for debouncing filter.
Definition at line 87 of file pio.c.
{
#if (SAM3S || SAM3N || SAM4S || SAM4E || SAM4N || SAM4C || SAMG || SAM4CP || SAM4CM || SAMV71 || SAMV70 || SAME70 || SAMS70)
    /* Set Debouncing, 0 bit field no effect */
    p_pio->PIO_IFSCER = ul_mask;
#elif (SAM3XA || SAM3U)
    /* Set Debouncing, 0 bit field no effect */
    p_pio->PIO_DIFSR = ul_mask;
#else
#error "Unsupported device"
#endif
    /*
     * The debouncing filter can filter a pulse of less than 1/2 Period of a
     * programmable Divided Slow Clock:
     * Tdiv_slclk = ((DIV+1)*2).Tslow_clock
     */
    p_pio->PIO_SCDR = PIO_SCDR_DIV((FREQ_SLOW_CLOCK_EXT /
            (2 * (ul_cut_off))) - 1);
}
References FREQ_SLOW_CLOCK_EXT, Pio::PIO_IFSCER, Pio::PIO_SCDR, and PIO_SCDR_DIV.
pio_set_input()
void pio_set_input (Pio * p_pio, const uint32_t ul_mask, const uint32_t ul_attribute)
Configure one or more pin(s) or a PIO controller as inputs.
Optionally, the corresponding internal pull-up(s) and glitch filter(s) can be enabled.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Bitmask indicating which pin(s) to configure as input(s).
ul_attribute PIO attribute(s).
Definition at line 257 of file pio.c.
{
    pio_disable_interrupt(p_pio, ul_mask);
    pio_pull_up(p_pio, ul_mask, ul_attribute & PIO_PULLUP);
    /* Enable Input Filter if necessary */
    if (ul_attribute & (PIO_DEGLITCH | PIO_DEBOUNCE)) {
        p_pio->PIO_IFER = ul_mask;
    } else {
        p_pio->PIO_IFDR = ul_mask;
    }
#if (SAM3S || SAM3N || SAM4S || SAM4E || SAM4N || SAM4C || SAMG || SAM4CP || SAM4CM || SAMV71 || SAMV70 || SAME70 || SAMS70)
    /* Enable de-glitch or de-bounce if necessary */
    if (ul_attribute & PIO_DEGLITCH) {
        p_pio->PIO_IFSCDR = ul_mask;
    } else {
        if (ul_attribute & PIO_DEBOUNCE) {
            p_pio->PIO_IFSCER = ul_mask;
        }
    }
#elif (SAM3XA|| SAM3U)
    /* Enable de-glitch or de-bounce if necessary */
    if (ul_attribute & PIO_DEGLITCH) {
        p_pio->PIO_SCIFSR = ul_mask;
    } else {
        if (ul_attribute & PIO_DEBOUNCE) {
            p_pio->PIO_DIFSR = ul_mask;
        }
    }
#else
#error "Unsupported device"
#endif
    /* Configure pin as input */
    p_pio->PIO_ODR = ul_mask;
    p_pio->PIO_PER = ul_mask;
}
References PIO_DEBOUNCE, PIO_DEGLITCH, pio_disable_interrupt(), Pio::PIO_IFDR, Pio::PIO_IFER, Pio::PIO_IFSCDR, Pio::PIO_IFSCER, Pio::PIO_ODR, Pio::PIO_PER, pio_pull_up(), and PIO_PULLUP.
Referenced by pio_configure(), pio_configure_pin(), and pio_configure_pin_group().
pio_set_multi_driver()
void pio_set_multi_driver (Pio * p_pio, const uint32_t ul_mask, const uint32_t ul_multi_driver_enable)
Configure PIO pin multi-driver.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Bitmask of one or more pin(s) to configure.
ul_multi_driver_enable Indicates if the pin(s) multi-driver shall be configured.
Definition at line 410 of file pio.c.
{
    /* Enable the multi-driver if necessary */
    if (ul_multi_driver_enable) {
        p_pio->PIO_MDER = ul_mask;
    } else {
        p_pio->PIO_MDDR = ul_mask;
    }
}
References Pio::PIO_MDDR, and Pio::PIO_MDER.
pio_set_output()
void pio_set_output (Pio * p_pio, const uint32_t ul_mask, const uint32_t ul_default_level, const uint32_t ul_multidrive_enable, const uint32_t ul_pull_up_enable)
Configure one or more pin(s) of a PIO controller as outputs, with the given default value.
Optionally, the multi-drive feature can be enabled on the pin(s).
Parameters
p_pio Pointer to a PIO instance.
ul_mask Bitmask indicating which pin(s) to configure.
ul_default_level Default level on the pin(s).
ul_multidrive_enable Indicates if the pin(s) shall be configured as open-drain.
ul_pull_up_enable Indicates if the pin shall have its pull-up activated.
Definition at line 310 of file pio.c.
{
    pio_disable_interrupt(p_pio, ul_mask);
    pio_pull_up(p_pio, ul_mask, ul_pull_up_enable);
    /* Enable multi-drive if necessary */
    if (ul_multidrive_enable) {
        p_pio->PIO_MDER = ul_mask;
    } else {
        p_pio->PIO_MDDR = ul_mask;
    }
    /* Set default value */
    if (ul_default_level) {
        p_pio->PIO_SODR = ul_mask;
    } else {
        p_pio->PIO_CODR = ul_mask;
    }
    /* Configure pin(s) as output(s) */
    p_pio->PIO_OER = ul_mask;
    p_pio->PIO_PER = ul_mask;
}
References Pio::PIO_CODR, pio_disable_interrupt(), Pio::PIO_MDDR, Pio::PIO_MDER, Pio::PIO_OER, Pio::PIO_PER, pio_pull_up(), and Pio::PIO_SODR.
Referenced by pio_configure(), pio_configure_pin(), and pio_configure_pin_group().
pio_set_peripheral()
void pio_set_peripheral (Pio * p_pio, const pio_type_t ul_type, const uint32_t ul_mask)
Configure IO of a PIO controller as being controlled by a specific peripheral.
Parameters
p_pio Pointer to a PIO instance.
ul_type PIO type.
ul_mask Bitmask of one or more pin(s) to configure.
Definition at line 174 of file pio.c.
{
    uint32_t ul_sr;
    /* Disable interrupts on the pin(s) */
    p_pio->PIO_IDR = ul_mask;
#if (SAM3S || SAM3N || SAM4S || SAM4E || SAM4N || SAM4C || SAMG || SAM4CP || SAM4CM || SAMV71 || SAMV70 || SAME70 || SAMS70)
    switch (ul_type) {
    case PIO_PERIPH_A:
        ul_sr = p_pio->PIO_ABCDSR[0];
        p_pio->PIO_ABCDSR[0] &= (~ul_mask & ul_sr);
        ul_sr = p_pio->PIO_ABCDSR[1];
        p_pio->PIO_ABCDSR[1] &= (~ul_mask & ul_sr);
        break;
    case PIO_PERIPH_B:
        ul_sr = p_pio->PIO_ABCDSR[0];
        p_pio->PIO_ABCDSR[0] = (ul_mask | ul_sr);
        ul_sr = p_pio->PIO_ABCDSR[1];
        p_pio->PIO_ABCDSR[1] &= (~ul_mask & ul_sr);
        break;
#if (!SAMG)
    case PIO_PERIPH_C:
        ul_sr = p_pio->PIO_ABCDSR[0];
        p_pio->PIO_ABCDSR[0] &= (~ul_mask & ul_sr);
        ul_sr = p_pio->PIO_ABCDSR[1];
        p_pio->PIO_ABCDSR[1] = (ul_mask | ul_sr);
        break;
    case PIO_PERIPH_D:
        ul_sr = p_pio->PIO_ABCDSR[0];
        p_pio->PIO_ABCDSR[0] = (ul_mask | ul_sr);
        ul_sr = p_pio->PIO_ABCDSR[1];
        p_pio->PIO_ABCDSR[1] = (ul_mask | ul_sr);
        break;
#endif
        /* Other types are invalid in this function */
    case PIO_INPUT:
    case PIO_OUTPUT_0:
    case PIO_OUTPUT_1:
    case PIO_NOT_A_PIN:
        return;
    }
#elif (SAM3XA|| SAM3U)
    switch (ul_type) {
    case PIO_PERIPH_A:
        ul_sr = p_pio->PIO_ABSR;
        p_pio->PIO_ABSR &= (~ul_mask & ul_sr);
        break;
    case PIO_PERIPH_B:
        ul_sr = p_pio->PIO_ABSR;
        p_pio->PIO_ABSR = (ul_mask | ul_sr);
        break;
        // other types are invalid in this function
    case PIO_INPUT:
    case PIO_OUTPUT_0:
    case PIO_OUTPUT_1:
    case PIO_NOT_A_PIN:
        return;
    }
#else
#error "Unsupported device"
#endif
    /* Remove the pins from under the control of PIO */
    p_pio->PIO_PDR = ul_mask;
}
References Pio::PIO_ABCDSR, Pio::PIO_IDR, PIO_INPUT, PIO_NOT_A_PIN, PIO_OUTPUT_0, PIO_OUTPUT_1, Pio::PIO_PDR, PIO_PERIPH_A, and PIO_PERIPH_B.
Referenced by pio_configure(), pio_configure_pin(), and pio_configure_pin_group().
pio_set_pin_group_high()
void pio_set_pin_group_high (Pio * p_pio, uint32_t ul_mask)
Drive a GPIO port to 1.
Parameters
p_pio Base address of the PIO port.
ul_mask Bitmask of one or more pin(s) to toggle.
Definition at line 818 of file pio.c.
{
    /* Value to be driven on the I/O line: 1. */
    p_pio->PIO_SODR = ul_mask;
}
References Pio::PIO_SODR.
pio_set_pin_group_low()
void pio_set_pin_group_low (Pio * p_pio, uint32_t ul_mask)
Drive a GPIO port to 0.
Parameters
p_pio Base address of the PIO port.
ul_mask Bitmask of one or more pin(s) to toggle.
Definition at line 830 of file pio.c.
{
    /* Value to be driven on the I/O line: 0. */
    p_pio->PIO_CODR = ul_mask;
}
References Pio::PIO_CODR.
pio_set_pin_high()
void pio_set_pin_high (uint32_t ul_pin)
Drive a GPIO pin to 1.
Parameters
ul_pin The pin index.
Note
The function pio_configure_pin must be called beforehand.
Definition at line 711 of file pio.c.
{
    Pio *p_pio = pio_get_pin_group(ul_pin);
    /* Value to be driven on the I/O line: 1. */
    p_pio->PIO_SODR = 1 << (ul_pin & 0x1F);
}
References pio_get_pin_group(), and Pio::PIO_SODR.
Referenced by board_init(), ili9488_copy_pixels_from_screen(), ili9488_read_chipid(), ili9488_read_ram(), ili9488_write_ram(), ili9488_write_ram_buffer(), and ili9488_write_register().
pio_set_pin_low()
void pio_set_pin_low (uint32_t ul_pin)
Drive a GPIO pin to 0.
Parameters
ul_pin The pin index.
Note
The function pio_configure_pin must be called before.
Definition at line 726 of file pio.c.
{
    Pio *p_pio = pio_get_pin_group(ul_pin);
    /* Value to be driven on the I/O line: 0. */
    p_pio->PIO_CODR = 1 << (ul_pin & 0x1F);
}
References Pio::PIO_CODR, and pio_get_pin_group().
Referenced by ili9488_write_ram_prepare(), and ili9488_write_register().
pio_set_writeprotect()
void pio_set_writeprotect (Pio * p_pio, const uint32_t ul_enable)
Enable or disable write protect of PIO registers.
Parameters
p_pio Pointer to a PIO instance.
ul_enable 1 to enable, 0 to disable.
Definition at line 667 of file pio.c.
{
    p_pio->PIO_WPMR = PIO_WPMR_WPKEY_PASSWD | (ul_enable & PIO_WPMR_WPEN);
}
References Pio::PIO_WPMR, PIO_WPMR_WPEN, and PIO_WPMR_WPKEY_PASSWD.
pio_sync_output_write()
void pio_sync_output_write (Pio * p_pio, const uint32_t ul_mask)
Synchronously write on output pins.
Note
Only bits unmasked by PIO_OWSR (Output Write Status Register) are written.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Bitmask of one or more pin(s) to configure.
Definition at line 497 of file pio.c.
{
    p_pio->PIO_ODSR = ul_mask;
}
References Pio::PIO_ODSR.
pio_toggle_pin()
void pio_toggle_pin (uint32_t ul_pin)
Toggle a GPIO pin.
Parameters
ul_pin The pin index.
Note
The function pio_configure_pin must be called before.
Definition at line 741 of file pio.c.
{
    Pio *p_pio = pio_get_pin_group(ul_pin);
    if (p_pio->PIO_ODSR & (1 << (ul_pin & 0x1F))) {
        /* Value to be driven on the I/O line: 0. */
        p_pio->PIO_CODR = 1 << (ul_pin & 0x1F);
    } else {
        /* Value to be driven on the I/O line: 1. */
        p_pio->PIO_SODR = 1 << (ul_pin & 0x1F);
    }
}
References Pio::PIO_CODR, pio_get_pin_group(), Pio::PIO_ODSR, and Pio::PIO_SODR.
pio_toggle_pin_group()
void pio_toggle_pin_group (Pio * p_pio, uint32_t ul_mask)
Toggle a GPIO group.
Parameters
p_pio Pointer to a PIO instance.
ul_mask Bitmask of one or more pin(s) to configure.
Definition at line 842 of file pio.c.
{
    if (p_pio->PIO_ODSR & ul_mask) {
        /* Value to be driven on the I/O line: 0. */
        p_pio->PIO_CODR = ul_mask;
    } else {
        /* Value to be driven on the I/O line: 1. */
        p_pio->PIO_SODR = ul_mask;
    }
}
References Pio::PIO_CODR, Pio::PIO_ODSR, and Pio::PIO_SODR.