WINC1500 Weather Client Demo for SAME70 Xplained: Functions
Functions
Common
Functions
sint8 hexstr_2_bytes (uint8 *pu8Out, uint8 *pu8In, uint8 u8SizeOut)
Converts a string of hex characters to bytes.
uint8 m2m_checksum (uint8 *buf, int sz)
Calculates checksum for the specified number of data bytes in specified data buffer.
sint8 m2m_memcmp (uint8 *pu8Buff1, uint8 *pu8Buff2, uint32 u32Size)
Compare specified number of data bytes in pu8Buff1 and pu8Buff2 and decide if they all match.
void m2m_memcpy (uint8 *pDst, uint8 *pSrc, uint32 sz)
Copy specified number of bytes from source buffer to destination buffer.
void m2m_memset (uint8 *pBuf, uint8 val, uint32 sz)
Set specified number of data bytes in specified data buffer to specified value.
uint16 m2m_strlen (uint8 *pcStr)
Returns the length of a null terminated string buffer.
uint8 m2m_strncmp (uint8 *pcS1, uint8 *pcS2, uint16 u16Len)
Compare specified number of data bytes in string buffers pcS1 and pcS2.
uint8 * m2m_strstr (uint8 *pcIn, uint8 *pcStr)
Find the occurrence of pcStr string in pcIn string.
Variables
NMI_API void(* at_sb_printf)(const char *_format,...)
Chooses which function to use in order to output debug.
Detailed Description
Function Documentation
hexstr_2_bytes()
sint8 hexstr_2_bytes (uint8 * pu8Out, uint8 * pu8In, uint8 u8SizeOut)
Converts a string of hex characters to bytes.
Parameters
[out] pu8Out Output buffer (eg {0x11, 0x12, 0x13,...})
[in] pu8In Input buffer (eg {0x31, 0x31, 0x31, 0x32, 0x31, 0x33, ...})
[in] u8SizeOut Length of output buffer (should be half of the length of the input buffer).
Returns
M2M_SUCCESS if successful, M2M_ERR_INVALID_ARG otherwise (eg unrecognised hexchar in input).
Definition at line 148 of file nm_common.c.
{
    while(u8SizeOut--)
    {
        uint8   u8Out = hexchar_2_val(*pu8In++);
        if(u8Out > 0xF)
            return M2M_ERR_INVALID_ARG;
        *pu8Out = u8Out * 0x10;
        u8Out = hexchar_2_val(*pu8In++);
        if(u8Out > 0xF)
            return M2M_ERR_INVALID_ARG;
        *pu8Out += u8Out;
        pu8Out++;
    }
    return M2M_SUCCESS;
}
References hexchar_2_val(), M2M_ERR_INVALID_ARG, and M2M_SUCCESS.
Referenced by m2m_wifi_connect_psk(), and m2m_wifi_connect_wep().
m2m_checksum()
uint8 m2m_checksum (uint8 * buf, int sz)
Calculates checksum for the specified number of data bytes in specified data buffer.
Parameters
[in] sz Number of data bytes used in the checksum calculation.
[in] buf The specified data buffer (whose data bytes will be used to calculate the checksum).
Returns
The calculated checksum.
Definition at line 46 of file nm_common.c.
{
    uint8 cs = 0;
    while(--sz)
    {
        cs ^= *buf;
        buf++;
    }
    return cs;
}
m2m_memcmp()
sint8 m2m_memcmp (uint8 * pu8Buff1, uint8 * pu8Buff2, uint32 u32Size)
Compare specified number of data bytes in pu8Buff1 and pu8Buff2 and decide if they all match.
Parameters
[in] u32Size Number of data bytes to compare.
[in] pu8Buff1 One of two data buffers for the comparison.
[in] pu8Buff2 One of two data buffers for the comparison.
Returns
Zero if matched, one if not matched.
Definition at line 116 of file nm_common.c.
{
    uint32  i;
    sint8       s8Result = 0;
    for(i    = 0 ; i < u32Size ; i++)
    {
        if(pu8Buff1[i] != pu8Buff2[i])
        {
            s8Result = 1;
            break;
        }
    }
    return s8Result;
}
m2m_memcpy()
void m2m_memcpy (uint8 * pDst, uint8 * pSrc, uint32 sz)
Copy specified number of bytes from source buffer to destination buffer.
Parameters
[in] sz Number of data bytes to copy.
[in] pSrc Source buffer.
[out] pDst Destination buffer.
Returns
None
Definition at line 36 of file nm_common.c.
{
    if(sz == 0) return;
    do
    {
        *pDst = *pSrc;
        pDst++;
        pSrc++;
    }while(--sz);
}
Referenced by bind(), connect(), m2m_ssl_send_certs_to_winc(), m2m_wifi_1x_get_option(), m2m_wifi_1x_set_option(), m2m_wifi_cb(), m2m_wifi_configure_sntp(), m2m_wifi_connect_1x_mschap2(), m2m_wifi_connect_1x_tls(), m2m_wifi_connect_prepare_msg(), m2m_wifi_connect_psk(), m2m_wifi_delete_sc(), m2m_wifi_enable_ap(), m2m_wifi_set_device_name(), m2m_wifi_set_mac_address(), m2m_wifi_start_provision_mode(), m2m_wifi_start_provision_mode_ext(), m2m_wifi_wps(), nm_i2c_write_special(), nmi_get_mac_address(), nmi_get_otp_mac_address(), nmi_inet_addr(), set_alpn_list(), and sslSetSockOpt().
m2m_memset()
void m2m_memset (uint8 * pBuf, uint8 val, uint32 sz)
Set specified number of data bytes in specified data buffer to specified value.
Parameters
[in] sz Number of data bytes (in specified data buffer whose values are to be set to the specified value).
[in] val The specified value (to which data bytes in data buffer will be set).
[out] pBuf The specified data buffer (whose data bytes will be set to the specified value).
Returns
None
Definition at line 58 of file nm_common.c.
{
    if(sz == 0) return;
    do
    {
        *pBuf = val;
        pBuf++;
    }while(--sz);
}
Referenced by close(), hif_deinit(), hif_init(), m2m_ota_cb(), m2m_wifi_1x_set_option(), m2m_wifi_cb(), m2m_wifi_connect_1x_mschap2(), m2m_wifi_connect_1x_tls(), m2m_wifi_connect_prepare_msg(), m2m_wifi_connect_psk(), m2m_wifi_delete_sc(), nm_get_firmware_full_info(), nm_get_ota_firmware_info(), nmi_get_otp_mac_address(), sendto(), socket(), socketDeinit(), and socketInit().
m2m_strlen()
uint16 m2m_strlen (uint8 * pcStr)
Returns the length of a null terminated string buffer.
Parameters
[in] pcStr Null terminated string buffer.
Returns
Length of the string in the specified string buffer.
Definition at line 68 of file nm_common.c.
{
    uint16  u16StrLen = 0;
    while(*pcStr)
    {
        u16StrLen ++;
        pcStr++;
    }
    return u16StrLen;
}
Referenced by gethostbyname(), m2m_ota_host_file_get(), m2m_ota_notif_set_url(), m2m_ota_start_update(), m2m_strstr(), m2m_validate_ap_parameters(), m2m_wifi_connect_sc(), m2m_wifi_start_provision_mode_ext(), and set_alpn_list().
m2m_strncmp()
uint8 m2m_strncmp (uint8 * pcS1, uint8 * pcS2, uint16 u16Len)
Compare specified number of data bytes in string buffers pcS1 and pcS2.
Parameters
[in] u16Len Number of data bytes to compare.
[in] pcS1 First of two string buffers for the comparison.
[in] pcS2 Second of two string buffers for the comparison.
Returns
0 if matched, -1 if the first non-matching byte in pcS1 is smaller than that in pcS2, +1 if it is bigger.
Definition at line 79 of file nm_common.c.
{
    for ( ; u16Len > 0; pcS1++, pcS2++, --u16Len)
    if (*pcS1 != *pcS2)
        return ((*(uint8 *)pcS1 < *(uint8 *)pcS2) ? -1 : +1);
    else if (*pcS1 == '\0')
        return 0;
    return 0;
}
Referenced by m2m_strstr().
m2m_strstr()
uint8 * m2m_strstr (uint8 * pcIn, uint8 * pcStr)
Find the occurrence of pcStr string in pcIn string.
Parameters
[in] pcStr One of two string buffers.
[in] pcIn One of two string buffers.
Returns
If pcStr string is part of pcIn string return a valid pointer to the start of pcStr within pcIn. If not, a NULL Pointer is returned.
Definition at line 93 of file nm_common.c.
{
    uint8 u8c;
    uint16 u16StrLen;
    u8c = *pcStr++;
    if (!u8c)
        return (uint8 *) pcIn;  // Trivial empty string case
    u16StrLen = m2m_strlen(pcStr);
    do {
        uint8 u8Sc;
        do {
            u8Sc = *pcIn++;
            if (!u8Sc)
                return (uint8 *) 0;
        } while (u8Sc != u8c);
    } while (m2m_strncmp(pcIn, pcStr, u16StrLen) != 0);
    return (uint8 *) (pcIn - 1);
}
References m2m_strlen(), and m2m_strncmp().
Variable Documentation
at_sb_printf
void(* at_sb_printf)(const char *_format,...) (const char * _format, ...)
Chooses which function to use in order to output debug.
Definition at line 260 of file nm_common.h.