WINC1500 Weather Client Demo for SAME70 Xplained: Standard I/O (stdio)
Standard I/O (stdio)
Common standard I/O driver that implements the stdio read and write functions on AVR and SAM devices.
Modules
Standard serial I/O (stdio)
Common standard serial I/O management driver that implements a stdio serial interface on AVR and SAM devices.
Functions
int _read (int file, char *ptr, int len)
int _write (int file, const char *ptr, int len)
Variables
void(* ptr_get)(void volatile *, char *)
Pointer to the external low level read function.
int(* ptr_put)(void volatile *, char)
Pointer to the external low level write function.
volatile void *volatile stdio_base
volatile void *volatile stdio_base
Pointer to the base of the USART module instance to use for stdio.
Detailed Description
Common standard I/O driver that implements the stdio read and write functions on AVR and SAM devices.
Function Documentation
_read()
int _read (int file, char * ptr, int len)
Definition at line 132 of file read.c.
{
    int nChars = 0;
    if (file != 0) {
        return -1;
    }
    for (; len > 0; --len) {
        ptr_get(stdio_base, ptr);
        ptr++;
        nChars++;
    }
    return nChars;
}
References ptr_get, and stdio_base.
Referenced by stdio_serial_init().
_write()
int _write (int file, const char * ptr, int len)
Definition at line 110 of file write.c.
{
    int nChars = 0;
    if ((file != 1) && (file != 2) && (file!=3)) {
        return -1;
    }
    for (; len != 0; --len) {
        if (ptr_put(stdio_base, *ptr++) < 0) {
            return -1;
        }
        ++nChars;
    }
    return nChars;
}
References ptr_put, and stdio_base.
Referenced by stdio_serial_init().
Variable Documentation
ptr_get
void(* ptr_get) (void volatile *, char *) (void volatile * , char *)
Pointer to the external low level read function.
Definition at line 50 of file read.c.
Referenced by _read(), and stdio_serial_init().
ptr_put
int(* ptr_put) (void volatile *, char) (void volatile * , char)
Pointer to the external low level write function.
Definition at line 47 of file write.c.
Referenced by _write(), and stdio_serial_init().
stdio_base [1/2]
volatile void* volatile stdio_base extern
Definition at line 46 of file write.c.
Referenced by _read().
stdio_base [2/2]
volatile void* volatile stdio_base
Pointer to the base of the USART module instance to use for stdio.
Definition at line 46 of file write.c.
Referenced by _read(), _write(), and stdio_serial_init().