WINC1500 Weather Client Demo for SAME70 Xplained: Global interrupt management
Global interrupt management
This is a driver for global enabling and disabling of interrupts.
Modules
Deprecated interrupt definitions
Macros
#define CONFIG_INTERRUPT_FORCE_INTC
Force usage of the ASF INTC driver.
Interrupt Service Routine definition
typedef uint32_t irqflags_t
Type used for holding state of interrupt flag.
static volatile uint32_t cpu_irq_critical_section_counter
static volatile bool cpu_irq_prev_interrupt_state
static irqflags_t cpu_irq_save (void)
Get and clear the global interrupt flags.
static bool cpu_irq_is_enabled_flags (irqflags_t flags)
Check if interrupts are globally enabled in supplied flags.
static void cpu_irq_restore (irqflags_t flags)
Restore global interrupt flags.
void cpu_irq_enter_critical (void)
void cpu_irq_leave_critical (void)
#define cpu_irq_enable()
Enable interrupts globally.
#define cpu_irq_disable()
Disable interrupts globally.
#define cpu_irq_is_enabled() (__get_PRIMASK() == 0)
Check if interrupts are globally enabled.
#define ISR(func) void func (void)
Define service routine.
#define irq_initialize_vectors()
Initialize interrupt vectors.
#define irq_register_handler(int_num, int_prio)
Register handler for interrupt.
#define Enable_global_interrupt() cpu_irq_enable()
#define Disable_global_interrupt() cpu_irq_disable()
#define Is_global_interrupt_enabled() cpu_irq_is_enabled()
Detailed Description
This is a driver for global enabling and disabling of interrupts.
Macro Definition Documentation
CONFIG_INTERRUPT_FORCE_INTC
#define CONFIG_INTERRUPT_FORCE_INTC
Force usage of the ASF INTC driver.
Predefine this symbol when preprocessing to force the use of the ASF INTC driver. This is useful to ensure compatibility across compilers and shall be used only when required by the application needs.
Definition at line 68 of file interrupt.h.
cpu_irq_disable
#define cpu_irq_disable ()
Value:
    do {                                       \
        __disable_irq();                       \
        __DMB();                               \
        g_interrupt_enabled = false;           \
    } while (0)
Disable interrupts globally.
Definition at line 123 of file interrupt_sam_nvic.h.
cpu_irq_enable
#define cpu_irq_enable ()
Value:
    do {                                       \
        g_interrupt_enabled = true;            \
        __DMB();                               \
        __enable_irq();                        \
    } while (0)
Enable interrupts globally.
Definition at line 117 of file interrupt_sam_nvic.h.
cpu_irq_is_enabled
#define cpu_irq_is_enabled () (__get_PRIMASK() == 0)
Check if interrupts are globally enabled.
Returns
True if interrupts are enabled.
Definition at line 136 of file interrupt_sam_nvic.h.
Disable_global_interrupt
#define Disable_global_interrupt () cpu_irq_disable()
Definition at line 168 of file interrupt_sam_nvic.h.
Enable_global_interrupt
#define Enable_global_interrupt () cpu_irq_enable()
Definition at line 167 of file interrupt_sam_nvic.h.
irq_initialize_vectors
#define irq_initialize_vectors ()
Value:
    do {                             \
    } while(0)
Initialize interrupt vectors.
For NVIC the interrupt vectors are put in vector table. So nothing to do to initialize them, except defined the vector function with right name.
This must be called prior to irq_register_handler.
Definition at line 89 of file interrupt_sam_nvic.h.
irq_register_handler
#define irq_register_handler (int_num, int_prio)
Value:
    NVIC_ClearPendingIRQ(    (IRQn_Type)int_num);                      \
    NVIC_SetPriority(    (IRQn_Type)int_num, int_prio);                \
    NVIC_EnableIRQ(      (IRQn_Type)int_num);                          \
Register handler for interrupt.
For NVIC the interrupt vectors are put in vector table. So nothing to do to register them, except defined the vector function with right name.
Usage:
irq_initialize_vectors();
irq_register_handler(foo_irq_handler);
Note
The function func must be defined with the ISR macro.
The functions prototypes can be found in the device exception header files (exceptions.h).
Definition at line 110 of file interrupt_sam_nvic.h.
Is_global_interrupt_enabled
#define Is_global_interrupt_enabled () cpu_irq_is_enabled()
Definition at line 169 of file interrupt_sam_nvic.h.
ISR
#define ISR (func) void func (void)
Define service routine.
Note
For NVIC devices the interrupt service routines are predefined to add to vector table in binary generation, so there is no service register at run time. The routine collections are in exceptions.h.
Usage:
ISR(foo_irq_handler)
{
     // Function definition
     ...
}
Parameters
func Name for the function.
Definition at line 77 of file interrupt_sam_nvic.h.
Typedef Documentation
irqflags_t
irqflags_t
Type used for holding state of interrupt flag.
Definition at line 130 of file interrupt_sam_nvic.h.
Function Documentation
cpu_irq_enter_critical()
void cpu_irq_enter_critical (void)
Definition at line 47 of file interrupt_sam_nvic.c.
{
    if (cpu_irq_critical_section_counter == 0) {
        if (cpu_irq_is_enabled()) {
            cpu_irq_disable();
            cpu_irq_prev_interrupt_state = true;
        } else {
            /* Make sure the to save the prev state as false */
            cpu_irq_prev_interrupt_state = false;
        }
    }
    cpu_irq_critical_section_counter++;
}
References cpu_irq_critical_section_counter, cpu_irq_disable, cpu_irq_is_enabled, and cpu_irq_prev_interrupt_state.
cpu_irq_is_enabled_flags()
bool cpu_irq_is_enabled_flags (irqflags_t flags) inline static
Check if interrupts are globally enabled in supplied flags.
Parameters
flags Currents state of interrupt flags.
Returns
True if interrupts are enabled.
Definition at line 148 of file interrupt_sam_nvic.h.
{
    return (flags);
}
Referenced by cpu_irq_restore().
cpu_irq_leave_critical()
void cpu_irq_leave_critical (void)
Definition at line 63 of file interrupt_sam_nvic.c.
{
    /* Check if the user is trying to leave a critical section when not in a critical section */
    Assert(cpu_irq_critical_section_counter > 0);
    cpu_irq_critical_section_counter--;
    /* Only enable global interrupts when the counter reaches 0 and the state of the global interrupt flag
       was enabled when entering critical state */
    if ((cpu_irq_critical_section_counter == 0) && (cpu_irq_prev_interrupt_state)) {
        cpu_irq_enable();
    }
}
References Assert, cpu_irq_critical_section_counter, cpu_irq_enable, and cpu_irq_prev_interrupt_state.
cpu_irq_restore()
void cpu_irq_restore (irqflags_t flags) inline static
Restore global interrupt flags.
Use in conjunction with cpu_irq_save.
Parameters
flags State to set interrupt flag to.
Definition at line 153 of file interrupt_sam_nvic.h.
{
    if (cpu_irq_is_enabled_flags(flags))
        cpu_irq_enable();
}
References cpu_irq_enable, and cpu_irq_is_enabled_flags().
Referenced by efc_perform_command(), fpu_disable(), fpu_enable(), and mpu_update_regions().
cpu_irq_save()
irqflags_t cpu_irq_save (void) inline static
Get and clear the global interrupt flags.
Use in conjunction with cpu_irq_restore.
Returns
Current state of interrupt flags.
Note
This function leaves interrupts disabled.
Definition at line 141 of file interrupt_sam_nvic.h.
{
    volatile irqflags_t flags = cpu_irq_is_enabled();
    cpu_irq_disable();
    return flags;
}
References cpu_irq_disable, and cpu_irq_is_enabled.
Referenced by efc_perform_command(), fpu_disable(), fpu_enable(), and mpu_update_regions().
Variable Documentation
cpu_irq_critical_section_counter
volatile uint32_t cpu_irq_critical_section_counter static
Definition at line 138 of file interrupt_sam_nvic.h.
Referenced by cpu_irq_enter_critical(), and cpu_irq_leave_critical().
cpu_irq_prev_interrupt_state
volatile bool cpu_irq_prev_interrupt_state static
Definition at line 139 of file interrupt_sam_nvic.h.
Referenced by cpu_irq_enter_critical(), and cpu_irq_leave_critical().