WINC1500 Weather Client Demo for SAME70 Xplained: Real-time Timer (RTT)
Real-time Timer (RTT)
The Real-time Timer is built around a 32-bit counter used to count roll-over events of the programmable 16-bit prescaler, which enables counting elapsed seconds from a 32 kHz slow clock source.
Functions
void rtt_disable_interrupt (Rtt *p_rtt, uint32_t ul_sources)
Disable RTT interrupts.
void rtt_enable_interrupt (Rtt *p_rtt, uint32_t ul_sources)
Enable RTT interrupts.
uint32_t rtt_get_status (Rtt *p_rtt)
Get the status register value of the given RTT.
uint32_t rtt_init (Rtt *p_rtt, uint16_t us_prescaler)
Initialize the given RTT.
uint32_t rtt_read_timer_value (Rtt *p_rtt)
Read the current value of the RTT timer value.
uint32_t rtt_write_alarm_time (Rtt *p_rtt, uint32_t ul_alarm_time)
Configure the RTT to generate an alarm at the given time.
Detailed Description
The Real-time Timer is built around a 32-bit counter used to count roll-over events of the programmable 16-bit prescaler, which enables counting elapsed seconds from a 32 kHz slow clock source.
This is a driver for configuration and use of the RTT peripheral.
Function Documentation
rtt_disable_interrupt()
void rtt_disable_interrupt (Rtt * p_rtt, uint32_t ul_sources)
Disable RTT interrupts.
Parameters
p_rtt Pointer to an RTT instance.
ul_sources Interrupts to be disabled.
Definition at line 175 of file rtt.c.
{
    uint32_t temp = 0;
    temp = p_rtt->RTT_MR;
    temp &= (~ul_sources);
#if (SAM4N || SAM4S || SAM4E || SAM4C || SAMG51 || SAM4CP || SAM4CM || SAMV71 || SAMV70 || SAME70 || SAMS70)
    temp |= g_wobits_in_rtt_mr;
#endif
    p_rtt->RTT_MR = temp;
}
References Rtt::RTT_MR.
Referenced by rtt_write_alarm_time().
rtt_enable_interrupt()
void rtt_enable_interrupt (Rtt * p_rtt, uint32_t ul_sources)
Enable RTT interrupts.
Parameters
p_rtt Pointer to an RTT instance.
ul_sources Interrupts to be enabled.
Definition at line 157 of file rtt.c.
{
    uint32_t temp;
    temp = p_rtt->RTT_MR;
    temp |= ul_sources;
#if (SAM4N || SAM4S || SAM4E || SAM4C || SAMG51 || SAM4CP || SAM4CM || SAMV71 || SAMV70 || SAME70 || SAMS70)
    temp |= g_wobits_in_rtt_mr;
#endif
    p_rtt->RTT_MR = temp;
}
References Rtt::RTT_MR.
Referenced by configure_rtt(), and rtt_write_alarm_time().
rtt_get_status()
uint32_t rtt_get_status (Rtt * p_rtt)
Get the status register value of the given RTT.
Parameters
p_rtt Pointer to an RTT instance.
Returns
The Real-time Timer status.
Definition at line 212 of file rtt.c.
{
    return p_rtt->RTT_SR;
}
References Rtt::RTT_SR.
Referenced by RTT_Handler().
rtt_init()
uint32_t rtt_init (Rtt * p_rtt, uint16_t us_prescaler)
Initialize the given RTT.
Note
This function restarts the real-time timer. If w_prescaler is equal to zero, the prescaler period is equal to 2^16 * SCLK period. If not, the prescaler period is equal to us_prescaler * SCLK period.
Parameters
p_rtt Pointer to an RTT instance.
us_prescaler Prescaler value for the RTT.
Returns
0 if successful.
Definition at line 78 of file rtt.c.
{
#if (SAM4N || SAM4S || SAM4E || SAM4C || SAMG51 || SAM4CP || SAM4CM || SAMV71 || SAMV70 || SAME70 || SAMS70)
    p_rtt->RTT_MR = (us_prescaler | RTT_MR_RTTRST | g_wobits_in_rtt_mr);
#else
    p_rtt->RTT_MR = (us_prescaler | RTT_MR_RTTRST);
#endif
    return 0;
}
References Rtt::RTT_MR, and RTT_MR_RTTRST.
Referenced by configure_rtt().
rtt_read_timer_value()
uint32_t rtt_read_timer_value (Rtt * p_rtt)
Read the current value of the RTT timer value.
Parameters
p_rtt Pointer to an RTT instance.
Returns
The current Real-time Timer value.
Definition at line 194 of file rtt.c.
{
    uint32_t rtt_val = p_rtt->RTT_VR;
    while (rtt_val != p_rtt->RTT_VR) {
        rtt_val = p_rtt->RTT_VR;
    }
    return rtt_val;
}
References Rtt::RTT_VR.
rtt_write_alarm_time()
uint32_t rtt_write_alarm_time (Rtt * p_rtt, uint32_t ul_alarm_time)
Configure the RTT to generate an alarm at the given time.
alarm happens when CRTV value equals ALMV+1, so RTT_AR should be alarmtime - 1. if you want to get alarm when rtt hit 0 , ALMV should be set to 0xFFFFFFFF.
Parameters
p_rtt Pointer to an RTT instance.
ul_alarm_time Alarm time,Alarm time = ALMV + 1.
Return values
0 Configuration is done.
Alarm time = ALMV + 1,If the incoming parameter is 0, the ALMV is set to 0xFFFFFFFF.
Definition at line 227 of file rtt.c.
{
    uint32_t flag;
    flag = p_rtt->RTT_MR & RTT_MR_ALMIEN;
    rtt_disable_interrupt(RTT, RTT_MR_ALMIEN);
    if(ul_alarm_time == 0) {
        p_rtt->RTT_AR = 0xFFFFFFFF;
    }
    else {
        p_rtt->RTT_AR = ul_alarm_time - 1;
    }
    if (flag) {
        rtt_enable_interrupt(RTT, RTT_MR_ALMIEN);
    }
    return 0;
}
References RTT, Rtt::RTT_AR, rtt_disable_interrupt(), rtt_enable_interrupt(), Rtt::RTT_MR, and RTT_MR_ALMIEN.