WINC1500 Weather Client Demo for SAME70 Xplained: Functions
Functions
SSL
Provides detail on the available APIs for the SSL Layer.
Functions
NMI_API void m2m_ssl_ecc_process_done (void)
Allow SSL driver to tidy up after application has finished processing ECC message.
NMI_API sint8 m2m_ssl_handshake_rsp (tstrEccReqInfo *strECCResp, uint8 *pu8RspDataBuff, uint16 u16RspDataSz)
Sends ECC responses to the WINC.
NMI_API sint8 m2m_ssl_init (tpfAppSSLCb pfAppSSLCb)
Initializes the SSL layer.
NMI_API sint8 m2m_ssl_retrieve_cert (uint16 *pu16Curve, uint8 *pu8Value, uint8 *pu8Sig, tstrECPoint *pstrKey)
Retrieve the next set of information from the WINC for ECDSA verification.
NMI_API sint8 m2m_ssl_retrieve_hash (uint8 *pu8Value, uint16 u16ValueSz)
Retrieve the value from the WINC for ECDSA signing.
NMI_API sint8 m2m_ssl_retrieve_next_for_verifying (tenuEcNamedCurve *penuCurve, uint8 *pu8Value, uint16 *pu16ValueSz, uint8 *pu8Sig, uint16 *pu16SigSz, tstrECPoint *pstrKey)
Retrieve the next set of information from the WINC for ECDSA verification.
NMI_API sint8 m2m_ssl_send_certs_to_winc (uint8 *pu8Buffer, uint32 u32BufferSz)
Sends certificates to the WINC.
NMI_API sint8 m2m_ssl_set_active_ciphersuites (uint32 u32SslCsBMP)
Sets the active ciphersuites.
NMI_API void m2m_ssl_stop_processing_certs (void)
Allow SSL driver to tidy up in case application does not read all available certificates.
NMI_API void m2m_ssl_stop_retrieving (void)
Allow SSL driver to tidy up when the application chooses not to retrieve all available information.
Detailed Description
Provides detail on the available APIs for the SSL Layer.
Function Documentation
m2m_ssl_ecc_process_done()
NMI_API void m2m_ssl_ecc_process_done (void)
Allow SSL driver to tidy up after application has finished processing ECC message.
Returns
None.
Warning
The application should call this function after receiving an SSL callback with message type M2M_SSL_REQ_ECC, after retrieving any related information, and before calling m2m_ssl_handshake_rsp.
Returns
None.
Warning
The application should call this function after receiving an SSL callback with message type M2M_SSL_REQ_ECC, after retrieving any related information, and before calling m2m_ssl_handshake_rsp.
Definition at line 467 of file m2m_ssl.c.
{
    gu32HIFAddr = 0;
}
References gu32HIFAddr.
m2m_ssl_handshake_rsp()
NMI_API sint8 m2m_ssl_handshake_rsp (tstrEccReqInfo * strECCResp, uint8 * pu8RspDataBuff, uint16 u16RspDataSz)
Sends ECC responses to the WINC.
Parameters
[in] strECCResp ECC Response struct.
[in] pu8RspDataBuff Pointer of the response data to be sent.
[in] u16RspDataSz Response data size.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
Definition at line 189 of file m2m_ssl.c.
{
    sint8 s8Ret = M2M_SUCCESS;
    s8Ret = hif_send(M2M_REQ_GROUP_SSL, (M2M_SSL_RESP_ECC | M2M_REQ_DATA_PKT), (uint8 *)strECCResp, sizeof(tstrEccReqInfo), pu8RspDataBuff, u16RspDataSz, sizeof(tstrEccReqInfo));
    return s8Ret;
}
References hif_send(), M2M_REQ_DATA_PKT, M2M_REQ_GROUP_SSL, M2M_SSL_RESP_ECC, and M2M_SUCCESS.
m2m_ssl_init()
NMI_API sint8 m2m_ssl_init (tpfAppSSLCb pfAppSSLCb)
Initializes the SSL layer.
Parameters
[in] pfAppSslCb Application SSL callback function.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
Parameters
[in] pfAppSSLCb Application SSL callback function.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
Definition at line 164 of file m2m_ssl.c.
{
    sint8 s8Ret = M2M_SUCCESS;
    gpfAppSSLCb = pfAppSSLCb;
    gu32HIFAddr = 0;
    genuStatus = TLS_FLASH_ERR_UNKNOWN;
    s8Ret = hif_register_cb(M2M_REQ_GROUP_SSL, m2m_ssl_cb);
    if(s8Ret != M2M_SUCCESS)
    {
        M2M_ERR("hif_register_cb() failed with ret=%d", s8Ret);
    }
    return s8Ret;
}
References genuStatus, gpfAppSSLCb, gu32HIFAddr, hif_register_cb(), M2M_ERR, M2M_REQ_GROUP_SSL, m2m_ssl_cb(), M2M_SUCCESS, and TLS_FLASH_ERR_UNKNOWN.
m2m_ssl_retrieve_cert()
NMI_API sint8 m2m_ssl_retrieve_cert (uint16 * pu16Curve, uint8 * pu8Value, uint8 * pu8Sig, tstrECPoint * pstrKey)
Retrieve the next set of information from the WINC for ECDSA verification.
Parameters
[out] pu16Curve The named curve, to be cast to type tenuEcNamedCurve.
[out] pu8Value Value retrieved for verification. This is the digest of the message, truncated/prepended to the appropriate size. The size of the value is equal to the field size of the curve, hence is determined by pu16Curve.
[out] pu8Sig Signature retrieved for verification. The size of the signature is equal to twice the field size of the curve, hence is determined by pu16Curve.
[out] pstrKey Public key retrieved for verification.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
Precondition
This function should only be called after the application has been notified that verification information is ready via ECC_REQ_SIGN_VERIFY.
Warning
If this function returns M2M_ERR_FAIL, then any remaining verification info from the WINC is lost.
This API has been deprecated and is kept for legacy purposes only. It is recommended that m2m_ssl_retrieve_next_for_verifying is used instead.
Definition at line 378 of file m2m_ssl.c.
{
    uint16  u16ValueSz = 32, u16SigSz = 64;
    return m2m_ssl_retrieve_next_for_verifying((tenuEcNamedCurve *)pu16Curve, pu8Value, &u16ValueSz, pu8Sig, &u16SigSz, pstrKey);
}
References m2m_ssl_retrieve_next_for_verifying().
m2m_ssl_retrieve_hash()
NMI_API sint8 m2m_ssl_retrieve_hash (uint8 * pu8Value, uint16 u16ValueSz)
Retrieve the value from the WINC for ECDSA signing.
Parameters
[out] pu8Value Value retrieved for signing. This is the digest of the message, truncated/prepended to the appropriate size.
[in] u16ValueSz Size of value to be retrieved. (The application should obtain this information, along with the curve, from the associated ECC_REQ_SIGN_GEN notification.)
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
Precondition
This function should only be called after the application has been notified that signing information is ready via ECC_REQ_SIGN_GEN.
Warning
If this function returns M2M_ERR_FAIL, then the value for signing is lost.
Definition at line 400 of file m2m_ssl.c.
{
    sint8   s8Ret = M2M_ERR_FAIL;
    if(gu32HIFAddr == 0) return M2M_ERR_FAIL;
    if(NULL == pu8Value)
    {
        s8Ret = M2M_ERR_INVALID_ARG;
        goto __ERR;
    }
    if(hif_receive(gu32HIFAddr, pu8Value, u16ValueSz, 0) != M2M_SUCCESS) goto __ERR;
    return M2M_SUCCESS;
__ERR:
    hif_receive(0, NULL, 0, 1);
    return s8Ret;
}
References gu32HIFAddr, hif_receive(), M2M_ERR_FAIL, M2M_ERR_INVALID_ARG, M2M_SUCCESS, and NULL.
m2m_ssl_retrieve_next_for_verifying()
NMI_API sint8 m2m_ssl_retrieve_next_for_verifying (tenuEcNamedCurve * penuCurve, uint8 * pu8Value, uint16 * pu16ValueSz, uint8 * pu8Sig, uint16 * pu16SigSz, tstrECPoint * pstrKey)
Retrieve the next set of information from the WINC for ECDSA verification.
Parameters
[out] penuCurve The named curve.
[out] pu8Value Value retrieved for verification. This is the digest of the message, truncated/prepended to the appropriate size.
[in,out] pu16ValueSz in: Size of value buffer provided by caller. out: Size of value retrieved (provided for convenience; the value size is in fact determined by the curve).
[out] pu8Sig Signature retrieved for verification.
[in,out] pu16SigSz in: Size of signature buffer provided by caller. out: Size of signature retrieved (provided for convenience; the signature size is in fact determined by the curve).
[out] pstrKey Public key retrieved for verification.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
Precondition
This function should only be called after the application has been notified that verification information is ready via ECC_REQ_SIGN_VERIFY.
Warning
If this function returns M2M_ERR_FAIL, then any remaining verification info from the WINC is lost.
Definition at line 301 of file m2m_ssl.c.
{
    sint8   s8Ret = M2M_ERR_FAIL;
    uint16  u16HashSz, u16SigSz, u16KeySz;
    if(gu32HIFAddr == 0) return M2M_ERR_FAIL;
    if((NULL == penuCurve) || (NULL == pu8Value) || (NULL == pu16ValueSz) || (NULL == pu8Sig) || (NULL == pu16SigSz) || (NULL == pstrKey))
    {
        s8Ret = M2M_ERR_INVALID_ARG;
        goto __ERR;
    }
    if(hif_receive(gu32HIFAddr, (uint8 *)&u16KeySz, 2, 0) != M2M_SUCCESS) goto __ERR;
    *penuCurve = _htons(u16KeySz);
    gu32HIFAddr += 2;
    if(hif_receive(gu32HIFAddr, (uint8 *)&u16KeySz, 2, 0) != M2M_SUCCESS) goto __ERR;
    u16KeySz = _htons(u16KeySz);
    if(u16KeySz > sizeof(pstrKey->X)) goto __ERR;
    pstrKey->u16Size = u16KeySz;
    gu32HIFAddr += 2;
    if(hif_receive(gu32HIFAddr, (uint8 *)&u16HashSz, 2, 0) != M2M_SUCCESS) goto __ERR;
    u16HashSz = _htons(u16HashSz);
    if(u16HashSz > *pu16ValueSz) goto __ERR;
    *pu16ValueSz = u16HashSz;
    gu32HIFAddr += 2;
    if(hif_receive(gu32HIFAddr, (uint8 *)&u16SigSz, 2, 0) != M2M_SUCCESS) goto __ERR;
    u16SigSz = _htons(u16SigSz);
    if(u16SigSz > *pu16SigSz) goto __ERR;
    *pu16SigSz = u16SigSz;
    gu32HIFAddr += 2;
    if(hif_receive(gu32HIFAddr, pstrKey->X, u16KeySz, 0) != M2M_SUCCESS) goto __ERR;
    gu32HIFAddr += u16KeySz;
    if(hif_receive(gu32HIFAddr, pstrKey->Y, u16KeySz, 0) != M2M_SUCCESS) goto __ERR;
    gu32HIFAddr += u16KeySz;
    if(hif_receive(gu32HIFAddr, pu8Value, u16HashSz, 0) != M2M_SUCCESS) goto __ERR;
    gu32HIFAddr += u16HashSz;
    if(hif_receive(gu32HIFAddr, pu8Sig, u16SigSz, 0) != M2M_SUCCESS) goto __ERR;
    gu32HIFAddr += u16SigSz;
    return M2M_SUCCESS;
__ERR:
    hif_receive(0, NULL, 0, 1);
    return s8Ret;
}
References _htons, gu32HIFAddr, hif_receive(), M2M_ERR_FAIL, M2M_ERR_INVALID_ARG, M2M_SUCCESS, and NULL.
Referenced by m2m_ssl_retrieve_cert().
m2m_ssl_send_certs_to_winc()
NMI_API sint8 m2m_ssl_send_certs_to_winc (uint8 * pu8Buffer, uint32 u32BufferSz)
Sends certificates to the WINC.
Parameters
[in] pu8Buffer Pointer to the certificates.
[in] u32BufferSz Size of the certificates.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
Parameters
[in] pu8Buffer Pointer to the certificates. The buffer format must match the format of tstrTlsSrvSecHdr.
[in] u32BufferSz Size of the certificates.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
Definition at line 207 of file m2m_ssl.c.
{
    sint8 s8Ret = M2M_SUCCESS;
#define TXLIMIT  (256 * 6)
    if(u32BufferSz <= TXLIMIT)
    {
        // set chunk header for one chunk
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcast-align"
        tstrTlsSrvChunkHdr *pchkhdr = (tstrTlsSrvChunkHdr *)pu8Buffer;
#pragma GCC diagnostic pop
        pchkhdr->u16Sig = TLS_CERTS_CHUNKED_SIG_VALUE;
        pchkhdr->u16TotalSize32 = (u32BufferSz + 3) >> 2;
        pchkhdr->u16Offset32 = 0;
        pchkhdr->u16Size32 = (u32BufferSz + 3) >> 2;
        s8Ret = hif_send(M2M_REQ_GROUP_SSL, (M2M_SSL_REQ_WRITE_OWN_CERTS | M2M_REQ_DATA_PKT), NULL, 0, pu8Buffer, u32BufferSz, 0);
        M2M_INFO("Transferred %lu bytes of cert data NON-CHUNKED\n", u32BufferSz);
    }
    else
    {
        // chunk it
        // We are sneaking in a header - tstrTlsSrvChunkHdr
#define CHUNKHDRSZ (sizeof(tstrTlsSrvChunkHdr))
#define CHUNKSZ    (TXLIMIT - 256) // divisible by 4
        uint8 saveblob[CHUNKHDRSZ];
        uint32 ofs = 0;
        uint32 thischunksz = 0;
        // first is special - over writing our header
        m2m_memcpy(saveblob, &pu8Buffer[ofs], CHUNKHDRSZ);
        thischunksz = min(CHUNKSZ, u32BufferSz-ofs); // no need to round up to quad words this time
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcast-align"
        tstrTlsSrvChunkHdr *pchkhdr = (tstrTlsSrvChunkHdr *)&pu8Buffer[ofs];
#pragma GCC diagnostic pop
        pchkhdr->u16Sig = TLS_CERTS_CHUNKED_SIG_VALUE;
        pchkhdr->u16TotalSize32 = ((u32BufferSz + 3) >> 2);
        pchkhdr->u16Offset32 = ((ofs + 3) >> 2);
        pchkhdr->u16Size32 = ((thischunksz + 3) >> 2);
        s8Ret = hif_send(M2M_REQ_GROUP_SSL, (M2M_SSL_REQ_WRITE_OWN_CERTS | M2M_REQ_DATA_PKT), NULL, 0, &pu8Buffer[ofs], thischunksz, 0);
        M2M_INFO("Transferred %u bytes of cert data CHUNKED to offset %u total %u\n", thischunksz, ofs, u32BufferSz);
        m2m_memcpy(&pu8Buffer[ofs], saveblob, CHUNKHDRSZ);
        ofs += thischunksz;
        while(ofs < u32BufferSz)
        {
            // Subsequent chunks write header before and send a little more
            m2m_memcpy(saveblob, &pu8Buffer[ofs-CHUNKHDRSZ], CHUNKHDRSZ);
            thischunksz = min(CHUNKSZ, u32BufferSz-ofs);
            thischunksz = (thischunksz + 3) & 0xFFFFFFFC; // needs to round up to quad word length
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcast-align"
            pchkhdr = (tstrTlsSrvChunkHdr *)&pu8Buffer[ofs - CHUNKHDRSZ];
#pragma GCC diagnostic pop
            pchkhdr->u16Sig = TLS_CERTS_CHUNKED_SIG_VALUE;
            pchkhdr->u16TotalSize32 = ((u32BufferSz + 3) >> 2);
            pchkhdr->u16Offset32 = ((ofs + 3) >> 2);
            pchkhdr->u16Size32 = ((thischunksz + 3) >> 2);
            s8Ret = hif_send(M2M_REQ_GROUP_SSL, (M2M_SSL_REQ_WRITE_OWN_CERTS | M2M_REQ_DATA_PKT), NULL, 0, &pu8Buffer[ofs - CHUNKHDRSZ], thischunksz + CHUNKHDRSZ, 0);
            M2M_INFO("Transferred %lu bytes of cert data CHUNKED to offset %u total %u\n", thischunksz, ofs, u32BufferSz);
            m2m_memcpy(&pu8Buffer[ofs - CHUNKHDRSZ], saveblob, CHUNKHDRSZ);
            ofs += thischunksz;
        }
    }
    return s8Ret;
}
References CHUNKHDRSZ, CHUNKSZ, hif_send(), M2M_INFO, m2m_memcpy(), M2M_REQ_DATA_PKT, M2M_REQ_GROUP_SSL, M2M_SSL_REQ_WRITE_OWN_CERTS, M2M_SUCCESS, min, NULL, TLS_CERTS_CHUNKED_SIG_VALUE, TXLIMIT, tstrTlsSrvChunkHdr::u16Offset32, tstrTlsSrvChunkHdr::u16Sig, tstrTlsSrvChunkHdr::u16Size32, and tstrTlsSrvChunkHdr::u16TotalSize32.
m2m_ssl_set_active_ciphersuites()
NMI_API sint8 m2m_ssl_set_active_ciphersuites (uint32 u32SslCsBMP)
Sets the active ciphersuites.
Override the default Active SSL ciphers in the SSL module with a certain combination selected by the caller in the form of a bitmap containing the required ciphers to be on. There is no need to call this function if the application will not change the default ciphersuites.
Parameters
[in] u32SslCsBMP Bitmap containing the desired ciphers to be enabled for the SSL module. The ciphersuites are defined in TLS Cipher Suite IDs. The default ciphersuites are all ciphersuites supported by the firmware with the exception of ECC ciphersuites. The caller can override the default with any desired combination. If u32SslCsBMP does not contain any ciphersuites supported by firmware, then the current active list will not change.
Returns
SOCK_ERR_NO_ERROR
SOCK_ERR_INVALID_ARG
Override the default Active SSL ciphers in the SSL module with a certain combination selected by the caller in the form of a bitmap containing the required ciphers to be on.
There is no need to call this function if the application will not change the default ciphersuites.
Parameters
[in] u32SslCsBMP Bitmap containing the desired ciphers to be enabled for the SSL module. The ciphersuites are defined in TLS Cipher Suite IDs. The default ciphersuites are all ciphersuites supported by the firmware with the exception of ECC ciphersuites. The caller can override the default with any desired combination. If u32SslCsBMP does not contain any ciphersuites supported by firmware, then the current active list will not change.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
Definition at line 491 of file m2m_ssl.c.
{
    sint8 s8Ret = M2M_SUCCESS;
    tstrSslSetActiveCsList  strCsList;
    strCsList.u32CsBMP = u32SslCsBMP;
    s8Ret = hif_send(M2M_REQ_GROUP_SSL, M2M_SSL_REQ_SET_CS_LIST, (uint8 *)&strCsList, sizeof(tstrSslSetActiveCsList), NULL, 0, 0);
    return s8Ret;
}
References hif_send(), M2M_REQ_GROUP_SSL, M2M_SSL_REQ_SET_CS_LIST, M2M_SUCCESS, NULL, and tstrSslSetActiveCsList::u32CsBMP.
m2m_ssl_stop_processing_certs()
NMI_API void m2m_ssl_stop_processing_certs (void)
Allow SSL driver to tidy up in case application does not read all available certificates.
Returns
None.
Warning
This API has been deprecated and is kept for legacy purposes only. It is recommended that m2m_ssl_stop_retrieving is used instead.
Definition at line 452 of file m2m_ssl.c.
{
    m2m_ssl_stop_retrieving();
}
References m2m_ssl_stop_retrieving().
m2m_ssl_stop_retrieving()
NMI_API void m2m_ssl_stop_retrieving (void)
Allow SSL driver to tidy up when the application chooses not to retrieve all available information.
Returns
None.
Warning
The application must call this function if it has been notified (via ECC_REQ_SIGN_GEN or ECC_REQ_SIGN_VERIFY) that information is available for retrieving from the WINC, but chooses not to retrieve it all. The application must not call this function if it has retrieved all the available information, or if a retrieve function returned M2M_ERR_FAIL indicating that any remaining information has been lost.
See also
m2m_ssl_retrieve_next_for_verifying
m2m_ssl_retrieve_cert
m2m_ssl_retrieve_hash
Returns
None.
Warning
The application must call this function if it has been notified (via ECC_REQ_SIGN_GEN or ECC_REQ_SIGN_VERIFY) that information is available for retrieving from the WINC, but chooses not to retrieve it all. The application must not call this function if it has retrieved all the available information, or if a retrieve function returned M2M_ERR_FAIL indicating that any remaining information has been lost.
See also
m2m_ssl_retrieve_next_for_verifying
m2m_ssl_retrieve_cert
m2m_ssl_retrieve_hash
Definition at line 439 of file m2m_ssl.c.
{
    hif_receive(0, NULL, 0, 1);
}
References hif_receive(), and NULL.
Referenced by m2m_ssl_stop_processing_certs().