WINC1500 Weather Client Demo for SAME70 Xplained: Oscillator Management
Oscillator Management
Clock Management
This group contains functions and definitions related to configuring and enabling/disabling on-chip oscillators.
Oscillator Management
static void osc_wait_ready (uint8_t id)
Wait until the oscillator identified by id is ready.
Oscillator clock speed in hertz
static void osc_enable (uint32_t ul_id)
static void osc_disable (uint32_t ul_id)
static bool osc_is_ready (uint32_t ul_id)
static uint32_t osc_get_rate (uint32_t ul_id)
#define OSC_SLCK_32K_RC_HZ CHIP_FREQ_SLCK_RC
Internal 32kHz RC oscillator.
#define OSC_SLCK_32K_XTAL_HZ BOARD_FREQ_SLCK_XTAL
External 32kHz crystal oscillator.
#define OSC_SLCK_32K_BYPASS_HZ BOARD_FREQ_SLCK_BYPASS
External 32kHz bypass oscillator.
#define OSC_MAINCK_4M_RC_HZ CHIP_FREQ_MAINCK_RC_4MHZ
Internal 4MHz RC oscillator.
#define OSC_MAINCK_8M_RC_HZ CHIP_FREQ_MAINCK_RC_8MHZ
Internal 8MHz RC oscillator.
#define OSC_MAINCK_12M_RC_HZ CHIP_FREQ_MAINCK_RC_12MHZ
Internal 12MHz RC oscillator.
#define OSC_MAINCK_XTAL_HZ BOARD_FREQ_MAINCK_XTAL
External crystal oscillator.
#define OSC_MAINCK_BYPASS_HZ BOARD_FREQ_MAINCK_BYPASS
External bypass oscillator.
Oscillator identifiers
#define OSC_SLCK_32K_RC 0
Internal 32kHz RC oscillator.
#define OSC_SLCK_32K_XTAL 1
External 32kHz crystal oscillator.
#define OSC_SLCK_32K_BYPASS 2
External 32kHz bypass oscillator.
#define OSC_MAINCK_4M_RC 3
Internal 4MHz RC oscillator.
#define OSC_MAINCK_8M_RC 4
Internal 8MHz RC oscillator.
#define OSC_MAINCK_12M_RC 5
Internal 12MHz RC oscillator.
#define OSC_MAINCK_XTAL 6
External crystal oscillator.
#define OSC_MAINCK_BYPASS 7
External bypass oscillator.
Detailed Description
This group contains functions and definitions related to configuring and enabling/disabling on-chip oscillators.
Internal RC-oscillators, external crystal oscillators and external clock generators are supported by this module. What all of these have in common is that they swing at a fixed, nominal frequency which is normally not adjustable.
Example: Enabling an oscillator
The following example demonstrates how to enable the external oscillator on XMEGA A and wait for it to be ready to use. The oscillator identifiers are platform-specific, so while the same procedure is used on all platforms, the parameter to osc_enable() will be different from device to device.
osc_enable(OSC_ID_XOSC);
osc_wait_ready(OSC_ID_XOSC);
Board-specific Definitions
If external oscillators are used, the board code must provide the following definitions for each of those:
BOARD_<osc name>_HZ: The nominal frequency of the oscillator.
BOARD_<osc name>_STARTUP_US: The startup time of the oscillator in microseconds.
BOARD_<osc name>_TYPE: The type of oscillator connected, i.e. whether it's a crystal or external clock, and sometimes what kind of crystal it is. The meaning of this value is platform-specific.
Macro Definition Documentation
OSC_MAINCK_12M_RC
#define OSC_MAINCK_12M_RC 5
Internal 12MHz RC oscillator.
Definition at line 92 of file same70/osc.h.
OSC_MAINCK_12M_RC_HZ
#define OSC_MAINCK_12M_RC_HZ CHIP_FREQ_MAINCK_RC_12MHZ
Internal 12MHz RC oscillator.
Definition at line 104 of file same70/osc.h.
OSC_MAINCK_4M_RC
#define OSC_MAINCK_4M_RC 3
Internal 4MHz RC oscillator.
Definition at line 90 of file same70/osc.h.
OSC_MAINCK_4M_RC_HZ
#define OSC_MAINCK_4M_RC_HZ CHIP_FREQ_MAINCK_RC_4MHZ
Internal 4MHz RC oscillator.
Definition at line 102 of file same70/osc.h.
OSC_MAINCK_8M_RC
#define OSC_MAINCK_8M_RC 4
Internal 8MHz RC oscillator.
Definition at line 91 of file same70/osc.h.
OSC_MAINCK_8M_RC_HZ
#define OSC_MAINCK_8M_RC_HZ CHIP_FREQ_MAINCK_RC_8MHZ
Internal 8MHz RC oscillator.
Definition at line 103 of file same70/osc.h.
OSC_MAINCK_BYPASS
#define OSC_MAINCK_BYPASS 7
External bypass oscillator.
Definition at line 94 of file same70/osc.h.
OSC_MAINCK_BYPASS_HZ
#define OSC_MAINCK_BYPASS_HZ BOARD_FREQ_MAINCK_BYPASS
External bypass oscillator.
Definition at line 106 of file same70/osc.h.
OSC_MAINCK_XTAL
#define OSC_MAINCK_XTAL 6
External crystal oscillator.
Definition at line 93 of file same70/osc.h.
OSC_MAINCK_XTAL_HZ
#define OSC_MAINCK_XTAL_HZ BOARD_FREQ_MAINCK_XTAL
External crystal oscillator.
Definition at line 105 of file same70/osc.h.
OSC_SLCK_32K_BYPASS
#define OSC_SLCK_32K_BYPASS 2
External 32kHz bypass oscillator.
Definition at line 89 of file same70/osc.h.
OSC_SLCK_32K_BYPASS_HZ
#define OSC_SLCK_32K_BYPASS_HZ BOARD_FREQ_SLCK_BYPASS
External 32kHz bypass oscillator.
Definition at line 101 of file same70/osc.h.
OSC_SLCK_32K_RC
#define OSC_SLCK_32K_RC 0
Internal 32kHz RC oscillator.
Definition at line 87 of file same70/osc.h.
OSC_SLCK_32K_RC_HZ
#define OSC_SLCK_32K_RC_HZ CHIP_FREQ_SLCK_RC
Internal 32kHz RC oscillator.
Definition at line 99 of file same70/osc.h.
OSC_SLCK_32K_XTAL
#define OSC_SLCK_32K_XTAL 1
External 32kHz crystal oscillator.
Definition at line 88 of file same70/osc.h.
OSC_SLCK_32K_XTAL_HZ
#define OSC_SLCK_32K_XTAL_HZ BOARD_FREQ_SLCK_XTAL
External 32kHz crystal oscillator.
Definition at line 100 of file same70/osc.h.
Function Documentation
osc_disable()
static void osc_disable (uint32_t ul_id) inline static
Definition at line 151 of file same70/osc.h.
{
    switch (ul_id) {
    case OSC_SLCK_32K_RC:
    case OSC_SLCK_32K_XTAL:
    case OSC_SLCK_32K_BYPASS:
        break;
    case OSC_MAINCK_4M_RC:
    case OSC_MAINCK_8M_RC:
    case OSC_MAINCK_12M_RC:
        pmc_osc_disable_fastrc();
        break;
    case OSC_MAINCK_XTAL:
        pmc_osc_disable_xtal(PMC_OSC_XTAL);
        break;
    case OSC_MAINCK_BYPASS:
        pmc_osc_disable_xtal(PMC_OSC_BYPASS);
        break;
    }
}
References OSC_MAINCK_12M_RC, OSC_MAINCK_4M_RC, OSC_MAINCK_8M_RC, OSC_MAINCK_BYPASS, OSC_MAINCK_XTAL, OSC_SLCK_32K_BYPASS, OSC_SLCK_32K_RC, OSC_SLCK_32K_XTAL, PMC_OSC_BYPASS, pmc_osc_disable_fastrc(), pmc_osc_disable_xtal(), and PMC_OSC_XTAL.
osc_enable()
static void osc_enable (uint32_t ul_id) inline static
Definition at line 109 of file same70/osc.h.
{
    switch (ul_id) {
    case OSC_SLCK_32K_RC:
        break;
    case OSC_SLCK_32K_XTAL:
        pmc_switch_sclk_to_32kxtal(PMC_OSC_XTAL);
        break;
    case OSC_SLCK_32K_BYPASS:
        pmc_switch_sclk_to_32kxtal(PMC_OSC_BYPASS);
        break;
    case OSC_MAINCK_4M_RC:
        pmc_switch_mainck_to_fastrc(CKGR_MOR_MOSCRCF_4_MHz);
        break;
    case OSC_MAINCK_8M_RC:
        pmc_switch_mainck_to_fastrc(CKGR_MOR_MOSCRCF_8_MHz);
        break;
    case OSC_MAINCK_12M_RC:
        pmc_switch_mainck_to_fastrc(CKGR_MOR_MOSCRCF_12_MHz);
        break;
    case OSC_MAINCK_XTAL:
        pmc_switch_mainck_to_xtal(PMC_OSC_XTAL,
            pmc_us_to_moscxtst(BOARD_OSC_STARTUP_US,
                OSC_SLCK_32K_RC_HZ));
        break;
    case OSC_MAINCK_BYPASS:
        pmc_switch_mainck_to_xtal(PMC_OSC_BYPASS,
            pmc_us_to_moscxtst(BOARD_OSC_STARTUP_US,
                OSC_SLCK_32K_RC_HZ));
        break;
    }
}
References BOARD_OSC_STARTUP_US, CKGR_MOR_MOSCRCF_12_MHz, CKGR_MOR_MOSCRCF_4_MHz, CKGR_MOR_MOSCRCF_8_MHz, OSC_MAINCK_12M_RC, OSC_MAINCK_4M_RC, OSC_MAINCK_8M_RC, OSC_MAINCK_BYPASS, OSC_MAINCK_XTAL, OSC_SLCK_32K_BYPASS, OSC_SLCK_32K_RC, OSC_SLCK_32K_RC_HZ, OSC_SLCK_32K_XTAL, PMC_OSC_BYPASS, PMC_OSC_XTAL, pmc_switch_mainck_to_fastrc(), pmc_switch_mainck_to_xtal(), pmc_switch_sclk_to_32kxtal(), and pmc_us_to_moscxtst.
Referenced by genclk_enable_source(), pll_enable_source(), and sysclk_init().
osc_get_rate()
static uint32_t osc_get_rate (uint32_t ul_id) inline static
Definition at line 196 of file same70/osc.h.
{
    switch (ul_id) {
    case OSC_SLCK_32K_RC:
        return OSC_SLCK_32K_RC_HZ;
    case OSC_SLCK_32K_XTAL:
        return BOARD_FREQ_SLCK_XTAL;
    case OSC_SLCK_32K_BYPASS:
        return BOARD_FREQ_SLCK_BYPASS;
    case OSC_MAINCK_4M_RC:
        return OSC_MAINCK_4M_RC_HZ;
    case OSC_MAINCK_8M_RC:
        return OSC_MAINCK_8M_RC_HZ;
    case OSC_MAINCK_12M_RC:
        return OSC_MAINCK_12M_RC_HZ;
    case OSC_MAINCK_XTAL:
        return BOARD_FREQ_MAINCK_XTAL;
    case OSC_MAINCK_BYPASS:
        return BOARD_FREQ_MAINCK_BYPASS;
    }
    return 0;
}
References BOARD_FREQ_MAINCK_BYPASS, BOARD_FREQ_MAINCK_XTAL, BOARD_FREQ_SLCK_BYPASS, BOARD_FREQ_SLCK_XTAL, OSC_MAINCK_12M_RC, OSC_MAINCK_12M_RC_HZ, OSC_MAINCK_4M_RC, OSC_MAINCK_4M_RC_HZ, OSC_MAINCK_8M_RC, OSC_MAINCK_8M_RC_HZ, OSC_MAINCK_BYPASS, OSC_MAINCK_XTAL, OSC_SLCK_32K_BYPASS, OSC_SLCK_32K_RC, OSC_SLCK_32K_RC_HZ, and OSC_SLCK_32K_XTAL.
Referenced by pll_config_init().
osc_is_ready()
static bool osc_is_ready (uint32_t ul_id) inline static
Definition at line 175 of file same70/osc.h.
{
    switch (ul_id) {
    case OSC_SLCK_32K_RC:
        return 1;
    case OSC_SLCK_32K_XTAL:
    case OSC_SLCK_32K_BYPASS:
        return pmc_osc_is_ready_32kxtal();
    case OSC_MAINCK_4M_RC:
    case OSC_MAINCK_8M_RC:
    case OSC_MAINCK_12M_RC:
    case OSC_MAINCK_XTAL:
    case OSC_MAINCK_BYPASS:
        return pmc_osc_is_ready_mainck();
    }
    return 0;
}
References OSC_MAINCK_12M_RC, OSC_MAINCK_4M_RC, OSC_MAINCK_8M_RC, OSC_MAINCK_BYPASS, OSC_MAINCK_XTAL, OSC_SLCK_32K_BYPASS, OSC_SLCK_32K_RC, OSC_SLCK_32K_XTAL, pmc_osc_is_ready_32kxtal(), and pmc_osc_is_ready_mainck().
Referenced by genclk_enable_source(), and osc_wait_ready().
osc_wait_ready()
static void osc_wait_ready (uint8_t id) inline static
Wait until the oscillator identified by id is ready.
This function will busy-wait for the oscillator identified by id to become stable and ready to use as a clock source.
Parameters
id A number identifying the oscillator to wait for.
Definition at line 162 of file osc.h.
{
    while (!osc_is_ready(id)) {
        /* Do nothing */
    }
}
References osc_is_ready().
Referenced by genclk_enable_source(), pll_enable_source(), and sysclk_init().