WINC1500 Weather Client Demo for SAME70 Xplained: High-Speed Two-Wire Interface (TWIHS)
High-Speed Two-Wire Interface (TWIHS)
Driver for the TWIHS (High-Speed Two-Wire Interface).
Macros
#define I2C_FAST_MODE_SPEED 400000
#define LOW_LEVEL_TIME_LIMIT 384000
#define TWIHS_CLK_CALC_ARGU 3
#define TWIHS_CLK_DIV_MAX 0xFF
#define TWIHS_CLK_DIV_MIN 7
#define TWIHS_CLK_DIVIDER 2
Functions
void twihs_disable_interrupt (Twihs *p_twihs, uint32_t ul_sources)
Disable TWIHS interrupts.
void twihs_disable_master_mode (Twihs *p_twihs)
Disable TWIHS master mode.
void twihs_disable_slave_mode (Twihs *p_twihs)
Disable TWIHS slave mode.
void twihs_enable_interrupt (Twihs *p_twihs, uint32_t ul_sources)
Enable TWIHS interrupts.
void twihs_enable_master_mode (Twihs *p_twihs)
Enable TWIHS master mode.
void twihs_enable_slave_mode (Twihs *p_twihs)
Enable TWIHS slave mode.
uint32_t twihs_get_interrupt_mask (Twihs *p_twihs)
Read TWIHS interrupt mask.
uint32_t twihs_get_interrupt_status (Twihs *p_twihs)
Get TWIHS interrupt status.
Pdc * twihs_get_pdc_base (Twihs *p_twihs)
Get TWIHS PDC base address.
void twihs_mask_slave_addr (Twihs *p_twihs, uint32_t ul_mask)
A mask can be applied on the slave device address in slave mode in order to allow multiple address answer.
uint32_t twihs_master_init (Twihs *p_twihs, const twihs_options_t *p_opt)
Initialize TWIHS master mode.
uint32_t twihs_master_read (Twihs *p_twihs, twihs_packet_t *p_packet)
Read multiple bytes from a TWIHS compatible slave device.
uint32_t twihs_master_write (Twihs *p_twihs, twihs_packet_t *p_packet)
Write multiple bytes to a TWIHS compatible slave device.
static uint32_t twihs_mk_addr (const uint8_t *addr, int len)
Construct the TWIHS module address register field.
uint32_t twihs_probe (Twihs *p_twihs, uint8_t uc_slave_addr)
Test if a chip answers a given I2C address.
uint8_t twihs_read_byte (Twihs *p_twihs)
Reads a byte from the TWIHS bus.
void twihs_read_write_protection_status (Twihs *p_twihs, uint32_t *p_status)
Read the write protection status.
void twihs_reset (Twihs *p_twihs)
Reset TWIHS.
void twihs_set_alternative_command (Twihs *p_twihs, uint32_t ul_alt_cmd)
Set length/direction/PEC for alternative command mode.
void twihs_set_filter (Twihs *p_twihs, uint32_t ul_filter)
Set the filter for TWIHS.
void twihs_set_slave_addr (Twihs *p_twihs, uint32_t ul_device_addr)
Set TWIHS slave address.
uint32_t twihs_set_speed (Twihs *p_twihs, uint32_t ul_speed, uint32_t ul_mck)
Set the I2C bus speed in conjunction with the clock frequency.
void twihs_set_write_protection (Twihs *p_twihs, bool flag)
Enables/Disables write protection mode.
void twihs_slave_init (Twihs *p_twihs, uint32_t ul_device_addr)
Initialize TWIHS slave mode.
uint32_t twihs_slave_read (Twihs *p_twihs, uint8_t *p_data)
Read data from master.
uint32_t twihs_slave_write (Twihs *p_twihs, uint8_t *p_data)
Write data to TWIHS bus.
void twihs_smbus_set_timing (Twihs *p_twihs, uint32_t ul_timing)
Set the prescaler, TLOW:SEXT, TLOW:MEXT and clock high max cycles for SMBUS mode.
void twihs_write_byte (Twihs *p_twihs, uint8_t uc_byte)
Sends a byte of data to one of the TWIHS slaves on the bus.
Detailed Description
Driver for the TWIHS (High-Speed Two-Wire Interface).
This driver provides access to the main features of the TWIHS controller. The TWIHS interconnects components on a unique two-wire bus. The TWIHS is programmable as a master or a slave with sequential or single-byte access. Multiple master capability is supported. The High Speed of 3.4Mbits per second can be achieved in slave mode only.
Usage
Enable the TWIHS peripheral clock in the PMC.
Enable the required TWIHS PIOs (see pio.h).
Enable TWIHS master mode by calling twihs_enable_master_mode if it is a master on the I2C bus.
Configure the TWIHS in master mode by calling twihs_master_init.
Send data to a slave device on the I2C bus by calling twihs_master_write.
Receive data from a slave device on the I2C bus by calling the twihs_master_read.
Enable TWIHS slave mode by calling twihs_enable_slave_mode if it is a slave on the I2C bus.
Configure the TWIHS in slave mode by calling twihs_slave_init.
Macro Definition Documentation
I2C_FAST_MODE_SPEED
#define I2C_FAST_MODE_SPEED 400000
Definition at line 73 of file twihs.c.
LOW_LEVEL_TIME_LIMIT
#define LOW_LEVEL_TIME_LIMIT 384000
Definition at line 72 of file twihs.c.
TWIHS_CLK_CALC_ARGU
#define TWIHS_CLK_CALC_ARGU 3
Definition at line 75 of file twihs.c.
TWIHS_CLK_DIV_MAX
#define TWIHS_CLK_DIV_MAX 0xFF
Definition at line 76 of file twihs.c.
TWIHS_CLK_DIV_MIN
#define TWIHS_CLK_DIV_MIN 7
Definition at line 77 of file twihs.c.
TWIHS_CLK_DIVIDER
#define TWIHS_CLK_DIVIDER 2
Definition at line 74 of file twihs.c.
Function Documentation
twihs_disable_interrupt()
void twihs_disable_interrupt (Twihs * p_twihs, uint32_t ul_sources)
Disable TWIHS interrupts.
Parameters
p_twihs Pointer to a TWIHS instance.
ul_sources Interrupts to be disabled.
Definition at line 406 of file twihs.c.
{
    /* Disable the specified interrupts */
    p_twihs->TWIHS_IDR = ul_sources;
    /* Dummy read */
    p_twihs->TWIHS_SR;
}
References Twihs::TWIHS_IDR, and Twihs::TWIHS_SR.
twihs_disable_master_mode()
void twihs_disable_master_mode (Twihs * p_twihs)
Disable TWIHS master mode.
Parameters
p_twihs Pointer to a TWIHS instance.
Definition at line 99 of file twihs.c.
{
    /* Set Master Disable bit */
    p_twihs->TWIHS_CR = TWIHS_CR_MSDIS;
}
References Twihs::TWIHS_CR, and TWIHS_CR_MSDIS.
twihs_disable_slave_mode()
void twihs_disable_slave_mode (Twihs * p_twihs)
Disable TWIHS slave mode.
Parameters
p_twihs Pointer to a TWIHS instance.
Definition at line 481 of file twihs.c.
{
    /* Set Slave Disable bit */
    p_twihs->TWIHS_CR = TWIHS_CR_SVDIS;
}
References Twihs::TWIHS_CR, and TWIHS_CR_SVDIS.
twihs_enable_interrupt()
void twihs_enable_interrupt (Twihs * p_twihs, uint32_t ul_sources)
Enable TWIHS interrupts.
Parameters
p_twihs Pointer to a TWIHS instance.
ul_sources Interrupts to be enabled.
Definition at line 394 of file twihs.c.
{
    /* Enable the specified interrupts */
    p_twihs->TWIHS_IER = ul_sources;
}
References Twihs::TWIHS_IER.
twihs_enable_master_mode()
void twihs_enable_master_mode (Twihs * p_twihs)
Enable TWIHS master mode.
Parameters
p_twihs Pointer to a TWIHS instance.
Definition at line 84 of file twihs.c.
{
    /* Set Master Disable bit and Slave Disable bit */
    p_twihs->TWIHS_CR = TWIHS_CR_MSDIS;
    p_twihs->TWIHS_CR = TWIHS_CR_SVDIS;
    /* Set Master Enable bit */
    p_twihs->TWIHS_CR = TWIHS_CR_MSEN;
}
References Twihs::TWIHS_CR, TWIHS_CR_MSDIS, TWIHS_CR_MSEN, and TWIHS_CR_SVDIS.
Referenced by twihs_master_init().
twihs_enable_slave_mode()
void twihs_enable_slave_mode (Twihs * p_twihs)
Enable TWIHS slave mode.
Parameters
p_twihs Pointer to a TWIHS instance.
Definition at line 466 of file twihs.c.
{
    /* Set Master Disable bit and Slave Disable bit */
    p_twihs->TWIHS_CR = TWIHS_CR_MSDIS;
    p_twihs->TWIHS_CR = TWIHS_CR_SVDIS;
    /* Set Slave Enable bit */
    p_twihs->TWIHS_CR = TWIHS_CR_SVEN;
}
References Twihs::TWIHS_CR, TWIHS_CR_MSDIS, TWIHS_CR_SVDIS, and TWIHS_CR_SVEN.
Referenced by twihs_slave_init().
twihs_get_interrupt_mask()
uint32_t twihs_get_interrupt_mask (Twihs * p_twihs)
Read TWIHS interrupt mask.
Parameters
p_twihs Pointer to a TWIHS instance.
Returns
The interrupt mask value.
Definition at line 433 of file twihs.c.
{
    return p_twihs->TWIHS_IMR;
}
References Twihs::TWIHS_IMR.
twihs_get_interrupt_status()
uint32_t twihs_get_interrupt_status (Twihs * p_twihs)
Get TWIHS interrupt status.
Parameters
p_twihs Pointer to a TWIHS instance.
Return values
TWIHS interrupt status.
Definition at line 421 of file twihs.c.
{
    return p_twihs->TWIHS_SR;
}
References Twihs::TWIHS_SR.
twihs_get_pdc_base()
Pdc * twihs_get_pdc_base (Twihs * p_twihs)
Get TWIHS PDC base address.
Parameters
p_twihs Pointer to a TWIHS instance.
Returns
TWIHS PDC registers base for PDC driver to access.
Definition at line 604 of file twihs.c.
{
    Pdc *p_pdc_base = NULL;
    if (p_twihs == TWI0) {
        p_pdc_base = PDC_TWI0;
    } else {
        Assert(false);
    }
    return p_pdc_base;
}
References Assert, and NULL.
twihs_mask_slave_addr()
void twihs_mask_slave_addr (Twihs * p_twihs, uint32_t ul_mask)
A mask can be applied on the slave device address in slave mode in order to allow multiple address answer.
For each bit of the MASK field set to one the corresponding SADR bit will be masked.
Parameters
p_twihs Base address of the TWIHS instance.
ul_mask Mask value.
Definition at line 686 of file twihs.c.
{
    p_twihs->TWIHS_SMR |= TWIHS_SMR_MASK(ul_mask);
}
References Twihs::TWIHS_SMR, and TWIHS_SMR_MASK.
twihs_master_init()
uint32_t twihs_master_init (Twihs * p_twihs, const twihs_options_t * p_opt)
Initialize TWIHS master mode.
Parameters
p_twihs Pointer to a TWIHS instance.
p_opt Options for initializing the TWIHS module (see twihs_options_t).
Returns
TWIHS_SUCCESS if initialization is complete, error code otherwise.
Definition at line 113 of file twihs.c.
{
    uint32_t status = TWIHS_SUCCESS;
    /* Disable TWIHS interrupts */
    p_twihs->TWIHS_IDR = ~0UL;
    /* Dummy read in status register */
    p_twihs->TWIHS_SR;
    /* Reset TWIHS peripheral */
    twihs_reset(p_twihs);
    twihs_enable_master_mode(p_twihs);
    /* Select the speed */
    if (twihs_set_speed(p_twihs, p_opt->speed, p_opt->master_clk) == FAIL) {
        /* The desired speed setting is rejected */
        status = TWIHS_INVALID_ARGUMENT;
    }
    return status;
}
References FAIL, twihs_options::master_clk, twihs_options::speed, twihs_enable_master_mode(), Twihs::TWIHS_IDR, TWIHS_INVALID_ARGUMENT, twihs_reset(), twihs_set_speed(), Twihs::TWIHS_SR, and TWIHS_SUCCESS.
Referenced by nm_bus_init().
twihs_master_read()
uint32_t twihs_master_read (Twihs * p_twihs, twihs_packet_t * p_packet)
Read multiple bytes from a TWIHS compatible slave device.
Note
This function will NOT return until all data has been read or error occurs.
Parameters
p_twihs Pointer to a TWIHS instance.
p_packet Packet information and data (see twihs_packet_t).
Returns
TWIHS_SUCCESS if all bytes were read, error code otherwise.
Definition at line 270 of file twihs.c.
{
    uint32_t status, cnt = p_packet->length;
    uint8_t *buffer = p_packet->buffer;
    uint32_t timeout = TWIHS_TIMEOUT;
    /* Check argument */
    if (cnt == 0) {
        return TWIHS_INVALID_ARGUMENT;
    }
    /* Set read mode, slave address and 3 internal address byte lengths */
    p_twihs->TWIHS_MMR = 0;
    p_twihs->TWIHS_MMR = TWIHS_MMR_MREAD | TWIHS_MMR_DADR(p_packet->chip) |
            ((p_packet->addr_length << TWIHS_MMR_IADRSZ_Pos) &
            TWIHS_MMR_IADRSZ_Msk);
    /* Set internal address for remote chip */
    p_twihs->TWIHS_IADR = 0;
    p_twihs->TWIHS_IADR = twihs_mk_addr(p_packet->addr, p_packet->addr_length);
    /* Send a START Condition */
    p_twihs->TWIHS_CR = TWIHS_CR_START;
    while (cnt > 0) {
        status = p_twihs->TWIHS_SR;
        if (status & TWIHS_SR_NACK) {
            return TWIHS_RECEIVE_NACK;
        }
        if (!timeout--) {
            return TWIHS_ERROR_TIMEOUT;
        }
        if (!(status & TWIHS_SR_RXRDY)) {
            continue;
        }
        /* Last byte ? */
        if (cnt == 1) {
            p_twihs->TWIHS_CR = TWIHS_CR_STOP;
        }
        *buffer++ = p_twihs->TWIHS_RHR;
        cnt--;
        timeout = TWIHS_TIMEOUT;
    }
    while (!(p_twihs->TWIHS_SR & TWIHS_SR_TXCOMP)) {
    }
    p_twihs->TWIHS_SR;
    return TWIHS_SUCCESS;
}
References twihs_packet::addr, twihs_packet::addr_length, twihs_packet::buffer, twihs_packet::chip, twihs_packet::length, Twihs::TWIHS_CR, TWIHS_CR_START, TWIHS_CR_STOP, TWIHS_ERROR_TIMEOUT, Twihs::TWIHS_IADR, TWIHS_INVALID_ARGUMENT, twihs_mk_addr(), Twihs::TWIHS_MMR, TWIHS_MMR_DADR, TWIHS_MMR_IADRSZ_Msk, TWIHS_MMR_IADRSZ_Pos, TWIHS_MMR_MREAD, TWIHS_RECEIVE_NACK, Twihs::TWIHS_RHR, Twihs::TWIHS_SR, TWIHS_SR_NACK, TWIHS_SR_RXRDY, TWIHS_SR_TXCOMP, TWIHS_SUCCESS, and TWIHS_TIMEOUT.
Referenced by nm_i2c_read().
twihs_master_write()
uint32_t twihs_master_write (Twihs * p_twihs, twihs_packet_t * p_packet)
Write multiple bytes to a TWIHS compatible slave device.
Note
This function will NOT return until all data has been written or error occurred.
Parameters
p_twihs Pointer to a TWIHS instance.
p_packet Packet information and data (see twihs_packet_t).
Returns
TWIHS_SUCCESS if all bytes were written, error code otherwise.
Definition at line 334 of file twihs.c.
{
    uint32_t status, cnt = p_packet->length;
    uint8_t *buffer = p_packet->buffer;
    /* Check argument */
    if (cnt == 0) {
        return TWIHS_INVALID_ARGUMENT;
    }
    /* Set write mode, slave address and 3 internal address byte lengths */
    p_twihs->TWIHS_MMR = 0;
    p_twihs->TWIHS_MMR = TWIHS_MMR_DADR(p_packet->chip) |
            ((p_packet->addr_length << TWIHS_MMR_IADRSZ_Pos) &
            TWIHS_MMR_IADRSZ_Msk);
    /* Set internal address for remote chip */
    p_twihs->TWIHS_IADR = 0;
    p_twihs->TWIHS_IADR = twihs_mk_addr(p_packet->addr, p_packet->addr_length);
    /* Send all bytes */
    while (cnt > 0) {
        status = p_twihs->TWIHS_SR;
        if (status & TWIHS_SR_NACK) {
            return TWIHS_RECEIVE_NACK;
        }
        if (!(status & TWIHS_SR_TXRDY)) {
            continue;
        }
        p_twihs->TWIHS_THR = *buffer++;
        cnt--;
    }
    while (1) {
        status = p_twihs->TWIHS_SR;
        if (status & TWIHS_SR_NACK) {
            return TWIHS_RECEIVE_NACK;
        }
        if (status & TWIHS_SR_TXRDY) {
            break;
        }
    }
    p_twihs->TWIHS_CR = TWIHS_CR_STOP;
    while (!(p_twihs->TWIHS_SR & TWIHS_SR_TXCOMP)) {
    }
    return TWIHS_SUCCESS;
}
References twihs_packet::addr, twihs_packet::addr_length, twihs_packet::buffer, twihs_packet::chip, twihs_packet::length, Twihs::TWIHS_CR, TWIHS_CR_STOP, Twihs::TWIHS_IADR, TWIHS_INVALID_ARGUMENT, twihs_mk_addr(), Twihs::TWIHS_MMR, TWIHS_MMR_DADR, TWIHS_MMR_IADRSZ_Msk, TWIHS_MMR_IADRSZ_Pos, TWIHS_RECEIVE_NACK, Twihs::TWIHS_SR, TWIHS_SR_NACK, TWIHS_SR_TXCOMP, TWIHS_SR_TXRDY, TWIHS_SUCCESS, and Twihs::TWIHS_THR.
Referenced by nm_i2c_write(), and twihs_probe().
twihs_mk_addr()
static uint32_t twihs_mk_addr (const uint8_t * addr, int len) static
Construct the TWIHS module address register field.
The TWIHS module address register is sent out MSB first. And the size controls which byte is the MSB to start with.
Please see the device datasheet for details on this.
Definition at line 241 of file twihs.c.
{
    uint32_t val;
    if (len == 0)
        return 0;
    val = addr[0];
    if (len > 1) {
        val <<= 8;
        val |= addr[1];
    }
    if (len > 2) {
        val <<= 8;
        val |= addr[2];
    }
    return val;
}
Referenced by twihs_master_read(), and twihs_master_write().
twihs_probe()
uint32_t twihs_probe (Twihs * p_twihs, uint8_t uc_slave_addr)
Test if a chip answers a given I2C address.
Parameters
p_twihs Pointer to a TWIHS instance.
uc_slave_addr Address of the remote chip to search for.
Returns
TWIHS_SUCCESS if a chip was found, error code otherwise.
Definition at line 211 of file twihs.c.
{
    twihs_packet_t packet;
    uint8_t data = 0;
    /* Data to send */
    packet.buffer = &data;
    /* Data length */
    packet.length = 1;
    /* Slave chip address */
    packet.chip = (uint32_t) uc_slave_addr;
    /* Internal chip address */
    packet.addr[0] = 0;
    /* Address length */
    packet.addr_length = 0;
    /* Perform a master write access */
    return (twihs_master_write(p_twihs, &packet));
}
References twihs_packet::addr, twihs_packet::addr_length, twihs_packet::buffer, twihs_packet::chip, twihs_packet::length, and twihs_master_write().
twihs_read_byte()
uint8_t twihs_read_byte (Twihs * p_twihs)
Reads a byte from the TWIHS bus.
Parameters
p_twihs Pointer to a TWIHS instance.
Returns
The byte read.
Definition at line 445 of file twihs.c.
{
    return p_twihs->TWIHS_RHR;
}
References Twihs::TWIHS_RHR.
twihs_read_write_protection_status()
void twihs_read_write_protection_status (Twihs * p_twihs, uint32_t * p_status)
Read the write protection status.
Parameters
p_twihs Pointer to a TWIHS instance.
p_status Pointer to save the status.
Definition at line 639 of file twihs.c.
{
    *p_status = p_twihs->TWIHS_WPSR;
}
References Twihs::TWIHS_WPSR.
twihs_reset()
void twihs_reset (Twihs * p_twihs)
Reset TWIHS.
Parameters
p_twihs Pointer to a TWIHS instance.
Definition at line 589 of file twihs.c.
{
    /* Set SWRST bit to reset TWIHS peripheral */
    p_twihs->TWIHS_CR = TWIHS_CR_SWRST;
    p_twihs->TWIHS_RHR;
}
References Twihs::TWIHS_CR, TWIHS_CR_SWRST, and Twihs::TWIHS_RHR.
Referenced by twihs_master_init(), and twihs_slave_init().
twihs_set_alternative_command()
void twihs_set_alternative_command (Twihs * p_twihs, uint32_t ul_alt_cmd)
Set length/direction/PEC for alternative command mode.
Parameters
p_twihs Base address of the TWIHS instance.
ul_alt_cmd Alternative command parameters.
Definition at line 662 of file twihs.c.
{
    p_twihs->TWIHS_ACR = ul_alt_cmd;;
}
twihs_set_filter()
void twihs_set_filter (Twihs * p_twihs, uint32_t ul_filter)
Set the filter for TWIHS.
Parameters
p_twihs Base address of the TWIHS instance.
ul_filter Filter value.
Definition at line 674 of file twihs.c.
{
    p_twihs->TWIHS_FILTR = ul_filter;;
}
References Twihs::TWIHS_FILTR.
twihs_set_slave_addr()
void twihs_set_slave_addr (Twihs * p_twihs, uint32_t ul_device_addr)
Set TWIHS slave address.
Parameters
p_twihs Pointer to a TWIHS instance.
ul_device_addr Device address of the SAM slave device on the I2C bus.
Definition at line 515 of file twihs.c.
{
    /* Set slave address */
    p_twihs->TWIHS_SMR = TWIHS_SMR_SADR(ul_device_addr);
}
References Twihs::TWIHS_SMR, and TWIHS_SMR_SADR.
twihs_set_speed()
uint32_t twihs_set_speed (Twihs * p_twihs, uint32_t ul_speed, uint32_t ul_mck)
Set the I2C bus speed in conjunction with the clock frequency.
Parameters
p_twihs Pointer to a TWIHS instance.
ul_speed The desired I2C bus speed (in Hz).
ul_mck Main clock of the device (in Hz).
Return values
PASS New speed setting is accepted.
FAIL New speed setting is rejected.
Definition at line 147 of file twihs.c.
{
    uint32_t ckdiv = 0;
    uint32_t c_lh_div;
    uint32_t cldiv, chdiv;
    /* High-Speed can be only used in slave mode, 400k is the max speed allowed for master */
    if (ul_speed > I2C_FAST_MODE_SPEED) {
        return FAIL;
    }
    /* Low level time not less than 1.3us of I2C Fast Mode. */
    if (ul_speed > LOW_LEVEL_TIME_LIMIT) {
        /* Low level of time fixed for 1.3us. */
        cldiv = ul_mck / (LOW_LEVEL_TIME_LIMIT * TWIHS_CLK_DIVIDER) - TWIHS_CLK_CALC_ARGU;
        chdiv = ul_mck / ((ul_speed + (ul_speed - LOW_LEVEL_TIME_LIMIT)) * TWIHS_CLK_DIVIDER) - TWIHS_CLK_CALC_ARGU;
        /* cldiv must fit in 8 bits, ckdiv must fit in 3 bits */
        while ((cldiv > TWIHS_CLK_DIV_MAX) && (ckdiv < TWIHS_CLK_DIV_MIN)) {
            /* Increase clock divider */
            ckdiv++;
            /* Divide cldiv value */
            cldiv /= TWIHS_CLK_DIVIDER;
        }
        /* chdiv must fit in 8 bits, ckdiv must fit in 3 bits */
        while ((chdiv > TWIHS_CLK_DIV_MAX) && (ckdiv < TWIHS_CLK_DIV_MIN)) {
            /* Increase clock divider */
            ckdiv++;
            /* Divide cldiv value */
            chdiv /= TWIHS_CLK_DIVIDER;
        }
        /* set clock waveform generator register */
        p_twihs->TWIHS_CWGR =
                TWIHS_CWGR_CLDIV(cldiv) | TWIHS_CWGR_CHDIV(chdiv) |
                TWIHS_CWGR_CKDIV(ckdiv);
    } else {
        c_lh_div = ul_mck / (ul_speed * TWIHS_CLK_DIVIDER) - TWIHS_CLK_CALC_ARGU;
        /* cldiv must fit in 8 bits, ckdiv must fit in 3 bits */
        while ((c_lh_div > TWIHS_CLK_DIV_MAX) && (ckdiv < TWIHS_CLK_DIV_MIN)) {
            /* Increase clock divider */
            ckdiv++;
            /* Divide cldiv value */
            c_lh_div /= TWIHS_CLK_DIVIDER;
        }
        /* set clock waveform generator register */
        p_twihs->TWIHS_CWGR =
                TWIHS_CWGR_CLDIV(c_lh_div) | TWIHS_CWGR_CHDIV(c_lh_div) |
                TWIHS_CWGR_CKDIV(ckdiv);
    }
    return PASS;
}
References FAIL, I2C_FAST_MODE_SPEED, LOW_LEVEL_TIME_LIMIT, PASS, TWIHS_CLK_CALC_ARGU, TWIHS_CLK_DIV_MAX, TWIHS_CLK_DIV_MIN, TWIHS_CLK_DIVIDER, Twihs::TWIHS_CWGR, TWIHS_CWGR_CHDIV, TWIHS_CWGR_CKDIV, and TWIHS_CWGR_CLDIV.
Referenced by twihs_master_init().
twihs_set_write_protection()
void twihs_set_write_protection (Twihs * p_twihs, bool flag)
Enables/Disables write protection mode.
Parameters
p_twihs Pointer to a TWIHS instance.
flag ture for enable, false for disable.
Definition at line 624 of file twihs.c.
{
    if (flag) {
        p_twihs->TWIHS_WPMR = TWIHS_WPMR_WPKEY_PASSWD | TWIHS_WPMR_WPEN;
    } else {
        p_twihs->TWIHS_WPMR = TWIHS_WPMR_WPKEY_PASSWD;
    }
}
References Twihs::TWIHS_WPMR, TWIHS_WPMR_WPEN, and TWIHS_WPMR_WPKEY_PASSWD.
twihs_slave_init()
void twihs_slave_init (Twihs * p_twihs, uint32_t ul_device_addr)
Initialize TWIHS slave mode.
Parameters
p_twihs Pointer to a TWIHS instance.
ul_device_addr Device address of the SAM slave device on the I2C bus.
Definition at line 493 of file twihs.c.
{
    /* Disable TWIHS interrupts */
    p_twihs->TWIHS_IDR = ~0UL;
    p_twihs->TWIHS_SR;
    /* Reset TWIHS */
    twihs_reset(p_twihs);
    /* Set slave address in slave mode */
    p_twihs->TWIHS_SMR = TWIHS_SMR_SADR(ul_device_addr);
    /* Enable slave mode */
    twihs_enable_slave_mode(p_twihs);
}
References twihs_enable_slave_mode(), Twihs::TWIHS_IDR, twihs_reset(), Twihs::TWIHS_SMR, TWIHS_SMR_SADR, and Twihs::TWIHS_SR.
twihs_slave_read()
uint32_t twihs_slave_read (Twihs * p_twihs, uint8_t * p_data)
Read data from master.
Note
This function will NOT return until master sends a STOP condition.
Parameters
p_twihs Pointer to a TWIHS instance.
p_data Pointer to the data buffer where data received will be stored.
Returns
Number of bytes read.
Definition at line 531 of file twihs.c.
{
    uint32_t status, cnt = 0;
    do {
        status = p_twihs->TWIHS_SR;
        if (status & TWIHS_SR_SVACC) {
            if (!(status & (TWIHS_SR_GACC | TWIHS_SR_SVREAD)) &&
            (status & TWIHS_SR_RXRDY)) {
                *p_data++ = (uint8_t) p_twihs->TWIHS_RHR;
                cnt++;
            }
        } else if ((status & (TWIHS_SR_EOSACC | TWIHS_SR_TXCOMP))
                    == (TWIHS_SR_EOSACC | TWIHS_SR_TXCOMP)) {
            break;
        }
    } while (1);
    return cnt;
}
References Twihs::TWIHS_RHR, Twihs::TWIHS_SR, TWIHS_SR_EOSACC, TWIHS_SR_GACC, TWIHS_SR_RXRDY, TWIHS_SR_SVACC, TWIHS_SR_SVREAD, and TWIHS_SR_TXCOMP.
twihs_slave_write()
uint32_t twihs_slave_write (Twihs * p_twihs, uint8_t * p_data)
Write data to TWIHS bus.
Note
This function will NOT return until master sends a STOP condition.
Parameters
p_twihs Pointer to a TWIHS instance.
p_data Pointer to the data buffer to be sent.
Returns
Number of bytes written.
Definition at line 562 of file twihs.c.
{
    uint32_t status, cnt = 0;
    do {
        status = p_twihs->TWIHS_SR;
        if (status & TWIHS_SR_SVACC) {
            if (!(status & (TWIHS_SR_GACC | TWIHS_SR_NACK)) &&
            ((status & (TWIHS_SR_SVREAD | TWIHS_SR_TXRDY))
            == (TWIHS_SR_SVREAD | TWIHS_SR_TXRDY))) {
                p_twihs->TWIHS_THR = *p_data++;
                cnt++;
            }
        } else if ((status & (TWIHS_SR_EOSACC | TWIHS_SR_TXCOMP))
                    == (TWIHS_SR_EOSACC | TWIHS_SR_TXCOMP)) {
            break;
        }
    } while (1);
    return cnt;
}
References Twihs::TWIHS_SR, TWIHS_SR_EOSACC, TWIHS_SR_GACC, TWIHS_SR_NACK, TWIHS_SR_SVACC, TWIHS_SR_SVREAD, TWIHS_SR_TXCOMP, TWIHS_SR_TXRDY, and Twihs::TWIHS_THR.
twihs_smbus_set_timing()
void twihs_smbus_set_timing (Twihs * p_twihs, uint32_t ul_timing)
Set the prescaler, TLOW:SEXT, TLOW:MEXT and clock high max cycles for SMBUS mode.
Parameters
p_twihs Base address of the TWIHS instance.
ul_timing Parameter for prescaler, TLOW:SEXT, TLOW:MEXT and clock high max cycles.
Definition at line 650 of file twihs.c.
{
    p_twihs->TWIHS_SMBTR = ul_timing;;
}
References Twihs::TWIHS_SMBTR.
twihs_write_byte()
void twihs_write_byte (Twihs * p_twihs, uint8_t uc_byte)
Sends a byte of data to one of the TWIHS slaves on the bus.
Parameters
p_twihs Pointer to a TWIHS instance.
byte The byte to send.
Definition at line 456 of file twihs.c.
{
    p_twihs->TWIHS_THR = uc_byte;
}
References Twihs::TWIHS_THR.