WINC1500 Weather Client Demo for SAME70 Xplained: Common
Common
OTA » Functions
Functions
NMI_API sint8 m2m_ota_abort (void)
Request OTA Abort.
NMI_API sint8 m2m_ota_init (tpfOtaUpdateCb pfOtaUpdateCb, tpfOtaNotifCb pfOtaNotifCb)
Initialize the OTA layer.
Detailed Description
Function Documentation
m2m_ota_abort()
sint8 m2m_ota_abort (void)
Request OTA Abort.
Request the WINC to abort an OTA or Host File download in progress.
If no download is in progress, the API will respond with failure.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
See also
m2m_ota_init m2m_ota_start_update
Returns
The function returns M2M_SUCCESS for a successful operation and a negative value otherwise.
Definition at line 271 of file m2m_ota.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = hif_send(M2M_REQ_GROUP_OTA,M2M_OTA_REQ_ABORT,NULL,0,NULL,0,0);
    return ret;
}
References hif_send(), M2M_OTA_REQ_ABORT, M2M_REQ_GROUP_OTA, M2M_SUCCESS, and NULL.
m2m_ota_init()
sint8 m2m_ota_init (tpfOtaUpdateCb pfOtaUpdateCb, tpfOtaNotifCb pfOtaNotifCb)
Initialize the OTA layer.
Synchronous initialization function for the OTA layer by registering the update callback.
The notification callback is not supported at the current version. Calling this API is a MUST for all the OTA API's.
Parameters
[in] pfOtaUpdateCb OTA Update callback function.
[in] pfOtaNotifCb OTA Notify callback function.
Returns
The function returns M2M_SUCCESS for success and a negative value otherwise.
Parameters
[in] pfOtaUpdateCb OTA Update callback function.
[in] pfOtaNotifCb OTA Notify callback function.
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 171 of file m2m_ota.c.
{
    sint8 ret = M2M_SUCCESS;
    if(pfOtaUpdateCb){
        gpfOtaUpdateCb = pfOtaUpdateCb;
    }else{
        M2M_ERR("Invalid Ota update cb\n");
    }
    if(pfOtaNotifCb){
        gpfOtaNotifCb = pfOtaNotifCb;
    }else{
        M2M_ERR("Invalid Ota notify cb\n");
    }
    hif_register_cb(M2M_REQ_GROUP_OTA,m2m_ota_cb);
    ret = hif_send(M2M_REQ_GROUP_OTA, M2M_OTA_REQ_HOST_FILE_STATUS, NULL, 0, NULL, 0, 0);
    return ret;
}
References gpfOtaNotifCb, gpfOtaUpdateCb, hif_register_cb(), hif_send(), M2M_ERR, m2m_ota_cb(), M2M_OTA_REQ_HOST_FILE_STATUS, M2M_REQ_GROUP_OTA, M2M_SUCCESS, and NULL.