WINC1500 Weather Client Demo for SAME70 Xplained: Initialization
Initialization
WLAN » Functions
Here are listed all the functions that implement the Wlan Initialization APIs.
Functions
sint8 m2m_wifi_deinit (void *arg)
De-initialize the WINC driver and host interface.
sint8 m2m_wifi_download_mode ()
Prepares the WINC board before downloading any data (Firmware, Certificates, etc).
uint8 m2m_wifi_get_state (void)
Get the wifi state.
sint8 m2m_wifi_init (tstrWifiInitParam *pWifiInitParam)
Synchronous API to initialize the WINC driver.
sint8 m2m_wifi_init_hold ()
First part of m2m_wifi_init, up to the point of initializing SPI for flash access.
sint8 m2m_wifi_init_start (tstrWifiInitParam *pWifiInitParam)
Second part of m2m_wifi_init, continuing from where m2m_wifi_init_hold left off.
sint8 m2m_wifi_reinit (tstrWifiInitParam *pWifiInitParam)
De-initialize and then initialize wifi. Resets the WINC.
sint8 m2m_wifi_reinit_hold (void)
First part of m2m_wifi_reinit, up to the point of initializing SPI for flash access.
sint8 m2m_wifi_reinit_start (tstrWifiInitParam *pWifiInitParam)
Second part of m2m_wifi_reinit, continuing from where m2m_wifi_reinit_hold left off.
Detailed Description
Here are listed all the functions that implement the Wlan Initialization APIs.
Function Documentation
m2m_wifi_deinit()
NMI_API sint8 m2m_wifi_deinit (void * arg)
De-initialize the WINC driver and host interface.
Synchronous de-initialization function for the WINC driver. De-initializes the host interface and frees any resources used by the M2M_WIFI layer. This function must be called in the application closing phase to ensure that all resources have been correctly released. No arguments are expected to be passed in.
Parameters
[in] arg Opaque argument, not used in current implementation. Application should use null.
Returns
The function returns M2M_SUCCESS if the command has been successfully queued to the WINC, and a negative value otherwise.
Note
This function must be called at the de-initialization stage of the application. Generally this function should be the last function before switching off the chip and it should be followed only by nm_bsp_deinit function call. Every function call of m2m_wifi_init should be matched with a call to m2m_wifi_deinit.
See also
nm_bsp_deinit m2m_wifi_init m2m_wifi_init_hold m2m_wifi_download_mode
Definition at line 525 of file m2m_wifi.c.
{
    gu8WifiState = WIFI_STATE_DEINIT;
    hif_deinit(NULL);
    nm_drv_deinit(NULL);
    return M2M_SUCCESS;
}
References gu8WifiState, hif_deinit(), M2M_SUCCESS, nm_drv_deinit(), NULL, and WIFI_STATE_DEINIT.
Referenced by m2m_wifi_reinit_hold().
m2m_wifi_download_mode()
NMI_API void m2m_wifi_download_mode (void)
Prepares the WINC board before downloading any data (Firmware, Certificates, etc).
This function should be called before attempting to download any data to the WINC board. Performs the appropriate WINC driver initialization, this includes bus initialization, interrupt enabling and it halts the chip to allow for the firmware downloads. Firmware can be downloaded through a number of interfaces, UART, I2C and SPI.
Precondition
Prior to call m2m_wifi_download_mode, the Application should ensure that the wifi is not initialized. This can be done by calling m2m_wifi_get_state and in case the wifi state differs from WIFI_STATE_DEINIT, a m2m_wifi_deinit needs to be issued.
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Definition at line 295 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    /* Apply device specific initialization. */
    ret = nm_drv_init_download_mode();
    if(ret != M2M_SUCCESS)  goto _EXIT0;
    enable_interrupts();
    gu8WifiState = WIFI_STATE_INIT;
_EXIT0:
    return ret;
}
References enable_interrupts(), gu8WifiState, M2M_SUCCESS, nm_drv_init_download_mode(), and WIFI_STATE_INIT.
m2m_wifi_get_state()
NMI_API uint8 m2m_wifi_get_state (void)
Get the wifi state.
Returns
The function returns the current wifi state (see tenuWifiState for the possible states).
Note
Check the WINC state. See tenuWifiState for possible states.
WIFI_STATE_INIT state represents WINC initialized but not started, this is a suitable state for safe flash access.
See also
m2m_wifi_init m2m_wifi_download_mode
Definition at line 2042 of file m2m_wifi.c.
{
    return gu8WifiState;
}
References gu8WifiState.
Referenced by m2m_ota_host_file_read_spi().
m2m_wifi_init()
NMI_API sint8 m2m_wifi_init (tstrWifiInitParam * pWifiInitParam)
Synchronous API to initialize the WINC driver.
This function initializes the WINC driver by registering the callback function for the M2M_WIFI layer (also the callback function for bypass mode/monitoring mode if defined), initializing the host interface layer and the bus interfaces. Wi-Fi callback registering is essential to allow the handling of the events received, in response to the asynchronous Wi-Fi operations.
The possible Wi-Fi events that are expected to be received through the callback function (provided by the application) to the M2M_WIFI layer are listed below:
M2M_WIFI_RESP_CON_STATE_CHANGED
M2M_WIFI_RESP_CONN_INFO
M2M_WIFI_REQ_DHCP_CONF
M2M_WIFI_REQ_WPS
M2M_WIFI_RESP_IP_CONFLICT
M2M_WIFI_RESP_SCAN_DONE
M2M_WIFI_RESP_SCAN_RESULT
M2M_WIFI_RESP_CURRENT_RSSI
M2M_WIFI_RESP_CLIENT_INFO
M2M_WIFI_RESP_PROVISION_INFO
M2M_WIFI_RESP_DEFAULT_CONNECT
M2M_WIFI_RESP_ETHERNET_RX_PACKET (if bypass mode is enabled)
M2M_WIFI_RESP_WIFI_RX_PACKET (if monitoring mode is enabled)
Any application using the WINC driver must call this function at the start of its main function.
Parameters
[in] pWifiInitParam This is a pointer to a structure of type tstrWifiInitParam which contains pointers to the application WIFI layer callback function, monitoring mode callback and tstrEthInitParam structure (which contains initialization settings for bypass mode).
Returns
The function returns M2M_SUCCESS for successful operations and a negative value otherwise.
Precondition
Prior to this function call, The application should initialize the BSP using nm_bsp_init. Also, application users must provide a call back function responsible for receiving all the wi-fi events that are received on the M2M_WIFI layer.
Warning
Failure to successfully complete indicates that the driver could not be initialized and a fatal error will prevent the application from proceeding, proper error handling should be implemented by the application.
See also
m2m_wifi_deinit m2m_wifi_init_hold m2m_wifi_init_start tstrWifiInitParam tenuM2mStaCmd tenuM2mStaCmd
Definition at line 513 of file m2m_wifi.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = m2m_wifi_init_hold();
    if (ret == M2M_SUCCESS)
{
        ret = m2m_wifi_init_start(pWifiInitParam);
    }
    return ret;
}
References M2M_SUCCESS, m2m_wifi_init_hold(), and m2m_wifi_init_start().
Referenced by wifi_init().
m2m_wifi_init_hold()
NMI_API sint8 m2m_wifi_init_hold (void)
First part of m2m_wifi_init, up to the point of initializing SPI for flash access.
See also
m2m_wifi_init m2m_wifi_init_start
Definition at line 443 of file m2m_wifi.c.
{
    sint8 ret = M2M_ERR_FAIL;
    /* Apply device specific initialization. */
    ret = nm_drv_init_hold();
    if(M2M_SUCCESS == ret) {
        gu8WifiState = WIFI_STATE_INIT;
    }
    return ret;
}
References gu8WifiState, M2M_ERR_FAIL, M2M_SUCCESS, nm_drv_init_hold(), and WIFI_STATE_INIT.
Referenced by m2m_wifi_init(), and m2m_wifi_reinit_hold().
m2m_wifi_init_start()
NMI_API sint8 m2m_wifi_init_start (tstrWifiInitParam * pWifiInitParam)
Second part of m2m_wifi_init, continuing from where m2m_wifi_init_hold left off.
Parameters
[in] pWifiInitParam This is a pointer to a variable of type tstrWifiInitParam which contains pointers to the application WIFI layer callback function (see tpfAppWifiCb), monitoring mode callback (see tpfAppEthCb) and tstrEthInitParam structure (which contains initialization settings for bypass mode).
See also
m2m_wifi_init tstrWifiInitParam
Definition at line 457 of file m2m_wifi.c.
{
    tstrM2mRev strtmp;
    sint8 ret = M2M_SUCCESS;
    uint8 u8WifiMode = M2M_WIFI_MODE_NORMAL;
    if(pWifiInitParam == NULL) {
        ret = M2M_ERR_FAIL;
        goto _EXIT0;
    }
    gpfAppWifiCb = pWifiInitParam->pfAppWifiCb;
#ifdef ETH_MODE
    gpfAppEthCb       = pWifiInitParam->strEthInitParam.pfAppEthCb;
    gau8ethRcvBuf     = pWifiInitParam->strEthInitParam.au8ethRcvBuf;
    gu16ethRcvBufSize = pWifiInitParam->strEthInitParam.u16ethRcvBufSize;
    if (pWifiInitParam->strEthInitParam.u8EthernetEnable)
        u8WifiMode = M2M_WIFI_MODE_ETHERNET;
#endif /* ETH_MODE */
    gu8scanInProgress = 0;
    /* Apply device specific initialization. */
    ret = nm_drv_init_start(&u8WifiMode);
    if(ret != M2M_SUCCESS)  goto _EXIT0;
    gu8WifiState = WIFI_STATE_START;
    /* Initialize host interface module */
    ret = hif_init(NULL);
    if(ret != M2M_SUCCESS)  goto _EXIT1;
    hif_register_cb(M2M_REQ_GROUP_WIFI,m2m_wifi_cb);
    ret = nm_get_firmware_full_info(&strtmp);
    M2M_INFO("Firmware ver   : %u.%u.%u Svnrev %u\n", strtmp.u8FirmwareMajor, strtmp.u8FirmwareMinor, strtmp.u8FirmwarePatch,strtmp.u16FirmwareSvnNum);
    M2M_INFO("Firmware Build %s Time %s\n",strtmp.BuildDate,strtmp.BuildTime);
    M2M_INFO("Firmware Min driver ver : %u.%u.%u\n", strtmp.u8DriverMajor, strtmp.u8DriverMinor, strtmp.u8DriverPatch);
    M2M_INFO("Driver ver: %u.%u.%u \n", M2M_RELEASE_VERSION_MAJOR_NO, M2M_RELEASE_VERSION_MINOR_NO, M2M_RELEASE_VERSION_PATCH_NO);
    M2M_INFO("Driver built at %s\t%s\n",__DATE__,__TIME__);
    if(M2M_ERR_FW_VER_MISMATCH == ret)
    {
        M2M_ERR("Mismatch Firmware Version\n");
    }
    goto _EXIT0;
_EXIT1:
    gu8WifiState = WIFI_STATE_DEINIT;
    nm_drv_deinit(NULL);
_EXIT0:
    return ret;
}
References tstrEthInitParam::au8ethRcvBuf, tstrM2mRev::BuildDate, tstrM2mRev::BuildTime, gpfAppWifiCb, gu8scanInProgress, gu8WifiState, hif_init(), hif_register_cb(), M2M_ERR, M2M_ERR_FAIL, M2M_ERR_FW_VER_MISMATCH, M2M_INFO, M2M_RELEASE_VERSION_MAJOR_NO, M2M_RELEASE_VERSION_MINOR_NO, M2M_RELEASE_VERSION_PATCH_NO, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, m2m_wifi_cb(), M2M_WIFI_MODE_ETHERNET, M2M_WIFI_MODE_NORMAL, nm_drv_deinit(), nm_drv_init_start(), nm_get_firmware_full_info(), NULL, tstrEthInitParam::pfAppEthCb, tstrWifiInitParam::pfAppWifiCb, tstrWifiInitParam::strEthInitParam, tstrEthInitParam::u16ethRcvBufSize, tstrM2mRev::u16FirmwareSvnNum, tstrM2mRev::u8DriverMajor, tstrM2mRev::u8DriverMinor, tstrM2mRev::u8DriverPatch, tstrEthInitParam::u8EthernetEnable, tstrM2mRev::u8FirmwareMajor, tstrM2mRev::u8FirmwareMinor, tstrM2mRev::u8FirmwarePatch, WIFI_STATE_DEINIT, and WIFI_STATE_START.
Referenced by m2m_wifi_init(), and m2m_wifi_reinit_start().
m2m_wifi_reinit()
NMI_API sint8 m2m_wifi_reinit (tstrWifiInitParam * pWifiInitParam)
De-initialize and then initialize wifi. Resets the WINC.
Parameters
[in] pWifiInitParam This is a pointer to a variable of type tstrWifiInitParam which contains pointers to the application WIFI layer callback function (see tpfAppWifiCb), monitoring mode callback (see tpfAppEthCb) and tstrEthInitParam structure (which contains initialization settings for bypass mode).
Note
m2m_wifi_reinit wraps a call to m2m_wifi_deinit and to m2m_wifi_init.
See also
m2m_wifi_deinit m2m_wifi_init tstrWifiInitParam
Definition at line 2022 of file m2m_wifi.c.
{
    sint8 ret = m2m_wifi_reinit_hold();
    if(M2M_SUCCESS == ret)
        ret = m2m_wifi_reinit_start(pWifiInitParam);
    return ret;
}
References M2M_SUCCESS, m2m_wifi_reinit_hold(), and m2m_wifi_reinit_start().
m2m_wifi_reinit_hold()
NMI_API sint8 m2m_wifi_reinit_hold (void)
First part of m2m_wifi_reinit, up to the point of initializing SPI for flash access.
Note
m2m_wifi_reinit_hold wraps a call to m2m_wifi_deinit and to m2m_wifi_init_hold.
See also
m2m_wifi_deinit m2m_wifi_reinit m2m_wifi_init_hold
Definition at line 2031 of file m2m_wifi.c.
{
    m2m_wifi_deinit(NULL);
    return m2m_wifi_init_hold();
}
References m2m_wifi_deinit(), m2m_wifi_init_hold(), and NULL.
Referenced by m2m_wifi_reinit().
m2m_wifi_reinit_start()
NMI_API sint8 m2m_wifi_reinit_start (tstrWifiInitParam * pWifiInitParam)
Second part of m2m_wifi_reinit, continuing from where m2m_wifi_reinit_hold left off.
Parameters
[in] pWifiInitParam This is a pointer to the tstrWifiInitParam structure which contains pointers to the application WIFI layer callback function (see tpfAppWifiCb), monitoring mode callback (see tpfAppEthCb) and tstrEthInitParam structure (which contains initialization settings for bypass mode).
See also
m2m_wifi_reinit m2m_wifi_init_start tstrWifiInitParam
Definition at line 2037 of file m2m_wifi.c.
{
    return m2m_wifi_init_start(pWifiInitParam);
}
References m2m_wifi_init_start().
Referenced by m2m_wifi_reinit().