WINC1500 Weather Client Demo for SAME70 Xplained: Wlan Events
Wlan Events
WLAN » Functions
Here are listed all the functions that implement the Wlan Events APIs.
Functions
sint8 m2m_wifi_handle_events (void *arg)
Synchronous M2M event handler function.
void m2m_wifi_yield (void)
Yield from processing more synchronous M2M events.
Detailed Description
Here are listed all the functions that implement the Wlan Events APIs.
Function Documentation
m2m_wifi_handle_events()
NMI_API sint8 m2m_wifi_handle_events (void * arg)
Synchronous M2M event handler function.
This function is responsible for handling interrupts received from the WINC firmware. Applications should call this function periodically in-order to receive the events that are to be handled by the callback functions implemented by the application.
Handle the various events received from the WINC board. Whenever an event happens in the WINC board (e.g. Connection, Disconnection, DHCP, etc), the WINC will interrupt the host to let it know that a new event has occurred. The host driver will attempt to handle these events whenever the application decides to do so by calling the m2m_wifi_handle_events function. It is mandatory to call this function periodically and independently of any other condition. It is ideal to include this function in the main and the most frequent loop of the host application.
Precondition
Prior to receiving events, the WINC driver should have been successfully initialized by calling the m2m_wifi_init function.
Warning
Failure to successfully complete this function indicates bus errors and hence a fatal error that will prevent the application from proceeding.
Returns
The function returns M2M_SUCCESS for successful interrupt handling and a negative value otherwise.
Definition at line 540 of file m2m_wifi.c.
{
    return hif_handle_isr();
}
References hif_handle_isr().
Referenced by wifi_handle_events().
m2m_wifi_yield()
NMI_API void m2m_wifi_yield (void)
Yield from processing more synchronous M2M events.
This function causes the synchronous M2M event handler function to yield from processing further events and return control to the caller.
Precondition
Prior to receiving Wi-Fi interrupts, the WINC driver should have been successfully initialized by calling the m2m_wifi_init function.
Warning
Failure to successfully complete this function indicates bus errors and hence a fatal error that will prevent the application from proceeding.
Definition at line 535 of file m2m_wifi.c.
{
    hif_yield();
}
References hif_yield().