WINC1500 Weather Client Demo for SAME70 Xplained: socketInit
socketInit
Socket » Functions
The function performs the necessary initializations for the socket library through the following steps:
Functions
NMI_API void socketInit (void)
Detailed Description
The function performs the necessary initializations for the socket library through the following steps:
A check made by the global variable gbSocketInit, ensuring that initialization for sockets is performed only once, in-order to prevent resetting the socket instances already created in the global socket array (gastrSockets).
Zero initializations to the global socket array (gastrSockets), which holds the list of TCP sockets.
Registers the socket (Host Interface)hif callback function through the call to the hif_register_cb function. This facilitates handling all of the socket related functions received through interrupts from the firmware.
Function Documentation
socketInit()
NMI_API void socketInit (void)
Returns
void
Remarks
This initialization function must be invoked before any socket operation is performed. No error codes from this initialization function since the socket array is statically allocated based in the maximum number of sockets MAX_SOCKET based on the systems capability.
Example
This example demonstrates the use of the socketinit for socket initialization for an mqtt chat application.
tstrWifiInitParam param;
tstrNetworkId       strNetworkId;
tstrAuthPsk         strAuthPsk;
int8_t ret;
char topic[strlen(MAIN_CHAT_TOPIC) + MAIN_CHAT_USER_NAME_SIZE + 1];
//Initialize the board.
system_init();
//Initialize the UART console.
configure_console();
// Initialize the BSP.
nm_bsp_init();
 ----------
// Initialize socket interface.
socketInit();
registerSocketCallback(socket_event_handler, socket_resolve_handler);
// Connect to router.
strNetworkId.pu8Bssid = NULL;
strNetworkId.pu8Ssid = MAIN_WLAN_SSID;
strNetworkId.u8SsidLen = sizeof(MAIN_WLAN_SSID);
strNetworkId.u8Channel = M2M_WIFI_CH_ALL;
strAuthPsk.pu8Psk = NULL;
strAuthPsk.pu8Passphrase = MAIN_WLAN_PSK;
strAuthPsk.u8PassphraseLen = (uint8)strlen((char*)MAIN_WLAN_PSK);
m2m_wifi_connect_psk(WIFI_CRED_SAVE_ENCRYPTED, &strNetworkId, &strAuthPsk);
Definition at line 457 of file socket.c.
{
    if(gbSocketInit == 0)
    {
        m2m_memset((uint8*)gastrSockets, 0, MAX_SOCKET * sizeof(tstrSocket));
        hif_register_cb(M2M_REQ_GROUP_IP,m2m_ip_cb);
        gbSocketInit    = 1;
        gu16SessionID   = 0;
    }
}
References gastrSockets, gbSocketInit, gu16SessionID, hif_register_cb(), m2m_ip_cb(), m2m_memset(), M2M_REQ_GROUP_IP, and MAX_SOCKET.
Referenced by wifi_init().