WINC1500 Weather Client Demo for SAME70 Xplained: Universal Asynchronous Receiver Transceiver (UART)
Universal Asynchronous Receiver Transceiver (UART)
The Universal Asynchronous Receiver Transmitter features a two-pin UART that can be used for communication and trace purposes and offers an ideal medium for in-situ programming solutions.
Functions
void uart_disable (Uart *p_uart)
Disable UART receiver and transmitter.
void uart_disable_interrupt (Uart *p_uart, uint32_t ul_sources)
Disable UART interrupts.
void uart_disable_rx (Uart *p_uart)
Disable UART receiver.
void uart_disable_tx (Uart *p_uart)
Disable UART transmitter.
void uart_enable (Uart *p_uart)
Enable UART receiver and transmitter.
void uart_enable_interrupt (Uart *p_uart, uint32_t ul_sources)
Enable UART interrupts.
void uart_enable_rx (Uart *p_uart)
Enable UART receiver.
void uart_enable_tx (Uart *p_uart)
Enable UART transmitter.
uint32_t uart_get_interrupt_mask (Uart *p_uart)
Read UART interrupt mask.
Pdc * uart_get_pdc_base (Uart *p_uart)
Get UART PDC base address.
uint32_t uart_get_status (Uart *p_uart)
Get current status.
uint32_t uart_init (Uart *p_uart, const sam_uart_opt_t *p_uart_opt)
Configure UART with the specified parameters.
uint32_t uart_is_rx_buf_end (Uart *p_uart)
Check if one receive buffer is filled.
uint32_t uart_is_rx_buf_full (Uart *p_uart)
Check if both receive buffers are full.
uint32_t uart_is_rx_ready (Uart *p_uart)
Check if Received data is ready.
uint32_t uart_is_tx_buf_empty (Uart *p_uart)
Check if both transmit buffers are sent out.
uint32_t uart_is_tx_buf_end (Uart *p_uart)
Check if one transmit buffer is sent out.
uint32_t uart_is_tx_empty (Uart *p_uart)
Check if Transmit Hold Register is empty.
uint32_t uart_is_tx_ready (Uart *p_uart)
Check if Transmit is Ready.
uint32_t uart_read (Uart *p_uart, uint8_t *puc_data)
Read from UART Receive Holding Register.
void uart_reset (Uart *p_uart)
Reset UART receiver and transmitter.
void uart_reset_rx (Uart *p_uart)
Reset UART receiver.
void uart_reset_status (Uart *p_uart)
Reset status bits.
void uart_reset_tx (Uart *p_uart)
Reset UART transmitter.
void uart_set_clock_divisor (Uart *p_uart, uint16_t us_divisor)
Set UART clock divisor value.
uint32_t uart_write (Uart *p_uart, const uint8_t uc_data)
Write to UART Transmit Holding Register Before writing user should check if tx is ready (or empty).
Detailed Description
The Universal Asynchronous Receiver Transmitter features a two-pin UART that can be used for communication and trace purposes and offers an ideal medium for in-situ programming solutions.
Moreover, the association with two peripheral DMA controller (PDC) channels permits packet handling for these tasks with processor time reduced to a minimum.
Usage
Enable the UART peripheral clock in the PMC.
Enable the required UART PIOs (see pio.h).
Configure the UART by calling uart_init.
Send data through the UART using the uart_write.
Receive data from the UART using the uart_read; the availability of data can be polled with uart_is_rx_ready.
Disable the transmitter and/or the receiver of the UART with uart_disable_tx and uart_disable_rx.
Function Documentation
uart_disable()
void uart_disable (Uart * p_uart)
Disable UART receiver and transmitter.
Parameters
p_uart Pointer to a UART instance.
Definition at line 192 of file uart.c.
{
    /* Disable receiver and transmitter */
    p_uart->UART_CR = UART_CR_RXDIS | UART_CR_TXDIS;
}
References Uart::UART_CR, UART_CR_RXDIS, and UART_CR_TXDIS.
uart_disable_interrupt()
void uart_disable_interrupt (Uart * p_uart, uint32_t ul_sources)
Disable UART interrupts.
Parameters
p_uart Pointer to a UART instance.
ul_sources Interrupts to be disabled.
Definition at line 225 of file uart.c.
{
    p_uart->UART_IDR = ul_sources;
}
References Uart::UART_IDR.
uart_disable_rx()
void uart_disable_rx (Uart * p_uart)
Disable UART receiver.
Parameters
p_uart Pointer to a UART instance.
Definition at line 159 of file uart.c.
{
    /* Disable receiver */
    p_uart->UART_CR = UART_CR_RXDIS;
}
References Uart::UART_CR, and UART_CR_RXDIS.
uart_disable_tx()
void uart_disable_tx (Uart * p_uart)
Disable UART transmitter.
Parameters
p_uart Pointer to a UART instance.
Definition at line 126 of file uart.c.
{
    /* Disable transmitter */
    p_uart->UART_CR = UART_CR_TXDIS;
}
References Uart::UART_CR, and UART_CR_TXDIS.
uart_enable()
void uart_enable (Uart * p_uart)
Enable UART receiver and transmitter.
Parameters
p_uart Pointer to a UART instance.
Definition at line 181 of file uart.c.
{
    /* Enable receiver and transmitter */
    p_uart->UART_CR = UART_CR_RXEN | UART_CR_TXEN;
}
References Uart::UART_CR, UART_CR_RXEN, and UART_CR_TXEN.
uart_enable_interrupt()
void uart_enable_interrupt (Uart * p_uart, uint32_t ul_sources)
Enable UART interrupts.
Parameters
p_uart Pointer to a UART instance.
ul_sources Interrupts to be enabled.
Definition at line 215 of file uart.c.
{
    p_uart->UART_IER = ul_sources;
}
References Uart::UART_IER.
uart_enable_rx()
void uart_enable_rx (Uart * p_uart)
Enable UART receiver.
Parameters
p_uart Pointer to a UART instance.
Definition at line 148 of file uart.c.
{
    /* Enable receiver */
    p_uart->UART_CR = UART_CR_RXEN;
}
References Uart::UART_CR, and UART_CR_RXEN.
uart_enable_tx()
void uart_enable_tx (Uart * p_uart)
Enable UART transmitter.
Parameters
p_uart Pointer to a UART instance.
Definition at line 115 of file uart.c.
{
    /* Enable transmitter */
    p_uart->UART_CR = UART_CR_TXEN;
}
References Uart::UART_CR, and UART_CR_TXEN.
uart_get_interrupt_mask()
uint32_t uart_get_interrupt_mask (Uart * p_uart)
Read UART interrupt mask.
Parameters
p_uart Pointer to a UART instance.
Returns
The interrupt mask value.
Definition at line 236 of file uart.c.
{
    return p_uart->UART_IMR;
}
References Uart::UART_IMR.
uart_get_pdc_base()
Pdc * uart_get_pdc_base (Uart * p_uart)
Get UART PDC base address.
Parameters
p_uart Pointer to a UART instance.
Returns
UART PDC registers base for PDC driver to access.
Definition at line 420 of file uart.c.
{
    Pdc *p_pdc_base;
#if (SAM3S || SAM3N || SAM4S || SAM4E || SAM4N || SAM4C || SAMG || SAM4CP || SAM4CM)
    if (p_uart == UART0)
        p_pdc_base = PDC_UART0;
#elif (SAM3XA || SAM3U)
    if (p_uart == UART)
        p_pdc_base = PDC_UART;
#else
#error "Unsupported device"
#endif
#if (SAM3S || SAM4S || SAM4E || SAM4N || SAM4C || SAMG || SAM4CP || SAM4CM)
    if (p_uart == UART1)
        p_pdc_base = PDC_UART1;
#endif
#if (SAM4N)
    if (p_uart == UART2)
        p_pdc_base = PDC_UART2;
#endif
    return p_pdc_base;
}
References UART0, UART1, and UART2.
uart_get_status()
uint32_t uart_get_status (Uart * p_uart)
Get current status.
Parameters
p_uart Pointer to a UART instance.
Returns
The current UART status.
Definition at line 248 of file uart.c.
{
    return p_uart->UART_SR;
}
References Uart::UART_SR.
uart_init()
uint32_t uart_init (Uart * p_uart, const sam_uart_opt_t * p_uart_opt)
Configure UART with the specified parameters.
Note
The PMC and PIOs must be configured first.
Parameters
p_uart Pointer to a UART instance.
p_uart_opt Pointer to sam_uart_opt_t instance.
Return values
0 Success.
1 Bad baud rate generator value.
Definition at line 81 of file uart.c.
{
    uint32_t cd = 0;
    /* Reset and disable receiver & transmitter */
    p_uart->UART_CR = UART_CR_RSTRX | UART_CR_RSTTX
            | UART_CR_RXDIS | UART_CR_TXDIS;
    /* Check and configure baudrate */
    /* Asynchronous, no oversampling */
    cd = (p_uart_opt->ul_mck / p_uart_opt->ul_baudrate) / UART_MCK_DIV;
    if (cd < UART_MCK_DIV_MIN_FACTOR || cd > UART_MCK_DIV_MAX_FACTOR)
        return 1;
    p_uart->UART_BRGR = cd;
    /* Configure mode */
    p_uart->UART_MR = p_uart_opt->ul_mode;
#if (!SAMV71 && !SAMV70 && !SAME70 && !SAMS70)
    /* Disable PDC channel */
    p_uart->UART_PTCR = UART_PTCR_RXTDIS | UART_PTCR_TXTDIS;
#endif
    /* Enable receiver and transmitter */
    p_uart->UART_CR = UART_CR_RXEN | UART_CR_TXEN;
    return 0;
}
References Uart::UART_BRGR, Uart::UART_CR, UART_CR_RSTRX, UART_CR_RSTTX, UART_CR_RXDIS, UART_CR_RXEN, UART_CR_TXDIS, UART_CR_TXEN, UART_MCK_DIV, UART_MCK_DIV_MAX_FACTOR, Uart::UART_MR, sam_uart_opt::ul_baudrate, sam_uart_opt::ul_mck, and sam_uart_opt::ul_mode.
Referenced by usart_serial_init().
uart_is_rx_buf_end()
uint32_t uart_is_rx_buf_end (Uart * p_uart)
Check if one receive buffer is filled.
Parameters
p_uart Pointer to a UART instance.
Return values
1 Receive is completed.
0 Receive is still pending.
Definition at line 382 of file uart.c.
{
    return (p_uart->UART_SR & UART_SR_ENDRX) > 0;
}
References Uart::UART_SR.
uart_is_rx_buf_full()
uint32_t uart_is_rx_buf_full (Uart * p_uart)
Check if both receive buffers are full.
Parameters
p_uart Pointer to a UART instance.
Return values
1 Receive buffers are full.
0 Receive buffers are not full.
Definition at line 408 of file uart.c.
{
    return (p_uart->UART_SR & UART_SR_RXBUFF) > 0;
}
References Uart::UART_SR.
uart_is_rx_ready()
uint32_t uart_is_rx_ready (Uart * p_uart)
Check if Received data is ready.
Check if data has been received and loaded in UART_RHR.
Parameters
p_uart Pointer to a UART instance.
Return values
1 One data has been received.
0 No data has been received.
Definition at line 302 of file uart.c.
{
    return (p_uart->UART_SR & UART_SR_RXRDY) > 0;
}
References Uart::UART_SR, and UART_SR_RXRDY.
Referenced by usart_serial_is_rx_ready().
uart_is_tx_buf_empty()
uint32_t uart_is_tx_buf_empty (Uart * p_uart)
Check if both transmit buffers are sent out.
Parameters
p_uart Pointer to a UART instance.
Return values
1 Transmit buffer is empty.
0 Transmit buffer is not empty.
Definition at line 315 of file uart.c.
{
    return (p_uart->UART_SR & UART_SR_TXEMPTY) > 0;
}
References Uart::UART_SR, and UART_SR_TXEMPTY.
uart_is_tx_buf_end()
uint32_t uart_is_tx_buf_end (Uart * p_uart)
Check if one transmit buffer is sent out.
Parameters
p_uart Pointer to a UART instance.
Return values
1 Transmit is completed.
0 Transmit is still pending.
Definition at line 395 of file uart.c.
{
    return (p_uart->UART_SR & UART_SR_ENDTX) > 0;
}
References Uart::UART_SR.
uart_is_tx_empty()
uint32_t uart_is_tx_empty (Uart * p_uart)
Check if Transmit Hold Register is empty.
Check if the last data written in UART_THR has been loaded in TSR and the last data loaded in TSR has been transmitted.
Parameters
p_uart Pointer to a UART instance.
Return values
1 Transmitter is empty.
0 Transmitter is not empty.
Definition at line 288 of file uart.c.
{
    return (p_uart->UART_SR & UART_SR_TXEMPTY) > 0;
}
References Uart::UART_SR, and UART_SR_TXEMPTY.
uart_is_tx_ready()
uint32_t uart_is_tx_ready (Uart * p_uart)
Check if Transmit is Ready.
Check if data has been loaded in UART_THR and is waiting to be loaded in the Transmit Shift Register (TSR).
Parameters
p_uart Pointer to a UART instance.
Return values
1 Data has been transmitted.
0 Transmit is not ready, data pending.
Definition at line 273 of file uart.c.
{
    return (p_uart->UART_SR & UART_SR_TXRDY) > 0;
}
References Uart::UART_SR, and UART_SR_TXRDY.
uart_read()
uint32_t uart_read (Uart * p_uart, uint8_t * puc_data)
Read from UART Receive Holding Register.
Before reading user should check if rx is ready.
Parameters
p_uart Pointer to a UART instance.
Return values
0 Success.
1 I/O Failure, UART is not ready.
Definition at line 362 of file uart.c.
{
    /* Check if the receiver is ready */
    if ((p_uart->UART_SR & UART_SR_RXRDY) == 0)
        return 1;
    /* Read character */
    *puc_data = (uint8_t) p_uart->UART_RHR;
    return 0;
}
References Uart::UART_RHR, Uart::UART_SR, and UART_SR_RXRDY.
Referenced by usart_serial_getchar().
uart_reset()
void uart_reset (Uart * p_uart)
Reset UART receiver and transmitter.
Parameters
p_uart Pointer to a UART instance.
Definition at line 203 of file uart.c.
{
    /* Reset and disable receiver & transmitter */
    p_uart->UART_CR = UART_CR_RSTRX | UART_CR_RSTTX
            | UART_CR_RXDIS | UART_CR_TXDIS;
}
References Uart::UART_CR, UART_CR_RSTRX, UART_CR_RSTTX, UART_CR_RXDIS, and UART_CR_TXDIS.
uart_reset_rx()
void uart_reset_rx (Uart * p_uart)
Reset UART receiver.
Parameters
p_uart Pointer to a UART instance.
Definition at line 170 of file uart.c.
{
    /* Reset receiver */
    p_uart->UART_CR = UART_CR_RSTRX | UART_CR_RXDIS;
}
References Uart::UART_CR, UART_CR_RSTRX, and UART_CR_RXDIS.
uart_reset_status()
void uart_reset_status (Uart * p_uart)
Reset status bits.
Parameters
p_uart Pointer to a UART instance.
Definition at line 258 of file uart.c.
{
    p_uart->UART_CR = UART_CR_RSTSTA;
}
References Uart::UART_CR, and UART_CR_RSTSTA.
uart_reset_tx()
void uart_reset_tx (Uart * p_uart)
Reset UART transmitter.
Parameters
p_uart Pointer to a UART instance.
Definition at line 137 of file uart.c.
{
    /* Reset transmitter */
    p_uart->UART_CR = UART_CR_RSTTX | UART_CR_TXDIS;
}
References Uart::UART_CR, UART_CR_RSTTX, and UART_CR_TXDIS.
uart_set_clock_divisor()
void uart_set_clock_divisor (Uart * p_uart, uint16_t us_divisor)
Set UART clock divisor value.
Parameters
p_uart Pointer to a UART instance.
us_divisor Value to be set.
Definition at line 327 of file uart.c.
{
    p_uart->UART_BRGR = us_divisor;
}
References Uart::UART_BRGR.
uart_write()
uint32_t uart_write (Uart * p_uart, const uint8_t uc_data)
Write to UART Transmit Holding Register Before writing user should check if tx is ready (or empty).
Parameters
p_uart Pointer to a UART instance.
data Data to be sent.
Return values
0 Success.
1 I/O Failure, UART is not ready.
Definition at line 342 of file uart.c.
{
    /* Check if the transmitter is ready */
    if (!(p_uart->UART_SR & UART_SR_TXRDY))
        return 1;
    /* Send character */
    p_uart->UART_THR = uc_data;
    return 0;
}
References Uart::UART_SR, UART_SR_TXRDY, and Uart::UART_THR.
Referenced by usart_serial_putchar().