WINC1500 Weather Client Demo for SAME70 Xplained: ioport_pio.h File Reference
ioport_pio.h File Reference
SAM architecture specific IOPORT service implementation header file.
#include <sysclk.h>
Macros
#define IOPORT_BASE_ADDRESS (uintptr_t)PIOA
#define IOPORT_CREATE_PIN(port, pin) ((IOPORT_ ## port) * 32 + (pin))
Create IOPORT pin number.
#define IOPORT_PIO_OFFSET ((uintptr_t)PIOB - (uintptr_t)PIOA)
#define IOPORT_PIOA 0
#define IOPORT_PIOB 1
#define IOPORT_PIOC 2
#define IOPORT_PIOD 3
#define IOPORT_PIOE 4
#define IOPORT_PIOF 5
IOPORT Mode bit definitions
#define IOPORT_MODE_DEBOUNCE (1 << 7)
#define IOPORT_MODE_GLITCH_FILTER (1 << 6)
#define IOPORT_MODE_MUX_A (0 << 0)
#define IOPORT_MODE_MUX_B (1 << 0)
#define IOPORT_MODE_MUX_BIT0 (1 << 0)
#define IOPORT_MODE_MUX_MASK (0x7 << 0)
#define IOPORT_MODE_OPEN_DRAIN (1 << 5)
#define IOPORT_MODE_PULLUP (1 << 3)
Typedefs
typedef uint32_t ioport_mode_t
typedef uint32_t ioport_pin_t
typedef uint32_t ioport_port_mask_t
typedef uint32_t ioport_port_t
Functions
static __always_inline void arch_ioport_disable_pin (ioport_pin_t pin)
static __always_inline void arch_ioport_disable_port (ioport_port_t port, ioport_port_mask_t mask)
static __always_inline void arch_ioport_enable_pin (ioport_pin_t pin)
static __always_inline void arch_ioport_enable_port (ioport_port_t port, ioport_port_mask_t mask)
static __always_inline bool arch_ioport_get_pin_level (ioport_pin_t pin)
static __always_inline ioport_port_mask_t arch_ioport_get_port_level (ioport_port_t port, ioport_port_mask_t mask)
static __always_inline void arch_ioport_init (void)
static __always_inline Pio * arch_ioport_pin_to_base (ioport_pin_t pin)
static __always_inline ioport_port_mask_t arch_ioport_pin_to_mask (ioport_pin_t pin)
static __always_inline ioport_port_t arch_ioport_pin_to_port_id (ioport_pin_t pin)
static __always_inline Pio * arch_ioport_port_to_base (ioport_port_t port)
static __always_inline void arch_ioport_set_pin_dir (ioport_pin_t pin, enum ioport_direction dir)
static __always_inline void arch_ioport_set_pin_level (ioport_pin_t pin, bool level)
static __always_inline void arch_ioport_set_pin_mode (ioport_pin_t pin, ioport_mode_t mode)
static __always_inline void arch_ioport_set_pin_sense_mode (ioport_pin_t pin, enum ioport_sense pin_sense)
static __always_inline void arch_ioport_set_port_dir (ioport_port_t port, ioport_port_mask_t mask, enum ioport_direction group_direction)
static __always_inline void arch_ioport_set_port_level (ioport_port_t port, ioport_port_mask_t mask, enum ioport_value level)
static __always_inline void arch_ioport_set_port_mode (ioport_port_t port, ioport_port_mask_t mask, ioport_mode_t mode)
static __always_inline void arch_ioport_set_port_sense_mode (ioport_port_t port, ioport_port_mask_t mask, enum ioport_sense pin_sense)
static __always_inline void arch_ioport_toggle_pin_level (ioport_pin_t pin)
static __always_inline void arch_ioport_toggle_port_level (ioport_port_t port, ioport_port_mask_t mask)
Detailed Description
SAM architecture specific IOPORT service implementation header file.
Copyright (c) 2012-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file ioport_pio.h.
Macro Definition Documentation
IOPORT_BASE_ADDRESS
#define IOPORT_BASE_ADDRESS (uintptr_t)PIOA
Definition at line 42 of file ioport_pio.h.
IOPORT_PIO_OFFSET
#define IOPORT_PIO_OFFSET ((uintptr_t)PIOB - (uintptr_t)PIOA)
Definition at line 43 of file ioport_pio.h.
IOPORT_PIOA
#define IOPORT_PIOA 0
Definition at line 45 of file ioport_pio.h.
IOPORT_PIOB
#define IOPORT_PIOB 1
Definition at line 46 of file ioport_pio.h.
IOPORT_PIOC
#define IOPORT_PIOC 2
Definition at line 47 of file ioport_pio.h.
IOPORT_PIOD
#define IOPORT_PIOD 3
Definition at line 48 of file ioport_pio.h.
IOPORT_PIOE
#define IOPORT_PIOE 4
Definition at line 49 of file ioport_pio.h.
IOPORT_PIOF
#define IOPORT_PIOF 5
Definition at line 50 of file ioport_pio.h.
Typedef Documentation
ioport_mode_t
typedef uint32_t ioport_mode_t
Definition at line 92 of file ioport_pio.h.
ioport_pin_t
typedef uint32_t ioport_pin_t
Definition at line 93 of file ioport_pio.h.
ioport_port_mask_t
typedef uint32_t ioport_port_mask_t
Definition at line 95 of file ioport_pio.h.
ioport_port_t
typedef uint32_t ioport_port_t
Definition at line 94 of file ioport_pio.h.
Function Documentation
arch_ioport_disable_pin()
static __always_inline void arch_ioport_disable_pin (ioport_pin_t pin) static
Definition at line 171 of file ioport_pio.h.
{
    arch_ioport_disable_port(arch_ioport_pin_to_port_id(pin),
            arch_ioport_pin_to_mask(pin));
}
References arch_ioport_disable_port(), arch_ioport_pin_to_mask(), and arch_ioport_pin_to_port_id().
Referenced by ioport_disable_pin().
arch_ioport_disable_port()
static __always_inline void arch_ioport_disable_port (ioport_port_t port, ioport_port_mask_t mask) static
Definition at line 159 of file ioport_pio.h.
{
    arch_ioport_port_to_base(port)->PIO_PDR = mask;
}
References arch_ioport_port_to_base(), and Pio::PIO_PDR.
Referenced by arch_ioport_disable_pin(), and ioport_disable_port().
arch_ioport_enable_pin()
static __always_inline void arch_ioport_enable_pin (ioport_pin_t pin) static
Definition at line 165 of file ioport_pio.h.
{
    arch_ioport_enable_port(arch_ioport_pin_to_port_id(pin),
            arch_ioport_pin_to_mask(pin));
}
References arch_ioport_enable_port(), arch_ioport_pin_to_mask(), and arch_ioport_pin_to_port_id().
Referenced by ioport_enable_pin().
arch_ioport_enable_port()
static __always_inline void arch_ioport_enable_port (ioport_port_t port, ioport_port_mask_t mask) static
Definition at line 153 of file ioport_pio.h.
{
    arch_ioport_port_to_base(port)->PIO_PER = mask;
}
References arch_ioport_port_to_base(), and Pio::PIO_PER.
Referenced by arch_ioport_enable_pin(), and ioport_enable_port().
arch_ioport_get_pin_level()
static __always_inline bool arch_ioport_get_pin_level (ioport_pin_t pin) static
Definition at line 302 of file ioport_pio.h.
{
    return arch_ioport_pin_to_base(pin)->PIO_PDSR & arch_ioport_pin_to_mask(pin);
}
References arch_ioport_pin_to_base(), arch_ioport_pin_to_mask(), and Pio::PIO_PDSR.
Referenced by ioport_get_pin_level().
arch_ioport_get_port_level()
static __always_inline ioport_port_mask_t arch_ioport_get_port_level (ioport_port_t port, ioport_port_mask_t mask) static
Definition at line 307 of file ioport_pio.h.
{
    return arch_ioport_port_to_base(port)->PIO_PDSR & mask;
}
References arch_ioport_port_to_base(), and Pio::PIO_PDSR.
Referenced by ioport_get_port_level().
arch_ioport_init()
static __always_inline void arch_ioport_init (void) static
Definition at line 131 of file ioport_pio.h.
{
#ifdef ID_PIOA
    sysclk_enable_peripheral_clock(ID_PIOA);
#endif
#ifdef ID_PIOB
    sysclk_enable_peripheral_clock(ID_PIOB);
#endif
#ifdef ID_PIOC
    sysclk_enable_peripheral_clock(ID_PIOC);
#endif
#ifdef ID_PIOD
    sysclk_enable_peripheral_clock(ID_PIOD);
#endif
#ifdef ID_PIOE
    sysclk_enable_peripheral_clock(ID_PIOE);
#endif
#ifdef ID_PIOF
    sysclk_enable_peripheral_clock(ID_PIOF);
#endif
}
References ID_PIOA, ID_PIOB, ID_PIOC, ID_PIOD, ID_PIOE, and sysclk_enable_peripheral_clock().
Referenced by ioport_init().
arch_ioport_pin_to_base()
static __always_inline Pio * arch_ioport_pin_to_base (ioport_pin_t pin) static
Definition at line 121 of file ioport_pio.h.
{
    return arch_ioport_port_to_base(arch_ioport_pin_to_port_id(pin));
}
References arch_ioport_pin_to_port_id(), and arch_ioport_port_to_base().
Referenced by arch_ioport_get_pin_level(), arch_ioport_set_pin_dir(), arch_ioport_set_pin_level(), and arch_ioport_toggle_pin_level().
arch_ioport_pin_to_mask()
static __always_inline ioport_port_mask_t arch_ioport_pin_to_mask (ioport_pin_t pin) static
Definition at line 126 of file ioport_pio.h.
{
    return 1U << (pin & 0x1F);
}
Referenced by arch_ioport_disable_pin(), arch_ioport_enable_pin(), arch_ioport_get_pin_level(), arch_ioport_set_pin_dir(), arch_ioport_set_pin_level(), arch_ioport_set_pin_mode(), arch_ioport_set_pin_sense_mode(), arch_ioport_toggle_pin_level(), and ioport_pin_to_mask().
arch_ioport_pin_to_port_id()
static __always_inline ioport_port_t arch_ioport_pin_to_port_id (ioport_pin_t pin) static
Definition at line 97 of file ioport_pio.h.
{
    return pin >> 5;
}
Referenced by arch_ioport_disable_pin(), arch_ioport_enable_pin(), arch_ioport_pin_to_base(), arch_ioport_set_pin_mode(), arch_ioport_set_pin_sense_mode(), and ioport_pin_to_port_id().
arch_ioport_port_to_base()
static __always_inline Pio * arch_ioport_port_to_base (ioport_port_t port) static
Definition at line 102 of file ioport_pio.h.
{
#if (SAM4C || SAM4CM || SAM4CP)
    if (port == IOPORT_PIOC) {
        return (Pio *)(uintptr_t)PIOC;
#  ifdef ID_PIOD
    } else if (port == IOPORT_PIOD) {
        return (Pio *)(uintptr_t)PIOD;
#  endif
    } else {
        return (Pio *)((uintptr_t)IOPORT_BASE_ADDRESS +
               (IOPORT_PIO_OFFSET * port));
    }
#else
    return (Pio *)((uintptr_t)IOPORT_BASE_ADDRESS +
           (IOPORT_PIO_OFFSET * port));
#endif
}
References IOPORT_BASE_ADDRESS, IOPORT_PIO_OFFSET, IOPORT_PIOC, IOPORT_PIOD, PIOC, and PIOD.
Referenced by arch_ioport_disable_port(), arch_ioport_enable_port(), arch_ioport_get_port_level(), arch_ioport_pin_to_base(), arch_ioport_set_port_dir(), arch_ioport_set_port_level(), arch_ioport_set_port_mode(), arch_ioport_set_port_sense_mode(), and arch_ioport_toggle_port_level().
arch_ioport_set_pin_dir()
static __always_inline void arch_ioport_set_pin_dir (ioport_pin_t pin, enum ioport_direction dir) static
Definition at line 264 of file ioport_pio.h.
{
    Pio *base = arch_ioport_pin_to_base(pin);
    if (dir == IOPORT_DIR_OUTPUT) {
        base->PIO_OER = arch_ioport_pin_to_mask(pin);
    } else if (dir == IOPORT_DIR_INPUT) {
        base->PIO_ODR = arch_ioport_pin_to_mask(pin);
    }
    base->PIO_OWER = arch_ioport_pin_to_mask(pin);
}
References arch_ioport_pin_to_base(), arch_ioport_pin_to_mask(), IOPORT_DIR_INPUT, IOPORT_DIR_OUTPUT, Pio::PIO_ODR, Pio::PIO_OER, and Pio::PIO_OWER.
Referenced by ioport_set_pin_dir().
arch_ioport_set_pin_level()
static __always_inline void arch_ioport_set_pin_level (ioport_pin_t pin, bool level) static
Definition at line 278 of file ioport_pio.h.
{
    Pio *base = arch_ioport_pin_to_base(pin);
    if (level) {
        base->PIO_SODR = arch_ioport_pin_to_mask(pin);
    } else {
        base->PIO_CODR = arch_ioport_pin_to_mask(pin);
    }
}
References arch_ioport_pin_to_base(), arch_ioport_pin_to_mask(), Pio::PIO_CODR, and Pio::PIO_SODR.
Referenced by ioport_set_pin_level().
arch_ioport_set_pin_mode()
static __always_inline void arch_ioport_set_pin_mode (ioport_pin_t pin, ioport_mode_t mode) static
Definition at line 243 of file ioport_pio.h.
{
    arch_ioport_set_port_mode(arch_ioport_pin_to_port_id(pin),
            arch_ioport_pin_to_mask(pin), mode);
}
References arch_ioport_pin_to_mask(), arch_ioport_pin_to_port_id(), and arch_ioport_set_port_mode().
Referenced by ioport_reset_pin_mode(), and ioport_set_pin_mode().
arch_ioport_set_pin_sense_mode()
static __always_inline void arch_ioport_set_pin_sense_mode (ioport_pin_t pin, enum ioport_sense pin_sense) static
Definition at line 366 of file ioport_pio.h.
{
    arch_ioport_set_port_sense_mode(arch_ioport_pin_to_port_id(pin),
            arch_ioport_pin_to_mask(pin), pin_sense);
}
References arch_ioport_pin_to_mask(), arch_ioport_pin_to_port_id(), and arch_ioport_set_port_sense_mode().
Referenced by ioport_set_pin_sense_mode().
arch_ioport_set_port_dir()
static __always_inline void arch_ioport_set_port_dir (ioport_port_t port, ioport_port_mask_t mask, enum ioport_direction group_direction) static
Definition at line 250 of file ioport_pio.h.
{
    Pio *base = arch_ioport_port_to_base(port);
    if (group_direction == IOPORT_DIR_OUTPUT) {
        base->PIO_OER = mask;
    } else if (group_direction == IOPORT_DIR_INPUT) {
        base->PIO_ODR = mask;
    }
    base->PIO_OWER = mask;
}
References arch_ioport_port_to_base(), IOPORT_DIR_INPUT, IOPORT_DIR_OUTPUT, Pio::PIO_ODR, Pio::PIO_OER, and Pio::PIO_OWER.
Referenced by ioport_set_port_dir().
arch_ioport_set_port_level()
static __always_inline void arch_ioport_set_port_level (ioport_port_t port, ioport_port_mask_t mask, enum ioport_value level) static
Definition at line 290 of file ioport_pio.h.
{
    Pio *base = arch_ioport_port_to_base(port);
    if (level){
        base->PIO_SODR = mask;
    } else {
        base->PIO_CODR = mask;
    }
}
References arch_ioport_port_to_base(), Pio::PIO_CODR, and Pio::PIO_SODR.
Referenced by ioport_set_port_level().
arch_ioport_set_port_mode()
static __always_inline void arch_ioport_set_port_mode (ioport_port_t port, ioport_port_mask_t mask, ioport_mode_t mode) static
Definition at line 177 of file ioport_pio.h.
{
    Pio *base = arch_ioport_port_to_base(port);
    if (mode & IOPORT_MODE_PULLUP) {
        base->PIO_PUER = mask;
    } else {
        base->PIO_PUDR = mask;
    }
#if defined(IOPORT_MODE_PULLDOWN)
    if (mode & IOPORT_MODE_PULLDOWN) {
        base->PIO_PPDER = mask;
    } else {
        base->PIO_PPDDR = mask;
    }
#endif
    if (mode & IOPORT_MODE_OPEN_DRAIN) {
        base->PIO_MDER = mask;
    } else {
        base->PIO_MDDR = mask;
    }
    if (mode & (IOPORT_MODE_GLITCH_FILTER | IOPORT_MODE_DEBOUNCE)) {
        base->PIO_IFER = mask;
    } else {
        base->PIO_IFDR = mask;
    }
    if (mode & IOPORT_MODE_DEBOUNCE) {
#if SAM3U || SAM3XA
        base->PIO_DIFSR = mask;
#else
        base->PIO_IFSCER = mask;
#endif
    } else {
#if SAM3U || SAM3XA
        base->PIO_SCIFSR = mask;
#else
        base->PIO_IFSCDR = mask;
#endif
    }
#if !defined(IOPORT_MODE_MUX_BIT1)
    if (mode & IOPORT_MODE_MUX_BIT0) {
        base->PIO_ABSR |= mask;
    } else {
        base->PIO_ABSR &= ~mask;
    }
#else
    if (mode & IOPORT_MODE_MUX_BIT0) {
        base->PIO_ABCDSR[0] |= mask;
    } else {
        base->PIO_ABCDSR[0] &= ~mask;
    }
    if (mode & IOPORT_MODE_MUX_BIT1) {
        base->PIO_ABCDSR[1] |= mask;
    } else {
        base->PIO_ABCDSR[1] &= ~mask;
    }
#endif
}
References arch_ioport_port_to_base(), IOPORT_MODE_DEBOUNCE, IOPORT_MODE_GLITCH_FILTER, IOPORT_MODE_MUX_BIT0, IOPORT_MODE_OPEN_DRAIN, IOPORT_MODE_PULLUP, Pio::PIO_ABCDSR, Pio::PIO_IFDR, Pio::PIO_IFER, Pio::PIO_IFSCDR, Pio::PIO_IFSCER, Pio::PIO_MDDR, Pio::PIO_MDER, Pio::PIO_PPDDR, Pio::PIO_PPDER, Pio::PIO_PUDR, and Pio::PIO_PUER.
Referenced by arch_ioport_set_pin_mode(), ioport_reset_port_mode(), and ioport_set_port_mode().
arch_ioport_set_port_sense_mode()
static __always_inline void arch_ioport_set_port_sense_mode (ioport_port_t port, ioport_port_mask_t mask, enum ioport_sense pin_sense) static
Definition at line 331 of file ioport_pio.h.
{
    Pio *base = arch_ioport_port_to_base(port);
    /*   AIMMR    ELSR    FRLHSR
     *       0       X         X    IOPORT_SENSE_BOTHEDGES (Default)
     *       1       0         0    IOPORT_SENSE_FALLING
     *       1       0         1    IOPORT_SENSE_RISING
     *       1       1         0    IOPORT_SENSE_LEVEL_LOW
     *       1       1         1    IOPORT_SENSE_LEVEL_HIGH
     */
    switch(pin_sense) {
    case IOPORT_SENSE_LEVEL_LOW:
        base->PIO_LSR = mask;
        base->PIO_FELLSR = mask;
        break;
    case IOPORT_SENSE_LEVEL_HIGH:
        base->PIO_LSR = mask;
        base->PIO_REHLSR = mask;
        break;
    case IOPORT_SENSE_FALLING:
        base->PIO_ESR = mask;
        base->PIO_FELLSR = mask;
        break;
    case IOPORT_SENSE_RISING:
        base->PIO_ESR = mask;
        base->PIO_REHLSR = mask;
        break;
    default:
        base->PIO_AIMDR = mask;
        return;
    }
    base->PIO_AIMER = mask;
}
References arch_ioport_port_to_base(), IOPORT_SENSE_FALLING, IOPORT_SENSE_RISING, Pio::PIO_AIMDR, Pio::PIO_AIMER, Pio::PIO_ESR, Pio::PIO_FELLSR, Pio::PIO_LSR, and Pio::PIO_REHLSR.
Referenced by arch_ioport_set_pin_sense_mode(), and ioport_set_port_sense_mode().
arch_ioport_toggle_pin_level()
static __always_inline void arch_ioport_toggle_pin_level (ioport_pin_t pin) static
Definition at line 313 of file ioport_pio.h.
{
    Pio *port = arch_ioport_pin_to_base(pin);
    ioport_port_mask_t mask = arch_ioport_pin_to_mask(pin);
    if (port->PIO_PDSR & arch_ioport_pin_to_mask(pin)) {
        port->PIO_CODR = mask;
    } else {
        port->PIO_SODR = mask;
    }
}
References arch_ioport_pin_to_base(), arch_ioport_pin_to_mask(), Pio::PIO_CODR, Pio::PIO_PDSR, and Pio::PIO_SODR.
Referenced by ioport_toggle_pin_level().
arch_ioport_toggle_port_level()
static __always_inline void arch_ioport_toggle_port_level (ioport_port_t port, ioport_port_mask_t mask) static
Definition at line 325 of file ioport_pio.h.
{
    arch_ioport_port_to_base(port)->PIO_ODSR ^= mask;
}
References arch_ioport_port_to_base(), and Pio::PIO_ODSR.
Referenced by ioport_toggle_port_level().