WINC1500 Weather Client Demo for SAME70 Xplained: m2m_hif.h File Reference
m2m_hif.h File Reference
This module contains M2M host interface APIs implementation.
#include "common/include/nm_common.h"
Data Structures
struct tstrHifHdr
Structure to hold HIF header.
Macros
#define M2M_HIF_HDR_OFFSET (sizeof(tstrHifHdr) + 4)
#define M2M_HIF_MAX_PACKET_SIZE (1600 - 4)
Typedefs
typedef void(* tpfHifCallBack) (uint8 u8OpCode, uint16 u16DataSize, uint32 u32Addr)
used to point to Wi-Fi call back function depend on Arduino project or other projects.
Functions
NMI_API sint8 hif_chip_sleep (void)
To make the chip sleep.
NMI_API sint8 hif_chip_sleep_sc (void)
To clear the chip sleep but keep the chip sleep.
NMI_API sint8 hif_chip_wake (void)
To Wakeup the chip.
NMI_API sint8 hif_deinit (void *arg)
To De-initialize HIF layer.
NMI_API uint8 hif_get_sleep_mode (void)
Get the sleep mode of the HIF layer.
NMI_API sint8 hif_handle_isr (void)
Handle interrupt received from NMC1500 firmware.
NMI_API sint8 hif_init (void *arg)
To initialize HIF layer.
NMI_API sint8 hif_receive (uint32 u32Addr, uint8 *pu8Buf, uint16 u16Sz, uint8 isDone)
NMI_API sint8 hif_register_cb (uint8 u8Grp, tpfHifCallBack fn)
NMI_API sint8 hif_send (uint8 u8Gid, uint8 u8Opcode, uint8 *pu8CtrlBuf, uint16 u16CtrlBufSize, uint8 *pu8DataBuf, uint16 u16DataSize, uint16 u16DataOffset)
Send packet using host interface.
NMI_API void hif_set_sleep_mode (uint8 u8Pstype)
Set the sleep mode of the HIF layer.
NMI_API void hif_yield (void)
Yields control from interrupt event handler.
Detailed Description
This module contains M2M host interface APIs implementation.
Copyright (c) 2016-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file m2m_hif.h.
Macro Definition Documentation
M2M_HIF_HDR_OFFSET
#define M2M_HIF_HDR_OFFSET (sizeof(tstrHifHdr) + 4)
Definition at line 56 of file m2m_hif.h.
M2M_HIF_MAX_PACKET_SIZE
#define M2M_HIF_MAX_PACKET_SIZE (1600 - 4)
< Include depends on UNO Board is used or not Maximum size of the buffer could be transferred between Host and Firmware.
Definition at line 54 of file m2m_hif.h.
Typedef Documentation
tpfHifCallBack
typedef void(* tpfHifCallBack)(uint8 u8OpCode, uint16 u16DataSize, uint32 u32Addr)
used to point to Wi-Fi call back function depend on Arduino project or other projects.
Parameters
[in] u8OpCode HIF Opcode type.
[in] u16DataSize HIF data length.
[in] u32Addr HIF address.
[in] grp HIF group type.
Definition at line 85 of file m2m_hif.h.
Function Documentation
hif_chip_sleep()
NMI_API sint8 hif_chip_sleep (void)
To make the chip sleep.
Returns
The function shall return ZERO for successful operation and a negative value otherwise.
Definition at line 219 of file m2m_hif.c.
{
    sint8 ret = M2M_SUCCESS;
    if(gstrHifCxt.u8ChipSleep >= 1)
    {
        gstrHifCxt.u8ChipSleep--;
    }
    if(gstrHifCxt.u8ChipSleep == 0)
    {
        if(gstrHifCxt.u8ChipMode != M2M_NO_PS)
        {
            ret = chip_sleep();
            if(ret != M2M_SUCCESS)goto ERR1;
        }
        else
        {
        }
    }
ERR1:
    return ret;
}
References chip_sleep(), gstrHifCxt, M2M_NO_PS, M2M_SUCCESS, tstrHifContext::u8ChipMode, and tstrHifContext::u8ChipSleep.
Referenced by hif_send(), m2m_ota_get_firmware_version(), m2m_wifi_get_firmware_version(), m2m_wifi_get_mac_address(), and m2m_wifi_get_otp_mac_address().
hif_chip_sleep_sc()
NMI_API sint8 hif_chip_sleep_sc (void)
To clear the chip sleep but keep the chip sleep.
To clear the chip count only but keep the chip awake.
Returns
The function shall return ZERO for successful operation and a negative value otherwise.
Definition at line 205 of file m2m_hif.c.
{
    if(gstrHifCxt.u8ChipSleep >= 1)
    {
        gstrHifCxt.u8ChipSleep--;
    }
    return M2M_SUCCESS;
}
References gstrHifCxt, M2M_SUCCESS, and tstrHifContext::u8ChipSleep.
Referenced by hif_send().
hif_chip_wake()
NMI_API sint8 hif_chip_wake (void)
To Wakeup the chip.
Returns
The function shall return ZERO for successful operation and a negative value otherwise.
Definition at line 142 of file m2m_hif.c.
{
    sint8 ret = M2M_SUCCESS;
    if(gstrHifCxt.u8HifRXDone)
    {
        /*chip already wake for the rx not done no need to send wake request*/
        return ret;
    }
    if(gstrHifCxt.u8ChipSleep == 0)
    {
        if(gstrHifCxt.u8ChipMode != M2M_NO_PS)
        {
            ret = chip_wake();
            if(ret != M2M_SUCCESS)goto ERR1;
        }
        else
        {
        }
    }
    gstrHifCxt.u8ChipSleep++;
ERR1:
    return ret;
}
References chip_wake(), gstrHifCxt, M2M_NO_PS, M2M_SUCCESS, tstrHifContext::u8ChipMode, tstrHifContext::u8ChipSleep, and tstrHifContext::u8HifRXDone.
Referenced by hif_deinit(), hif_send(), m2m_ota_get_firmware_version(), m2m_wifi_get_firmware_version(), m2m_wifi_get_mac_address(), and m2m_wifi_get_otp_mac_address().
hif_deinit()
NMI_API sint8 hif_deinit (void * arg)
To De-initialize HIF layer.
To Deinitialize HIF layer.
Parameters
[in] arg Pointer to the arguments.
Returns
The function shall return ZERO for successful operation and a negative value otherwise.
Definition at line 264 of file m2m_hif.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = hif_chip_wake();
    m2m_memset((uint8*)&gstrHifCxt,0,sizeof(tstrHifContext));
    return ret;
}
References gstrHifCxt, hif_chip_wake(), m2m_memset(), and M2M_SUCCESS.
Referenced by m2m_wifi_deinit().
hif_get_sleep_mode()
NMI_API uint8 hif_get_sleep_mode (void)
Get the sleep mode of the HIF layer.
Returns
The function SHALL return the sleep mode of the HIF layer.
Returns
The function SHALL return the sleep mode of the HIF layer.
Definition at line 194 of file m2m_hif.c.
{
    return gstrHifCxt.u8ChipMode;
}
References gstrHifCxt, and tstrHifContext::u8ChipMode.
Referenced by m2m_wifi_get_sleep_mode(), and m2m_wifi_request_sleep().
hif_handle_isr()
NMI_API sint8 hif_handle_isr (void)
Handle interrupt received from NMC1500 firmware.
Returns
The function SHALL return 0 for success and a negative value otherwise.
Definition at line 581 of file m2m_hif.c.
{
    sint8 ret = M2M_SUCCESS;
    gstrHifCxt.u8Yield = 0;
    while(gstrHifCxt.u8Interrupt && !gstrHifCxt.u8Yield)
    {
        /* Atomic decrement u8Interrupt since it takes multiple instructions to load, decrement and store,
         * during which the ISR could fire again.
         * If LEVEL interrupt is used instead of EDGE then the atomicity isn't needed since the interrupt
         * is turned off in the ISR and back on again only after the interrupt has been serviced in hif_isr(). */
#ifndef NM_LEVEL_INTERRUPT
        nm_bsp_interrupt_ctrl(0);
#endif
        gstrHifCxt.u8Interrupt--;
#ifndef NM_LEVEL_INTERRUPT
        nm_bsp_interrupt_ctrl(1);
#endif
        uint8 retries = 5;
        while(1)
        {
            ret = hif_isr();
            if(ret == M2M_SUCCESS) {
                /*we will try forever until we get that interrupt*/
                /*Fail return errors here due to bus errors (reading expected values)*/
                break;
            } else {
                retries--;
                if(!retries)
                {
                    M2M_ERR("(HIF) Failed to handle interrupt %d, aborting due to too many retries\n", ret);
                    break;
                }
                else
                    M2M_ERR("(HIF) Failed to handle interrupt %d try again... (%u)\n", ret, retries);
            }
        }
    }
    return ret;
}
References gstrHifCxt, hif_isr(), M2M_ERR, M2M_SUCCESS, nm_bsp_interrupt_ctrl(), tstrHifContext::u8Interrupt, and tstrHifContext::u8Yield.
Referenced by m2m_wifi_handle_events().
hif_init()
NMI_API sint8 hif_init (void * arg)
To initialize HIF layer.
Parameters
[in] arg Pointer to the arguments.
Returns
The function shall return ZERO for successful operation and a negative value otherwise.
Definition at line 250 of file m2m_hif.c.
{
    m2m_memset((uint8*)&gstrHifCxt,0,sizeof(tstrHifContext));
    nm_bsp_register_isr(isr);
    hif_register_cb(M2M_REQ_GROUP_HIF,m2m_hif_cb);
    return M2M_SUCCESS;
}
References gstrHifCxt, hif_register_cb(), isr(), m2m_hif_cb(), m2m_memset(), M2M_REQ_GROUP_HIF, M2M_SUCCESS, and nm_bsp_register_isr().
Referenced by m2m_wifi_init_start().
hif_receive()
NMI_API sint8 hif_receive (uint32 u32Addr, uint8 * pu8Buf, uint16 u16Sz, uint8 isDone)
Definition at line 639 of file m2m_hif.c.
{
    sint8 ret = M2M_SUCCESS;
    if((u32Addr == 0)||(pu8Buf == NULL) || (u16Sz == 0))
    {
        if(isDone)
        {
            /* set RX done */
            ret = hif_set_rx_done();
        }
        else
        {
            ret = M2M_ERR_FAIL;
            M2M_ERR(" hif_receive: Invalid argument\n");
        }
        goto ERR1;
    }
    if(u16Sz > gstrHifCxt.u32RxSize)
    {
        ret = M2M_ERR_FAIL;
        M2M_ERR("APP Requested Size is larger than the received buffer size <%u><%lu>\n",u16Sz, gstrHifCxt.u32RxSize);
        goto ERR1;
    }
    if((u32Addr < gstrHifCxt.u32RxAddr)||((u32Addr + u16Sz)>(gstrHifCxt.u32RxAddr + gstrHifCxt.u32RxSize)))
    {
        ret = M2M_ERR_FAIL;
        M2M_ERR("APP Requested Address beyond the received buffer address and length\n");
        goto ERR1;
    }
    /* Receive the payload */
    ret = nm_read_block(u32Addr, pu8Buf, u16Sz);
    if(ret != M2M_SUCCESS)goto ERR1;
    /* check if this is the last packet */
    if((((gstrHifCxt.u32RxAddr + gstrHifCxt.u32RxSize) - (u32Addr + u16Sz)) <= 0) || isDone)
    {
        /* set RX done */
        ret = hif_set_rx_done();
    }
ERR1:
    return ret;
}
References gstrHifCxt, hif_set_rx_done(), M2M_ERR, M2M_ERR_FAIL, M2M_SUCCESS, nm_read_block(), NULL, tstrHifContext::u32RxAddr, and tstrHifContext::u32RxSize.
Referenced by m2m_ip_cb(), m2m_ota_cb(), m2m_ssl_cb(), m2m_ssl_retrieve_hash(), m2m_ssl_retrieve_next_for_verifying(), m2m_ssl_stop_retrieving(), m2m_wifi_cb(), and Socket_ReadSocketData().
hif_register_cb()
NMI_API sint8 hif_register_cb (uint8 u8Grp, tpfHifCallBack fn)
Definition at line 695 of file m2m_hif.c.
{
    sint8 ret = M2M_SUCCESS;
    switch(u8Grp)
    {
        case M2M_REQ_GROUP_IP:
            gstrHifCxt.pfIpCb = fn;
            break;
        case M2M_REQ_GROUP_WIFI:
            gstrHifCxt.pfWifiCb = fn;
            break;
        case M2M_REQ_GROUP_OTA:
            gstrHifCxt.pfOtaCb = fn;
            break;
        case M2M_REQ_GROUP_HIF:
            gstrHifCxt.pfHifCb = fn;
            break;
        case M2M_REQ_GROUP_CRYPTO:
            gstrHifCxt.pfCryptoCb = fn;
            break;
        case M2M_REQ_GROUP_SIGMA:
            gstrHifCxt.pfSigmaCb = fn;
            break;
        case M2M_REQ_GROUP_SSL:
            gstrHifCxt.pfSslCb = fn;
            break;
        default:
            M2M_ERR("GRp ? %d\n",u8Grp);
            ret = M2M_ERR_FAIL;
            break;
    }
    return ret;
}
References gstrHifCxt, M2M_ERR, M2M_ERR_FAIL, M2M_REQ_GROUP_CRYPTO, M2M_REQ_GROUP_HIF, M2M_REQ_GROUP_IP, M2M_REQ_GROUP_OTA, M2M_REQ_GROUP_SIGMA, M2M_REQ_GROUP_SSL, M2M_REQ_GROUP_WIFI, M2M_SUCCESS, tstrHifContext::pfCryptoCb, tstrHifContext::pfHifCb, tstrHifContext::pfIpCb, tstrHifContext::pfOtaCb, tstrHifContext::pfSigmaCb, tstrHifContext::pfSslCb, and tstrHifContext::pfWifiCb.
Referenced by hif_init(), m2m_ota_init(), m2m_ssl_init(), m2m_wifi_init_start(), socketDeinit(), and socketInit().
hif_send()
NMI_API sint8 hif_send (uint8 u8Gid, uint8 u8Opcode, uint8 * pu8CtrlBuf, uint16 u16CtrlBufSize, uint8 * pu8DataBuf, uint16 u16DataSize, uint16 u16DataOffset)
Send packet using host interface.
Parameters
[in] u8Gid Group ID.
[in] u8Opcode Operation ID.
[in] pu8CtrlBuf Pointer to the Control buffer.
[in] u16CtrlBufSize Control buffer size.
[in] u16DataOffset Packet Data offset.
[in] pu8DataBuf Packet buffer Allocated by the caller.
[in] u16DataSize Packet buffer size (including the HIF header).
Returns
The function shall return ZERO for successful operation and a negative value otherwise.
Definition at line 293 of file m2m_hif.c.
{
    sint8       ret = M2M_ERR_SEND;
    tstrHifHdr  strHif;
    strHif.u8Opcode     = u8Opcode&(~NBIT7);
    strHif.u8Gid        = u8Gid;
    strHif.u16Length    = M2M_HIF_HDR_OFFSET;
    if(pu8DataBuf != NULL)
    {
        strHif.u16Length += u16DataOffset + u16DataSize;
    }
    else
    {
        strHif.u16Length += u16CtrlBufSize;
    }
    if (strHif.u16Length <= M2M_HIF_MAX_PACKET_SIZE)
    {
    ret = hif_chip_wake();
    if(ret == M2M_SUCCESS)
    {
        volatile uint32 reg, dma_addr = 0;
        volatile uint16 cnt = 0;
//#define OPTIMIZE_BUS
/*please define in firmware also*/
#ifndef OPTIMIZE_BUS
        reg = 0UL;
        reg |= (uint32)u8Gid;
        reg |= ((uint32)u8Opcode<<8);
        reg |= ((uint32)strHif.u16Length<<16);
        ret = nm_write_reg(NMI_STATE_REG,reg);
        if(M2M_SUCCESS != ret) goto ERR1;
        reg = 0UL;
        reg |= NBIT1;
        ret = nm_write_reg(WIFI_HOST_RCV_CTRL_2, reg);
        if(M2M_SUCCESS != ret) goto ERR1;
#else
        reg = 0UL;
        reg |= NBIT1;
        reg |= ((u8Opcode & NBIT7) ? (NBIT2):(0)); /*Data = 1 or config*/
        reg |= (u8Gid == M2M_REQ_GROUP_IP) ? (NBIT3):(0); /*IP = 1 or non IP*/
        reg |= ((uint32)strHif.u16Length << 4); /*length of pkt max = 4096*/
        ret = nm_write_reg(WIFI_HOST_RCV_CTRL_2, reg);
        if(M2M_SUCCESS != ret) goto ERR1;
#endif
        dma_addr = 0;
        for(cnt = 0; cnt < 1000; cnt ++)
        {
            ret = nm_read_reg_with_ret(WIFI_HOST_RCV_CTRL_2,(uint32 *)&reg);
            if(ret != M2M_SUCCESS) break;
            /*
             * If it takes too long to get a response, the slow down to
             * avoid back-to-back register read operations.
             */
            if(cnt >= 500) {
                if(cnt < 501) {
                    M2M_INFO("Slowing down...\n");
                }
                nm_bsp_sleep(1);
            }
            if (!(reg & NBIT1))
            {
                ret = nm_read_reg_with_ret(WIFI_HOST_RCV_CTRL_4,(uint32 *)&dma_addr);
                if(ret != M2M_SUCCESS) {
                    /*in case of read error clear the DMA address and return error*/
                    dma_addr = 0;
                    goto ERR1;
                }
                /*in case of success break */
                break;
            }
        }
        if (dma_addr != 0)
        {
            volatile uint32 u32CurrAddr;
            u32CurrAddr = dma_addr;
            strHif.u16Length=NM_BSP_B_L_16(strHif.u16Length);
            ret = nm_write_block(u32CurrAddr, (uint8*)&strHif, M2M_HIF_HDR_OFFSET);
            if(M2M_SUCCESS != ret) goto ERR1;
            u32CurrAddr += M2M_HIF_HDR_OFFSET;
            if(pu8CtrlBuf != NULL)
            {
                ret = nm_write_block(u32CurrAddr, pu8CtrlBuf, u16CtrlBufSize);
                if(M2M_SUCCESS != ret) goto ERR1;
                u32CurrAddr += u16CtrlBufSize;
            }
            if(pu8DataBuf != NULL)
            {
                u32CurrAddr += (u16DataOffset - u16CtrlBufSize);
                ret = nm_write_block(u32CurrAddr, pu8DataBuf, u16DataSize);
                if(M2M_SUCCESS != ret) goto ERR1;
                u32CurrAddr += u16DataSize;
            }
            reg = dma_addr << 2;
            reg |= NBIT1;
            ret = nm_write_reg(WIFI_HOST_RCV_CTRL_3, reg);
            if(M2M_SUCCESS != ret) goto ERR1;
        }
        else
        {
            ret = hif_chip_sleep();
            M2M_DBG("Failed to alloc rx size %d\r",ret);
            ret = M2M_ERR_MEM_ALLOC;
            goto ERR2;
        }
    }
    else
    {
            M2M_ERR("(HIF)Failed to wakeup the chip\n");
            goto ERR2;
        }
    }
    else
    {
        M2M_ERR("HIF message length (%d) exceeds max length (%d)\n",strHif.u16Length, M2M_HIF_MAX_PACKET_SIZE);
        ret = M2M_ERR_SEND;
        goto ERR2;
    }
    /*actual sleep ret = M2M_SUCCESS*/
    ret = hif_chip_sleep();
    return ret;
ERR1:
    /*reset the count but no actual sleep as it already bus error*/
    hif_chip_sleep_sc();
ERR2:
    /*logical error*/
    return ret;
}
References hif_chip_sleep(), hif_chip_sleep_sc(), hif_chip_wake(), M2M_DBG, M2M_ERR, M2M_ERR_MEM_ALLOC, M2M_ERR_SEND, M2M_HIF_HDR_OFFSET, M2M_HIF_MAX_PACKET_SIZE, M2M_INFO, M2M_REQ_GROUP_IP, M2M_SUCCESS, NBIT1, NBIT2, NBIT3, NBIT7, NM_BSP_B_L_16, nm_bsp_sleep(), nm_read_reg_with_ret(), nm_write_block(), nm_write_reg(), NMI_STATE_REG, NULL, tstrHifHdr::u16Length, tstrHifHdr::u8Gid, tstrHifHdr::u8Opcode, WIFI_HOST_RCV_CTRL_2, WIFI_HOST_RCV_CTRL_3, and WIFI_HOST_RCV_CTRL_4.
Referenced by m2m_ota_abort(), m2m_ota_host_file_erase(), m2m_ota_host_file_get(), m2m_ota_host_file_read_hif(), m2m_ota_init(), m2m_ota_notif_check_for_update(), m2m_ota_notif_sched(), m2m_ota_notif_set_url(), m2m_ota_rollback(), m2m_ota_start_update(), m2m_ota_switch_firmware(), m2m_ssl_handshake_rsp(), m2m_ssl_send_certs_to_winc(), m2m_ssl_set_active_ciphersuites(), m2m_wifi_conf_auto_rate(), m2m_wifi_configure_sntp(), m2m_wifi_connect_1x_mschap2(), m2m_wifi_connect_1x_tls(), m2m_wifi_connect_open(), m2m_wifi_connect_psk(), m2m_wifi_connect_wep(), m2m_wifi_default_connect(), m2m_wifi_delete_sc(), m2m_wifi_disable_ap(), m2m_wifi_disable_roaming(), m2m_wifi_disconnect(), m2m_wifi_enable_ap_ext(), m2m_wifi_enable_dhcp(), m2m_wifi_enable_firmware_logs(), m2m_wifi_enable_roaming(), m2m_wifi_enable_sntp(), m2m_wifi_enable_XO_during_sleep(), m2m_wifi_get_connection_info(), m2m_wifi_get_system_time(), m2m_wifi_p2p(), m2m_wifi_p2p_disconnect(), m2m_wifi_prng_get_random_bytes(), m2m_wifi_req_client_ctrl(), m2m_wifi_req_curr_rssi(), m2m_wifi_req_scan_result(), m2m_wifi_req_server_init(), m2m_wifi_request_scan(), m2m_wifi_request_scan_passive(), m2m_wifi_request_scan_ssid_list(), m2m_wifi_request_sleep(), m2m_wifi_send_crl(), m2m_wifi_send_ethernet_pkt(), m2m_wifi_set_battery_voltage(), m2m_wifi_set_cust_InfoElement(), m2m_wifi_set_device_name(), m2m_wifi_set_gain_table_idx(), m2m_wifi_set_gains(), m2m_wifi_set_lsn_int(), m2m_wifi_set_mac_address(), m2m_wifi_set_power_profile(), m2m_wifi_set_scan_options(), m2m_wifi_set_scan_region(), m2m_wifi_set_sleep_mode(), m2m_wifi_set_static_ip(), m2m_wifi_set_stop_scan_on_first(), m2m_wifi_set_system_time(), m2m_wifi_set_tx_power(), m2m_wifi_start_provision_mode_ext(), m2m_wifi_stop_provision_mode(), m2m_wifi_wps(), and m2m_wifi_wps_disable().
hif_set_sleep_mode()
NMI_API void hif_set_sleep_mode (uint8 u8Pstype)
Set the sleep mode of the HIF layer.
Parameters
[in] u8Pstype Sleep mode.
Returns
The function SHALL return 0 for success and a negative value otherwise.
Parameters
[in] u8Pstype Sleep mode.
Returns
The function SHALL return 0 for success and a negative value otherwise.
Definition at line 179 of file m2m_hif.c.
{
    gstrHifCxt.u8ChipMode = u8Pstype;
}
References gstrHifCxt, and tstrHifContext::u8ChipMode.
Referenced by m2m_wifi_set_sleep_mode().
hif_yield()
NMI_API void hif_yield (void)
Yields control from interrupt event handler.
Definition at line 570 of file m2m_hif.c.
{
    gstrHifCxt.u8Yield = 1;
}
References gstrHifCxt, and tstrHifContext::u8Yield.
Referenced by m2m_wifi_yield().