WINC1500 Weather Client Demo for SAME70 Xplained: main.c File Reference
main.c File Reference
SAME70 Weather Client Demo Example.
#include "asf.h"
#include "image.h"
#include "main_wifi.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "bsp/include/nm_bsp.h"
#include "driver/include/m2m_wifi.h"
#include "socket/include/socket.h"
Macros
#define ASCII_BS 0x7F
ASCII char definition for backspace.
#define ASCII_CR 13
ASCII char definition for carriage return.
#define STRING_EOL "\r\n"
#define STRING_HEADER
Functions
static void configure_console (void)
Configure UART console.
void configure_rtt (void)
RTT configuration function.
void ili9488_draw_number (uint32_t ul_x, uint32_t ul_y, uint8_t index)
void ili9488_draw_temperature (uint32_t ul_x, uint32_t ul_y, char *temperature)
int main (void)
Main application function.
static uint8_t parse_weather_icon (char *pcWeather)
static void refresh_display ()
static void resolve_cb (uint8_t *hostName, uint32_t hostIp)
Callback function of IP address.
void RTT_Handler (void)
Interrupt handler for the RTT.
static void socket_cb (SOCKET sock, uint8_t u8Msg, void *pvMsg)
Callback function of TCP client socket.
static void wifi_cb (uint8_t u8MsgType, void *pvMsg)
Callback to get the Wi-Fi status update.
void wifi_connect (void)
static void wifi_handle_events (void)
static void wifi_init (void)
void wifi_recieve_packet (void)
static void wifi_require_weather (char *city_name)
Variables
bool city_is_sha = true
bool display_is_sha = true
struct ili9488_opt_t g_ili9488_display_opt
uint32_t g_ul_sec_ticks = 0
static uint8_t gau8ReceivedBuffer [MAIN_WIFI_M2M_BUFFER_SIZE] = {0}
Receive buffer definition.
static bool gbConnectedWifi = false
Wi-Fi status variable.
static bool gbContinueReceive = false
Continue Receive status variable.
static bool gbFinishedGetWeather = false
Weather client status variable.
static bool gbHostIpByName = false
Get host IP status variable.
static bool gbRequireWeather = false
static bool gbTcpConnection = false
TCP Connection status variable.
static char gcWeatherInfo [2048] = {0}
uint32_t gu32HostIp = 0
IP address of host.
char * gWeatherIcon [4]
const uint8_t mark [11] = {'S', 'A', 'M', 'E','7', '0', 'D', 'E', 'M','O'}
char * pcCity = NULL
char * pcTemperature = NULL
char * pcWeather = NULL
static char server_host_name [] = MAIN_WEATHER_SERVER_NAME
Server host name.
static SOCKET tcp_client_socket = -1
TCP client socket handlers.
char Temperature_seoul [30]
char Temperature_sha [30]
uint8_t ucWeatherNum = 0
uint8_t ucWeatherNum_seoul
uint8_t ucWeatherNum_sha
char Weather_seoul [30]
char Weather_sha [30]
Detailed Description
SAME70 Weather Client Demo Example.
Copyright (c) 2015-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file main.c.
Macro Definition Documentation
ASCII_BS
#define ASCII_BS 0x7F
ASCII char definition for backspace.
Definition at line 132 of file main.c.
ASCII_CR
#define ASCII_CR 13
ASCII char definition for carriage return.
Definition at line 134 of file main.c.
STRING_EOL
#define STRING_EOL "\r\n"
Definition at line 136 of file main.c.
STRING_HEADER
#define STRING_HEADER
Value:
    "-- SAME70 Weather Client Demo --"STRING_EOL    \
    "-- "BOARD_NAME " --"STRING_EOL \
    "-- Compiled: "__DATE__ " "__TIME__ " --"STRING_EOL
Definition at line 137 of file main.c.
Function Documentation
configure_console()
static void configure_console (void) static
Configure UART console.
Definition at line 584 of file main.c.
{
    const usart_serial_options_t uart_serial_options = {
        .baudrate =     CONF_UART_BAUDRATE,
        .charlength =   CONF_UART_CHAR_LENGTH,
        .paritytype =   CONF_UART_PARITY,
        .stopbits =     CONF_UART_STOP_BITS,
    };
    /* Configure UART console. */
    sysclk_enable_peripheral_clock(CONSOLE_UART_ID);
    stdio_serial_init(CONF_UART, &uart_serial_options);
}
References uart_rs232_options::baudrate, CONF_UART, CONF_UART_BAUDRATE, CONF_UART_CHAR_LENGTH, CONF_UART_PARITY, CONF_UART_STOP_BITS, CONSOLE_UART_ID, stdio_serial_init(), and sysclk_enable_peripheral_clock().
Referenced by main().
configure_rtt()
void configure_rtt (void)
RTT configuration function.
Configure the RTT to generate a one second tick, which triggers the RTTINC interrupt.
Definition at line 647 of file main.c.
{
    /* Configure RTT for a 1 second tick interrupt */
    rtt_sel_source(RTT, false);
    rtt_init(RTT, 32768);
    /* Enable RTT interrupt */
    NVIC_DisableIRQ(RTT_IRQn);
    NVIC_ClearPendingIRQ(RTT_IRQn);
    NVIC_SetPriority(RTT_IRQn, 0);
    NVIC_EnableIRQ(RTT_IRQn);
    rtt_enable_interrupt(RTT, RTT_MR_RTTINCIEN);
}
References RTT, rtt_enable_interrupt(), rtt_init(), RTT_IRQn, and RTT_MR_RTTINCIEN.
Referenced by resolve_cb().
ili9488_draw_number()
void ili9488_draw_number (uint32_t ul_x, uint32_t ul_y, uint8_t index)
Definition at line 486 of file main_image.c.
{
    uint32_t row, col, i;
    uint32_t offset;
    offset = ((uint32_t)index) * (48 * 48 / 8);
    for(row = 0; row < 6; row++) {
        for(col = 0; col < 48; col++) {
            for (i = 0; i < 8; i++) {
                if ((p_uc_numberset48x48[offset] >> i) & 0x1) {
                    ili9488_draw_pixel(ul_x + col, ul_y + 8 * row + i);
                }
            }
            offset++;
        }
    }
}
References ili9488_draw_pixel(), and p_uc_numberset48x48.
Referenced by ili9488_draw_temperature().
ili9488_draw_temperature()
void ili9488_draw_temperature (uint32_t ul_x, uint32_t ul_y, char * temperature)
Definition at line 505 of file main_image.c.
{
    float temp_value_f = atof(temperature);
    int32_t temp_value_n;
    uint8_t index = 0;
    if(temp_value_f < 0.000001) {
        ili9488_draw_number(ul_x, ul_y, 11);
        index++;
        temp_value_n = (int32_t)(temp_value_f - 0.5);
        temp_value_n = -temp_value_n;
    } else {
        temp_value_n = (int32_t)(temp_value_f + 0.5);
    }
    ul_x += 40;
    if(temp_value_n >= 10 && temp_value_n < 100) {
        ili9488_draw_number(ul_x, ul_y, temp_value_n/10);
        ul_x += 40;
        ili9488_draw_number(ul_x, ul_y, temp_value_n%10);
        ul_x += 40;
    } else {
        ili9488_draw_number(ul_x, ul_y, temp_value_n);
        ul_x += 40;
    }
    ili9488_draw_number(ul_x, ul_y, 10);
}
References ili9488_draw_number().
Referenced by refresh_display().
main()
int main (void)
Main application function.
Initialize system, UART console, network then start weather client.
Returns
Program return value.
Definition at line 669 of file main.c.
{
    struct sockaddr_in addr_in;
    /* Initialize the board. */
    sysclk_init();
    board_init();
    ioport_init();
    /* Initialize the UART console. */
    configure_console();
    printf(STRING_HEADER);
    /* Set direction and pullup on the given button IOPORT */
    ioport_set_pin_dir(GPIO_PUSH_BUTTON_1, IOPORT_DIR_INPUT);
    ioport_set_pin_mode(GPIO_PUSH_BUTTON_1, IOPORT_MODE_PULLUP);
    /* Initialize display parameter */
    g_ili9488_display_opt.ul_width = ILI9488_LCD_WIDTH;
    g_ili9488_display_opt.ul_height = ILI9488_LCD_HEIGHT;
    g_ili9488_display_opt.foreground_color = COLOR_CONVERT(COLOR_WHITE);
    g_ili9488_display_opt.background_color = COLOR_CONVERT(COLOR_WHITE);
    /* Initialize LCD */
    ili9488_init(&g_ili9488_display_opt);
    ili9488_draw_filled_rectangle(0, 0, ILI9488_LCD_WIDTH-1, ILI9488_LCD_HEIGHT-1);
    ili9488_set_foreground_color(COLOR_CONVERT(0x0078C0));
    ili9488_draw_filled_rectangle(0, 0, ILI9488_LCD_WIDTH-1, 120-1);
    ili9488_draw_filled_rectangle(0, 360, ILI9488_LCD_WIDTH-1, 480-1);
    ili9488_draw_pixmap(80, 200, 156, 76, gImage_atmel_18bit);
    wifi_init();
    wifi_connect();
    ili9488_set_foreground_color(COLOR_CONVERT(COLOR_WHITE));
    ili9488_draw_filled_rectangle(0, 300, ILI9488_LCD_WIDTH-1, 315);
    ili9488_set_foreground_color(COLOR_CONVERT(COLOR_BLACK));
    ili9488_draw_string(10, 300, (uint8_t *)"Connecting......");
    while (1) {
        wifi_handle_events();
        if (gbConnectedWifi && !gbTcpConnection) {
            if (gbHostIpByName) {
                /* Open TCP client socket. */
                if (tcp_client_socket < 0) {
                    if ((tcp_client_socket = socket(AF_INET, SOCK_STREAM, 0)) < 0) {
                        printf("main: failed to create TCP client socket error!\r\n");
                        continue;
                    }
                }
                /* Connect TCP client socket. */
                addr_in.sin_family = AF_INET;
                addr_in.sin_port = _htons(MAIN_SERVER_PORT);
                addr_in.sin_addr.s_addr = gu32HostIp;
                if (connect(tcp_client_socket, (struct sockaddr *)&addr_in, sizeof(struct sockaddr_in)) != SOCK_ERR_NO_ERROR) {
                    printf("main: failed to connect socket error!\r\n");
                    continue;
                }
                gbTcpConnection = true;
            }
        }
        if(gbFinishedGetWeather)
        {
            wifi_recieve_packet();
            refresh_display();
            gbFinishedGetWeather = false;
        }
        if((g_ul_sec_ticks == 60) || (gbRequireWeather == true)) {
            if(city_is_sha) {
                wifi_require_weather("Shanghai");
                city_is_sha = false;
                display_is_sha = true;
            } else {
                wifi_require_weather("seoul");
                city_is_sha = true;
                display_is_sha = false;
            }
            g_ul_sec_ticks = 0;
            gbRequireWeather = false;
        }
    }
    return 0;
}
References _htons, AF_INET, ili9488_opt_t::background_color, board_init(), city_is_sha, COLOR_BLACK, COLOR_CONVERT, COLOR_WHITE, configure_console(), connect(), display_is_sha, ili9488_opt_t::foreground_color, g_ili9488_display_opt, g_ul_sec_ticks, gbConnectedWifi, gbFinishedGetWeather, gbHostIpByName, gbRequireWeather, gbTcpConnection, gImage_atmel_18bit, GPIO_PUSH_BUTTON_1, gu32HostIp, ili9488_draw_filled_rectangle(), ili9488_draw_pixmap(), ili9488_draw_string(), ili9488_init(), ILI9488_LCD_HEIGHT, ILI9488_LCD_WIDTH, ili9488_set_foreground_color(), IOPORT_DIR_INPUT, ioport_init(), IOPORT_MODE_PULLUP, ioport_set_pin_dir(), ioport_set_pin_mode(), MAIN_SERVER_PORT, refresh_display(), in_addr::s_addr, sockaddr_in::sin_addr, sockaddr_in::sin_family, sockaddr_in::sin_port, SOCK_ERR_NO_ERROR, SOCK_STREAM, socket(), STRING_HEADER, sysclk_init(), tcp_client_socket, ili9488_opt_t::ul_height, ili9488_opt_t::ul_width, wifi_connect(), wifi_handle_events(), wifi_init(), wifi_recieve_packet(), and wifi_require_weather().
parse_weather_icon()
static uint8_t parse_weather_icon (char * pcWeather) static
Definition at line 457 of file main.c.
{
    char *pcStartPtr;
    char *pcEndPtr;
    pcStartPtr = pcWeather;
    pcEndPtr = strstr(pcStartPtr, "cloud");
    if(pcEndPtr != NULL) {
        return 1;
    }
    pcStartPtr = pcWeather;
    pcEndPtr = strstr(pcStartPtr, "rain");
    if(pcEndPtr != NULL) {
        return 2;
    }
    pcStartPtr = pcWeather;
    pcEndPtr = strstr(pcStartPtr, "snow");
    if(pcEndPtr != NULL) {
        return 3;
    }
    return 0;
}
References NULL, and pcWeather.
Referenced by wifi_recieve_packet().
refresh_display()
static void refresh_display () static
Definition at line 597 of file main.c.
{
    ili9488_set_foreground_color(COLOR_CONVERT(COLOR_WHITE));
    ili9488_draw_filled_rectangle(0, 0, ILI9488_LCD_WIDTH-1, ILI9488_LCD_HEIGHT-1);
    ili9488_set_foreground_color(COLOR_CONVERT(0x0078C0));
    ili9488_draw_filled_rectangle(0, 120, ILI9488_LCD_WIDTH-1, 360-1);
    if(display_is_sha) {
        ili9488_draw_pixmap(30, 180, 120, 120, gWeatherIcon[ucWeatherNum_sha]);
        ili9488_draw_pixmap(159, 120, 160, 60, gImage_shanghai);
        ili9488_set_foreground_color(COLOR_CONVERT(COLOR_WHITE));
        ili9488_draw_temperature(150, 220, (uint8_t *)Temperature_sha);
        ili9488_draw_string(60, 320, (uint8_t *)Weather_sha);
    } else {
        ili9488_draw_pixmap(30, 180, 120, 120, gWeatherIcon[ucWeatherNum_seoul]);
        ili9488_draw_pixmap(159, 120, 160, 60, gImage_seoul);
        ili9488_set_foreground_color(COLOR_CONVERT(COLOR_WHITE));
        ili9488_draw_temperature(150, 220, (uint8_t *)Temperature_seoul);
        ili9488_draw_string(60, 320, (uint8_t *)Weather_seoul);
    }
    ili9488_set_foreground_color(COLOR_CONVERT(COLOR_BLACK));
    ili9488_draw_string(10, 10, (uint8_t *)"openweathermap.org");
}
References COLOR_BLACK, COLOR_CONVERT, COLOR_WHITE, display_is_sha, gImage_seoul, gImage_shanghai, gWeatherIcon, ili9488_draw_filled_rectangle(), ili9488_draw_pixmap(), ili9488_draw_string(), ili9488_draw_temperature(), ILI9488_LCD_HEIGHT, ILI9488_LCD_WIDTH, ili9488_set_foreground_color(), Temperature_seoul, Temperature_sha, ucWeatherNum_seoul, ucWeatherNum_sha, Weather_seoul, and Weather_sha.
Referenced by main().
resolve_cb()
static void resolve_cb (uint8_t * hostName, uint32_t hostIp) static
Callback function of IP address.
Parameters
[in] hostName Domain name.
[in] hostIp Server IP.
Returns
None.
Definition at line 180 of file main.c.
{
    gu32HostIp = hostIp;
    gbHostIpByName = true;
    printf("Host IP is %d.%d.%d.%d\r\n", (int)IPV4_BYTE(hostIp, 0), (int)IPV4_BYTE(hostIp, 1),
            (int)IPV4_BYTE(hostIp, 2), (int)IPV4_BYTE(hostIp, 3));
    printf("Host Name is %s\r\n", hostName);
    //ili9488_set_foreground_color(COLOR_CONVERT(COLOR_WHITE));
    //ili9488_draw_filled_rectangle(0, 300, ILI9488_LCD_WIDTH-1, 315);
    //ili9488_set_foreground_color(COLOR_CONVERT(COLOR_BLACK));
    //ili9488_draw_string(10, 300, (uint8_t *)"Push button");
    configure_rtt();
    //pio_enable_interrupt(PIN_PUSHBUTTON_1_PIO, PIN_PUSHBUTTON_1_MASK);
}
References configure_rtt(), gbHostIpByName, gu32HostIp, and IPV4_BYTE.
Referenced by wifi_init().
RTT_Handler()
void RTT_Handler (void)
Interrupt handler for the RTT.
Display the current time on the terminal.
Definition at line 628 of file main.c.
{
    uint32_t ul_status;
    /* Get RTT status */
    ul_status = rtt_get_status(RTT);
    /* Time has changed, refresh display */
    if ((ul_status & RTT_SR_RTTINC) == RTT_SR_RTTINC) {
        g_ul_sec_ticks++;
    }
}
References g_ul_sec_ticks, RTT, rtt_get_status(), and RTT_SR_RTTINC.
socket_cb()
static void socket_cb (SOCKET sock, uint8_t u8Msg, void * pvMsg) static
Callback function of TCP client socket.
Parameters
[in] sock socket handler.
[in] u8Msg Type of Socket notification
[in] pvMsg A structure contains notification informations.
Returns
None.
Definition at line 204 of file main.c.
{
    /* Check for socket event on TCP socket. */
    if (sock == tcp_client_socket) {
        switch (u8Msg) {
        case SOCKET_MSG_CONNECT:
        {
            if (gbTcpConnection) {
                tstrSocketConnectMsg *pstrConnect = (tstrSocketConnectMsg *)pvMsg;
                if (pstrConnect && pstrConnect->s8Error >= SOCK_ERR_NO_ERROR) {
                    gbRequireWeather = true;
                    //g_ul_sec_ticks = 58;
                } else {
                    printf("socket_cb: connect error!\r\n");
                    g_ul_sec_ticks = 0;
                    gbRequireWeather = false;
                    gbTcpConnection = false;
                    close(tcp_client_socket);
                    tcp_client_socket = -1;
                }
            }
        }
        break;
        case SOCKET_MSG_RECV:
        {
            tstrSocketRecvMsg *pstrRecv = (tstrSocketRecvMsg *)pvMsg;
            if (pstrRecv && pstrRecv->s16BufferSize > 0) {
                strcpy(gcWeatherInfo, (char *)pstrRecv->pu8Buffer);
                gbFinishedGetWeather = true;
            } else {
                printf("socket_cb: recv error!\r\n");
                g_ul_sec_ticks = 0;
                gbRequireWeather = false;
                gbTcpConnection = false;
                close(tcp_client_socket);
                tcp_client_socket = -1;
            }
        }
        break;
        default:
            break;
        }
    }
}
References close(), g_ul_sec_ticks, gbFinishedGetWeather, gbRequireWeather, gbTcpConnection, gcWeatherInfo, tstrSocketRecvMsg::pu8Buffer, tstrSocketRecvMsg::s16BufferSize, tstrSocketConnectMsg::s8Error, SOCK_ERR_NO_ERROR, SOCKET_MSG_CONNECT, SOCKET_MSG_RECV, and tcp_client_socket.
Referenced by wifi_init().
wifi_cb()
static void wifi_cb (uint8_t u8MsgType, void * pvMsg) static
Callback to get the Wi-Fi status update.
Parameters
[in] u8MsgType Type of Wi-Fi notification.
[in] pvMsg A pointer to a buffer containing the notification parameters.
Returns
None.
Definition at line 260 of file main.c.
{
    switch (u8MsgType) {
    case M2M_WIFI_RESP_CON_STATE_CHANGED:
    {
        tstrM2mWifiStateChanged *pstrWifiState = (tstrM2mWifiStateChanged *)pvMsg;
        if (pstrWifiState->u8CurrState == M2M_WIFI_CONNECTED) {
            printf("Wi-Fi connected\r\n");
            m2m_wifi_request_dhcp_client();
        } else if (pstrWifiState->u8CurrState == M2M_WIFI_DISCONNECTED) {
            printf("Wi-Fi disconnected\r\n");
            printf("Please reconnect Wi-Fi\r\n");
            gbConnectedWifi = false;
            wifi_connect();
        }
        break;
    }
    case M2M_WIFI_REQ_DHCP_CONF:
    {
        uint8_t *pu8IPAddress = (uint8_t *)pvMsg;
        /* Turn LED0 on to declare that IP address received. */
        printf("Wi-Fi IP is %u.%u.%u.%u\r\n",
                pu8IPAddress[0], pu8IPAddress[1], pu8IPAddress[2], pu8IPAddress[3]);
        gbConnectedWifi = true;
        /* Obtain the IP Address by network name */
        gethostbyname((uint8_t *)server_host_name);
        break;
    }
    default:
    {
        break;
    }
    }
}
References gbConnectedWifi, gethostbyname(), M2M_WIFI_CONNECTED, M2M_WIFI_DISCONNECTED, M2M_WIFI_REQ_DHCP_CONF, m2m_wifi_request_dhcp_client(), M2M_WIFI_RESP_CON_STATE_CHANGED, server_host_name, tstrM2mWifiStateChanged::u8CurrState, and wifi_connect().
Referenced by wifi_init().
wifi_connect()
void wifi_connect (void)
Definition at line 323 of file main.c.
{
    char wlan_ssid[32];
    char wlan_pwd[32];
    uint8_t c;
    uint32_t i;
    volatile uint8_t ssid_length = 0;
    volatile uint8_t pwd_length = 0;
    uint8_t page_buffer[IFLASH_PAGE_SIZE];
    uint32_t page_addr = IFLASH_ADDR + IFLASH_SIZE - IFLASH_PAGE_SIZE;
    uint8_t *p_page_addr = (uint8_t *)page_addr;
    uint32_t ul_rc;
    bool is_need_input = false;
    for(i = 0; i < 32; i++) {
        wlan_ssid[i] = 0;
        wlan_pwd[i] = 0;
    }
    for(i = 0; i < IFLASH_PAGE_SIZE; i++) {
        page_buffer[i] = p_page_addr[i];
    }
    for(i = 0; i < 11; i++) {
        if(page_buffer[i] != mark[i]) {
            is_need_input = true;
        }
    }
    if(!ioport_get_pin_level(GPIO_PUSH_BUTTON_1)) {
        is_need_input = true;
    }
    if(is_need_input) {
        ili9488_set_foreground_color(COLOR_CONVERT(COLOR_BLACK));
        ili9488_draw_string(10, 300, (uint8_t *)"Input SSID and Password...");
        printf("Please input your WLAN SSID Name.\r\n");
        while (1) {
            scanf("%c", &c);
            if (c == ASCII_BS) {
                printf("%c", ASCII_BS);
                ssid_length--;
                wlan_ssid[ssid_length] = 0;
            } else if(c == ASCII_CR) {
                wlan_ssid[ssid_length] = 0;
                printf("\r\n");
                break;
                } else {
                printf("%c", c);
                wlan_ssid[ssid_length] = c;
                ssid_length++;
            }
        }
        printf("Please input your WLAN Password.\r\n");
        while (1) {
            scanf("%c", &c);
            if (c == ASCII_BS) {
                printf("%c", ASCII_BS);
                pwd_length--;
                wlan_pwd[pwd_length] = 0;
            } else if(c == ASCII_CR) {
                wlan_pwd[pwd_length] = 0;
                printf("\r\n");
                break;
                } else {
                printf("%c", c);
                wlan_pwd[pwd_length] = c;
                pwd_length++;
            }
        }
        for(i = 0; i< 11; i++) {
            page_buffer[i] = mark[i];
        }
        for(i = 0; i < ssid_length; i++) {
            page_buffer[11 + i] = wlan_ssid[i];
        }
        for(i = 0; i < pwd_length; i++) {
            page_buffer[11 + ssid_length + i] = wlan_pwd[i];
        }
        page_buffer[75] = ssid_length;
        page_buffer[76] = pwd_length;
        ul_rc = flash_init(FLASH_ACCESS_MODE_128, 6);
        if (ul_rc != FLASH_RC_OK) {
            printf("-F- Initialization error %lu\n\r", ul_rc);
            return 0;
        }
        printf("-I- Unlocking test page: 0x%08x\r\n", page_addr);
        ul_rc = flash_unlock(page_addr,  page_addr + IFLASH_PAGE_SIZE - 1, 0, 0);
        if (ul_rc != FLASH_RC_OK) {
            printf("-F- Unlock error %lu\n\r", ul_rc);
            return 0;
        }
        ul_rc = flash_erase_sector(page_addr);
        if (ul_rc != FLASH_RC_OK) {
            printf("-F- Flash programming error %lu\n\r", ul_rc);
            return 0;
        }
        ul_rc = flash_write(page_addr, page_buffer, IFLASH_PAGE_SIZE, 0);
        if (ul_rc != FLASH_RC_OK) {
            printf("-F- Flash programming error %lu\n\r", ul_rc);
        return 0;
    }
    }else {
        ssid_length = page_buffer[75];
        pwd_length = page_buffer[76];
        for(i = 0; i < ssid_length; i++) {
            wlan_ssid[i] = page_buffer[11 + i];
        }
        for(i = 0; i < pwd_length; i++) {
            wlan_pwd[i] = page_buffer[11 + ssid_length + i] ;
        }
    }
    printf("Connecting to %s.\r\n", wlan_ssid);
    m2m_wifi_connect((char *)wlan_ssid, ssid_length, MAIN_WLAN_AUTH, (void *)wlan_pwd, M2M_WIFI_CH_ALL);
    //printf("Connecting to %s.\r\n", (char *)MAIN_WLAN_SSID);
    //m2m_wifi_connect((char *)MAIN_WLAN_SSID, sizeof(MAIN_WLAN_SSID), MAIN_WLAN_AUTH, (void *)MAIN_WLAN_PSK, M2M_WIFI_CH_ALL);
}
References ASCII_BS, ASCII_CR, COLOR_BLACK, COLOR_CONVERT, FLASH_ACCESS_MODE_128, flash_init(), FLASH_RC_OK, flash_unlock(), flash_write(), GPIO_PUSH_BUTTON_1, IFLASH_ADDR, IFLASH_PAGE_SIZE, IFLASH_SIZE, ili9488_draw_string(), ili9488_set_foreground_color(), ioport_get_pin_level(), M2M_WIFI_CH_ALL, m2m_wifi_connect(), MAIN_WLAN_AUTH, and mark.
Referenced by main(), and wifi_cb().
wifi_handle_events()
static void wifi_handle_events (void) static
Definition at line 442 of file main.c.
{
    m2m_wifi_handle_events(NULL);
}
References m2m_wifi_handle_events(), and NULL.
Referenced by main().
wifi_init()
static void wifi_init (void) static
Definition at line 298 of file main.c.
{
    tstrWifiInitParam param;
    int8_t ret;
    /* Initialize the BSP. */
    nm_bsp_init();
    /* Initialize Wi-Fi parameters structure. */
    memset((uint8_t *)&param, 0, sizeof(tstrWifiInitParam));
    /* Initialize Wi-Fi driver with data and status callbacks. */
    param.pfAppWifiCb = wifi_cb;
    ret = m2m_wifi_init(&param);
    if (M2M_SUCCESS != ret) {
        printf("main: m2m_wifi_init call error!(%d)\r\n", ret);
        while (1) {
        }
    }
    /* Initialize socket API. */
    socketInit();
    registerSocketCallback(socket_cb, resolve_cb);
}
References M2M_SUCCESS, m2m_wifi_init(), nm_bsp_init(), tstrWifiInitParam::pfAppWifiCb, registerSocketCallback(), resolve_cb(), socket_cb(), socketInit(), and wifi_cb().
Referenced by main().
wifi_recieve_packet()
void wifi_recieve_packet (void)
Definition at line 484 of file main.c.
{
    char *pcIndxPtr;
    char *pcEndPtr;
    if (!gbContinueReceive) {
        /* Get city name */
        pcIndxPtr = strstr(gcWeatherInfo, "name=");
        printf("City: ");
        if (NULL != pcIndxPtr) {
            pcIndxPtr = pcIndxPtr + strlen("name=") + 1;
            pcEndPtr = strstr(pcIndxPtr, "\">");
            if (NULL != pcEndPtr) {
                *pcEndPtr = 0;
            }
            pcCity = pcIndxPtr;
            printf("%s\r\n", pcIndxPtr);
        } else {
            printf("N/A\r\n");
            return;
        }
        /* Get temperature */
        pcIndxPtr = strstr(pcEndPtr + 1, "temperature value");
        printf("Temperature: ");
        if (NULL != pcIndxPtr) {
            pcIndxPtr = pcIndxPtr + strlen("temperature value") + 2;
            pcEndPtr = strstr(pcIndxPtr, "\" ");
            if (NULL != pcEndPtr) {
                *pcEndPtr = 0;
            }
            pcTemperature = pcIndxPtr;
            if(display_is_sha) {
                strcpy(Temperature_sha, pcTemperature);
            } else {
                strcpy(Temperature_seoul, pcTemperature);
            }
            printf("%s\r\n", pcIndxPtr);
        } else {
            printf("N/A\r\n");
            return;
        }
        /* Get weather condition */
        pcIndxPtr = strstr(pcEndPtr + 1, "weather number");
        if (NULL != pcIndxPtr) {
            printf("Weather Condition: ");
            pcIndxPtr = pcIndxPtr + strlen("weather number") + 14;
            pcEndPtr = strstr(pcIndxPtr, "\" ");
            if (NULL != pcEndPtr) {
                *pcEndPtr = 0;
            }
            pcWeather = pcIndxPtr;
            ucWeatherNum = parse_weather_icon(pcWeather);
            if(display_is_sha) {
                strcpy(Weather_sha, pcWeather);
                ucWeatherNum_sha = ucWeatherNum;
            } else {
                strcpy(Weather_seoul, pcWeather);
                ucWeatherNum_seoul = ucWeatherNum;
            }
            printf("%s\r\n", pcIndxPtr);
            gbContinueReceive = false;
            return;
        } else {
            gbContinueReceive = true;
        }
    } else {
        /* Get weather condition */
        pcIndxPtr = strstr(gcWeatherInfo, "weather number");
        printf("Weather Condition: ");
        if (NULL != pcIndxPtr) {
            pcIndxPtr = pcIndxPtr + strlen("weather number") + 14;
            pcEndPtr = strstr(pcIndxPtr, "\" ");
            if (NULL != pcEndPtr) {
                *pcEndPtr = 0;
            }
            pcWeather = pcIndxPtr;
            if(display_is_sha) {
                strcpy(Weather_sha, pcWeather);
            } else {
                strcpy(Weather_seoul, pcWeather);
            }
            printf("%s\r\n", pcIndxPtr);
            gbContinueReceive = false;
            gbTcpConnection = false;
            return;
        } else {
            gbContinueReceive = true;
            printf("N/A\r\n");
        }
    }
    memset(gau8ReceivedBuffer, 0, sizeof(gau8ReceivedBuffer));
    recv(tcp_client_socket, &gau8ReceivedBuffer[0], MAIN_WIFI_M2M_BUFFER_SIZE, 0);
}
References display_is_sha, gau8ReceivedBuffer, gbContinueReceive, gbTcpConnection, gcWeatherInfo, MAIN_WIFI_M2M_BUFFER_SIZE, NULL, parse_weather_icon(), pcCity, pcTemperature, pcWeather, recv(), tcp_client_socket, Temperature_seoul, Temperature_sha, ucWeatherNum, ucWeatherNum_seoul, ucWeatherNum_sha, Weather_seoul, and Weather_sha.
Referenced by main().
wifi_require_weather()
static void wifi_require_weather (char * city_name) static
Definition at line 447 of file main.c.
{
    memset(gau8ReceivedBuffer, 0, sizeof(gau8ReceivedBuffer));
    sprintf((char *)gau8ReceivedBuffer, "%s%s%s%s", MAIN_PREFIX_BUFFER, city_name, MAIN_APP_ID, MAIN_POST_BUFFER);
    send(tcp_client_socket, gau8ReceivedBuffer, strlen((char *)gau8ReceivedBuffer), 0);
    memset(gau8ReceivedBuffer, 0, MAIN_WIFI_M2M_BUFFER_SIZE);
    recv(tcp_client_socket, &gau8ReceivedBuffer[0], MAIN_WIFI_M2M_BUFFER_SIZE, 0);
}
References gau8ReceivedBuffer, MAIN_APP_ID, MAIN_POST_BUFFER, MAIN_PREFIX_BUFFER, MAIN_WIFI_M2M_BUFFER_SIZE, recv(), send(), and tcp_client_socket.
Referenced by main().
Variable Documentation
city_is_sha
bool city_is_sha = true
Definition at line 156 of file main.c.
Referenced by main().
display_is_sha
bool display_is_sha = true
Definition at line 157 of file main.c.
Referenced by main(), refresh_display(), and wifi_recieve_packet().
g_ili9488_display_opt
struct ili9488_opt_t g_ili9488_display_opt
Definition at line 141 of file main.c.
Referenced by main().
g_ul_sec_ticks
uint32_t g_ul_sec_ticks = 0
Definition at line 102 of file main.c.
Referenced by main(), RTT_Handler(), and socket_cb().
gau8ReceivedBuffer
uint8_t gau8ReceivedBuffer[MAIN_WIFI_M2M_BUFFER_SIZE] = {0} static
Receive buffer definition.
Definition at line 108 of file main.c.
Referenced by wifi_recieve_packet(), and wifi_require_weather().
gbConnectedWifi
bool gbConnectedWifi = false static
Wi-Fi status variable.
Definition at line 111 of file main.c.
Referenced by main(), and wifi_cb().
gbContinueReceive
bool gbContinueReceive = false static
Continue Receive status variable.
Definition at line 117 of file main.c.
Referenced by wifi_recieve_packet().
gbFinishedGetWeather
bool gbFinishedGetWeather = false static
Weather client status variable.
Definition at line 128 of file main.c.
Referenced by main(), and socket_cb().
gbHostIpByName
bool gbHostIpByName = false static
Get host IP status variable.
Definition at line 114 of file main.c.
Referenced by main(), and resolve_cb().
gbRequireWeather
bool gbRequireWeather = false static
Definition at line 129 of file main.c.
Referenced by main(), and socket_cb().
gbTcpConnection
bool gbTcpConnection = false static
TCP Connection status variable.
Definition at line 120 of file main.c.
Referenced by main(), socket_cb(), and wifi_recieve_packet().
gcWeatherInfo
char gcWeatherInfo[2048] = {0} static
Definition at line 125 of file main.c.
Referenced by socket_cb(), and wifi_recieve_packet().
gu32HostIp
uint32_t gu32HostIp = 0
IP address of host.
Definition at line 100 of file main.c.
Referenced by main(), and resolve_cb().
gWeatherIcon
char* gWeatherIcon[4]
Initial value:
= {
    gImage_sun,
    gImage_cloud,
    gImage_rain,
    gImage_snow,
}
Definition at line 159 of file main.c.
Referenced by refresh_display().
mark
const uint8_t mark[11] = {'S', 'A', 'M', 'E','7', '0', 'D', 'E', 'M','O'}
Definition at line 165 of file main.c.
Referenced by wifi_connect().
pcCity
char* pcCity = NULL
Definition at line 143 of file main.c.
Referenced by wifi_recieve_packet().
pcTemperature
char* pcTemperature = NULL
Definition at line 144 of file main.c.
Referenced by wifi_recieve_packet().
pcWeather
char* pcWeather = NULL
Definition at line 145 of file main.c.
Referenced by parse_weather_icon(), and wifi_recieve_packet().
server_host_name
char server_host_name[] = MAIN_WEATHER_SERVER_NAME static
Server host name.
Definition at line 123 of file main.c.
Referenced by wifi_cb().
tcp_client_socket
SOCKET tcp_client_socket = -1 static
TCP client socket handlers.
Definition at line 105 of file main.c.
Referenced by main(), socket_cb(), wifi_recieve_packet(), and wifi_require_weather().
Temperature_seoul
char Temperature_seoul[30]
Definition at line 152 of file main.c.
Referenced by refresh_display(), and wifi_recieve_packet().
Temperature_sha
char Temperature_sha[30]
Definition at line 148 of file main.c.
Referenced by refresh_display(), and wifi_recieve_packet().
ucWeatherNum
uint8_t ucWeatherNum = 0
Definition at line 146 of file main.c.
Referenced by wifi_recieve_packet().
ucWeatherNum_seoul
uint8_t ucWeatherNum_seoul
Definition at line 154 of file main.c.
Referenced by refresh_display(), and wifi_recieve_packet().
ucWeatherNum_sha
uint8_t ucWeatherNum_sha
Definition at line 150 of file main.c.
Referenced by refresh_display(), and wifi_recieve_packet().
Weather_seoul
char Weather_seoul[30]
Definition at line 153 of file main.c.
Referenced by refresh_display(), and wifi_recieve_packet().
Weather_sha
char Weather_sha[30]
Definition at line 149 of file main.c.
Referenced by refresh_display(), and wifi_recieve_packet().