WINC1500 Weather Client Demo for SAME70 Xplained: main_image.c File Reference
main_image.c File Reference
SAME70 Weather Client Demo Example.
#include "compiler.h"
#include <string.h>
Functions
void ili9488_draw_number (uint32_t ul_x, uint32_t ul_y, uint8_t index)
uint32_t ili9488_draw_pixel (uint32_t ul_x, uint32_t ul_y)
Draw a pixel on LCD.
void ili9488_draw_string (uint32_t ul_x, uint32_t ul_y, const uint8_t *p_str)
Draw a string on LCD.
void ili9488_draw_temperature (uint32_t ul_x, uint32_t ul_y, char *temperature)
Variables
const uint8_t p_uc_numberset48x48 []
Detailed Description
SAME70 Weather Client Demo Example.
Copyright (c) 2015-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file main_image.c.
Function Documentation
ili9488_draw_number()
void ili9488_draw_number (uint32_t ul_x, uint32_t ul_y, uint8_t index)
Definition at line 486 of file main_image.c.
{
    uint32_t row, col, i;
    uint32_t offset;
    offset = ((uint32_t)index) * (48 * 48 / 8);
    for(row = 0; row < 6; row++) {
        for(col = 0; col < 48; col++) {
            for (i = 0; i < 8; i++) {
                if ((p_uc_numberset48x48[offset] >> i) & 0x1) {
                    ili9488_draw_pixel(ul_x + col, ul_y + 8 * row + i);
                }
            }
            offset++;
        }
    }
}
References ili9488_draw_pixel(), and p_uc_numberset48x48.
Referenced by ili9488_draw_temperature().
ili9488_draw_temperature()
void ili9488_draw_temperature (uint32_t ul_x, uint32_t ul_y, char * temperature)
Definition at line 505 of file main_image.c.
{
    float temp_value_f = atof(temperature);
    int32_t temp_value_n;
    uint8_t index = 0;
    if(temp_value_f < 0.000001) {
        ili9488_draw_number(ul_x, ul_y, 11);
        index++;
        temp_value_n = (int32_t)(temp_value_f - 0.5);
        temp_value_n = -temp_value_n;
    } else {
        temp_value_n = (int32_t)(temp_value_f + 0.5);
    }
    ul_x += 40;
    if(temp_value_n >= 10 && temp_value_n < 100) {
        ili9488_draw_number(ul_x, ul_y, temp_value_n/10);
        ul_x += 40;
        ili9488_draw_number(ul_x, ul_y, temp_value_n%10);
        ul_x += 40;
    } else {
        ili9488_draw_number(ul_x, ul_y, temp_value_n);
        ul_x += 40;
    }
    ili9488_draw_number(ul_x, ul_y, 10);
}
References ili9488_draw_number().
Referenced by refresh_display().
Variable Documentation
p_uc_numberset48x48
const uint8_t p_uc_numberset48x48[]
Definition at line 40 of file main_image.c.
Referenced by ili9488_draw_number().