WINC1500 Weather Client Demo for SAME70 Xplained: nm_bsp_same70.c File Reference
nm_bsp_same70.c File Reference
This module contains SAME70 BSP APIs implementation.
#include "bsp/include/nm_bsp.h"
#include "common/include/nm_common.h"
#include "asf.h"
#include "conf_winc.h"
Functions
static void chip_isr (uint32_t id, uint32_t mask)
static void init_chip_pins (void)
sint8 nm_bsp_deinit (void)
De-iInitialize BSP.
sint8 nm_bsp_init (void)
This function is used to initialize the Board Support Package (BSP) in order to prepare the WINC before any WINC API calls.
void nm_bsp_interrupt_ctrl (uint8 u8Enable)
Enable/Disable interrupts from the WINC.
void nm_bsp_register_isr (tpfNmBspIsr pfIsr)
Register the host interface interrupt service routine.
void nm_bsp_reset (void)
Reset WINC1500 SoC by setting CHIP_EN and RESET_N signals low, CHIP_EN high then RESET_N high.
void nm_bsp_sleep (uint32 u32TimeMsec)
Used to put the host to sleep for the specified duration (in milliseconds). Forcing the host to sleep for extended period may lead to host not being able to respond to WINC board events. It is important to be considerate while choosing the sleep period.
Variables
static tpfNmBspIsr gpfIsr
Detailed Description
This module contains SAME70 BSP APIs implementation.
Copyright (c) 2016-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file nm_bsp_same70.c.
Function Documentation
chip_isr()
static void chip_isr (uint32_t id, uint32_t mask) static
Definition at line 42 of file nm_bsp_same70.c.
{
    if ((id == CONF_WINC_SPI_INT_PIO_ID) && (mask == CONF_WINC_SPI_INT_MASK)) {
        if (gpfIsr) {
            gpfIsr();
        }
    }
}
References CONF_WINC_SPI_INT_MASK, CONF_WINC_SPI_INT_PIO_ID, and gpfIsr.
Referenced by nm_bsp_register_isr().
init_chip_pins()
static void init_chip_pins (void) static
Definition at line 55 of file nm_bsp_same70.c.
{
    ioport_init();
    ioport_set_pin_dir(CONF_WINC_PIN_RESET, IOPORT_DIR_OUTPUT);
    ioport_set_pin_level(CONF_WINC_PIN_RESET, IOPORT_PIN_LEVEL_HIGH);
    ioport_set_pin_dir(CONF_WINC_PIN_CHIP_ENABLE, IOPORT_DIR_OUTPUT);
    ioport_set_pin_level(CONF_WINC_PIN_CHIP_ENABLE, IOPORT_PIN_LEVEL_HIGH);
    ioport_set_pin_dir(CONF_WINC_PIN_WAKE, IOPORT_DIR_OUTPUT);
    ioport_set_pin_level(CONF_WINC_PIN_WAKE, IOPORT_PIN_LEVEL_HIGH);
}
References CONF_WINC_PIN_CHIP_ENABLE, CONF_WINC_PIN_RESET, CONF_WINC_PIN_WAKE, IOPORT_DIR_OUTPUT, ioport_init(), IOPORT_PIN_LEVEL_HIGH, ioport_set_pin_dir(), and ioport_set_pin_level().
Referenced by nm_bsp_init().
Variable Documentation
gpfIsr
tpfNmBspIsr gpfIsr static
Definition at line 40 of file nm_bsp_same70.c.
Referenced by chip_isr(), nm_bsp_init(), and nm_bsp_register_isr().