WINC1500 Weather Client Demo for SAME70 Xplained: nm_bus_wrapper.h File Reference
nm_bus_wrapper.h File Reference
This module contains NMC1000 bus wrapper APIs declarations.
#include "common/include/nm_common.h"
Data Structures
struct tstrNmBusCapabilities
Structure holding bus capabilities information.
struct tstrNmI2cDefault
Structure holding I2C default operation parameters.
struct tstrNmI2cSpecial
Structure holding I2C special operation parameters.
struct tstrNmSpiRw
Structure holding SPI R/W parameters.
struct tstrNmUartDefault
Structure holding UART default operation parameters.
Macros
#define NM_BUS_IOCTL_R ((uint8)0)
IOCTL commands.
#define NM_BUS_IOCTL_RW ((uint8)3)
#define NM_BUS_IOCTL_W ((uint8)1)
#define NM_BUS_IOCTL_W_SPECIAL ((uint8)2)
#define NM_BUS_IOCTL_WR_RESTART ((uint8)4)
#define NM_BUS_TYPE_I2C ((uint8)0)
BUS Type.
#define NM_BUS_TYPE_SPI ((uint8)1)
#define NM_BUS_TYPE_UART ((uint8)2)
Functions
sint8 nm_bus_deinit (void)
De-initialize the bus wrapper.
sint8 nm_bus_init (void *)
sint8 nm_bus_ioctl (uint8 u8Cmd, void *pvParameter)
sint8 nm_bus_reinit (void *)
Variables
tstrNmBusCapabilities egstrNmBusCapabilities
Detailed Description
This module contains NMC1000 bus wrapper APIs declarations.
Copyright (c) 2016-2021 Microchip Technology Inc. and its subsidiaries.
Definition in file nm_bus_wrapper.h.
Macro Definition Documentation
NM_BUS_IOCTL_R
#define NM_BUS_IOCTL_R ((uint8)0)
IOCTL commands.
Read only ==> I2C/UART. Parameter:tstrNmI2cDefault/tstrNmUartDefault
Definition at line 49 of file nm_bus_wrapper.h.
NM_BUS_IOCTL_RW
#define NM_BUS_IOCTL_RW ((uint8)3)
Read/Write at the same time ==> SPI only. Parameter:tstrNmSpiRw
Definition at line 53 of file nm_bus_wrapper.h.
NM_BUS_IOCTL_W
#define NM_BUS_IOCTL_W ((uint8)1)
Write only ==> I2C/UART. Parameter type tstrNmI2cDefault/tstrNmUartDefault
Definition at line 50 of file nm_bus_wrapper.h.
NM_BUS_IOCTL_W_SPECIAL
#define NM_BUS_IOCTL_W_SPECIAL ((uint8)2)
Write two buffers within the same transaction (same start/stop conditions) ==> I2C only. Parameter:tstrNmI2cSpecial
Definition at line 52 of file nm_bus_wrapper.h.
NM_BUS_IOCTL_WR_RESTART
#define NM_BUS_IOCTL_WR_RESTART ((uint8)4)
Write buffer then made restart condition then read ==> I2C only. parameter:tstrNmI2cSpecial
Definition at line 55 of file nm_bus_wrapper.h.
NM_BUS_TYPE_I2C
#define NM_BUS_TYPE_I2C ((uint8)0)
BUS Type.
Definition at line 43 of file nm_bus_wrapper.h.
NM_BUS_TYPE_SPI
#define NM_BUS_TYPE_SPI ((uint8)1)
Definition at line 44 of file nm_bus_wrapper.h.
NM_BUS_TYPE_UART
#define NM_BUS_TYPE_UART ((uint8)2)
Definition at line 45 of file nm_bus_wrapper.h.
Function Documentation
nm_bus_deinit()
sint8 nm_bus_deinit (void)
De-initialize the bus wrapper.
Returns
ZERO in case of success and M2M_ERR_BUS_FAIL in case of failure
Definition at line 273 of file nm_bus_wrapper_same70.c.
{
    sint8 result = M2M_SUCCESS;
#ifdef CONF_WINC_USE_I2C
    //TODO:
#endif /* CONF_WINC_USE_I2C */
#ifdef CONF_WINC_USE_SPI
    spi_disable(CONF_WINC_SPI);
    ioport_set_pin_dir(CONF_WINC_SPI_MOSI_GPIO, IOPORT_DIR_INPUT);
    ioport_set_pin_dir(CONF_WINC_SPI_MISO_GPIO, IOPORT_DIR_INPUT);
    ioport_set_pin_dir(CONF_WINC_SPI_CLK_GPIO, IOPORT_DIR_INPUT);
    ioport_set_pin_dir(CONF_WINC_SPI_CS_GPIO, IOPORT_DIR_INPUT);
#endif /* CONF_WINC_USE_SPI */
    return result;
}
References CONF_WINC_SPI, CONF_WINC_SPI_CLK_GPIO, CONF_WINC_SPI_CS_GPIO, CONF_WINC_SPI_MISO_GPIO, CONF_WINC_SPI_MOSI_GPIO, IOPORT_DIR_INPUT, ioport_set_pin_dir(), M2M_SUCCESS, and spi_disable().
Referenced by nm_bus_iface_deinit().
nm_bus_init()
sint8 nm_bus_init (void * pvinit)
Definition at line 164 of file nm_bus_wrapper_same70.c.
{
    sint8 result = M2M_SUCCESS;
#ifdef CONF_WINC_USE_I2C
    twihs_options_t opt;
    /* Enable the peripheral clock for TWI */
    pmc_enable_periph_clk(CONF_WINC_I2C_ID);
    /* Configure the options of TWI driver */
    opt.master_clk = sysclk_get_peripheral_hz();
    opt.speed      = CONF_WINC_TWIHS_CLOCK;
    if (twihs_master_init(CONF_WINC_I2C, &opt) != TWIHS_SUCCESS) {
        M2M_ERR("-E-\tTWI master initialization failed.\r");
        while (1) {
            /* Capture error */
        }
    }
#elif CONF_WINC_USE_SPI
    /* Configure SPI pins. */
    ioport_set_pin_mode(CONF_WINC_SPI_MISO_GPIO, CONF_WINC_SPI_MISO_FLAGS);
    ioport_set_pin_mode(CONF_WINC_SPI_MOSI_GPIO, CONF_WINC_SPI_MOSI_FLAGS);
    ioport_set_pin_mode(CONF_WINC_SPI_CLK_GPIO, CONF_WINC_SPI_CLK_FLAGS);
    ioport_set_pin_mode(CONF_WINC_SPI_CS_GPIO, CONF_WINC_SPI_CS_FLAGS);
    ioport_disable_pin(CONF_WINC_SPI_MISO_GPIO);
    ioport_disable_pin(CONF_WINC_SPI_MOSI_GPIO);
    ioport_disable_pin(CONF_WINC_SPI_CLK_GPIO);
    /* Configure CS for manual (GPIO) control. */
    p_pio_cs = (Pio *)((uint32_t)PIOA + (PIO_DELTA * (CONF_WINC_SPI_CS_GPIO >> 5)));
    SPI_DEASSERT_CS();
    ioport_set_pin_dir(CONF_WINC_SPI_CS_GPIO, IOPORT_DIR_OUTPUT);
    ioport_enable_pin(CONF_WINC_SPI_CS_GPIO);
    spi_enable_clock(CONF_WINC_SPI);
    spi_disable(CONF_WINC_SPI);
    spi_reset(CONF_WINC_SPI);
    spi_set_master_mode(CONF_WINC_SPI);
    spi_disable_mode_fault_detect(CONF_WINC_SPI);
    spi_set_peripheral_chip_select_value(CONF_WINC_SPI, CONF_WINC_SPI_NPCS);
    spi_set_clock_polarity(CONF_WINC_SPI,
            CONF_WINC_SPI_NPCS, CONF_WINC_SPI_POL);
    spi_set_clock_phase(CONF_WINC_SPI, CONF_WINC_SPI_NPCS, CONF_WINC_SPI_PHA);
    spi_set_bits_per_transfer(CONF_WINC_SPI, CONF_WINC_SPI_NPCS, SPI_CSR_BITS_8_BIT);
    spi_set_baudrate_div(CONF_WINC_SPI, CONF_WINC_SPI_NPCS,
            (sysclk_get_peripheral_hz() / CONF_WINC_SPI_CLOCK));
    spi_set_transfer_delay(CONF_WINC_SPI, CONF_WINC_SPI_NPCS, CONF_WINC_SPI_DLYBS,
            CONF_WINC_SPI_DLYBCT);
    spi_enable(CONF_WINC_SPI);
    nm_bsp_reset();
    nm_bsp_sleep(1);
#endif
    return result;
}
References CONF_WINC_I2C, CONF_WINC_I2C_ID, CONF_WINC_SPI, CONF_WINC_SPI_CLK_FLAGS, CONF_WINC_SPI_CLK_GPIO, CONF_WINC_SPI_CLOCK, CONF_WINC_SPI_CS_FLAGS, CONF_WINC_SPI_CS_GPIO, CONF_WINC_SPI_DLYBCT, CONF_WINC_SPI_DLYBS, CONF_WINC_SPI_MISO_FLAGS, CONF_WINC_SPI_MISO_GPIO, CONF_WINC_SPI_MOSI_FLAGS, CONF_WINC_SPI_MOSI_GPIO, CONF_WINC_SPI_NPCS, CONF_WINC_SPI_PHA, CONF_WINC_SPI_POL, CONF_WINC_TWIHS_CLOCK, IOPORT_DIR_OUTPUT, ioport_disable_pin(), ioport_enable_pin(), ioport_set_pin_dir(), ioport_set_pin_mode(), M2M_ERR, M2M_SUCCESS, twihs_options::master_clk, nm_bsp_reset(), nm_bsp_sleep(), PIO_DELTA, PIOA, pmc_enable_periph_clk(), twihs_options::speed, SPI_CSR_BITS_8_BIT, spi_disable(), spi_disable_mode_fault_detect(), spi_enable(), spi_enable_clock(), spi_reset(), spi_set_baudrate_div(), spi_set_bits_per_transfer(), spi_set_clock_phase(), spi_set_clock_polarity(), spi_set_master_mode(), spi_set_peripheral_chip_select_value(), spi_set_transfer_delay(), sysclk_get_peripheral_hz(), twihs_master_init(), and TWIHS_SUCCESS.
Referenced by nm_bus_iface_init().
nm_bus_ioctl()
sint8 nm_bus_ioctl (uint8 u8Cmd, void * pvParameter)
Definition at line 232 of file nm_bus_wrapper_same70.c.
{
    sint8 s8Ret = 0;
    switch(u8Cmd)
    {
#ifdef CONF_WINC_USE_I2C
        case NM_BUS_IOCTL_R: {
            tstrNmI2cDefault *pstrParam = (tstrNmI2cDefault *)pvParameter;
            s8Ret = nm_i2c_read(pstrParam->pu8Buf, pstrParam->u16Sz);
        }
        break;
        case NM_BUS_IOCTL_W: {
            tstrNmI2cDefault *pstrParam = (tstrNmI2cDefault *)pvParameter;
            s8Ret = nm_i2c_write(pstrParam->pu8Buf, pstrParam->u16Sz);
        }
        break;
        case NM_BUS_IOCTL_W_SPECIAL: {
            tstrNmI2cSpecial *pstrParam = (tstrNmI2cSpecial *)pvParameter;
            s8Ret = nm_i2c_write_special(pstrParam->pu8Buf1, pstrParam->u16Sz1, pstrParam->pu8Buf2, pstrParam->u16Sz2);
        }
        break;
#elif CONF_WINC_USE_SPI
        case NM_BUS_IOCTL_RW: {
            tstrNmSpiRw *pstrParam = (tstrNmSpiRw *)pvParameter;
            s8Ret = nm_spi_rw(pstrParam->pu8InBuf, pstrParam->pu8OutBuf, pstrParam->u16Sz);
        }
        break;
#endif
        default:
            s8Ret = -1;
            M2M_ERR("Invalid IOCTL command!\n");
            break;
    }
    return s8Ret;
}
References M2M_ERR, NM_BUS_IOCTL_R, NM_BUS_IOCTL_RW, NM_BUS_IOCTL_W, NM_BUS_IOCTL_W_SPECIAL, nm_i2c_read(), nm_i2c_write(), nm_i2c_write_special(), tstrNmI2cDefault::pu8Buf, tstrNmI2cSpecial::pu8Buf1, tstrNmI2cSpecial::pu8Buf2, tstrNmSpiRw::pu8InBuf, tstrNmSpiRw::pu8OutBuf, tstrNmI2cDefault::u16Sz, tstrNmSpiRw::u16Sz, tstrNmI2cSpecial::u16Sz1, and tstrNmI2cSpecial::u16Sz2.
Referenced by nm_i2c_read_block(), nm_i2c_read_reg_with_ret(), nm_i2c_write_block(), and nm_i2c_write_reg().
nm_bus_reinit()
sint8 nm_bus_reinit (void *)
Variable Documentation
egstrNmBusCapabilities
tstrNmBusCapabilities egstrNmBusCapabilities extern
Definition at line 44 of file nm_bus_wrapper_same70.c.
Referenced by nm_read_block(), and nm_write_block().