WINC1500 Weather Client Demo for SAME70 Xplained: nm_bus_wrapper_same70.c File Reference
nm_bus_wrapper_same70.c File Reference
This module contains NMC1000 bus wrapper APIs implementation.
#include <stdio.h>
#include "bsp/include/nm_bsp.h"
#include "common/include/nm_common.h"
#include "bus_wrapper/include/nm_bus_wrapper.h"
#include "asf.h"
#include "conf_winc.h"
Macros
#define I2C_TIMEOUT 100
Number of times to try to send packet if failed.
#define NM_BUS_MAX_TRX_SZ 4096
#define SLAVE_ADDRESS 0x60
Functions
sint8 nm_bus_deinit (void)
De-initialize the bus wrapper.
sint8 nm_bus_init (void *pvinit)
sint8 nm_bus_ioctl (uint8 u8Cmd, void *pvParameter)
static sint8 nm_i2c_read (uint8 *rb, uint16 sz)
static sint8 nm_i2c_write (uint8 *b, uint16 sz)
static sint8 nm_i2c_write_special (uint8 *wb1, uint16 sz1, uint8 *wb2, uint16 sz2)
Variables
tstrNmBusCapabilities egstrNmBusCapabilities
Detailed Description
This module contains NMC1000 bus wrapper APIs implementation.
Copyright (c) 2016-2021 Microchip Technology Inc. and its subsidiaries.
Definition in file nm_bus_wrapper_same70.c.
Macro Definition Documentation
I2C_TIMEOUT
#define I2C_TIMEOUT 100
Number of times to try to send packet if failed.
Definition at line 53 of file nm_bus_wrapper_same70.c.
NM_BUS_MAX_TRX_SZ
#define NM_BUS_MAX_TRX_SZ 4096
Definition at line 42 of file nm_bus_wrapper_same70.c.
SLAVE_ADDRESS
#define SLAVE_ADDRESS 0x60
Definition at line 50 of file nm_bus_wrapper_same70.c.
Function Documentation
nm_bus_deinit()
nm_bus_deinit (void)
De-initialize the bus wrapper.
Returns
ZERO in case of success and M2M_ERR_BUS_FAIL in case of failure
Definition at line 273 of file nm_bus_wrapper_same70.c.
{
    sint8 result = M2M_SUCCESS;
#ifdef CONF_WINC_USE_I2C
    //TODO:
#endif /* CONF_WINC_USE_I2C */
#ifdef CONF_WINC_USE_SPI
    spi_disable(CONF_WINC_SPI);
    ioport_set_pin_dir(CONF_WINC_SPI_MOSI_GPIO, IOPORT_DIR_INPUT);
    ioport_set_pin_dir(CONF_WINC_SPI_MISO_GPIO, IOPORT_DIR_INPUT);
    ioport_set_pin_dir(CONF_WINC_SPI_CLK_GPIO, IOPORT_DIR_INPUT);
    ioport_set_pin_dir(CONF_WINC_SPI_CS_GPIO, IOPORT_DIR_INPUT);
#endif /* CONF_WINC_USE_SPI */
    return result;
}
References CONF_WINC_SPI, CONF_WINC_SPI_CLK_GPIO, CONF_WINC_SPI_CS_GPIO, CONF_WINC_SPI_MISO_GPIO, CONF_WINC_SPI_MOSI_GPIO, IOPORT_DIR_INPUT, ioport_set_pin_dir(), M2M_SUCCESS, and spi_disable().
Referenced by nm_bus_iface_deinit().
nm_bus_init()
sint8 nm_bus_init (void * pvinit)
Definition at line 164 of file nm_bus_wrapper_same70.c.
{
    sint8 result = M2M_SUCCESS;
#ifdef CONF_WINC_USE_I2C
    twihs_options_t opt;
    /* Enable the peripheral clock for TWI */
    pmc_enable_periph_clk(CONF_WINC_I2C_ID);
    /* Configure the options of TWI driver */
    opt.master_clk = sysclk_get_peripheral_hz();
    opt.speed      = CONF_WINC_TWIHS_CLOCK;
    if (twihs_master_init(CONF_WINC_I2C, &opt) != TWIHS_SUCCESS) {
        M2M_ERR("-E-\tTWI master initialization failed.\r");
        while (1) {
            /* Capture error */
        }
    }
#elif CONF_WINC_USE_SPI
    /* Configure SPI pins. */
    ioport_set_pin_mode(CONF_WINC_SPI_MISO_GPIO, CONF_WINC_SPI_MISO_FLAGS);
    ioport_set_pin_mode(CONF_WINC_SPI_MOSI_GPIO, CONF_WINC_SPI_MOSI_FLAGS);
    ioport_set_pin_mode(CONF_WINC_SPI_CLK_GPIO, CONF_WINC_SPI_CLK_FLAGS);
    ioport_set_pin_mode(CONF_WINC_SPI_CS_GPIO, CONF_WINC_SPI_CS_FLAGS);
    ioport_disable_pin(CONF_WINC_SPI_MISO_GPIO);
    ioport_disable_pin(CONF_WINC_SPI_MOSI_GPIO);
    ioport_disable_pin(CONF_WINC_SPI_CLK_GPIO);
    /* Configure CS for manual (GPIO) control. */
    p_pio_cs = (Pio *)((uint32_t)PIOA + (PIO_DELTA * (CONF_WINC_SPI_CS_GPIO >> 5)));
    SPI_DEASSERT_CS();
    ioport_set_pin_dir(CONF_WINC_SPI_CS_GPIO, IOPORT_DIR_OUTPUT);
    ioport_enable_pin(CONF_WINC_SPI_CS_GPIO);
    spi_enable_clock(CONF_WINC_SPI);
    spi_disable(CONF_WINC_SPI);
    spi_reset(CONF_WINC_SPI);
    spi_set_master_mode(CONF_WINC_SPI);
    spi_disable_mode_fault_detect(CONF_WINC_SPI);
    spi_set_peripheral_chip_select_value(CONF_WINC_SPI, CONF_WINC_SPI_NPCS);
    spi_set_clock_polarity(CONF_WINC_SPI,
            CONF_WINC_SPI_NPCS, CONF_WINC_SPI_POL);
    spi_set_clock_phase(CONF_WINC_SPI, CONF_WINC_SPI_NPCS, CONF_WINC_SPI_PHA);
    spi_set_bits_per_transfer(CONF_WINC_SPI, CONF_WINC_SPI_NPCS, SPI_CSR_BITS_8_BIT);
    spi_set_baudrate_div(CONF_WINC_SPI, CONF_WINC_SPI_NPCS,
            (sysclk_get_peripheral_hz() / CONF_WINC_SPI_CLOCK));
    spi_set_transfer_delay(CONF_WINC_SPI, CONF_WINC_SPI_NPCS, CONF_WINC_SPI_DLYBS,
            CONF_WINC_SPI_DLYBCT);
    spi_enable(CONF_WINC_SPI);
    nm_bsp_reset();
    nm_bsp_sleep(1);
#endif
    return result;
}
References CONF_WINC_I2C, CONF_WINC_I2C_ID, CONF_WINC_SPI, CONF_WINC_SPI_CLK_FLAGS, CONF_WINC_SPI_CLK_GPIO, CONF_WINC_SPI_CLOCK, CONF_WINC_SPI_CS_FLAGS, CONF_WINC_SPI_CS_GPIO, CONF_WINC_SPI_DLYBCT, CONF_WINC_SPI_DLYBS, CONF_WINC_SPI_MISO_FLAGS, CONF_WINC_SPI_MISO_GPIO, CONF_WINC_SPI_MOSI_FLAGS, CONF_WINC_SPI_MOSI_GPIO, CONF_WINC_SPI_NPCS, CONF_WINC_SPI_PHA, CONF_WINC_SPI_POL, CONF_WINC_TWIHS_CLOCK, IOPORT_DIR_OUTPUT, ioport_disable_pin(), ioport_enable_pin(), ioport_set_pin_dir(), ioport_set_pin_mode(), M2M_ERR, M2M_SUCCESS, twihs_options::master_clk, nm_bsp_reset(), nm_bsp_sleep(), PIO_DELTA, PIOA, pmc_enable_periph_clk(), twihs_options::speed, SPI_CSR_BITS_8_BIT, spi_disable(), spi_disable_mode_fault_detect(), spi_enable(), spi_enable_clock(), spi_reset(), spi_set_baudrate_div(), spi_set_bits_per_transfer(), spi_set_clock_phase(), spi_set_clock_polarity(), spi_set_master_mode(), spi_set_peripheral_chip_select_value(), spi_set_transfer_delay(), sysclk_get_peripheral_hz(), twihs_master_init(), and TWIHS_SUCCESS.
Referenced by nm_bus_iface_init().
nm_bus_ioctl()
sint8 nm_bus_ioctl (uint8 u8Cmd, void * pvParameter)
Definition at line 232 of file nm_bus_wrapper_same70.c.
{
    sint8 s8Ret = 0;
    switch(u8Cmd)
    {
#ifdef CONF_WINC_USE_I2C
        case NM_BUS_IOCTL_R: {
            tstrNmI2cDefault *pstrParam = (tstrNmI2cDefault *)pvParameter;
            s8Ret = nm_i2c_read(pstrParam->pu8Buf, pstrParam->u16Sz);
        }
        break;
        case NM_BUS_IOCTL_W: {
            tstrNmI2cDefault *pstrParam = (tstrNmI2cDefault *)pvParameter;
            s8Ret = nm_i2c_write(pstrParam->pu8Buf, pstrParam->u16Sz);
        }
        break;
        case NM_BUS_IOCTL_W_SPECIAL: {
            tstrNmI2cSpecial *pstrParam = (tstrNmI2cSpecial *)pvParameter;
            s8Ret = nm_i2c_write_special(pstrParam->pu8Buf1, pstrParam->u16Sz1, pstrParam->pu8Buf2, pstrParam->u16Sz2);
        }
        break;
#elif CONF_WINC_USE_SPI
        case NM_BUS_IOCTL_RW: {
            tstrNmSpiRw *pstrParam = (tstrNmSpiRw *)pvParameter;
            s8Ret = nm_spi_rw(pstrParam->pu8InBuf, pstrParam->pu8OutBuf, pstrParam->u16Sz);
        }
        break;
#endif
        default:
            s8Ret = -1;
            M2M_ERR("Invalid IOCTL command!\n");
            break;
    }
    return s8Ret;
}
References M2M_ERR, NM_BUS_IOCTL_R, NM_BUS_IOCTL_RW, NM_BUS_IOCTL_W, NM_BUS_IOCTL_W_SPECIAL, nm_i2c_read(), nm_i2c_write(), nm_i2c_write_special(), tstrNmI2cDefault::pu8Buf, tstrNmI2cSpecial::pu8Buf1, tstrNmI2cSpecial::pu8Buf2, tstrNmSpiRw::pu8InBuf, tstrNmSpiRw::pu8OutBuf, tstrNmI2cDefault::u16Sz, tstrNmSpiRw::u16Sz, tstrNmI2cSpecial::u16Sz1, and tstrNmI2cSpecial::u16Sz2.
Referenced by nm_i2c_read_block(), nm_i2c_read_reg_with_ret(), nm_i2c_write_block(), and nm_i2c_write_reg().
nm_i2c_read()
static sint8 nm_i2c_read (uint8 * rb, uint16 sz) static
Definition at line 78 of file nm_bus_wrapper_same70.c.
{
    sint8 result = M2M_SUCCESS;
    twihs_packet_t packet_rx;
    uint16_t timeout = 0;
    /* Configure the data packet to be received */
    packet_rx.chip        = SLAVE_ADDRESS;
    packet_rx.addr[0]     = 0;
    packet_rx.addr[1]     = 0;
    packet_rx.addr[2]     = 0;
    packet_rx.addr_length = 0;
    packet_rx.buffer      = rb;
    packet_rx.length      = sz;
    while (twihs_master_read(CONF_WINC_I2C, &packet_rx) != TWIHS_SUCCESS) {
        if (timeout++ == I2C_TIMEOUT) {
            break;
        }
    }
    return result;
}
References twihs_packet::addr, twihs_packet::addr_length, twihs_packet::buffer, twihs_packet::chip, CONF_WINC_I2C, I2C_TIMEOUT, twihs_packet::length, M2M_SUCCESS, SLAVE_ADDRESS, twihs_master_read(), and TWIHS_SUCCESS.
Referenced by nm_bus_ioctl().
nm_i2c_write()
static sint8 nm_i2c_write (uint8 * b, uint16 sz) static
Definition at line 55 of file nm_bus_wrapper_same70.c.
{
    sint8 result = M2M_SUCCESS;
    twihs_packet_t packet_tx;
    uint16_t timeout = 0;
    /* Configure the data packet to be transmitted */
    packet_tx.chip        = SLAVE_ADDRESS;
    packet_tx.addr[0]     = 0;
    packet_tx.addr[1]     = 0;
    packet_tx.addr[2]     = 0;
    packet_tx.addr_length = 0;
    packet_tx.buffer      = b;
    packet_tx.length      = sz;
    while(twihs_master_write(CONF_WINC_I2C, &packet_tx) != TWIHS_SUCCESS) {
        if (timeout++ == I2C_TIMEOUT) {
            break;
        }
    }
    return result;
}
References twihs_packet::addr, twihs_packet::addr_length, twihs_packet::buffer, twihs_packet::chip, CONF_WINC_I2C, I2C_TIMEOUT, twihs_packet::length, M2M_SUCCESS, SLAVE_ADDRESS, twihs_master_write(), and TWIHS_SUCCESS.
Referenced by nm_bus_ioctl(), and nm_i2c_write_special().
nm_i2c_write_special()
static sint8 nm_i2c_write_special (uint8 * wb1, uint16 sz1, uint8 * wb2, uint16 sz2) static
Definition at line 101 of file nm_bus_wrapper_same70.c.
{
    static uint8 tmp[NM_BUS_MAX_TRX_SZ];
    m2m_memcpy(tmp, wb1, sz1);
    m2m_memcpy(&tmp[sz1], wb2, sz2);
    return nm_i2c_write(tmp, sz1+sz2);
}
References m2m_memcpy(), NM_BUS_MAX_TRX_SZ, and nm_i2c_write().
Referenced by nm_bus_ioctl().
Variable Documentation
egstrNmBusCapabilities
tstrNmBusCapabilities egstrNmBusCapabilities
Initial value:
=
{
    NM_BUS_MAX_TRX_SZ
}
Definition at line 44 of file nm_bus_wrapper_same70.c.
Referenced by nm_read_block(), and nm_write_block().