WINC1500 Weather Client Demo for SAME70 Xplained: nmasic.h File Reference
nmasic.h File Reference
This module contains NMC1500 ASIC specific internal APIs.
#include "common/include/nm_common.h"
Data Structures
struct tstrGpRegs
Macros
#define BOOTROM_REG (0xc000c)
#define EFUSED_MAC(value) (value & 0xffff0000)
#define GET_CHIPID() nmi_get_chipid()
#define ISNMC1000(id) ((((id) & 0xfffff000) == 0x100000) ? 1 : 0)
#define ISNMC1500(id) ((((id) & 0xfffff000) == 0x150000) ? 1 : 0)
#define ISNMC3000(id) ((((id) & 0xfff00000) == 0x300000) ? 1 : 0)
#define M2M_ATE_FW_IS_UP_VALUE (0xD75DC1C3) /*Also, Change this value in ATE (Burst) firmware if it will be changed here*/
#define M2M_ATE_FW_START_VALUE (0x3C1CD57D) /*Also, Change this value in boot_firmware if it will be changed here*/
#define M2M_FINISH_BOOT_ROM 0x10add09eUL
#define M2M_FINISH_INIT_STATE 0x02532636UL
#define M2M_START_FIRMWARE 0xef522f61UL
#define M2M_START_PS_FIRMWARE 0x94992610UL
#define M2M_WAIT_FOR_HOST_REG (0x207bc)
#define NMI_CHIPID (NMI_PERIPH_REG_BASE)
#define NMI_PERIPH_REG_BASE 0x1000
#define NMI_REV_REG (0x207ac) /*Also, Used to load ATE firmware from SPI Flash and to ensure that it is running too*/
#define NMI_REV_REG_ATE (0x1048) /*Revision info register in case of ATE FW*/
#define NMI_STATE_REG (0x108c)
#define REV(id) (((id) & 0x00000fff))
#define REV_2B0 (0x2B0)
#define REV_3A0 (0x3A0)
#define REV_B0 (0x2B0)
#define rHAVE_ETHERNET_MODE_BIT (NBIT7)
#define rHAVE_EXT_PA_INV_TX_RX (NBIT4)
#define rHAVE_LEGACY_RF_SETTINGS (NBIT5)
#define rHAVE_LOGS_DISABLED_BIT (NBIT6)
#define rHAVE_RESERVED1_BIT (NBIT8)
#define rHAVE_RESERVED2_BIT (NBIT9)
#define rHAVE_SDIO_IRQ_GPIO_BIT (NBIT0)
#define rHAVE_SLEEP_CLK_SRC_RTC_BIT (NBIT2)
#define rHAVE_SLEEP_CLK_SRC_XO_BIT (NBIT3)
#define rHAVE_USE_PMU_BIT (NBIT1)
#define rHAVE_XO_XTALGM2_DIS_BIT (NBIT10)
#define rNMI_BOOT_RESET_MUX (0x1118)
#define rNMI_GLB_RESET (0x1400)
#define rNMI_GP_REG_0 (0x149c)
#define rNMI_GP_REG_1 (0x14A0)
#define rNMI_GP_REG_2 (0xc0008)
Functions
sint8 chip_apply_conf (uint32 u32conf)
sint8 chip_deinit (void)
void chip_idle (void)
sint8 chip_reset (void)
sint8 chip_reset_and_cpu_halt (void)
sint8 chip_sleep (void)
sint8 chip_wake (void)
sint8 cpu_halt (void)
sint8 cpu_start (void)
sint8 enable_interrupts (void)
sint8 get_gpio_val (uint8 gpio, uint8 *val)
uint32 nmi_get_chipid (void)
sint8 nmi_get_mac_address (uint8 *pu8MacAddr)
sint8 nmi_get_otp_mac_address (uint8 *pu8MacAddr, uint8 *pu8IsValid)
uint32 nmi_get_rfrevid (void)
void nmi_set_sys_clk_src_to_xo (void)
void nmi_update_pll (void)
sint8 pullup_ctrl (uint32 pinmask, uint8 enable)
void restore_pmu_settings_after_global_reset (void)
sint8 set_gpio_dir (uint8 gpio, uint8 dir)
sint8 set_gpio_val (uint8 gpio, uint8 val)
sint8 wait_for_bootrom (uint8)
sint8 wait_for_firmware_start (uint8)
Detailed Description
This module contains NMC1500 ASIC specific internal APIs.
Copyright (c) 2016-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file nmasic.h.
Macro Definition Documentation
BOOTROM_REG
#define BOOTROM_REG (0xc000c)
Definition at line 47 of file nmasic.h.
EFUSED_MAC
#define EFUSED_MAC (value) (value & 0xffff0000)
Definition at line 67 of file nmasic.h.
GET_CHIPID
#define GET_CHIPID () nmi_get_chipid()
Definition at line 62 of file nmasic.h.
ISNMC1000
#define ISNMC1000 (id) ((((id) & 0xfffff000) == 0x100000) ? 1 : 0)
Definition at line 63 of file nmasic.h.
ISNMC1500
#define ISNMC1500 (id) ((((id) & 0xfffff000) == 0x150000) ? 1 : 0)
Definition at line 64 of file nmasic.h.
ISNMC3000
#define ISNMC3000 (id) ((((id) & 0xfff00000) == 0x300000) ? 1 : 0)
Definition at line 65 of file nmasic.h.
M2M_ATE_FW_IS_UP_VALUE
#define M2M_ATE_FW_IS_UP_VALUE (0xD75DC1C3) /*Also, Change this value in ATE (Burst) firmware if it will be changed here*/
Definition at line 57 of file nmasic.h.
M2M_ATE_FW_START_VALUE
#define M2M_ATE_FW_START_VALUE (0x3C1CD57D) /*Also, Change this value in boot_firmware if it will be changed here*/
Definition at line 56 of file nmasic.h.
M2M_FINISH_BOOT_ROM
#define M2M_FINISH_BOOT_ROM 0x10add09eUL
Definition at line 52 of file nmasic.h.
M2M_FINISH_INIT_STATE
#define M2M_FINISH_INIT_STATE 0x02532636UL
Definition at line 51 of file nmasic.h.
M2M_START_FIRMWARE
#define M2M_START_FIRMWARE 0xef522f61UL
Definition at line 53 of file nmasic.h.
M2M_START_PS_FIRMWARE
#define M2M_START_PS_FIRMWARE 0x94992610UL
Definition at line 54 of file nmasic.h.
M2M_WAIT_FOR_HOST_REG
#define M2M_WAIT_FOR_HOST_REG (0x207bc)
Definition at line 50 of file nmasic.h.
NMI_CHIPID
#define NMI_CHIPID (NMI_PERIPH_REG_BASE)
Definition at line 40 of file nmasic.h.
NMI_PERIPH_REG_BASE
#define NMI_PERIPH_REG_BASE 0x1000
Definition at line 39 of file nmasic.h.
NMI_REV_REG
#define NMI_REV_REG (0x207ac) /*Also, Used to load ATE firmware from SPI Flash and to ensure that it is running too*/
Definition at line 48 of file nmasic.h.
NMI_REV_REG_ATE
#define NMI_REV_REG_ATE (0x1048) /*Revision info register in case of ATE FW*/
Definition at line 49 of file nmasic.h.
NMI_STATE_REG
#define NMI_STATE_REG (0x108c)
Definition at line 46 of file nmasic.h.
REV
#define REV (id) (((id) & 0x00000fff))
Definition at line 66 of file nmasic.h.
REV_2B0
#define REV_2B0 (0x2B0)
Definition at line 59 of file nmasic.h.
REV_3A0
#define REV_3A0 (0x3A0)
Definition at line 61 of file nmasic.h.
REV_B0
#define REV_B0 (0x2B0)
Definition at line 60 of file nmasic.h.
rHAVE_ETHERNET_MODE_BIT
#define rHAVE_ETHERNET_MODE_BIT (NBIT7)
Definition at line 76 of file nmasic.h.
rHAVE_EXT_PA_INV_TX_RX
#define rHAVE_EXT_PA_INV_TX_RX (NBIT4)
Definition at line 73 of file nmasic.h.
rHAVE_LEGACY_RF_SETTINGS
#define rHAVE_LEGACY_RF_SETTINGS (NBIT5)
Definition at line 74 of file nmasic.h.
rHAVE_LOGS_DISABLED_BIT
#define rHAVE_LOGS_DISABLED_BIT (NBIT6)
Definition at line 75 of file nmasic.h.
rHAVE_RESERVED1_BIT
#define rHAVE_RESERVED1_BIT (NBIT8)
Definition at line 77 of file nmasic.h.
rHAVE_RESERVED2_BIT
#define rHAVE_RESERVED2_BIT (NBIT9)
Definition at line 78 of file nmasic.h.
rHAVE_SDIO_IRQ_GPIO_BIT
#define rHAVE_SDIO_IRQ_GPIO_BIT (NBIT0)
Definition at line 69 of file nmasic.h.
rHAVE_SLEEP_CLK_SRC_RTC_BIT
#define rHAVE_SLEEP_CLK_SRC_RTC_BIT (NBIT2)
Definition at line 71 of file nmasic.h.
rHAVE_SLEEP_CLK_SRC_XO_BIT
#define rHAVE_SLEEP_CLK_SRC_XO_BIT (NBIT3)
Definition at line 72 of file nmasic.h.
rHAVE_USE_PMU_BIT
#define rHAVE_USE_PMU_BIT (NBIT1)
Definition at line 70 of file nmasic.h.
rHAVE_XO_XTALGM2_DIS_BIT
#define rHAVE_XO_XTALGM2_DIS_BIT (NBIT10)
Definition at line 79 of file nmasic.h.
rNMI_BOOT_RESET_MUX
#define rNMI_BOOT_RESET_MUX (0x1118)
Definition at line 45 of file nmasic.h.
rNMI_GLB_RESET
#define rNMI_GLB_RESET (0x1400)
Definition at line 44 of file nmasic.h.
rNMI_GP_REG_0
#define rNMI_GP_REG_0 (0x149c)
Definition at line 41 of file nmasic.h.
rNMI_GP_REG_1
#define rNMI_GP_REG_1 (0x14A0)
Definition at line 42 of file nmasic.h.
rNMI_GP_REG_2
#define rNMI_GP_REG_2 (0xc0008)
Definition at line 43 of file nmasic.h.
Function Documentation
chip_apply_conf()
sint8 chip_apply_conf (uint32 u32conf)
Definition at line 58 of file nmasic.c.
{
    sint8 ret = M2M_SUCCESS;
    uint32 val32 = u32Conf;
#if (defined __ENABLE_PMU__) || (defined CONF_WINC_INT_PMU)
    val32 |= rHAVE_USE_PMU_BIT;
#endif
#ifdef __ENABLE_SLEEP_CLK_SRC_RTC__
    val32 |= rHAVE_SLEEP_CLK_SRC_RTC_BIT;
#elif defined __ENABLE_SLEEP_CLK_SRC_XO__
    val32 |= rHAVE_SLEEP_CLK_SRC_XO_BIT;
#endif
#ifdef __ENABLE_EXT_PA_INV_TX_RX__
    val32 |= rHAVE_EXT_PA_INV_TX_RX;
#endif
#ifdef __ENABLE_LEGACY_RF_SETTINGS__
    val32 |= rHAVE_LEGACY_RF_SETTINGS;
#endif
#ifdef __DISABLE_FIRMWARE_LOGS__
    val32 |= rHAVE_LOGS_DISABLED_BIT;
#endif
#if defined CONF_WINC_XO_XTALGM2_DIS
    val32 |= rHAVE_XO_XTALGM2_DIS_BIT;
#endif
    val32 |= rHAVE_RESERVED1_BIT;
    do  {
        nm_write_reg(rNMI_GP_REG_1, val32);
        if(val32 != 0) {
            uint32 reg = 0;
            ret = nm_read_reg_with_ret(rNMI_GP_REG_1, &reg);
            if(ret == M2M_SUCCESS) {
                if(reg == val32)
                    break;
            }
        } else {
            break;
        }
    } while(1);
    return M2M_SUCCESS;
}
References M2M_SUCCESS, nm_read_reg_with_ret(), nm_write_reg(), rHAVE_EXT_PA_INV_TX_RX, rHAVE_LEGACY_RF_SETTINGS, rHAVE_LOGS_DISABLED_BIT, rHAVE_RESERVED1_BIT, rHAVE_SLEEP_CLK_SRC_RTC_BIT, rHAVE_SLEEP_CLK_SRC_XO_BIT, rHAVE_USE_PMU_BIT, rHAVE_XO_XTALGM2_DIS_BIT, and rNMI_GP_REG_1.
Referenced by wait_for_bootrom().
chip_deinit()
sint8 chip_deinit (void)
stop the firmware, need a re-download
Definition at line 503 of file nmasic.c.
{
    uint32 reg = 0;
    sint8 ret;
    ret = nm_read_reg_with_ret(NMI_GLB_RESET_0, &reg);
    if (ret != M2M_SUCCESS) {
        M2M_ERR("failed to de-initialize\n");
        goto ERR1;
    }
    reg &= ~(1 << 10);
    ret = nm_write_reg(NMI_GLB_RESET_0, reg);
    if (ret != M2M_SUCCESS) {
        M2M_ERR("failed to de-initialize\n");
        goto ERR1;
    }
ERR1:
    return ret;
}
References M2M_ERR, M2M_SUCCESS, nm_read_reg_with_ret(), nm_write_reg(), and NMI_GLB_RESET_0.
Referenced by nm_drv_deinit().
chip_idle()
void chip_idle (void)
Definition at line 101 of file nmasic.c.
{
    uint32 reg = 0;
    nm_read_reg_with_ret(WAKE_CLK_REG, &reg);
    if(reg & NBIT1)
    {
        reg &=~ NBIT1;
        nm_write_reg(WAKE_CLK_REG, reg);
    }
}
References NBIT1, nm_read_reg_with_ret(), nm_write_reg(), and WAKE_CLK_REG.
chip_reset()
sint8 chip_reset (void)
Definition at line 388 of file nmasic.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = nm_write_reg(NMI_GLB_RESET_0, 0);
    nm_bsp_sleep(50);
    return ret;
}
References M2M_SUCCESS, nm_bsp_sleep(), nm_write_reg(), and NMI_GLB_RESET_0.
Referenced by chip_reset_and_cpu_halt(), and nm_drv_init_hold().
chip_reset_and_cpu_halt()
sint8 chip_reset_and_cpu_halt (void)
Definition at line 373 of file nmasic.c.
{
    sint8 ret = M2M_SUCCESS;
    /*Wakeup needed only for I2C interface*/
    ret = chip_wake();
    if(ret != M2M_SUCCESS) goto ERR1;
    /*Reset and CPU halt need for no wait board only*/
    ret = chip_reset();
    if(ret != M2M_SUCCESS) goto ERR1;
    ret = cpu_halt();
    if(ret != M2M_SUCCESS) goto ERR1;
ERR1:
    return ret;
}
References chip_reset(), chip_wake(), cpu_halt(), and M2M_SUCCESS.
Referenced by nm_drv_init_download_mode().
chip_sleep()
sint8 chip_sleep (void)
Definition at line 274 of file nmasic.c.
{
    uint32 reg;
    sint8 ret = M2M_SUCCESS;
    while(1)
    {
        ret = nm_read_reg_with_ret(CORT_HOST_COMM,&reg);
        if(ret != M2M_SUCCESS) goto ERR1;
        if((reg & NBIT0) == 0) break;
    }
    /* Clear bit 1 */
    ret = nm_read_reg_with_ret(WAKE_CLK_REG, &reg);
    if(ret != M2M_SUCCESS)goto ERR1;
    if(reg & NBIT1)
    {
        reg &=~NBIT1;
        ret = nm_write_reg(WAKE_CLK_REG, reg);
        if(ret != M2M_SUCCESS)goto ERR1;
    }
    ret = nm_read_reg_with_ret(HOST_CORT_COMM, &reg);
    if(ret != M2M_SUCCESS)goto ERR1;
    if(reg & NBIT0)
    {
        reg &= ~NBIT0;
        ret = nm_write_reg(HOST_CORT_COMM, reg);
        if(ret != M2M_SUCCESS)goto ERR1;
    }
ERR1:
    return ret;
}
References CORT_HOST_COMM, HOST_CORT_COMM, M2M_SUCCESS, NBIT0, NBIT1, nm_read_reg_with_ret(), nm_write_reg(), and WAKE_CLK_REG.
Referenced by hif_chip_sleep().
chip_wake()
sint8 chip_wake (void)
Definition at line 308 of file nmasic.c.
{
    sint8 ret = M2M_SUCCESS;
    uint32 reg = 0, clk_status_reg = 0,trials = 0;
    ret = nm_read_reg_with_ret(HOST_CORT_COMM, &reg);
    if(ret != M2M_SUCCESS)goto _WAKE_EXIT;
    if(!(reg & NBIT0))
    {
        /*USE bit 0 to indicate host wakeup*/
        ret = nm_write_reg(HOST_CORT_COMM, reg|NBIT0);
        if(ret != M2M_SUCCESS)goto _WAKE_EXIT;
    }
    ret = nm_read_reg_with_ret(WAKE_CLK_REG, &reg);
    if(ret != M2M_SUCCESS)goto _WAKE_EXIT;
    /* Set bit 1 */
    if(!(reg & NBIT1))
    {
        ret = nm_write_reg(WAKE_CLK_REG, reg | NBIT1);
        if(ret != M2M_SUCCESS) goto _WAKE_EXIT;
    }
    do
    {
        ret = nm_read_reg_with_ret(CLOCKS_EN_REG, &clk_status_reg);
        if(ret != M2M_SUCCESS) {
            M2M_ERR("Bus error (5).%d %lx\n",ret,clk_status_reg);
            goto _WAKE_EXIT;
        }
        if(clk_status_reg & NBIT2) {
            break;
        }
        nm_bsp_sleep(2);
        trials++;
        if(trials > WAKUP_TRAILS_TIMEOUT)
        {
            M2M_ERR("Failed to wake up the chip\n");
            ret = M2M_ERR_TIME_OUT;
            goto _WAKE_EXIT;
        }
    }while(1);
    /*workaround sometimes spi fail to read clock regs after reading/writing clockless registers*/
    nm_bus_reset();
_WAKE_EXIT:
    return ret;
}
References CLOCKS_EN_REG, HOST_CORT_COMM, M2M_ERR, M2M_ERR_TIME_OUT, M2M_SUCCESS, NBIT0, NBIT1, NBIT2, nm_bsp_sleep(), nm_bus_reset(), nm_read_reg_with_ret(), nm_write_reg(), WAKE_CLK_REG, and WAKUP_TRAILS_TIMEOUT.
Referenced by chip_reset_and_cpu_halt(), hif_chip_wake(), and nm_drv_init_hold().
cpu_halt()
sint8 cpu_halt (void)
Definition at line 358 of file nmasic.c.
{
    sint8 ret;
    uint32 reg = 0;
    ret = nm_read_reg_with_ret(0x1118, &reg);
    reg |= (1 << 0);
    ret += nm_write_reg(0x1118, reg);
    ret += nm_read_reg_with_ret(NMI_GLB_RESET_0, &reg);
    if ((reg & (1ul << 10)) == (1ul << 10)) {
        reg &= ~(1ul << 10);
        ret += nm_write_reg(NMI_GLB_RESET_0, reg);
        ret += nm_read_reg_with_ret(NMI_GLB_RESET_0, &reg);
    }
    return ret;
}
References nm_read_reg_with_ret(), nm_write_reg(), and NMI_GLB_RESET_0.
Referenced by chip_reset_and_cpu_halt().
cpu_start()
sint8 cpu_start (void)
reset regs
Go...
Definition at line 139 of file nmasic.c.
                      {
    uint32 reg = 0;
    sint8 ret;
    ret = nm_write_reg(BOOTROM_REG,0);
    ret += nm_write_reg(NMI_STATE_REG,0);
    ret += nm_write_reg(NMI_REV_REG,0);
    ret += nm_read_reg_with_ret(0x1118, &reg);
    reg |= (1 << 0);
    ret += nm_write_reg(0x1118, reg);
    ret += nm_read_reg_with_ret(NMI_GLB_RESET_0, &reg);
    if ((reg & (1ul << 10)) == (1ul << 10)) {
        reg &= ~(1ul << 10);
        ret += nm_write_reg(NMI_GLB_RESET_0, reg);
    }
    reg |= (1ul << 10);
    ret += nm_write_reg(NMI_GLB_RESET_0, reg);
    nm_bsp_sleep(1);
    return ret;
}
References BOOTROM_REG, nm_bsp_sleep(), nm_read_reg_with_ret(), nm_write_reg(), NMI_GLB_RESET_0, NMI_REV_REG, and NMI_STATE_REG.
enable_interrupts()
sint8 enable_interrupts (void)
interrupt pin mux select
interrupt enable
Definition at line 112 of file nmasic.c.
{
    uint32 reg = 0;
    sint8 ret = M2M_SUCCESS;
    ret = nm_read_reg_with_ret(NMI_PIN_MUX_0, &reg);
    if (M2M_SUCCESS != ret) goto ERR1;
    reg |= ((uint32) 1 << 8);
    ret = nm_write_reg(NMI_PIN_MUX_0, reg);
    if (M2M_SUCCESS != ret) goto ERR1;
    ret = nm_read_reg_with_ret(NMI_INTR_ENABLE, &reg);
    if (M2M_SUCCESS != ret) goto ERR1;
    reg |= ((uint32) 1 << 16);
    ret = nm_write_reg(NMI_INTR_ENABLE, reg);
    if (M2M_SUCCESS != ret) goto ERR1;
ERR1:
    return ret;
}
References M2M_SUCCESS, nm_read_reg_with_ret(), nm_write_reg(), NMI_INTR_ENABLE, and NMI_PIN_MUX_0.
Referenced by m2m_wifi_download_mode(), and nm_drv_init_start().
get_gpio_val()
sint8 get_gpio_val (uint8 gpio, uint8 * val)
nmi_get_chipid()
uint32 nmi_get_chipid (void)
Definition at line 166 of file nmasic.c.
{
    static uint32 chipid = 0;
    if (chipid == 0) {
        uint32 rfrevid;
        if((nm_read_reg_with_ret(0x1000, &chipid)) != M2M_SUCCESS) {
            chipid = 0;
            return 0;
        }
        //if((ret = nm_read_reg_with_ret(0x11fc, &revid)) != M2M_SUCCESS) {
        //  return 0;
        //}
        if((nm_read_reg_with_ret(0x13f4, &rfrevid)) != M2M_SUCCESS) {
            chipid = 0;
            return 0;
        }
        if (chipid == 0x1002a0)  {
            if (rfrevid == 0x1) { /* 1002A0 */
            } else /* if (rfrevid == 0x2) */ { /* 1002A1 */
                chipid = 0x1002a1;
            }
        } else if(chipid == 0x1002b0) {
            if(rfrevid == 3) { /* 1002B0 */
            } else if(rfrevid == 4) { /* 1002B1 */
                chipid = 0x1002b1;
            } else /* if(rfrevid == 5) */ { /* 1002B2 */
                chipid = 0x1002b2;
            }
        }else if(chipid == 0x1000F0) {
            if((nm_read_reg_with_ret(0x3B0000, &chipid)) != M2M_SUCCESS) {
            chipid = 0;
            return 0;
            }
        }else {
        }
//#define PROBE_FLASH
#ifdef PROBE_FLASH
        if(chipid) {
            UWORD32 flashid;
            flashid = probe_spi_flash();
            if(flashid == 0x1230ef) {
                chipid &= ~(0x0f0000);
                chipid |= 0x050000;
            }
            if(flashid == 0xc21320c2) {
                chipid &= ~(0x0f0000);
                chipid |= 0x050000;
            }
        }
#else
        /*M2M is by default have SPI flash*/
        chipid &= ~(0x0f0000);
        chipid |= 0x050000;
#endif /* PROBE_FLASH */
    }
    return chipid;
}
References M2M_SUCCESS, and nm_read_reg_with_ret().
Referenced by nm_drv_init_download_mode(), nm_drv_init_hold(), nm_get_firmware_info(), restore_pmu_settings_after_global_reset(), spi_flash_enable(), and wait_for_bootrom().
nmi_get_mac_address()
sint8 nmi_get_mac_address (uint8 * pu8MacAddr)
Definition at line 638 of file nmasic.c.
{
    sint8 ret;
    uint32  u32RegValue;
    uint8   mac[6];
    tstrGpRegs strgp = {0};
    ret = nm_read_reg_with_ret(rNMI_GP_REG_2, &u32RegValue);
    if(ret != M2M_SUCCESS) goto _EXIT_ERR;
    ret = nm_read_block(u32RegValue|0x30000,(uint8*)&strgp,sizeof(tstrGpRegs));
    if(ret != M2M_SUCCESS) goto _EXIT_ERR;
    u32RegValue = strgp.u32Mac_efuse_mib;
    u32RegValue &=0x0000ffff;
    ret = nm_read_block(u32RegValue|0x30000, mac, 6);
    m2m_memcpy(pu8MacAddr, mac, 6);
    return ret;
_EXIT_ERR:
    return ret;
}
References m2m_memcpy(), M2M_SUCCESS, nm_read_block(), nm_read_reg_with_ret(), rNMI_GP_REG_2, and tstrGpRegs::u32Mac_efuse_mib.
Referenced by m2m_wifi_get_mac_address().
nmi_get_otp_mac_address()
sint8 nmi_get_otp_mac_address (uint8 * pu8MacAddr, uint8 * pu8IsValid)
Definition at line 606 of file nmasic.c.
{
    sint8 ret;
    uint32  u32RegValue;
    uint8   mac[6];
    tstrGpRegs strgp = {0};
    ret = nm_read_reg_with_ret(rNMI_GP_REG_2, &u32RegValue);
    if(ret != M2M_SUCCESS) goto _EXIT_ERR;
    ret = nm_read_block(u32RegValue|0x30000,(uint8*)&strgp,sizeof(tstrGpRegs));
    if(ret != M2M_SUCCESS) goto _EXIT_ERR;
    u32RegValue = strgp.u32Mac_efuse_mib;
    if(!EFUSED_MAC(u32RegValue)) {
        M2M_DBG("Default MAC\n");
        m2m_memset(pu8MacAddr, 0, 6);
        goto _EXIT_ERR;
    }
    M2M_DBG("OTP MAC\n");
    u32RegValue >>=16;
    ret = nm_read_block(u32RegValue|0x30000, mac, 6);
    m2m_memcpy(pu8MacAddr,mac,6);
    if(pu8IsValid) *pu8IsValid = 1;
    return ret;
_EXIT_ERR:
    if(pu8IsValid) *pu8IsValid = 0;
    return ret;
}
References EFUSED_MAC, M2M_DBG, m2m_memcpy(), m2m_memset(), M2M_SUCCESS, nm_read_block(), nm_read_reg_with_ret(), rNMI_GP_REG_2, and tstrGpRegs::u32Mac_efuse_mib.
Referenced by m2m_wifi_get_otp_mac_address().
nmi_get_rfrevid()
uint32 nmi_get_rfrevid (void)
Definition at line 229 of file nmasic.c.
{
    uint32 rfrevid;
    if((nm_read_reg_with_ret(0x13f4, &rfrevid)) != M2M_SUCCESS) {
        rfrevid = 0;
        return 0;
    }
    return rfrevid;
}
References M2M_SUCCESS, and nm_read_reg_with_ret().
nmi_set_sys_clk_src_to_xo()
void nmi_set_sys_clk_src_to_xo (void)
Definition at line 262 of file nmasic.c.
{
    uint32 val32;
    /* Switch system clock source to XO. This will take effect after nmi_update_pll(). */
    val32 = nm_read_reg(0x141c);
    val32 |= (1 << 2);
    nm_write_reg(0x141c, val32);
    /* Do PLL update */
    nmi_update_pll();
}
References nm_read_reg(), nm_write_reg(), and nmi_update_pll().
nmi_update_pll()
void nmi_update_pll (void)
Definition at line 251 of file nmasic.c.
{
    uint32 pll;
    pll = nm_read_reg(0x1428);
    pll &= ~0x1ul;
    nm_write_reg(0x1428, pll);
    pll |= 0x1ul;
    nm_write_reg(0x1428, pll);
}
References nm_read_reg(), and nm_write_reg().
Referenced by nmi_set_sys_clk_src_to_xo().
pullup_ctrl()
sint8 pullup_ctrl (uint32 pinmask, uint8 enable)
restore_pmu_settings_after_global_reset()
void restore_pmu_settings_after_global_reset (void)
Definition at line 239 of file nmasic.c.
{
    /*
    * Must restore PMU register value after
    * global reset if PMU toggle is done at
    * least once since the last hard reset.
    */
    if(REV(nmi_get_chipid()) >= REV_2B0) {
        nm_write_reg(0x1e48, 0xb78469ce);
    }
}
References nm_write_reg(), nmi_get_chipid(), REV, and REV_2B0.
set_gpio_dir()
sint8 set_gpio_dir (uint8 gpio, uint8 dir)
set_gpio_val()
sint8 set_gpio_val (uint8 gpio, uint8 val)
wait_for_bootrom()
sint8 wait_for_bootrom (uint8 arg)
Definition at line 396 of file nmasic.c.
{
    sint8 ret = M2M_SUCCESS;
    uint32 reg = 0, cnt = 0;
    uint32 u32GpReg1 = 0;
    uint32 u32DriverVerInfo = M2M_MAKE_VERSION_INFO(M2M_RELEASE_VERSION_MAJOR_NO,\
                M2M_RELEASE_VERSION_MINOR_NO, M2M_RELEASE_VERSION_PATCH_NO,\
                M2M_MIN_REQ_DRV_VERSION_MAJOR_NO, M2M_MIN_REQ_DRV_VERSION_MINOR_NO,\
                M2M_MIN_REQ_DRV_VERSION_PATCH_NO);
    reg = 0;
    while(1) {
        reg = nm_read_reg(0x1014);  /* wait for efuse loading done */
        if (reg & 0x80000000) {
            break;
        }
        nm_bsp_sleep(1); /* TODO: Why bus error if this delay is not here. */
    }
    reg = nm_read_reg(M2M_WAIT_FOR_HOST_REG);
    reg &= 0x1;
    /* check if waiting for the host will be skipped or not */
    if(reg == 0)
    {
        reg = 0;
        while(reg != M2M_FINISH_BOOT_ROM)
        {
            nm_bsp_sleep(1);
            reg = nm_read_reg(BOOTROM_REG);
            if(++cnt > TIMEOUT)
            {
                M2M_DBG("failed to load firmware from flash.\n");
                ret = M2M_ERR_INIT;
                goto ERR2;
            }
        }
    }
    if(M2M_WIFI_MODE_ATE_HIGH == arg) {
        nm_write_reg(NMI_REV_REG, M2M_ATE_FW_START_VALUE);
        nm_write_reg(NMI_STATE_REG, NBIT20);
    }else if(M2M_WIFI_MODE_ATE_LOW == arg) {
        nm_write_reg(NMI_REV_REG, M2M_ATE_FW_START_VALUE);
        nm_write_reg(NMI_STATE_REG, 0);
    }else if(M2M_WIFI_MODE_ETHERNET == arg){
        u32GpReg1 = rHAVE_ETHERNET_MODE_BIT;
        nm_write_reg(NMI_STATE_REG, u32DriverVerInfo);
    } else {
        /*bypass this step*/
        nm_write_reg(NMI_STATE_REG, u32DriverVerInfo);
    }
    if(REV(nmi_get_chipid()) >= REV_3A0){
        chip_apply_conf(u32GpReg1 | rHAVE_USE_PMU_BIT);
    } else {
        chip_apply_conf(u32GpReg1);
    }
    M2M_INFO("DriverVerInfo: 0x%08lx\n",u32DriverVerInfo);
    nm_write_reg(BOOTROM_REG,M2M_START_FIRMWARE);
#ifdef __ROM_TEST__
    rom_test();
#endif /* __ROM_TEST__ */
ERR2:
    return ret;
}
References BOOTROM_REG, chip_apply_conf(), M2M_ATE_FW_START_VALUE, M2M_DBG, M2M_ERR_INIT, M2M_FINISH_BOOT_ROM, M2M_INFO, M2M_MAKE_VERSION_INFO, M2M_MIN_REQ_DRV_VERSION_MAJOR_NO, M2M_MIN_REQ_DRV_VERSION_MINOR_NO, M2M_MIN_REQ_DRV_VERSION_PATCH_NO, M2M_RELEASE_VERSION_MAJOR_NO, M2M_RELEASE_VERSION_MINOR_NO, M2M_RELEASE_VERSION_PATCH_NO, M2M_START_FIRMWARE, M2M_SUCCESS, M2M_WAIT_FOR_HOST_REG, M2M_WIFI_MODE_ATE_HIGH, M2M_WIFI_MODE_ATE_LOW, M2M_WIFI_MODE_ETHERNET, NBIT20, nm_bsp_sleep(), nm_read_reg(), nm_write_reg(), nmi_get_chipid(), NMI_REV_REG, NMI_STATE_REG, REV, REV_3A0, rHAVE_ETHERNET_MODE_BIT, rHAVE_USE_PMU_BIT, and TIMEOUT.
Referenced by nm_drv_init_start().
wait_for_firmware_start()
sint8 wait_for_firmware_start (uint8 arg)
Definition at line 467 of file nmasic.c.
{
    sint8 ret = M2M_SUCCESS;
    uint32 reg = 0, cnt = 0;
    uint32 u32Timeout = TIMEOUT;
    volatile uint32 regAddress = NMI_STATE_REG;
    volatile uint32 checkValue = M2M_FINISH_INIT_STATE;
    if((M2M_WIFI_MODE_ATE_HIGH == arg)||(M2M_WIFI_MODE_ATE_LOW == arg)) {
        regAddress = NMI_REV_REG;
        checkValue = M2M_ATE_FW_IS_UP_VALUE;
    } else {
        /*bypass this step*/
    }
    while (checkValue != reg)
    {
        nm_bsp_sleep(2); /* TODO: Why bus error if this delay is not here. */
        M2M_DBG("%x %x %x\n",(unsigned int)nm_read_reg(0x108c),(unsigned int)nm_read_reg(0x108c),(unsigned int)nm_read_reg(0x14A0));
        reg = nm_read_reg(regAddress);
        if(++cnt >= u32Timeout)
        {
            M2M_DBG("Time out for wait firmware Run\n");
            ret = M2M_ERR_INIT;
            goto ERR;
        }
    }
    if(M2M_FINISH_INIT_STATE == checkValue)
    {
        nm_write_reg(NMI_STATE_REG, 0);
    }
ERR:
    return ret;
}
References M2M_ATE_FW_IS_UP_VALUE, M2M_DBG, M2M_ERR_INIT, M2M_FINISH_INIT_STATE, M2M_SUCCESS, M2M_WIFI_MODE_ATE_HIGH, M2M_WIFI_MODE_ATE_LOW, nm_bsp_sleep(), nm_read_reg(), nm_write_reg(), NMI_REV_REG, NMI_STATE_REG, and TIMEOUT.
Referenced by nm_drv_init_start().