WINC1500 Weather Client Demo for SAME70 Xplained: nmbus.h File Reference
nmbus.h File Reference
This module contains NMC1000 bus APIs implementation.
#include "common/include/nm_common.h"
#include "bus_wrapper/include/nm_bus_wrapper.h"
Functions
sint8 nm_bus_iface_deinit (void)
Deinitialize bus interface.
sint8 nm_bus_iface_init (void *)
sint8 nm_bus_iface_reconfigure (void *ptr)
sint8 nm_bus_reset (void)
reset bus interface
sint8 nm_read_block (uint32 u32Addr, uint8 *puBuf, uint32 u32Sz)
uint32 nm_read_reg (uint32 u32Addr)
sint8 nm_read_reg_with_ret (uint32 u32Addr, uint32 *pu32RetVal)
sint8 nm_write_block (uint32 u32Addr, uint8 *puBuf, uint32 u32Sz)
sint8 nm_write_reg (uint32 u32Addr, uint32 u32Val)
Detailed Description
This module contains NMC1000 bus APIs implementation.
Copyright (c) 2016-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file nmbus.h.
Function Documentation
nm_bus_iface_deinit()
sint8 nm_bus_iface_deinit (void)
Deinitialize bus interface.
Returns
M2M_SUCCESS in case of success and M2M_ERR_BUS_FAIL in case of failure
Author
Samer Sarhan
Date
07 April 2014
Version
1.0
Returns
M2M_SUCCESS in case of success and M2M_ERR_BUS_FAIL in case of failure
Definition at line 66 of file nmbus.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = nm_bus_deinit();
    return ret;
}
References M2M_SUCCESS, and nm_bus_deinit().
Referenced by nm_drv_deinit(), nm_drv_init_hold(), and nm_drv_init_start().
nm_bus_iface_init()
sint8 nm_bus_iface_init (void * pvInitVal)
Definition at line 51 of file nmbus.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = nm_bus_init(pvInitVal);
    return ret;
}
References M2M_SUCCESS, and nm_bus_init().
Referenced by nm_drv_init_download_mode(), and nm_drv_init_hold().
nm_bus_iface_reconfigure()
sint8 nm_bus_iface_reconfigure (void * ptr)
Definition at line 102 of file nmbus.c.
{
    sint8 ret = M2M_SUCCESS;
#ifdef CONF_WINC_USE_UART
    ret = nm_uart_reconfigure(ptr);
#endif
    return ret;
}
References M2M_SUCCESS, and nm_uart_reconfigure().
nm_bus_reset()
sint8 nm_bus_reset (void)
reset bus interface
Returns
M2M_SUCCESS in case of success and M2M_ERR_BUS_FAIL in case of failure
Version
1.0
Definition at line 80 of file nmbus.c.
{
    sint8 ret = M2M_SUCCESS;
#ifdef CONF_WINC_USE_UART
#elif defined (CONF_WINC_USE_SPI)
    return nm_spi_reset();
#elif defined (CONF_WINC_USE_I2C)
#else
#error "Please define bus usage"
#endif
    return ret;
}
References M2M_SUCCESS, and nm_spi_reset().
Referenced by chip_wake().
nm_read_block()
sint8 nm_read_block (uint32 u32Addr, uint8 * puBuf, uint32 u32Sz)
Definition at line 211 of file nmbus.c.
{
    uint16 u16MaxTrxSz = egstrNmBusCapabilities.u16MaxTrxSz - MAX_TRX_CFG_SZ;
    uint32 off = 0;
    sint8 s8Ret = M2M_SUCCESS;
    for(;;)
    {
        if(u32Sz <= u16MaxTrxSz)
        {
            s8Ret += p_nm_read_block(u32Addr, &puBuf[off], (uint16)u32Sz);
            break;
        }
        else
        {
            s8Ret += p_nm_read_block(u32Addr, &puBuf[off], u16MaxTrxSz);
            if(M2M_SUCCESS != s8Ret) break;
            u32Sz -= u16MaxTrxSz;
            off += u16MaxTrxSz;
            u32Addr += u16MaxTrxSz;
        }
    }
    return s8Ret;
}
References egstrNmBusCapabilities, M2M_SUCCESS, MAX_TRX_CFG_SZ, p_nm_read_block(), and tstrNmBusCapabilities::u16MaxTrxSz.
Referenced by hif_isr(), hif_receive(), nm_get_firmware_full_info(), nm_get_ota_firmware_info(), nmi_get_mac_address(), nmi_get_otp_mac_address(), and spi_flash_read_internal().
nm_read_reg()
uint32 nm_read_reg (uint32 u32Addr)
Definition at line 120 of file nmbus.c.
{
#ifdef CONF_WINC_USE_UART
    return nm_uart_read_reg(u32Addr);
#elif defined (CONF_WINC_USE_SPI)
    return nm_spi_read_reg(u32Addr);
#elif defined (CONF_WINC_USE_I2C)
    return nm_i2c_read_reg(u32Addr);
#else
#error "Please define bus usage"
#endif
}
References nm_i2c_read_reg(), nm_spi_read_reg(), and nm_uart_read_reg().
Referenced by nmi_set_sys_clk_src_to_xo(), nmi_update_pll(), spi_flash_enter_low_power_mode(), spi_flash_leave_low_power_mode(), spi_flash_rdid(), spi_flash_read_status_reg(), wait_for_bootrom(), and wait_for_firmware_start().
nm_read_reg_with_ret()
sint8 nm_read_reg_with_ret (uint32 u32Addr, uint32 * pu32RetVal)
Definition at line 146 of file nmbus.c.
{
#ifdef CONF_WINC_USE_UART
    return nm_uart_read_reg_with_ret(u32Addr,pu32RetVal);
#elif defined (CONF_WINC_USE_SPI)
    return nm_spi_read_reg_with_ret(u32Addr,pu32RetVal);
#elif defined (CONF_WINC_USE_I2C)
    return nm_i2c_read_reg_with_ret(u32Addr,pu32RetVal);
#else
#error "Please define bus usage"
#endif
}
References nm_i2c_read_reg_with_ret(), nm_spi_read_reg_with_ret(), and nm_uart_read_reg_with_ret().
Referenced by chip_apply_conf(), chip_deinit(), chip_idle(), chip_sleep(), chip_wake(), cpu_halt(), cpu_start(), enable_interrupts(), hif_isr(), hif_send(), hif_set_rx_done(), nm_get_firmware_full_info(), nm_get_firmware_info(), nm_get_ota_firmware_info(), nmi_get_chipid(), nmi_get_mac_address(), nmi_get_otp_mac_address(), nmi_get_rfrevid(), spi_flash_enable(), spi_flash_load_to_cortus_mem(), spi_flash_page_program(), spi_flash_rdid(), spi_flash_read_status_reg(), spi_flash_sector_erase(), spi_flash_write_disable(), and spi_flash_write_enable().
nm_write_block()
sint8 nm_write_block (uint32 u32Addr, uint8 * puBuf, uint32 u32Sz)
Definition at line 264 of file nmbus.c.
{
    uint16 u16MaxTrxSz = egstrNmBusCapabilities.u16MaxTrxSz - MAX_TRX_CFG_SZ;
    uint32 off = 0;
    sint8 s8Ret = M2M_SUCCESS;
    for(;;)
    {
        if(u32Sz <= u16MaxTrxSz)
        {
            s8Ret += p_nm_write_block(u32Addr, &puBuf[off], (uint16)u32Sz);
            break;
        }
        else
        {
            s8Ret += p_nm_write_block(u32Addr, &puBuf[off], u16MaxTrxSz);
            if(M2M_SUCCESS != s8Ret) break;
            u32Sz -= u16MaxTrxSz;
            off += u16MaxTrxSz;
            u32Addr += u16MaxTrxSz;
        }
    }
    return s8Ret;
}
References egstrNmBusCapabilities, M2M_SUCCESS, MAX_TRX_CFG_SZ, p_nm_write_block(), and tstrNmBusCapabilities::u16MaxTrxSz.
Referenced by hif_send(), and spi_flash_pp().
nm_write_reg()
sint8 nm_write_reg (uint32 u32Addr, uint32 u32Val)
Definition at line 171 of file nmbus.c.
{
#ifdef CONF_WINC_USE_UART
    return nm_uart_write_reg(u32Addr,u32Val);
#elif defined (CONF_WINC_USE_SPI)
    return nm_spi_write_reg(u32Addr,u32Val);
#elif defined (CONF_WINC_USE_I2C)
    return nm_i2c_write_reg(u32Addr,u32Val);
#else
#error "Please define bus usage"
#endif
}
References nm_i2c_write_reg(), nm_spi_write_reg(), and nm_uart_write_reg().
Referenced by chip_apply_conf(), chip_deinit(), chip_idle(), chip_reset(), chip_sleep(), chip_wake(), cpu_halt(), cpu_start(), enable_interrupts(), hif_isr(), hif_send(), hif_set_rx_done(), nm_drv_init_download_mode(), nmi_set_sys_clk_src_to_xo(), nmi_update_pll(), restore_pmu_settings_after_global_reset(), spi_flash_enable(), spi_flash_enter_low_power_mode(), spi_flash_leave_low_power_mode(), spi_flash_load_to_cortus_mem(), spi_flash_page_program(), spi_flash_rdid(), spi_flash_read_status_reg(), spi_flash_sector_erase(), spi_flash_write_disable(), spi_flash_write_enable(), wait_for_bootrom(), and wait_for_firmware_start().