WINC1500 Weather Client Demo for SAME70 Xplained: nmdrv.h File Reference
nmdrv.h File Reference
This module contains NMC1500 M2M driver APIs declarations.
#include "common/include/nm_common.h"
Data Structures
struct tstrM2mBinaryHeader
Structure holding compatibility version info for firmware binaries.
struct tstrM2mRev
Structure holding firmware version parameters and build date/time.
Functions
sint8 nm_drv_deinit (void *arg)
sint8 nm_drv_init (void *arg)
sint8 nm_drv_init_download_mode (void)
sint8 nm_drv_init_hold (void)
sint8 nm_drv_init_start (void *arg)
sint8 nm_get_firmware_full_info (tstrM2mRev *pstrRev)
Get Firmware version info.
sint8 nm_get_firmware_info (tstrM2mRev *M2mRev)
Get Firmware version info.
sint8 nm_get_ota_firmware_info (tstrM2mRev *pstrRev)
Get Firmware version info.
Detailed Description
This module contains NMC1500 M2M driver APIs declarations.
Copyright (c) 2016-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file nmdrv.h.
Function Documentation
nm_drv_deinit()
sint8 nm_drv_deinit (void * arg)
Definition at line 379 of file nmdrv.c.
{
    sint8 ret;
    ret = chip_deinit();
    if (M2M_SUCCESS != ret) {
        M2M_ERR("[nmi stop]: chip_deinit fail\n");
        goto ERR1;
    }
    /* Disable SPI flash to save power when the chip is off */
    ret = spi_flash_enable(0);
    if (M2M_SUCCESS != ret) {
        M2M_ERR("[nmi stop]: SPI flash disable fail\n");
        goto ERR1;
    }
    ret = nm_bus_iface_deinit();
    if (M2M_SUCCESS != ret) {
        M2M_ERR("[nmi stop]: fail init bus\n");
        goto ERR1;
    }
#ifdef CONF_WINC_USE_SPI
    /* Must do this after global reset to set SPI data packet size. */
    nm_spi_deinit();
#endif
ERR1:
    return ret;
}
References chip_deinit(), M2M_ERR, M2M_SUCCESS, nm_bus_iface_deinit(), nm_spi_deinit(), and spi_flash_enable().
Referenced by m2m_wifi_deinit(), and m2m_wifi_init_start().
nm_drv_init()
sint8 nm_drv_init (void * arg)
Definition at line 360 of file nmdrv.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = nm_drv_init_hold();
    if(ret == M2M_SUCCESS)
        ret = nm_drv_init_start(arg);
    return ret;
}
References M2M_SUCCESS, nm_drv_init_hold(), and nm_drv_init_start().
nm_drv_init_download_mode()
sint8 nm_drv_init_download_mode (void)
TODO:reset the chip and halt the cpu in case of no wait efuse is set (add the no wait effuse check)
Definition at line 229 of file nmdrv.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = nm_bus_iface_init(NULL);
    if (M2M_SUCCESS != ret) {
        M2M_ERR("[nmi start]: fail init bus\n");
        goto ERR1;
    }
    if(!ISNMC3000(GET_CHIPID()))
    {
        /*Execute that function only for 1500A/B, no room in 3000, but it may be needed in 3400 no wait*/
        chip_reset_and_cpu_halt();
    }
#ifdef CONF_WINC_USE_SPI
    /* Must do this after global reset to set SPI data packet size. */
    nm_spi_init();
#endif
    M2M_INFO("Chip ID %lx\n", nmi_get_chipid());
    /*disable all interrupt in ROM (to disable uart) in 2b0 chip*/
    nm_write_reg(0x20300,0);
ERR1:
    return ret;
}
References chip_reset_and_cpu_halt(), GET_CHIPID, ISNMC3000, M2M_ERR, M2M_INFO, M2M_SUCCESS, nm_bus_iface_init(), nm_spi_init(), nm_write_reg(), nmi_get_chipid(), and NULL.
Referenced by m2m_wifi_download_mode().
nm_drv_init_hold()
sint8 nm_drv_init_hold (void)
Definition at line 262 of file nmdrv.c.
{
    sint8 ret = M2M_SUCCESS;
    ret = nm_bus_iface_init(NULL);
    if (M2M_SUCCESS != ret) {
        M2M_ERR("[nmi start]: fail init bus\n");
        goto ERR1;
    }
#ifdef BUS_ONLY
    return;
#endif
#ifdef NO_HW_CHIP_EN
    ret = chip_wake();
    if (M2M_SUCCESS != ret) {
        M2M_ERR("[nmi start]: fail chip_wakeup\n");
        goto ERR2;
    }
    ret = chip_reset();
    if (M2M_SUCCESS != ret) {
        goto ERR2;
    }
#endif
    M2M_INFO("Chip ID %lx\n", nmi_get_chipid());
#ifdef CONF_WINC_USE_SPI
    /* Must do this after global reset to set SPI data packet size. */
    nm_spi_init();
#endif
    return ret;
#ifdef NO_HW_CHIP_EN
ERR2:
    nm_bus_iface_deinit();
#endif
ERR1:
    return ret;
}
References chip_reset(), chip_wake(), M2M_ERR, M2M_INFO, M2M_SUCCESS, nm_bus_iface_deinit(), nm_bus_iface_init(), nm_spi_init(), nmi_get_chipid(), and NULL.
Referenced by m2m_wifi_init_hold(), and nm_drv_init().
nm_drv_init_start()
sint8 nm_drv_init_start (void * arg)
Definition at line 306 of file nmdrv.c.
{
    sint8 ret = M2M_SUCCESS;
    uint8 u8Mode = M2M_WIFI_MODE_NORMAL;
    if(NULL != arg) {
        u8Mode = *((uint8 *)arg);
        if((u8Mode < M2M_WIFI_MODE_NORMAL)||(u8Mode >= M2M_WIFI_MODE_MAX)) {
            u8Mode = M2M_WIFI_MODE_NORMAL;
        }
    }
    ret = wait_for_bootrom(u8Mode);
    if (M2M_SUCCESS != ret) {
        goto ERR2;
    }
    ret = wait_for_firmware_start(u8Mode);
    if (M2M_SUCCESS != ret) {
        goto ERR2;
    }
    if((M2M_WIFI_MODE_ATE_HIGH == u8Mode)||(M2M_WIFI_MODE_ATE_LOW == u8Mode)) {
        goto ERR1;
    } else {
        /*continue running*/
    }
    ret = enable_interrupts();
    if (M2M_SUCCESS != ret) {
        M2M_ERR("failed to enable interrupts..\n");
        goto ERR2;
    }
    return ret;
ERR2:
    nm_bus_iface_deinit();
#ifdef CONF_WINC_USE_SPI
    nm_spi_deinit();
#endif
ERR1:
    return ret;
}
References enable_interrupts(), M2M_ERR, M2M_SUCCESS, M2M_WIFI_MODE_ATE_HIGH, M2M_WIFI_MODE_ATE_LOW, M2M_WIFI_MODE_MAX, M2M_WIFI_MODE_NORMAL, nm_bus_iface_deinit(), nm_spi_deinit(), NULL, wait_for_bootrom(), and wait_for_firmware_start().
Referenced by m2m_wifi_init_start(), and nm_drv_init().
nm_get_firmware_full_info()
sint8 nm_get_firmware_full_info (tstrM2mRev * pstrRev)
Get Firmware version info.
Parameters
[out] M2mRev pointer holds address of structure "tstrM2mRev" that contains the firmware version parameters
Version
1.0
Definition at line 97 of file nmdrv.c.
{
    uint16  curr_drv_ver, min_req_drv_ver,curr_firm_ver;
    uint32  reg = 0;
    sint8   ret = M2M_SUCCESS;
    tstrGpRegs strgp = {0};
    if (pstrRev != NULL)
    {
        m2m_memset((uint8*)pstrRev,0,sizeof(tstrM2mRev));
        ret = nm_read_reg_with_ret(rNMI_GP_REG_2, &reg);
        if(ret == M2M_SUCCESS)
        {
            if(reg != 0)
            {
                ret = nm_read_block(reg|0x30000,(uint8*)&strgp,sizeof(tstrGpRegs));
                if(ret == M2M_SUCCESS)
                {
                    reg = strgp.u32Firmware_Ota_rev;
                    reg &= 0x0000ffff;
                    if(reg != 0)
                    {
                        ret = nm_read_block(reg|0x30000,(uint8*)pstrRev,sizeof(tstrM2mRev));
                        if(ret == M2M_SUCCESS)
{
                            curr_firm_ver   = M2M_MAKE_VERSION(pstrRev->u8FirmwareMajor, pstrRev->u8FirmwareMinor,pstrRev->u8FirmwarePatch);
                            curr_drv_ver    = M2M_MAKE_VERSION(M2M_RELEASE_VERSION_MAJOR_NO, M2M_RELEASE_VERSION_MINOR_NO, M2M_RELEASE_VERSION_PATCH_NO);
                            min_req_drv_ver = M2M_MAKE_VERSION(pstrRev->u8DriverMajor, pstrRev->u8DriverMinor,pstrRev->u8DriverPatch);
                            if((curr_firm_ver == 0)||(min_req_drv_ver == 0)||(min_req_drv_ver == 0)){
                                ret = M2M_ERR_FAIL;
                                goto EXIT;
                            }
                            if(curr_drv_ver <  min_req_drv_ver) {
                                /*The current driver version should be larger or equal
                                than the min driver that the current firmware support  */
                                ret = M2M_ERR_FW_VER_MISMATCH;
                                goto EXIT;
                            }
                            if(curr_drv_ver >  curr_firm_ver) {
                                /*The current driver should be equal or less than the firmware version*/
                                ret = M2M_ERR_FW_VER_MISMATCH;
                                goto EXIT;
                            }
                        }
                    }else {
                        ret = M2M_ERR_FAIL;
                    }
                }
            }else{
                ret = M2M_ERR_FAIL;
            }
        }
    }
EXIT:
    return ret;
}
References M2M_ERR_FAIL, M2M_ERR_FW_VER_MISMATCH, M2M_MAKE_VERSION, m2m_memset(), M2M_RELEASE_VERSION_MAJOR_NO, M2M_RELEASE_VERSION_MINOR_NO, M2M_RELEASE_VERSION_PATCH_NO, M2M_SUCCESS, nm_read_block(), nm_read_reg_with_ret(), NULL, and rNMI_GP_REG_2.
Referenced by m2m_wifi_get_firmware_version(), and m2m_wifi_init_start().
nm_get_firmware_info()
sint8 nm_get_firmware_info (tstrM2mRev * M2mRev)
Get Firmware version info.
Parameters
[out] M2mRev pointer holds address of structure "tstrM2mRev" that contains the firmware version parameters
Version
1.0
Definition at line 54 of file nmdrv.c.
{
    uint16  curr_drv_ver, min_req_drv_ver,curr_firm_ver;
    uint32  reg = 0;
    sint8   ret = M2M_SUCCESS;
    ret = nm_read_reg_with_ret(NMI_REV_REG, &reg);
    //In case the Firmware running is ATE fw
    if(M2M_ATE_FW_IS_UP_VALUE == reg)
    {
        //Read FW info again from the register specified for ATE
        ret = nm_read_reg_with_ret(NMI_REV_REG_ATE, &reg);
    }
    M2mRev->u8DriverMajor   = M2M_GET_DRV_MAJOR(reg);
    M2mRev->u8DriverMinor   = M2M_GET_DRV_MINOR(reg);
    M2mRev->u8DriverPatch   = M2M_GET_DRV_PATCH(reg);
    M2mRev->u8FirmwareMajor = M2M_GET_FW_MAJOR(reg);
    M2mRev->u8FirmwareMinor = M2M_GET_FW_MINOR(reg);
    M2mRev->u8FirmwarePatch = M2M_GET_FW_PATCH(reg);
    M2mRev->u32Chipid   = nmi_get_chipid();
    M2mRev->u16FirmwareSvnNum = 0;
    curr_firm_ver   = M2M_MAKE_VERSION(M2mRev->u8FirmwareMajor, M2mRev->u8FirmwareMinor,M2mRev->u8FirmwarePatch);
    curr_drv_ver    = M2M_MAKE_VERSION(M2M_RELEASE_VERSION_MAJOR_NO, M2M_RELEASE_VERSION_MINOR_NO, M2M_RELEASE_VERSION_PATCH_NO);
    min_req_drv_ver = M2M_MAKE_VERSION(M2mRev->u8DriverMajor, M2mRev->u8DriverMinor,M2mRev->u8DriverPatch);
    if(curr_drv_ver <  min_req_drv_ver) {
        /*The current driver version should be larger or equal
        than the min driver that the current firmware support  */
        ret = M2M_ERR_FW_VER_MISMATCH;
    }
    if(curr_drv_ver >  curr_firm_ver) {
        /*The current driver should be equal or less than the firmware version*/
        ret = M2M_ERR_FW_VER_MISMATCH;
    }
    return ret;
}
References M2M_ATE_FW_IS_UP_VALUE, M2M_ERR_FW_VER_MISMATCH, M2M_GET_DRV_MAJOR, M2M_GET_DRV_MINOR, M2M_GET_DRV_PATCH, M2M_GET_FW_MAJOR, M2M_GET_FW_MINOR, M2M_GET_FW_PATCH, M2M_MAKE_VERSION, M2M_RELEASE_VERSION_MAJOR_NO, M2M_RELEASE_VERSION_MINOR_NO, M2M_RELEASE_VERSION_PATCH_NO, M2M_SUCCESS, nm_read_reg_with_ret(), nmi_get_chipid(), NMI_REV_REG, NMI_REV_REG_ATE, tstrM2mRev::u16FirmwareSvnNum, tstrM2mRev::u32Chipid, tstrM2mRev::u8DriverMajor, tstrM2mRev::u8DriverMinor, tstrM2mRev::u8DriverPatch, tstrM2mRev::u8FirmwareMajor, tstrM2mRev::u8FirmwareMinor, and tstrM2mRev::u8FirmwarePatch.
nm_get_ota_firmware_info()
sint8 nm_get_ota_firmware_info (tstrM2mRev * pstrRev)
Get Firmware version info.
Parameters
[out] M2mRev pointer holds address of structure "tstrM2mRev" that contains the firmware version parameters
Version
1.0
Definition at line 160 of file nmdrv.c.
{
    uint16  curr_drv_ver, min_req_drv_ver,curr_firm_ver;
    uint32  reg = 0;
    sint8   ret;
    tstrGpRegs strgp = {0};
    if (pstrRev != NULL)
    {
        m2m_memset((uint8*)pstrRev,0,sizeof(tstrM2mRev));
        ret = nm_read_reg_with_ret(rNMI_GP_REG_2, &reg);
        if(ret == M2M_SUCCESS)
        {
            if(reg != 0)
            {
                ret = nm_read_block(reg|0x30000,(uint8*)&strgp,sizeof(tstrGpRegs));
                if(ret == M2M_SUCCESS)
                {
                    reg = strgp.u32Firmware_Ota_rev;
                    reg >>= 16;
                    if(reg != 0)
                    {
                        ret = nm_read_block(reg|0x30000,(uint8*)pstrRev,sizeof(tstrM2mRev));
                        if(ret == M2M_SUCCESS)
{
                            curr_firm_ver   = M2M_MAKE_VERSION(pstrRev->u8FirmwareMajor, pstrRev->u8FirmwareMinor,pstrRev->u8FirmwarePatch);
                            curr_drv_ver    = M2M_MAKE_VERSION(M2M_RELEASE_VERSION_MAJOR_NO, M2M_RELEASE_VERSION_MINOR_NO, M2M_RELEASE_VERSION_PATCH_NO);
                            min_req_drv_ver = M2M_MAKE_VERSION(pstrRev->u8DriverMajor, pstrRev->u8DriverMinor,pstrRev->u8DriverPatch);
                            if((curr_firm_ver == 0)||(min_req_drv_ver == 0)||(min_req_drv_ver == 0)){
                                ret = M2M_ERR_FAIL;
                                goto EXIT;
                            }
                            if(curr_drv_ver <  min_req_drv_ver) {
                                /*The current driver version should be larger or equal
                                than the min driver that the current firmware support  */
                                ret = M2M_ERR_FW_VER_MISMATCH;
                            }
                            if(curr_drv_ver >  curr_firm_ver) {
                                /*The current driver should be equal or less than the firmware version*/
                                ret = M2M_ERR_FW_VER_MISMATCH;
                            }
                        }
                    }else{
                        ret = M2M_ERR_INVALID;
                    }
                }
            }else{
                ret = M2M_ERR_FAIL;
            }
        }
    } else {
        ret = M2M_ERR_INVALID_ARG;
    }
EXIT:
    return ret;
}
References M2M_ERR_FAIL, M2M_ERR_FW_VER_MISMATCH, M2M_ERR_INVALID, M2M_ERR_INVALID_ARG, M2M_MAKE_VERSION, m2m_memset(), M2M_RELEASE_VERSION_MAJOR_NO, M2M_RELEASE_VERSION_MINOR_NO, M2M_RELEASE_VERSION_PATCH_NO, M2M_SUCCESS, nm_read_block(), nm_read_reg_with_ret(), NULL, and rNMI_GP_REG_2.
Referenced by m2m_ota_get_firmware_version().