WINC1500 Weather Client Demo for SAME70 Xplained: nmi2c.c File Reference
nmi2c.c File Reference
This module contains NMC1000 I2C protocol bus APIs implementation.
#include "common/include/nm_common.h"
#include "nmi2c.h"
#include "bus_wrapper/include/nm_bus_wrapper.h"
Functions
sint8 nm_i2c_read_block (uint32 u32Addr, uint8 *pu8Buf, uint16 u16Sz)
uint32 nm_i2c_read_reg (uint32 u32Addr)
sint8 nm_i2c_read_reg_with_ret (uint32 u32Addr, uint32 *pu32RetVal)
sint8 nm_i2c_write_block (uint32 u32Addr, uint8 *pu8Buf, uint16 u16Sz)
sint8 nm_i2c_write_reg (uint32 u32Addr, uint32 u32Val)
Detailed Description
This module contains NMC1000 I2C protocol bus APIs implementation.
Copyright (c) 2016-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file nmi2c.c.
Function Documentation
nm_i2c_read_block()
sint8 nm_i2c_read_block (uint32 u32Addr, uint8 * pu8Buf, uint16 u16Sz)
Definition at line 182 of file nmi2c.c.
{
    tstrNmI2cDefault strI2c;
    uint8 au8Buf[7];
    sint8 s8Ret = M2M_SUCCESS;
    au8Buf[0] = 0x02;
    au8Buf[1] = (uint8)(u32Addr >> 24);
    au8Buf[2] = (uint8)(u32Addr >> 16);
    au8Buf[3] = (uint8)(u32Addr >> 8);
    au8Buf[4] = (uint8)(u32Addr >> 0);
    au8Buf[5] = (uint8)(u16Sz >> 8);
    au8Buf[6] = (uint8)(u16Sz);
    strI2c.pu8Buf = au8Buf;
    strI2c.u16Sz = sizeof(au8Buf);
    if(M2M_SUCCESS != nm_bus_ioctl(NM_BUS_IOCTL_W, &strI2c))
    {
        M2M_ERR("write error\n");
        s8Ret = M2M_ERR_BUS_FAIL;
    }
    else
    {
        strI2c.pu8Buf = pu8Buf;
        strI2c.u16Sz = u16Sz;
        if(M2M_SUCCESS != nm_bus_ioctl(NM_BUS_IOCTL_R, &strI2c))
        {
            M2M_ERR("read error\n");
            s8Ret = M2M_ERR_BUS_FAIL;
        }
    }
    return s8Ret;
}
References M2M_ERR, M2M_ERR_BUS_FAIL, M2M_SUCCESS, nm_bus_ioctl(), NM_BUS_IOCTL_R, NM_BUS_IOCTL_W, tstrNmI2cDefault::pu8Buf, and tstrNmI2cDefault::u16Sz.
Referenced by p_nm_read_block().
nm_i2c_read_reg()
uint32 nm_i2c_read_reg (uint32 u32Addr)
Definition at line 113 of file nmi2c.c.
{
    uint32 val;
    nm_i2c_read_reg_with_ret(u32Addr, &val);
    return val;
}
References nm_i2c_read_reg_with_ret().
Referenced by nm_read_reg().
nm_i2c_read_reg_with_ret()
sint8 nm_i2c_read_reg_with_ret (uint32 u32Addr, uint32 * pu32RetVal)
Definition at line 55 of file nmi2c.c.
{
    uint8 b[6];
    uint8 rsz;
    tstrNmI2cDefault strI2c;
    sint8 s8Ret = M2M_SUCCESS;
    if(u32Addr < 0xff) { /* clockless i2c */
        b[0] = 0x09;
        b[1] = (uint8)(u32Addr);
        rsz = 1;
        strI2c.u16Sz = 2;
    } else {
        b[0] = 0x80;
        b[1] = (uint8)(u32Addr >> 24);
        b[2] = (uint8)(u32Addr >> 16);
        b[3] = (uint8)(u32Addr >> 8);
        b[4] = (uint8)(u32Addr);
        b[5] = 0x04;
        rsz = 4;
        strI2c.u16Sz = 6;
    }
    strI2c.pu8Buf = b;
    if(M2M_SUCCESS == nm_bus_ioctl(NM_BUS_IOCTL_W, &strI2c))
    {
        strI2c.u16Sz = rsz;
        if(M2M_SUCCESS != nm_bus_ioctl(NM_BUS_IOCTL_R, &strI2c))
        {
            //M2M_ERR("read error\n");
            s8Ret = M2M_ERR_BUS_FAIL;
        }
    }
    else
    {
        M2M_ERR("failed to send cfg bytes\n");
        s8Ret = M2M_ERR_BUS_FAIL;
    }
    if (rsz == 1) {
        *pu32RetVal = b[0];
    } else {
        *pu32RetVal = b[0] | ((uint32)b[1] << 8) | ((uint32)b[2] << 16) | ((uint32)b[3] << 24);
    }
    return s8Ret;
}
References M2M_ERR, M2M_ERR_BUS_FAIL, M2M_SUCCESS, nm_bus_ioctl(), NM_BUS_IOCTL_R, NM_BUS_IOCTL_W, tstrNmI2cDefault::pu8Buf, and tstrNmI2cDefault::u16Sz.
Referenced by nm_i2c_read_reg(), and nm_read_reg_with_ret().
nm_i2c_write_block()
sint8 nm_i2c_write_block (uint32 u32Addr, uint8 * pu8Buf, uint16 u16Sz)
Definition at line 233 of file nmi2c.c.
{
    uint8 au8Buf[7];
    tstrNmI2cSpecial strI2c;
    sint8 s8Ret = M2M_SUCCESS;
    au8Buf[0] = 0x12;
    au8Buf[1] = (uint8)(u32Addr >> 24);
    au8Buf[2] = (uint8)(u32Addr >> 16);
    au8Buf[3] = (uint8)(u32Addr >> 8);
    au8Buf[4] = (uint8)(u32Addr);
    au8Buf[5] = (uint8)(u16Sz >> 8);
    au8Buf[6] = (uint8)(u16Sz);
    strI2c.pu8Buf1 = au8Buf;
    strI2c.pu8Buf2 = pu8Buf;
    strI2c.u16Sz1 = sizeof(au8Buf);
    strI2c.u16Sz2 = u16Sz;
    if(M2M_SUCCESS != nm_bus_ioctl(NM_BUS_IOCTL_W_SPECIAL, &strI2c))
    {
        M2M_ERR("write error\n");
        s8Ret = M2M_ERR_BUS_FAIL;
    }
    return s8Ret;
}
References M2M_ERR, M2M_ERR_BUS_FAIL, M2M_SUCCESS, nm_bus_ioctl(), NM_BUS_IOCTL_W_SPECIAL, tstrNmI2cSpecial::pu8Buf1, tstrNmI2cSpecial::pu8Buf2, tstrNmI2cSpecial::u16Sz1, and tstrNmI2cSpecial::u16Sz2.
Referenced by p_nm_write_block().
nm_i2c_write_reg()
sint8 nm_i2c_write_reg (uint32 u32Addr, uint32 u32Val)
Definition at line 132 of file nmi2c.c.
{
    tstrNmI2cDefault strI2c;
    uint8 b[16];
    sint8 s8Ret = M2M_SUCCESS;
    if(u32Addr < 0xff) { /* clockless i2c */
        b[0] = 0x19;
        b[1] = (uint8)(u32Addr);
        b[2] = (uint8)(u32Val);
        strI2c.u16Sz = 3;
    } else {
        b[0] = 0x90;
        b[1] = (uint8)(u32Addr >> 24);
        b[2] = (uint8)(u32Addr >> 16);
        b[3] = (uint8)(u32Addr >> 8);
        b[4] = (uint8)u32Addr;
        b[5] = 0x04;
        b[6] = (uint8)u32Val;
        b[7] = (uint8)(u32Val >> 8);
        b[8] = (uint8)(u32Val >> 16);
        b[9] = (uint8)(u32Val >> 24);
        strI2c.u16Sz = 10;
    }
    strI2c.pu8Buf = b;
    if(M2M_SUCCESS != nm_bus_ioctl(NM_BUS_IOCTL_W, &strI2c))
    {
        M2M_ERR("write error\n");
        s8Ret = M2M_ERR_BUS_FAIL;
    }
    return s8Ret;
}
References M2M_ERR, M2M_ERR_BUS_FAIL, M2M_SUCCESS, nm_bus_ioctl(), NM_BUS_IOCTL_W, tstrNmI2cDefault::pu8Buf, and tstrNmI2cDefault::u16Sz.
Referenced by nm_write_reg().