WINC1500 Weather Client Demo for SAME70 Xplained: nmspi.h File Reference
nmspi.h File Reference
This module contains NMC1000 SPI protocol bus APIs implementation.
#include "common/include/nm_common.h"
Functions
sint8 nm_spi_deinit (void)
DeInitialize the SPI.
sint8 nm_spi_init (void)
Initialize the SPI.
sint8 nm_spi_read_block (uint32 u32Addr, uint8 *puBuf, uint16 u16Sz)
uint32 nm_spi_read_reg (uint32 u32Addr)
sint8 nm_spi_read_reg_with_ret (uint32 u32Addr, uint32 *pu32RetVal)
sint8 nm_spi_reset (void)
reset the SPI
sint8 nm_spi_write_block (uint32 u32Addr, uint8 *puBuf, uint16 u16Sz)
sint8 nm_spi_write_reg (uint32 u32Addr, uint32 u32Val)
Detailed Description
This module contains NMC1000 SPI protocol bus APIs implementation.
Copyright (c) 2016-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file nmspi.h.
Function Documentation
nm_spi_deinit()
nm_spi_deinit (void)
DeInitialize the SPI.
Returns
ZERO in case of success and M2M_ERR_BUS_FAIL in case of failure
Referenced by nm_drv_deinit(), and nm_drv_init_start().
nm_spi_init()
nm_spi_init (void)
Initialize the SPI.
Returns
ZERO in case of success and M2M_ERR_BUS_FAIL in case of failure
Referenced by nm_drv_init_download_mode(), and nm_drv_init_hold().
nm_spi_read_block()
sint8 nm_spi_read_block (uint32 u32Addr, uint8 * puBuf, uint16 u16Sz)
Referenced by p_nm_read_block().
nm_spi_read_reg()
uint32 nm_spi_read_reg (uint32 u32Addr)
Referenced by nm_read_reg().
nm_spi_read_reg_with_ret()
sint8 nm_spi_read_reg_with_ret (uint32 u32Addr, uint32 * pu32RetVal)
Referenced by nm_read_reg_with_ret().
nm_spi_reset()
nm_spi_reset (void)
reset the SPI
Returns
ZERO in case of success and M2M_ERR_BUS_FAIL in case of failure
Referenced by nm_bus_reset().
nm_spi_write_block()
sint8 nm_spi_write_block (uint32 u32Addr, uint8 * puBuf, uint16 u16Sz)
Referenced by p_nm_write_block().
nm_spi_write_reg()
sint8 nm_spi_write_reg (uint32 u32Addr, uint32 u32Val)
Referenced by nm_write_reg().