WINC1500 Weather Client Demo for SAME70 Xplained: nmuart.h File Reference
nmuart.h File Reference
This module contains NMC1000 UART protocol bus APIs implementation.
#include "common/include/nm_common.h"
Functions
sint8 nm_uart_read_block (uint32 u32Addr, uint8 *puBuf, uint16 u16Sz)
uint32 nm_uart_read_reg (uint32 u32Addr)
sint8 nm_uart_read_reg_with_ret (uint32 u32Addr, uint32 *pu32RetVal)
sint8 nm_uart_reconfigure (void *ptr)
sint8 nm_uart_sync_cmd (void)
sint8 nm_uart_write_block (uint32 u32Addr, uint8 *puBuf, uint16 u16Sz)
sint8 nm_uart_write_reg (uint32 u32Addr, uint32 u32Val)
Detailed Description
This module contains NMC1000 UART protocol bus APIs implementation.
Copyright (c) 2016-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file nmuart.h.
Function Documentation
nm_uart_read_block()
sint8 nm_uart_read_block (uint32 u32Addr, uint8 * puBuf, uint16 u16Sz)
Referenced by p_nm_read_block().
nm_uart_read_reg()
uint32 nm_uart_read_reg (uint32 u32Addr)
Referenced by nm_read_reg().
nm_uart_read_reg_with_ret()
sint8 nm_uart_read_reg_with_ret (uint32 u32Addr, uint32 * pu32RetVal)
Referenced by nm_read_reg_with_ret().
nm_uart_reconfigure()
sint8 nm_uart_reconfigure (void * ptr)
Referenced by nm_bus_iface_reconfigure().
nm_uart_sync_cmd()
sint8 nm_uart_sync_cmd (void)
nm_uart_write_block()
sint8 nm_uart_write_block (uint32 u32Addr, uint8 * puBuf, uint16 u16Sz)
Referenced by p_nm_write_block().
nm_uart_write_reg()
sint8 nm_uart_write_reg (uint32 u32Addr, uint32 u32Val)
Referenced by nm_write_reg().