WINC1500 Weather Client Demo for SAME70 Xplained: spi_flash.h File Reference
spi_flash.h File Reference
WINC1500 SPI Flash.
#include "common/include/nm_common.h"
#include "bus_wrapper/include/nm_bus_wrapper.h"
#include "driver/source/nmbus.h"
#include "driver/source/nmasic.h"
Macros
#define FLASH_SECTOR_SZ (4 * 1024UL)
Functions
sint8 spi_flash_enable (uint8 enable)
sint8 spi_flash_erase (uint32 u32Offset, uint32 u32Sz)
Erase a specified portion of SPI Flash.
.
uint32 spi_flash_get_size (void)
Get size of SPI Flash.
sint8 spi_flash_read (uint8 *pu8Buf, uint32 u32Addr, uint32 u32Sz)
Read a specified portion of data from SPI Flash.
.
sint8 spi_flash_write (uint8 *pu8Buf, uint32 u32Offset, uint32 u32Sz)
Write a specified portion of data to SPI Flash.
.
Detailed Description
WINC1500 SPI Flash.
This file describe SPI flash APIs, how to use it and limitations with each one.
Copyright (c) 2016-2018 Microchip Technology Inc. and its subsidiaries.
Example
This example illustrates a complete guide of how to use these APIs.
#include "spi_flash.h"
#define DATA_TO_REPLACE "THIS IS A NEW SECTOR IN FLASH"
int main()
{
    uint8   au8FlashContent[FLASH_SECTOR_SZ] = {0};
    uint32  u32FlashTotalSize = 0;
    uint32  u32FlashOffset = 0;
    ret = m2m_wifi_download_mode();
    if(M2M_SUCCESS != ret)
    {
        printf("Unable to enter download mode\r\n");
    }
    else
    {
        u32FlashTotalSize = spi_flash_get_size();
    }
    while((u32FlashTotalSize > u32FlashOffset) && (M2M_SUCCESS == ret))
    {
        ret = spi_flash_read(au8FlashContent, u32FlashOffset, FLASH_SECTOR_SZ);
        if(M2M_SUCCESS != ret)
        {
            printf("Unable to read SPI sector\r\n");
            break;
        }
        memcpy(au8FlashContent, DATA_TO_REPLACE, strlen(DATA_TO_REPLACE));
        ret = spi_flash_erase(u32FlashOffset, FLASH_SECTOR_SZ);
        if(M2M_SUCCESS != ret)
        {
            printf("Unable to erase SPI sector\r\n");
            break;
        }
        ret = spi_flash_write(au8FlashContent, u32FlashOffset, FLASH_SECTOR_SZ);
        if(M2M_SUCCESS != ret)
        {
            printf("Unable to write SPI sector\r\n");
            break;
        }
        u32FlashOffset += FLASH_SECTOR_SZ;
    }
    if(M2M_SUCCESS == ret)
    {
        printf("Successful operations\r\n");
    }
    else
    {
        printf("Failed operations\r\n");
    }
    while(1);
    return M2M_SUCCESS;
}
Definition in file spi_flash.h.
Macro Definition Documentation
FLASH_SECTOR_SZ
#define FLASH_SECTOR_SZ (4 * 1024UL)
Sector Size in Flash Memory
Definition at line 111 of file spi_flash.h.
Function Documentation
spi_flash_enable()
sint8 spi_flash_enable (uint8 enable)
Definition at line 529 of file spi_flash.c.
{
    sint8 s8Ret = M2M_SUCCESS;
    if(REV(nmi_get_chipid()) >= REV_3A0) {
        uint32 u32Val;
        /* Enable pinmux to SPI flash. */
        s8Ret = nm_read_reg_with_ret(0x1410, &u32Val);
        if(s8Ret != M2M_SUCCESS) {
            goto ERR1;
        }
        /* GPIO15/16/17/18 */
        u32Val &= ~((0x7777ul) << 12);
        if(enable) {
            u32Val |= ((0x1111ul) << 12);
            nm_write_reg(0x1410, u32Val);
            spi_flash_leave_low_power_mode();
        } else {
            spi_flash_enter_low_power_mode();
            /* Disable pinmux to SPI flash to minimize leakage. */
            u32Val |= ((0x0010ul) << 12);
            nm_write_reg(0x1410, u32Val);
        }
    }
ERR1:
    return s8Ret;
}
References M2M_SUCCESS, nm_read_reg_with_ret(), nm_write_reg(), nmi_get_chipid(), REV, REV_3A0, spi_flash_enter_low_power_mode(), and spi_flash_leave_low_power_mode().
Referenced by nm_drv_deinit().