WINC1500 Weather Client Demo for SAME70 Xplained: spi_master.c File Reference
spi_master.c File Reference
SPI master common service for SAM.
#include "spi_master.h"
Macros
#define DEFAULT_CHIP_ID 0
The default chip select id.
#define MAX_NUM_WITH_DECODER 0x10
Max number when the chip selects are connected to a 4- to 16-bit decoder.
#define MAX_NUM_WITHOUT_DECODER 0x04
Max number when the chip selects are directly connected to peripheral device.
#define NONE_CHIP_SELECT_ID 0x0f
Max number when the chip selects are directly connected to peripheral device.
Functions
void spi_deselect_device (Spi *p_spi, struct spi_device *device)
Deselect the given device on the SPI bus.
void spi_master_init (Spi *p_spi)
Initialize the SPI in master mode.
void spi_master_setup_device (Spi *p_spi, struct spi_device *device, spi_flags_t flags, uint32_t baud_rate, board_spi_select_id_t sel_id)
Set up an SPI device.
status_code_t spi_read_packet (Spi *p_spi, uint8_t *data, size_t len)
Receive a sequence of bytes from an SPI device.
void spi_select_device (Spi *p_spi, struct spi_device *device)
Select the given device on the SPI bus.
status_code_t spi_transceive_packet (Spi *p_spi, uint8_t *tx_data, uint8_t *rx_data, size_t len)
Send and receive a sequence of bytes from an SPI device.
status_code_t spi_write_packet (Spi *p_spi, const uint8_t *data, size_t len)
Send a sequence of bytes to an SPI device.
Detailed Description
SPI master common service for SAM.
Copyright (c) 2011-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file spi_master.c.
Macro Definition Documentation
DEFAULT_CHIP_ID
#define DEFAULT_CHIP_ID 0
The default chip select id.
Definition at line 61 of file spi_master.c.
MAX_NUM_WITH_DECODER
#define MAX_NUM_WITH_DECODER 0x10
Max number when the chip selects are connected to a 4- to 16-bit decoder.
Definition at line 46 of file spi_master.c.
MAX_NUM_WITHOUT_DECODER
#define MAX_NUM_WITHOUT_DECODER 0x04
Max number when the chip selects are directly connected to peripheral device.
Definition at line 51 of file spi_master.c.
NONE_CHIP_SELECT_ID
#define NONE_CHIP_SELECT_ID 0x0f
Max number when the chip selects are directly connected to peripheral device.
Definition at line 56 of file spi_master.c.
Function Documentation
spi_deselect_device()
void spi_deselect_device (Spi * p_spi, struct spi_device * device)
Deselect the given device on the SPI bus.
Call board chip deselect.
Parameters
p_spi Base address of the SPI instance.
device SPI device.
Precondition
SPI device must be selected with spi_select_device() first.
Definition at line 155 of file spi_master.c.
{
    /* avoid Cppcheck Warning */
    UNUSED(device);
    while (!spi_is_tx_empty(p_spi)) {
    }
    // Assert all lines; no peripheral is selected.
    spi_set_peripheral_chip_select_value(p_spi, NONE_CHIP_SELECT_ID);
    // Last transfer, so de-assert the current NPCS if CSAAT is set.
    spi_set_lastxfer(p_spi);
}
References NONE_CHIP_SELECT_ID, spi_is_tx_empty(), spi_set_lastxfer(), spi_set_peripheral_chip_select_value(), and UNUSED.
spi_master_init()
void spi_master_init (Spi * p_spi)
Initialize the SPI in master mode.
Parameters
p_spi Base address of the SPI instance.
Definition at line 68 of file spi_master.c.
{
#if SAMG55
    flexcom_enable(BOARD_FLEXCOM_SPI);
    flexcom_set_opmode(BOARD_FLEXCOM_SPI, FLEXCOM_SPI);
#else
    spi_enable_clock(p_spi);
#endif
    spi_reset(p_spi);
    spi_set_master_mode(p_spi);
    spi_disable_mode_fault_detect(p_spi);
    spi_disable_loopback(p_spi);
    spi_set_peripheral_chip_select_value(p_spi, DEFAULT_CHIP_ID);
    spi_set_fixed_peripheral_select(p_spi);
    spi_disable_peripheral_select_decode(p_spi);
    spi_set_delay_between_chip_select(p_spi, CONFIG_SPI_MASTER_DELAY_BCS);
}
References CONFIG_SPI_MASTER_DELAY_BCS, DEFAULT_CHIP_ID, spi_disable_loopback(), spi_disable_mode_fault_detect(), spi_disable_peripheral_select_decode(), spi_enable_clock(), spi_reset(), spi_set_delay_between_chip_select(), spi_set_fixed_peripheral_select(), spi_set_master_mode(), and spi_set_peripheral_chip_select_value().
Referenced by ili9488_init().
spi_master_setup_device()
void spi_master_setup_device (Spi * p_spi, struct spi_device * device, spi_flags_t flags, uint32_t baud_rate, board_spi_select_id_t sel_id)
Set up an SPI device.
The returned device descriptor structure must be passed to the driver whenever that device should be used as current slave device.
Parameters
p_spi Base address of the SPI instance.
device Pointer to SPI device struct that should be initialized.
flags SPI configuration flags. Common flags for all implementations are the SPI modes SPI_MODE_0 ... SPI_MODE_3.
baud_rate Baud rate for communication with slave device in Hz.
sel_id Board specific select id.
Definition at line 100 of file spi_master.c.
{
#if (SAM4L)
    int16_t baud_div = spi_calc_baudrate_div(baud_rate, sysclk_get_pba_hz());
#else
    int16_t baud_div = spi_calc_baudrate_div(baud_rate, sysclk_get_peripheral_hz());
#endif
    /* avoid Cppcheck Warning */
    UNUSED(sel_id);
    if (-1 == baud_div) {
        Assert(0 == "Failed to find baudrate divider");
    }
    spi_set_transfer_delay(p_spi, device->id, CONFIG_SPI_MASTER_DELAY_BS,
            CONFIG_SPI_MASTER_DELAY_BCT);
    spi_set_bits_per_transfer(p_spi, device->id,
            CONFIG_SPI_MASTER_BITS_PER_TRANSFER);
    spi_set_baudrate_div(p_spi, device->id, baud_div);
    spi_configure_cs_behavior(p_spi, device->id, SPI_CS_KEEP_LOW);
    spi_set_clock_polarity(p_spi, device->id, flags >> 1);
    spi_set_clock_phase(p_spi, device->id, ((flags & 0x1) ^ 0x1));
}
References Assert, CONFIG_SPI_MASTER_BITS_PER_TRANSFER, CONFIG_SPI_MASTER_DELAY_BCT, CONFIG_SPI_MASTER_DELAY_BS, spi_device::id, spi_calc_baudrate_div(), spi_configure_cs_behavior(), SPI_CS_KEEP_LOW, spi_set_baudrate_div(), spi_set_bits_per_transfer(), spi_set_clock_phase(), spi_set_clock_polarity(), spi_set_transfer_delay(), sysclk_get_peripheral_hz(), and UNUSED.
Referenced by ili9488_init().
spi_read_packet()
status_code_t spi_read_packet (Spi * p_spi, uint8_t * data, size_t len)
Receive a sequence of bytes from an SPI device.
All bytes sent out on SPI bus are sent as value 0.
Parameters
p_spi Base address of the SPI instance.
data Data buffer to read.
len Length of data to be read.
Precondition
SPI device must be selected with spi_select_device() first.
Definition at line 215 of file spi_master.c.
{
    uint32_t timeout = SPI_TIMEOUT;
    uint8_t val;
    uint32_t i = 0;
    while (len) {
        timeout = SPI_TIMEOUT;
        while (!spi_is_tx_ready(p_spi)) {
            if (!timeout--) {
                return ERR_TIMEOUT;
            }
        }
        spi_write_single(p_spi, CONFIG_SPI_MASTER_DUMMY);
        timeout = SPI_TIMEOUT;
        while (!spi_is_rx_ready(p_spi)) {
            if (!timeout--) {
                return ERR_TIMEOUT;
            }
        }
        spi_read_single(p_spi, &val);
        data[i] = val;
        i++;
        len--;
    }
    return STATUS_OK;
}
References CONFIG_SPI_MASTER_DUMMY, ERR_TIMEOUT, spi_is_rx_ready(), spi_is_tx_ready(), spi_read_single(), SPI_TIMEOUT, spi_write_single(), and STATUS_OK.
Referenced by ili9488_copy_pixels_from_screen(), ili9488_read_chipid(), and ili9488_read_ram().
spi_select_device()
void spi_select_device (Spi * p_spi, struct spi_device * device)
Select the given device on the SPI bus.
Set device specific setting and call board chip select.
Parameters
p_spi Base address of the SPI instance.
device SPI device.
Definition at line 132 of file spi_master.c.
{
    if (spi_get_peripheral_select_decode_setting(p_spi)) {
        if (device->id < MAX_NUM_WITH_DECODER) {
            spi_set_peripheral_chip_select_value(p_spi, device->id);
        }
    } else {
        if (device->id < MAX_NUM_WITHOUT_DECODER) {
            spi_set_peripheral_chip_select_value(p_spi, (~(1 << device->id)));
        }
    }
}
References spi_device::id, MAX_NUM_WITH_DECODER, MAX_NUM_WITHOUT_DECODER, spi_get_peripheral_select_decode_setting(), and spi_set_peripheral_chip_select_value().
Referenced by ili9488_init().
spi_transceive_packet()
status_code_t spi_transceive_packet (Spi * p_spi, uint8_t * tx_data, uint8_t * rx_data, size_t len)
Send and receive a sequence of bytes from an SPI device.
Parameters
p_spi Base address of the SPI instance.
tx_data Data buffer to send.
rx_data Data buffer to read.
len Length of data to be read.
Precondition
SPI device must be selected with spi_select_device() first.
Definition at line 256 of file spi_master.c.
{
    uint32_t timeout = SPI_TIMEOUT;
    uint8_t val;
    uint32_t i = 0;
    while (len) {
        timeout = SPI_TIMEOUT;
        while (!spi_is_tx_ready(p_spi)) {
            if (!timeout--) {
                return ERR_TIMEOUT;
            }
        }
        spi_write_single(p_spi, tx_data[i]);
        timeout = SPI_TIMEOUT;
        while (!spi_is_rx_ready(p_spi)) {
            if (!timeout--) {
                return ERR_TIMEOUT;
            }
        }
        spi_read_single(p_spi, &val);
        rx_data[i] = val;
        i++;
        len--;
    }
    return STATUS_OK;
}
References ERR_TIMEOUT, spi_is_rx_ready(), spi_is_tx_ready(), spi_read_single(), SPI_TIMEOUT, spi_write_single(), and STATUS_OK.
spi_write_packet()
status_code_t spi_write_packet (Spi * p_spi, const uint8_t * data, size_t len)
Send a sequence of bytes to an SPI device.
Received bytes on the SPI bus are discarded.
Parameters
p_spi Base address of the SPI instance.
data Data buffer to write.
len Length of data to be written.
Precondition
SPI device must be selected with spi_select_device() first.
Definition at line 181 of file spi_master.c.
{
    uint32_t timeout = SPI_TIMEOUT;
    uint32_t i = 0;
    uint8_t val;
    while (len) {
        timeout = SPI_TIMEOUT;
        while (!spi_is_tx_ready(p_spi)) {
            if (!timeout--) {
                return ERR_TIMEOUT;
            }
        }
        val = data[i];
        spi_write_single(p_spi, val);
        i++;
        len--;
    }
    return STATUS_OK;
}
References ERR_TIMEOUT, spi_is_tx_ready(), SPI_TIMEOUT, spi_write_single(), and STATUS_OK.
Referenced by ili9488_write_ram_buffer(), and ili9488_write_register().