WINC1500 Weather Client Demo for SAME70 Xplained: spi_flash.c File Reference
spi_flash.c File Reference
WINC1500 SPI Flash.
#include "spi_flash/include/spi_flash.h"
Macros
#define CORTUS_SHARE_MEM_BASE (0x60000000UL)
#define DUMMY_REGISTER (0x1084)
#define FLASH_BLOCK_SIZE (32UL * 1024)
#define FLASH_PAGE_SZ (256)
#define GET_UINT32(X, Y) (X[0+Y] + ((uint32)X[1+Y]<<8) + ((uint32)X[2+Y]<<16) +((uint32)X[3+Y]<<24))
#define HOST_SHARE_MEM_BASE (0xd0000UL)
#define NMI_SPI_FLASH_ADDR (0x111c)
#define SPI_FLASH_BASE (0x10200)
#define SPI_FLASH_BUF1 (SPI_FLASH_BASE + 0x0c)
#define SPI_FLASH_BUF2 (SPI_FLASH_BASE + 0x10)
#define SPI_FLASH_BUF_DIR (SPI_FLASH_BASE + 0x14)
#define SPI_FLASH_CMD_CNT (SPI_FLASH_BASE + 0x04)
#define SPI_FLASH_DATA_CNT (SPI_FLASH_BASE + 0x08)
#define SPI_FLASH_DMA_ADDR (SPI_FLASH_BASE + 0x1c)
#define SPI_FLASH_MODE (SPI_FLASH_BASE + 0x00)
#define SPI_FLASH_MSB_CTL (SPI_FLASH_BASE + 0x20)
#define SPI_FLASH_TR_DONE (SPI_FLASH_BASE + 0x18)
#define SPI_FLASH_TX_CTL (SPI_FLASH_BASE + 0x24)
#define TIMEOUT (-1) /*MS*/
Functions
sint8 spi_flash_enable (uint8 enable)
static void spi_flash_enter_low_power_mode (void)
sint8 spi_flash_erase (uint32 u32Offset, uint32 u32Sz)
Erase a specified portion of SPI Flash.
.
uint32 spi_flash_get_size (void)
Get size of SPI Flash.
static void spi_flash_leave_low_power_mode (void)
static sint8 spi_flash_load_to_cortus_mem (uint32 u32MemAdr, uint32 u32FlashAdr, uint32 u32Sz)
static sint8 spi_flash_page_program (uint32 u32MemAdr, uint32 u32FlashAdr, uint32 u32Sz)
static sint8 spi_flash_pp (uint32 u32Offset, uint8 *pu8Buf, uint16 u16Sz)
static uint32 spi_flash_rdid (void)
Read SPI Flash ID.
sint8 spi_flash_read (uint8 *pu8Buf, uint32 u32offset, uint32 u32Sz)
Read a specified portion of data from SPI Flash.
.
static sint8 spi_flash_read_internal (uint8 *pu8Buf, uint32 u32Addr, uint32 u32Sz)
static sint8 spi_flash_read_status_reg (uint8 *val)
static sint8 spi_flash_sector_erase (uint32 u32FlashAdr)
sint8 spi_flash_write (uint8 *pu8Buf, uint32 u32Offset, uint32 u32Sz)
Write a specified portion of data to SPI Flash.
.
static sint8 spi_flash_write_disable (void)
Send write disable command to SPI flash.
static sint8 spi_flash_write_enable (void)
Send write enable command to SPI flash.
Detailed Description
WINC1500 SPI Flash.
Copyright (c) 2016-2021 Microchip Technology Inc. and its subsidiaries.
Definition in file spi_flash.c.
Macro Definition Documentation
CORTUS_SHARE_MEM_BASE
#define CORTUS_SHARE_MEM_BASE (0x60000000UL)
Definition at line 52 of file spi_flash.c.
DUMMY_REGISTER
#define DUMMY_REGISTER (0x1084)
Definition at line 39 of file spi_flash.c.
FLASH_BLOCK_SIZE
#define FLASH_BLOCK_SIZE (32UL * 1024)
Block Size in Flash Memory
Definition at line 47 of file spi_flash.c.
FLASH_PAGE_SZ
#define FLASH_PAGE_SZ (256)
Page Size in Flash Memory
Definition at line 49 of file spi_flash.c.
GET_UINT32
#define GET_UINT32 (X, Y) (X[0+Y] + ((uint32)X[1+Y]<<8) + ((uint32)X[2+Y]<<16) +((uint32)X[3+Y]<<24))
Definition at line 57 of file spi_flash.c.
HOST_SHARE_MEM_BASE
#define HOST_SHARE_MEM_BASE (0xd0000UL)
Definition at line 51 of file spi_flash.c.
NMI_SPI_FLASH_ADDR
#define NMI_SPI_FLASH_ADDR (0x111c)
Definition at line 53 of file spi_flash.c.
SPI_FLASH_BASE
#define SPI_FLASH_BASE (0x10200)
Definition at line 58 of file spi_flash.c.
SPI_FLASH_BUF1
#define SPI_FLASH_BUF1 (SPI_FLASH_BASE + 0x0c)
Definition at line 62 of file spi_flash.c.
SPI_FLASH_BUF2
#define SPI_FLASH_BUF2 (SPI_FLASH_BASE + 0x10)
Definition at line 63 of file spi_flash.c.
SPI_FLASH_BUF_DIR
#define SPI_FLASH_BUF_DIR (SPI_FLASH_BASE + 0x14)
Definition at line 64 of file spi_flash.c.
SPI_FLASH_CMD_CNT
#define SPI_FLASH_CMD_CNT (SPI_FLASH_BASE + 0x04)
Definition at line 60 of file spi_flash.c.
SPI_FLASH_DATA_CNT
#define SPI_FLASH_DATA_CNT (SPI_FLASH_BASE + 0x08)
Definition at line 61 of file spi_flash.c.
SPI_FLASH_DMA_ADDR
#define SPI_FLASH_DMA_ADDR (SPI_FLASH_BASE + 0x1c)
Definition at line 66 of file spi_flash.c.
SPI_FLASH_MODE
#define SPI_FLASH_MODE (SPI_FLASH_BASE + 0x00)
Definition at line 59 of file spi_flash.c.
SPI_FLASH_MSB_CTL
#define SPI_FLASH_MSB_CTL (SPI_FLASH_BASE + 0x20)
Definition at line 67 of file spi_flash.c.
SPI_FLASH_TR_DONE
#define SPI_FLASH_TR_DONE (SPI_FLASH_BASE + 0x18)
Definition at line 65 of file spi_flash.c.
SPI_FLASH_TX_CTL
#define SPI_FLASH_TX_CTL (SPI_FLASH_BASE + 0x24)
Definition at line 68 of file spi_flash.c.
TIMEOUT
#define TIMEOUT (-1) /*MS*/
Definition at line 41 of file spi_flash.c.
Function Documentation
spi_flash_enable()
sint8 spi_flash_enable (uint8 enable)
Definition at line 529 of file spi_flash.c.
{
    sint8 s8Ret = M2M_SUCCESS;
    if(REV(nmi_get_chipid()) >= REV_3A0) {
        uint32 u32Val;
        /* Enable pinmux to SPI flash. */
        s8Ret = nm_read_reg_with_ret(0x1410, &u32Val);
        if(s8Ret != M2M_SUCCESS) {
            goto ERR1;
        }
        /* GPIO15/16/17/18 */
        u32Val &= ~((0x7777ul) << 12);
        if(enable) {
            u32Val |= ((0x1111ul) << 12);
            nm_write_reg(0x1410, u32Val);
            spi_flash_leave_low_power_mode();
        } else {
            spi_flash_enter_low_power_mode();
            /* Disable pinmux to SPI flash to minimize leakage. */
            u32Val |= ((0x0010ul) << 12);
            nm_write_reg(0x1410, u32Val);
        }
    }
ERR1:
    return s8Ret;
}
References M2M_SUCCESS, nm_read_reg_with_ret(), nm_write_reg(), nmi_get_chipid(), REV, REV_3A0, spi_flash_enter_low_power_mode(), and spi_flash_leave_low_power_mode().
Referenced by nm_drv_deinit().
spi_flash_enter_low_power_mode()
static void spi_flash_enter_low_power_mode (void) static
Definition at line 492 of file spi_flash.c.
{
    volatile unsigned long tmp;
    unsigned char* cmd = (unsigned char*) &tmp;
    cmd[0] = 0xb9;
    nm_write_reg(SPI_FLASH_DATA_CNT, 0);
    nm_write_reg(SPI_FLASH_BUF1, cmd[0]);
    nm_write_reg(SPI_FLASH_BUF_DIR, 0x1);
    nm_write_reg(SPI_FLASH_DMA_ADDR, 0);
    nm_write_reg(SPI_FLASH_CMD_CNT, 1 | (1 << 7));
    while(nm_read_reg(SPI_FLASH_TR_DONE) != 1);
}
References nm_read_reg(), nm_write_reg(), SPI_FLASH_BUF1, SPI_FLASH_BUF_DIR, SPI_FLASH_CMD_CNT, SPI_FLASH_DATA_CNT, SPI_FLASH_DMA_ADDR, and SPI_FLASH_TR_DONE.
Referenced by spi_flash_enable().
spi_flash_leave_low_power_mode()
static void spi_flash_leave_low_power_mode (void) static
Definition at line 507 of file spi_flash.c.
{
    volatile unsigned long tmp;
    unsigned char* cmd = (unsigned char*) &tmp;
    cmd[0] = 0xab;
    nm_write_reg(SPI_FLASH_DATA_CNT, 0);
    nm_write_reg(SPI_FLASH_BUF1, cmd[0]);
    nm_write_reg(SPI_FLASH_BUF_DIR, 0x1);
    nm_write_reg(SPI_FLASH_DMA_ADDR, 0);
    nm_write_reg(SPI_FLASH_CMD_CNT,  1 | (1 << 7));
    while(nm_read_reg(SPI_FLASH_TR_DONE) != 1);
}
References nm_read_reg(), nm_write_reg(), SPI_FLASH_BUF1, SPI_FLASH_BUF_DIR, SPI_FLASH_CMD_CNT, SPI_FLASH_DATA_CNT, SPI_FLASH_DMA_ADDR, and SPI_FLASH_TR_DONE.
Referenced by spi_flash_enable().
spi_flash_load_to_cortus_mem()
static sint8 spi_flash_load_to_cortus_mem (uint32 u32MemAdr, uint32 u32FlashAdr, uint32 u32Sz) static
Definition at line 217 of file spi_flash.c.
{
    uint8 cmd[5];
    uint32  val = 0;
    sint8   ret = M2M_SUCCESS;
    cmd[0] = 0x0b;
    cmd[1] = (uint8)(u32FlashAdr >> 16);
    cmd[2] = (uint8)(u32FlashAdr >> 8);
    cmd[3] = (uint8)(u32FlashAdr);
    cmd[4] = 0xA5;
    ret += nm_write_reg(SPI_FLASH_DATA_CNT, u32Sz);
    ret += nm_write_reg(SPI_FLASH_BUF1, cmd[0]|(((uint32)cmd[1])<<8)|(((uint32)cmd[2])<<16)|(((uint32)cmd[3])<<24));
    ret += nm_write_reg(SPI_FLASH_BUF2, cmd[4]);
    ret += nm_write_reg(SPI_FLASH_BUF_DIR, 0x1f);
    ret += nm_write_reg(SPI_FLASH_DMA_ADDR, u32MemAdr);
    ret += nm_write_reg(SPI_FLASH_CMD_CNT, 5 | (1<<7));
    do
    {
        ret += nm_read_reg_with_ret(SPI_FLASH_TR_DONE, (uint32 *)&val);
        if(M2M_SUCCESS != ret) break;
    }
    while(val != 1);
    return ret;
}
References M2M_SUCCESS, nm_read_reg_with_ret(), nm_write_reg(), SPI_FLASH_BUF1, SPI_FLASH_BUF2, SPI_FLASH_BUF_DIR, SPI_FLASH_CMD_CNT, SPI_FLASH_DATA_CNT, SPI_FLASH_DMA_ADDR, and SPI_FLASH_TR_DONE.
Referenced by spi_flash_read_internal().
spi_flash_page_program()
static sint8 spi_flash_page_program (uint32 u32MemAdr, uint32 u32FlashAdr, uint32 u32Sz) static
Definition at line 354 of file spi_flash.c.
{
    uint8 cmd[4];
    uint32  val = 0;
    sint8   ret = M2M_SUCCESS;
    cmd[0] = 0x02;
    cmd[1] = (uint8)(u32FlashAdr >> 16);
    cmd[2] = (uint8)(u32FlashAdr >> 8);
    cmd[3] = (uint8)(u32FlashAdr);
    ret += nm_write_reg(SPI_FLASH_DATA_CNT, 0);
    ret += nm_write_reg(SPI_FLASH_BUF1, cmd[0]|(((uint32)cmd[1])<<8)|(((uint32)cmd[2])<<16)|(((uint32)cmd[3])<<24));
    ret += nm_write_reg(SPI_FLASH_BUF_DIR, 0x0f);
    ret += nm_write_reg(SPI_FLASH_DMA_ADDR, u32MemAdr);
    ret += nm_write_reg(SPI_FLASH_CMD_CNT, 4 | (1<<7) | ((u32Sz & 0xfffff) << 8));
    do
    {
        ret += nm_read_reg_with_ret(SPI_FLASH_TR_DONE, (uint32 *)&val);
        if(M2M_SUCCESS != ret) break;
    }
    while(val != 1);
    return ret;
}
References M2M_SUCCESS, nm_read_reg_with_ret(), nm_write_reg(), SPI_FLASH_BUF1, SPI_FLASH_BUF_DIR, SPI_FLASH_CMD_CNT, SPI_FLASH_DATA_CNT, SPI_FLASH_DMA_ADDR, and SPI_FLASH_TR_DONE.
Referenced by spi_flash_pp().
spi_flash_pp()
static sint8 spi_flash_pp (uint32 u32Offset, uint8 * pu8Buf, uint16 u16Sz) static
Definition at line 417 of file spi_flash.c.
{
    sint8 ret = M2M_SUCCESS;
    uint8 tmp;
    spi_flash_write_enable();
    /* use shared packet memory as temp mem */
    ret += nm_write_block(HOST_SHARE_MEM_BASE, pu8Buf, u16Sz);
    ret += spi_flash_page_program(HOST_SHARE_MEM_BASE, u32Offset, u16Sz);
    ret += spi_flash_read_status_reg(&tmp);
    do
    {
        if(ret != M2M_SUCCESS) goto ERR;
        ret += spi_flash_read_status_reg(&tmp);
    }while(tmp & 0x01);
    ret += spi_flash_write_disable();
ERR:
    return ret;
}
References HOST_SHARE_MEM_BASE, M2M_SUCCESS, nm_write_block(), spi_flash_page_program(), spi_flash_read_status_reg(), spi_flash_write_disable(), and spi_flash_write_enable().
Referenced by spi_flash_write().
spi_flash_rdid()
spi_flash_rdid (void) static
Read SPI Flash ID.
Returns
SPI FLash ID
Author
M.S.M
Version
1.0
Definition at line 443 of file spi_flash.c.
{
    unsigned char cmd[1];
    uint32 reg = 0;
    uint32 cnt = 0;
    sint8   ret = M2M_SUCCESS;
    cmd[0] = 0x9f;
    ret += nm_write_reg(SPI_FLASH_DATA_CNT, 4);
    ret += nm_write_reg(SPI_FLASH_BUF1, cmd[0]);
    ret += nm_write_reg(SPI_FLASH_BUF_DIR, 0x1);
    ret += nm_write_reg(SPI_FLASH_DMA_ADDR, DUMMY_REGISTER);
    ret += nm_write_reg(SPI_FLASH_CMD_CNT, 1 | (1<<7));
    do
    {
        ret += nm_read_reg_with_ret(SPI_FLASH_TR_DONE, (uint32 *)&reg);
        if(M2M_SUCCESS != ret) break;
        if(++cnt > 500)
        {
            ret = M2M_ERR_INIT;
            break;
        }
    }
    while(reg != 1);
    reg = (M2M_SUCCESS == ret)?(nm_read_reg(DUMMY_REGISTER)):(0);
    M2M_PRINT("Flash ID %x \n",(unsigned int)reg);
    return reg;
}
References DUMMY_REGISTER, M2M_ERR_INIT, M2M_PRINT, M2M_SUCCESS, nm_read_reg(), nm_read_reg_with_ret(), nm_write_reg(), SPI_FLASH_BUF1, SPI_FLASH_BUF_DIR, SPI_FLASH_CMD_CNT, SPI_FLASH_DATA_CNT, SPI_FLASH_DMA_ADDR, and SPI_FLASH_TR_DONE.
Referenced by spi_flash_get_size().
spi_flash_read_internal()
static sint8 spi_flash_read_internal (uint8 * pu8Buf, uint32 u32Addr, uint32 u32Sz) static
Definition at line 393 of file spi_flash.c.
{
    sint8 ret = M2M_SUCCESS;
    /* read size must be < 64KB */
    ret = spi_flash_load_to_cortus_mem(HOST_SHARE_MEM_BASE, u32Addr, u32Sz);
    if(M2M_SUCCESS != ret) goto ERR;
    ret = nm_read_block(HOST_SHARE_MEM_BASE, pu8Buf, u32Sz);
ERR:
    return ret;
}
References HOST_SHARE_MEM_BASE, M2M_SUCCESS, nm_read_block(), and spi_flash_load_to_cortus_mem().
Referenced by spi_flash_read().
spi_flash_read_status_reg()
static sint8 spi_flash_read_status_reg (uint8 * val) static
Definition at line 84 of file spi_flash.c.
{
    sint8 ret = M2M_SUCCESS;
    uint8 cmd[1];
    uint32 reg;
    cmd[0] = 0x05;
    ret += nm_write_reg(SPI_FLASH_DATA_CNT, 4);
    ret += nm_write_reg(SPI_FLASH_BUF1, cmd[0]);
    ret += nm_write_reg(SPI_FLASH_BUF_DIR, 0x01);
    ret += nm_write_reg(SPI_FLASH_DMA_ADDR, DUMMY_REGISTER);
    ret += nm_write_reg(SPI_FLASH_CMD_CNT, 1 | (1<<7));
    do
    {
        ret += nm_read_reg_with_ret(SPI_FLASH_TR_DONE, (uint32 *)&reg);
        if(M2M_SUCCESS != ret) break;
    }
    while(reg != 1);
    reg = (M2M_SUCCESS == ret)?(nm_read_reg(DUMMY_REGISTER)):(0);
    *val = (uint8)(reg & 0xff);
    return ret;
}
References DUMMY_REGISTER, M2M_SUCCESS, nm_read_reg(), nm_read_reg_with_ret(), nm_write_reg(), SPI_FLASH_BUF1, SPI_FLASH_BUF_DIR, SPI_FLASH_CMD_CNT, SPI_FLASH_DATA_CNT, SPI_FLASH_DMA_ADDR, and SPI_FLASH_TR_DONE.
Referenced by spi_flash_erase(), and spi_flash_pp().
spi_flash_sector_erase()
static sint8 spi_flash_sector_erase (uint32 u32FlashAdr) static
Definition at line 255 of file spi_flash.c.
{
    uint8 cmd[4];
    uint32  val = 0;
    sint8   ret = M2M_SUCCESS;
    cmd[0] = 0x20;
    cmd[1] = (uint8)(u32FlashAdr >> 16);
    cmd[2] = (uint8)(u32FlashAdr >> 8);
    cmd[3] = (uint8)(u32FlashAdr);
    ret += nm_write_reg(SPI_FLASH_DATA_CNT, 0);
    ret += nm_write_reg(SPI_FLASH_BUF1, cmd[0]|(((uint32)cmd[1])<<8)|(((uint32)cmd[2])<<16)|(((uint32)cmd[3])<<24));
    ret += nm_write_reg(SPI_FLASH_BUF_DIR, 0x0f);
    ret += nm_write_reg(SPI_FLASH_DMA_ADDR, 0);
    ret += nm_write_reg(SPI_FLASH_CMD_CNT, 4 | (1<<7));
    do
    {
        ret += nm_read_reg_with_ret(SPI_FLASH_TR_DONE, (uint32 *)&val);
        if(M2M_SUCCESS != ret) break;
    }
    while(val != 1);
    return ret;
}
References M2M_SUCCESS, nm_read_reg_with_ret(), nm_write_reg(), SPI_FLASH_BUF1, SPI_FLASH_BUF_DIR, SPI_FLASH_CMD_CNT, SPI_FLASH_DATA_CNT, SPI_FLASH_DMA_ADDR, and SPI_FLASH_TR_DONE.
Referenced by spi_flash_erase().
spi_flash_write_disable()
spi_flash_write_disable (void) static
Send write disable command to SPI flash.
Note
Compatible with MX25L6465E and should be working with other types
Author
M. Abdelmawla
Version
1.0
Definition at line 319 of file spi_flash.c.
{
    uint8 cmd[1];
    uint32  val = 0;
    sint8   ret = M2M_SUCCESS;
    cmd[0] = 0x04;
    ret += nm_write_reg(SPI_FLASH_DATA_CNT, 0);
    ret += nm_write_reg(SPI_FLASH_BUF1, cmd[0]);
    ret += nm_write_reg(SPI_FLASH_BUF_DIR, 0x01);
    ret += nm_write_reg(SPI_FLASH_DMA_ADDR, 0);
    ret += nm_write_reg(SPI_FLASH_CMD_CNT, 1 | (1<<7));
    do
    {
        ret += nm_read_reg_with_ret(SPI_FLASH_TR_DONE, (uint32 *)&val);
        if(M2M_SUCCESS != ret) break;
    }
    while(val != 1);
    return ret;
}
References M2M_SUCCESS, nm_read_reg_with_ret(), nm_write_reg(), SPI_FLASH_BUF1, SPI_FLASH_BUF_DIR, SPI_FLASH_CMD_CNT, SPI_FLASH_DATA_CNT, SPI_FLASH_DMA_ADDR, and SPI_FLASH_TR_DONE.
Referenced by spi_flash_pp().
spi_flash_write_enable()
spi_flash_write_enable (void) static
Send write enable command to SPI flash.
Returns
Status of execution
Note
Compatible with MX25L6465E and should be working with other types
Author
M. Abdelmawla
Version
1.0
Definition at line 289 of file spi_flash.c.
{
    uint8 cmd[1];
    uint32  val = 0;
    sint8   ret = M2M_SUCCESS;
    cmd[0] = 0x06;
    ret += nm_write_reg(SPI_FLASH_DATA_CNT, 0);
    ret += nm_write_reg(SPI_FLASH_BUF1, cmd[0]);
    ret += nm_write_reg(SPI_FLASH_BUF_DIR, 0x01);
    ret += nm_write_reg(SPI_FLASH_DMA_ADDR, 0);
    ret += nm_write_reg(SPI_FLASH_CMD_CNT, 1 | (1<<7));
    do
    {
        ret += nm_read_reg_with_ret(SPI_FLASH_TR_DONE, (uint32 *)&val);
        if(M2M_SUCCESS != ret) break;
    }
    while(val != 1);
    return ret;
}
References M2M_SUCCESS, nm_read_reg_with_ret(), nm_write_reg(), SPI_FLASH_BUF1, SPI_FLASH_BUF_DIR, SPI_FLASH_CMD_CNT, SPI_FLASH_DATA_CNT, SPI_FLASH_DMA_ADDR, and SPI_FLASH_TR_DONE.
Referenced by spi_flash_erase(), and spi_flash_pp().