WINC1500 Weather Client Demo for SAME70 Xplained: system_same70.c File Reference
system_same70.c File Reference
Copyright (c) 2015-2018 Microchip Technology Inc.
#include "same70.h"
Macros
#define SYS_BOARD_MCKR (PMC_MCKR_PRES_CLK_2 | PMC_MCKR_CSS_PLLA_CLK | (1<<8))
#define SYS_BOARD_OSCOUNT (CKGR_MOR_MOSCXTST(0x8U))
#define SYS_BOARD_PLLAR
Functions
void system_init_flash (uint32_t ul_clk)
Initialize flash.
void SystemCoreClockUpdate (void)
Updates the SystemCoreClock with current core Clock retrieved from cpu registers.
void SystemInit (void)
Setup the microcontroller system.
Variables
uint32_t SystemCoreClock = CHIP_FREQ_MAINCK_RC_4MHZ
Detailed Description
Copyright (c) 2015-2018 Microchip Technology Inc.
and its subsidiaries.
Definition in file system_same70.c.
Macro Definition Documentation
SYS_BOARD_MCKR
#define SYS_BOARD_MCKR (PMC_MCKR_PRES_CLK_2 | PMC_MCKR_CSS_PLLA_CLK | (1<<8))
Definition at line 51 of file system_same70.c.
SYS_BOARD_OSCOUNT
#define SYS_BOARD_OSCOUNT (CKGR_MOR_MOSCXTST(0x8U))
Definition at line 48 of file system_same70.c.
SYS_BOARD_PLLAR
#define SYS_BOARD_PLLAR
Value:
                            (CKGR_PLLAR_ONE | CKGR_PLLAR_MULA(0x31U) | \
                            CKGR_PLLAR_PLLACOUNT(0x3fU) | CKGR_PLLAR_DIVA(0x1U))
Definition at line 49 of file system_same70.c.
Function Documentation
system_init_flash()
void system_init_flash (uint32_t ul_clk)
Initialize flash.
Definition at line 202 of file system_same70.c.
{
  /* Set FWS for embedded Flash access according to operating frequency */
  if ( ul_clk < CHIP_FREQ_FWS_0 )
  {
    EFC->EEFC_FMR = EEFC_FMR_FWS(0)|EEFC_FMR_CLOE;
  }
  else
  {
    if (ul_clk < CHIP_FREQ_FWS_1)
    {
      EFC->EEFC_FMR = EEFC_FMR_FWS(1)|EEFC_FMR_CLOE;
    }
    else
    {
      if (ul_clk < CHIP_FREQ_FWS_2)
      {
        EFC->EEFC_FMR = EEFC_FMR_FWS(2)|EEFC_FMR_CLOE;
      }
      else
      {
        if ( ul_clk < CHIP_FREQ_FWS_3 )
        {
          EFC->EEFC_FMR = EEFC_FMR_FWS(3)|EEFC_FMR_CLOE;
        }
        else
        {
          if ( ul_clk < CHIP_FREQ_FWS_4 )
          {
            EFC->EEFC_FMR = EEFC_FMR_FWS(4)|EEFC_FMR_CLOE;
          }
          else
          {
            if ( ul_clk < CHIP_FREQ_FWS_5 )
            {
              EFC->EEFC_FMR = EEFC_FMR_FWS(5)|EEFC_FMR_CLOE;
            }
            else
            {
              EFC->EEFC_FMR = EEFC_FMR_FWS(6)|EEFC_FMR_CLOE;
            }
          }
        }
      }
    }
  }
}
References CHIP_FREQ_FWS_0, CHIP_FREQ_FWS_1, CHIP_FREQ_FWS_2, CHIP_FREQ_FWS_3, CHIP_FREQ_FWS_4, CHIP_FREQ_FWS_5, EEFC_FMR_CLOE, EEFC_FMR_FWS, and EFC.
Referenced by sysclk_init().
SystemCoreClockUpdate()
void SystemCoreClockUpdate (void)
Updates the SystemCoreClock with current core Clock retrieved from cpu registers.
Definition at line 108 of file system_same70.c.
{
  /* Determine clock frequency according to clock register values */
  switch (PMC->PMC_MCKR & (uint32_t) PMC_MCKR_CSS_Msk)
  {
    case PMC_MCKR_CSS_SLOW_CLK: /* Slow clock */
      if ( SUPC->SUPC_SR & SUPC_SR_OSCSEL )
      {
        SystemCoreClock = CHIP_FREQ_XTAL_32K;
      }
      else
      {
        SystemCoreClock = CHIP_FREQ_SLCK_RC;
      }
    break;
    case PMC_MCKR_CSS_MAIN_CLK: /* Main clock */
      if ( PMC->CKGR_MOR & CKGR_MOR_MOSCSEL )
      {
        SystemCoreClock = CHIP_FREQ_XTAL_12M;
      }
      else
      {
        SystemCoreClock = CHIP_FREQ_MAINCK_RC_4MHZ;
        switch ( PMC->CKGR_MOR & CKGR_MOR_MOSCRCF_Msk )
        {
          case CKGR_MOR_MOSCRCF_4_MHz:
          break;
          case CKGR_MOR_MOSCRCF_8_MHz:
            SystemCoreClock *= 2U;
          break;
          case CKGR_MOR_MOSCRCF_12_MHz:
            SystemCoreClock *= 3U;
          break;
          default:
          break;
        }
      }
    break;
    case PMC_MCKR_CSS_PLLA_CLK: /* PLLA clock */
      if ( PMC->CKGR_MOR & CKGR_MOR_MOSCSEL )
      {
        SystemCoreClock = CHIP_FREQ_XTAL_12M ;
      }
      else
      {
        SystemCoreClock = CHIP_FREQ_MAINCK_RC_4MHZ;
        switch ( PMC->CKGR_MOR & CKGR_MOR_MOSCRCF_Msk )
        {
          case CKGR_MOR_MOSCRCF_4_MHz:
          break;
          case CKGR_MOR_MOSCRCF_8_MHz:
            SystemCoreClock *= 2U;
          break;
          case CKGR_MOR_MOSCRCF_12_MHz:
            SystemCoreClock *= 3U;
          break;
          default:
          break;
        }
      }
      if ( (uint32_t) (PMC->PMC_MCKR & (uint32_t) PMC_MCKR_CSS_Msk) == PMC_MCKR_CSS_PLLA_CLK )
      {
        SystemCoreClock *= ((((PMC->CKGR_PLLAR) & CKGR_PLLAR_MULA_Msk) >> CKGR_PLLAR_MULA_Pos) + 1U);
        SystemCoreClock /= ((((PMC->CKGR_PLLAR) & CKGR_PLLAR_DIVA_Msk) >> CKGR_PLLAR_DIVA_Pos));
      }
    break;
    default:
    break;
  }
  if ( (PMC->PMC_MCKR & PMC_MCKR_PRES_Msk) == PMC_MCKR_PRES_CLK_3 )
  {
    SystemCoreClock /= 3U;
  }
  else
  {
    SystemCoreClock >>= ((PMC->PMC_MCKR & PMC_MCKR_PRES_Msk) >> PMC_MCKR_PRES_Pos);
  }
}
References CHIP_FREQ_MAINCK_RC_4MHZ, CHIP_FREQ_SLCK_RC, CHIP_FREQ_XTAL_12M, CHIP_FREQ_XTAL_32K, CKGR_MOR_MOSCRCF_12_MHz, CKGR_MOR_MOSCRCF_4_MHz, CKGR_MOR_MOSCRCF_8_MHz, CKGR_MOR_MOSCRCF_Msk, CKGR_MOR_MOSCSEL, CKGR_PLLAR_DIVA_Msk, CKGR_PLLAR_DIVA_Pos, CKGR_PLLAR_MULA_Msk, CKGR_PLLAR_MULA_Pos, PMC, PMC_MCKR_CSS_MAIN_CLK, PMC_MCKR_CSS_Msk, PMC_MCKR_CSS_PLLA_CLK, PMC_MCKR_CSS_SLOW_CLK, PMC_MCKR_PRES_CLK_3, PMC_MCKR_PRES_Msk, PMC_MCKR_PRES_Pos, SUPC, SUPC_SR_OSCSEL, and SystemCoreClock.
Referenced by sysclk_init(), sysclk_set_prescalers(), and sysclk_set_source().
SystemInit()
void SystemInit (void)
Setup the microcontroller system.
Initialize the System and update the SystemFrequency variable.
Definition at line 59 of file system_same70.c.
{
  /* Set FWS according to SYS_BOARD_MCKR configuration */
  EFC->EEFC_FMR = EEFC_FMR_FWS(5);
  /* Initialize main oscillator */
  if ( !(PMC->CKGR_MOR & CKGR_MOR_MOSCSEL) )
  {
    PMC->CKGR_MOR = CKGR_MOR_KEY_PASSWD | SYS_BOARD_OSCOUNT | CKGR_MOR_MOSCRCEN | CKGR_MOR_MOSCXTEN;
    while ( !(PMC->PMC_SR & PMC_SR_MOSCXTS) )
    {
    }
  }
  /* Switch to 3-20MHz Xtal oscillator */
  PMC->CKGR_MOR = CKGR_MOR_KEY_PASSWD | SYS_BOARD_OSCOUNT | CKGR_MOR_MOSCRCEN | CKGR_MOR_MOSCXTEN | CKGR_MOR_MOSCSEL;
  while ( !(PMC->PMC_SR & PMC_SR_MOSCSELS) )
  {
  }
  PMC->PMC_MCKR = (PMC->PMC_MCKR & ~(uint32_t)PMC_MCKR_CSS_Msk) | PMC_MCKR_CSS_MAIN_CLK;
  while ( !(PMC->PMC_SR & PMC_SR_MCKRDY) )
  {
  }
  /* Initialize PLLA */
  PMC->CKGR_PLLAR = SYS_BOARD_PLLAR;
  while ( !(PMC->PMC_SR & PMC_SR_LOCKA) )
  {
  }
  /* Switch to main clock */
  PMC->PMC_MCKR = (SYS_BOARD_MCKR & ~PMC_MCKR_CSS_Msk) | PMC_MCKR_CSS_MAIN_CLK;
  while ( !(PMC->PMC_SR & PMC_SR_MCKRDY) )
  {
  }
  /* Switch to PLLA */
  PMC->PMC_MCKR = SYS_BOARD_MCKR;
  while ( !(PMC->PMC_SR & PMC_SR_MCKRDY) )
  {
  }
  SystemCoreClock = CHIP_FREQ_CPU_MAX;
}
References CHIP_FREQ_CPU_MAX, CKGR_MOR_KEY_PASSWD, CKGR_MOR_MOSCRCEN, CKGR_MOR_MOSCSEL, CKGR_MOR_MOSCXTEN, EEFC_FMR_FWS, EFC, PMC, PMC_MCKR_CSS_MAIN_CLK, PMC_MCKR_CSS_Msk, PMC_SR_LOCKA, PMC_SR_MCKRDY, PMC_SR_MOSCSELS, PMC_SR_MOSCXTS, SYS_BOARD_MCKR, SYS_BOARD_OSCOUNT, SYS_BOARD_PLLAR, and SystemCoreClock.
Variable Documentation
SystemCoreClock
uint32_t SystemCoreClock = CHIP_FREQ_MAINCK_RC_4MHZ
Definition at line 53 of file system_same70.c.
Referenced by SystemCoreClockUpdate(), and SystemInit().