WINC1500 Weather Client Demo for SAME70 Xplained: uart_serial.h File Reference
uart_serial.h File Reference
Uart Serial for SAM.
#include "compiler.h"
#include "sysclk.h"
#include "uart.h"
#include "usart.h"
#include "conf_uart_serial.h"
Data Structures
struct uart_rs232_options
Input parameters when initializing RS232 and similar modes.
Typedefs
typedef Usart * usart_if
This type can be used independently to refer to USART module for the architecture used.
typedef struct uart_rs232_options usart_rs232_options_t
Input parameters when initializing RS232 and similar modes.
typedef usart_rs232_options_t usart_serial_options_t
Functions
static void usart_serial_getchar (usart_if p_usart, uint8_t *data)
Waits until a character is received, and returns it.
static void usart_serial_init (usart_if p_usart, usart_serial_options_t *opt)
Initializes the Usart in master mode.
static uint32_t usart_serial_is_rx_ready (usart_if p_usart)
Check if Received data is ready.
static int usart_serial_putchar (usart_if p_usart, const uint8_t c)
Sends a character with the USART.
status_code_t usart_serial_read_packet (usart_if usart, uint8_t *data, size_t len)
Receive a sequence of bytes to a USART device.
status_code_t usart_serial_write_packet (usart_if usart, const uint8_t *data, size_t len)
Send a sequence of bytes to a USART device.
Detailed Description
Uart Serial for SAM.
Copyright (c) 2011-2018 Microchip Technology Inc. and its subsidiaries.
Definition in file uart_serial.h.
Typedef Documentation
usart_if
usart_if
This type can be used independently to refer to USART module for the architecture used.
It refers to the correct type definition for the architecture, ie. USART_t* for XMEGA or avr32_usart_t* for UC3.
Definition at line 78 of file uart_serial.h.
usart_rs232_options_t
typedef struct uart_rs232_options usart_rs232_options_t
Input parameters when initializing RS232 and similar modes.
usart_serial_options_t
typedef usart_rs232_options_t usart_serial_options_t
Definition at line 76 of file uart_serial.h.
Function Documentation
usart_serial_getchar()
static void usart_serial_getchar (usart_if p_usart, uint8_t * data) inline static
Waits until a character is received, and returns it.
Parameters
p_usart Base address of the USART instance.
data Data to read
Definition at line 476 of file uart_serial.h.
{
    uint32_t val = 0;
    /* Avoid Cppcheck Warning */
    UNUSED(val);
#ifdef UART
    if (UART == (Uart*)p_usart) {
        while (uart_read((Uart*)p_usart, data));
    }
#else
# ifdef UART0
    if (UART0 == (Uart*)p_usart) {
        while (uart_read((Uart*)p_usart, data));
    }
# endif
# ifdef UART1
    if (UART1 == (Uart*)p_usart) {
        while (uart_read((Uart*)p_usart, data));
    }
# endif
# ifdef UART2
    if (UART2 == (Uart*)p_usart) {
        while (uart_read((Uart*)p_usart, data));
    }
# endif
# ifdef UART3
    if (UART3 == (Uart*)p_usart) {
        while (uart_read((Uart*)p_usart, data));
    }
# endif
#endif /* ifdef UART */
#ifdef USART
    if (USART == p_usart) {
        while (usart_read(p_usart, &val));
        *data = (uint8_t)(val & 0xFF);
    }
#else
# ifdef USART0
    if (USART0 == p_usart) {
        while (usart_read(p_usart, &val));
        *data = (uint8_t)(val & 0xFF);
    }
# endif
# ifdef USART1
    if (USART1 == p_usart) {
        while (usart_read(p_usart, &val));
        *data = (uint8_t)(val & 0xFF);
    }
# endif
# ifdef USART2
    if (USART2 == p_usart) {
        while (usart_read(p_usart, &val));
        *data = (uint8_t)(val & 0xFF);
    }
# endif
# ifdef USART3
    if (USART3 == p_usart) {
        while (usart_read(p_usart, &val));
        *data = (uint8_t)(val & 0xFF);
    }
# endif
# ifdef USART4
    if (USART4 == p_usart) {
        while (usart_read(p_usart, &val));
        *data = (uint8_t)(val & 0xFF);
    }
# endif
# ifdef USART5
    if (USART5 == p_usart) {
        while (usart_read(p_usart, &val));
        *data = (uint8_t)(val & 0xFF);
    }
# endif
# ifdef USART6
    if (USART6 == p_usart) {
        while (usart_read(p_usart, &val));
        *data = (uint8_t)(val & 0xFF);
    }
# endif
# ifdef USART7
    if (USART7 == p_usart) {
        while (usart_read(p_usart, &val));
        *data = (uint8_t)(val & 0xFF);
    }
# endif
#endif /* ifdef USART */
}
References UART0, UART1, UART2, UART3, uart_read(), UNUSED, USART0, USART1, USART2, and usart_read().
Referenced by stdio_serial_init(), and usart_serial_read_packet().
usart_serial_init()
static void usart_serial_init (usart_if p_usart, usart_serial_options_t * opt) inline static
Initializes the Usart in master mode.
Parameters
p_usart Base address of the USART instance.
opt Options needed to set up RS232 communication (see usart_options_t).
Definition at line 87 of file uart_serial.h.
{
#if ((!SAM4L) && (!SAMG55))
    sam_uart_opt_t uart_settings;
    uart_settings.ul_mck = sysclk_get_peripheral_hz();
    uart_settings.ul_baudrate = opt->baudrate;
    uart_settings.ul_mode = opt->paritytype;
#endif
    sam_usart_opt_t usart_settings;
    usart_settings.baudrate = opt->baudrate;
    usart_settings.char_length = opt->charlength;
    usart_settings.parity_type = opt->paritytype;
    usart_settings.stop_bits= opt->stopbits;
    usart_settings.channel_mode= US_MR_CHMODE_NORMAL;
#ifdef UART
    if (UART == (Uart*)p_usart) {
        sysclk_enable_peripheral_clock(ID_UART);
        /* Configure UART */
        uart_init((Uart*)p_usart, &uart_settings);
    }
#else
# ifdef UART0
    if (UART0 == (Uart*)p_usart) {
        sysclk_enable_peripheral_clock(ID_UART0);
        /* Configure UART */
        uart_init((Uart*)p_usart, &uart_settings);
    }
# endif
# ifdef UART1
    if (UART1 == (Uart*)p_usart) {
        sysclk_enable_peripheral_clock(ID_UART1);
        /* Configure UART */
        uart_init((Uart*)p_usart, &uart_settings);
    }
# endif
# ifdef UART2
    if (UART2 == (Uart*)p_usart) {
        sysclk_enable_peripheral_clock(ID_UART2);
        /* Configure UART */
        uart_init((Uart*)p_usart, &uart_settings);
    }
# endif
# ifdef UART3
    if (UART3 == (Uart*)p_usart) {
        sysclk_enable_peripheral_clock(ID_UART3);
        /* Configure UART */
        uart_init((Uart*)p_usart, &uart_settings);
    }
# endif
# ifdef UART4
    if (UART4 == (Uart*)p_usart) {
        sysclk_enable_peripheral_clock(ID_UART4);
        /* Configure UART */
        uart_init((Uart*)p_usart, &uart_settings);
    }
# endif
#endif /* ifdef UART */
#ifdef USART
    if (USART == p_usart) {
#if (!SAM4L)
        sysclk_enable_peripheral_clock(ID_USART);
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_hz());
#endif
#if (SAM4L)
        sysclk_enable_peripheral_clock(p_usart);
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_bus_hz(p_usart));
#endif
        /* Enable the receiver and transmitter. */
        usart_enable_tx(p_usart);
        usart_enable_rx(p_usart);
    }
#else
# ifdef USART0
    if (USART0 == p_usart) {
#if (!SAM4L)
#if (SAMG55)
        flexcom_enable(FLEXCOM0);
        flexcom_set_opmode(FLEXCOM0, FLEXCOM_USART);
#else
        sysclk_enable_peripheral_clock(ID_USART0);
#endif
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_hz());
#endif
#if (SAM4L)
        sysclk_enable_peripheral_clock(p_usart);
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_bus_hz(p_usart));
#endif
        /* Enable the receiver and transmitter. */
        usart_enable_tx(p_usart);
        usart_enable_rx(p_usart);
    }
# endif
# ifdef USART1
    if (USART1 == p_usart) {
#if (!SAM4L)
#if (SAMG55)
        flexcom_enable(FLEXCOM1);
        flexcom_set_opmode(FLEXCOM1, FLEXCOM_USART);
#else
        sysclk_enable_peripheral_clock(ID_USART1);
#endif
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_hz());
#endif
#if (SAM4L)
        sysclk_enable_peripheral_clock(p_usart);
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_bus_hz(p_usart));
#endif
        /* Enable the receiver and transmitter. */
        usart_enable_tx(p_usart);
        usart_enable_rx(p_usart);
    }
# endif
# ifdef USART2
    if (USART2 == p_usart) {
#if (!SAM4L)
#if (SAMG55)
        flexcom_enable(FLEXCOM2);
        flexcom_set_opmode(FLEXCOM2, FLEXCOM_USART);
#else
        sysclk_enable_peripheral_clock(ID_USART2);
#endif
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_hz());
#endif
#if (SAM4L)
        sysclk_enable_peripheral_clock(p_usart);
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_bus_hz(p_usart));
#endif
        /* Enable the receiver and transmitter. */
        usart_enable_tx(p_usart);
        usart_enable_rx(p_usart);
    }
# endif
# ifdef USART3
    if (USART3 == p_usart) {
#if (!SAM4L)
#if (SAMG55)
        flexcom_enable(FLEXCOM3);
        flexcom_set_opmode(FLEXCOM3, FLEXCOM_USART);
#else
        sysclk_enable_peripheral_clock(ID_USART3);
#endif
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_hz());
#endif
#if (SAM4L)
        sysclk_enable_peripheral_clock(p_usart);
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_bus_hz(p_usart));
#endif
        /* Enable the receiver and transmitter. */
        usart_enable_tx(p_usart);
        usart_enable_rx(p_usart);
    }
# endif
# ifdef USART4
    if (USART4 == p_usart) {
#if (!SAM4L)
#if (SAMG55)
        flexcom_enable(FLEXCOM4);
        flexcom_set_opmode(FLEXCOM4, FLEXCOM_USART);
#else
        sysclk_enable_peripheral_clock(ID_USART4);
#endif
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_hz());
#endif
#if (SAM4L)
        sysclk_enable_peripheral_clock(p_usart);
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_bus_hz(p_usart));
#endif
        /* Enable the receiver and transmitter. */
        usart_enable_tx(p_usart);
        usart_enable_rx(p_usart);
    }
# endif
# ifdef USART5
    if (USART5 == p_usart) {
#if (!SAM4L)
#if (SAMG55)
        flexcom_enable(FLEXCOM5);
        flexcom_set_opmode(FLEXCOM5, FLEXCOM_USART);
#else
        sysclk_enable_peripheral_clock(ID_USART5);
#endif
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_hz());
#endif
#if (SAM4L)
        sysclk_enable_peripheral_clock(p_usart);
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_bus_hz(p_usart));
#endif
        /* Enable the receiver and transmitter. */
        usart_enable_tx(p_usart);
        usart_enable_rx(p_usart);
    }
# endif
# ifdef USART6
    if (USART6 == p_usart) {
#if (!SAM4L)
#if (SAMG55)
        flexcom_enable(FLEXCOM6);
        flexcom_set_opmode(FLEXCOM6, FLEXCOM_USART);
#else
        sysclk_enable_peripheral_clock(ID_USART6);
#endif
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_hz());
#endif
#if (SAM4L)
        sysclk_enable_peripheral_clock(p_usart);
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_bus_hz(p_usart));
#endif
        /* Enable the receiver and transmitter. */
        usart_enable_tx(p_usart);
        usart_enable_rx(p_usart);
    }
# endif
# ifdef USART7
    if (USART7 == p_usart) {
#if (!SAM4L)
#if (SAMG55)
        flexcom_enable(FLEXCOM7);
        flexcom_set_opmode(FLEXCOM7, FLEXCOM_USART);
#else
        sysclk_enable_peripheral_clock(ID_USART7);
#endif
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_hz());
#endif
#if (SAM4L)
        sysclk_enable_peripheral_clock(p_usart);
        /* Configure USART */
        usart_init_rs232(p_usart, &usart_settings,
                sysclk_get_peripheral_bus_hz(p_usart));
#endif
        /* Enable the receiver and transmitter. */
        usart_enable_tx(p_usart);
        usart_enable_rx(p_usart);
    }
# endif
#endif /* ifdef USART */
}
References uart_rs232_options::baudrate, sam_usart_opt_t::baudrate, sam_usart_opt_t::channel_mode, sam_usart_opt_t::char_length, uart_rs232_options::charlength, ID_UART0, ID_UART1, ID_UART2, ID_UART3, ID_UART4, ID_USART0, ID_USART1, ID_USART2, sam_usart_opt_t::parity_type, uart_rs232_options::paritytype, sam_usart_opt_t::stop_bits, uart_rs232_options::stopbits, sysclk_enable_peripheral_clock(), sysclk_get_peripheral_bus_hz(), sysclk_get_peripheral_hz(), UART0, UART1, UART2, UART3, UART4, uart_init(), sam_uart_opt::ul_baudrate, sam_uart_opt::ul_mck, sam_uart_opt::ul_mode, US_MR_CHMODE_NORMAL, USART0, USART1, USART2, usart_enable_rx(), usart_enable_tx(), and usart_init_rs232().
Referenced by stdio_serial_init().
usart_serial_is_rx_ready()
static uint32_t usart_serial_is_rx_ready (usart_if p_usart) inline static
Check if Received data is ready.
Parameters
p_usart Base address of the USART instance.
Return values
1 One data has been received.
0 No data has been received.
Definition at line 577 of file uart_serial.h.
{
#ifdef UART
    if (UART == (Uart*)p_usart) {
        return uart_is_rx_ready((Uart*)p_usart);
    }
#else
# ifdef UART0
    if (UART0 == (Uart*)p_usart) {
        return uart_is_rx_ready((Uart*)p_usart);
    }
# endif
# ifdef UART1
    if (UART1 == (Uart*)p_usart) {
        return uart_is_rx_ready((Uart*)p_usart);
    }
# endif
# ifdef UART2
    if (UART2 == (Uart*)p_usart) {
        return uart_is_rx_ready((Uart*)p_usart);
    }
# endif
# ifdef UART3
    if (UART3 == (Uart*)p_usart) {
        return uart_is_rx_ready((Uart*)p_usart);
    }
# endif
#endif /* ifdef UART */
#ifdef USART
    if (USART == p_usart) {
        return usart_is_rx_ready(p_usart);
    }
#else
# ifdef USART0
    if (USART0 == p_usart) {
        return usart_is_rx_ready(p_usart);
    }
# endif
# ifdef USART1
    if (USART1 == p_usart) {
        return usart_is_rx_ready(p_usart);
    }
# endif
# ifdef USART2
    if (USART2 == p_usart) {
        return usart_is_rx_ready(p_usart);
    }
# endif
# ifdef USART3
    if (USART3 == p_usart) {
        return usart_is_rx_ready(p_usart);
    }
# endif
# ifdef USART4
    if (USART4 == p_usart) {
        return usart_is_rx_ready(p_usart);
    }
# endif
# ifdef USART5
    if (USART5 == p_usart) {
        return usart_is_rx_ready(p_usart);
    }
# endif
# ifdef USART6
    if (USART6 == p_usart) {
        return usart_is_rx_ready(p_usart);
    }
# endif
# ifdef USART7
    if (USART7 == p_usart) {
        return usart_is_rx_ready(p_usart);
    }
# endif
#endif /* ifdef USART */
    return 0;
}
References UART0, UART1, UART2, UART3, uart_is_rx_ready(), USART0, USART1, USART2, and usart_is_rx_ready().
usart_serial_putchar()
static int usart_serial_putchar (usart_if p_usart, const uint8_t c) inline static
Sends a character with the USART.
Parameters
p_usart Base address of the USART instance.
c Character to write.
Returns
Status.
Return values
1 The character was written.
0 The function timed out before the USART transmitter became ready to send.
Definition at line 376 of file uart_serial.h.
{
#ifdef UART
    if (UART == (Uart*)p_usart) {
        while (uart_write((Uart*)p_usart, c)!=0);
        return 1;
    }
#else
# ifdef UART0
    if (UART0 == (Uart*)p_usart) {
        while (uart_write((Uart*)p_usart, c)!=0);
        return 1;
    }
# endif
# ifdef UART1
    if (UART1 == (Uart*)p_usart) {
        while (uart_write((Uart*)p_usart, c)!=0);
        return 1;
    }
# endif
# ifdef UART2
    if (UART2 == (Uart*)p_usart) {
        while (uart_write((Uart*)p_usart, c)!=0);
        return 1;
    }
# endif
# ifdef UART3
    if (UART3 == (Uart*)p_usart) {
        while (uart_write((Uart*)p_usart, c)!=0);
        return 1;
    }
# endif
#endif /* ifdef UART */
#ifdef USART
    if (USART == p_usart) {
        while (usart_write(p_usart, c)!=0);
        return 1;
    }
#else
# ifdef USART0
    if (USART0 == p_usart) {
        while (usart_write(p_usart, c)!=0);
        return 1;
    }
# endif
# ifdef USART1
    if (USART1 == p_usart) {
        while (usart_write(p_usart, c)!=0);
        return 1;
    }
# endif
# ifdef USART2
    if (USART2 == p_usart) {
        while (usart_write(p_usart, c)!=0);
        return 1;
    }
# endif
# ifdef USART3
    if (USART3 == p_usart) {
        while (usart_write(p_usart, c)!=0);
        return 1;
    }
# endif
# ifdef USART4
    if (USART4 == p_usart) {
        while (usart_write(p_usart, c)!=0);
        return 1;
    }
# endif
# ifdef USART5
    if (USART5 == p_usart) {
        while (usart_write(p_usart, c)!=0);
        return 1;
    }
# endif
# ifdef USART6
    if (USART6 == p_usart) {
        while (usart_write(p_usart, c)!=0);
        return 1;
    }
# endif
# ifdef USART7
    if (USART7 == p_usart) {
        while (usart_write(p_usart, c)!=0);
        return 1;
    }
# endif
#endif /* ifdef USART */
    return 0;
}
References UART0, UART1, UART2, UART3, uart_write(), USART0, USART1, USART2, and usart_write().
Referenced by stdio_serial_init(), and usart_serial_write_packet().
usart_serial_read_packet()
status_code_t usart_serial_read_packet (usart_if usart, uint8_t * data, size_t len)
Receive a sequence of bytes to a USART device.
Parameters
usart Base address of the USART instance.
data data buffer to write
len Length of data
Receive a sequence of bytes to a USART device.
Parameters
usart Base address of the USART instance.
data Data buffer to write
len Length of data
Definition at line 68 of file usart_serial.c.
{
    while (len) {
        usart_serial_getchar(usart, data);
        len--;
        data++;
    }
    return STATUS_OK;
}
References STATUS_OK, and usart_serial_getchar().
usart_serial_write_packet()
status_code_t usart_serial_write_packet (usart_if usart, const uint8_t * data, size_t len)
Send a sequence of bytes to a USART device.
Parameters
usart Base address of the USART instance.
data data buffer to write
len Length of data
Send a sequence of bytes to a USART device.
Parameters
usart Base address of the USART instance.
data Data buffer to read
len Length of data
Definition at line 48 of file usart_serial.c.
{
    while (len) {
        usart_serial_putchar(usart, *data);
        len--;
        data++;
    }
    return STATUS_OK;
}
References STATUS_OK, and usart_serial_putchar().